import type { CompanyConfig } from "./types";

export const amentumClaimsDbaConfig: CompanyConfig = {
  companyId: "amentum-claims-dba-intelligence",
  displayName: "Amentum Claims, Safety Trend & DBA Intelligence",
  shortName: "Amentum Claims",
  sector:
    "Workers compensation, Defense Base Act claims, SafeUp safety performance, NSC awards, CPAR impact, EMR, FY2025 reserves, TRIR/LWCR trend inference, domestic return-to-work, overseas injury reporting, and claims-administration intelligence",
  headquarters: "Chantilly, Virginia / Chesapeake, Virginia claims operations signal / Fresno-area Occu-Med exam relevance",
  employees: 53000,
  employeesAsOf:
    "Uploaded Amentum trend, 2025 update, workers compensation, DBA, and Occu-Med Fresno context files: FY2022-FY2025 source-specific safety and claims trend intelligence",
  summary:
    "Amentum Claims, Safety Trend & DBA Intelligence captures the workers' compensation, injury-rate, Defense Base Act, claims-administration, insurance-facing, and trend-analysis material from the uploaded Amentum files as a focused intelligence node. The newest uploaded trend files add the actual Occu-Med question: if Occu-Med is doing pre-employment and annual exams for Amentum from Fresno, what can public data say about whether the broader injury/claim trend is improving even when Amentum does not share internal provider-level results? The answer is directionally strong but attribution-limited. Public/source-modeled trend files show TRIR declining from about 0.82 in FY2022 to 0.64 in FY2023 and 0.47 in FY2024, while LWCR declined from about 0.15 to 0.11 to 0.09. Amentum also reported 400+ NSC safety awards in 2025, including 152 Perfect Record programs, 43 Safety Leadership programs, 45 Million Work Hour programs, and 196 Occupational Excellence awards. FY2025 balance-sheet reserves declined from $235M to $159M across current and long-term reserves, a $76M or roughly 32% reduction. None of that proves Occu-Med alone caused the improvement, but it creates a credible value narrative: prevention, surveillance, pre-placement screening, return-to-work documentation, and lost-time prevention are aligned with the direction of Amentum's public safety and claims signals.",
  tags: [
    "Entity profile",
    "Amentum",
    "Workers compensation",
    "DBA claims",
    "Defense Base Act",
    "SafeUp",
    "CPAR",
    "EMR",
    "TRIR trend",
    "LWCR trend",
    "FY2025 reserves",
    "NSC awards",
    "Fresno exams",
    "Return to work",
    "Lost-time prevention",
    "DOL OWCP",
    "Claims administrator",
    "Insurance carrier",
  ],
  aliases: [
    "Amentum Claims",
    "Amentum DBA",
    "Amentum Workers Compensation",
    "Amentum SafeUp",
    "Amentum Holdings Claims",
    "Amentum Injury Trend",
    "Amentum Fresno exams",
  ],
  sourceFilters: {
    sec: { ticker: "AMTM", legalEntities: ["Amentum Holdings, Inc."] },
    sam: { legalNames: ["Amentum", "Amentum Services", "Amentum Holdings"] },
    usaSpending: { recipientNames: ["Amentum"], parentOrgs: ["Amentum Holdings"] },
    newsSources: {
      aliases: [
        "Amentum SafeUp",
        "Amentum workers compensation",
        "Amentum DBA claims",
        "Amentum NSC awards",
        "Amentum TRIR",
        "Amentum FY2025 reserves",
      ],
    },
  },
  executiveSignals: [
    {
      label: "FY2024 TRIR trend",
      value: "0.47",
      note: "Uploaded trend file reconstructs TRIR decline from about 0.82 in FY2022 to 0.64 in FY2023 and 0.47 in FY2024.",
    },
    {
      label: "FY2024 LWCR trend",
      value: "0.09",
      note: "Uploaded trend file reconstructs LWCR decline from about 0.15 in FY2022 to 0.11 in FY2023 and 0.09 in FY2024.",
    },
    {
      label: "2025 NSC awards",
      value: "400+",
      note: "Uploaded 2025 update cites 400+ National Safety Council safety awards, including 152 Perfect Record programs.",
    },
    {
      label: "Reserve decline",
      value: "$76M down",
      note: "Uploaded 2025 update identifies reserves declining from $235M in Sep 2024 to $159M in Oct 2025 across current and long-term categories.",
    },
  ],
  curveTitle: "Amentum safety trend, claims reserves, and Occu-Med value-defense curve",
  curveSubtitle:
    "Uploaded Amentum claims/DBA/trend files normalized into a focused intelligence profile. Some values are reconstructed or source-specific; use as directional account intelligence, not audited proof of provider attribution.",
  chartDefinitions: [
    {
      id: "amentum-trir-lwcr-trend",
      title: "Amentum injury rates declining FY2022-FY2024",
      subtitle: "Uploaded trend analysis: TRIR and LWCR fell roughly 40%+ in two years while industry averages remained much higher.",
      type: "line",
      xKey: "year",
      data: [
        { year: "FY2022 est.", trir: 0.82, lwcr: 0.15, industryTrir: 2.77, industryLwcr: 1.63 },
        { year: "FY2023", trir: 0.64, lwcr: 0.11, industryTrir: 2.77, industryLwcr: 1.63 },
        { year: "FY2024", trir: 0.47, lwcr: 0.09, industryTrir: 2.77, industryLwcr: 1.63 },
      ],
      series: [
        { dataKey: "trir", name: "Amentum TRIR", color: "#22c55e" },
        { dataKey: "lwcr", name: "Amentum LWCR", color: "#22d3ee" },
        { dataKey: "industryTrir", name: "Industry avg TRIR", color: "#ef4444" },
        { dataKey: "industryLwcr", name: "Industry avg LWCR", color: "#a78bfa" },
      ],
      domain: [0, 3],
      headline: "injury trend",
      fullWidth: true,
    },
    {
      id: "amentum-2027-goal-progress",
      title: "Progress toward Amentum's 50% injury-reduction goal",
      subtitle: "Uploaded trend file: using FY2022 baseline, FY2024 TRIR is about 86% of the way to the 2027 50% reduction target, and LWCR is about 80% of the way there.",
      type: "grouped",
      xKey: "metric",
      data: [
        { metric: "TRIR", fy2022: 0.82, target2027: 0.41, fy2024: 0.47 },
        { metric: "LWCR", fy2022: 0.15, target2027: 0.075, fy2024: 0.09 },
      ],
      series: [
        { dataKey: "fy2022", name: "FY2022 baseline", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "fy2024", name: "FY2024 actual", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "target2027", name: "2027 target", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      headline: "goal progress",
    },
    {
      id: "amentum-nsc-award-growth-claims",
      title: "Amentum NSC award growth signal",
      subtitle: "Uploaded 2025 update and trend files: award counts show program-level breadth, not just one good site.",
      type: "grouped",
      xKey: "year",
      data: [
        { year: "2023", perfectRecord: 89, safetyLeadership: 30, millionHours: 37, occupationalExcellence: 0, industryLeader: 6 },
        { year: "2024", perfectRecord: 113, safetyLeadership: 28, millionHours: 40, occupationalExcellence: 0, industryLeader: 6 },
        { year: "2025", perfectRecord: 152, safetyLeadership: 43, millionHours: 45, occupationalExcellence: 196, industryLeader: 10 },
      ],
      series: [
        { dataKey: "perfectRecord", name: "Perfect Record", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "safetyLeadership", name: "Safety Leadership", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "millionHours", name: "Million Hours", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "occupationalExcellence", name: "Occupational Excellence", color: "#a78bfa", radius: [8, 8, 0, 0] },
      ],
      headline: "NSC awards",
      fullWidth: true,
    },
    {
      id: "amentum-reserves-decline",
      title: "FY2025 balance-sheet reserves declined sharply",
      subtitle: "Uploaded 2025 update: reserves decreased from $235M to $159M across current and long-term reserve categories.",
      type: "stacked",
      xKey: "period",
      data: [
        { period: "Sep 2024", current: 50, longTerm: 185 },
        { period: "Oct 2025", current: 46, longTerm: 113 },
      ],
      series: [
        { dataKey: "current", name: "Current reserves", color: "#22d3ee", stackId: "reserves" },
        { dataKey: "longTerm", name: "Long-term reserves", color: "#ef4444", stackId: "reserves", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "reserve trend",
    },
    {
      id: "amentum-occumed-value-levers",
      title: "Occu-Med value levers inside the trend",
      subtitle: "Where pre-employment and annual exam quality plausibly supports lower lost-time, stronger documentation, and claims control.",
      type: "bar",
      xKey: "lever",
      data: [
        { lever: "Pre-employment screens", priority: 10 },
        { lever: "Annual surveillance exams", priority: 9 },
        { lever: "Return-to-work exams", priority: 10 },
        { lever: "Respirator / PFT / audio", priority: 8 },
        { lever: "Objective baseline records", priority: 10 },
        { lever: "Provider network pre-build", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Value-defense priority", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "Occu-Med levers",
    },
    {
      id: "amentum-claims-safety-benchmarks",
      title: "Amentum claims/insurance benchmark lane",
      subtitle: "Separate uploaded claims file benchmark lane: TRIR, DART, and EMR shown against broad industry/baseline values.",
      type: "grouped",
      xKey: "metric",
      data: [
        { metric: "TRIR", amentum: 1.39, industry: 3.2 },
        { metric: "DART", amentum: 0.70, industry: 1.8 },
        { metric: "EMR", amentum: 0.46, industry: 1.0 },
      ],
      series: [
        { dataKey: "amentum", name: "Amentum", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "industry", name: "Industry / baseline", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "claims metrics",
    },
    {
      id: "amentum-dba-carrier-volume",
      title: "DBA carrier market volume context",
      subtitle: "Uploaded file lists total DBA claims by carrier for 2001-2018; this is market context, not Amentum-specific carrier disclosure.",
      type: "bar",
      xKey: "carrier",
      data: [
        { carrier: "AIG / ICSP", claims: 79237 },
        { carrier: "CNA", claims: 13358 },
        { carrier: "Allied World", claims: 12261 },
        { carrier: "ACE / Chubb", claims: 9838 },
        { carrier: "Zurich", claims: 7526 },
        { carrier: "Starr", claims: 2889 },
      ],
      series: [{ dataKey: "claims", name: "DBA claims", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "DBA market",
      fullWidth: true,
    },
    {
      id: "amentum-claims-workflow",
      title: "Amentum DBA / workers' comp workflow signals",
      subtitle: "The uploaded files describe operational claims roles and coordination points that matter for medical documentation quality.",
      type: "bar",
      xKey: "workflow",
      data: [
        { workflow: "Injury reporting", priority: 10 },
        { workflow: "Carrier / TPA coordination", priority: 9 },
        { workflow: "DOL / OWCP reporting", priority: 10 },
        { workflow: "Occupational Health coordination", priority: 9 },
        { workflow: "Legal / HR coordination", priority: 8 },
        { workflow: "Return-to-work", priority: 9 },
        { workflow: "IME / second opinion", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Documentation priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "claims workflow",
    },
  ],
  metricDefinitions: [
    { id: "amentum-trir-fy24", label: "FY2024 TRIR", value: 0.47, unit: "score", category: "safety" },
    { id: "amentum-lwcr-fy24", label: "FY2024 LWCR", value: 0.09, unit: "score", category: "safety" },
    { id: "amentum-trir-decline", label: "FY2022-FY2024 TRIR decline", value: 43, unit: "percent", category: "safety" },
    { id: "amentum-lwcr-decline", label: "FY2022-FY2024 LWCR decline", value: 40, unit: "percent", category: "safety" },
    { id: "amentum-claims-reserve-decline", label: "Reserve decline", value: 76, unit: "usd", category: "financial" },
    { id: "amentum-claims-reserve-decline-percent", label: "Reserve decline percent", value: 32, unit: "percent", category: "financial" },
    { id: "amentum-claims-trir", label: "TRIR benchmark lane", value: 1.39, unit: "score", category: "safety" },
    { id: "amentum-claims-dart", label: "DART benchmark lane", value: 0.70, unit: "score", category: "safety" },
    { id: "amentum-claims-emr", label: "Experience modification rate", value: 0.46, unit: "score", category: "financial" },
    { id: "amentum-claims-cpar", label: "CPAR lift correlation", value: 9, unit: "percent", category: "financial" },
    { id: "amentum-claims-nsc-perfect-2025", label: "2025 NSC Perfect Record awards", value: 152, unit: "count", category: "safety" },
    { id: "amentum-claims-aig-dba", label: "AIG DBA market claims", value: 79237, unit: "count", category: "risk" },
    { id: "amentum-claims-employees", label: "Amentum employees", value: 53000, unit: "count", category: "workforce" },
    { id: "amentum-claims-revenue", label: "FY2025 revenue", value: 14.4, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Lost-time claims", revenue: 200, risk: 9.5, workers: 53000 },
    { name: "DBA deployed workforce", revenue: 250, risk: 10.0, workers: 5000 },
    { name: "Return-to-work delays", revenue: 150, risk: 8.5, workers: 53000 },
    { name: "Carrier/TPA documentation", revenue: 125, risk: 8.0, workers: 53000 },
    { name: "CPAR safety impact", revenue: 300, risk: 9.0, workers: 53000 },
    { name: "Fresno/Central Valley exams", revenue: 175, risk: 8.0, workers: 1000 },
  ],
  opportunityMatrix: [
    { name: "Pre-Employment Value Defense", revenuePotential: 350, implementationComplexity: 5, strategicValue: 10 },
    { name: "Annual Surveillance Trend Support", revenuePotential: 300, implementationComplexity: 5, strategicValue: 9 },
    { name: "DBA Medical Baseline Program", revenuePotential: 300, implementationComplexity: 7, strategicValue: 10 },
    { name: "Return-to-Work Documentation", revenuePotential: 200, implementationComplexity: 5, strategicValue: 9 },
    { name: "Lost-Time Prevention Protocol", revenuePotential: 175, implementationComplexity: 6, strategicValue: 9 },
    { name: "Provider Network Pre-Build", revenuePotential: 150, implementationComplexity: 7, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Claims and trend intelligence node, not a duplicate Amentum profile",
      narrative:
        "This profile isolates the safety trend, workers' compensation, DBA, claims, insurance, and provider-value-defense material from the uploaded Amentum files. It should sit beside the broader Amentum / PAE Legacy profile as a source-specific claims and trend intelligence node.",
      bullets: [
        "The uploaded trend file reconstructs TRIR falling from about 0.82 in FY2022 to 0.47 in FY2024.",
        "LWCR fell from about 0.15 to 0.09 over the same period, which is the lane where pre-employment screening, annual exams, and return-to-work quality matter most.",
        "The uploaded 2025 update does not provide a clean FY2025 TRIR/LWCR figure, but it does provide 2025 award breadth and claims-reserve direction.",
        "The correct claim is aligned contribution, not proof that Occu-Med alone caused the improvement.",
      ],
      metricIds: ["amentum-trir-fy24", "amentum-lwcr-fy24", "amentum-trir-decline", "amentum-lwcr-decline"],
    },
    {
      type: "safety",
      title: "2025 public signals: awards up, reserves down",
      narrative:
        "The 2025 public-data lane does not give a companywide FY2025 TRIR/LWCR number, but it does show a larger safety-award footprint and a material reduction in balance-sheet reserves. Those two signals are directionally consistent with stronger safety performance and lower/faster-resolving claim exposure.",
      bullets: [
        "2025 NSC safety awards exceeded 400 programs, including 152 Perfect Record programs, 43 Safety Leadership programs, 45 Million Work Hour programs, and 196 Occupational Excellence awards.",
        "Current reserves declined from $50M to $46M.",
        "Long-term reserves declined from $185M to $113M.",
        "Total reserves declined from $235M to $159M, a $76M or roughly 32% decline.",
      ],
      metricIds: ["amentum-claims-nsc-perfect-2025", "amentum-claims-reserve-decline", "amentum-claims-reserve-decline-percent"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med value-defense interpretation",
      narrative:
        "From Occu-Med's perspective, the trend file answers the practical question: if Amentum will not share internal provider-level outcomes, public trend data can still support the argument that prevention-focused exams, objective baselines, annual surveillance, and return-to-work documentation are part of the system moving in the right direction.",
      bullets: [
        "Pre-employment screens support early identification of MSK, respiratory, hearing, and fitness-for-duty issues before they become lost-time claims.",
        "Annual exams and surveillance help catch deterioration before it becomes recordable or lost-time.",
        "Return-to-work documentation helps keep LWCR low and protects CPAR-sensitive contract performance.",
        "Objective baseline records are the value-defense asset when Amentum's internal data is not shared externally.",
      ],
      metricIds: ["amentum-claims-cpar", "amentum-claims-emr"],
    },
    {
      type: "medical-opportunities",
      title: "DBA and workers' compensation documentation wedge",
      narrative:
        "The DBA section creates an Occu-Med service wedge: baseline documentation, injury documentation, return-to-work support, and provider coordination before the claim becomes contested.",
      bullets: [
        "DBA applies to civilian contractors working overseas on qualifying U.S. government or military contracts.",
        "The uploaded file describes DBA claims administrators reporting to carriers/TPAs and the Department of Labor while coordinating with Occupational Health, Legal, and HR.",
        "For domestic operations, the file describes workers' compensation case management, return-to-work programs, second opinions, IMEs, and early settlement discussions.",
        "Occu-Med's value is objective medical documentation before and immediately after injury, not after the record becomes messy.",
      ],
      metricIds: ["amentum-claims-aig-dba"],
    },
  ],
};
