import type { CompanyConfig } from "./types";

export const amentumAddendumIntelligenceConfig: CompanyConfig = {
  companyId: "amentum-addendum-intelligence",
  displayName: "Amentum Holdings Addendum Intelligence",
  shortName: "Amentum Addendum",
  sector:
    "Amentum Holdings corporate structure, DOE 10 CFR 851 surveillance, LOGCAP / DOE / aviation / engineering exam populations, NAICS benchmark translation, Jacobs CMS merger, claims-history consolidation, and Occu-Med value-defense messaging",
  headquarters: "Chantilly, Virginia",
  employees: 50000,
  employeesAsOf:
    "Uploaded Amentum Holdings and addendum files: approximately 50,000 employees in 70+ countries, $14.4B FY2025 revenue, and two reportable segments after the Jacobs CMS / Cyber & Intelligence merger",
  summary:
    "Amentum Holdings Addendum Intelligence captures the material that should sit on top of the existing Amentum / PAE and Amentum Claims profiles. The uploaded Amentum Holdings file identifies the current publicly traded parent as Amentum Holdings, Inc. (NYSE: AMTM), formed September 27, 2024 from legacy Amentum and Jacobs Critical Mission Solutions / Cyber & Intelligence. It operates through Digital Solutions and Global Engineering Solutions, with approximately 50,000 employees in 70+ countries and about $14.4B FY2025 revenue. The addendum file adds the actual Occu-Med action layer: Amentum has four distinct exam populations — DOE/environmental remediation, aviation/airfield operations, engineering/technical services, and logistics/base operations — and the DOE/nuclear lane requires DOE 10 CFR 851 occupational medicine fluency, not generic pre-employment physicals. The point is not that Amentum needs a generic company overview. The point is that Occu-Med must defend and expand its value by tying exam quality to DOE 10 CFR 851, NAICS-specific BLS benchmarks, claims reserve improvement, EMR advantage, return-to-work documentation, and the new Jacobs CMS workforce population.",
  tags: [
    "Entity profile",
    "Amentum Holdings",
    "AMTM",
    "Jacobs CMS",
    "Digital Solutions",
    "Global Engineering Solutions",
    "DOE 10 CFR 851",
    "Hanford",
    "Y-12",
    "Pantex",
    "Savannah River Site",
    "China Lake",
    "Point Mugu",
    "NAICS benchmarks",
    "EMR advantage",
    "Occu-Med value defense",
  ],
  aliases: ["Amentum Holdings", "Amentum Holdings Inc.", "AMTM", "Amentum Addendum", "Jacobs CMS Amentum"],
  sourceFilters: {
    sec: { ticker: "AMTM", legalEntities: ["Amentum Holdings, Inc."] },
    sam: { legalNames: ["Amentum", "Amentum Holdings", "Amentum Services"] },
    usaSpending: { recipientNames: ["Amentum"], parentOrgs: ["Amentum Holdings"] },
    newsSources: { aliases: ["Amentum Holdings", "Jacobs CMS merger", "Amentum DOE 10 CFR 851", "Amentum Hanford", "Amentum Y-12 Pantex"] },
  },
  executiveSignals: [
    {
      label: "FY2025 revenue",
      value: "$14.4B",
      note: "Uploaded Amentum Holdings file identifies $14.4B annual revenue for FY2025.",
    },
    {
      label: "Segments",
      value: "DS / GES",
      note: "Amentum Holdings operates through Digital Solutions and Global Engineering Solutions.",
    },
    {
      label: "DOE mandate",
      value: "10 CFR 851",
      note: "DOE covered-workplace medical surveillance is a specialized exam mandate most general occ med providers miss.",
    },
    {
      label: "Jacobs CMS impact",
      value: "+~7K workers",
      note: "The merger added intelligence, cyber, energy/nuclear, and digital-engineering personnel into the Amentum exam population.",
    },
  ],
  curveTitle: "Amentum DOE surveillance, NAICS benchmark, and value-defense addendum curve",
  curveSubtitle:
    "Uploaded Amentum Holdings and addendum files normalized into a source-specific intelligence layer. Values are strategic account intelligence, not audited claims causation proof.",
  chartDefinitions: [
    {
      id: "amentum-exam-populations",
      title: "Amentum exam populations by regulatory / work lane",
      subtitle: "The addendum separates Amentum into four medical populations rather than one generic account.",
      type: "bar",
      xKey: "population",
      data: [
        { population: "DOE / environmental", priority: 10 },
        { population: "Aviation / airfield", priority: 9 },
        { population: "Engineering / technical", priority: 7 },
        { population: "Logistics / BOS", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "exam lanes",
      fullWidth: true,
    },
    {
      id: "amentum-naics-benchmarks",
      title: "Amentum NAICS benchmark translation",
      subtitle: "The addendum maps different Amentum populations to materially different BLS TRIR benchmarks.",
      type: "bar",
      xKey: "businessLine",
      data: [
        { businessLine: "Airfield / aviation support", benchmark: 4.1 },
        { businessLine: "Environmental remediation", benchmark: 2.4 },
        { businessLine: "Logistics / facilities", benchmark: 2.5 },
        { businessLine: "Engineering services", benchmark: 1.25 },
      ],
      series: [{ dataKey: "benchmark", name: "BLS TRIR benchmark", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 5],
      headline: "benchmarks",
    },
    {
      id: "amentum-doe-sites",
      title: "DOE / nuclear surveillance sites named in addendum",
      subtitle: "10 CFR 851 medical surveillance is the highest-specificity account wedge.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "Hanford HITDC", priority: 10 },
        { site: "Y-12 Oak Ridge", priority: 10 },
        { site: "Pantex Amarillo", priority: 10 },
        { site: "Savannah River Site", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Surveillance priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "DOE sites",
    },
    {
      id: "amentum-jacobs-cms-impact",
      title: "Jacobs CMS merger impact on exam population",
      subtitle: "The merger added intelligence, cyber, energy/nuclear, and digital engineering workers into the medical-support universe.",
      type: "bar",
      xKey: "impact",
      data: [
        { impact: "Added workers", value: 7000 },
        { impact: "Combined backlog $B", value: 47 },
        { impact: "FY2025 revenue $B", value: 14.4 },
        { impact: "Rapid Solutions divestiture $M", value: 360 },
      ],
      series: [{ dataKey: "value", name: "Value", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "merger impact",
      fullWidth: true,
    },
    {
      id: "amentum-occumed-value-defense",
      title: "Occu-Med value-defense points",
      subtitle: "The right message is not 'you need help'; it is 'protect the exceptional EMR and safety advantage already built.'",
      type: "bar",
      xKey: "message",
      data: [
        { message: "Protect EMR 0.46 advantage", priority: 10 },
        { message: "DOE 10 CFR 851 fluency", priority: 10 },
        { message: "RTW documentation", priority: 9 },
        { message: "Hazard-based surveillance", priority: 10 },
        { message: "Jacobs CMS onboarding", priority: 8 },
        { message: "NAICS benchmark proof", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Message strength", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "value defense",
    },
  ],
  metricDefinitions: [
    { id: "amentum-addendum-employees", label: "Employees", value: 50000, unit: "count", category: "workforce" },
    { id: "amentum-addendum-revenue", label: "FY2025 revenue", value: 14.4, unit: "usd", category: "financial" },
    { id: "amentum-addendum-backlog", label: "Combined backlog", value: 47, unit: "usd", category: "financial" },
    { id: "amentum-addendum-jacobs-workers", label: "Jacobs CMS employees added", value: 7000, unit: "count", category: "workforce" },
    { id: "amentum-addendum-emr", label: "EMR advantage", value: 0.46, unit: "score", category: "safety" },
    { id: "amentum-addendum-doe-sites", label: "DOE/nuclear priority sites", value: 4, unit: "count", category: "risk" },
  ],
  riskMatrix: [
    { name: "DOE / nuclear 10 CFR 851", revenue: 10, risk: 10.0, workers: 4000 },
    { name: "Aviation / airfield", revenue: 9, risk: 8.5, workers: 2500 },
    { name: "Logistics / BOS", revenue: 9, risk: 8.5, workers: 8000 },
    { name: "Engineering / cyber / IC", revenue: 7, risk: 5.5, workers: 7000 },
    { name: "Claims / RTW documentation", revenue: 9, risk: 9.0, workers: 50000 },
  ],
  opportunityMatrix: [
    { name: "DOE 10 CFR 851 Surveillance", revenuePotential: 900, implementationComplexity: 8, strategicValue: 10 },
    { name: "Aviation / Airfield Support Exams", revenuePotential: 350, implementationComplexity: 6, strategicValue: 9 },
    { name: "Jacobs CMS Onboarding Baselines", revenuePotential: 500, implementationComplexity: 7, strategicValue: 9 },
    { name: "RTW / Five-Day Absence Protocol", revenuePotential: 300, implementationComplexity: 5, strategicValue: 9 },
    { name: "NAICS Benchmark Account Defense", revenuePotential: 200, implementationComplexity: 4, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Lead with numbers, not company background",
      narrative:
        "This addendum exists because the Amentum report standard is the right standard: start with TRIR, EMR, reserves, exam populations, and dollars. Company background only matters if it explains the medical opportunity.",
      bullets: [
        "Amentum Holdings is now the publicly traded parent formed from legacy Amentum and Jacobs CMS / Cyber & Intelligence.",
        "The action point is the changed exam population, not the corporate history itself.",
        "Digital Solutions and Global Engineering Solutions create different medical risk lanes.",
      ],
      metricIds: ["amentum-addendum-employees", "amentum-addendum-revenue", "amentum-addendum-backlog"],
    },
    {
      type: "safety",
      title: "DOE 10 CFR 851 is the specialized wedge",
      narrative:
        "For DOE covered workplaces, the occupational medicine program is not a generic annual physical. It includes placement evaluations, hazard-based monitoring, fitness-for-duty, diagnostic exams, five-day absence notification, return-to-work monitoring, written restrictions, and principal morbidity prevention.",
      bullets: [
        "Hanford, Y-12, Pantex, and Savannah River Site are the key Amentum DOE/nuclear signals.",
        "DOE 10 CFR 851 creates higher-complexity, higher-value medical surveillance than standard pre-employment exams.",
        "Occu-Med should treat 10 CFR 851 fluency as an account-defense and expansion product.",
      ],
      metricIds: ["amentum-addendum-doe-sites"],
    },
    {
      type: "medical-opportunities",
      title: "The sales message",
      narrative:
        "The correct pitch is: Amentum has built an exceptional safety/EMR advantage. Occu-Med's value is protecting that advantage with higher-quality DOE surveillance, RTW documentation, NAICS-specific benchmarking, and onboarding support for new CMS/C&I populations.",
      bullets: [
        "Do not say Amentum is unsafe; say their performance is exceptional and must be protected.",
        "Use DOE 10 CFR 851, NAICS benchmarks, claims reserve improvement, and EMR as the proof language.",
        "The new Jacobs CMS workers change the medical-support population and should be explicitly surfaced.",
      ],
      metricIds: ["amentum-addendum-emr", "amentum-addendum-jacobs-workers"],
    },
  ],
};
