import type { CompanyConfig } from "./types";

export const amentumClaimsDbaConfig: CompanyConfig = {
  companyId: "amentum-claims-dba-intelligence",
  displayName: "Amentum Claims & DBA Intelligence",
  shortName: "Amentum Claims",
  sector:
    "Workers compensation, Defense Base Act claims, SafeUp safety performance, NSC awards, CPAR impact, EMR, domestic return-to-work, overseas injury reporting, and claims-administration intelligence",
  headquarters: "Chantilly, Virginia / Chesapeake, Virginia claims operations signal",
  employees: 50000,
  employeesAsOf: "Uploaded Amentum workers compensation / DBA intelligence files: Amentum Holdings profile and claims operation notes",
  summary:
    "Amentum Claims & DBA Intelligence captures the workers' compensation, injury-rate, Defense Base Act, claims-administration, and insurance-facing material from the uploaded Amentum files as a focused intelligence node. The uploaded analysis says Amentum reports materially better safety metrics than broad industry averages in one source lane: TRIR 1.39 vs 3.2, DART 0.70 vs 1.8, and EMR 0.46 vs a 1.0 baseline. It also says Amentum's SafeUp program is positioned as a competitive weapon because fewer recordables correlate with higher CPAR scores, and lost-workday cases hurt CPARs fastest. The DBA section identifies overseas injury reporting, carrier/TPA coordination, Department of Labor reporting, and dedicated DBA claims roles as operational signals. This profile should be read as claims/insurance intelligence, not a replacement for the broader Amentum / PAE Legacy entity profile.",
  tags: [
    "Entity profile",
    "Amentum",
    "Workers compensation",
    "DBA claims",
    "Defense Base Act",
    "SafeUp",
    "CPAR",
    "EMR",
    "Return to work",
    "DOL OWCP",
    "Claims administrator",
    "NSC awards",
    "Insurance carrier",
  ],
  aliases: ["Amentum Claims", "Amentum DBA", "Amentum Workers Compensation", "Amentum SafeUp", "Amentum Holdings Claims"],
  sourceFilters: {
    sec: { ticker: "AMTM", legalEntities: ["Amentum Holdings, Inc."] },
    sam: { legalNames: ["Amentum", "Amentum Services", "Amentum Holdings"] },
    usaSpending: { recipientNames: ["Amentum"], parentOrgs: ["Amentum Holdings"] },
    newsSources: { aliases: ["Amentum SafeUp", "Amentum workers compensation", "Amentum DBA claims", "Amentum NSC awards"] },
  },
  executiveSignals: [
    { label: "TRIR lane", value: "1.39", note: "Uploaded claims file cites Amentum TRIR of 1.39 versus 3.2 industry average in one source lane." },
    { label: "DART lane", value: "0.70", note: "Uploaded file cites DART rate of 0.70 versus 1.8 industry average." },
    { label: "EMR", value: "0.46", note: "Uploaded file treats this as a 54% workers' compensation premium discount signal versus a 1.0 baseline." },
    { label: "CPAR lift", value: "+9%", note: "SafeUp study summary says projects with fewer recordables scored about 9% higher on CPARs." },
  ],
  curveTitle: "Amentum workers' compensation, DBA, and claims-control curve",
  curveSubtitle:
    "Uploaded Amentum claims/DBA files normalized into a focused intelligence profile. Some safety values differ from other Amentum source lanes; treat this as a source-specific claims/insurance profile and verify before external use.",
  chartDefinitions: [
    {
      id: "amentum-claims-safety-benchmarks",
      title: "Amentum safety metrics vs industry averages",
      subtitle: "Claims file benchmark lane: TRIR, DART, and EMR shown against broad industry/baseline values.",
      type: "grouped",
      xKey: "metric",
      data: [
        { metric: "TRIR", amentum: 1.39, industry: 3.2 },
        { metric: "DART", amentum: 0.70, industry: 1.8 },
        { metric: "EMR", amentum: 0.46, industry: 1.0 },
      ],
      series: [
        { dataKey: "amentum", name: "Amentum", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "industry", name: "Industry / baseline", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "claims metrics",
      fullWidth: true,
    },
    {
      id: "amentum-nsc-award-growth-claims",
      title: "Amentum NSC award growth signal",
      subtitle: "Uploaded claims file: Perfect Record, Million Work Hour, Safety Leadership, Superior Safety, and Industry Leader counts by year.",
      type: "grouped",
      xKey: "year",
      data: [
        { year: "2023", perfectRecord: 89, safetyLeadership: 30, millionHours: 37, superiorSafety: 10, industryLeader: 6 },
        { year: "2024", perfectRecord: 113, safetyLeadership: 28, millionHours: 40, superiorSafety: 8, industryLeader: 6 },
        { year: "2025", perfectRecord: 152, safetyLeadership: 43, millionHours: 45, superiorSafety: 9, industryLeader: 10 },
      ],
      series: [
        { dataKey: "perfectRecord", name: "Perfect Record", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "safetyLeadership", name: "Safety Leadership", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "millionHours", name: "Million Hours", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "industryLeader", name: "Industry Leader", color: "#a78bfa", radius: [8, 8, 0, 0] },
      ],
      headline: "NSC awards",
    },
    {
      id: "amentum-dba-carrier-volume",
      title: "DBA carrier market volume context",
      subtitle: "Uploaded file lists total DBA claims by carrier for 2001-2018; this is market context, not Amentum-specific carrier disclosure.",
      type: "bar",
      xKey: "carrier",
      data: [
        { carrier: "AIG / ICSP", claims: 79237 },
        { carrier: "CNA", claims: 13358 },
        { carrier: "Allied World", claims: 12261 },
        { carrier: "ACE / Chubb", claims: 9838 },
        { carrier: "Zurich", claims: 7526 },
        { carrier: "Starr", claims: 2889 },
      ],
      series: [{ dataKey: "claims", name: "DBA claims", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "DBA market",
      fullWidth: true,
    },
    {
      id: "amentum-claims-workflow",
      title: "Amentum DBA / workers' comp workflow signals",
      subtitle: "The uploaded files describe operational claims roles and coordination points that matter for medical documentation quality.",
      type: "bar",
      xKey: "workflow",
      data: [
        { workflow: "Injury reporting", priority: 10 },
        { workflow: "Carrier / TPA coordination", priority: 9 },
        { workflow: "DOL / OWCP reporting", priority: 10 },
        { workflow: "Occupational Health coordination", priority: 9 },
        { workflow: "Legal / HR coordination", priority: 8 },
        { workflow: "Return-to-work", priority: 9 },
        { workflow: "IME / second opinion", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Documentation priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "claims workflow",
    },
    {
      id: "amentum-occumed-claims-wedge",
      title: "Occu-Med claims-control service wedge",
      subtitle: "Where medical documentation quality can support claims defense, return-to-work, DBA readiness, and safety-performance preservation.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "Pre-deployment baseline", priority: 10 },
        { lane: "DBA injury documentation", priority: 10 },
        { lane: "Return-to-work exams", priority: 9 },
        { lane: "Lost-time prevention", priority: 9 },
        { lane: "Provider network pre-build", priority: 8 },
        { lane: "Objective functional baseline", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "service wedge",
    },
  ],
  metricDefinitions: [
    { id: "amentum-claims-trir", label: "TRIR benchmark lane", value: 1.39, unit: "score", category: "safety" },
    { id: "amentum-claims-dart", label: "DART benchmark lane", value: 0.70, unit: "score", category: "safety" },
    { id: "amentum-claims-emr", label: "Experience modification rate", value: 0.46, unit: "score", category: "financial" },
    { id: "amentum-claims-cpar", label: "CPAR lift correlation", value: 9, unit: "percent", category: "financial" },
    { id: "amentum-claims-nsc-perfect-2025", label: "2025 NSC Perfect Record awards", value: 152, unit: "count", category: "safety" },
    { id: "amentum-claims-aig-dba", label: "AIG DBA market claims", value: 79237, unit: "count", category: "risk" },
    { id: "amentum-claims-employees", label: "Amentum employees", value: 50000, unit: "count", category: "workforce" },
    { id: "amentum-claims-revenue", label: "FY2025 revenue", value: 14.4, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "DBA deployed workforce", revenue: 250, risk: 10.0, workers: 5000 },
    { name: "Lost-time claims", revenue: 200, risk: 9.5, workers: 50000 },
    { name: "Return-to-work delays", revenue: 150, risk: 8.5, workers: 50000 },
    { name: "Carrier/TPA documentation", revenue: 125, risk: 8.0, workers: 50000 },
    { name: "CPAR safety impact", revenue: 300, risk: 9.0, workers: 50000 },
  ],
  opportunityMatrix: [
    { name: "DBA Medical Baseline Program", revenuePotential: 300, implementationComplexity: 7, strategicValue: 10 },
    { name: "Return-to-Work Documentation", revenuePotential: 200, implementationComplexity: 5, strategicValue: 9 },
    { name: "Lost-Time Prevention Protocol", revenuePotential: 175, implementationComplexity: 6, strategicValue: 9 },
    { name: "Provider Network Pre-Build", revenuePotential: 150, implementationComplexity: 7, strategicValue: 8 },
    { name: "Claims Documentation Audit", revenuePotential: 125, implementationComplexity: 6, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Claims intelligence node, not a duplicate Amentum profile",
      narrative:
        "This profile isolates the workers' compensation, DBA, claims, and insurance material from the uploaded Amentum files. It should sit beside the broader Amentum / PAE Legacy profile as a source-specific claims intelligence node.",
      bullets: [
        "The uploaded files cite TRIR 1.39, DART 0.70, and EMR 0.46 as a claims/insurance benchmark lane.",
        "Amentum's broader entity profile still contains other safety trend and PAE acquisition data.",
        "The key business insight is that safety performance affects CPARs, recompetes, claims costs, and insurance posture.",
      ],
      metricIds: ["amentum-claims-trir", "amentum-claims-dart", "amentum-claims-emr"],
    },
    {
      type: "safety",
      title: "SafeUp and CPAR business logic",
      narrative:
        "The uploaded file says Amentum treats safety performance as a competitive business weapon, not merely a compliance checkbox. Fewer recordables and fewer lost-workday cases protect government performance ratings.",
      bullets: [
        "Projects with fewer recordable incidents scored about 9% higher on CPARs in the file's SafeUp summary.",
        "Lost-workday cases are described as hurting CPAR scores fastest and hardest.",
        "NSC award counts grew substantially from 2023 to 2025, including Perfect Record awards rising from 89 to 152 programs.",
      ],
      metricIds: ["amentum-claims-cpar", "amentum-claims-nsc-perfect-2025"],
    },
    {
      type: "medical-opportunities",
      title: "DBA and workers' compensation documentation wedge",
      narrative:
        "The DBA section creates an Occu-Med service wedge: baseline documentation, injury documentation, return-to-work support, and provider coordination before the claim becomes contested.",
      bullets: [
        "DBA applies to civilian contractors working overseas on qualifying U.S. government or military contracts.",
        "The uploaded file describes DBA claims administrators reporting to carriers/TPAs and the Department of Labor while coordinating with Occupational Health, Legal, and HR.",
        "For domestic operations, the file describes workers' compensation case management, return-to-work programs, second opinions, IMEs, and early settlement discussions.",
        "Occu-Med's value is objective medical documentation before and immediately after injury, not after the record becomes messy.",
      ],
      metricIds: ["amentum-claims-aig-dba"],
    },
  ],
};
