import type { CompanyConfig } from "./types";

export const asrcFederalConfig: CompanyConfig = {
  companyId: "asrc-federal",
  displayName: "ASRC Federal Holding Company",
  shortName: "ASRC Federal",
  sector:
    "Federal services, IT modernization, cybersecurity, engineering, aerospace research, logistics and supply chain, base operations support, DLA/NASA/DoD mission support, Navy depot supply chain, and California aerospace/readiness operations",
  headquarters: "Reston, Virginia",
  employees: 8500,
  employeesAsOf:
    "Uploaded ASRC Federal global operations research: workforce estimate retained pending verified roster, with 240 SAIC logistics employees and nearly 600 Broadleaf employees added in 2023 acquisitions",
  summary:
    "ASRC Federal is the federal government services subsidiary of Arctic Slope Regional Corporation. The uploaded ASRC Federal global operations research replaces the old pending stub with a real profile: ASRC Federal is a holding-company-style federal integrator with subsidiaries across system solutions, data solutions, field services, professional services, aerospace, missile defense, Navy mission systems, cyber, cloud migration, and logistics. It is headquartered in Reston, Virginia, with important facilities and innovation hubs in Beltsville, Huntsville, Cocoa, Moorestown, Neptune, and McLean. The report emphasizes ASRC Federal's 2023 acquisition of SAIC's logistics and supply-chain management business for $350M, adding roughly 240 employees and deepening DLA/Army/Navy/Air Force supply-chain penetration, plus Broadleaf, Inc., adding nearly 600 employees and cyber/cloud/network engineering capabilities. For Occu-Med, the strongest practical angle is not a generic IT profile; it is the mixed operational footprint: California aerospace and readiness sites, Edwards AFB rocket test facilities, NASA Ames/Moffett Field, Fresno Air National Guard Base / 144th Fighter Wing readiness support, Beale AFB, Camp Pendleton, DLA logistics, Navy depot supply chain, and technical field services.",
  tags: [
    "Entity profile",
    "ASRC Federal",
    "Federal services",
    "DLA logistics",
    "SAIC logistics acquisition",
    "Broadleaf acquisition",
    "Cybersecurity",
    "NASA Ames",
    "Edwards AFB",
    "Fresno Air National Guard Base",
    "144th Fighter Wing",
    "Beale AFB",
    "Camp Pendleton",
    "Navy IPV Gen IV",
    "OASIS+",
  ],
  aliases: [
    "ASRC Federal",
    "ASRC Federal Holding Company",
    "ASRC Federal System Solutions",
    "ASRC Federal Data Solutions",
    "ASRC Federal Field Services",
    "ASRC Federal Facilities Logistics",
    "Broadleaf",
    "Broadleaf Inc.",
  ],
  sourceFilters: {
    sam: {
      legalNames: [
        "ASRC Federal",
        "ASRC Federal Holding Company",
        "ASRC Federal System Solutions",
        "ASRC Federal Data Solutions",
        "ASRC Federal Field Services",
        "ASRC Federal Facilities Logistics",
      ],
    },
    usaSpending: { recipientNames: ["ASRC Federal", "ASRC Federal Holding", "ASRC Federal Facilities Logistics"] },
    jobSources: { linkedin: "asrc-federal", careerSite: "https://www.asrcfederal.com/careers/" },
    newsSources: { aliases: ["ASRC Federal", "ASRC Federal SAIC logistics acquisition", "ASRC Federal Broadleaf", "Navy IPV Gen IV"] },
  },
  executiveSignals: [
    { label: "Structure", value: "Federal services", note: "Uploaded report frames ASRC Federal as a holding-company-style federal services integrator." },
    { label: "SAIC logistics deal", value: "$350M", note: "May 2023 acquisition of SAIC logistics and supply-chain management business added about 240 employees." },
    { label: "Broadleaf acquisition", value: "~600 workers", note: "Broadleaf acquisition added cybersecurity, network engineering, cloud migration, APG, NAVSEA, NAVWAR, and DCSA relationships." },
    { label: "California signal", value: "5 sites", note: "Uploaded California table highlights Edwards AFB, NASA Ames/Moffett Field, Fresno ANG Base, Beale AFB, and Camp Pendleton." },
  ],
  curveTitle: "ASRC Federal logistics-acquisition, California operations, and mission-support curve",
  curveSubtitle:
    "Uploaded ASRC Federal global operations reports normalized into an entity profile. Workforce and site-specific medical demand should be validated against current task-order staffing before outreach.",
  chartDefinitions: [
    {
      id: "asrc-regional-hubs",
      title: "ASRC Federal headquarters and regional innovation hubs",
      subtitle: "Uploaded report lists Reston HQ plus Beltsville, Huntsville, Cocoa, Moorestown, Neptune, and McLean technical hubs.",
      type: "bar",
      xKey: "hub",
      data: [
        { hub: "Reston VA", priority: 9 },
        { hub: "Beltsville MD", priority: 10 },
        { hub: "Huntsville AL", priority: 9 },
        { hub: "Cocoa FL", priority: 8 },
        { hub: "Moorestown NJ", priority: 8 },
        { hub: "Neptune NJ", priority: 7 },
        { hub: "McLean VA", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Operational priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "hub map",
      fullWidth: true,
    },
    {
      id: "asrc-acquisition-impact",
      title: "2023 acquisition impact",
      subtitle: "SAIC logistics and Broadleaf acquisitions moved ASRC Federal deeper into DLA logistics, cyber, cloud, APG, NAVSEA, NAVWAR, and DCSA lanes.",
      type: "bar",
      xKey: "acquisition",
      data: [
        { acquisition: "SAIC logistics", workers: 240, dealValue: 350 },
        { acquisition: "Broadleaf", workers: 600, dealValue: 0 },
      ],
      series: [{ dataKey: "workers", name: "Workers added", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "acquisition growth",
    },
    {
      id: "asrc-california-footprint",
      title: "ASRC Federal California mission footprint",
      subtitle: "The uploaded report specifically flags California as relevant to aerospace, readiness, logistics, and infrastructure-support operations.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "Edwards AFB", priority: 10 },
        { site: "NASA Ames / Moffett", priority: 9 },
        { site: "Fresno ANG Base", priority: 10 },
        { site: "Beale AFB", priority: 8 },
        { site: "Camp Pendleton", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med / network priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "California sites",
      fullWidth: true,
    },
    {
      id: "asrc-contract-vehicles",
      title: "ASRC Federal contract-vehicle reach",
      subtitle: "Uploaded report highlights OASIS+, STARS III, SeaPort NxG, ASTRO, RS3, and Navy IPV Gen IV.",
      type: "bar",
      xKey: "vehicle",
      data: [
        { vehicle: "OASIS+ unrestricted", priority: 10 },
        { vehicle: "OASIS+ small business", priority: 9 },
        { vehicle: "GSA 8(a) STARS III", priority: 8 },
        { vehicle: "SeaPort NxG", priority: 8 },
        { vehicle: "ASTRO", priority: 8 },
        { vehicle: "RS3", priority: 7 },
        { vehicle: "Navy IPV Gen IV", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Contract reach", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "contract vehicles",
    },
    {
      id: "asrc-occumed-wedges",
      title: "ASRC Federal Occu-Med service wedges",
      subtitle: "The profile is mixed: IT/cyber employees plus aerospace test, logistics, base support, depot supply chain, and California readiness support.",
      type: "bar",
      xKey: "wedge",
      data: [
        { wedge: "Aerospace/test readiness", priority: 10 },
        { wedge: "Logistics/BOS exams", priority: 9 },
        { wedge: "Fresno ANG network", priority: 10 },
        { wedge: "Depot/warehouse surveillance", priority: 8 },
        { wedge: "Cyber/IT ergonomics", priority: 5 },
        { wedge: "Provider network pre-build", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med fit", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "medical wedge",
    },
  ],
  metricDefinitions: [
    { id: "asrc-saic-deal", label: "SAIC logistics acquisition", value: 350, unit: "usd", category: "financial" },
    { id: "asrc-saic-workers", label: "SAIC employees added", value: 240, unit: "count", category: "workforce" },
    { id: "asrc-broadleaf-workers", label: "Broadleaf employees added", value: 600, unit: "count", category: "workforce" },
    { id: "asrc-california-sites", label: "California mission sites", value: 5, unit: "count", category: "workforce" },
    { id: "asrc-navy-ipv", label: "Navy IPV Gen IV", value: 500, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "California aerospace/test", revenue: 250, risk: 8.5, workers: 800 },
    { name: "Logistics / BOS", revenue: 350, risk: 8.0, workers: 1200 },
    { name: "Navy depot supply chain", revenue: 500, risk: 7.5, workers: 700 },
    { name: "Cyber/cloud/IT", revenue: 200, risk: 4.0, workers: 1600 },
    { name: "Fresno ANG support", revenue: 100, risk: 7.5, workers: 200 },
  ],
  opportunityMatrix: [
    { name: "Fresno ANG / Central Valley Network", revenuePotential: 125, implementationComplexity: 4, strategicValue: 10 },
    { name: "Aerospace Test Support Exams", revenuePotential: 200, implementationComplexity: 6, strategicValue: 9 },
    { name: "Logistics / Warehouse / BOS Medicals", revenuePotential: 250, implementationComplexity: 5, strategicValue: 9 },
    { name: "Depot Supply Chain Surveillance", revenuePotential: 180, implementationComplexity: 6, strategicValue: 8 },
    { name: "IT/Cyber Ergonomics & Visual Strain", revenuePotential: 90, implementationComplexity: 4, strategicValue: 6 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "ASRC Federal is not just another IT modernization contractor. The uploaded report frames it as a federal services integrator with acquisition-driven scale, logistics depth, and geographically distributed technical operations.",
      bullets: [
        "Headquartered at 11091 Sunset Hills Road, Suite 800 in Reston, Virginia, according to the uploaded hub table.",
        "Key hubs include Beltsville, Huntsville, Cocoa, Moorestown, Neptune, and McLean.",
        "The company has matured beyond set-aside work into unrestricted GWAC and large IDIQ competition.",
      ],
      metricIds: ["asrc-saic-deal", "asrc-broadleaf-workers"],
    },
    {
      type: "contracts",
      title: "Acquisition and contract-vehicle strategy",
      narrative:
        "The uploaded report says ASRC Federal's 2023 acquisitions were designed to move the company deeper into high-value logistics, cyber, cloud, network engineering, and large-scale mission-support vehicles.",
      bullets: [
        "SAIC logistics and supply-chain business acquired for $350M in cash, adding about 240 employees and DLA supply-chain depth.",
        "Broadleaf acquisition added nearly 600 employees and expanded APG, NAVSEA, NAVWAR, and DCSA relationships.",
        "OASIS+ positions span unrestricted and small-business tracks.",
        "Navy IPV Gen IV is valued up to $500M for supply-chain management at Fleet Readiness Centers and satellite locations.",
      ],
      metricIds: ["asrc-saic-workers", "asrc-navy-ipv"],
    },
    {
      type: "locations",
      title: "California and Fresno relevance",
      narrative:
        "For Occu-Med, the strongest new value in this ASRC report is the California footprint. The uploaded report explicitly names Edwards AFB, NASA Ames/Moffett Field, Fresno Air National Guard Base, Beale AFB, and Camp Pendleton as mission-relevant sites.",
      bullets: [
        "Edwards AFB: rocket propulsion research and RF&ESS engineering/test-stand modification support.",
        "NASA Ames/Moffett Field: ACITS consolidated IT and spectrum research support.",
        "Fresno Air National Guard Base: 144th Fighter Wing readiness, base operations, logistics, and procurement support.",
        "Beale AFB and Camp Pendleton add ISR, logistics, infrastructure, supply-chain, and warehousing relevance.",
      ],
      metricIds: ["asrc-california-sites"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The ASRC opportunity should not be reduced to office ergonomics. The practical medical lanes are logistics/BOS physicals, aerospace/test support readiness, depot/warehouse surveillance, Fresno/Central Valley network buildout, and provider coverage around California mission sites.",
      bullets: [
        "Fresno ANG / 144th Fighter Wing support creates a direct Central Valley relevance point.",
        "Logistics and supply-chain work supports DOT, hearing, respirator, fit-for-duty, forklift/warehouse, and injury-management lanes.",
        "Aerospace test and readiness support at Edwards and NASA Ames requires higher-specificity provider coverage than generic office work.",
      ],
      metricIds: [],
    },
  ],
};
