import type { CompanyConfig } from "./types";

export const c3elConfig: CompanyConfig = {
  companyId: "cel",
  displayName: "Command Control Communications Engineering & Logistics, LLC (C3EL)",
  shortName: "C3EL",
  sector:
    "Command, control, communications, engineering, logistics, AV integration, secure operations-center design, deployable tactical C2 systems, JADC2 infrastructure, network integration, Tampa defense nexus, and mission-partner communications support",
  headquarters: "Tampa, Florida / Westshore District near Tampa International Airport",
  employees: 400,
  employeesAsOf:
    "Uploaded C3EL Global Operations and Presence report: prior placeholder workforce retained pending verified roster; profile upgraded from generic CEL stub to C3EL-specific operational intelligence",
  summary:
    "C3EL is modeled as Command Control Communications Engineering & Logistics, LLC, a Woman-Owned Small Business that designs and delivers command, control, audiovisual, communications, and integration systems for defense and federal mission partners. The uploaded report corrects the old generic CEL placeholder by tying C3EL to the Tampa/Westshore defense nexus near MacDill AFB, USCENTCOM, USSOCOM, and JCSE. C3EL relocated its headquarters and integration center to the Westshore District in 2024 and operates a 10,000-square-foot integration facility and Emerging Technology Center used to stage and test complex architectures before global deployment. Its D-TACCS deployable tactical command-and-control system supports 24/7 Joint Operations Centers, Tactical Operations Centers, and Emergency Operations Centers in demanding or austere environments. For Occu-Med, C3EL is not a volume account; it is a specialized C2 integration account where field engineering, rack-and-stack AV work, deployment support, travel readiness, ergonomic load, visual strain, hearing/noise, and OCONUS/field-service baseline logic matter.",
  tags: [
    "Entity profile",
    "C3EL",
    "Command and Control",
    "C2 integration",
    "JADC2",
    "D-TACCS",
    "Tampa defense nexus",
    "Westshore District",
    "MacDill AFB",
    "USCENTCOM",
    "USSOCOM",
    "JCSE",
    "Emerging Technology Center",
    "Integration facility",
    "WOSB",
  ],
  aliases: [
    "C3EL",
    "Command Control Communications Engineering & Logistics",
    "Command Control Communications Engineering and Logistics",
    "Command Control Communications Engineering & Logistics, LLC",
    "CEL",
  ],
  sourceFilters: {
    sam: { legalNames: ["Command Control Communications Engineering & Logistics", "C3EL"] },
    usaSpending: { recipientNames: ["Command Control Communications Engineering & Logistics", "C3EL"] },
    jobSources: { linkedin: "c3el", careerSite: "https://www.c3el.com/careers" },
    newsSources: {
      aliases: ["C3EL", "D-TACCS", "Command Control Communications Engineering & Logistics", "Tampa Westshore C3EL"],
    },
  },
  executiveSignals: [
    {
      label: "Strategic hub",
      value: "Tampa / Westshore",
      note: "Uploaded report says C3EL relocated HQ/integration center near Tampa International Airport in 2024.",
    },
    {
      label: "Facility signal",
      value: "10K sq. ft.",
      note: "Uploaded table lists a 10,000-square-foot integration facility and Emerging Technology Center.",
    },
    {
      label: "C2 product",
      value: "D-TACCS",
      note: "Deployable Tactical Command & Control System for 24/7 JOC/TOC/EOC environments.",
    },
    {
      label: "Customer proximity",
      value: "CENTCOM / SOCOM",
      note: "Tampa positioning aligns with MacDill AFB, USCENTCOM, USSOCOM, and JCSE mission partners.",
    },
  ],
  curveTitle: "C3EL Tampa C2 integration, deployable command center, and field-support curve",
  curveSubtitle:
    "Uploaded C3EL global operations report normalized into an entity profile. Workforce size and medical demand should be validated against actual C3EL staffing and deployment patterns.",
  chartDefinitions: [
    {
      id: "c3el-tampa-defense-nexus",
      title: "Tampa defense nexus positioning",
      subtitle: "The uploaded report frames Westshore/MacDill proximity as the strategic reason for C3EL and peer clustering.",
      type: "bar",
      xKey: "organization",
      data: [
        { organization: "C3EL", proximity: 10 },
        { organization: "Trace Systems", proximity: 10 },
        { organization: "SkyBridge Tactical", proximity: 8 },
        { organization: "SOSi MacDill hub", proximity: 7 },
      ],
      series: [{ dataKey: "proximity", name: "Strategic proximity", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "Tampa nexus",
      fullWidth: true,
    },
    {
      id: "c3el-c2-integration-lanes",
      title: "C3EL C2 integration lanes",
      subtitle: "Command-center integration is data distribution, latency management, secure access, AV, and communications architecture — not display-wall installation alone.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "AV/video walls", priority: 9 },
        { lane: "Secure C2 networks", priority: 10 },
        { lane: "Data distribution", priority: 9 },
        { lane: "Latency management", priority: 8 },
        { lane: "Multilevel access", priority: 9 },
        { lane: "Deployment testing", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Mission priority", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "C2 lanes",
    },
    {
      id: "c3el-dtaccs-environments",
      title: "D-TACCS operating environments",
      subtitle: "Uploaded report identifies D-TACCS use in JOCs, TOCs, and EOCs in demanding deployment environments.",
      type: "bar",
      xKey: "environment",
      data: [
        { environment: "Joint Operations Center", priority: 10 },
        { environment: "Tactical Operations Center", priority: 10 },
        { environment: "Emergency Operations Center", priority: 8 },
        { environment: "Austere deployment", priority: 9 },
        { environment: "24/7 operations", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Operational demand", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "D-TACCS",
    },
    {
      id: "c3el-occumed-wedges",
      title: "C3EL Occu-Med service wedges",
      subtitle: "Small-company/high-specialty account: field engineering and deployed C2 support drive the medical logic.",
      type: "bar",
      xKey: "wedge",
      data: [
        { wedge: "Field-service baselines", priority: 9 },
        { wedge: "Travel readiness", priority: 8 },
        { wedge: "Rack/AV ergonomic strain", priority: 8 },
        { wedge: "Visual strain / displays", priority: 7 },
        { wedge: "Hearing/noise baseline", priority: 6 },
        { wedge: "OCONUS/DBA readiness", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "medical wedge",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "c3el-integration-space", label: "Integration facility sq. ft.", value: 10000, unit: "count", category: "workforce" },
    { id: "c3el-strategic-proximity", label: "Tampa/MacDill proximity score", value: 10, unit: "score", category: "financial" },
    { id: "c3el-dtaccs-priority", label: "D-TACCS mission priority", value: 10, unit: "score", category: "risk" },
    { id: "c3el-medical-fit", label: "Field-support medical fit", value: 8, unit: "score", category: "risk" },
  ],
  riskMatrix: [
    { name: "Field C2 integrators", revenue: 80, risk: 8.0, workers: 80 },
    { name: "Rack/AV technicians", revenue: 65, risk: 7.0, workers: 60 },
    { name: "Deployment support", revenue: 90, risk: 8.5, workers: 50 },
    { name: "Engineering/admin", revenue: 40, risk: 3.5, workers: 150 },
    { name: "Tampa integration center", revenue: 75, risk: 6.5, workers: 100 },
  ],
  opportunityMatrix: [
    { name: "Field-Service Medical Baselines", revenuePotential: 90, implementationComplexity: 5, strategicValue: 8 },
    { name: "Travel / Deployment Readiness", revenuePotential: 75, implementationComplexity: 5, strategicValue: 8 },
    { name: "Ergonomics / Lift / Display Strain", revenuePotential: 60, implementationComplexity: 4, strategicValue: 7 },
    { name: "OCONUS / DBA Readiness", revenuePotential: 50, implementationComplexity: 6, strategicValue: 8 },
    { name: "Hearing / Noise Baselines", revenuePotential: 40, implementationComplexity: 4, strategicValue: 6 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "This profile corrects the earlier generic CEL placeholder and treats the entity as C3EL: Command Control Communications Engineering & Logistics, a Tampa-centered command-and-control integration firm.",
      bullets: [
        "C3EL relocated its headquarters and integration center to the Westshore District near Tampa International Airport in 2024.",
        "The uploaded report lists a 10,000-square-foot integration facility and Emerging Technology Center.",
        "Strategic proximity is to MacDill AFB, USCENTCOM, USSOCOM, JCSE, and federal mission partners.",
        "The company specializes in turnkey audiovisual, communications, and C2 systems rather than generic IT staffing.",
      ],
      metricIds: ["c3el-integration-space", "c3el-strategic-proximity"],
    },
    {
      type: "workforce",
      title: "C2 integration and D-TACCS work reality",
      narrative:
        "C3EL's work sits at the intersection of AV integration, secure communications, deployable command centers, and fielded mission architecture. The occupational-health story is field engineering, deployment readiness, and ergonomics, not factory-scale injury volume.",
      bullets: [
        "D-TACCS supports 24/7 JOC, TOC, and EOC environments.",
        "Integration work includes physical AV/rack work, data distribution, latency management, secure multilevel access, and pre-deployment testing.",
        "The Emerging Technology Center is useful as a staging/testing location before systems are sent to global theaters.",
      ],
      metricIds: ["c3el-dtaccs-priority"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The account should be approached as a small specialized C2 field-support profile. The useful wedges are field-service baselines, deployment readiness, travel medicine, ergonomic/visual strain, hearing/noise baselines, and OCONUS/DBA readiness when field support leaves CONUS.",
      bullets: [
        "Do not pitch generic pre-employment physical volume first.",
        "Pitch readiness for field engineers and deployable integration teams supporting 24/7 operations centers.",
        "Tampa/MacDill proximity makes C3EL useful for broader CENTCOM/SOCOM network-expansion planning.",
      ],
      metricIds: ["c3el-medical-fit"],
    },
  ],
};
