import type { CompanyConfig } from "./types";

export const caciConfig: CompanyConfig = {
  companyId: "caci",
  displayName: "CACI International Inc.",
  shortName: "CACI",
  sector:
    "Defense IT, intelligence, cyber, engineering, federal civilian services, cleared professional services, OCONUS support, DBA exposure, high-consequence injury trend monitoring, and security-clearance workforce readiness",
  headquarters: "Reston, Virginia",
  employees: 25000,
  employeesAsOf:
    "Uploaded CACI deep-dive report: approximately 25,000 employees as of June 30, 2025, with $8.6B FY2025 revenue and 95.7% federal-government revenue exposure",
  summary:
    "CACI International is a Fortune 500 defense and IT services contractor headquartered in Reston, Virginia. The uploaded CACI deep-dive upgrades the prior short dossier into a full Occu-Med intelligence profile: CACI has about 25,000 employees, $8.6B FY2025 revenue, 95.7% federal-government revenue exposure, and 75.4% DoD revenue exposure. Unlike Amentum, CACI's workforce is heavily weighted toward IT, intelligence analysis, cyber, engineering, and office-based knowledge work. That produces an extremely low recordable injury rate — 0.12 in CY2022 and CY2023 after 0.20 in CY2021 — but the high-consequence injury count jumped from 3 to 13 in CY2023. The key Occu-Med insight is that CACI is not a high-volume industrial surveillance account; it is a low-rate but high-severity signal account where deployed personnel, clearance-sensitive workforce fitness, travel, ergonomics, DOT or transportation pockets, and DBA-covered OCONUS support matter. The CY2023 high-consequence spike is the sales wedge because those cases drive workers' comp, lost time, EMR pressure, and CPAR risk even when total recordables remain low.",
  tags: [
    "Entity profile",
    "CACI",
    "Defense IT",
    "Intelligence community",
    "Cyber",
    "Federal services",
    "High-consequence injuries",
    "Low TRIR",
    "DBA exposure",
    "OCONUS",
    "Clearance workforce",
    "Ergonomics",
    "Travel risk",
    "CPAR risk",
  ],
  aliases: ["CACI", "CACI International", "CACI International Inc.", "CACI International Inc"],
  sourceFilters: {
    sec: { ticker: "CACI", legalEntities: ["CACI International Inc"] },
    sam: { legalNames: ["CACI International Inc", "CACI"] },
    usaSpending: { recipientNames: ["CACI", "CACI International"] },
    jobSources: { linkedin: "caci-international", clearanceJobs: "CACI", careerSite: "https://careers.caci.com/" },
    newsSources: { aliases: ["CACI", "CACI International", "CACI high consequence injury", "CACI DBA"] },
  },
  executiveSignals: [
    { label: "Employees", value: "25K", note: "Uploaded CACI report cites approximately 25,000 employees as of June 30, 2025." },
    { label: "FY2025 revenue", value: "$8.6B", note: "Uploaded report says FY2025 revenue was $8.6B, up 13% year over year." },
    { label: "Recordable rate", value: "0.12", note: "CY2023 recordable injury rate was 0.12, flat from CY2022 and down 40% from CY2021." },
    { label: "Red flag", value: "13 high-consequence", note: "High-consequence injuries rose from 3 in CY2022 to 13 in CY2023 despite low recordables." },
  ],
  curveTitle: "CACI low-rate, high-consequence injury and cleared-workforce readiness curve",
  curveSubtitle:
    "Uploaded CACI deep-dive normalized into an entity profile. CACI's risk is not broad industrial injury volume; it is high-consequence events, deployed support, ergonomics, travel, and clearance-sensitive workforce fitness.",
  chartDefinitions: [
    {
      id: "caci-revenue-growth",
      title: "CACI revenue growth FY2021-FY2025",
      subtitle: "Uploaded CACI report: revenue rose from about $6.0B to $8.6B, with FY2025 up 13% year over year.",
      type: "bar",
      xKey: "year",
      data: [
        { year: "FY2021", revenue: 6.0 },
        { year: "FY2022", revenue: 6.2 },
        { year: "FY2023", revenue: 6.7 },
        { year: "FY2024", revenue: 7.7 },
        { year: "FY2025", revenue: 8.6 },
      ],
      series: [{ dataKey: "revenue", name: "Revenue", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "revenue growth",
      fullWidth: true,
    },
    {
      id: "caci-injury-counts",
      title: "CACI recordable vs high-consequence injury counts",
      subtitle: "Recordables dropped sharply from CY2021, but high-consequence injuries spiked in CY2023.",
      type: "grouped",
      xKey: "year",
      data: [
        { year: "CY2021", recordable: 42, highConsequence: 9 },
        { year: "CY2022", recordable: 21, highConsequence: 3 },
        { year: "CY2023", recordable: 22, highConsequence: 13 },
      ],
      series: [
        { dataKey: "recordable", name: "Recordable injuries", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "highConsequence", name: "High-consequence injuries", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "injury mix",
      fullWidth: true,
    },
    {
      id: "caci-injury-rates",
      title: "CACI injury-rate trend CY2021-CY2023",
      subtitle: "Recordable rate fell from 0.20 to 0.12, but high-consequence rate rose to 0.07 in CY2023.",
      type: "line",
      xKey: "year",
      data: [
        { year: "CY2021", recordableRate: 0.20, highConsequenceRate: 0.04 },
        { year: "CY2022", recordableRate: 0.12, highConsequenceRate: 0.02 },
        { year: "CY2023", recordableRate: 0.12, highConsequenceRate: 0.07 },
      ],
      series: [
        { dataKey: "recordableRate", name: "Recordable rate", color: "#22d3ee" },
        { dataKey: "highConsequenceRate", name: "High-consequence rate", color: "#ef4444" },
      ],
      domain: [0, 0.25],
      headline: "rate trend",
    },
    {
      id: "caci-vs-amentum-industry",
      title: "CACI vs Amentum vs industry TRIR-style comparison",
      subtitle: "CACI's 0.12 rate is lower than Amentum's already-elite 0.47, but the workforce hazard profile is structurally different.",
      type: "bar",
      xKey: "entity",
      data: [
        { entity: "CACI CY2023", rate: 0.12 },
        { entity: "Amentum FY2024", rate: 0.47 },
        { entity: "Industry composite", rate: 2.77 },
      ],
      series: [{ dataKey: "rate", name: "Rate", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 3],
      headline: "benchmark",
      fullWidth: true,
    },
    {
      id: "caci-revenue-dependency",
      title: "CACI revenue dependency",
      subtitle: "Uploaded report: federal customers account for 95.7% of revenue, with DoD alone at 75.4%.",
      type: "bar",
      xKey: "customer",
      data: [
        { customer: "DoD", share: 75.4 },
        { customer: "Other federal", share: 20.3 },
        { customer: "Commercial/other", share: 4.3 },
      ],
      series: [{ dataKey: "share", name: "Revenue share", color: "#22c55e", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 100],
      headline: "customer mix",
    },
    {
      id: "caci-occumed-wedges",
      title: "CACI Occu-Med service wedges",
      subtitle: "The right pitch is high-consequence prevention, deployed support, clearance-sensitive readiness, and ergonomics — not industrial-volume surveillance.",
      type: "bar",
      xKey: "wedge",
      data: [
        { wedge: "High-consequence prevention", priority: 10 },
        { wedge: "Deployed/OCONUS readiness", priority: 8 },
        { wedge: "Clearance-sensitive fitness", priority: 8 },
        { wedge: "Ergonomics / visual strain", priority: 7 },
        { wedge: "Travel injury prevention", priority: 7 },
        { wedge: "RTW documentation", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "medical wedge",
    },
  ],
  metricDefinitions: [
    { id: "caci-employees", label: "Employees", value: 25000, unit: "count", category: "workforce" },
    { id: "caci-revenue", label: "FY2025 revenue", value: 8.6, unit: "usd", category: "financial" },
    { id: "caci-federal-share", label: "Federal revenue share", value: 95.7, unit: "percent", category: "financial" },
    { id: "caci-dod-share", label: "DoD revenue share", value: 75.4, unit: "percent", category: "financial" },
    { id: "caci-recordable-rate", label: "CY2023 recordable rate", value: 0.12, unit: "score", category: "safety" },
    { id: "caci-recordables-2023", label: "CY2023 recordables", value: 22, unit: "count", category: "safety" },
    { id: "caci-high-consequence-2023", label: "CY2023 high-consequence injuries", value: 13, unit: "count", category: "safety" },
    { id: "caci-high-consequence-rate", label: "CY2023 high-consequence rate", value: 0.07, unit: "score", category: "safety" },
    { id: "caci-hours-worked", label: "CY2023 hours worked", value: 38.0, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "High-consequence injuries", revenue: 13, risk: 9.5, workers: 25000 },
    { name: "OCONUS / DBA support", revenue: 3, risk: 8.0, workers: 750 },
    { name: "Clearance workforce", revenue: 75, risk: 6.5, workers: 18000 },
    { name: "Ergonomics / visual strain", revenue: 25, risk: 6.0, workers: 20000 },
    { name: "Travel / field work", revenue: 15, risk: 7.0, workers: 3000 },
  ],
  opportunityMatrix: [
    { name: "High-Consequence Injury Review", revenuePotential: 175, implementationComplexity: 6, strategicValue: 10 },
    { name: "RTW / Lost-Time Documentation", revenuePotential: 150, implementationComplexity: 5, strategicValue: 9 },
    { name: "Deployed Personnel Baselines", revenuePotential: 125, implementationComplexity: 6, strategicValue: 8 },
    { name: "Clearance-Sensitive FFD", revenuePotential: 100, implementationComplexity: 7, strategicValue: 8 },
    { name: "Ergonomic / Visual Strain Program", revenuePotential: 75, implementationComplexity: 4, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "CACI is a large defense IT and intelligence contractor, but its medical profile is not the same as Amentum, V2X, or KBR. It is a low-recordable-rate knowledge-workforce account with selective deployed and high-consequence risk.",
      bullets: [
        "Approximately 25,000 employees and $8.6B FY2025 revenue in the uploaded report.",
        "Federal government contracts account for 95.7% of revenue, with DoD at 75.4%.",
        "The workforce skews toward IT, intelligence analysis, cyber, engineering, and office-based knowledge work.",
        "This means fewer physical injuries, but more emphasis on severity, clearance readiness, ergonomics, travel, and deployed support.",
      ],
      metricIds: ["caci-employees", "caci-revenue", "caci-federal-share", "caci-dod-share"],
    },
    {
      type: "safety",
      title: "The CY2023 high-consequence spike",
      narrative:
        "The most actionable CACI safety signal is not total recordables. Recordables remained low, but high-consequence injuries jumped from 3 to 13 in CY2023, which is exactly the category that drives lost-time cost, claim severity, EMR pressure, and CPAR concern.",
      bullets: [
        "Recordable injury count fell from 42 in CY2021 to 21 in CY2022 and 22 in CY2023.",
        "Recordable injury rate stabilized at 0.12 in CY2022 and CY2023.",
        "High-consequence injuries rose from 3 in CY2022 to 13 in CY2023.",
        "The sales angle is high-consequence prevention and RTW documentation, not generic injury-rate reduction.",
      ],
      metricIds: ["caci-recordable-rate", "caci-recordables-2023", "caci-high-consequence-2023", "caci-high-consequence-rate"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "CACI should be approached as a specialized cleared-workforce and high-consequence-prevention account. The most credible wedges are return-to-work support, pre-deployment baselines, clearance-sensitive fitness-for-duty, ergonomics, visual strain, travel injury prevention, and documentation quality.",
      bullets: [
        "A broad industrial surveillance pitch will not fit CACI's workforce composition.",
        "High-consequence injuries are the strongest opening because they affect workers' compensation severity and government performance concerns.",
        "Any international or OCONUS personnel create DBA and pre-deployment baseline opportunities.",
        "Ergonomic and visual-strain programs match the IT/cyber/intelligence workforce reality.",
      ],
      metricIds: [],
    },
  ],
};
