import type { CompanyConfig } from "./types";

export const clovehitchConfig: CompanyConfig = {
  companyId: "clovehitch",
  displayName: "CLOVEHITCH / CLGT Solutions",
  shortName: "CLOVEHITCH",
  sector:
    "Small intelligence services, language services, ASL interpretation, cleared administration, OCONUS linguist support, and IC-adjacent occupational health protocols",
  headquarters: "Granville, Ohio",
  employees: 125,
  employeesAsOf: "Uploaded Occu-Med intelligence report: estimated 50-200 employees and cleared contractors",
  summary:
    "CLOVEHITCH / CLGT Solutions is a Service-Disabled Veteran-Owned Small Business headquartered in Granville, Ohio. The uploaded reports make the key point clearly: this is not a high-volume physical-exam account. It is a small intelligence and language-services contractor with a uniquely underserved occupational health profile: OCONUS DBA deployment baselines, secondary traumatic stress screening for intelligence analysts, clearance-preservation behavioral health protocols, headset/hearing surveillance, voice-strain support for interpreters, and ergonomic surveillance for linguists and analysts.",
  tags: [
    "Entity profile",
    "SDVOSB",
    "Language services",
    "ASL interpretation",
    "Intelligence support",
    "INSCOM",
    "AFOSI",
    "DLITE",
    "DBA exposure",
    "Behavioral health",
    "Secondary traumatic stress",
    "Clearance preservation",
    "Small account pilot",
  ],
  aliases: ["CLGT Solutions", "CLGT Solutions LLC", "CLOVEHITCH", "Clovehitch", "Clovehitch Analytics"],
  sourceFilters: {
    sam: { legalNames: ["CLGT Solutions, LLC", "CLGT Solutions LLC", "CLOVEHITCH"] },
    usaSpending: { recipientNames: ["CLGT Solutions", "CLOVEHITCH"] },
    jobSources: { linkedin: "clovehitch", careerSite: "https://www.clovehitch.us/careers" },
    newsSources: {
      aliases: ["CLGT Solutions", "CLOVEHITCH", "Clovehitch", "DLITE", "INSCOM linguist", "AFOSI LASI"],
    },
  },
  executiveSignals: [
    {
      label: "Workforce size",
      value: "50-200",
      note: "Uploaded Occu-Med report says the account is small and should not be treated like a high-volume physical-exam relationship.",
    },
    {
      label: "Annual potential",
      value: "$24K-$90K/yr",
      note: "Modeled annual opportunity across pre-employment, DBA deployment exams, behavioral health screening, audiometry, and ergonomics.",
    },
    {
      label: "DBA exposure",
      value: "10-30 deployed",
      note: "Small OCONUS deployed population, but a single uncapped DBA claim could exceed the entire annual occ med spend.",
    },
    {
      label: "Primary differentiator",
      value: "STS protocol",
      note: "Secondary traumatic stress / clearance-preservation behavioral health screening is the distinctive Occu-Med play, not TRIR reduction.",
    },
  ],
  curveTitle: "CLOVEHITCH small-account, IC-adjacent occupational health curve",
  curveSubtitle:
    "Uploaded Clovehitch reports normalized into entity-profile charts. Values are modeled Occu-Med intelligence estimates and should not be presented as audited CLGT disclosures.",
  chartDefinitions: [
    {
      id: "clovehitch-revenue-potential",
      title: "CLOVEHITCH annual Occu-Med revenue potential",
      subtitle: "Uploaded Occu-Med report: small $24K-$90K relationship, valuable mainly as an IC-adjacent pilot and referral wedge.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Pre-employment physicals", low: 2.6, high: 11.0 },
        { examType: "DBA pre/post deployment", low: 7.0, high: 20.0 },
        { examType: "Behavioral health screening", low: 9.0, high: 30.0 },
        { examType: "Audiometric baseline", low: 3.8, high: 18.8 },
        { examType: "Ergonomic assessments", low: 2.0, high: 10.5 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "small-account revenue",
      fullWidth: true,
    },
    {
      id: "clovehitch-risk-profile",
      title: "CLOVEHITCH risk profile: physical injury is not the main story",
      subtitle: "The workforce is mostly linguists, analysts, instructors, and cleared professionals; true risk concentrates in behavioral health and OCONUS deployment.",
      type: "bar",
      xKey: "riskLane",
      data: [
        { riskLane: "Physical injury/TRIR", priority: 2 },
        { riskLane: "DBA deployment baseline", priority: 9 },
        { riskLane: "Secondary traumatic stress", priority: 10 },
        { riskLane: "Clearance-preservation BH", priority: 10 },
        { riskLane: "Headset/audiometry", priority: 7 },
        { riskLane: "Ergonomics/voice strain", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "risk inversion",
    },
    {
      id: "clovehitch-workforce-portfolios",
      title: "Two workforce portfolios: intelligence vs language services",
      subtitle: "Uploaded reports split the account into intelligence support and lower-risk language/ASL services.",
      type: "bar",
      xKey: "portfolio",
      data: [
        { portfolio: "Intelligence / SIGINT / GEOINT", risk: 8, volume: 35 },
        { portfolio: "OCONUS deployed linguists", risk: 9, volume: 20 },
        { portfolio: "ASL / language services", risk: 4, volume: 45 },
        { portfolio: "Cleared administration / IT", risk: 3, volume: 25 },
      ],
      series: [
        { dataKey: "risk", name: "Risk priority", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "volume", name: "Illustrative workforce weight", color: "#22d3ee", radius: [8, 8, 0, 0] },
      ],
      headline: "portfolio split",
    },
    {
      id: "clovehitch-domestic-footprint",
      title: "Domestic operational footprint and project sites",
      subtitle: "Global operations/facilities report identifies HQ, ASL, staffing, intelligence, training, and contract support nodes.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Granville OH", operationalWeight: 10 },
        { location: "Phoenix AZ", operationalWeight: 5 },
        { location: "Virginia Beach VA", operationalWeight: 6 },
        { location: "Cleveland OH", operationalWeight: 4 },
        { location: "Washington DC", operationalWeight: 8 },
        { location: "Quantico VA", operationalWeight: 7 },
        { location: "Maryland", operationalWeight: 5 },
        { location: "North Carolina", operationalWeight: 5 },
        { location: "Colorado", operationalWeight: 4 },
      ],
      series: [{ dataKey: "operationalWeight", name: "Operational relevance", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "footprint",
      fullWidth: true,
    },
    {
      id: "clovehitch-service-pillars",
      title: "CLOVEHITCH service pillars",
      subtitle: "The global operations report organizes capabilities around language, intelligence, IT, and cleared administration.",
      type: "bar",
      xKey: "pillar",
      data: [
        { pillar: "Language solutions", priority: 10 },
        { pillar: "Intelligence services", priority: 9 },
        { pillar: "Information technology", priority: 7 },
        { pillar: "Cleared administration", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Strategic pillar weight", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "capabilities",
    },
    {
      id: "clovehitch-dba-severity",
      title: "Small deployed population, high DBA consequence",
      subtitle: "Uploaded report estimates 10-30 deployed workers at a time; DBA severity is concentrated in single-event catastrophic risk.",
      type: "bar",
      xKey: "scenario",
      data: [
        { scenario: "Low deployed count", count: 10 },
        { scenario: "High deployed count", count: 30 },
        { scenario: "Low DBA exam volume", count: 20 },
        { scenario: "High DBA exam volume", count: 40 },
      ],
      series: [{ dataKey: "count", name: "People / annual exam volume", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "DBA exposure",
    },
    {
      id: "clovehitch-unique-value",
      title: "Why this account matters despite low volume",
      subtitle: "The uploaded report identifies three strategic reasons to pursue CLOVEHITCH.",
      type: "bar",
      xKey: "valueDriver",
      data: [
        { valueDriver: "IC referral network", priority: 10 },
        { valueDriver: "Behavioral health differentiation", priority: 10 },
        { valueDriver: "DBA protocol for small contractors", priority: 9 },
        { valueDriver: "Direct exam volume", priority: 3 },
      ],
      series: [{ dataKey: "priority", name: "Strategic value", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "strategic wedge",
    },
  ],
  metricDefinitions: [
    { id: "clovehitch-employees-mid", label: "Estimated employees midpoint", value: 125, unit: "count", category: "workforce" },
    { id: "clovehitch-employees-low", label: "Estimated employees low", value: 50, unit: "count", category: "workforce" },
    { id: "clovehitch-employees-high", label: "Estimated employees high", value: 200, unit: "count", category: "workforce" },
    { id: "clovehitch-revenue-low", label: "Occu-Med revenue low", value: 0.024, unit: "usd", category: "financial" },
    { id: "clovehitch-revenue-high", label: "Occu-Med revenue high", value: 0.09, unit: "usd", category: "financial" },
    { id: "clovehitch-deployed-low", label: "Deployed population low", value: 10, unit: "count", category: "risk" },
    { id: "clovehitch-deployed-high", label: "Deployed population high", value: 30, unit: "count", category: "risk" },
    { id: "clovehitch-gsa-end-year", label: "GSA ultimate end year", value: 2044, unit: "count", category: "financial" },
  ],
  riskMatrix: [
    { name: "STS / behavioral health", revenue: 30, risk: 10.0, workers: 60 },
    { name: "DBA deployed analysts/linguists", revenue: 20, risk: 9.5, workers: 30 },
    { name: "Headset / audiometry", revenue: 18.8, risk: 6.5, workers: 150 },
    { name: "Ergonomics / voice strain", revenue: 10.5, risk: 6.0, workers: 60 },
    { name: "Pre-employment physicals", revenue: 11, risk: 3.0, workers: 40 },
  ],
  opportunityMatrix: [
    { name: "STS / Clearance-Preservation Protocol", revenuePotential: 30, implementationComplexity: 8, strategicValue: 10 },
    { name: "DBA Pre/Post Deployment", revenuePotential: 20, implementationComplexity: 6, strategicValue: 10 },
    { name: "Audiometric Baseline", revenuePotential: 18.8, implementationComplexity: 4, strategicValue: 7 },
    { name: "Ergonomic / Voice Assessment", revenuePotential: 10.5, implementationComplexity: 5, strategicValue: 7 },
    { name: "Pre-Employment Physicals", revenuePotential: 11, implementationComplexity: 3, strategicValue: 4 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "CLOVEHITCH should be treated as a small, specialized IC-adjacent entity rather than a volume account. The uploaded report is blunt: the numbers will not support a high-volume physical-exam relationship, but the account can be valuable as a behavioral health, DBA compliance, and intelligence-community referral wedge.",
      bullets: [
        "Formerly CLGT Solutions LLC and rebranded to CLOVEHITCH around 2022.",
        "Headquartered in Granville, Ohio and founded in 2010.",
        "Estimated workforce is 50-200 employees and cleared contractors.",
        "Corporate/GSA data identifies CLGT Solutions LLC as an SDVOSB with GSA MAS contract 47QRAA24D0084 and ultimate contract end date of May 12, 2044.",
      ],
      metricIds: ["clovehitch-employees-mid", "clovehitch-revenue-high", "clovehitch-gsa-end-year"],
    },
    {
      type: "workforce",
      title: "What the workforce actually does",
      narrative:
        "The workforce is mostly linguists, intelligence analysts, instructors, and cleared professionals. BLS benchmark TRIR for this kind of professional services workforce is low, so physical injury is not the correct sales story.",
      bullets: [
        "Intelligence portfolio: geolocation, SIGINT support, deployed intelligence analysis, remote sensing, imagery analysis, INSCOM support, DLITE mission support, AFOSI LASI, and Afghanistan analytical support.",
        "Language services portfolio: foreign language interpretation, translation, ASL interpretation, State FSI area studies, language proficiency testing, and NEA/SCA linguist support.",
        "Core service domains from the global operations report are Language Solutions, Intelligence Services, Information Technology, and Cleared Administration.",
      ],
      metricIds: [],
    },
    {
      type: "locations",
      title: "Operational footprint and facilities",
      narrative:
        "The global operations/facilities report gives enough location data to treat CLOVEHITCH as a distributed small-business contractor with HQ administration in Ohio and project/service nodes across federal agency and defense locations.",
      bullets: [
        "Granville, Ohio is the corporate HQ / production point and GSA contract administration hub.",
        "Phoenix, Arizona is a government-agency onsite ASL services location awarded in July 2024 for 34 hours/month.",
        "Virginia Beach is a staffing support center for ASL and administrative personnel.",
        "Washington, DC, Quantico, Maryland, North Carolina, and Colorado appear as intelligence, training, contract support, linguistic, or technical services nodes.",
      ],
      metricIds: [],
    },
    {
      type: "safety",
      title: "The behavioral health gap is the primary risk",
      narrative:
        "The uploaded Occu-Med report identifies secondary traumatic stress and clearance-preservation behavioral health as the real occupational medicine gap. Analysts processing sensitive or traumatic intelligence material may avoid care because of clearance concerns, making routine EAP-style support insufficient.",
      bullets: [
        "Secondary traumatic stress can arise from exposure to graphic imagery, casualty data, torture documentation, and terrorism-related material.",
        "Mission-related moral injury can emerge from analytical decisions with lethal consequence implications.",
        "Cognitive fatigue and burnout are linked to sustained high-security, high-consequence analytical work without standard decompression protocols.",
        "Clearance-preservation bias means workers may not self-refer until symptoms become a disability, substance-use, or clearance-investigation problem.",
      ],
      metricIds: [],
    },
    {
      type: "locations",
      title: "OCONUS DBA deployment exposure",
      narrative:
        "CLOVEHITCH's deployed population is small, but the legal and claim consequence is large. Personnel deployed OCONUS under INSCOM, AFOSI, DLITE, NEA/SCA, or similar mission support can trigger Defense Base Act coverage with no lifetime medical cap.",
      bullets: [
        "The deployed population may be only 10-30 workers at a time.",
        "A single permanent disability claim from a vehicle accident, indirect fire, or field injury could exceed the account's entire annual occupational medicine spend.",
        "Pre-deployment fitness-for-duty and DBA-compliant medicals are framed as an insurance mechanism against catastrophic single-claim exposure.",
      ],
      metricIds: ["clovehitch-deployed-low", "clovehitch-deployed-high"],
    },
    {
      type: "medical-opportunities",
      title: "Interpreter, translator, and analyst surveillance lanes",
      narrative:
        "CLOVEHITCH's language-services population creates under-recognized surveillance lanes: headset/hearing baselines, voice strain, upper extremity cumulative trauma, visual strain, and ergonomics.",
      bullets: [
        "Headset-heavy translation or SIGINT-adjacent monitoring can create audiometric baseline need, even when standard office assumptions would miss it.",
        "Simultaneous interpreters and ASL interpreters can face voice strain, vocal fold injury, and upper-extremity cumulative trauma disorders.",
        "Sedentary linguistic and analytical work can produce cervical strain, carpal tunnel symptoms, and visual strain.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The relationship is not big in dollars. The uploaded report estimates about $24K-$90K per year, but argues the account is valuable because it can pilot an IC-adjacent behavioral health and DBA protocol before selling the same model to larger cleared contractor networks.",
      bullets: [
        "Pre-employment physicals: 15-40 annual volume; modeled $2.6K-$11K per year.",
        "DBA pre/post deployment exams: 20-40 annual volume; modeled $7K-$20K per year.",
        "Annual behavioral health screening: 30-60 annual volume; modeled $9K-$30K per year.",
        "Audiometric baseline: 50-150 annual volume; modeled $3.8K-$18.8K per year.",
        "Ergonomic assessments: 10-30 annual volume; modeled $2K-$10.5K per year.",
      ],
      metricIds: ["clovehitch-revenue-low", "clovehitch-revenue-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "CLOVEHITCH values in this profile are extracted from the uploaded Occu-Med intelligence report and the uploaded global operations/facilities report. The account is intentionally modeled as low-volume but strategically differentiated. Do not inflate headcount or revenue potential to make it look like a large account.",
      bullets: [
        "Use the 50-200 workforce range from the Occu-Med report, not the older rough 800-worker shell estimate.",
        "Treat behavioral health, DBA, audiometry, and ergonomics as the sales story rather than injury-cost or TRIR reduction.",
        "World Vision International and Operation CLOVEHITCH references in the global operations report are contextual/name-ecosystem material, not CLGT workforce exposure unless separately tied to CLGT operations.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "deep-analysis",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
