import type { CompanyConfig } from "./types";

export const constellisConfig: CompanyConfig = {
  companyId: "constellis",
  displayName: "Constellis / Centerra / Triple Canopy",
  shortName: "Constellis",
  sector:
    "Protective security, DOE nuclear guard force, global protective services, background investigations, domestic guard services, high-threat protective operations, and DBA-covered security work",
  headquarters: "Herndon, Virginia",
  employees: 20000,
  employeesAsOf: "Uploaded Constellis Occu-Med intelligence report: February 19, 2026",
  summary:
    "Constellis is a privately held protective-security entity with roughly $1B revenue and about 20,000 employees across Triple Canopy, Centerra, OMNIPLEX, and domestic guard operations. The uploaded Occu-Med report frames Constellis as one of the largest exam-demand accounts in the portfolio because the $10.3B GPS MATOC creates a major pre-employment and transition-baseline event, while Centerra's DOE nuclear guard force creates mandatory annual fitness-for-duty exams. The profile is not generic security guards; it is a mix of OCONUS PSOs, DOE nuclear protective forces, DoD domestic guards, and background investigators with sharply different medical protocols.",
  tags: [
    "Entity profile",
    "Constellis",
    "Triple Canopy",
    "Centerra",
    "OMNIPLEX",
    "GPS MATOC",
    "DOE nuclear guard",
    "WPS III Baghdad",
    "DBA",
    "Fitness-for-duty",
    "Protective security",
    "Guard force transition",
  ],
  aliases: ["Constellis", "Constellis Holdings", "Centerra Group", "Triple Canopy", "OMNIPLEX", "Acuity International legacy"],
  sourceFilters: {
    sam: { legalNames: ["Constellis", "Triple Canopy", "Centerra Group", "OMNIPLEX"] },
    usaSpending: { recipientNames: ["Constellis", "Triple Canopy", "Centerra", "OMNIPLEX"] },
    jobSources: { linkedin: "constellis", careerSite: "https://www.constellis.com/careers/" },
    newsSources: { aliases: ["Constellis", "Triple Canopy", "Centerra", "GPS MATOC", "Global Protective Services", "DOE nuclear guard"] },
  },
  executiveSignals: [
    { label: "GPS MATOC", value: "$10.3B", note: "Uploaded report identifies the Army Global Protective Services MATOC as the largest single exam-demand driver." },
    { label: "Total workforce", value: "~20K", note: "Modeled across OCONUS PSOs, DOE nuclear guards, domestic guards, and background investigators." },
    { label: "Direct cost", value: "$12.5M-$18.7M", note: "BLS benchmark model across worker populations for direct annual injury costs." },
    { label: "DOE recurring exams", value: "$980K-$1.47M", note: "Annual fitness-for-duty revenue model for roughly 2,450 Centerra nuclear guards." },
  ],
  curveTitle: "Constellis GPS MATOC, DOE guard force, and DBA/security risk curve",
  curveSubtitle:
    "Uploaded Constellis Occu-Med report normalized for entity-profile scanning; injury, revenue, and workforce values are modeled intelligence estimates requiring validation with task-order and headcount data.",
  chartDefinitions: [
    {
      id: "constellis-injury-cost",
      title: "Constellis annual injury-cost exposure",
      subtitle: "Uploaded report: direct cost low plus additional high estimate shown in $M.",
      type: "stacked",
      xKey: "name",
      data: [
        { name: "OCONUS PSOs", direct: 2.4, additional: 1.2 },
        { name: "DOE Nuclear Guard", direct: 2.8, additional: 1.4 },
        { name: "DoD Domestic", direct: 7.3, additional: 3.6 },
        { name: "Investigators", direct: 0.3, additional: 0.2 },
        { name: "Total Portfolio", direct: 12.5, additional: 6.2 },
      ],
      series: [
        { dataKey: "direct", name: "Direct low", color: "#22d3ee", stackId: "cost" },
        { dataKey: "additional", name: "Additional high", color: "#ef4444", stackId: "cost", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "injury cost",
      fullWidth: true,
    },
    {
      id: "constellis-contracts",
      title: "Constellis contract portfolio demand signals",
      subtitle: "GPS MATOC dominates the contract vehicle signal; DOE and Baghdad remain high-value specialty lanes.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "GPS MATOC", value: 10.3 },
        { name: "WPS III Baghdad", value: 1.3 },
        { name: "DOE Savannah River", value: 1.0 },
        { name: "LANL", value: 0.592 },
        { name: "Other DOE", value: 0.5 },
      ],
      series: [{ dataKey: "value", name: "Contract value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "contract drivers",
    },
    {
      id: "constellis-worker-risk",
      title: "Constellis worker risk by BLS / analog TRIR",
      subtitle: "OCONUS PSOs, DOE protective force, and domestic guard populations carry different risk and exam logic.",
      type: "bar",
      xKey: "population",
      data: [
        { population: "OCONUS PSOs", trir: 3.0, headcount: 2000, injuries: 60 },
        { population: "DOE Nuclear Guard", trir: 2.0, headcount: 3500, injuries: 70 },
        { population: "DoD Domestic Guard", trir: 1.4, headcount: 13000, injuries: 182 },
        { population: "Investigators", trir: 0.5, headcount: 1500, injuries: 8 },
      ],
      series: [{ dataKey: "trir", name: "TRIR benchmark", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 3.5],
      headline: "worker risk",
      fullWidth: true,
    },
    {
      id: "constellis-gps-volume",
      title: "GPS MATOC annual new-hire exam volume",
      subtitle: "Uploaded report: even conservative turnover creates thousands of annual pre-employment exams.",
      type: "bar",
      xKey: "scenario",
      data: [
        { scenario: "15% turnover", exams: 1950, revenueLow: 390, revenueHigh: 682.5 },
        { scenario: "20% turnover", exams: 2600, revenueLow: 520, revenueHigh: 910 },
        { scenario: "25% turnover", exams: 3250, revenueLow: 650, revenueHigh: 1137.5 },
        { scenario: "Transition low", exams: 5000, revenueLow: 1000, revenueHigh: 1750 },
        { scenario: "Transition high", exams: 8000, revenueLow: 1600, revenueHigh: 2800 },
      ],
      series: [{ dataKey: "exams", name: "Exam volume", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "GPS volume",
    },
    {
      id: "constellis-doe-exam",
      title: "Centerra DOE fitness-for-duty exam revenue",
      subtitle: "Uploaded report: roughly 2,450 Centerra nuclear guards create annual mandatory FFD exam demand.",
      type: "stacked",
      xKey: "site",
      data: [
        { site: "SRS", low: 480, additional: 240, guards: 1200 },
        { site: "LANL", low: 240, additional: 120, guards: 600 },
        { site: "Hanford", low: 120, additional: 60, guards: 300 },
        { site: "SPR Sites", low: 80, additional: 40, guards: 200 },
        { site: "NFS Erwin", low: 60, additional: 30, guards: 150 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", stackId: "rev" },
        { dataKey: "additional", name: "Additional", color: "#ef4444", stackId: "rev", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "DOE recurring",
    },
    {
      id: "constellis-priority-map",
      title: "Constellis Occu-Med priority map",
      subtitle: "Service lanes from GPS transition, DOE nuclear FFD, Baghdad DBA, and domestic guard churn.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "GPS transition baseline", priority: 10 },
        { lane: "DOE nuclear FFD", priority: 10 },
        { lane: "OCONUS DBA medical", priority: 10 },
        { lane: "Domestic guard pre-employment", priority: 9 },
        { lane: "Psychological suitability", priority: 9 },
        { lane: "Vision/hearing standards", priority: 8 },
        { lane: "Background investigator ergonomics", priority: 5 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "priority map",
    },
  ],
  metricDefinitions: [
    { id: "constellis-employees", label: "Employees", value: 20000, unit: "count", category: "workforce" },
    { id: "constellis-revenue", label: "Estimated revenue", value: 1.0, unit: "usd", category: "financial" },
    { id: "constellis-injuries", label: "Expected injuries/yr", value: 320, unit: "count", category: "safety" },
    { id: "constellis-direct-cost-low", label: "Direct injury cost low", value: 12.5, unit: "usd", category: "financial" },
    { id: "constellis-direct-cost-high", label: "Direct injury cost high", value: 18.7, unit: "usd", category: "financial" },
    { id: "constellis-gps-matoc", label: "GPS MATOC ceiling", value: 10.3, unit: "usd", category: "financial" },
    { id: "constellis-doe-guards", label: "DOE nuclear guards", value: 2450, unit: "count", category: "workforce" },
    { id: "constellis-doe-revenue-high", label: "DOE FFD revenue high", value: 1.47, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "GPS domestic guard force", revenue: 910, risk: 8.0, workers: 13000 },
    { name: "DOE nuclear guards", revenue: 1470, risk: 9.5, workers: 2450 },
    { name: "OCONUS PSOs", revenue: 1200, risk: 10.0, workers: 2000 },
    { name: "GPS transition baseline", revenue: 2800, risk: 8.5, workers: 8000 },
    { name: "Background investigators", revenue: 100, risk: 3.5, workers: 1500 },
  ],
  opportunityMatrix: [
    { name: "GPS Transition Baseline", revenuePotential: 2800, implementationComplexity: 8, strategicValue: 10 },
    { name: "DOE Nuclear Guard FFD", revenuePotential: 1470, implementationComplexity: 8, strategicValue: 10 },
    { name: "GPS Annual Guard Physicals", revenuePotential: 910, implementationComplexity: 6, strategicValue: 9 },
    { name: "OCONUS DBA Medicals", revenuePotential: 700, implementationComplexity: 7, strategicValue: 10 },
    { name: "Psychological Suitability", revenuePotential: 450, implementationComplexity: 8, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Constellis is a large protective-security entity where the exam opportunity comes from multiple distinct populations rather than one generic guard-force program.",
      bullets: [
        "Privately held company with approximately $1B revenue and about 20,000 employees.",
        "Worker populations include OCONUS PSOs, DOE nuclear guards, DoD domestic guards, and OMNIPLEX background investigators.",
        "The uploaded report models about 320 expected injuries per year and $12.5M-$18.7M in direct annual injury cost.",
        "The correct profile is Triple Canopy plus Centerra plus OMNIPLEX, not a single undifferentiated security vendor.",
      ],
      metricIds: ["constellis-employees", "constellis-injuries", "constellis-direct-cost-high"],
    },
    {
      type: "contracts",
      title: "GPS MATOC is the largest exam-demand event",
      narrative:
        "The uploaded report identifies the Army's $10.3B Global Protective Services MATOC as the largest single driver of exam demand in Constellis's history.",
      bullets: [
        "Conservative 15-20% turnover on 13,000 GPS guards creates about 1,950-2,600 new hires per year.",
        "At $200-$350 per pre-employment physical, GPS alone can produce about $390K-$910K in annual exam revenue.",
        "Transition from prior guard vehicles may create a one-time baseline opportunity for 5,000-8,000 workers.",
      ],
      metricIds: ["constellis-gps-matoc"],
    },
    {
      type: "medical-opportunities",
      title: "DOE nuclear guard force is the highest-value niche",
      narrative:
        "Centerra's DOE nuclear protective force is the highest-margin recurring niche because armed protective-force personnel require periodic fitness-for-duty evaluations tied to DOE and NRC expectations.",
      bullets: [
        "Roughly 2,450 DOE nuclear guards are modeled across Savannah River Site, Los Alamos, Hanford, Strategic Petroleum Reserve, and Nuclear Fuel Services Erwin.",
        "Annual FFD exams are modeled at $980K-$1.47M in recurring revenue.",
        "Protocols include cardiovascular stress, musculoskeletal fitness, psychological suitability, vision, and hearing standards.",
      ],
      metricIds: ["constellis-doe-guards", "constellis-doe-revenue-high"],
    },
    {
      type: "safety",
      title: "OCONUS PSO and DBA exposure",
      narrative:
        "Triple Canopy's OCONUS protective-services population should be handled separately from domestic guard hiring because pre-deployment fitness and DBA documentation are different from standard pre-employment screening.",
      bullets: [
        "OCONUS PSOs are modeled at roughly 2,000 workers and about 60 expected injuries per year.",
        "WPS III Baghdad and related programs create recurring pre-deployment and post-deployment medical documentation needs.",
        "DBA medical documentation quality is the main risk-control value for this worker group.",
      ],
      metricIds: [],
    },
  ],
};
