import type { CompanyConfig } from "./types";

export const constellisConfig: CompanyConfig = {
  companyId: "constellis",
  displayName: "Constellis / Centerra",
  shortName: "Constellis",
  sector: "Protective security, DOE nuclear guard force, background investigations, GPS MATOC, and international PSO operations",
  headquarters: "Herndon, Virginia",
  employees: 15000,
  employeesAsOf: "Uploaded Constellis dossier estimate",
  summary: "Constellis / Centerra operates across protective security, DOE nuclear guard force, background investigations, and international PSO operations with significant DBA exposure and DOE fitness-for-duty requirements.",
  tags: ["GPS MATOC", "DOE nuclear guard", "WPS III Baghdad", "Background investigations", "DBA", "Fitness-for-duty"],
  aliases: ["Centerra Group", "Constellis Holdings", "Triple Canopy"],
  executiveSignals: [
    { label: "GPS MATOC ceiling", value: "$10.3B", note: "Largest active contract vehicle in portfolio." },
    { label: "Total workforce", value: "~15K", note: "Modeled across PSOs, DOE nuclear guards, domestic guards, and investigators." },
    { label: "DOE exam pipeline", value: "~2,450 guards", note: "Listed DOE site guards requiring fitness-for-duty exams." },
    { label: "Worker risk peak", value: "TRIR 3.0", note: "OCONUS PSOs carry the highest benchmarked risk." },
  ],
  curveTitle: "Constellis contract and worker-risk curve",
  curveSubtitle: "Contract portfolio, injury cost exposure, DOE exam revenue, GPS MATOC volume, and worker-risk values normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "constellis-contracts",
      title: "Constellis contract portfolio",
      subtitle: "Source: uploaded Constellis visual; active vehicle ceiling/value shown in $B.",
      type: "bar",
      xKey: "name",
      data: [{ name: "GPS MATOC", value: 10.3 }, { name: "WPS III Baghdad", value: 1.3 }, { name: "DOE Savannah River", value: 1.0 }, { name: "LANL", value: 0.592 }, { name: "Other DOE", value: 0.5 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "Constellis metric",
    },
    {
      id: "constellis-injury-cost",
      title: "Constellis annual injury-cost exposure",
      subtitle: "Source: uploaded Constellis visual; direct cost plus additional high estimate shown in $M.",
      type: "stacked",
      xKey: "name",
      data: [{ name: "OCONUS PSOs", direct: 2.2, additional: 1.2 }, { name: "DOE Nuclear Guard", direct: 2.8, additional: 1.4 }, { name: "DoD Domestic", direct: 7.3, additional: 3.6 }, { name: "Total Portfolio", direct: 12.5, additional: 6.2 }],
      series: [
        { dataKey: "direct", name: "Direct low", color: "#22d3ee", stackId: "cost" },
        { dataKey: "additional", name: "Additional high", color: "#ef4444", stackId: "cost", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "injury cost stack",
    },
    {
      id: "constellis-doe-exam",
      title: "Centerra DOE fitness-for-duty exam revenue",
      subtitle: "Source: uploaded Centerra DOE visual; annual revenue shown in $K.",
      type: "stacked",
      xKey: "name",
      data: [{ name: "SRS", low: 480, additional: 240 }, { name: "LANL", low: 240, additional: 120 }, { name: "Hanford", low: 120, additional: 60 }, { name: "SPR Sites", low: 80, additional: 40 }, { name: "NFS Erwin", low: 60, additional: 30 }],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", stackId: "rev" },
        { dataKey: "additional", name: "Additional", color: "#ef4444", stackId: "rev", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "exam revenue stack",
    },
    {
      id: "constellis-gps-volume",
      title: "GPS MATOC annual new-hire exam volume",
      subtitle: "Source: uploaded GPS MATOC visual; annual pre-employment exam volume by turnover scenario.",
      type: "bar",
      xKey: "name",
      data: [{ name: "15% Turnover", exams: 1950 }, { name: "20% Turnover", exams: 2600 }, { name: "25% Turnover", exams: 3250 }],
      series: [{ dataKey: "exams", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "Constellis metric",
    },
    {
      id: "constellis-trir",
      title: "Constellis worker risk by BLS TRIR benchmark",
      subtitle: "Source: uploaded Constellis visual; TRIR by worker category.",
      type: "bar",
      xKey: "name",
      data: [{ name: "OCONUS PSOs", value: 3.0 }, { name: "DOE Nuclear Guard", value: 2.0 }, { name: "DoD Domestic Guard", value: 1.4 }, { name: "Background Investigators", value: 0.5 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "Constellis metric",
      fullWidth: true,
    },
  ],
};
