import type { CompanyConfig } from "./types";

export const coreClientStatsDashboardConfig: CompanyConfig = {
  companyId: "core-client-stats-dashboard",
  displayName: "Core Client Stats Dashboard",
  shortName: "Core Stats",
  sector:
    "Eight-company core portfolio stats, North America worker exposure, TRIR benchmark comparisons, confirmed fatalities, estimated direct injury costs, revenue potential, and private-company safety-data gaps",
  headquarters: "Occu-Med portfolio-level stats dashboard",
  employees: 124768,
  employeesAsOf:
    "Uploaded Stats dashboard: 8-company portfolio with approximately 124,768 North America workers and $61.6B combined revenue",
  summary:
    "Core Client Stats Dashboard captures the uploaded eight-company portfolio snapshot for Amentum, Fluor, Freeport-McMoRan, Weatherford, Constellis, Versar, IDS International, and Clovehitch. It is intentionally different from the 21-account master portfolio profile: this dashboard focuses on a smaller core portfolio where public TRIR/fatality data exists for the large public companies and BLS proxy benchmarks are used for private companies. The strongest insight is that Freeport-McMoRan, Fluor, and Amentum account for 89% of combined revenue, while the private companies carry some of the most hazardous work with no public TRIR or fatality disclosures. Amentum has the largest North America exam pool at roughly 48,000 workers, while Weatherford's global size shrinks to only about 3,518 North America workers for Occu-Med opportunity purposes.",
  tags: [
    "Entity profile",
    "Core stats",
    "Portfolio dashboard",
    "Amentum",
    "Fluor",
    "Freeport-McMoRan",
    "Weatherford",
    "Constellis",
    "Versar",
    "IDS International",
    "Clovehitch",
    "TRIR benchmark",
    "Fatalities",
    "Revenue potential",
  ],
  aliases: ["Stats Dashboard", "Core Client Stats", "8 Company Portfolio", "Master Stats Dashboard"],
  sourceFilters: {
    newsSources: { aliases: ["Occu-Med master stats dashboard", "core client portfolio stats"] },
  },
  executiveSignals: [
    { label: "Combined revenue", value: "$61.6B", note: "Uploaded Stats dashboard total across the eight-company portfolio." },
    { label: "NA workers", value: "124,768", note: "North America worker count is the actual exam-market lens used in the dashboard." },
    { label: "Confirmed fatalities", value: "13+", note: "Amentum, Fluor, FCX, and Weatherford public data account for at least 13 confirmed 2024 fatalities." },
    { label: "Revenue potential", value: "$2.83M-$6.19M", note: "Uploaded dashboard revenue range across the eight-company core portfolio." },
  ],
  curveTitle: "Eight-company revenue, worker, TRIR, and revenue-potential curve",
  curveSubtitle:
    "Uploaded Stats dashboard normalized into a portfolio entity. Public/private data quality differs materially by company.",
  chartDefinitions: [
    {
      id: "core-revenue-comparison",
      title: "Core portfolio revenue comparison",
      subtitle: "Freeport-McMoRan, Fluor, and Amentum account for nearly all combined revenue in this core view.",
      type: "bar",
      xKey: "company",
      data: [
        { company: "FCX", revenue: 25.5 },
        { company: "Fluor", revenue: 15.7 },
        { company: "Amentum", revenue: 13.8 },
        { company: "Weatherford", revenue: 5.1 },
        { company: "Constellis", revenue: 1.0 },
        { company: "Versar", revenue: 0.45 },
        { company: "IDS", revenue: 0.045 },
        { company: "Clovehitch", revenue: 0.01 },
      ],
      series: [{ dataKey: "revenue", name: "Revenue", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "revenue",
      fullWidth: true,
    },
    {
      id: "core-na-workers",
      title: "North America workers: the actual exam market",
      subtitle: "Amentum has the largest NA exam pool; Weatherford's global headcount materially overstates domestic opportunity.",
      type: "bar",
      xKey: "company",
      data: [
        { company: "Amentum", workers: 48000 },
        { company: "FCX", workers: 34800 },
        { company: "Fluor", workers: 18000 },
        { company: "Constellis", workers: 17000 },
        { company: "Weatherford", workers: 3518 },
        { company: "Versar", workers: 2000 },
        { company: "IDS", workers: 1300 },
        { company: "Clovehitch", workers: 150 },
      ],
      series: [{ dataKey: "workers", name: "NA workers", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "exam market",
      fullWidth: true,
    },
    {
      id: "core-trir-vs-bls",
      title: "Public-company TRIR vs BLS benchmark",
      subtitle: "All four public companies beat BLS benchmarks; private companies require proxy modeling.",
      type: "grouped",
      xKey: "company",
      data: [
        { company: "Weatherford", trir: 0.12, benchmark: 1.6 },
        { company: "Fluor", trir: 0.31, benchmark: 2.1 },
        { company: "Amentum", trir: 0.33, benchmark: 1.6 },
        { company: "FCX", trir: 0.69, benchmark: 1.8 },
      ],
      series: [
        { dataKey: "trir", name: "Reported TRIR", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "benchmark", name: "BLS benchmark", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      domain: [0, 2.5],
      headline: "TRIR benchmark",
    },
    {
      id: "core-revenue-potential",
      title: "Occu-Med annual revenue potential by account",
      subtitle: "Uploaded Stats table: low/high revenue ranges and primary revenue drivers.",
      type: "bar",
      xKey: "company",
      data: [
        { company: "Amentum", low: 800, high: 1800 },
        { company: "FCX", low: 600, high: 1200 },
        { company: "Constellis", low: 500, high: 1000 },
        { company: "Fluor", low: 400, high: 900 },
        { company: "Versar", low: 280, high: 600 },
        { company: "IDS", low: 150, high: 400 },
        { company: "Weatherford", low: 80, high: 200 },
        { company: "Clovehitch", low: 24, high: 90 },
      ],
      series: [
        { dataKey: "low", name: "Low estimate", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High estimate", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
      fullWidth: true,
    },
    {
      id: "core-private-data-gap",
      title: "Private-company safety-data gap",
      subtitle: "The dashboard identifies private high-risk entities with no public TRIR/fatality data.",
      type: "bar",
      xKey: "company",
      data: [
        { company: "Constellis", risk: 10 },
        { company: "Versar", risk: 9 },
        { company: "IDS", risk: 9 },
        { company: "Clovehitch", risk: 6 },
      ],
      series: [{ dataKey: "risk", name: "Data-gap risk", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "private gap",
    },
  ],
  metricDefinitions: [
    { id: "core-revenue", label: "Combined revenue", value: 61.6, unit: "usd", category: "financial" },
    { id: "core-na-workers", label: "North America workers", value: 124768, unit: "count", category: "workforce" },
    { id: "core-confirmed-fatalities", label: "Confirmed 2024 fatalities", value: 13, unit: "count", category: "safety" },
    { id: "core-revenue-low", label: "Revenue potential low", value: 2.83, unit: "usd", category: "financial" },
    { id: "core-revenue-high", label: "Revenue potential high", value: 6.19, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "FCX mining", revenue: 1200, risk: 9.5, workers: 34800 },
    { name: "Amentum NA workforce", revenue: 1800, risk: 8.5, workers: 48000 },
    { name: "Constellis private risk", revenue: 1000, risk: 10.0, workers: 17000 },
    { name: "Fluor construction", revenue: 900, risk: 8.0, workers: 18000 },
    { name: "Versar HAZWOPER", revenue: 600, risk: 9.0, workers: 2000 },
  ],
  opportunityMatrix: [
    { name: "Amentum HAZWOPER / DOT / Nuclear", revenuePotential: 1800, implementationComplexity: 7, strategicValue: 10 },
    { name: "FCX MSHA / B-reader / Mine Physicals", revenuePotential: 1200, implementationComplexity: 8, strategicValue: 9 },
    { name: "Constellis DOE / DBA / GPS MATOC", revenuePotential: 1000, implementationComplexity: 7, strategicValue: 9 },
    { name: "Fluor Construction Medical", revenuePotential: 900, implementationComplexity: 6, strategicValue: 8 },
    { name: "Versar HAZWOPER Annual Exams", revenuePotential: 600, implementationComplexity: 5, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Eight-company core dashboard",
      narrative:
        "This uploaded dashboard is the compact, executive version of the portfolio: eight companies, $61.6B combined revenue, 124,768 North America workers, and at least 13 confirmed 2024 fatalities from public-company disclosures.",
      bullets: [
        "Freeport-McMoRan, Fluor, and Amentum account for 89% of combined revenue.",
        "Amentum is the largest North America exam pool at roughly 48,000 workers.",
        "Weatherford's global headcount is misleading for domestic exam opportunity because NA workers are only about 3,518.",
      ],
      metricIds: ["core-revenue", "core-na-workers", "core-confirmed-fatalities"],
    },
    {
      type: "safety",
      title: "Public data vs private data gap",
      narrative:
        "The strongest strategic point is not that public companies disclose TRIR. It is that the private companies do some of the most hazardous work in the group while producing little to no public safety data.",
      bullets: [
        "Public companies beat BLS benchmarks, but still produce material fatality and injury-cost exposure.",
        "Constellis, Versar, IDS, and Clovehitch require proxy modeling because TRIR/fatality disclosures are not public.",
        "The dashboard argues this is exactly the market Occu-Med can own with specialized occupational medicine infrastructure.",
      ],
      metricIds: [],
    },
  ],
};
