import type { CompanyConfig } from "./types";

export const dbaCarrierNetworkConfig: CompanyConfig = {
  companyId: "dba-carrier-network",
  displayName: "DBA Carrier Network Intelligence",
  shortName: "DBA Carriers",
  sector:
    "Defense Base Act insurance carrier networks, workers' compensation claims routing, carrier provider access, and OCONUS occupational medicine channel strategy",
  headquarters: "Network-level intelligence entity",
  employees: 0,
  employeesAsOf: "Not applicable — carrier network intelligence entity",
  summary:
    "Cross-entity carrier intelligence showing how Defense Base Act referral volume concentrates around a small number of workers' compensation/DBA carrier networks. The uploaded carrier-mapping reports identify AIG/ICSOP, CNA/Rutherfoord/USACE, ACE/Chubb, self-insured employers, and a V2X layered carrier stack as the key access points for provider-network growth. Chart pack 2 adds high-risk DBA audit client analysis showing companies with >75% OCONUS footprint, including Applus+, Weatherford, World Vision, and QinetiQ.",
  tags: [
    "Entity profile",
    "DBA insurance",
    "Carrier network",
    "AIG",
    "CNA",
    "ACE/Chubb",
    "Self-insured",
    "V2X carrier stack",
    "Provider credentialing",
    "Growth channel",
  ],
  aliases: [
    "DBA Carrier Network",
    "Defense Base Act Carrier Network",
    "DBA insurance carrier intelligence",
    "Carrier provider-network strategy",
  ],
  sourceFilters: {
    newsSources: {
      aliases: [
        "Defense Base Act carrier",
        "AIG DBA",
        "CNA DBA",
        "ACE Chubb DBA",
        "DBA claims provider network",
        "V2X DBA carrier stack",
      ],
    },
  },
  executiveSignals: [
    {
      label: "Carrier concentration",
      value: "AIG-led",
      note: "Uploaded mapping identifies AIG/Insurance Company of the State of Pennsylvania as the dominant DBA carrier channel by claim share and referral volume.",
    },
    {
      label: "AIG volume share",
      value: "~73%",
      note: "Carrier share chart shows AIG at roughly 72.8% of mapped referral volume; DOL historical claim data in the report cites 79% of DBA claims handled by AIG from 2001-2018.",
    },
    {
      label: "CNA gatekeeper lane",
      value: "USACE / DOS / USAID",
      note: "Uploaded report states CNA is mandatory for certain USACE work through Rutherfoord International, making CNA provider access a strategic channel.",
    },
    {
      label: "V2X carrier stack",
      value: "5 carriers",
      note: "V2X carrier intelligence lists Allianz Commercial, Applied Risk Services, Falls Lake/Coventry, QBE North America, and Texas Insurance Company as a layered program.",
    },
    {
      label: "Highest audit risk",
      value: "Applus+ 98%",
      note: "Chart pack 2 high-risk DBA audit chart shows Applus+, Weatherford, World Vision, International SOS, Kapsuun, and QinetiQ with very high OCONUS mix.",
    },
  ],
  curveTitle: "DBA carrier network concentration and growth curve",
  curveSubtitle:
    "Carrier intelligence is modeled from uploaded Occu-Med reports and should be treated as source-backed operating intelligence requiring verification with each carrier/provider network.",
  chartDefinitions: [
    {
      id: "dba-carrier-share",
      title: "DBA carrier share by mapped referral volume",
      subtitle: "Uploaded carrier mapping: AIG dominates the mapped entity volume, followed by CNA and self-insured networks.",
      type: "bar",
      xKey: "carrier",
      data: [
        { carrier: "AIG", share: 72.8 },
        { carrier: "CNA", share: 15.0 },
        { carrier: "Self-insured", share: 8.82 },
        { carrier: "Unknown", share: 2.4 },
        { carrier: "ACE/Chubb", share: 0.465 },
      ],
      series: [{ dataKey: "share", name: "Referral volume share", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 80],
      headline: "carrier share",
      fullWidth: true,
    },
    {
      id: "dba-growth-potential",
      title: "Entity footprint growth potential",
      subtitle: "Re-labeled from uploaded growth-potential chart: expansion entities represent roughly 66% of the current tracked footprint.",
      type: "bar",
      xKey: "group",
      data: [
        { group: "Current tracked footprint", sites: 1458 },
        { group: "Expansion entities", sites: 956 },
      ],
      series: [{ dataKey: "sites", name: "Total sites", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "growth potential",
    },
    {
      id: "dba-top-entities-by-carrier",
      title: "Top entities by annual refs and DBA carrier channel",
      subtitle: "Carrier-colored top-entity chart converted into stacked data keys for the entity-profile renderer.",
      type: "bar",
      xKey: "entity",
      data: [
        { entity: "V2X", aig: 5427, cna: 0, aceChubb: 0, selfInsured: 0, unknown: 0 },
        { entity: "Amentum", aig: 852, cna: 0, aceChubb: 0, selfInsured: 0, unknown: 0 },
        { entity: "Lockheed Martin", aig: 0, cna: 0, aceChubb: 0, selfInsured: 675, unknown: 0 },
        { entity: "Akima", aig: 525, cna: 0, aceChubb: 0, selfInsured: 0, unknown: 0 },
        { entity: "Booz Allen", aig: 0, cna: 0, aceChubb: 425, selfInsured: 0, unknown: 0 },
        { entity: "Valiant", aig: 423, cna: 0, aceChubb: 0, selfInsured: 0, unknown: 0 },
        { entity: "IAP", aig: 409, cna: 0, aceChubb: 0, selfInsured: 0, unknown: 0 },
        { entity: "AECOM", aig: 0, cna: 350, aceChubb: 0, selfInsured: 0, unknown: 0 },
        { entity: "Cherokee Nation", aig: 350, cna: 0, aceChubb: 0, selfInsured: 0, unknown: 0 },
        { entity: "Leidos", aig: 0, cna: 0, aceChubb: 0, selfInsured: 307, unknown: 0 },
        { entity: "Bechtel", aig: 0, cna: 250, aceChubb: 0, selfInsured: 0, unknown: 0 },
        { entity: "HII", aig: 0, cna: 0, aceChubb: 0, selfInsured: 250, unknown: 0 },
        { entity: "ManTech", aig: 198, cna: 0, aceChubb: 0, selfInsured: 0, unknown: 0 },
        { entity: "Textron", aig: 0, cna: 0, aceChubb: 175, selfInsured: 0, unknown: 0 },
        { entity: "SOSi", aig: 167, cna: 0, aceChubb: 0, selfInsured: 0, unknown: 0 },
      ],
      series: [
        { dataKey: "aig", name: "AIG", color: "#22d3ee", stackId: "carrier" },
        { dataKey: "cna", name: "CNA", color: "#ef4444", stackId: "carrier" },
        { dataKey: "aceChubb", name: "ACE/Chubb", color: "#f97316", stackId: "carrier" },
        { dataKey: "selfInsured", name: "Self-insured", color: "#22c55e", stackId: "carrier" },
        { dataKey: "unknown", name: "Unknown", color: "#94a3b8", stackId: "carrier" },
      ],
      headline: "annual refs",
      fullWidth: true,
    },
    {
      id: "v2x-layered-carrier-stack",
      title: "V2X layered DBA carrier stack",
      subtitle: "Uploaded V2X carrier brief: provider-network access should cover every layer, not one carrier only.",
      type: "bar",
      xKey: "carrier",
      data: [
        { carrier: "Allianz Commercial", priority: 10 },
        { carrier: "Applied Risk / Promesa", priority: 10 },
        { carrier: "Falls Lake / Coventry", priority: 10 },
        { carrier: "QBE North America", priority: 10 },
        { carrier: "Texas Insurance Co.", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Credentialing priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "network priority",
    },
    {
      id: "carrier-access-strategy",
      title: "Carrier access strategy by gatekeeper network",
      subtitle: "Operating logic from uploaded reports: a small number of carrier networks can unlock large contractor groups.",
      type: "bar",
      xKey: "channel",
      data: [
        { channel: "AIG / ICSOP", unlockScore: 10 },
        { channel: "CNA / Rutherfoord", unlockScore: 8 },
        { channel: "ACE / Chubb", unlockScore: 5 },
        { channel: "Self-insured direct", unlockScore: 6 },
        { channel: "Coventry WCS", unlockScore: 7 },
        { channel: "QBE / Allianz", unlockScore: 8 },
      ],
      series: [{ dataKey: "unlockScore", name: "Strategic unlock score", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "network unlock",
    },
    {
      id: "dba-high-risk-audit-clients",
      title: "Highest DBA audit-risk clients",
      subtitle: "Chart pack 2: companies with >75% OCONUS footprint.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "Weatherford", oconusShare: 93 },
        { client: "Applus+", oconusShare: 98 },
        { client: "World Vision", oconusShare: 91 },
        { client: "Amentum", oconusShare: 77 },
        { client: "Versar Global", oconusShare: 77 },
        { client: "QinetiQ", oconusShare: 89 },
        { client: "Group SSI", oconusShare: 79 },
        { client: "Kapsuun", oconusShare: 90 },
        { client: "International SOS", oconusShare: 92 },
        { client: "Fluor", oconusShare: 78 },
      ],
      series: [{ dataKey: "oconusShare", name: "OCONUS %", color: "#ef4444", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 100],
      headline: "audit risk",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "carrier-aig-share", label: "AIG mapped volume share", value: 72.8, unit: "percent", category: "risk" },
    { id: "carrier-dol-aig-claims", label: "AIG historical DBA claims share", value: 79, unit: "percent", category: "risk" },
    { id: "carrier-current-sites", label: "Current tracked footprint", value: 1458, unit: "count", category: "workforce" },
    { id: "carrier-expansion-sites", label: "Expansion entity footprint", value: 956, unit: "count", category: "workforce" },
    { id: "carrier-v2x-refs", label: "V2X annual refs", value: 5427, unit: "count", category: "workforce" },
    { id: "carrier-high-risk-applus", label: "Applus+ OCONUS share", value: 98, unit: "percent", category: "risk" },
  ],
  riskMatrix: [
    { name: "AIG / ICSOP", revenue: 10.0, risk: 7.5, workers: 10000 },
    { name: "CNA / Rutherfoord", revenue: 3.0, risk: 6.5, workers: 1800 },
    { name: "ACE / Chubb", revenue: 1.0, risk: 5.0, workers: 600 },
    { name: "Self-insured direct", revenue: 2.0, risk: 4.5, workers: 1200 },
    { name: "Coventry WCS", revenue: 2.5, risk: 6.0, workers: 1500 },
  ],
  opportunityMatrix: [
    { name: "AIG provider network", revenuePotential: 10000, implementationComplexity: 8, strategicValue: 10 },
    { name: "CNA / Rutherfoord", revenuePotential: 1800, implementationComplexity: 7, strategicValue: 9 },
    { name: "QBE provider nomination", revenuePotential: 1200, implementationComplexity: 5, strategicValue: 8 },
    { name: "Allianz nomination", revenuePotential: 1200, implementationComplexity: 5, strategicValue: 8 },
    { name: "Coventry WCS", revenuePotential: 1500, implementationComplexity: 6, strategicValue: 8 },
    { name: "Self-insured direct", revenuePotential: 1200, implementationComplexity: 4, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Carrier network overview",
      narrative:
        "The uploaded reports shift the strategy from entity-by-entity sales to carrier-network access. AIG/ICSOP, CNA/Rutherfoord, ACE/Chubb, self-insured employers, Coventry WCS, QBE, Allianz, and Applied/Promesa function as referral-routing infrastructure for DBA and workers' compensation medical activity.",
      bullets: [
        "AIG/ICSOP is identified as the dominant DBA carrier channel by historical DBA claim share and mapped referral volume.",
        "CNA is positioned as the mandatory carrier lane for key USACE/DOS/USAID work through Rutherfoord International.",
        "ACE/Chubb is identified as a third major carrier, especially for UK defense-prime style entities such as BAE and QinetiQ.",
        "Self-insured entities such as Leidos, Lockheed Martin, and HII require direct outreach rather than carrier-network access.",
      ],
      metricIds: ["carrier-aig-share", "carrier-dol-aig-claims"],
    },
    {
      type: "procurement",
      title: "Confirmed and high-confidence entity-carrier mapping",
      narrative:
        "The mapping document identifies confirmed/high-confidence carrier relationships and separates them from industry-pattern assumptions. This profile uses the uploaded report as source-backed operating intelligence, not final carrier verification.",
      bullets: [
        "V2X / Vectrus: AIG/ICSOP is identified as confirmed in the carrier mapping report, while a separate V2X brief identifies a layered carrier stack.",
        "Amentum: mapped as AIG/CNA depending on agency/contract lane.",
        "Leidos: mapped as self-insured with Aetna administrative infrastructure.",
        "Fluor, AECOM, Bechtel, and Michael Baker are mapped to CNA for USACE-mandated work.",
        "BAE Systems and QinetiQ are mapped toward ACE/Chubb based on UK defense-prime patterning.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "V2X layered carrier action plan",
      narrative:
        "The uploaded V2X brief says V2X does not use a single DBA insurer; it runs a layered program across Allianz Commercial, Applied Risk Services/Promesa, Falls Lake/Coventry, QBE North America, and Texas Insurance Company. Occu-Med should pursue every layer so a carrier switch does not break referral flow.",
      bullets: [
        "Allianz Commercial: use provider nomination form and follow up through workers' compensation claims leadership.",
        "Applied Risk Services: call 877-234-4420 and ask for Promesa Health network credentialing or National Broker Services.",
        "Falls Lake: credential through Coventry Workers' Comp Services and also contact Falls Lake business development.",
        "QBE North America: use provider nomination portal and pursue claims/program contacts.",
        "Texas Insurance Company: confirm actual TPA/claims administrator through V2X risk/vendor contacts before outreach.",
      ],
      metricIds: ["carrier-v2x-refs"],
    },
    {
      type: "procurement",
      title: "Strategic implication",
      narrative:
        "The carrier reports argue that the fastest way to scale is not cold-calling every contractor. The higher-leverage path is carrier-network credentialing: AIG first, CNA second, ACE/Chubb third, then direct self-insured outreach.",
      bullets: [
        "Verify whether Occu-Med is already in AIG, CNA, Chubb, Coventry, QBE, Allianz, and Applied/Promesa networks.",
        "If not in AIG, pursue AIG/ICSOP access immediately because the report models it as the dominant referral channel.",
        "CNA/Rutherfoord access unlocks USACE-mandated contractors such as AECOM, Bechtel, Michael Baker, and Fluor.",
        "Self-insured entities bypass carriers and still require direct HR, safety, risk, and benefits outreach.",
      ],
      metricIds: ["carrier-current-sites", "carrier-expansion-sites"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "Carrier values in this profile are source-backed but should be verified before operational use. Some entity-carrier relationships are confirmed, while others are high- or medium-confidence pattern matches. The profile should preserve confidence labels and avoid presenting inferred mappings as final certificate-of-insurance facts.",
      bullets: [
        "Treat V2X carrier stack as confirmed by the uploaded brief, but confirm the Texas Insurance Company TPA before outreach.",
        "Treat AIG dominance as high-confidence based on uploaded DOL/market analysis, but verify each employer's active policy year.",
        "Treat medium-confidence mappings such as CACI, BAE, QinetiQ, Akima, Cherokee Nation, Booz Allen, and Textron as prospecting hypotheses until verified.",
        "Keep the language as entity/carrier intelligence, not client/prospect categories.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "comparative-benchmark",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
