import type { CompanyConfig } from "./types";

export const caciConfig: CompanyConfig = {
  companyId: "caci",
  displayName: "CACI International Inc.",
  shortName: "CACI",
  sector: "Defense and government technology services",
  headquarters: "Reston, Virginia",
  employees: 25000,
  employeesAsOf: "2025-06-30",
  summary: "Technology and mission-services contractor with global program support and high-clearance workforce concentration.",
  tags: ["DoD prime", "Intelligence community", "Federal civilian", "Workers compensation"],
  aliases: ["CACI International", "CACI"],
  sourceFilters: {
    sec: { ticker: "CACI", legalEntities: ["CACI International Inc"] },
    sam: { legalNames: ["CACI International Inc"] },
    usaSpending: { recipientNames: ["CACI", "CACI International"] },
    jobSources: { linkedin: "caci-international", clearanceJobs: "CACI" },
    newsSources: { aliases: ["CACI"] },
  },
  executiveSignals: [
    { label: "Employees", value: "~25,000", note: "DoD/IC prime with global workforce." },
    { label: "FY2025 Revenue", value: "$8.627B", note: "Growing through acquisition and organic capture." },
    { label: "Multi-state WC", value: "27 states + D.C.", note: "Complex jurisdictional WC administration." },
    { label: "Fringe growth", value: "$1.833B", note: "FY2025 indirect and fringe cost exposure." },
  ],
  curveTitle: "CACI risk and compliance curve",
  curveSubtitle: "Fringe exposure, multi-state WC, acquisition integration, and compliance values normalized for executive scanning.",
  chartDefinitions: [],
};

export const fluorConfig: CompanyConfig = {
  companyId: "fluor",
  displayName: "Fluor Corporation",
  shortName: "Fluor",
  sector: "Engineering, construction, and government services",
  headquarters: "Irving, Texas",
  employees: 26866,
  employeesAsOf: "2024-12-31",
  summary: "Large engineering and construction operator with material self-insured liability disclosures and global project delivery footprint.",
  tags: ["Engineering", "Construction", "Government services", "Industrial risk"],
  aliases: ["Fluor Corp"],
  sourceFilters: {
    sec: { ticker: "FLR", legalEntities: ["Fluor Corporation"] },
    newsSources: { aliases: ["Fluor"] },
  },
  executiveSignals: [
    { label: "Employees", value: "~26,866", note: "Large engineering and construction workforce." },
    { label: "Sector risk", value: "Industrial", note: "Engineering and construction carry elevated TRIR benchmarks." },
    { label: "Self-insured", value: "Material", note: "Disclosed self-insured WC and GL liabilities." },
    { label: "Global footprint", value: "Multi-continent", note: "Project delivery across Americas, EMEA, Asia-Pacific." },
  ],
  curveTitle: "Fluor engineering and risk curve",
  curveSubtitle: "Self-insured liabilities, industrial risk, and global delivery normalized for executive scanning.",
  chartDefinitions: [],
};

export const gditConfig: CompanyConfig = {
  companyId: "gdit",
  displayName: "General Dynamics Information Technology",
  shortName: "GDIT",
  sector: "Federal IT services, cloud, cybersecurity, AI/ML, and mission support",
  headquarters: "Falls Church, Virginia",
  employees: 32000,
  employeesAsOf: "2025 estimate",
  summary: "GDIT operates as General Dynamics' IT services division with federal cloud, cybersecurity, and mission-support programs. Worker-risk profile is concentrated in data centers, field service, and OCONUS deployment lanes.",
  tags: ["Federal IT", "Cloud", "Cybersecurity", "AI/ML", "General Dynamics"],
  aliases: ["GDIT", "GD Information Technology"],
  sourceFilters: {
    sec: { ticker: "GD", legalEntities: ["General Dynamics Corporation"] },
    newsSources: { aliases: ["GDIT", "General Dynamics IT"] },
  },
  executiveSignals: [
    { label: "Employees", value: "~32,000", note: "Large federal IT workforce." },
    { label: "Parent", value: "General Dynamics", note: "Division of NYSE-listed General Dynamics." },
    { label: "Sector", value: "Federal IT/Cloud", note: "Growing cloud and cybersecurity portfolio." },
    { label: "OCONUS", value: "Limited", note: "Primarily CONUS with selective OCONUS field service." },
  ],
  curveTitle: "GDIT technology and workforce curve",
  curveSubtitle: "Federal IT portfolio, workforce scale, and limited field-risk exposure normalized for executive scanning.",
  chartDefinitions: [],
};

export const clovehitchConfig: CompanyConfig = {
  companyId: "clovehitch",
  displayName: "CLOVEHITCH / CLGT Solutions",
  shortName: "Clovehitch",
  sector: "Language services, intelligence support, OCONUS interpretation, behavioral health, and defense linguistics",
  headquarters: "Granville, Ohio",
  employees: 800,
  employeesAsOf: "Uploaded Clovehitch dossier estimate",
  summary: "Clovehitch / CLGT Solutions is a language and intelligence services provider with OCONUS deployment, behavioral health screening needs, and DBA exposure across deployed linguist and analyst populations.",
  tags: ["Language services", "Intelligence support", "OCONUS", "DBA", "Behavioral health", "INSCOM"],
  aliases: ["CLGT Solutions", "Clovehitch Analytics"],
  executiveSignals: [
    { label: "Workforce", value: "~800", note: "Deployed linguists, analysts, and intelligence support." },
    { label: "OCONUS DBA", value: "Moderate", note: "Deployed linguist population creates DBA exam demand." },
    { label: "Behavioral health", value: "High need", note: "Intelligence and OCONUS workers have elevated behavioral health screening needs." },
    { label: "ASL growth", value: "Signal", note: "ASL interpreting services represent a growth lane." },
  ],
  curveTitle: "Clovehitch language and intelligence curve",
  curveSubtitle: "Workforce, OCONUS DBA, behavioral health, and intelligence portfolio values normalized for executive scanning.",
  chartDefinitions: [],
};

export const freeportConfig: CompanyConfig = {
  companyId: "freeport-mcmoran",
  displayName: "Freeport-McMoRan",
  shortName: "FCX",
  sector: "Mining, copper production, molybdenum, gold, and global mineral extraction",
  headquarters: "Phoenix, Arizona",
  employees: 26700,
  employeesAsOf: "2024-12-31",
  summary: "One of the world's largest copper producers with extensive mining operations across the Americas and Indonesia. Elevated safety risk profile from underground and open-pit mining, contractor fatality signals, and global workforce distribution.",
  tags: ["Mining", "Copper", "Global operations", "Contractor safety", "Hearing conservation"],
  aliases: ["FCX", "Freeport McMoRan"],
  sourceFilters: {
    sec: { ticker: "FCX", legalEntities: ["Freeport-McMoRan Inc."] },
    newsSources: { aliases: ["Freeport-McMoRan", "FCX"] },
  },
  executiveSignals: [
    { label: "2024 TRIR", value: "0.69", note: "Total TRIR nearly flat YoY but 33% above 2020." },
    { label: "Fatalities", value: "5 in 2024", note: "All four 2024 fatalities involved JV contractors." },
    { label: "Employees", value: "~26,700", note: "Large mining workforce across Americas and Indonesia." },
    { label: "Hearing conservation", value: "30 CFR Part 62", note: "Major surveillance lane for miners exposed to 85 dB TWA." },
  ],
  curveTitle: "Freeport-McMoRan mining and safety curve",
  curveSubtitle: "TRIR, fatality signals, contractor risk, and hearing conservation values normalized for executive scanning.",
  chartDefinitions: [],
};

export const versarConfig: CompanyConfig = {
  companyId: "versar-global-solutions",
  displayName: "Versar Global Solutions",
  shortName: "Versar",
  sector: "Environmental services, munitions response, construction management, and government support",
  headquarters: "Springfield, Virginia",
  employees: 1200,
  employeesAsOf: "Uploaded Versar dossier estimate",
  summary: "Versar Global Solutions provides environmental remediation, munitions response, construction management, and government support services with elevated field-operations risk.",
  tags: ["Environmental", "Munitions response", "Construction", "Field operations"],
  aliases: ["Versar Inc", "Versar Global"],
  executiveSignals: [
    { label: "Employees", value: "~1,200", note: "Field-heavy environmental and munitions workforce." },
    { label: "Sector risk", value: "Elevated", note: "Environmental and munitions response carry elevated field hazards." },
    { label: "Government focus", value: "DoD/EPA", note: "Primary customer base is DoD and EPA programs." },
    { label: "Field operations", value: "High exposure", note: "Munitions, environmental remediation, and construction create field-ops hazard exposure." },
  ],
  curveTitle: "Versar environmental and field-operations curve",
  curveSubtitle: "Environmental, munitions, and construction risk values normalized for executive scanning.",
  chartDefinitions: [],
};

export const dynamicAviationConfig: CompanyConfig = {
  companyId: "dynamic-aviation",
  displayName: "Dynamic Aviation Group",
  shortName: "Dynamic Aviation",
  sector: "Aviation maintenance, ISR flight operations, special mission aircraft, wildfire aviation, and government aviation support",
  headquarters: "Bridgewater, Virginia",
  employees: 575,
  employeesAsOf: "Uploaded report: estimated ~575 employees",
  summary: "Privately held aviation operator with no public TRIR, DART, or WC data. Risk focus is aviation MRO, composite-shop hazards, the 2022 mechanic severe-injury spike, FAA medical cycles, OCONUS DBA exposure, and USFS wildfire aviation readiness.",
  tags: ["Aviation MRO", "ISR", "FAA medicals", "USFS wildfire aviation", "Composite shop", "DBA"],
  aliases: ["Dynamic Aviation"],
  executiveSignals: [
    { label: "Employees", value: "~575", note: "Small but high-risk aviation workforce." },
    { label: "MRO TRIR benchmark", value: "3.40", note: "Aviation MRO industry benchmark TRIR." },
    { label: "Safety gap", value: "No public data", note: "No public TRIR, DART, or WC data available." },
    { label: "Wildfire aviation", value: "USFS", note: "USFS wildfire aviation readiness is a key risk lane." },
  ],
  curveTitle: "Dynamic Aviation MRO and risk curve",
  curveSubtitle: "Aviation MRO hazards, wildfire readiness, and FAA medical cycle values normalized for executive scanning.",
  chartDefinitions: [],
};

export const idsInternationalConfig: CompanyConfig = {
  companyId: "ids-international",
  displayName: "IDS International (Dossier)",
  shortName: "IDS Intl",
  sector: "Defense training, security, expeditionary support, and security services",
  headquarters: "Arlington, Virginia",
  employees: 1300,
  employeesAsOf: "Uploaded IDS International dossier",
  summary: "Extended dossier for IDS International covering intelligence portfolio, workforce sizing, OCONUS DBA exposure, and positioning signals.",
  tags: ["Defense training", "Security", "Expeditionary support", "DBA"],
  aliases: ["IDS International LLC"],
  executiveSignals: [
    { label: "Workforce", value: "~1,300", note: "Modeled across tactical, security, and expeditionary roles." },
    { label: "OCONUS", value: "High", note: "Heavy OCONUS deployment creates DBA exam demand." },
    { label: "Stop-work risk", value: "Elevated", note: "Concentrated contract value increases stop-work exposure." },
    { label: "Training hazards", value: "Tactical", note: "Tactical training carries elevated injury risk." },
  ],
  curveTitle: "IDS International intelligence curve",
  curveSubtitle: "Defense training, security, and expeditionary workforce values normalized for executive scanning.",
  chartDefinitions: [],
};
