import type { CompanyConfig } from "./types";

export const dynamicAviationConfig: CompanyConfig = {
  companyId: "dynamic-aviation",
  displayName: "Dynamic Aviation Group",
  shortName: "Dynamic Aviation",
  sector:
    "Aviation MRO, special mission aircraft, ISR flight operations, wildfire aviation, USFS aerial supervision, composite shop work, FAA medical cycles, and DBA-covered OCONUS aviation support",
  headquarters: "Bridgewater, Virginia",
  employees: 575,
  employeesAsOf: "Uploaded Dynamic Aviation Occu-Med intelligence report: February 19, 2026",
  summary:
    "Dynamic Aviation Group is a privately held special-mission aviation and MRO entity headquartered in Bridgewater, Virginia. The uploaded report emphasizes that Dynamic publishes no TRIR, DART, or workers' comp data, so its injury profile must be modeled from worker populations: aircraft mechanics / MRO technicians, pilots and flight crew, USFS aerial firefighting support, and ISR/ground support staff. The account is not a desk-job company. It is a hangar-floor, flight-line, composite-shop, wildfire-aviation, and special-mission aircraft operator with recurring FAA medical, aviation MRO, chemical/noise, composite dust, seasonal wildfire, and DBA exposure lanes.",
  tags: [
    "Entity profile",
    "Dynamic Aviation",
    "Aviation MRO",
    "Special mission aircraft",
    "ISR",
    "USFS wildfire aviation",
    "Composite shop",
    "FAA medicals",
    "Bridgewater VA",
    "Rockingham County expansion",
    "DBA exposure",
  ],
  aliases: ["Dynamic Aviation", "Dynamic Aviation Group", "Dynamic Aviation Group Inc"],
  sourceFilters: {
    sam: { legalNames: ["Dynamic Aviation Group", "Dynamic Aviation"] },
    usaSpending: { recipientNames: ["Dynamic Aviation"] },
    jobSources: { linkedin: "dynamic-aviation", careerSite: "https://www.dynamicaviation.com/careers" },
    newsSources: { aliases: ["Dynamic Aviation", "Bridgewater", "King Air", "USFS Air Attack", "ICE-MAN", "Rockingham County"] },
  },
  executiveSignals: [
    { label: "Expected injuries", value: "14-17/yr", note: "BLS benchmark model across MRO, pilot/flight crew, wildfire aviation, and ISR/ground support worker populations." },
    { label: "Direct cost", value: "$612K-$1.25M/yr", note: "Modeled direct annual injury cost range from uploaded worker-population table." },
    { label: "MRO benchmark", value: "TRIR 3.40", note: "NAICS 488190 aircraft mechanics and aviation support services carry high injury risk." },
    { label: "Growth signal", value: "+207 jobs", note: "Uploaded report links Rockingham County expansion to a higher-risk post-growth MRO workforce environment." },
  ],
  curveTitle: "Dynamic Aviation MRO, wildfire aviation, and FAA/DBA readiness curve",
  curveSubtitle:
    "Uploaded Dynamic Aviation Occu-Med report normalized into entity-profile charts; modeled values should be validated against internal headcount, flight operations, and exam cycle data.",
  chartDefinitions: [
    {
      id: "dynamic-worker-risk",
      title: "Dynamic Aviation worker risk by BLS TRIR benchmark",
      subtitle: "Aircraft mechanics, MRO technicians, wildfire aviation, and flight crew are the core exposure groups.",
      type: "bar",
      xKey: "workerType",
      data: [
        { workerType: "Aircraft MRO Techs", trir: 3.4, headcount: 250, injuries: 8.5 },
        { workerType: "Pilots / Flight Crew", trir: 2.8, headcount: 150, injuries: 4.5 },
        { workerType: "USFS Firefighting", trir: 4.5, headcount: 50, injuries: 1.5 },
        { workerType: "ISR / Ground Support", trir: 0.6, headcount: 125, injuries: 0.75 },
      ],
      series: [{ dataKey: "trir", name: "BLS / analog TRIR", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 5],
      headline: "worker risk",
      fullWidth: true,
    },
    {
      id: "dynamic-expected-injuries",
      title: "Expected injuries by worker population",
      subtitle: "Uploaded report estimates total injuries at about 14-17 per year.",
      type: "bar",
      xKey: "workerType",
      data: [
        { workerType: "MRO Techs", injuries: 8.5 },
        { workerType: "Pilots / Crew", injuries: 4.5 },
        { workerType: "USFS Firefighting", injuries: 1.5 },
        { workerType: "ISR / Office", injuries: 0.75 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/yr", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "injury model",
    },
    {
      id: "dynamic-cost-range",
      title: "Modeled direct annual injury cost",
      subtitle: "Uploaded table: direct annual cost by worker category.",
      type: "grouped",
      xKey: "workerType",
      data: [
        { workerType: "MRO Techs", low: 360, high: 675 },
        { workerType: "Pilots / Crew", low: 180, high: 375 },
        { workerType: "USFS Firefighting", low: 45, high: 150 },
        { workerType: "ISR / Office", low: 27, high: 45 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "direct cost",
      fullWidth: true,
    },
    {
      id: "dynamic-severe-injury-context",
      title: "Aircraft mechanic severe-injury context",
      subtitle: "Uploaded report: U.S. aircraft mechanic severe injuries doubled in 2022 during rapid restaffing conditions.",
      type: "line",
      xKey: "year",
      data: [
        { year: "2015", severe: 14 },
        { year: "2016", severe: 13 },
        { year: "2017", severe: 19 },
        { year: "2018", severe: 16 },
        { year: "2019", severe: 15 },
        { year: "2020", severe: 11 },
        { year: "2021", severe: 12 },
        { year: "2022", severe: 30 },
      ],
      series: [{ dataKey: "severe", name: "Severe injuries", color: "#dc2626" }],
      headline: "MRO context",
    },
    {
      id: "dynamic-medical-priority",
      title: "Dynamic Aviation Occu-Med priority map",
      subtitle: "Priority lanes from MRO, composite shop, pilot FAA cycles, wildfire aviation, and OCONUS support.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "MRO pre-placement", priority: 10 },
        { lane: "Composite respiratory", priority: 9 },
        { lane: "Hearing conservation", priority: 9 },
        { lane: "FAA pilot medicals", priority: 9 },
        { lane: "Wildfire readiness", priority: 8 },
        { lane: "DBA OCONUS baseline", priority: 8 },
        { lane: "Flight-line chemical exposure", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "priority map",
    },
  ],
  metricDefinitions: [
    { id: "dynamic-employees", label: "Employees", value: 575, unit: "count", category: "workforce" },
    { id: "dynamic-revenue-low", label: "Revenue low", value: 163, unit: "usd", category: "financial" },
    { id: "dynamic-revenue-high", label: "Revenue high", value: 212, unit: "usd", category: "financial" },
    { id: "dynamic-expected-injuries-low", label: "Expected injuries low", value: 14, unit: "count", category: "safety" },
    { id: "dynamic-expected-injuries-high", label: "Expected injuries high", value: 17, unit: "count", category: "safety" },
    { id: "dynamic-direct-cost-low", label: "Direct cost low", value: 0.612, unit: "usd", category: "financial" },
    { id: "dynamic-direct-cost-high", label: "Direct cost high", value: 1.25, unit: "usd", category: "financial" },
    { id: "dynamic-mro-workers", label: "MRO workers", value: 250, unit: "count", category: "workforce" },
    { id: "dynamic-expansion-jobs", label: "Expansion jobs", value: 207, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "Aircraft MRO techs", revenue: 675, risk: 9.5, workers: 250 },
    { name: "Pilots / flight crew", revenue: 375, risk: 8.0, workers: 150 },
    { name: "USFS wildfire aviation", revenue: 150, risk: 10.0, workers: 50 },
    { name: "Composite shop", revenue: 200, risk: 8.5, workers: 60 },
    { name: "ISR / OCONUS crew", revenue: 125, risk: 8.0, workers: 100 },
  ],
  opportunityMatrix: [
    { name: "MRO Pre-Placement", revenuePotential: 250, implementationComplexity: 5, strategicValue: 9 },
    { name: "FAA AME Medicals", revenuePotential: 150, implementationComplexity: 7, strategicValue: 9 },
    { name: "Hearing Conservation", revenuePotential: 120, implementationComplexity: 4, strategicValue: 8 },
    { name: "Composite Respiratory Surveillance", revenuePotential: 100, implementationComplexity: 6, strategicValue: 8 },
    { name: "Wildfire / OCONUS Readiness", revenuePotential: 90, implementationComplexity: 7, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Dynamic Aviation is a small-to-mid-size special mission aviation entity, but the work is physical and specialized. The report says the injury story is built from MRO, flight crew, wildfire aviation, and ISR/ground support populations because no public TRIR or workers' comp data is available.",
      bullets: [
        "Privately held and headquartered in Bridgewater, Virginia.",
        "Estimated workforce is about 575 employees.",
        "Estimated annual revenue is about $163M-$212M.",
        "The report models 14-17 injuries per year and $612K-$1.25M in direct annual injury cost.",
      ],
      metricIds: ["dynamic-employees", "dynamic-expected-injuries-high", "dynamic-direct-cost-high"],
    },
    {
      type: "safety",
      title: "MRO and composite-shop exposure",
      narrative:
        "The core exposure is aircraft mechanics and MRO technicians. The uploaded report highlights falls, struck-by/pinch points, flight-line vehicle exposure, aviation fuels, Skydrol, paint/primer/solvents, engine-runup noise, and composite dust from grinding, sanding, and cutting carbon fiber and fiberglass.",
      bullets: [
        "Aircraft MRO technicians are modeled at NAICS 488190 TRIR 3.40.",
        "A new 33,000-square-foot hangar and 13,000-square-foot composite shop increase the need for respiratory and hearing surveillance.",
        "The 2022 aircraft mechanic severe-injury spike is used as a growth-phase caution signal.",
      ],
      metricIds: ["dynamic-mro-workers", "dynamic-expansion-jobs"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The strongest Occu-Med lanes are MRO pre-placement, FAA AME medical cycles for pilots, hearing conservation, respirator/composite exposure surveillance, wildfire aviation readiness, and DBA baseline support for OCONUS ISR or government missions.",
      bullets: [
        "FAA pilot medicals are recurring, federally regulated exam streams if AME coverage is available.",
        "Wildfire aviation is seasonal but intense and benefits from pre-season readiness review.",
        "DBA applies to qualifying OCONUS government-contract deployments.",
      ],
      metricIds: [],
    },
  ],
};
