import type { CompanyConfig } from "./types";

export const fluorConfig: CompanyConfig = {
  companyId: "fluor",
  displayName: "Fluor Corporation",
  shortName: "Fluor",
  sector:
    "Global EPC, engineering and construction, energy solutions, urban solutions, DOE nuclear cleanup, mission solutions, base operations, and high-hazard megaprojects",
  headquarters: "Irving, Texas",
  employees: 26866,
  employeesAsOf: "Uploaded Fluor Occu-Med intelligence report: 2024 company snapshot",
  summary:
    "Fluor Corporation is a global EPC and government mission-solutions entity with 26,866 employees, $16.3B 2024 revenue, and $28.5B backlog. The uploaded Occu-Med report frames Fluor as Amentum plus Weatherford plus DOE nuclear exposure in one company: strong headline safety performance, major construction and energy megaproject exposure, DOE nuclear cleanup and mission support, and high-severity contractor events in 2024. The right sales frame is not that Fluor lacks safety maturity; it is that high-quality occupational medicine protects top-tier safety performance in high-hazard construction, energy, nuclear cleanup, and mission-support populations.",
  tags: [
    "Entity profile",
    "Fluor",
    "EPC",
    "Engineering construction",
    "DOE nuclear cleanup",
    "Mission Solutions",
    "Savannah River Site",
    "10 CFR 851",
    "High-potential incidents",
    "Contractor safety",
    "Megaprojects",
  ],
  aliases: ["Fluor", "Fluor Corporation", "FLR", "Fluor Mission Solutions", "Fluor Federal Services"],
  sourceFilters: {
    sec: { ticker: "FLR", legalEntities: ["Fluor Corporation"] },
    sam: { legalNames: ["Fluor Corporation", "Fluor Federal Services", "Fluor Mission Solutions"] },
    usaSpending: { recipientNames: ["Fluor", "Fluor Federal Services"] },
    jobSources: { linkedin: "fluor", careerSite: "https://www.fluor.com/careers" },
    newsSources: { aliases: ["Fluor", "Fluor Corporation", "Savannah River Site", "SRNS", "SRMC", "Hanford", "DOE nuclear cleanup"] },
  },
  executiveSignals: [
    { label: "2024 revenue", value: "$16.3B", note: "Uploaded report lists 2024 revenue at $16.3B, up 5% year over year." },
    { label: "Backlog", value: "$28.5B", note: "2024 backlog is listed at $28.5B." },
    { label: "TCIR", value: "0.31", note: "Strong headline safety performance versus large-contractor benchmark, though slightly worse than 2023." },
    { label: "High-potential events", value: "135", note: "Uploaded report highlights 135 high-potential incidents threatening serious injury, severe outcome, or damage." },
  ],
  curveTitle: "Fluor EPC, DOE nuclear, and high-severity safety curve",
  curveSubtitle:
    "Uploaded Fluor Occu-Med report normalized into entity-profile charts; safety, revenue, and opportunity values are modeled strategic intelligence, not operating guidance.",
  chartDefinitions: [
    {
      id: "fluor-safety-trend",
      title: "Fluor TCIR and DART trend",
      subtitle: "Uploaded report combines 2019-2024 trend values and 2024 disclosed metrics.",
      type: "grouped",
      xKey: "year",
      data: [
        { year: "2019", tcir: 0.36, dart: 0.19 },
        { year: "2020", tcir: 0.38, dart: 0.21 },
        { year: "2021", tcir: 0.37, dart: 0.20 },
        { year: "2022", tcir: 0.34, dart: 0.18 },
        { year: "2023", tcir: 0.29, dart: 0.15 },
        { year: "2024", tcir: 0.31, dart: 0.17 },
      ],
      series: [
        { dataKey: "tcir", name: "TCIR", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "dart", name: "DART", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      domain: [0, 0.5],
      headline: "safety trend",
      fullWidth: true,
    },
    {
      id: "fluor-safety-context",
      title: "2024 safety context",
      subtitle: "Low TCIR exists alongside high-potential events and life-altering injuries.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Recordables", value: 366 },
        { metric: "High-potential", value: 135 },
        { metric: "Life-altering", value: 2 },
        { metric: "DART x100", value: 17 },
        { metric: "TCIR x100", value: 31 },
      ],
      series: [{ dataKey: "value", name: "Count / scaled rate", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "severity context",
    },
    {
      id: "fluor-business-segments",
      title: "Fluor business segment risk lanes",
      subtitle: "Urban, Energy, and Mission Solutions drive different occupational medicine protocols.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "Urban Solutions", priority: 8 },
        { segment: "Energy Solutions", priority: 9 },
        { segment: "Mission Solutions / DOE", priority: 10 },
        { segment: "Government support", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "segment risk",
    },
    {
      id: "fluor-financial-scale",
      title: "Fluor scale indicators",
      subtitle: "Revenue, backlog, and exposure hours create large denominator risk.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Revenue ($B)", value: 16.3 },
        { metric: "Backlog ($B)", value: 28.5 },
        { metric: "Exposure hrs (10M)", value: 23.8 },
        { metric: "Employees (10K)", value: 2.6866 },
      ],
      series: [{ dataKey: "value", name: "Scaled value", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "scale",
      fullWidth: true,
    },
    {
      id: "fluor-medical-priority",
      title: "Fluor Occu-Med priority map",
      subtitle: "High-value lanes from construction, energy, nuclear cleanup, and base operations.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "DOE nuclear surveillance", priority: 10 },
        { lane: "Construction pre-placement", priority: 9 },
        { lane: "Confined space / respirator", priority: 9 },
        { lane: "Heat readiness", priority: 8 },
        { lane: "Crane / equipment operator", priority: 8 },
        { lane: "Hand injury / fit-for-duty", priority: 8 },
        { lane: "OCONUS/base operations", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "priority map",
    },
  ],
  metricDefinitions: [
    { id: "fluor-employees", label: "Employees", value: 26866, unit: "count", category: "workforce" },
    { id: "fluor-revenue", label: "2024 revenue", value: 16.3, unit: "usd", category: "financial" },
    { id: "fluor-backlog", label: "2024 backlog", value: 28.5, unit: "usd", category: "financial" },
    { id: "fluor-tcir", label: "2024 TCIR", value: 0.31, unit: "score", category: "safety" },
    { id: "fluor-dart", label: "2024 DART", value: 0.17, unit: "score", category: "safety" },
    { id: "fluor-recordables", label: "2024 recordables", value: 366, unit: "count", category: "safety" },
    { id: "fluor-high-potential", label: "High-potential events", value: 135, unit: "count", category: "safety" },
    { id: "fluor-exposure-hours", label: "Exposure hours", value: 238, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "DOE nuclear cleanup", revenue: 4500, risk: 10.0, workers: 6000 },
    { name: "Energy megaprojects", revenue: 3000, risk: 9.0, workers: 12000 },
    { name: "Urban construction", revenue: 2500, risk: 8.5, workers: 10000 },
    { name: "Base operations", revenue: 1000, risk: 7.0, workers: 3000 },
    { name: "Corporate / engineering", revenue: 500, risk: 3.0, workers: 5000 },
  ],
  opportunityMatrix: [
    { name: "DOE Medical Surveillance", revenuePotential: 1500, implementationComplexity: 9, strategicValue: 10 },
    { name: "Construction Pre-Placement", revenuePotential: 1200, implementationComplexity: 6, strategicValue: 9 },
    { name: "Respirator / Confined Space", revenuePotential: 800, implementationComplexity: 6, strategicValue: 9 },
    { name: "Heat Readiness", revenuePotential: 500, implementationComplexity: 5, strategicValue: 8 },
    { name: "Equipment Operator FFD", revenuePotential: 450, implementationComplexity: 5, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Fluor should be treated as a top-tier safety performer operating in unusually high-hazard environments. The profile is a safety-sustainment and regulatory-depth account, not a basic physicals account.",
      bullets: [
        "2024 revenue was $16.3B and backlog was $28.5B.",
        "Segments include Urban Solutions, Energy Solutions, and Mission Solutions.",
        "Fluor reported 238 million exposure hours in 2024, equivalent to a much larger project workforce than employee headcount alone implies.",
        "TCIR of 0.31 is strong, but high-potential incidents show the risk environment remains significant.",
      ],
      metricIds: ["fluor-employees", "fluor-revenue", "fluor-backlog", "fluor-tcir"],
    },
    {
      type: "safety",
      title: "Headline safety is strong, severity exposure remains real",
      narrative:
        "The uploaded report emphasizes that Fluor's low TCIR must be interpreted beside high-potential events, life-altering injuries, and contractor severity exposure.",
      bullets: [
        "2024 TCIR was 0.31 and DART was 0.17.",
        "The report lists 366 recordable incidents and 135 high-potential incidents in 2024.",
        "High-potential events far exceed the small number of severe outcomes, meaning preventive screening and surveillance still matter.",
        "Hand/finger injuries are called out as a major severity driver.",
      ],
      metricIds: ["fluor-recordables", "fluor-high-potential", "fluor-dart"],
    },
    {
      type: "medical-opportunities",
      title: "DOE nuclear and megaproject medical opportunity",
      narrative:
        "The highest-value lanes are DOE nuclear cleanup and high-hazard construction environments where occupational medicine must connect to industrial hygiene, radiation/chemical surveillance, respirator clearance, confined-space fitness, and job-specific pre-placement exams.",
      bullets: [
        "Mission Solutions includes DOE nuclear and environmental cleanup at sites such as Savannah River, Hanford legacy work, Fernald, and Portsmouth.",
        "10 CFR 851 Worker Safety and Health Program makes occupational medicine part of the regulated safety architecture.",
        "Energy and Urban Solutions create hot work, heavy lift, confined space, work-at-height, and extreme-temperature screening needs.",
      ],
      metricIds: [],
    },
  ],
};
