import type { CompanyConfig } from "./types";

export const freeportConfig: CompanyConfig = {
  companyId: "freeport-mcmoran",
  displayName: "Freeport-McMoRan",
  shortName: "FCX",
  sector:
    "Copper mining, molybdenum, gold, open-pit mining, underground mining, contractor safety, MSHA-regulated operations, Sierrita Mine enforcement, executive TRIR incentives, and hearing conservation",
  headquarters: "Phoenix, Arizona",
  employees: 26700,
  employeesAsOf: "Uploaded Freeport-McMoRan Occu-Med intelligence report: 2024 safety dataset",
  summary:
    "Freeport-McMoRan is a global copper, molybdenum, and gold mining entity whose 2024 safety data tells two stories at once. The headline TRIR was 0.69, essentially flat year-over-year and about 62% below the BLS copper mining benchmark of 1.80. Underneath that headline, employee TRIR worsened from 0.75 to 0.77, employee LTIR worsened from 0.31 to 0.33, near-miss frequency jumped 73% from 0.93 to 1.61, and fatalities rose from 2 to 5 — the worst year since 2015, with four contractor fatalities and one direct-employee fatality. The uploaded report frames the contractor population as the most actionable gap: if FCX's strongest medical screening and surveillance processes cover direct employees but not contractors, the population generating the worst outcomes may be outside the strongest medical controls. The Occu-Med pitch is contractor screening, MSHA surveillance, hearing conservation, fit-for-duty, near-miss analytics, and executive-value protection because FCX's Annual Incentive Plan includes a 15% safety/TRIR component tied to executive compensation.",
  tags: [
    "Entity profile",
    "Freeport-McMoRan",
    "FCX",
    "Copper mining",
    "MSHA",
    "Contractor fatalities",
    "Near misses",
    "CEO bonus TRIR",
    "Executive compensation",
    "Hearing conservation",
    "Sierrita Mine",
    "Contractor screening",
  ],
  aliases: ["FCX", "Freeport McMoRan", "Freeport-McMoRan", "Freeport-McMoRan Inc."],
  sourceFilters: {
    sec: { ticker: "FCX", legalEntities: ["Freeport-McMoRan Inc."] },
    sam: { legalNames: ["Freeport-McMoRan"] },
    usaSpending: { recipientNames: ["Freeport-McMoRan", "FCX"] },
    newsSources: { aliases: ["Freeport-McMoRan", "FCX", "Sierrita", "Morenci", "Bagdad Mine", "Safford Mine", "Kathleen Quirk"] },
  },
  executiveSignals: [
    { label: "2024 TRIR", value: "0.69", note: "Headline total TRIR was flat and 62% below the BLS copper mining benchmark of 1.80." },
    { label: "Near misses", value: "+73%", note: "Near Miss Frequency Rate increased from 0.93 to 1.61 year over year." },
    { label: "Fatalities", value: "5", note: "Worst year since 2015; uploaded report says four contractor fatalities and one employee fatality." },
    { label: "Economic value", value: "$28M-$42M", note: "Modeled North America direct injury cost avoided annually versus BLS copper mining benchmark." },
  ],
  curveTitle: "Freeport contractor fatality, near-miss, and TRIR-protection curve",
  curveSubtitle:
    "Uploaded Freeport Occu-Med report normalized into entity-profile charts; modeled savings and injury avoidance values are strategic estimates, not audited FCX financial disclosures.",
  chartDefinitions: [
    {
      id: "freeport-safety-two-stories",
      title: "FCX 2024 safety data tells two stories",
      subtitle: "Headline TRIR is strong, but employee TRIR, LTIR, near misses, and fatalities moved the wrong direction.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Total TRIR", value2024: 0.69, value2023: 0.70 },
        { metric: "Employee TRIR", value2024: 0.77, value2023: 0.75 },
        { metric: "Contractor TRIR", value2024: 0.57, value2023: 0.62 },
        { metric: "Near miss rate", value2024: 1.61, value2023: 0.93 },
        { metric: "LTIR employees", value2024: 0.33, value2023: 0.31 },
      ],
      series: [
        { dataKey: "value2023", name: "2023", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "value2024", name: "2024", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "two stories",
      fullWidth: true,
    },
    {
      id: "freeport-fatality-gap",
      title: "FCX 2024 fatality and contractor gap",
      subtitle: "Uploaded report: five 2024 fatalities, four contractors and one direct employee.",
      type: "bar",
      xKey: "population",
      data: [
        { population: "Contractors", fatalities: 4, trir2024: 0.57 },
        { population: "Employees", fatalities: 1, trir2024: 0.77 },
      ],
      series: [{ dataKey: "fatalities", name: "Fatalities", color: "#dc2626", radius: [10, 10, 0, 0] }],
      headline: "fatality split",
    },
    {
      id: "freeport-near-miss-warning",
      title: "Near-miss leading indicator flashing red",
      subtitle: "Near Miss Frequency Rate rose 73% from 0.93 to 1.61.",
      type: "bar",
      xKey: "year",
      data: [
        { year: "2023", nmfr: 0.93 },
        { year: "2024", nmfr: 1.61 },
      ],
      series: [{ dataKey: "nmfr", name: "Near miss frequency rate", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "near-miss jump",
    },
    {
      id: "freeport-economic-value",
      title: "North America injury avoidance value",
      subtitle: "Uploaded report: FCX performance vs BLS copper mining benchmark protects major direct and total economic value.",
      type: "bar",
      xKey: "valueType",
      data: [
        { valueType: "Direct low", value: 28 },
        { valueType: "Direct high", value: 42 },
        { valueType: "Total low", value: 56 },
        { valueType: "Total high", value: 210 },
        { valueType: "10% Occu-Med share low", value: 2.8 },
        { valueType: "10% Occu-Med share high", value: 21 },
      ],
      series: [{ dataKey: "value", name: "Annual value", color: "#22c55e", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "economic value",
      fullWidth: true,
    },
    {
      id: "freeport-executive-incentive",
      title: "Executive incentive alignment",
      subtitle: "Uploaded report: FCX Annual Incentive Plan includes a 15% safety/TRIR component for named executive officers.",
      type: "bar",
      xKey: "component",
      data: [
        { component: "Safety / TRIR", percent: 15 },
        { component: "Other AIP components", percent: 85 },
      ],
      series: [{ dataKey: "percent", name: "AIP weighting", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      headline: "executive tie",
    },
    {
      id: "freeport-occumed-priority",
      title: "Freeport Occu-Med priority map",
      subtitle: "Service lanes from contractor fatalities, MSHA enforcement, hearing conservation, and executive TRIR incentives.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "Contractor screening", priority: 10 },
        { lane: "MSHA hearing surveillance", priority: 9 },
        { lane: "Fit-for-duty", priority: 9 },
        { lane: "Near-miss medical analytics", priority: 8 },
        { lane: "Sierrita MSHA hotspot", priority: 8 },
        { lane: "Executive TRIR protection", priority: 10 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "priority map",
    },
  ],
  metricDefinitions: [
    { id: "freeport-employees", label: "Employees", value: 26700, unit: "count", category: "workforce" },
    { id: "freeport-trir", label: "2024 total TRIR", value: 0.69, unit: "score", category: "safety" },
    { id: "freeport-employee-trir", label: "2024 employee TRIR", value: 0.77, unit: "score", category: "safety" },
    { id: "freeport-contractor-trir", label: "2024 contractor TRIR", value: 0.57, unit: "score", category: "safety" },
    { id: "freeport-near-miss-rate", label: "2024 near miss rate", value: 1.61, unit: "score", category: "safety" },
    { id: "freeport-fatalities", label: "2024 fatalities", value: 5, unit: "count", category: "safety" },
    { id: "freeport-contractor-fatalities", label: "2024 contractor fatalities", value: 4, unit: "count", category: "safety" },
    { id: "freeport-na-direct-value-low", label: "NA direct value low", value: 28, unit: "usd", category: "financial" },
    { id: "freeport-na-direct-value-high", label: "NA direct value high", value: 42, unit: "usd", category: "financial" },
    { id: "freeport-aip-safety-weight", label: "Executive safety incentive weight", value: 15, unit: "score", category: "financial" },
  ],
  riskMatrix: [
    { name: "Contractor workforce", revenue: 42, risk: 10.0, workers: 5000 },
    { name: "Sierrita MSHA hotspot", revenue: 10, risk: 9.0, workers: 800 },
    { name: "Hearing conservation", revenue: 20, risk: 8.5, workers: 12000 },
    { name: "Employee TRIR trend", revenue: 15, risk: 8.0, workers: 26700 },
    { name: "Near-miss conversion", revenue: 21, risk: 8.5, workers: 26700 },
  ],
  opportunityMatrix: [
    { name: "Contractor Medical Screening", revenuePotential: 1200, implementationComplexity: 8, strategicValue: 10 },
    { name: "MSHA Hearing Conservation", revenuePotential: 900, implementationComplexity: 5, strategicValue: 9 },
    { name: "Fitness-for-Duty / Return-to-Work", revenuePotential: 750, implementationComplexity: 6, strategicValue: 9 },
    { name: "Executive TRIR-Protection Program", revenuePotential: 600, implementationComplexity: 7, strategicValue: 10 },
    { name: "Near-Miss Medical Analytics", revenuePotential: 450, implementationComplexity: 8, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Freeport's headline safety performance is strong, but the uploaded report argues the underlying picture is not simple: employee TRIR worsened, near misses rose sharply, and fatalities increased to the worst level since 2015.",
      bullets: [
        "Total TRIR was 0.69 in 2024, down slightly from 0.70 in 2023.",
        "Employee TRIR worsened from 0.75 to 0.77 while contractor TRIR improved from 0.62 to 0.57.",
        "Near Miss Frequency Rate increased 73% from 0.93 to 1.61.",
        "Fatalities rose from 2 in 2023 to 5 in 2024.",
      ],
      metricIds: ["freeport-trir", "freeport-employee-trir", "freeport-near-miss-rate", "freeport-fatalities"],
    },
    {
      type: "safety",
      title: "Contractor fatalities and medical-screening gap",
      narrative:
        "The uploaded report identifies contractor exposure as the most actionable safety gap. If contractor populations receive lower-standard or inconsistent medical screening, the highest-risk population may sit outside the strongest medical controls.",
      bullets: [
        "Four of five 2024 fatalities were contract personnel.",
        "Contractor TRIR improved year over year but remains much higher than its 2020 level in the uploaded analysis.",
        "The key question is whether FCX's occupational medicine program covers contractor populations at the same standard as direct employees.",
        "The sales conversation should connect contractor medical screening to fatality prevention, not just compliance paperwork.",
      ],
      metricIds: ["freeport-contractor-fatalities", "freeport-contractor-trir"],
    },
    {
      type: "financial",
      title: "Executive compensation and economic value",
      narrative:
        "The uploaded report says FCX's annual incentive plan allocates 15% of every named executive officer's annual bonus to safety/TRIR performance. That creates a direct executive-value story for incremental injury prevention.",
      bullets: [
        "At North America scale, the report models $28M-$42M in direct injury cost avoided annually versus BLS copper mining benchmarks.",
        "Including indirect costs, total economic value is modeled at $56M-$210M.",
        "If occupational medicine contributes even 10% of that avoidance, the protected value is modeled at $2.8M-$21M annually.",
        "Executive compensation alignment makes TRIR reduction a leadership-value argument, not just an EHS compliance argument.",
      ],
      metricIds: ["freeport-na-direct-value-low", "freeport-na-direct-value-high", "freeport-aip-safety-weight"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The Freeport conversation should be framed as contractor fatality reduction, TRIR protection, MSHA surveillance, and executive-value protection, not generic mining physicals.",
      bullets: [
        "Contractor screening and fit-for-duty should be prioritized because contractors accounted for most 2024 fatalities.",
        "MSHA Part 62 hearing conservation and Part 56/57 medical-record quality are important compliance lanes.",
        "Sierrita Mine should be treated as an enforcement hotspot because the uploaded report flags high 2025 MSHA penalties.",
      ],
      metricIds: [],
    },
  ],
};
