import type { CompanyConfig } from "./types";

export const globalOperationalSitesIntelligenceConfig: CompanyConfig = {
  companyId: "global-operational-sites-intelligence",
  displayName: "Global Operational Sites Intelligence",
  shortName: "Operational Sites",
  sector:
    "Entity operational-site mapping, country/city/facility-type capture, Leidos/PAE/CACI/GDIT site research, innovation-center location logic, CONUS/OCONUS clinic targeting, and provider-network branch research",
  headquarters: "Occu-Med portfolio-level operational-site research",
  employees: 0,
  employeesAsOf:
    "Uploaded Grok operational-sites export: 37-page Leidos, PAE, CACI, GDIT, and related client/prospect site research transcript",
  summary:
    "Global Operational Sites Intelligence normalizes the uploaded operational-site research transcript into one portfolio entity. The file began with Leidos and PAE, then expanded into Leidos Innovations Center, CACI International, GDIT, Platform Aerospace, Dynamic Aviation, Camber, Global Linguist Solutions, APV, Alutiiq Essential Services, BAE Systems, IAP Worldwide, Jacobs Technology, Mission Essential, Patriot Group International, and Group SSI. The key app value is not to duplicate every company profile. It is to preserve country, city/area, and facility-type intelligence as a network-research layer that can feed provider coverage work. Leidos has a broad global footprint across Australia, Bahrain, Canada, Cuba, Djibouti, Germany, India, Ireland, Israel, Italy, Japan, Saudi Arabia, South Korea, Turkey, UAE, UK, and the US; Leidos Innovations Center is US-only R&D; legacy PAE/Amentum sites include Australia, France, Japan, New Zealand, South Korea, UK, and a large US footprint; CACI and GDIT have broad domestic and selective OCONUS support nodes.",
  tags: [
    "Entity profile",
    "Operational sites",
    "Leidos",
    "PAE",
    "Amentum",
    "CACI",
    "GDIT",
    "Leidos Innovations Center",
    "Platform Aerospace",
    "Dynamic Aviation",
    "Camber",
    "Global Linguist Solutions",
    "Alutiiq",
    "IAP Worldwide",
    "Jacobs Technology",
    "Mission Essential",
    "Group SSI",
  ],
  aliases: ["Operational Sites", "Leidos PAE Global Operational Sites", "Grok Operational Sites Export", "Client Site Research"],
  sourceFilters: {
    newsSources: {
      aliases: [
        "Leidos operational sites",
        "PAE operational sites",
        "CACI operational sites",
        "GDIT operational sites",
        "Leidos Innovations Center sites",
      ],
    },
  },
  executiveSignals: [
    { label: "Primary entities", value: "16+", note: "The uploaded transcript covers Leidos, PAE/Amentum, CACI, GDIT, and additional defense/language/aviation entities." },
    { label: "Leidos footprint", value: "17 countries", note: "Leidos section lists presence across Australia, Middle East, Europe, APAC, North America, and the United States." },
    { label: "LInC pattern", value: "US-only R&D", note: "Leidos Innovations Center is framed as US-only due to classified/national-security R&D concentration." },
    { label: "Use case", value: "Network research", note: "This file is best used as location/facility-type source data, not as a separate employer sales report." },
  ],
  curveTitle: "Operational-site capture, facility-type, and network research curve",
  curveSubtitle:
    "Uploaded operational-sites transcript normalized into a portfolio entity. Site labels marked details-limited should be verified before provider outreach.",
  chartDefinitions: [
    {
      id: "operational-sites-entity-coverage",
      title: "Operational-site research coverage by entity group",
      subtitle: "Approximate count of entity sections in the uploaded transcript.",
      type: "bar",
      xKey: "entityGroup",
      data: [
        { entityGroup: "Leidos + LInC", sections: 2 },
        { entityGroup: "PAE / Amentum", sections: 1 },
        { entityGroup: "CACI", sections: 1 },
        { entityGroup: "GDIT", sections: 2 },
        { entityGroup: "Aviation / platform", sections: 3 },
        { entityGroup: "Language / staffing", sections: 4 },
        { entityGroup: "Other services", sections: 4 },
      ],
      series: [{ dataKey: "sections", name: "Research sections", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "coverage breadth",
      fullWidth: true,
    },
    {
      id: "leidos-country-footprint",
      title: "Leidos countries captured in the site transcript",
      subtitle: "Country-level site footprint from the uploaded Leidos section.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "Australia", sites: 7 },
        { region: "United Kingdom", sites: 10 },
        { region: "United States", sites: 37 },
        { region: "Japan", sites: 5 },
        { region: "Saudi Arabia", sites: 5 },
        { region: "Italy", sites: 4 },
        { region: "Other countries", sites: 13 },
      ],
      series: [{ dataKey: "sites", name: "Listed sites / areas", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "Leidos footprint",
      fullWidth: true,
    },
    {
      id: "leidos-innovation-center",
      title: "Leidos Innovations Center R&D nodes",
      subtitle: "The transcript separates LInC from Leidos global operations; public footprint is US R&D only.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "Arlington VA", priority: 10 },
        { site: "Dayton OH", priority: 9 },
        { site: "Albuquerque NM", priority: 9 },
        { site: "San Diego CA", priority: 9 },
        { site: "Beavercreek OH", priority: 8 },
        { site: "Huntsville AL", priority: 8 },
        { site: "St. Petersburg FL", priority: 7 },
        { site: "Ann Arbor MI", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "R&D priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "LInC nodes",
    },
    {
      id: "pae-legacy-operational-sites",
      title: "PAE / Amentum legacy operational-site spread",
      subtitle: "The uploaded transcript lists PAE legacy locations now integrated into Amentum.",
      type: "bar",
      xKey: "countryOrRegion",
      data: [
        { countryOrRegion: "United States", sites: 26 },
        { countryOrRegion: "United Kingdom", sites: 2 },
        { countryOrRegion: "Australia", sites: 1 },
        { countryOrRegion: "France", sites: 1 },
        { countryOrRegion: "Japan", sites: 1 },
        { countryOrRegion: "New Zealand", sites: 1 },
        { countryOrRegion: "South Korea", sites: 1 },
      ],
      series: [{ dataKey: "sites", name: "Listed sites", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "PAE legacy",
    },
    {
      id: "facility-type-use-case",
      title: "Facility-type information use case",
      subtitle: "How the site research should feed the app.",
      type: "bar",
      xKey: "useCase",
      data: [
        { useCase: "Provider-radius check", priority: 10 },
        { useCase: "Facility-type medical lane", priority: 10 },
        { useCase: "OCONUS staging map", priority: 9 },
        { useCase: "Details-limited verification", priority: 8 },
        { useCase: "Client overlap table", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "app use case",
    },
  ],
  metricDefinitions: [
    { id: "ops-entity-sections", label: "Entity sections", value: 16, unit: "count", category: "workforce" },
    { id: "ops-leidos-countries", label: "Leidos listed countries", value: 17, unit: "count", category: "workforce" },
    { id: "ops-leidos-us-sites", label: "Leidos listed US sites", value: 37, unit: "count", category: "workforce" },
    { id: "ops-linc-sites", label: "LInC R&D nodes", value: 8, unit: "count", category: "workforce" },
    { id: "ops-pae-us-sites", label: "PAE listed US sites", value: 26, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "Leidos global footprint", revenue: 37, risk: 7.0, workers: 47000 },
    { name: "PAE/Amentum legacy sites", revenue: 26, risk: 8.0, workers: 18000 },
    { name: "GDIT OCONUS details-limited", revenue: 20, risk: 7.5, workers: 32000 },
    { name: "CACI details-limited OCONUS", revenue: 15, risk: 7.0, workers: 25000 },
    { name: "Aviation/platform entities", revenue: 12, risk: 8.5, workers: 2500 },
  ],
  opportunityMatrix: [
    { name: "Leidos Global Site Verification", revenuePotential: 4500, implementationComplexity: 7, strategicValue: 9 },
    { name: "PAE/Amentum Legacy Provider Audit", revenuePotential: 3400, implementationComplexity: 7, strategicValue: 9 },
    { name: "GDIT OCONUS Support Audit", revenuePotential: 2560, implementationComplexity: 7, strategicValue: 8 },
    { name: "CACI Site Coverage Audit", revenuePotential: 1200, implementationComplexity: 6, strategicValue: 8 },
    { name: "Details-Limited Cleanup", revenuePotential: 500, implementationComplexity: 4, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "This is a network research layer, not a duplicate dossier",
      narrative:
        "The uploaded transcript is most valuable as location/facility-type data. It helps answer where the app should check provider coverage, where multiple entities overlap, and which details-limited locations need verification.",
      bullets: [
        "Leidos and PAE were the starting point, but the transcript expanded into many additional entities.",
        "Leidos global operations and Leidos Innovations Center should be separated because LInC appears US-only R&D while Leidos overall is global.",
        "PAE should remain under the Amentum / PAE Legacy profile because PAE is no longer independent.",
      ],
      metricIds: ["ops-entity-sections", "ops-leidos-countries"],
    },
    {
      type: "locations",
      title: "How to use the location list",
      narrative:
        "Each country/city/facility-type line should eventually become a structured location record with entity, country, city/area, facility type, confidence level, and provider coverage status.",
      bullets: [
        "Details-limited records should be flagged as verification tasks, not treated as confirmed provider destinations.",
        "Operations sites, R&D facilities, data centers, aviation nodes, and headquarters should map to different Occu-Med service lanes.",
        "The biggest missing app feature is a structured location table tied to entity profiles and network coverage checks.",
      ],
      metricIds: ["ops-leidos-us-sites", "ops-linc-sites", "ops-pae-us-sites"],
    },
  ],
};
