import type { CompanyConfig } from "./types";

export const iapConfig: CompanyConfig = {
  companyId: "iap-worldwide",
  displayName: "IAP Worldwide Services",
  shortName: "IAP",
  sector: "Base operations, power generation, logistics, LOGCAP, and expeditionary support services",
  headquarters: "Cape Canaveral, Florida",
  employees: 6000,
  employeesAsOf: "Uploaded IAP dossier estimate",
  summary: "IAP Worldwide Services is a base-operations and power-generation contractor with heavy DBA exposure, OCONUS workforce concentration, and modeled revenue opportunities across pre-deploy exams, hearing conservation, electrical safety, and respirator clearance lanes.",
  tags: ["Base operations", "Power generation", "LOGCAP V", "DBA", "OCONUS", "Electrical safety"],
  aliases: ["IAP Worldwide Services", "IAP World Services"],
  executiveSignals: [
    { label: "LOGCAP V ceiling", value: "$120M", note: "Largest modeled active contract vehicle." },
    { label: "OCONUS workforce", value: "~80%", note: "Estimated OCONUS percentage driving DBA exposure." },
    { label: "Revenue potential", value: "$461K/yr", note: "DBA pre-deploy is the largest modeled exam lane." },
    { label: "Worker risk peak", value: "TRIR 3.9", note: "Logistics workers carry the highest benchmarked TRIR." },
  ],
  curveTitle: "IAP contract and workforce exposure curve",
  curveSubtitle: "Contract portfolio, DBA exposure, injury cost, revenue potential, and worker-risk values normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "iap-contracts",
      title: "IAP active contract revenue streams",
      subtitle: "Source: uploaded IAP visual; estimated annual value shown in $M.",
      type: "bar",
      xKey: "name",
      data: [{ name: "NSA Souda Bay", value: 9 }, { name: "DoD BOS IDIQ", value: 58 }, { name: "LOGCAP V", value: 120 }, { name: "GCS MAC III", value: 80 }, { name: "IAP-ECC JV", value: 25 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "IAP metric",
    },
    {
      id: "iap-dba-compare",
      title: "OCONUS workforce percentage / DBA exposure",
      subtitle: "Source: uploaded IAP comparison visual; estimated workforce OCONUS percentage.",
      type: "bar",
      xKey: "name",
      data: [{ name: "IDS Intl", oconus: 70 }, { name: "IAP", oconus: 80 }, { name: "Constellis", oconus: 15 }, { name: "GDIT", oconus: 5 }, { name: "Cloveltch", oconus: 10 }],
      series: [{ dataKey: "oconus", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 90],
      headline: "IAP metric",
    },
    {
      id: "iap-injury-cost",
      title: "IAP estimated annual DBA injury costs",
      subtitle: "Source: uploaded IAP visual; low DBA average plus additional modeled cost shown in $K.",
      type: "stacked",
      xKey: "name",
      data: [{ name: "Power Gen", low: 640, additional: 512 }, { name: "BOS Facilities", low: 375, additional: 300 }, { name: "Logistics", low: 780, additional: 624 }, { name: "Program Mgmt", low: 105, additional: 84 }],
      series: [
        { dataKey: "low", name: "Low DBA avg", color: "#22d3ee", stackId: "cost" },
        { dataKey: "additional", name: "Additional", color: "#ef4444", stackId: "cost", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "DBA cost stack",
    },
    {
      id: "iap-revenue",
      title: "IAP Occu-Med revenue by exam type",
      subtitle: "Source: uploaded IAP visual; annual revenue potential shown in $K.",
      type: "bar",
      xKey: "name",
      data: [{ name: "DBA Pre-Deploy", value: 245 }, { name: "Pre-Employment", value: 65 }, { name: "Hearing", value: 43 }, { name: "Electrical Safety", value: 45 }, { name: "Respirator", value: 45 }, { name: "DOT/CDL", value: 18 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "IAP metric",
    },
    {
      id: "iap-trir",
      title: "IAP worker risk by BLS TRIR benchmark",
      subtitle: "Source: uploaded IAP visual; worker category TRIR benchmark.",
      type: "bar",
      xKey: "name",
      data: [{ name: "Power Gen", value: 3.2 }, { name: "BOS Facilities", value: 2.5 }, { name: "Logistics", value: 3.9 }, { name: "Program Mgmt", value: 0.7 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "IAP metric",
      fullWidth: true,
    },
  ],
};
