import type { CompanyConfig } from "./types";

export const iapConfig: CompanyConfig = {
  companyId: "iap-worldwide",
  displayName: "IAP Worldwide Services",
  shortName: "IAP",
  sector:
    "Privately held logistics, contingency power generation, OCONUS base operations support, facilities maintenance, LOGCAP, GCS MAC III, and expeditionary services",
  headquarters: "Cape Canaveral, Florida",
  employees: 1400,
  employeesAsOf: "Uploaded Occu-Med intelligence report: estimated 1,400-1,502 employees",
  summary:
    "IAP Worldwide Services is a privately held logistics, power generation, and base operations support entity owned by Cerberus Capital Management. The uploaded Occu-Med intelligence model treats IAP as one of the highest OCONUS-ratio entities in the portfolio: its core physical workforce is concentrated in deployed power generation, logistics, and base operations where most serious injuries become DBA claims rather than state workers' compensation claims.",
  tags: [
    "Entity profile",
    "Base operations",
    "Power generation",
    "LOGCAP V",
    "GCS MAC III",
    "DBA exposure",
    "OCONUS",
    "Electrical safety",
    "Souda Bay",
    "FCA compliance trigger",
  ],
  aliases: ["IAP Worldwide Services", "IAP World Services", "IAP World Services, Inc.", "IAP Worldwide Services, Inc."],
  sourceFilters: {
    sam: { legalNames: ["IAP Worldwide Services", "IAP World Services, Inc.", "IAP Worldwide Services, Inc."] },
    usaSpending: { recipientNames: ["IAP Worldwide", "IAP World Services", "IAP Worldwide Services"] },
    jobSources: { linkedin: "iap-worldwide-services", careerSite: "https://www.iapws.com/" },
    newsSources: { aliases: ["IAP Worldwide Services", "IAP World Services", "IAP", "Cerberus IAP"] },
  },
  executiveSignals: [
    {
      label: "Expected injuries",
      value: "~39/yr",
      note: "Modeled from BLS benchmarks applied to IAP's workforce composition: power generation, BOS facilities, logistics, and technical staff.",
    },
    {
      label: "DBA cost exposure",
      value: "$1.95M–$3.5M/yr",
      note: "Modeled annual DBA injury-cost range; OCONUS injuries carry unlimited DBA medical exposure.",
    },
    {
      label: "OCONUS ratio",
      value: "~80%",
      note: "Uploaded report states IAP has the highest OCONUS physical-workforce ratio in the reviewed portfolio.",
    },
    {
      label: "Occu-Med potential",
      value: "~$450K/yr midpoint",
      note: "Revenue potential is driven by DBA pre-deploy medicals, electrical safety, hearing conservation, respirator clearance, and LOGCAP surge readiness.",
    },
  ],
  curveTitle: "IAP OCONUS DBA exposure and surge-readiness curve",
  curveSubtitle:
    "Uploaded Occu-Med intelligence values normalized for entity-profile scanning; modeled estimates should be treated as assumption-driven signals, not audited employer disclosures.",
  chartDefinitions: [
    {
      id: "iap-worker-risk",
      title: "IAP worker risk by BLS TRIR benchmark",
      subtitle: "Uploaded report: logistics/supply chain and power generation carry the highest benchmarked physical-work risk.",
      type: "bar",
      xKey: "workerType",
      data: [
        { workerType: "Power Gen / Electrical", trir: 3.2, headcount: 400, injuries: 13 },
        { workerType: "BOS Facilities", trir: 2.5, headcount: 300, injuries: 8 },
        { workerType: "Logistics / Supply", trir: 3.9, headcount: 400, injuries: 16 },
        { workerType: "Program Mgmt / Tech", trir: 0.7, headcount: 300, injuries: 2 },
      ],
      series: [{ dataKey: "trir", name: "BLS TRIR benchmark", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 4.5],
      headline: "worker risk",
      fullWidth: true,
    },
    {
      id: "iap-expected-injuries",
      title: "Expected injuries by workforce lane",
      subtitle: "BLS benchmark injuries by IAP worker type; total modeled estimate is roughly 39 injuries per year.",
      type: "bar",
      xKey: "workerType",
      data: [
        { workerType: "Power Gen / Electrical", injuries: 13 },
        { workerType: "BOS Facilities", injuries: 8 },
        { workerType: "Logistics / Supply", injuries: 16 },
        { workerType: "Program Mgmt / Tech", injuries: 2 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/yr", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "injury model",
    },
    {
      id: "iap-contract-streams",
      title: "IAP active contract revenue streams",
      subtitle: "Uploaded report: active/latent contract streams converted into annualized intelligence signals in $M.",
      type: "bar",
      xKey: "contract",
      data: [
        { contract: "NSA Souda Bay", value: 9 },
        { contract: "DoD BOS IDIQ", value: 58 },
        { contract: "LOGCAP V", value: 120 },
        { contract: "GCS MAC III", value: 80 },
        { contract: "IAP-ECC JV", value: 25 },
      ],
      series: [{ dataKey: "value", name: "Estimated annual value", color: "#f97316", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "contract streams",
    },
    {
      id: "iap-oconus-dba-comparison",
      title: "OCONUS workforce percentage / DBA exposure comparison",
      subtitle: "Uploaded report: IAP has the highest estimated OCONUS physical-workforce ratio in the reviewed portfolio.",
      type: "bar",
      xKey: "entity",
      data: [
        { entity: "IDS International", oconus: 70 },
        { entity: "IAP Worldwide", oconus: 80 },
        { entity: "Constellis", oconus: 15 },
        { entity: "GDIT", oconus: 5 },
        { entity: "Clovehitch", oconus: 10 },
      ],
      series: [{ dataKey: "oconus", name: "Estimated workforce OCONUS", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 90],
      headline: "DBA exposure",
    },
    {
      id: "iap-dba-injury-cost",
      title: "IAP estimated annual DBA injury costs",
      subtitle: "Modeled annual DBA injury cost range by worker category, shown in $K.",
      type: "bar",
      xKey: "workerType",
      data: [
        { workerType: "Power Gen", low: 650, high: 1200 },
        { workerType: "BOS Facilities", low: 400, high: 720 },
        { workerType: "Logistics", low: 800, high: 1400 },
        { workerType: "Program Mgmt", low: 100, high: 180 },
      ],
      series: [
        { dataKey: "low", name: "Low estimate", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High estimate", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "DBA cost",
      fullWidth: true,
    },
    {
      id: "iap-revenue-potential",
      title: "IAP Occu-Med revenue by exam type",
      subtitle: "Uploaded report: midpoint opportunity is roughly $450K/year, led by DBA pre-deploy medicals.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "DBA Pre-Deploy", revenue: 245 },
        { examType: "Pre-Employment", revenue: 65 },
        { examType: "Hearing", revenue: 43 },
        { examType: "Electrical Safety", revenue: 45 },
        { examType: "Respirator", revenue: 45 },
        { examType: "DOT/CDL", revenue: 18 },
      ],
      series: [{ dataKey: "revenue", name: "Annual revenue potential", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "revenue potential",
    },
    {
      id: "iap-surge-readiness",
      title: "LOGCAP V / GCS MAC III surge-readiness lanes",
      subtitle: "Contingency activation could rapidly scale IAP deployment medical demand beyond routine BOS activity.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "DBA pre-deploy protocol", priority: 10 },
        { lane: "1910.269 electrical fitness", priority: 10 },
        { lane: "Hearing conservation", priority: 8 },
        { lane: "Respirator clearance", priority: 8 },
        { lane: "Heat-stress screening", priority: 7 },
        { lane: "DOT/CDL", priority: 4 },
      ],
      series: [{ dataKey: "priority", name: "Readiness priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "surge readiness",
    },
  ],
  metricDefinitions: [
    { id: "iap-employees", label: "Employees", value: 1400, unit: "count", category: "workforce" },
    { id: "iap-revenue", label: "Annual revenue", value: 422.7, unit: "usd", category: "financial" },
    { id: "iap-expected-injuries", label: "Expected injuries/yr", value: 39, unit: "count", category: "safety" },
    { id: "iap-dba-cost-low", label: "DBA injury cost low", value: 1.95, unit: "usd", category: "risk" },
    { id: "iap-dba-cost-high", label: "DBA injury cost high", value: 3.5, unit: "usd", category: "risk" },
    { id: "iap-oconus-ratio", label: "OCONUS physical workforce ratio", value: 80, unit: "percent", category: "risk" },
    { id: "iap-occumed-revenue-mid", label: "Occu-Med revenue midpoint", value: 0.45, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Power Gen / Electrical", revenue: 1.2, risk: 9.5, workers: 400 },
    { name: "BOS Facilities", revenue: 0.72, risk: 8.0, workers: 300 },
    { name: "Logistics / Supply Chain", revenue: 1.4, risk: 9.0, workers: 400 },
    { name: "Program Mgmt / Tech", revenue: 0.18, risk: 3.0, workers: 300 },
  ],
  opportunityMatrix: [
    { name: "DBA Pre-Deployment", revenuePotential: 245, implementationComplexity: 7, strategicValue: 10 },
    { name: "Electrical Safety 1910.269", revenuePotential: 45, implementationComplexity: 8, strategicValue: 10 },
    { name: "Pre-Employment Physicals", revenuePotential: 65, implementationComplexity: 4, strategicValue: 7 },
    { name: "Hearing Conservation", revenuePotential: 43, implementationComplexity: 4, strategicValue: 8 },
    { name: "Respirator Clearance", revenuePotential: 45, implementationComplexity: 5, strategicValue: 8 },
    { name: "LOGCAP Surge Readiness", revenuePotential: 450, implementationComplexity: 8, strategicValue: 10 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "IAP is a privately held base operations, power generation, and logistics support entity owned by Cerberus Capital Management. The uploaded report emphasizes that IAP publishes no TRIR, DART, or workers' compensation data, so exposure must be modeled from BLS benchmarks applied to actual workforce composition.",
      bullets: [
        "Founded in 1990 and headquartered in Cape Canaveral, Florida.",
        "Estimated 1,400-1,502 employees and $422.7M annual revenue in the uploaded report.",
        "Core business lines include Global Operations & Logistics, Facilities Management / Base Operations Support, and Professional & Technical Services.",
        "The key sales frame is OCONUS DBA exposure, electrical safety compliance, and LOGCAP surge readiness.",
      ],
      metricIds: ["iap-employees", "iap-revenue", "iap-expected-injuries"],
    },
    {
      type: "workforce",
      title: "Workforce and BLS risk model",
      narrative:
        "IAP's injury model is driven by a physically demanding workforce composition: power generation/electrical technicians, BOS facilities maintenance, logistics/supply chain workers, and a smaller program-management/technical staff group.",
      bullets: [
        "Power generation/electrical technicians: ~400 workers, BLS TRIR benchmark 3.20, approximately 13 expected injuries per year.",
        "BOS facilities maintenance: ~300 workers, BLS TRIR benchmark 2.50, approximately 8 expected injuries per year.",
        "Logistics/supply chain: ~400 workers, BLS TRIR benchmark 3.90, approximately 16 expected injuries per year.",
        "Program management/technical staff: ~300 workers, BLS TRIR benchmark 0.70, approximately 2 expected injuries per year.",
      ],
      metricIds: ["iap-expected-injuries"],
    },
    {
      type: "contracts",
      title: "Business lines and contract streams",
      narrative:
        "The uploaded report identifies three major operating lines: contingency power generation/logistics, base operations support, and professional/technical services. The most important active and latent streams are NSA Souda Bay, BOS IDIQ work, LOGCAP V, GCS MAC III, and IAP-ECC joint venture work.",
      bullets: [
        "Global Operations & Logistics includes contingency power generation and logistics support in austere military environments.",
        "Facilities Management / BOS includes NSA Souda Bay utilities, HVAC, plumbing, construction services, and base support operations.",
        "Professional & Technical Services is the lowest-risk segment, staffed by project managers, analysts, and consultants.",
        "LOGCAP V and GCS MAC III are latent surge vehicles: low current tasking can become rapid deployment medical demand if activated.",
      ],
      metricIds: [],
    },
    {
      type: "locations",
      title: "OCONUS DBA exposure",
      narrative:
        "The report states that IAP's fundamental business model places a higher percentage of its physical workforce OCONUS than any other entity in the portfolio. At an estimated 80% OCONUS ratio, core injuries are likely DBA claims rather than domestic state workers' comp claims.",
      bullets: [
        "High-voltage power generation work at FOBs and naval installations creates electrocution, arc flash, and severe burn scenarios.",
        "NSA Souda Bay BOS workers perform building trades, roofing, confined-space work, heavy equipment operation, and utility maintenance.",
        "Middle East, Afghanistan-theater, and Mediterranean power generation/base operations create heat illness risk.",
        "Logistics and supply chain work involves warehousing, materials handling, and transportation in deployed environments.",
      ],
      metricIds: ["iap-oconus-ratio", "iap-dba-cost-high"],
    },
    {
      type: "procurement",
      title: "False Claims Act compliance trigger",
      narrative:
        "The uploaded report identifies a December 2025 False Claims Act settlement as the opening for a compliance-documentation conversation. The key argument is that after an FCA settlement and whistleblower action, Cerberus and contracting agencies will care about documented OSHA medical surveillance and DBA clearance records.",
      bullets: [
        "The report says IAP agreed to pay $810,821.65 to resolve allegations involving non-conforming goods provided to the government.",
        "The case was investigated by NCIS and filed under qui tam provisions, meaning a whistleblower triggered the investigation.",
        "The report frames this as a reason to audit medical-surveillance documentation, not as a safety allegation.",
        "Cerberus Capital Management ownership is used as a compliance-assurance lever after the settlement.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded model places IAP at roughly $450K/year midpoint revenue potential, differentiated by 1910.269 electrical safety medical evaluation and LOGCAP V surge-readiness protocols rather than commodity pre-employment physicals alone.",
      bullets: [
        "DBA pre-deployment medicals are the largest immediate lane at roughly $245K/year modeled midpoint.",
        "Pre-employment physicals, hearing conservation, electrical safety, respirator clearances, and DOT/CDL exams add smaller recurring lanes.",
        "1910.269 electrical safety medical fitness for high-voltage work is the specialized differentiator.",
        "LOGCAP V surge readiness can be scoped and contracted before task-order activation.",
      ],
      metricIds: ["iap-occumed-revenue-mid"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "IAP values in this profile are source-backed but model-driven. The charts should be interpreted as Occu-Med intelligence estimates derived from the uploaded IAP report, BLS benchmarks, contract records, DBA assumptions, and compliance-trigger analysis.",
      bullets: [
        "Do not present modeled injury, DBA cost, OCONUS ratio, or revenue projections as audited IAP disclosures.",
        "Label the profile as an uploaded Occu-Med intelligence model.",
        "Preserve the source file as evidence for extracted charts, tables, and sales narrative.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "executive-summary",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: false,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
