import type { CompanyConfig } from "./types";

export const idsConfig: CompanyConfig = {
  companyId: "ids",
  displayName: "IDS International",
  shortName: "IDS",
  sector:
    "Defense training, DECO domestic security, expeditionary support, OCONUS tactical training, cyber/SMEIR operations, and government facility security",
  headquarters: "Arlington, Virginia",
  employees: 1300,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 19, 2026",
  summary:
    "IDS International is a privately held defense-support and security entity with roughly 1,300 employees and no public TRIR, DART, or workers' compensation disclosures. The uploaded report treats IDS as a concentrated contract-preservation and DBA-risk account: the highest acute risk is the $27.9M Iraq QK Regiment Tactical Ground Training Support contract at Camp Taji, where heat, weapons, live-fire training, vehicle movement, and stop-work exposure make medical clearance documentation strategically important.",
  tags: [
    "Entity profile",
    "Defense training",
    "DECO security",
    "OCONUS tactical training",
    "Camp Taji",
    "Iraq contract",
    "DBA exposure",
    "Heat readiness",
    "Stop-work exposure",
    "Security guards",
    "Regulatory surveillance",
  ],
  aliases: ["IDS International", "IDS International LLC", "DECO Security", "DECO", "SMEIR"],
  sourceFilters: {
    sam: { legalNames: ["IDS International", "IDS International LLC", "DECO Security"] },
    usaSpending: { recipientNames: ["IDS International", "IDS International LLC"] },
    jobSources: { linkedin: "ids-international", careerSite: "https://idsinternational.com/careers/" },
    newsSources: { aliases: ["IDS International", "IDS", "DECO Security", "Camp Taji", "W900KK-24-C-0036"] },
  },
  executiveSignals: [
    {
      label: "Expected injuries",
      value: "~20/yr",
      note: "BLS benchmark model across DECO guards, tactical trainers, expeditionary support, and cyber/office workers.",
    },
    {
      label: "Direct injury cost",
      value: "$790K–$1.5M/yr",
      note: "Modeled direct annual cost from uploaded IDS workforce table and cost chart.",
    },
    {
      label: "Iraq contract at risk",
      value: "$27.9M",
      note: "Sole-source Camp Taji tactical training support contract; a catastrophic safety event could trigger stop-work, investigation, and CPAR damage.",
    },
    {
      label: "DBA claim severity",
      value: "$500K–$2M+",
      note: "Uploaded report's long-term DBA disability claim exposure for serious TBI, spinal, blast, or tactical training injuries.",
    },
  ],
  curveTitle: "IDS contract-preservation, DBA, and tactical training risk curve",
  curveSubtitle:
    "Uploaded Occu-Med intelligence values normalized for entity-profile scanning; modeled estimates should be treated as assumption-driven signals, not audited employer disclosures.",
  chartDefinitions: [
    {
      id: "ids-injury-cost-stack",
      title: "IDS estimated annual injury cost by worker population",
      subtitle: "Uploaded chart/page 2: direct cost low plus high-estimate additional cost, shown in $K.",
      type: "stacked",
      xKey: "population",
      data: [
        { population: "DECO Guards", directLow: 320, highAdditional: 240 },
        { population: "Tactical Trainers", directLow: 320, highAdditional: 320 },
        { population: "Expeditionary Support", directLow: 160, highAdditional: 120 },
        { population: "Cyber / Office", directLow: 30, highAdditional: 30 },
      ],
      series: [
        { dataKey: "directLow", name: "Direct low", color: "#22d3ee", stackId: "cost" },
        { dataKey: "highAdditional", name: "High additional", color: "#ef4444", stackId: "cost", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "injury cost",
      fullWidth: true,
    },
    {
      id: "ids-worker-risk-trir",
      title: "IDS worker risk: BLS TRIR benchmarks by population",
      subtitle: "Uploaded chart/page 3: tactical trainers and expeditionary support carry the highest benchmarked risk.",
      type: "bar",
      xKey: "population",
      data: [
        { population: "DECO Guards", trir: 1.1 },
        { population: "Tactical Trainers", trir: 2.5 },
        { population: "Expeditionary Support", trir: 2.0 },
        { population: "Cyber / Office", trir: 0.5 },
      ],
      series: [{ dataKey: "trir", name: "BLS TRIR benchmark", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 3],
      headline: "TRIR benchmark",
    },
    {
      id: "ids-contract-value-risk",
      title: "IDS contract value at risk from preventable event",
      subtitle: "Uploaded chart/page 4: one serious event at Camp Taji could place the full $27.9M Iraq contract at risk.",
      type: "bar",
      xKey: "contract",
      data: [
        { contract: "Iraq / Camp Taji", value: 27.9 },
        { contract: "Djibouti", value: 8.0 },
        { contract: "Jordan", value: 6.0 },
        { contract: "DECO Domestic Security", value: 4.0 },
      ],
      series: [{ dataKey: "value", name: "Contract value", color: "#f97316", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "contract risk",
      fullWidth: true,
    },
    {
      id: "ids-headcount-by-risk-lane",
      title: "IDS workforce by risk lane",
      subtitle: "Uploaded table/page 1: modeled headcount used for injury and exam opportunity estimates.",
      type: "bar",
      xKey: "population",
      data: [
        { population: "DECO Guards", headcount: 700 },
        { population: "Tactical Trainers", headcount: 300 },
        { population: "Expeditionary Support", headcount: 200 },
        { population: "Cyber / Office", headcount: 100 },
      ],
      series: [{ dataKey: "headcount", name: "Estimated headcount", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "worker population",
    },
    {
      id: "ids-regulatory-gap-priority",
      title: "IDS regulatory and deployment medical gap priority",
      subtitle: "Uploaded page 6 table converted into priority weights for medical-surveillance action.",
      type: "bar",
      xKey: "gap",
      data: [
        { gap: "DBA pre-deploy", priority: 10 },
        { gap: "Heat readiness", priority: 10 },
        { gap: "Noise / audiometry", priority: 8 },
        { gap: "Respirator clearance", priority: 8 },
        { gap: "Bloodborne pathogens", priority: 7 },
        { gap: "DOT / CMV physicals", priority: 6 },
        { gap: "Firearms / FFD", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Priority score", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "gap priority",
    },
    {
      id: "ids-dba-severity",
      title: "IDS DBA long-tail claim severity",
      subtitle: "Uploaded report states serious DBA claims can run $500K-$2M+ over claim life.",
      type: "bar",
      xKey: "claimType",
      data: [
        { claimType: "Serious DBA low", value: 500 },
        { claimType: "Serious DBA high", value: 2000 },
        { claimType: "Annual direct injury low", value: 790 },
        { claimType: "Annual direct injury high", value: 1500 },
      ],
      series: [{ dataKey: "value", name: "Exposure", color: "#ef4444", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "DBA severity",
    },
  ],
  metricDefinitions: [
    { id: "ids-employees", label: "Employees", value: 1300, unit: "count", category: "workforce" },
    { id: "ids-expected-injuries", label: "Expected injuries/yr", value: 20, unit: "count", category: "safety" },
    { id: "ids-direct-cost-low", label: "Direct injury cost low", value: 0.79, unit: "usd", category: "financial" },
    { id: "ids-direct-cost-high", label: "Direct injury cost high", value: 1.5, unit: "usd", category: "financial" },
    { id: "ids-indirect-cost-high", label: "Total cost high with indirect", value: 7.5, unit: "usd", category: "financial" },
    { id: "ids-iraq-contract-risk", label: "Iraq contract value at risk", value: 27.9, unit: "usd", category: "risk" },
    { id: "ids-camp-taji-ftes", label: "Camp Taji average FTEs", value: 62, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "Camp Taji tactical training", revenue: 27.9, risk: 10.0, workers: 62 },
    { name: "Djibouti expeditionary support", revenue: 8.0, risk: 8.5, workers: 80 },
    { name: "Jordan training support", revenue: 6.0, risk: 7.5, workers: 60 },
    { name: "DECO security guards", revenue: 4.0, risk: 6.0, workers: 700 },
    { name: "Cyber / SMEIR", revenue: 2.0, risk: 2.5, workers: 100 },
  ],
  opportunityMatrix: [
    { name: "DBA Pre-Deployment", revenuePotential: 160, implementationComplexity: 6, strategicValue: 10 },
    { name: "Heat Readiness Protocol", revenuePotential: 90, implementationComplexity: 8, strategicValue: 10 },
    { name: "DECO Pre-Employment Physicals", revenuePotential: 175, implementationComplexity: 4, strategicValue: 8 },
    { name: "Firearms / Fitness-for-Duty", revenuePotential: 140, implementationComplexity: 5, strategicValue: 8 },
    { name: "Audiometry / Noise", revenuePotential: 75, implementationComplexity: 4, strategicValue: 7 },
    { name: "Respirator / BBP / DOT", revenuePotential: 80, implementationComplexity: 5, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "IDS publishes no public safety metrics, but the uploaded report argues that the absence of TRIR/DART data does not mean the absence of risk. The risk profile is driven by DECO security guards, tactical trainers, expeditionary OCONUS support, and a small cyber/office population.",
      bullets: [
        "Privately held entity with roughly $45M revenue and approximately 1,300 employees.",
        "BLS benchmark model produces roughly 20 expected injuries per year.",
        "Direct injury cost is modeled at $790K-$1.5M annually, with indirect costs potentially lifting total impact to $1.6M-$7.5M.",
        "For a $45M revenue company, the report frames that as 2%-17% of gross revenue lost to preventable injury costs.",
      ],
      metricIds: ["ids-employees", "ids-expected-injuries", "ids-direct-cost-high"],
    },
    {
      type: "contracts",
      title: "Single biggest financial exposure: Iraq contract",
      narrative:
        "The report identifies sole-source contract W900KK-24-C-0036 for Iraq QK Regiment Tactical Ground Training Support at Camp Taji as IDS's most important financial exposure. The ceiling value is $27.9M and the work involves live-fire, tactical movement, small-unit training, heat, weapons, and operational stop-work risk.",
      bullets: [
        "The contract supports 62 average FTEs executing live-fire and tactical training at Camp Taji.",
        "The report states it was already subject to a stop-work order in August 2025.",
        "Potential end date is October 2027, meaning a 2026 safety event could forfeit $20M+ in remaining revenue.",
        "A catastrophic event could trigger USACE stop-work, an Army investigation, and CPAR damage affecting future FMS training awards.",
      ],
      metricIds: ["ids-iraq-contract-risk", "ids-camp-taji-ftes"],
    },
    {
      type: "safety",
      title: "Heat, weapons, and DBA deployment risk",
      narrative:
        "The acute preventable fatality risk in IDS's portfolio is heat-stress and tactical-training risk at Camp Taji. The report says summer temperatures regularly exceed 45°C / 113°F, while trainers work outdoors with full combat loads and minimal shade.",
      bullets: [
        "DBA-covered injuries are federal claims with unlimited medical benefits and potentially long wage-replacement duration.",
        "Serious TBI, spinal, blast, or weapons-training injuries can become $500K-$2M+ lifetime DBA claims.",
        "Pre-deployment medicals should document cardiovascular heat fitness, prior heat injury, heat-impairing medications, MSK load-bearing fitness, and psychological readiness.",
        "The report identifies no public IDS heat-readiness medical protocol for deploying trainers.",
      ],
      metricIds: [],
    },
    {
      type: "workforce",
      title: "DECO domestic security exposure",
      narrative:
        "DECO security is the most predictable and schedulable exam population in IDS. The report says DECO is licensed in 38 states and operates 16 staffed branch offices, mostly providing armed/unarmed guards at government facilities, embassies, and cleared construction sites.",
      bullets: [
        "Estimated 700 domestic guards generate roughly 7-8 recordable injuries per year.",
        "Injury profile concentrates in slips/trips/falls, patrol vehicle incidents, assault/use-of-force trauma, and cumulative musculoskeletal strain.",
        "Recurring exam lanes include pre-employment physicals, annual firearms/fitness-for-duty clearances, vision, and hearing surveillance.",
      ],
      metricIds: [],
    },
    {
      type: "safety",
      title: "Regulatory obligations left on the table",
      narrative:
        "The uploaded report identifies several OSHA and deployment-medical obligations that may be informal, absent, or inconsistently documented at smaller tactical contractors.",
      bullets: [
        "Noise/audiometry: weapons ranges, generators, and armored vehicles require baseline audiograms under 29 CFR 1910.95 logic.",
        "Respirator clearance: OCONUS dust/toxic sites may require 1910.134 medical clearance.",
        "Bloodborne pathogens: tactical medical and combat medic trainers may need hepatitis B documentation and BBP compliance.",
        "DOT/CMV physicals: staff driving military vehicles, buses, or tactical trucks may have two-year renewal gaps.",
        "DBA pre-deployment medicals are the most valuable gap and may be done informally if at all.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med sales narrative",
      narrative:
        "The report says IDS leadership will not respond to a commodity price pitch. The correct conversation is contract preservation, DBA risk, heat-readiness documentation, and whether the medical clearance standard can survive a DoD safety investigation.",
      bullets: [
        "Lead with the $27.9M Iraq contract and the fact that it already experienced stop-work pressure.",
        "Ask what medical clearance standard trainers complete before flying to Baghdad.",
        "Frame medical exams as contract-risk management and DBA claim defense, not cheaper pre-employment physicals.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "IDS values in this profile are source-backed but model-driven. The charts should be interpreted as Occu-Med intelligence estimates derived from the uploaded IDS report, BLS benchmarks, contract records, DBA logic, and medical-surveillance assumptions.",
      bullets: [
        "Do not present modeled injury, cost, DBA severity, or contract-risk values as audited IDS disclosures.",
        "Treat Camp Taji heat-readiness, DBA, and regulatory gaps as prospecting theses requiring validation with IDS operations and program leadership.",
        "Preserve the source file as evidence for extracted tables, charts, and sales narrative.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "executive-summary",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: false,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
