import type { CompanyConfig } from "./types";

export const insuranceCarrierMappingConfig: CompanyConfig = {
  companyId: "insurance-carrier-mapping",
  displayName: "Insurance Carrier Mapping Intelligence",
  shortName: "Carrier Mapping",
  sector:
    "Defense Base Act and workers compensation carrier mapping, AIG/ICSOP, CNA/Rutherfoord, ACE/Chubb, self-insured employer networks, carrier credentialing strategy, and provider-network growth channels",
  headquarters: "Occu-Med portfolio-level carrier intelligence",
  employees: 0,
  employeesAsOf:
    "Uploaded carrier-mapping report: 30 mapped entities, including 20 clients and 10 prospects, with confirmed/high-confidence and medium-confidence carrier assignments",
  summary:
    "Insurance Carrier Mapping Intelligence captures the uploaded carrier research that maps Occu-Med's current and target defense/federal entities to DBA and workers' compensation carrier channels. The core finding is that AIG, through Insurance Company of the State of Pennsylvania, dominates the DBA market and appears as the major channel behind V2X/Vectrus and many AIG-pattern defense contractors. CNA is the required USACE carrier lane for many USACE/DOS/USAID workstreams through Rutherfoord International, making AECOM, Bechtel, Michael Baker, and Fluor CNA-relevant when work is under USACE requirements. ACE/Chubb is the third major DBA carrier, especially for UK defense-prime-style entities such as BAE Systems and QinetiQ. Self-insured employers such as Leidos, Lockheed Martin, and HII should be approached directly. The strategic implication is blunt: Occu-Med should not only chase every employer separately; it should verify and expand its standing with the few carrier/provider networks that route a large share of DBA and workers' compensation medical demand.",
  tags: [
    "Entity profile",
    "DBA carrier mapping",
    "AIG",
    "ICSOP",
    "CNA",
    "Rutherfoord",
    "ACE Chubb",
    "Self-insured",
    "Aetna admin",
    "USACE mandated",
    "Provider network",
    "Carrier credentialing",
    "Chase strategy",
  ],
  aliases: ["Carrier Mapping", "Insurance Carrier Intelligence", "DBA Carrier Mapping", "Who Insures Whom"],
  sourceFilters: {
    newsSources: {
      aliases: ["AIG DBA Insurance Company of the State of Pennsylvania", "CNA Rutherfoord DBA", "Chubb Defense Base Act", "Leidos self insured Aetna admin"],
    },
  },
  executiveSignals: [
    { label: "Dominant carrier", value: "AIG", note: "Uploaded report states AIG/ICSOP dominates the DBA market and is the largest mapped channel." },
    { label: "Historical DBA share", value: "79%", note: "Uploaded report cites DOL carrier data showing AIG handled 79% of DBA claims from 2001-2018." },
    { label: "Mapped entities", value: "30", note: "Carrier mapping covers 20 clients and 10 prospects." },
    { label: "Primary strategy", value: "2-3 networks", note: "The report says provider-network access to AIG, CNA, and Chubb can unlock more than entity-by-entity cold outreach." },
  ],
  curveTitle: "Insurance carrier mapping, network gatekeeper, and provider-access curve",
  curveSubtitle:
    "Uploaded carrier-mapping report normalized into a portfolio profile. Mapping confidence varies; confirm carrier/TPA status before external claims or credentialing outreach.",
  chartDefinitions: [
    {
      id: "carrier-share-by-volume-expanded",
      title: "DBA carrier share by mapped referral volume",
      subtitle: "Uploaded carrier report: AIG dominates mapped volume, with CNA second and self-insured employers third.",
      type: "bar",
      xKey: "carrier",
      data: [
        { carrier: "AIG / ICSOP", share: 72.8 },
        { carrier: "CNA", share: 15.0 },
        { carrier: "Self-insured", share: 8.82 },
        { carrier: "Unknown", share: 2.4 },
        { carrier: "ACE / Chubb", share: 0.465 },
      ],
      series: [{ dataKey: "share", name: "Mapped volume share", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 80],
      headline: "carrier share",
      fullWidth: true,
    },
    {
      id: "confirmed-carrier-mapping",
      title: "Confirmed and high-confidence carrier mappings",
      subtitle: "Carrier-channel assignments from the uploaded mapping table.",
      type: "bar",
      xKey: "entity",
      data: [
        { entity: "V2X / AIG", annualRefs: 5427 },
        { entity: "Amentum / AIG-CNA", annualRefs: 852 },
        { entity: "Leidos / Self-insured", annualRefs: 307 },
        { entity: "Fluor / CNA-AIG", annualRefs: 75 },
        { entity: "AECOM / CNA", annualRefs: 350 },
        { entity: "Bechtel / CNA-AIG", annualRefs: 250 },
        { entity: "Lockheed / Self-insured", annualRefs: 675 },
        { entity: "HII / Self-insured", annualRefs: 250 },
        { entity: "Michael Baker / CNA", annualRefs: 135 },
      ],
      series: [{ dataKey: "annualRefs", name: "Annual refs / modeled volume", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "mapped entities",
      fullWidth: true,
    },
    {
      id: "medium-confidence-carriers",
      title: "Medium-confidence carrier patterns",
      subtitle: "Industry-pattern mapping that requires verification before outreach.",
      type: "bar",
      xKey: "entity",
      data: [
        { entity: "IAP / AIG", annualRefs: 409 },
        { entity: "CACI / AIG-Chubb", annualRefs: 146 },
        { entity: "BAE / Chubb", annualRefs: 95 },
        { entity: "Alutiiq / AIG", annualRefs: 45 },
        { entity: "Weatherford / AIG-Zurich", annualRefs: 40 },
        { entity: "QinetiQ / Chubb", annualRefs: 30 },
        { entity: "Akima / AIG", annualRefs: 525 },
        { entity: "Cherokee / AIG", annualRefs: 350 },
        { entity: "Booz Allen / AIG-Chubb", annualRefs: 425 },
      ],
      series: [{ dataKey: "annualRefs", name: "Modeled annual refs", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      headline: "patterns",
    },
    {
      id: "carrier-network-action-plan",
      title: "Carrier network action plan",
      subtitle: "Provider-network access is a channel strategy, not only an employer sales strategy.",
      type: "bar",
      xKey: "action",
      data: [
        { action: "Verify current AIG status", priority: 10 },
        { action: "Credential with AIG", priority: 10 },
        { action: "Credential with CNA/Rutherfoord", priority: 9 },
        { action: "Evaluate Chubb/ACE", priority: 7 },
        { action: "Direct self-insured outreach", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "action plan",
    },
  ],
  metricDefinitions: [
    { id: "carrier-mapped-entities", label: "Mapped entities", value: 30, unit: "count", category: "financial" },
    { id: "carrier-aig-dol-share", label: "AIG historical DBA claim share", value: 79, unit: "percent", category: "risk" },
    { id: "carrier-aig-volume-share", label: "AIG mapped volume share", value: 72.8, unit: "percent", category: "risk" },
    { id: "carrier-cna-volume-share", label: "CNA mapped volume share", value: 15, unit: "percent", category: "risk" },
    { id: "carrier-self-insured-share", label: "Self-insured mapped share", value: 8.82, unit: "percent", category: "risk" },
  ],
  riskMatrix: [
    { name: "AIG / ICSOP channel", revenue: 10000, risk: 7.0, workers: 10000 },
    { name: "CNA / Rutherfoord channel", revenue: 1800, risk: 6.0, workers: 1800 },
    { name: "ACE / Chubb channel", revenue: 700, risk: 5.0, workers: 700 },
    { name: "Self-insured direct", revenue: 1200, risk: 4.5, workers: 1200 },
    { name: "Unknown / verify", revenue: 500, risk: 8.5, workers: 500 },
  ],
  opportunityMatrix: [
    { name: "AIG Provider-Network Verification", revenuePotential: 10000, implementationComplexity: 8, strategicValue: 10 },
    { name: "CNA / Rutherfoord Credentialing", revenuePotential: 1800, implementationComplexity: 7, strategicValue: 9 },
    { name: "Chubb / ACE DBA Channel", revenuePotential: 700, implementationComplexity: 6, strategicValue: 7 },
    { name: "Self-Insured Direct Campaign", revenuePotential: 1200, implementationComplexity: 4, strategicValue: 8 },
    { name: "Carrier Verification Project", revenuePotential: 500, implementationComplexity: 5, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "AIG is the core channel",
      narrative:
        "The uploaded report says the single most important discovery is that AIG/ICSOP controls the largest share of DBA carrier flow. Occu-Med should verify whether existing V2X flow is direct-client only or also carrier-network enabled.",
      bullets: [
        "V2X/Vectrus is mapped as AIG/ICSOP confirmed in the report.",
        "AIG is cited as handling 79% of historical DBA claims from 2001-2018.",
        "A single AIG credentialing path could unlock multiple current and target entities.",
      ],
      metricIds: ["carrier-aig-dol-share", "carrier-aig-volume-share"],
    },
    {
      type: "procurement",
      title: "CNA, Chubb, and self-insured routes",
      narrative:
        "The carrier map separates channel strategy by gatekeeper: CNA for USACE-mandated work, ACE/Chubb for certain defense-prime patterns, and direct outreach for self-insured employers.",
      bullets: [
        "AECOM, Bechtel, Michael Baker, and parts of Fluor are CNA-relevant when work is USACE-mandated.",
        "BAE Systems and QinetiQ are mapped toward ACE/Chubb based on UK defense-prime patterning.",
        "Leidos, Lockheed Martin, and HII are self-insured/direct-network plays.",
      ],
      metricIds: ["carrier-cna-volume-share", "carrier-self-insured-share"],
    },
  ],
};
