import type { CompanyConfig } from "./types";

export const kbrConfig: CompanyConfig = {
  companyId: "kbr",
  displayName: "KBR, Inc.",
  shortName: "KBR",
  sector:
    "Global engineering, technology, LOGCAP logistics, life support, classified mission support, sustainable technology solutions, and government services",
  headquarters: "Houston, Texas",
  employees: 38000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 19, 2026",
  summary:
    "KBR is a global engineering, technology, and government solutions entity with an unusually strong reported safety record. The uploaded Occu-Med intelligence model argues that KBR requires a different outreach frame: not that its safety program is broken, but that its occupational medicine infrastructure must match the sophistication of its Zero Harm safety culture across LOGCAP EUCOM/NORTHCOM, STS chemical/process work, and classified science and technology populations.",
  tags: [
    "Entity profile",
    "LOGCAP",
    "EUCOM risk",
    "Zero Harm",
    "DBA exposure",
    "STS chemical surveillance",
    "Classified workforce",
    "Compliance documentation",
    "Revenue opportunity",
  ],
  aliases: ["KBR", "KBR, Inc.", "Kellogg Brown & Root"],
  sourceFilters: {
    sec: { ticker: "KBR", legalEntities: ["KBR, Inc."] },
    sam: { legalNames: ["KBR, Inc.", "KBR Services LLC"] },
    usaSpending: { recipientNames: ["KBR", "KBR Services"] },
    jobSources: { linkedin: "kbr-inc", careerSite: "https://www.kbr.com/en/careers", clearanceJobs: "KBR" },
    newsSources: { aliases: ["KBR"], acquisitionAliases: ["Kellogg Brown & Root"] },
  },
  executiveSignals: [
    {
      label: "Reported TRIR",
      value: "0.050 → 0.033",
      note: "Uploaded report states KBR's confirmed 2024 TRIR was 0.050 and declined further in 2025.",
    },
    {
      label: "Zero Harm frame",
      value: "93% incident-free",
      note: "The report says KBR achieved 338 incident-free days in 2024 and promotes safety under its Zero Harm brand.",
    },
    {
      label: "Occu-Med potential",
      value: "$1.9M–$5.5M/yr",
      note: "Modeled annual opportunity across pre-employment, LOGCAP DBA, hearing, respirator, DOT, and behavioral health lanes.",
    },
    {
      label: "Compliance exposure",
      value: "$710M+",
      note: "Violation-penalty model dominated by historical FCPA and False Claims Act categories; OSHA history is comparatively minor.",
    },
  ],
  curveTitle: "KBR Zero Harm, LOGCAP, and occupational medicine infrastructure curve",
  curveSubtitle:
    "Uploaded Occu-Med intelligence values normalized for entity-profile scanning; modeled estimates should be treated as assumption-driven signals, not audited employer disclosures.",
  chartDefinitions: [
    {
      id: "kbr-trir-trend",
      title: "KBR TRIR trend vs portfolio peers",
      subtitle: "Source: uploaded KBR report; KBR's reported TRIR is far below peer and BLS references.",
      type: "line",
      xKey: "year",
      data: [
        { year: "2023", kbr: 0.064 },
        { year: "2024", kbr: 0.05 },
        { year: "2025", kbr: 0.033 },
      ],
      series: [{ dataKey: "kbr", name: "KBR TRIR", color: "#22c55e" }],
      domain: [0, 1.5],
      referenceLines: [
        { y: 1.4, stroke: "#94a3b8", strokeDasharray: "4 4", label: { value: "BLS avg", fill: "#94a3b8", fontSize: 11 } },
        { y: 0.69, stroke: "#ef4444", strokeDasharray: "4 4", label: { value: "FCX 0.69", fill: "#ef4444", fontSize: 11 } },
        { y: 0.33, stroke: "#38bdf8", strokeDasharray: "4 4", label: { value: "Amentum 0.33", fill: "#38bdf8", fontSize: 11 } },
        { y: 0.12, stroke: "#f97316", strokeDasharray: "4 4", label: { value: "Weatherford 0.12", fill: "#f97316", fontSize: 11 } },
      ],
      headline: "TRIR excellence",
      fullWidth: true,
    },
    {
      id: "kbr-worker-risk-segment",
      title: "KBR worker risk by BLS TRIR segment",
      subtitle: "Segment benchmarks explain why company-wide TRIR understates physical-work exposure.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "STS chemical/const", trir: 3.5 },
        { segment: "LOGCAP OCONUS", trir: 2.5 },
        { segment: "Govt solutions tech", trir: 0.7 },
        { segment: "Classified intel/cyber", trir: 0.5 },
        { segment: "HQ/corporate", trir: 0.4 },
      ],
      series: [{ dataKey: "trir", name: "BLS TRIR benchmark", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 4],
      headline: "segment risk",
    },
    {
      id: "kbr-eucom-risk",
      title: "LOGCAP EUCOM hostile-environment risk index",
      subtitle: "Uploaded report identifies Eastern Europe deployments as materially different from routine LOGCAP support.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Poland", risk: 8 },
        { country: "Romania", risk: 7 },
        { country: "Latvia", risk: 8 },
        { country: "Lithuania", risk: 8 },
        { country: "Bulgaria", risk: 5 },
        { country: "Kosovo", risk: 6 },
        { country: "Germany", risk: 3 },
        { country: "Italy", risk: 2 },
        { country: "Türkiye", risk: 5 },
      ],
      series: [{ dataKey: "risk", name: "Risk index", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "EUCOM risk",
    },
    {
      id: "kbr-penalties",
      title: "KBR cumulative violation penalties by type",
      subtitle: "Uploaded report frames compliance documentation as a key risk context; penalties shown in $M.",
      type: "bar",
      xKey: "category",
      data: [
        { category: "FCPA", value: 579 },
        { category: "False Claims 2023", value: 108.75 },
        { category: "False Claims 2022", value: 13.67 },
        { category: "Wage & Hour", value: 8.51 },
        { category: "OSHA", value: 0.09 },
        { category: "Accounting", value: 2.5 },
      ],
      series: [{ dataKey: "value", name: "Total penalties", color: "#dc2626", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "compliance exposure",
      fullWidth: true,
    },
    {
      id: "kbr-revenue-potential",
      title: "Occu-Med annual revenue potential by exam lane",
      subtitle: "Modeled opportunity range from uploaded KBR report; values shown in $K per year.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Pre-employment", low: 750, high: 2000, midpoint: 1375 },
        { examType: "DBA pre/post", low: 700, high: 2000, midpoint: 1350 },
        { examType: "Hearing", low: 150, high: 500, midpoint: 325 },
        { examType: "Respirator", low: 50, high: 263, midpoint: 156.5 },
        { examType: "DOT CDL", low: 63, high: 200, midpoint: 131.5 },
        { examType: "Behavioral", low: 150, high: 500, midpoint: 325 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
      fullWidth: true,
    },
    {
      id: "kbr-zero-harm-readiness",
      title: "Zero Harm occupational medicine readiness map",
      subtitle: "Strategic lanes where occupational medicine infrastructure must match KBR's safety culture.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "STS chemical surveillance", priority: 10 },
        { lane: "LOGCAP DBA deployment", priority: 10 },
        { lane: "EUCOM cold/blast readiness", priority: 9 },
        { lane: "Hearing conservation", priority: 8 },
        { lane: "Respirator clearance", priority: 8 },
        { lane: "Classified behavioral health", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Priority score", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "readiness lanes",
    },
  ],
  metricDefinitions: [
    { id: "kbr-employees", label: "Employees", value: 38000, unit: "count", category: "workforce" },
    { id: "kbr-revenue", label: "Revenue", value: 7.3, unit: "usd", category: "financial" },
    { id: "kbr-trir-2024", label: "2024 TRIR", value: 0.05, unit: "score", category: "safety" },
    { id: "kbr-trir-2025", label: "2025 TRIR", value: 0.033, unit: "score", category: "safety" },
    { id: "kbr-incident-free-days", label: "Incident-free days", value: 338, unit: "count", category: "safety" },
    { id: "kbr-revenue-potential-high", label: "Occu-Med revenue potential high", value: 5.5, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "STS chemical / construction", revenue: 1.1, risk: 9.0, workers: 3500 },
    { name: "LOGCAP OCONUS", revenue: 2.5, risk: 8.5, workers: 8500 },
    { name: "Government tech / SCI", revenue: 1.4, risk: 4.0, workers: 15000 },
    { name: "Classified intel / cyber", revenue: 0.8, risk: 3.5, workers: 6000 },
    { name: "HQ / corporate", revenue: 0.4, risk: 1.5, workers: 3000 },
  ],
  opportunityMatrix: [
    { name: "DBA Pre/Post Deployment", revenuePotential: 2000, implementationComplexity: 8, strategicValue: 10 },
    { name: "Pre-Employment Physicals", revenuePotential: 2000, implementationComplexity: 5, strategicValue: 9 },
    { name: "Behavioral Health", revenuePotential: 500, implementationComplexity: 8, strategicValue: 9 },
    { name: "Hearing Conservation", revenuePotential: 500, implementationComplexity: 5, strategicValue: 8 },
    { name: "STS Respirator Clearances", revenuePotential: 263, implementationComplexity: 5, strategicValue: 8 },
    { name: "DOT CDL Physicals", revenuePotential: 200, implementationComplexity: 3, strategicValue: 5 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "The uploaded report positions KBR as the rare account where the correct sales message is not injury-cost correction. KBR's reported safety record is exceptional, so the opportunity is to align occupational medicine infrastructure with a world-class Zero Harm safety culture.",
      bullets: [
        "$7.3B revenue global engineering, technology, and government solutions entity headquartered in Houston, Texas.",
        "Approximately 38,000 employees across professional, LOGCAP, STS, classified, and corporate populations.",
        "2024 TRIR is modeled/reported in the uploaded report at 0.050, declining to 0.033 in 2025.",
        "The standard 'your TRIR is high' pitch should not be used; the frame is occupational medicine sophistication matching safety sophistication.",
      ],
      metricIds: ["kbr-employees", "kbr-revenue", "kbr-trir-2024", "kbr-trir-2025"],
    },
    {
      type: "safety",
      title: "TRIR scrutiny and exposure gap",
      narrative:
        "The report argues that KBR's low TRIR is real but incomplete as an exposure measure. Professional workforce composition, subcontracted LOGCAP labor, and the gap between OSHA recordables and DBA claims all make TRIR a poor proxy for actual occupational medicine need.",
      bullets: [
        "At least 60% of the workforce is modeled as engineers, scientists, IT specialists, and program managers.",
        "LOGCAP subcontract workers are not part of KBR's direct-employee TRIR denominator/numerator structure.",
        "DBA claims for OCONUS direct employees may not appear in OSHA recordables.",
        "The opportunity is not proving the safety program is broken; it is quantifying hidden medical-surveillance and deployment-readiness exposure.",
      ],
      metricIds: ["kbr-trir-2024", "kbr-incident-free-days"],
    },
    {
      type: "locations",
      title: "LOGCAP EUCOM / NORTHCOM exposure",
      narrative:
        "The uploaded report highlights LOGCAP V support across roughly 50 Europe and North America locations, with Eastern Europe treated as a hostile-environment readiness problem rather than routine logistics support.",
      bullets: [
        "European operating countries listed include Bulgaria, Germany, Italy, Kosovo, Latvia, Lithuania, Poland, Romania, and Türkiye.",
        "Poland, Latvia, and Lithuania are modeled as the highest-risk EUCOM nodes because of proximity to the Russia-Ukraine conflict.",
        "Deployment medicals should account for blast exposure risk, cold-region operations, and legacy environmental toxicant exposure.",
        "Generic DBA physicals may not document the risks needed for future severe-claim defense.",
      ],
      metricIds: [],
    },
    {
      type: "workforce",
      title: "STS chemical and process safety population",
      narrative:
        "KBR's Sustainable Technology Solutions segment is modeled as the hidden high-risk population because it includes engineering and technology support for ammonia, hydrogen, petrochemical, and energy-transition facilities.",
      bullets: [
        "STS chemical plant construction and commissioning work carries BLS benchmark TRIR in the 3.0-4.0 range.",
        "Relevant medical lanes include OSHA PSM fitness, respirator clearance, hearing conservation, and air-contaminant surveillance.",
        "Noise-induced hearing loss and chemical exposure may not surface in TRIR until years after initial exposure.",
        "Zero Harm should include Zero Disease, not only Zero Injury.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "Compliance documentation pressure",
      narrative:
        "The report links historical FCA, FCPA, wage/hour, and other compliance issues to the value of documented third-party occupational medicine programs. The argument is that medical surveillance records are part of the compliance file, not just clinical paperwork.",
      bullets: [
        "The report lists major historical FCPA and False Claims Act penalties, with comparatively minor OSHA penalties.",
        "The 2023 FCA settlement is used as the compliance-documentation opening, not as a safety allegation.",
        "Audiometry baselines, respirator clearances, and DBA pre-deployment records are the occupational medicine paper trail.",
        "A third-party verified program can reduce future documentation vulnerability under cost-pressure environments.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded model estimates $1.9M-$5.5M in annual Occu-Med revenue potential, with a midpoint of roughly $3.7M. The largest revenue lanes are pre-employment physicals and LOGCAP DBA pre/post-deployment medicals.",
      bullets: [
        "Pre-employment physicals: 5,000-8,000 annual volume; modeled $750K-$2.0M per year.",
        "DBA pre/post-deployment exams: 2,000-4,000 annual volume; modeled $700K-$2.0M per year.",
        "Hearing conservation: 2,000-4,000 annual volume; modeled $150K-$500K per year.",
        "STS respirator clearances, DOT CDL physicals, and classified-workforce behavioral health add specialized high-value lanes.",
      ],
      metricIds: ["kbr-revenue-potential-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "KBR values in this profile are source-backed but model-driven. The charts should be interpreted as Occu-Med intelligence estimates derived from the uploaded KBR report, public company data, sustainability/safety disclosures, LOGCAP contract context, violation history, and occupational medicine assumptions.",
      bullets: [
        "Do not present modeled revenue opportunity, segment risk, or compliance exposure as audited KBR disclosures.",
        "Label the profile as an uploaded Occu-Med intelligence model.",
        "Preserve the source file as evidence for extracted charts, tables, and sales narrative.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "executive-summary",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: false,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
