import type { CompanyConfig } from "./types";

export const kbrConfig: CompanyConfig = {
  companyId: "kbr",
  displayName: "KBR, Inc.",
  shortName: "KBR",
  sector: "LOGCAP, contingency support, engineering, construction, classified intelligence support, and government services",
  headquarters: "Houston, Texas",
  employees: 38000,
  employeesAsOf: "Modeled worker categories from uploaded KBR visual set",
  summary: "KBR has been added as a LOGCAP-focused visual dossier connecting EUCOM hostile-environment risk, Occu-Med revenue potential, worker-risk segmentation, TRIR peer comparisons, and cumulative violation-penalty signals.",
  tags: ["LOGCAP", "EUCOM risk", "Revenue opportunity", "Compliance history", "Worker-risk segmentation"],
  aliases: ["Kellogg Brown & Root"],
  sourceFilters: {
    sec: { ticker: "KBR", legalEntities: ["KBR, Inc."] },
    sam: { legalNames: ["KBR, Inc.", "KBR Services LLC"] },
    usaSpending: { recipientNames: ["KBR", "KBR Services"] },
    jobSources: { linkedin: "kbr-inc", clearanceJobs: "KBR" },
    newsSources: { aliases: ["KBR"], acquisitionAliases: ["Kellogg Brown & Root"] },
  },
  executiveSignals: [
    { label: "Revenue potential", value: "$3.657M", note: "Modeled annual Occu-Med revenue opportunity." },
    { label: "Peak EUCOM risk", value: "8/10", note: "Poland, Latvia, and Lithuania are highest-risk nodes." },
    { label: "Worker population", value: "~38K", note: "Modeled across five workforce categories." },
    { label: "Compliance exposure", value: "$710M", note: "Penalty model dominated by FCPA and False Claims Act categories." },
  ],
  curveTitle: "KBR opportunity and risk curve",
  curveSubtitle: "Revenue potential, country risk, worker risk, TRIR, and penalty exposure normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "kbr-eucom-risk",
      title: "KBR LOGCAP EUCOM hostile-environment risk",
      subtitle: "Source: uploaded KBR visual; country risk 1-10.",
      type: "bar",
      xKey: "name",
      data: [{ name: "Poland", value: 8 }, { name: "Romania", value: 7 }, { name: "Latvia", value: 8 }, { name: "Lithuania", value: 8 }, { name: "Bulgaria", value: 5 }, { name: "Kosovo", value: 6 }, { name: "Germany", value: 3 }, { name: "Italy", value: 2 }, { name: "Türkiye", value: 5 }],
      series: [{ dataKey: "value", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "EUCOM risk",
    },
    {
      id: "kbr-revenue",
      title: "KBR Occu-Med annual revenue potential",
      subtitle: "Source: uploaded KBR visual; annual revenue shown in $K.",
      type: "bar",
      xKey: "name",
      data: [{ name: "Pre-Employment", value: 1375 }, { name: "DBA Pre-Deploy", value: 1350 }, { name: "Hearing", value: 325 }, { name: "Respirator", value: 150 }, { name: "DOT CDL", value: 132 }, { name: "Behavioral", value: 325 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "revenue potential",
    },
    {
      id: "kbr-trir-segment",
      title: "KBR worker risk by TRIR segment",
      subtitle: "Source: uploaded KBR visual; segment benchmark.",
      type: "bar",
      xKey: "name",
      data: [{ name: "STS Chem/Const", trir: 3.5 }, { name: "LOGCAP OCONUS", trir: 2.5 }, { name: "Govt Tech/SCI", trir: 0.7 }, { name: "Intel/Cyber", trir: 0.5 }, { name: "HQ/Corporate", trir: 0.4 }],
      series: [{ dataKey: "trir", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "TRIR segment",
    },
    {
      id: "kbr-trir-trend",
      title: "KBR TRIR trend vs portfolio peers",
      subtitle: "Source: uploaded KBR visual; benchmark reference lines.",
      type: "line",
      xKey: "year",
      data: [{ year: "2023", kbr: 0.04 }, { year: "2024", kbr: 0.05 }, { year: "2025", kbr: 0.04 }],
      series: [{ dataKey: "kbr", color: "#22c55e" }],
      domain: [0, 1.5],
      referenceLines: [
        { y: 1.4, stroke: "#94a3b8", strokeDasharray: "4 4" },
        { y: 0.69, stroke: "#ef4444", strokeDasharray: "4 4" },
        { y: 0.33, stroke: "#38bdf8", strokeDasharray: "4 4" },
        { y: 0.31, stroke: "#f97316", strokeDasharray: "4 4" },
      ],
      headline: "TRIR trend",
    },
    {
      id: "kbr-penalties",
      title: "KBR cumulative violation penalties",
      subtitle: "Source: uploaded KBR visual; penalties shown in $M.",
      type: "bar",
      xKey: "name",
      data: [{ name: "FCPA", value: 579 }, { name: "False Claims", value: 108.75 }, { name: "FCA", value: 13.67 }, { name: "Wage & Hour", value: 8.51 }, { name: "OSHA", value: 0.09 }],
      series: [{ dataKey: "value", color: "#dc2626", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "penalties",
      fullWidth: true,
    },
  ],
  riskMatrix: [
    { name: "STS Chemical", revenue: 0.8, risk: 8.5, workers: 3200 },
    { name: "LOGCAP OCONUS", revenue: 2.5, risk: 7.0, workers: 8500 },
    { name: "Govt Tech", revenue: 1.2, risk: 3.0, workers: 12000 },
    { name: "Intel/Cyber", revenue: 0.6, risk: 2.5, workers: 6000 },
    { name: "HQ/Corporate", revenue: 0.3, risk: 1.5, workers: 3000 },
  ],
};
