import type { CompanyConfig } from "./types";

export const kongsbergConfig: CompanyConfig = {
  companyId: "kongsberg-defence-aerospace",
  displayName: "Kongsberg Defence & Aerospace",
  shortName: "Kongsberg",
  sector:
    "Missile manufacturing, naval strike missile production, joint strike missile production, defense aerospace, propulsion integration, warhead assembly, and OCONUS sustainment",
  headquarters: "Kongsberg, Norway / Toano, Virginia U.S. missile production facility",
  employees: 600,
  employeesAsOf: "Uploaded Occu-Med intelligence report: current U.S. workforce model; Toano full-rate scenario modeled at ~775 workers by 2028",
  summary:
    "Kongsberg Defence & Aerospace is the defense subsidiary of Norway's Kongsberg Gruppen ASA. The uploaded Occu-Med report frames Kongsberg as a small but time-critical account because it broke ground on its first U.S. missile manufacturing facility in Toano, Virginia in January 2026. Construction is scheduled to begin in Q2 2026, missile manufacturing in late 2027, and full-rate NSM/JSM production by the end of 2028. The account should be pursued before the first manufacturing workforce is fully hired because propulsion integration, warhead assembly, ammonium perchlorate exposure, explosive-material handling, and DBA sustainment exposure all require baseline medical architecture.",
  tags: [
    "Entity profile",
    "Kongsberg Defence & Aerospace",
    "Norway",
    "Toano Virginia",
    "NSM",
    "JSM",
    "Missile manufacturing",
    "Ammonium perchlorate",
    "Explosives",
    "DBA exposure",
    "Time-critical",
  ],
  aliases: ["Kongsberg", "Kongsberg Defence & Aerospace", "KDA", "Kongsberg Gruppen", "KOG"],
  sourceFilters: {
    sam: { legalNames: ["Kongsberg Defence & Aerospace", "Kongsberg Defense & Aerospace"] },
    usaSpending: { recipientNames: ["Kongsberg", "Kongsberg Defence"] },
    jobSources: { linkedin: "kongsberg", careerSite: "https://www.kongsberg.com/careers/" },
    newsSources: { aliases: ["Kongsberg", "KDA", "Toano", "Naval Strike Missile", "Joint Strike Missile", "NSM", "JSM"] },
  },
  executiveSignals: [
    { label: "Time window", value: "6-12 mo", note: "Uploaded report says Occu-Med should establish the relationship before the first manufacturing workers are hired." },
    { label: "Toano investment", value: "$101M", note: "New missile manufacturing and sustainment facility in Toano, Virginia." },
    { label: "Injury model", value: "7.7 → 11.4/yr", note: "Current U.S. model vs Toano full-rate production scenario." },
    { label: "DBA exposure", value: "$1.16M/yr", note: "Modeled annual DBA claim exposure stays material across current and full-rate scenarios." },
  ],
  curveTitle: "Kongsberg Toano missile production and medical-readiness curve",
  curveSubtitle:
    "Uploaded Kongsberg Occu-Med report normalized into entity-profile charts; values are modeled account intelligence and should be validated against actual hiring and production ramp schedules.",
  chartDefinitions: [
    {
      id: "kongsberg-five-numbers",
      title: "Kongsberg current vs Toano full-rate exposure",
      subtitle: "Uploaded report: current ~600 U.S. workers vs Toano full-rate ~775 workers by 2028.",
      type: "grouped",
      xKey: "metric",
      data: [
        { metric: "Expected injuries", current: 7.7, fullRate: 11.4 },
        { metric: "Direct cost ($K)", current: 332, fullRate: 491 },
        { metric: "Economic burden ($M)", current: 1.83, fullRate: 2.7 },
        { metric: "DBA exposure ($M)", current: 1.16, fullRate: 1.16 },
      ],
      series: [
        { dataKey: "current", name: "Current", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "fullRate", name: "Toano full-rate", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "ramp exposure",
      fullWidth: true,
    },
    {
      id: "kongsberg-toano-ramp",
      title: "Toano missile facility ramp timeline",
      subtitle: "Construction begins Q2 2026; manufacturing begins late 2027; full-rate production by end of 2028.",
      type: "bar",
      xKey: "milestone",
      data: [
        { milestone: "Today", workers: 600, urgency: 10 },
        { milestone: "Q2 2026 Construction", workers: 600, urgency: 10 },
        { milestone: "Late 2027 Mfg starts", workers: 700, urgency: 8 },
        { milestone: "End 2028 Full-rate", workers: 775, urgency: 6 },
      ],
      series: [{ dataKey: "workers", name: "U.S. headcount", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "ramp timeline",
    },
    {
      id: "kongsberg-production-risk",
      title: "Toano production role hazard profile",
      subtitle: "Propulsion integration and warhead assembly are the highest-risk roles in the uploaded production table.",
      type: "bar",
      xKey: "role",
      data: [
        { role: "Guidance/electronics", workers: 80, trir: 1.2 },
        { role: "Propulsion integration", workers: 40, trir: 3.0 },
        { role: "Warhead assembly", workers: 30, trir: 3.5 },
        { role: "Systems assembly/test", workers: 30, trir: 1.5 },
        { role: "QE/engineering", workers: 70, trir: 0.6 },
      ],
      series: [{ dataKey: "trir", name: "BLS / analog TRIR", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 4],
      headline: "production risk",
    },
    {
      id: "kongsberg-surveillance-priority",
      title: "Kongsberg medical surveillance priority stack",
      subtitle: "Medical protocol lanes implied by NSM/JSM production and sustainment work.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "Thyroid baseline", priority: 10 },
        { lane: "Explosives fitness", priority: 10 },
        { lane: "Confined space eval", priority: 8 },
        { lane: "Hearing conservation", priority: 8 },
        { lane: "Respirator clearance", priority: 8 },
        { lane: "DBA pre-deploy", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "protocol stack",
    },
  ],
  metricDefinitions: [
    { id: "kongsberg-current-workers", label: "Current U.S. workers", value: 600, unit: "count", category: "workforce" },
    { id: "kongsberg-fullrate-workers", label: "Toano full-rate workers", value: 775, unit: "count", category: "workforce" },
    { id: "kongsberg-current-injuries", label: "Current expected injuries", value: 7.7, unit: "count", category: "safety" },
    { id: "kongsberg-fullrate-injuries", label: "Full-rate expected injuries", value: 11.4, unit: "count", category: "safety" },
    { id: "kongsberg-dba-exposure", label: "Annual DBA claim exposure", value: 1.16, unit: "usd", category: "risk" },
    { id: "kongsberg-toano-investment", label: "Toano facility investment", value: 101, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Propulsion integration", revenue: 80, risk: 10.0, workers: 40 },
    { name: "Warhead assembly", revenue: 70, risk: 10.0, workers: 30 },
    { name: "Guidance electronics", revenue: 120, risk: 6.5, workers: 80 },
    { name: "Systems assembly/test", revenue: 60, risk: 7.0, workers: 30 },
    { name: "OCONUS sustainment / DBA", revenue: 100, risk: 8.5, workers: 100 },
  ],
  opportunityMatrix: [
    { name: "Pre-hire Toano medical architecture", revenuePotential: 775, implementationComplexity: 7, strategicValue: 10 },
    { name: "Thyroid/perchlorate surveillance", revenuePotential: 150, implementationComplexity: 8, strategicValue: 10 },
    { name: "Explosives fitness determinations", revenuePotential: 120, implementationComplexity: 8, strategicValue: 10 },
    { name: "DBA pre-deployment", revenuePotential: 200, implementationComplexity: 6, strategicValue: 9 },
    { name: "Hearing/respirator surveillance", revenuePotential: 250, implementationComplexity: 5, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Kongsberg is small compared with RTX or KBR, but the uploaded report says it is one of the most time-critical opportunities because the U.S. missile production facility is being built now.",
      bullets: [
        "KDA is the defense subsidiary of Norway's Kongsberg Gruppen ASA.",
        "The Toano, Virginia missile manufacturing and sustainment facility is a $101M investment.",
        "The facility will produce Naval Strike Missile and Joint Strike Missile systems for U.S. military customers.",
        "The account should be approached before manufacturing workers are hired and before claim history forms around the new facility.",
      ],
      metricIds: ["kongsberg-current-workers", "kongsberg-fullrate-workers", "kongsberg-toano-investment"],
    },
    {
      type: "safety",
      title: "Missile production hazard profile",
      narrative:
        "The highest-risk Toano roles are propulsion integration and warhead assembly. The uploaded report flags ammonium perchlorate, solid rocket motor propellant, high explosive fill, RDX/PBXN, and medical-fitness requirements for explosive-material handling.",
      bullets: [
        "Propulsion integration requires thyroid baseline logic for ammonium perchlorate exposure.",
        "Warhead assembly requires medical fitness for workers handling explosive materials.",
        "If threshold quantities of highly hazardous chemicals are stored, process safety management may apply.",
        "Baseline documentation should exist before the production workforce ramps.",
      ],
      metricIds: ["kongsberg-fullrate-injuries"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The opportunity is not volume; it is timing and protocol specificity. Occu-Med can help build the medical surveillance program while Toano is still ramping.",
      bullets: [
        "Pre-employment and pre-placement exams should be job-specific before full-rate production.",
        "Protocol stack should include thyroid baseline, explosives fitness, respirator clearance, hearing conservation, confined-space evaluation, and DBA pre-deployment where applicable.",
        "The uploaded report frames the next 6-12 months as the relationship-building window.",
      ],
      metricIds: ["kongsberg-dba-exposure"],
    },
  ],
};
