import type { CompanyConfig } from "./types";

export const leidosConfig: CompanyConfig = {
  companyId: "leidos",
  displayName: "Leidos Holdings, Inc.",
  shortName: "Leidos",
  sector:
    "Defense systems, digital modernization, health and civil federal IT, intelligence, space, missile defense, aviation, manufacturing, and Antarctic support operations",
  headquarters: "Reston, Virginia",
  employees: 47000,
  employeesAsOf: "Uploaded Leidos city-by-city hiring activity analysis: FY2025 context",
  summary:
    "Leidos is a Fortune 500 federal technology and defense entity with approximately 47,000 global employees, $16.7B FY2025 revenue, and nearly 1,900 open positions in the uploaded hiring analysis. Hiring intensity is concentrated in Reston, Huntsville, Chantilly, Bethesda, San Diego, Colorado Springs, Odenton, and Springfield, with major demand across intelligence, software engineering, systems engineering, cyber, radar, missile systems, manufacturing, health IT, space systems, and federal enterprise services. The profile should be treated as a hiring-footprint intelligence record rather than an injury-cost model until a full Occu-Med safety report is uploaded.",
  tags: [
    "Entity profile",
    "Leidos",
    "Hiring intelligence",
    "Fortune 500",
    "Defense Systems",
    "Digital Modernization",
    "Health & Civil",
    "Huntsville manufacturing",
    "Intelligence community",
    "Space systems",
    "Antarctic support",
  ],
  aliases: ["Leidos", "Leidos Holdings", "Leidos Holdings, Inc.", "LDOS"],
  sourceFilters: {
    sec: { ticker: "LDOS", legalEntities: ["Leidos Holdings, Inc."] },
    sam: { legalNames: ["Leidos, Inc.", "Leidos Holdings, Inc."] },
    usaSpending: { recipientNames: ["Leidos", "Leidos Inc"] },
    jobSources: { linkedin: "leidos", careerSite: "https://careers.leidos.com/" },
    newsSources: { aliases: ["Leidos", "LDOS", "Leidos Defense Systems", "Leidos Digital Modernization", "Leidos Health & Civil"] },
  },
  executiveSignals: [
    { label: "Open positions", value: "1,894+", note: "Uploaded city-by-city hiring analysis identifies 1,894+ current open positions globally." },
    { label: "Active hubs", value: "13", note: "Summary identifies 13 active hiring locations with 10+ postings or major concentration." },
    { label: "Revenue", value: "$16.7B", note: "Uploaded context lists FY2025 revenue at $16.7B." },
    { label: "Workforce", value: "47K", note: "Large global workforce across defense, digital modernization, and health/civil sectors." },
  ],
  curveTitle: "Leidos hiring intensity and mission-footprint curve",
  curveSubtitle:
    "Uploaded city-by-city hiring activity normalized into entity-profile charts; posting counts are open-source hiring signals and should be refreshed before operational use.",
  chartDefinitions: [
    {
      id: "leidos-active-us-hubs",
      title: "Leidos active U.S. hiring hubs",
      subtitle: "Midpoint or reported count from uploaded city-by-city hiring table.",
      type: "bar",
      xKey: "city",
      data: [
        { city: "Huntsville AL", postings: 135.5 },
        { city: "Bethesda MD", postings: 105 },
        { city: "Reston VA", postings: 101.5 },
        { city: "Chantilly VA", postings: 87.5 },
        { city: "Odenton MD", postings: 60 },
        { city: "Springfield VA", postings: 32.5 },
        { city: "San Diego CA", postings: 31 },
        { city: "Colorado Springs CO", postings: 34.5 },
      ],
      series: [{ dataKey: "postings", name: "Current postings", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "active hubs",
      fullWidth: true,
    },
    {
      id: "leidos-moderate-hubs",
      title: "Leidos moderate U.S. hiring locations",
      subtitle: "Selected moderate hubs from the uploaded hiring table.",
      type: "bar",
      xKey: "city",
      data: [
        { city: "Tampa FL", postings: 14 },
        { city: "Pittsburgh PA", postings: 10 },
        { city: "Fort Worth TX", postings: 10 },
        { city: "Houston TX", postings: 15 },
        { city: "Orlando FL", postings: 27 },
        { city: "Aurora CO", postings: 26 },
        { city: "Tewksbury MA", postings: 14 },
        { city: "Omaha NE", postings: 13 },
      ],
      series: [{ dataKey: "postings", name: "Current postings", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "moderate hubs",
    },
    {
      id: "leidos-sector-footprint",
      title: "Leidos sector footprint priority",
      subtitle: "Three reported business sectors weighted by hiring relevance in the uploaded analysis.",
      type: "bar",
      xKey: "sector",
      data: [
        { sector: "Defense Systems", priority: 10 },
        { sector: "Digital Modernization", priority: 10 },
        { sector: "Health & Civil", priority: 8 },
        { sector: "Antarctic Support", priority: 6 },
        { sector: "Space / Missile Defense", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "sector mix",
    },
    {
      id: "leidos-international-signals",
      title: "Leidos international and special-environment signals",
      subtitle: "Uploaded table flags Antarctica, Australia, UK, and APAC activity in addition to the U.S. footprint.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "Antarctica", postings: 7 },
        { region: "Australia", postings: 20 },
        { region: "United Kingdom", postings: 10 },
        { region: "Asia-Pacific", postings: 6 },
        { region: "Europe/Middle East", postings: 6 },
      ],
      series: [{ dataKey: "postings", name: "Posting signal", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "global signal",
    },
  ],
  metricDefinitions: [
    { id: "leidos-employees", label: "Employees", value: 47000, unit: "count", category: "workforce" },
    { id: "leidos-revenue", label: "FY2025 revenue", value: 16.7, unit: "usd", category: "financial" },
    { id: "leidos-open-positions", label: "Open positions", value: 1894, unit: "count", category: "workforce" },
    { id: "leidos-active-hubs", label: "Active hiring hubs", value: 13, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "Huntsville defense manufacturing", revenue: 135.5, risk: 7.5, workers: 5000 },
    { name: "Intelligence / cyber hubs", revenue: 250, risk: 4.5, workers: 12000 },
    { name: "Space / missile defense", revenue: 80, risk: 6.5, workers: 3500 },
    { name: "Health IT / federal programs", revenue: 105, risk: 5.0, workers: 6000 },
    { name: "Antarctic support", revenue: 7, risk: 8.0, workers: 200 },
  ],
  opportunityMatrix: [
    { name: "Hiring surge pre-employment", revenuePotential: 1894, implementationComplexity: 6, strategicValue: 9 },
    { name: "Manufacturing / radar surveillance", revenuePotential: 750, implementationComplexity: 7, strategicValue: 9 },
    { name: "Antarctic medical support", revenuePotential: 250, implementationComplexity: 8, strategicValue: 8 },
    { name: "Space/missile readiness", revenuePotential: 450, implementationComplexity: 7, strategicValue: 8 },
    { name: "Federal health/civil screening", revenuePotential: 500, implementationComplexity: 5, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Leidos is currently represented by hiring intelligence. The uploaded analysis shows a very large, geographically distributed federal technology and defense workforce with unusually broad hiring volume.",
      bullets: [
        "Company context lists 47,000 global employees and $16.7B FY2025 revenue.",
        "The report identifies 1,894+ current open positions globally.",
        "Three business sectors are Defense Systems, Digital Modernization, and Health & Civil.",
        "Headquarters and the highest corporate concentration are in Reston, Virginia.",
      ],
      metricIds: ["leidos-employees", "leidos-revenue", "leidos-open-positions"],
    },
    {
      type: "hiring",
      title: "Hiring concentration",
      narrative:
        "The highest hiring intensity is concentrated in Huntsville, Bethesda, Reston, Chantilly, Odenton, Springfield, San Diego, and Colorado Springs.",
      bullets: [
        "Huntsville is the largest active hiring hub with manufacturing, assembly, radar, signal processing, missile systems, hypersonics, NASA, and space systems roles.",
        "Reston, Chantilly, Odenton, and Springfield reflect the Northern Virginia / Maryland intelligence and federal IT corridor.",
        "Colorado Springs is tied to space systems, missile defense, USSPACECOM, and Space Force support.",
        "San Diego and Norfolk/Newport News/Hampton indicate naval systems and defense engineering demand.",
      ],
      metricIds: ["leidos-active-hubs"],
    },
    {
      type: "locations",
      title: "Special-environment footprint",
      narrative:
        "The uploaded file also flags Antarctica support, APAC, Australia, and Europe/Middle East postings. Those signals should be preserved separately from the core CONUS hiring map because they imply different medical-readiness requirements.",
      bullets: [
        "Antarctica: systems admin, systems engineering, IT support, and logistics under scientific research / National Science Foundation support.",
        "Australia: Canberra and Scoresby/Melbourne appear as active international locations.",
        "Tampa, Colorado Springs, and Fort Belvoir connect Leidos to CENTCOM, Space Force, and Army enterprise IT environments.",
      ],
      metricIds: [],
    },
  ],
};
