import type { CompanyConfig } from "./types";

export const leonardoConfig: CompanyConfig = {
  companyId: "leonardo-drs",
  displayName: "Leonardo DRS",
  shortName: "Leonardo DRS",
  sector:
    "Defense technology manufacturing, naval power systems, ground vehicle electronics, sensors, counter-UAS, directed energy, field service technicians, and OCONUS sustainment",
  headquarters: "Arlington, Virginia / Leonardo SpA parent in Italy",
  employees: 9500,
  employeesAsOf: "Uploaded Leonardo DRS Occu-Med intelligence report: U.S. operations model",
  summary:
    "Leonardo DRS is a U.S.-listed defense technology manufacturer majority-owned by Italy's Leonardo SpA. The uploaded Occu-Med report frames DRS as a hardware manufacturer and field-integration contractor, not an IT services company. Its risk profile comes from naval power systems manufacturing, land systems electronics integration, sensors and targeting manufacturing, counter-UAS / directed-energy engineering, and an 800-person field service technician population that may spend 50-75% of the working year on CONUS and OCONUS rotations. The Occu-Med opportunity is baseline documentation, high-voltage/manufacturing surveillance, field service pre-rotation medicals, DBA documentation, veteran baseline documentation, and RF/EMF / laser / ergonomics protocols.",
  tags: [
    "Entity profile",
    "Leonardo DRS",
    "Defense manufacturing",
    "Naval power systems",
    "Land systems electronics",
    "Field service technicians",
    "OCONUS DBA",
    "High-voltage testing",
    "RF/EMF",
    "Veteran baseline",
    "Counter-UAS",
  ],
  aliases: ["Leonardo DRS", "DRS", "Leonardo DRS, Inc.", "NASDAQ: DRS", "Leonardo SpA"],
  sourceFilters: {
    sec: { ticker: "DRS", legalEntities: ["Leonardo DRS, Inc."] },
    sam: { legalNames: ["Leonardo DRS", "DRS Network & Imaging Systems", "DRS Naval Power Systems"] },
    usaSpending: { recipientNames: ["Leonardo DRS", "DRS"] },
    jobSources: { linkedin: "leonardo-drs", careerSite: "https://careers.leonardodrs.com/" },
    newsSources: { aliases: ["Leonardo DRS", "DRS", "Leonardo SpA", "IM-SHORAD", "Zumwalt", "counter-UAS"] },
  },
  executiveSignals: [
    { label: "Expected injuries", value: "119/yr", note: "Uploaded report models expected annual U.S. operations injuries from BLS benchmarks applied to 9,500 U.S. employees." },
    { label: "Direct cost", value: "$5.12M/yr", note: "119 expected injuries multiplied by the $43K NSC average direct cost assumption." },
    { label: "Total burden", value: "$28.1M/yr", note: "Uploaded report applies a 5.5x OSHA indirect-cost multiplier to the direct-cost estimate." },
    { label: "DBA exposure", value: "$6.0M/yr", note: "Modeled annual DBA claim exposure from OCONUS field service technician injuries." },
  ],
  curveTitle: "Leonardo DRS manufacturing, field-service, and DBA exposure curve",
  curveSubtitle:
    "Uploaded Leonardo DRS Occu-Med report normalized into entity-profile charts; values are strategic modeling assumptions requiring validation with DRS program and worker data.",
  chartDefinitions: [
    {
      id: "leonardo-five-numbers",
      title: "Leonardo DRS five numbers that matter",
      subtitle: "Uploaded report: U.S. operations exposure model.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Expected injuries", value: 119 },
        { metric: "Direct cost ($M)", value: 5.12 },
        { metric: "Economic burden ($M)", value: 28.1 },
        { metric: "DBA exposure ($M)", value: 6.0 },
        { metric: "Severe event EV ($K)", value: 149 },
      ],
      series: [{ dataKey: "value", name: "Modeled value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "exposure model",
      fullWidth: true,
    },
    {
      id: "leonardo-segment-injuries",
      title: "Expected injuries by segment",
      subtitle: "The uploaded table shows physical manufacturing and FST work drive most expected injuries.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "Naval Power Mfg", injuries: 27, trir: 1.8, headcount: 1500 },
        { segment: "Land Systems Mfg", injuries: 30, trir: 1.5, headcount: 2000 },
        { segment: "FST OCONUS", injuries: 20, trir: 2.5, headcount: 800 },
        { segment: "Sensors/Targeting", injuries: 24, trir: 1.2, headcount: 2000 },
        { segment: "C-UAS/Directed Energy", injuries: 7, trir: 0.7, headcount: 1000 },
        { segment: "Software/Systems", injuries: 6, trir: 0.5, headcount: 1200 },
        { segment: "PM/Corporate", injuries: 5, trir: 0.5, headcount: 1000 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/yr", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "segment injuries",
      fullWidth: true,
    },
    {
      id: "leonardo-trir-by-segment",
      title: "BLS TRIR benchmark by segment",
      subtitle: "FST, naval power, land systems, and sensors work are not generic IT risk lanes.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "FST OCONUS", trir: 2.5 },
        { segment: "Naval Power Mfg", trir: 1.8 },
        { segment: "Land Systems Mfg", trir: 1.5 },
        { segment: "Sensors/Targeting", trir: 1.2 },
        { segment: "C-UAS/Directed Energy", trir: 0.7 },
        { segment: "Software/Systems", trir: 0.5 },
      ],
      series: [{ dataKey: "trir", name: "BLS / analog TRIR", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 3],
      headline: "TRIR segments",
    },
    {
      id: "leonardo-rotation-calendar",
      title: "FST annual DBA exposure pattern",
      subtitle: "Two four-month OCONUS rotations can place a field technician under DBA exposure for eight months of the year.",
      type: "bar",
      xKey: "month",
      data: [
        { month: "Jan", exposure: 1 },
        { month: "Feb", exposure: 1 },
        { month: "Mar", exposure: 1 },
        { month: "Apr", exposure: 1 },
        { month: "May", exposure: 0 },
        { month: "Jun", exposure: 0 },
        { month: "Jul", exposure: 1 },
        { month: "Aug", exposure: 1 },
        { month: "Sep", exposure: 1 },
        { month: "Oct", exposure: 1 },
        { month: "Nov", exposure: 0 },
        { month: "Dec", exposure: 0 },
      ],
      series: [{ dataKey: "exposure", name: "DBA-active month", color: "#dc2626", radius: [8, 8, 0, 0] }],
      domain: [0, 1],
      headline: "rotation exposure",
    },
    {
      id: "leonardo-medical-priority",
      title: "Leonardo DRS Occu-Med priority map",
      subtitle: "Priority lanes derived from manufacturing, veteran baseline, FST rotation, and directed-energy exposure sections.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "FST pre-rotation medical", priority: 10 },
        { lane: "DBA documentation", priority: 10 },
        { lane: "Veteran baseline", priority: 9 },
        { lane: "High-voltage / RF-EMF", priority: 9 },
        { lane: "Manufacturing MSK baseline", priority: 8 },
        { lane: "Laser/optic surveillance", priority: 8 },
        { lane: "Hearing conservation", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "priority map",
    },
  ],
  metricDefinitions: [
    { id: "leonardo-employees", label: "U.S. employees", value: 9500, unit: "count", category: "workforce" },
    { id: "leonardo-revenue", label: "FY2025 revenue tracking", value: 3.5, unit: "usd", category: "financial" },
    { id: "leonardo-expected-injuries", label: "Expected injuries/yr", value: 119, unit: "count", category: "safety" },
    { id: "leonardo-direct-cost", label: "Direct annual injury cost", value: 5.12, unit: "usd", category: "financial" },
    { id: "leonardo-economic-burden", label: "Total economic burden", value: 28.1, unit: "usd", category: "financial" },
    { id: "leonardo-dba-exposure", label: "Annual DBA claim exposure", value: 6.0, unit: "usd", category: "risk" },
    { id: "leonardo-fst", label: "Field service technicians", value: 800, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "Field Service Techs", revenue: 6000, risk: 9.5, workers: 800 },
    { name: "Land systems integration", revenue: 3000, risk: 8.0, workers: 2000 },
    { name: "Naval power systems", revenue: 2700, risk: 8.5, workers: 1500 },
    { name: "Sensors / targeting", revenue: 2400, risk: 7.5, workers: 2000 },
    { name: "Directed energy / RF", revenue: 700, risk: 8.0, workers: 1000 },
  ],
  opportunityMatrix: [
    { name: "FST Pre-Rotation Medicals", revenuePotential: 800, implementationComplexity: 6, strategicValue: 10 },
    { name: "DBA Medical Documentation", revenuePotential: 600, implementationComplexity: 7, strategicValue: 10 },
    { name: "Manufacturing Pre-Placement", revenuePotential: 1200, implementationComplexity: 5, strategicValue: 9 },
    { name: "High-Voltage / RF-EMF Surveillance", revenuePotential: 350, implementationComplexity: 8, strategicValue: 9 },
    { name: "Veteran Baseline Documentation", revenuePotential: 500, implementationComplexity: 7, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Leonardo DRS should be treated as a manufacturing and field-service account, not as a generic defense technology office population. The uploaded report emphasizes that the physical work is real and the DBA exposure is unusually concentrated in the FST population.",
      bullets: [
        "Approximately 9,500 U.S. employees and FY2025 revenue tracking around $3.5B.",
        "Majority-owned by Italy's Leonardo SpA.",
        "Manufactures naval propulsion, land systems electronics, sensors, counter-UAS systems, and vehicle fire-control systems.",
        "Field Service Technicians may deploy 50-75% of their working year on 4-6 month rotations.",
      ],
      metricIds: ["leonardo-employees", "leonardo-revenue", "leonardo-expected-injuries"],
    },
    {
      type: "safety",
      title: "Manufacturing and FST exposure",
      narrative:
        "The expected-injury model is driven by Land Systems, Naval Power Systems, Sensors/Targeting, and Field Service Technician populations. These roles involve electronics assembly, vehicle integration, high-voltage testing, optics, soldering, chemicals, and combat-vehicle field maintenance.",
      bullets: [
        "Naval Power Systems manufacturing: 1,500 workers and 27 modeled injuries per year.",
        "Land Systems electronics manufacturing and integration: 2,000 workers and 30 modeled injuries per year.",
        "FST OCONUS population: 800 workers and 20 modeled injuries per year.",
        "Counter-UAS and directed energy engineers carry RF/EMF and high-voltage testing exposure.",
      ],
      metricIds: ["leonardo-direct-cost", "leonardo-economic-burden"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The strongest account-opening wedge is FST pre-rotation medical documentation. The uploaded report argues the exam should occur before each rotation, not only at hire, because worker baseline can change during the year.",
      bullets: [
        "Pre-rotation medicals protect the DBA record for each 4-6 month deployment cycle.",
        "Veteran baseline documentation matters because many FSTs and defense manufacturing workers may have prior service-related musculoskeletal, hearing, or TBI exposure histories.",
        "Manufacturing protocols should include MSK/cardiovascular baseline, hearing, vision, high-voltage/RF-EMF, and chemicals/soldering exposure surveillance.",
      ],
      metricIds: ["leonardo-dba-exposure", "leonardo-fst"],
    },
  ],
};
