import type { CompanyConfig } from "./types";

export const magAerospaceConfig: CompanyConfig = {
  companyId: "mag-aerospace",
  displayName: "MAG Aerospace",
  shortName: "MAG",
  sector:
    "ISR aviation, C5ISR integration, special mission aircraft operations, unmanned systems, aviation maintenance, acquisition support, and defense technology services",
  headquarters: "Fairfax, Virginia",
  employees: 1000,
  employeesAsOf: "Uploaded MAG Aerospace hiring activity analysis",
  summary:
    "MAG Aerospace is a veteran-founded ISR, C5ISR, specialty aviation, and tactical systems entity headquartered in Fairfax, Virginia. The uploaded city-by-city hiring analysis describes a company with 1,000+ global employees, 200+ manned and unmanned special mission aircraft, roughly 100,000 flight hours annually across six continents, and a workforce that is approximately 75% veteran. Current hiring is concentrated in Fairfax, Fort Belvoir, and Huntsville/Redstone Arsenal, with sustained aviation engineering and mission support activity across Virginia, Maryland, Georgia, Canada, and quiet international aviation nodes.",
  tags: [
    "Entity profile",
    "ISR aviation",
    "C5ISR",
    "Special mission aircraft",
    "UAS",
    "Veteran workforce",
    "Fairfax HQ",
    "Fort Belvoir",
    "Redstone Arsenal",
    "Aviation maintenance",
    "Canada wildfire aviation",
  ],
  aliases: ["MAG Aerospace", "MAG Aero", "MAG", "MAG Aerospace Canada"],
  sourceFilters: {
    sam: { legalNames: ["MAG Aerospace", "MAG Aerospace Industries", "MAG Aero"] },
    usaSpending: { recipientNames: ["MAG Aerospace", "MAG Aero"] },
    jobSources: { linkedin: "mag-aerospace", careerSite: "https://www.magaero.com/careers" },
    newsSources: { aliases: ["MAG Aerospace", "MAG Aero", "MAG Aerospace Canada", "ATHENA-R", "MC-208 Guardian"] },
  },
  executiveSignals: [
    {
      label: "Current postings",
      value: "49–90",
      note: "Uploaded hiring analysis estimates 49-90 current open positions across US and international locations.",
    },
    {
      label: "Active hubs",
      value: "3",
      note: "Fairfax, Fort Belvoir, and Huntsville/Redstone Arsenal are the three active concentrations with 10+ postings or major concentration.",
    },
    {
      label: "Veteran workforce",
      value: "~75%",
      note: "Uploaded analysis identifies MAG as veteran-founded with a workforce that is roughly 75% veteran.",
    },
    {
      label: "Operational scale",
      value: "200+ aircraft",
      note: "Company context lists 200+ manned/unmanned special mission aircraft and roughly 100,000 annual flight hours across six continents.",
    },
  ],
  curveTitle: "MAG Aerospace hiring, aviation operations, and ISR growth curve",
  curveSubtitle:
    "Uploaded city-by-city hiring activity normalized into entity-profile charts; posting counts are open-source hiring signals and should be refreshed before operational use.",
  chartDefinitions: [
    {
      id: "mag-hiring-by-city-us",
      title: "MAG Aerospace US hiring activity by city",
      subtitle: "Midpoint of uploaded current posting ranges; active concentration is strongest in Fairfax, Fort Belvoir, and Huntsville/Redstone Arsenal.",
      type: "bar",
      xKey: "city",
      data: [
        { city: "Fairfax VA", postings: 18.5 },
        { city: "Fort Belvoir VA", postings: 15.0 },
        { city: "Huntsville AL", postings: 12.5 },
        { city: "Patuxent River MD", postings: 7.5 },
        { city: "Augusta GA", postings: 6.0 },
        { city: "Newport News VA", postings: 7.0 },
        { city: "Quantico VA", postings: 5.0 },
        { city: "Aberdeen PG MD", postings: 4.0 },
        { city: "Washington DC", postings: 4.0 },
      ],
      series: [{ dataKey: "postings", name: "Current postings midpoint", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "US hiring hubs",
      fullWidth: true,
    },
    {
      id: "mag-activity-level-counts",
      title: "Locations by activity level",
      subtitle: "Uploaded summary: 3 active, 8 moderate, and 20 quiet locations across US and international footprint.",
      type: "bar",
      xKey: "activity",
      data: [
        { activity: "Active", locations: 3 },
        { activity: "Moderate", locations: 8 },
        { activity: "Quiet", locations: 20 },
      ],
      series: [{ dataKey: "locations", name: "Locations", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "activity mix",
    },
    {
      id: "mag-job-family-distribution",
      title: "Job family distribution",
      subtitle: "Uploaded report distribution of hiring demand by job family.",
      type: "bar",
      xKey: "family",
      data: [
        { family: "Engineering", share: 40 },
        { family: "Aviation Ops", share: 25 },
        { family: "Acquisition / PM", share: 20 },
        { family: "Intel / Cyber", share: 10 },
        { family: "Business Ops", share: 5 },
      ],
      series: [{ dataKey: "share", name: "Share of demand", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 45],
      headline: "job mix",
    },
    {
      id: "mag-canada-hiring",
      title: "MAG Canada aviation hiring signal",
      subtitle: "Canada activity centers on Sudbury and Waterloo, with quiet activity in Dryden and Kenora.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Sudbury ON", postings: 7.0 },
        { location: "Waterloo ON", postings: 5.0 },
        { location: "Dryden ON", postings: 2.0 },
        { location: "Kenora ON", postings: 2.0 },
      ],
      series: [{ dataKey: "postings", name: "Current postings midpoint", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "Canada aviation",
    },
    {
      id: "mag-international-footprint",
      title: "Quiet international footprint by region",
      subtitle: "International nodes are mostly quiet but show aviation, ISR, program management, and logistics support reach.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "Europe / Middle East", locations: 4 },
        { region: "Africa", locations: 2 },
        { region: "Latin America", locations: 1 },
        { region: "Asia-Pacific", locations: 1 },
        { region: "Middle East contingency", locations: 1 },
        { region: "Oceania", locations: 1 },
      ],
      series: [{ dataKey: "locations", name: "Listed locations", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "global nodes",
    },
    {
      id: "mag-program-priority",
      title: "MAG notable contract/program priority map",
      subtitle: "Strategic programs from uploaded hiring analysis converted into visual intelligence weights.",
      type: "bar",
      xKey: "program",
      data: [
        { program: "Army SETA", priority: 10 },
        { program: "ATHENA-R", priority: 10 },
        { program: "CBP SATCOM", priority: 8 },
        { program: "Army C5ISR", priority: 8 },
        { program: "NIWC Atlantic", priority: 7 },
        { program: "Canada wildfire", priority: 7 },
        { program: "MC-208 Guardian", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Strategic priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "program signals",
    },
  ],
  metricDefinitions: [
    { id: "mag-employees", label: "Employees", value: 1000, unit: "count", category: "workforce" },
    { id: "mag-aircraft", label: "Special mission aircraft", value: 200, unit: "count", category: "workforce" },
    { id: "mag-flight-hours", label: "Annual flight hours", value: 100000, unit: "count", category: "workforce" },
    { id: "mag-veteran-workforce", label: "Veteran workforce", value: 75, unit: "percent", category: "workforce" },
    { id: "mag-open-positions-low", label: "Open positions low", value: 49, unit: "count", category: "workforce" },
    { id: "mag-open-positions-high", label: "Open positions high", value: 90, unit: "count", category: "workforce" },
    { id: "mag-active-locations", label: "Active hiring hubs", value: 3, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "Fairfax tactical systems", revenue: 18.5, risk: 4.0, workers: 200 },
    { name: "Fort Belvoir SETA", revenue: 15.0, risk: 4.5, workers: 180 },
    { name: "Huntsville ISR/UAS", revenue: 12.5, risk: 6.0, workers: 160 },
    { name: "Aviation maintenance", revenue: 10.0, risk: 8.0, workers: 120 },
    { name: "Canada wildfire aviation", revenue: 7.0, risk: 8.5, workers: 100 },
    { name: "International ISR support", revenue: 5.0, risk: 7.0, workers: 80 },
  ],
  opportunityMatrix: [
    { name: "Aviation Medical Surveillance", revenuePotential: 350, implementationComplexity: 6, strategicValue: 9 },
    { name: "Pre-Employment Physicals", revenuePotential: 225, implementationComplexity: 4, strategicValue: 7 },
    { name: "Hearing Conservation", revenuePotential: 150, implementationComplexity: 4, strategicValue: 8 },
    { name: "Respirator Clearance", revenuePotential: 120, implementationComplexity: 5, strategicValue: 7 },
    { name: "OCONUS / Field Readiness", revenuePotential: 200, implementationComplexity: 7, strategicValue: 9 },
    { name: "DOT / Pilot / Flight Ops Support", revenuePotential: 150, implementationComplexity: 6, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "The uploaded analysis presents MAG Aerospace as a Fairfax-based specialty aviation and ISR entity whose hiring footprint is concentrated around Virginia and Alabama defense hubs, with secondary aviation activity in Canada and quiet international program nodes.",
      bullets: [
        "Company context lists 1,000+ global employees and 200+ manned/unmanned special mission aircraft.",
        "MAG is described as operating roughly 100,000 flight hours annually across six continents.",
        "The workforce is approximately 75% veteran and the company was founded by veterans.",
        "Core focus areas are ISR, C5ISR, special mission aviation, unmanned systems, aviation engineering, and tactical systems development.",
      ],
      metricIds: ["mag-employees", "mag-aircraft", "mag-flight-hours", "mag-veteran-workforce"],
    },
    {
      type: "hiring",
      title: "Active hiring concentration",
      narrative:
        "The clearest hiring signal is concentrated in three active hubs: Fairfax, Fort Belvoir, and Huntsville/Redstone Arsenal. These represent corporate/tactical systems development, Army SETA acquisition support, and aviation engineering/ISR integration activity.",
      bullets: [
        "Fairfax, VA: 15-22 postings across full-stack, AI/ML, analytics, DevSecOps, robotics, network engineering, cloud admin, and capture management.",
        "Fort Belvoir, VA: 12-18 postings tied to Army SETA acquisition, logistics, systems engineering, and product-office team lead support.",
        "Huntsville/Redstone Arsenal, AL: 10-15 postings around aviation engineering, ISR integration, UAS SMEs, systems engineering, and logistics.",
        "Moderate hubs include Newport News, Quantico, Aberdeen Proving Ground, Patuxent River, Augusta, Washington/DC Metro, Sudbury, and Waterloo.",
      ],
      metricIds: ["mag-open-positions-low", "mag-open-positions-high", "mag-active-locations"],
    },
    {
      type: "locations",
      title: "Geographic footprint",
      narrative:
        "The uploaded city-by-city table identifies a Virginia-heavy US footprint, Alabama Army aviation concentration, Canadian aviation maintenance and wildfire operations, and quiet international nodes in Europe, the Middle East, Africa, Latin America, Asia-Pacific, and Oceania.",
      bullets: [
        "Virginia dominance: Fairfax, Fort Belvoir, Newport News, Quantico, and Herndon are core operations and engineering hubs.",
        "Maryland activity: Aberdeen Proving Ground and Patuxent River support EW, cyber, ISR, supply/logistics, aviation ops, and naval aviation engineering.",
        "Canada: Sudbury and Waterloo are moderate hubs for aircraft maintenance engineers, flight instructors, pilots, GIS technicians, wildfire detection, and Air Cadet training.",
        "Quiet international locations include London, Ljubljana, Madrid, Riyadh, Bamako, Harare, Bogota, Wellington, Kabul, and Wagga Wagga.",
      ],
      metricIds: [],
    },
    {
      type: "workforce",
      title: "Job family distribution",
      narrative:
        "The uploaded report estimates hiring demand by job family, with engineering leading the mix and aviation operations representing a substantial operational workforce signal.",
      bullets: [
        "Engineering: 40% of demand, including systems, cloud, network, software, AI/ML, DevSecOps, robotics, electrical, and avionics roles.",
        "Aviation Operations: 25%, including pilots, aircraft maintenance engineers, flight instructors, and field service representatives.",
        "Acquisition / Program Management: 20%, including SETA analysts, acquisition leads, logistics analysts, and admin support.",
        "Intelligence / Cyber: 10%, including ISR operators, intelligence analysts, information operations researchers, and EW specialists.",
      ],
      metricIds: [],
    },
    {
      type: "contracts",
      title: "Notable contracts and programs",
      narrative:
        "The hiring analysis highlights a set of programs that explain the entity's demand pattern: Army SETA support, ATHENA-R, CBP SATCOM/avionics, Army C5ISR, NIWC Atlantic, Canadian wildfire aviation, and MC-208 Guardian.",
      bullets: [
        "U.S. Army SETA at Fort Belvoir and Huntsville is a major acquisition and product-office support lane.",
        "ATHENA-R is identified as an aerial ISR platform tied to a Lockheed Martin partnership.",
        "CBP contingent hiring includes SATCOM field engineers and avionics engineers.",
        "Canadian wildfire management includes aerial fire detection and air tactical / birddog services.",
      ],
      metricIds: [],
    },
    {
      type: "safety",
      title: "Aviation and field-operations occupational medicine implications",
      narrative:
        "This upload is a hiring and location analysis rather than a full injury-cost report. The occupational medicine implication is that MAG's aviation maintenance, flight operations, ISR field work, and international support nodes likely require medical surveillance and readiness protocols beyond office-based engineering hiring.",
      bullets: [
        "Aircraft maintenance and avionics roles imply hearing conservation, respirator clearance, chemical exposure, ergonomics, and safety-sensitive work screening needs.",
        "Pilots, flight instructors, field service reps, and ISR operators imply aviation medical/readiness and fatigue-risk considerations.",
        "International aviation and ISR mission support nodes imply potential OCONUS/field-readiness documentation requirements.",
        "This profile should be supplemented later with injury, DBA, workers' compensation, and exam-volume modeling if available.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "MAG values in this profile are extracted from the uploaded city-by-city hiring activity analysis. Posting counts are hiring signals, not audited workforce counts or confirmed contract headcount. Midpoints were used for chart rendering where the source provided ranges.",
      bullets: [
        "Do not present posting ranges as exact staffing levels.",
        "Treat quiet international locations as low-visibility operating nodes until corroborated by contracts or direct company data.",
        "Program priority scores are visual intelligence weights derived from the report, not audited financial values.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "deep-analysis",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
