import type { CompanyConfig } from "./types";

export const masterPortfolioIntelligenceConfig: CompanyConfig = {
  companyId: "master-portfolio-intelligence",
  displayName: "Master Portfolio Intelligence",
  shortName: "Master Portfolio",
  sector:
    "Portfolio-level defense and federal contractor occupational medicine intelligence, injury-burden modeling, DBA exposure, surveillance opportunity, and entity prioritization",
  headquarters: "Portfolio-level intelligence entity",
  employees: 629945,
  employeesAsOf: "Uploaded master portfolio report: February 20, 2026; enhanced with chart pack 4 portfolio sizing data",
  summary:
    "Master roll-up profile for 21 defense/federal contractor accounts. The uploaded report quantifies a portfolio-wide occupational medicine opportunity across 630,945 workers, 5,233 expected injuries per year, $2.59B in total economic burden (master report baseline), $255M in DBA exposure, and $56.2M-$84.8M in modeled annual Occu-Med revenue potential with a $70.5M midpoint. Chart pack 4 provides an enhanced model with $1.24B burden, $268.5M DBA exposure, and $65.5M revenue midpoint. The report separates the portfolio into four operating populations: large defense integrators, mid-size OCONUS services, defense manufacturing/production, and specialized niche service entities. Chart pack 4 adds provider-network share analysis showing 97.9% third-party provider dependence and priority-tier exam volume distribution.",
  tags: [
    "Portfolio intelligence",
    "Master report",
    "Defense contractors",
    "Federal contractors",
    "DBA exposure",
    "Economic burden",
    "TRIR distribution",
    "Revenue potential",
    "Prioritization",
    "Surveillance programs",
  ],
  aliases: [
    "Master Portfolio Report",
    "21 Defense/Federal Contractor Accounts",
    "Portfolio Rollup",
    "Portfolio Intelligence",
  ],
  sourceFilters: {
    newsSources: {
      aliases: [
        "Occu-Med master portfolio report",
        "defense contractor occupational medicine portfolio",
        "DBA exposure portfolio",
      ],
    },
  },
  executiveSignals: [
    {
      label: "Total workforce",
      value: "630,945",
      note: "Combined workforce across the uploaded 21-account defense/federal contractor portfolio from chart pack 4.",
    },
    {
      label: "Expected injuries",
      value: "5,233/yr",
      note: "Portfolio-level modeled injuries per year across all included accounts.",
    },
    {
      label: "Economic burden",
      value: "$2.59B/yr",
      note: "Master report baseline total burden; chart pack 4 enhanced model shows $1.24B.",
    },
    {
      label: "Occu-Med potential",
      value: "$70.5M/yr",
      note: "Master report baseline revenue midpoint; chart pack 4 enhanced model shows $65.5M.",
    },
    {
      label: "Provider dependence",
      value: "97.9% third-party",
      note: "Chart pack 4 shows Occu-Med own facilities at 2.1% and third-party providers at 97.9%.",
    },
  ],
  curveTitle: "Portfolio-wide injury burden, DBA exposure, and revenue opportunity curve",
  curveSubtitle:
    "Uploaded master report values normalized into one portfolio entity. Values should be treated as modeled Occu-Med intelligence, not audited employer disclosures.",
  chartDefinitions: [
    {
      id: "portfolio-executive-costs",
      title: "Executive summary: portfolio cost and exposure",
      subtitle: "Master report roll-up: $1.24B total burden, $268.5M DBA exposure, and $65.5M revenue midpoint.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Direct injury cost", value: 225.0 },
        { metric: "Economic burden", value: 1240.0 },
        { metric: "DBA exposure", value: 268.5 },
        { metric: "Fatality exposure", value: 5.3 },
        { metric: "Revenue midpoint", value: 65.5 },
      ],
      series: [{ dataKey: "value", name: "Annual amount", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "portfolio economics",
      fullWidth: true,
    },
    {
      id: "portfolio-workforce-and-injuries",
      title: "Portfolio workforce and injury scale",
      subtitle: "Total workforce, expected injuries, and OCONUS injuries from the master report.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Total workforce", value: 629945 },
        { metric: "Expected injuries", value: 5233 },
        { metric: "OCONUS injuries", value: 895 },
      ],
      series: [{ dataKey: "value", name: "Count", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "portfolio scale",
    },
    {
      id: "portfolio-tier-workforce",
      title: "Portfolio tier workforce comparison",
      subtitle: "Four operating tiers from the master report; note that the source text contains minor count/list inconsistencies but the totals are preserved.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "Large Integrators", workers: 180000 },
        { tier: "Specialized Services", workers: 71400 },
        { tier: "Manufacturing", workers: 331775 },
        { tier: "Niche Services", workers: 46770 },
      ],
      series: [{ dataKey: "workers", name: "Workers", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "tier workforce",
      fullWidth: true,
    },
    {
      id: "portfolio-tier-burden",
      title: "Portfolio tier economic burden",
      subtitle: "Tier burden from master report: large integrators and specialized services drive most modeled burden.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "Large Integrators", burden: 665 },
        { tier: "Specialized Services", burden: 321 },
        { tier: "Manufacturing", burden: 212 },
        { tier: "Niche Services", burden: 40 },
      ],
      series: [{ dataKey: "burden", name: "Economic burden", color: "#ef4444", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "tier burden",
    },
    {
      id: "portfolio-tier-revenue",
      title: "Occu-Med revenue potential by tier",
      subtitle: "Modeled revenue range by tier; manufacturing has the largest absolute opportunity because of headcount and surveillance volume.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "Large Integrators", low: 18.6, high: 28.0 },
        { tier: "Specialized Services", low: 6.7, high: 10.1 },
        { tier: "Manufacturing", low: 28.9, high: 43.3 },
        { tier: "Niche Services", low: 5.1, high: 7.7 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "tier revenue",
    },
    {
      id: "portfolio-top-burden-accounts",
      title: "Top accounts by annual economic burden",
      subtitle: "Chart values from the uploaded master report visual; these are modeled annual economic burden values in $M.",
      type: "bar",
      xKey: "account",
      data: [
        { account: "RTX", burden: 282.5 },
        { account: "Northrop", burden: 188.7 },
        { account: "KBR", burden: 114.9 },
        { account: "Amentum", burden: 112.8 },
        { account: "L3Harris", burden: 88.7 },
        { account: "Leidos", burden: 68.1 },
        { account: "PAE", burden: 51.6 },
        { account: "GDIT", burden: 50.8 },
        { account: "Serco", burden: 47.4 },
        { account: "Maximus", burden: 46.1 },
      ],
      series: [{ dataKey: "burden", name: "Economic burden", color: "#dc2626", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "burden concentration",
      fullWidth: true,
    },
    {
      id: "portfolio-dba-exposure-by-account",
      title: "Annual DBA claim exposure by account",
      subtitle: "OCONUS service contractors drive concentrated unlimited DBA liability; top five accounts combine for roughly $186M/year.",
      type: "bar",
      xKey: "account",
      data: [
        { account: "Amentum", exposure: 54.0 },
        { account: "KBR", exposure: 45.0 },
        { account: "PAE", exposure: 37.5 },
        { account: "Vectrus", exposure: 25.5 },
        { account: "DynCorp", exposure: 24.0 },
        { account: "Leidos", exposure: 18.0 },
        { account: "GDIT", exposure: 12.0 },
        { account: "IAP", exposure: 9.8 },
        { account: "SAIC", exposure: 9.0 },
        { account: "Peraton", exposure: 8.7 },
        { account: "ECC", exposure: 6.7 },
        { account: "RTX", exposure: 6.0 },
        { account: "L3Harris", exposure: 4.5 },
        { account: "Valiant", exposure: 3.3 },
        { account: "Northrop", exposure: 2.4 },
        { account: "Maximus", exposure: 1.0 },
        { account: "Serco", exposure: 0.4 },
      ],
      series: [{ dataKey: "exposure", name: "Annual DBA exposure", color: "#f97316", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "DBA concentration",
      fullWidth: true,
    },
    {
      id: "portfolio-revenue-midpoint-by-account",
      title: "Occu-Med revenue potential by account midpoint",
      subtitle: "Master report visual values shown in $K/year. RTX and Northrop dominate midpoint opportunity.",
      type: "bar",
      xKey: "account",
      data: [
        { account: "RTX", revenue: 17344 },
        { account: "Northrop", revenue: 8900 },
        { account: "Amentum", revenue: 4989 },
        { account: "KBR", revenue: 4750 },
        { account: "L3Harris", revenue: 4688 },
        { account: "Leidos", revenue: 4500 },
        { account: "PAE", revenue: 3400 },
        { account: "GDIT", revenue: 2560 },
        { account: "SAIC", revenue: 2560 },
        { account: "Serco", revenue: 1890 },
        { account: "Maximus", revenue: 1870 },
        { account: "ECC", revenue: 1785 },
        { account: "Peraton", revenue: 1700 },
        { account: "Vectrus", revenue: 1312 },
        { account: "DynCorp", revenue: 1032 },
        { account: "Valiant", revenue: 884 },
        { account: "Peckham", revenue: 645 },
        { account: "Kongsberg", revenue: 224 },
        { account: "IAP", revenue: 202 },
        { account: "Source Group", revenue: 114 },
        { account: "Tecmotiv", revenue: 96 },
      ],
      series: [{ dataKey: "revenue", name: "Revenue midpoint", color: "#22c55e", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "revenue distribution",
      fullWidth: true,
    },
    {
      id: "portfolio-trir-distribution",
      title: "Portfolio TRIR distribution",
      subtitle: "Manufacturing entities cluster lower, while OCONUS services and niche hazardous-work entities carry higher modeled TRIR.",
      type: "bar",
      xKey: "account",
      data: [
        { account: "RTX", trir: 0.30 },
        { account: "L3Harris", trir: 0.75 },
        { account: "Northrop", trir: 0.84 },
        { account: "Leidos", trir: 1.20 },
        { account: "SAIC", trir: 1.22 },
        { account: "Peraton", trir: 1.31 },
        { account: "GDIT", trir: 1.43 },
        { account: "Maximus", trir: 1.77 },
        { account: "Amentum", trir: 1.80 },
        { account: "Serco", trir: 2.00 },
        { account: "PAE", trir: 2.42 },
        { account: "KBR", trir: 2.56 },
        { account: "Kongsberg", trir: 2.94 },
        { account: "Peckham", trir: 3.05 },
        { account: "Source Group", trir: 3.50 },
        { account: "Valiant", trir: 4.10 },
        { account: "Vectrus", trir: 4.80 },
        { account: "DynCorp", trir: 5.09 },
        { account: "IAP", trir: 5.43 },
        { account: "ECC", trir: 5.66 },
        { account: "Tecmotiv", trir: 5.87 },
      ],
      series: [{ dataKey: "trir", name: "TRIR", color: "#ef4444", radius: [10, 10, 0, 0] }],
      referenceLines: [{ y: 1.0, stroke: "#94a3b8", strokeDasharray: "4 4", label: { value: "OSHA world-class 1.0", fill: "#94a3b8", fontSize: 11 } }],
      domain: [0, 7],
      headline: "TRIR spread",
      fullWidth: true,
    },
    {
      id: "portfolio-compliance-case",
      title: "Portfolio compliance case",
      subtitle: "Mandated or liability-critical populations identified in the master report.",
      type: "bar",
      xKey: "population",
      data: [
        { population: "HAZWOPER surveillance", workers: 105 },
        { population: "Asbestos surveillance", workers: 100 },
        { population: "OCONUS FSRs", workers: 600 },
        { population: "Contact center ergonomics", workers: 8000 },
        { population: "UXO fitness", workers: 27 },
      ],
      series: [{ dataKey: "workers", name: "Workers", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      headline: "compliance populations",
    },
    {
      id: "portfolio-priority-map",
      title: "Portfolio prioritization roadmap",
      subtitle: "Immediate, high-value expansion, and long-tail optimization targets converted to visual priority scores.",
      type: "bar",
      xKey: "target",
      data: [
        { target: "Kongsberg", priority: 10 },
        { target: "ECC", priority: 10 },
        { target: "IAP", priority: 9 },
        { target: "Northrop", priority: 9 },
        { target: "KBR", priority: 9 },
        { target: "Amentum", priority: 9 },
        { target: "Tier 3 Manufacturing", priority: 7 },
        { target: "Maximus/Serco Ergo", priority: 7 },
        { target: "Niche Accounts", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Priority score", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "next steps",
      fullWidth: true,
    },
    {
      id: "portfolio-provider-network-share",
      title: "Provider network visit share",
      subtitle: "Chart pack 4: Occu-Med own facilities = 2.1%; 97.9% third-party provider reliance.",
      type: "bar",
      xKey: "provider",
      data: [
        { provider: "All Others", visits: 5979, share: 36.5 },
        { provider: "Concentra", visits: 2691, share: 16.4 },
        { provider: "Swedish Specialist (Erbil)", visits: 1975, share: 12.0 },
        { provider: "British Medical (Kuwait)", visits: 1785, share: 10.8 },
        { provider: "Agile OccMed (CA)", visits: 1723, share: 10.5 },
        { provider: "Asian Medical (Qatar)", visits: 652, share: 4.0 },
        { provider: "Apollo Medical", visits: 402, share: 2.5 },
        { provider: "Occu-Med Own", visits: 355, share: 2.1 },
        { provider: "Kwajalein Hospital", visits: 332, share: 2.0 },
        { provider: "AFC", visits: 277, share: 1.7 },
        { provider: "Akeso", visits: 240, share: 1.5 },
      ],
      series: [{ dataKey: "visits", name: "Clinic visits", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "provider share",
      fullWidth: true,
    },
    {
      id: "portfolio-priority-tier-exam-volume",
      title: "Exam volume distribution by priority tier",
      subtitle: "Chart pack 4: Tier 1 critical locations carry most annual exam volume.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "Tier 1 Critical", annualExamVolume: 2229 },
        { tier: "Tier 2 High", annualExamVolume: 454 },
        { tier: "Tier 3 Medium", annualExamVolume: 194 },
      ],
      series: [{ dataKey: "annualExamVolume", name: "Annual exam volume", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "priority volume",
    },
    {
      id: "portfolio-priority-tier-location-count",
      title: "Location count by priority tier",
      subtitle: "Chart pack 4: Tier 3 has more locations, but Tier 1 carries the demand concentration.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "Tier 1 Critical", locations: 10 },
        { tier: "Tier 2 High", locations: 3 },
        { tier: "Tier 3 Medium", locations: 13 },
      ],
      series: [{ dataKey: "locations", name: "Number of locations", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "priority locations",
    },
  ],
  metricDefinitions: [
    { id: "portfolio-workforce", label: "Total workforce", value: 630945, unit: "count", category: "workforce" },
    { id: "portfolio-expected-injuries", label: "Expected injuries/yr", value: 5233, unit: "count", category: "safety" },
    { id: "portfolio-weighted-trir", label: "Portfolio-weighted TRIR", value: 0.83, unit: "score", category: "safety" },
    { id: "portfolio-direct-cost", label: "Direct injury cost", value: 225.0, unit: "usd", category: "financial" },
    { id: "portfolio-economic-burden", label: "Total economic burden", value: 2590, unit: "usd", category: "financial" },
    { id: "portfolio-oconus-injuries", label: "OCONUS injuries/yr", value: 895, unit: "count", category: "risk" },
    { id: "portfolio-dba-exposure", label: "Total DBA exposure", value: 255, unit: "usd", category: "risk" },
    { id: "portfolio-fatality-exposure", label: "Fatality exposure", value: 5.3, unit: "usd", category: "risk" },
    { id: "portfolio-revenue-low", label: "Occu-Med revenue low", value: 56.2, unit: "usd", category: "financial" },
    { id: "portfolio-revenue-high", label: "Occu-Med revenue high", value: 84.8, unit: "usd", category: "financial" },
    { id: "portfolio-revenue-midpoint", label: "Occu-Med revenue midpoint", value: 70.5, unit: "usd", category: "financial" },
    { id: "portfolio-own-facility-share", label: "Own-facility share", value: 2.1, unit: "percent", category: "risk" },
    { id: "portfolio-third-party-share", label: "Third-party provider share", value: 97.9, unit: "percent", category: "risk" },
  ],
  riskMatrix: [
    { name: "Large Integrators", revenue: 28.0, risk: 7.0, workers: 180000 },
    { name: "Specialized OCONUS Services", revenue: 10.1, risk: 9.0, workers: 71400 },
    { name: "Defense Manufacturing", revenue: 43.3, risk: 6.5, workers: 331775 },
    { name: "Specialized Niche Services", revenue: 7.7, risk: 8.0, workers: 46770 },
  ],
  opportunityMatrix: [
    { name: "RTX", revenuePotential: 17344, implementationComplexity: 9, strategicValue: 10 },
    { name: "Northrop", revenuePotential: 8900, implementationComplexity: 9, strategicValue: 10 },
    { name: "Amentum", revenuePotential: 4989, implementationComplexity: 8, strategicValue: 9 },
    { name: "KBR", revenuePotential: 4750, implementationComplexity: 8, strategicValue: 9 },
    { name: "L3Harris", revenuePotential: 4688, implementationComplexity: 7, strategicValue: 8 },
    { name: "Leidos", revenuePotential: 4500, implementationComplexity: 7, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Executive summary: the $1.24B opportunity",
      narrative:
        "The uploaded master report converts individual entity reports into one quantified portfolio view. Across 629,945 workers, the model estimates 5,233 expected injuries per year, $225M in direct injury cost, $1.24B in total economic burden, and $52.3M-$78.7M in annual Occu-Med revenue potential.",
      bullets: [
        "Portfolio-weighted TRIR is modeled at 0.83 across 21 defense/federal contractor accounts.",
        "Total DBA exposure is modeled at $268.5M per year from 895 OCONUS injuries.",
        "The midpoint annual Occu-Med revenue opportunity is $65.5M.",
        "The report argues the portfolio pays for itself if the program prevents 528 injuries, or 10.1% of expected annual injuries.",
      ],
      metricIds: ["portfolio-workforce", "portfolio-expected-injuries", "portfolio-economic-burden", "portfolio-revenue-midpoint"],
    },
    {
      type: "workforce",
      title: "Portfolio composition: four distinct tiers",
      narrative:
        "The report organizes the portfolio into four strategic populations with different sales and clinical playbooks: large integrators, mid-size specialized OCONUS service contractors, defense manufacturing/production accounts, and specialized niche service accounts.",
      bullets: [
        "Tier 1 large defense integrators: mature safety programs, significant OCONUS exposure, DBA claims, cleared workforce protocols.",
        "Tier 2 specialized services: highest TRIR range, intensive OCONUS deployment, logistics/base operations, and $117M combined DBA exposure.",
        "Tier 3 manufacturing/production: lower TRIR but very high surveillance volume across HAZWOPER, hearing, chemical exposure, and manufacturing baselines.",
        "Tier 4 niche accounts: lower headcount but high medical-surveillance complexity, including ADA, UXO, HAZWOPER, asbestos, and CTD interventions.",
      ],
      metricIds: [],
    },
    {
      type: "safety",
      title: "Concentration analysis",
      narrative:
        "The portfolio is heavily concentrated. RTX, Northrop, KBR, Amentum, and L3Harris dominate burden and revenue opportunity; DBA exposure is even more concentrated among OCONUS service contractors.",
      bullets: [
        "Top burden accounts include RTX, Northrop, KBR, Amentum, L3Harris, Leidos, PAE, GDIT, Serco, and Maximus.",
        "Top DBA exposure accounts are Amentum, KBR, PAE, Vectrus, and DynCorp, combining for roughly $186M/year.",
        "Revenue is driven by volume in manufacturing accounts and complexity in OCONUS/specialized accounts.",
        "Manufacturing accounts have the highest absolute revenue due to headcount; OCONUS service accounts have higher revenue per worker due to DBA pre-deployment requirements.",
      ],
      metricIds: ["portfolio-dba-exposure", "portfolio-revenue-midpoint"],
    },
    {
      type: "safety",
      title: "TRIR distribution: two populations",
      narrative:
        "The report shows two different risk populations. Manufacturing accounts cluster between 0.30 and 2.94 TRIR, while field logistics, construction, hazardous remediation, and OCONUS base operations cluster as high as 5.87 TRIR.",
      bullets: [
        "Lower-TRIR manufacturing entities include RTX, L3Harris, Northrop, Leidos, and SAIC.",
        "High-TRIR OCONUS/service or hazardous-work entities include Tecmotiv, ECC, IAP, DynCorp, Vectrus, and Valiant.",
        "The 7x spread is not random; it reflects climate-controlled office/production work versus field logistics, construction, remediation, and base operations.",
      ],
      metricIds: ["portfolio-weighted-trir"],
    },
    {
      type: "medical-opportunities",
      title: "Portfolio-wide value proposition",
      narrative:
        "The master value proposition is that Occu-Med does not merely perform occupational medicine; it executes the specific medical-surveillance programs federal contracts, OSHA standards, DBA exposure, and specialized workforces require.",
      bullets: [
        "A 10% reduction in injury burden equals $124M in annual cost avoidance across the portfolio.",
        "At a $65.5M revenue midpoint, the program pays for itself if it prevents 528 injuries.",
        "Travelers first-year injury logic is used to support pre-employment baselines and first-year surveillance as the most practical reduction pathway.",
        "The moat is specialization: DBA, HAZWOPER, disability workforce ADA compliance, UXO fitness, and foreign deployment protocols.",
      ],
      metricIds: ["portfolio-revenue-low", "portfolio-revenue-high"],
    },
    {
      type: "procurement",
      title: "Strategic positioning by account type",
      narrative:
        "The report defines three different sales messages: surveillance enhancement for manufacturing accounts, DBA pre-deployment protocols for OCONUS accounts, and specialty clinical expertise for niche accounts.",
      bullets: [
        "Manufacturing: 'We are not replacing your program. We are upgrading it to match the compliance reality of 2026.'",
        "OCONUS services: 'Every worker who boards a plane enters the Defense Base Act system; the pre-deployment medical is your only insurance policy against unlimited liability.'",
        "Niche accounts: 'You need a physician who has read the OSHA standard that governs your workforce.'",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "Next steps: portfolio prioritization",
      narrative:
        "The report prioritizes execution into immediate targets, high-value expansion, and long-tail optimization. The immediate targets are smaller or urgent enough to attack first; the high-value targets carry the largest burden and DBA exposure; the long tail creates durable specialization.",
      bullets: [
        "Immediate targets: Kongsberg, ECC, and IAP Worldwide.",
        "High-value expansion: Northrop Grumman, KBR, and Amentum.",
        "Long-tail optimization: Tier 3 manufacturing surveillance, Maximus/Serco ergonomic intervention, and specialized niche accounts.",
        "The portfolio is mapped; the opportunity is quantified; the next phase is execution.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "The master portfolio values are modeled from uploaded entity reports and the master roll-up document. They are excellent for prioritization and sales strategy, but they should not be presented as audited employer disclosures.",
      bullets: [
        "Preserve model/source language around TRIR, expected injuries, DBA exposure, economic burden, and revenue potential.",
        "The source report contains minor internal inconsistencies in tier counts and burden text versus chart values; the profile preserves the chart values where visual data is more detailed.",
        "Before external presentation, validate each target's current headcount, contract status, active policy/carrier lane, and current occupational medicine vendor status.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "comparative-benchmark",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
