import type { CompanyConfig } from "./types";

export const maximusFederalConfig: CompanyConfig = {
  companyId: "maximus-federal",
  displayName: "Maximus Federal / Maximus Inc.",
  shortName: "Maximus Federal",
  sector:
    "Federal clinical assessment services, Veterans Evaluation Services, medical disability exams, contact centers, benefits administration, federal healthcare support, and OCONUS VES Region 7 clinical operations",
  headquarters: "Tysons / McLean, Virginia",
  employees: 36000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 20, 2026",
  summary:
    "Maximus Inc. is a large government services entity whose US Federal Services segment operates as the federal government's clinical assessment engine. The uploaded Occu-Med intelligence report focuses on Maximus Federal and its Veterans Evaluation Services subsidiary, which conducts VA Medical Disability Exams across seven national regions, including Region 7 OCONUS. The report frames Maximus as a clinical, contact-center, and benefits-administration risk profile rather than a defense manufacturing or cleared IT profile.",
  tags: [
    "Entity profile",
    "Federal clinical assessments",
    "Veterans Evaluation Services",
    "VES",
    "VA MDE",
    "PACT Act surge",
    "Contact center CTD",
    "DBA OCONUS",
    "TB surveillance",
    "Ergonomics",
    "ESG disclosure gap",
  ],
  aliases: ["Maximus", "Maximus Inc.", "Maximus Federal", "Veterans Evaluation Services", "VES", "MMS"],
  sourceFilters: {
    sec: { ticker: "MMS", legalEntities: ["Maximus Inc."] },
    sam: { legalNames: ["Maximus Federal Services", "Maximus Inc.", "Veterans Evaluation Services"] },
    usaSpending: { recipientNames: ["Maximus", "Maximus Federal", "Veterans Evaluation Services"] },
    jobSources: { linkedin: "maximus", careerSite: "https://maximus.com/careers" },
    newsSources: { aliases: ["Maximus", "Maximus Federal", "Veterans Evaluation Services", "VES", "PACT Act MDE"] },
  },
  executiveSignals: [
    {
      label: "Expected injuries",
      value: "195/yr",
      note: "Modeled from BLS benchmarks applied to roughly 22,000 US Federal Services workers.",
    },
    {
      label: "Economic burden",
      value: "$46.1M/yr",
      note: "Direct annual injury cost of $8.38M multiplied by OSHA indirect cost factor.",
    },
    {
      label: "First-year burden",
      value: "$16.6M/yr",
      note: "70 injuries from first-year workers, driven by PACT Act surge hiring and lack of pre-employment musculoskeletal baselines.",
    },
    {
      label: "Occu-Med potential",
      value: "$1.49M–$2.25M/yr",
      note: "Modeled opportunity across pre-employment, TB/clinical screening, contact-center ergonomics, annual TB surveillance, and DBA pre-deployment lanes.",
    },
  ],
  curveTitle: "Maximus Federal clinical assessment and contact-center risk curve",
  curveSubtitle:
    "Uploaded Occu-Med intelligence values normalized for entity-profile scanning; modeled estimates should be treated as assumption-driven signals, not audited employer disclosures.",
  chartDefinitions: [
    {
      id: "maximus-five-numbers",
      title: "Maximus Federal five exposure numbers that matter",
      subtitle: "Source: uploaded Maximus Federal report; modeled injury, cost, first-year burden, and DBA exposure values.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Direct injury cost", value: 8.38 },
        { metric: "Economic burden", value: 46.1 },
        { metric: "First-year burden", value: 16.6 },
        { metric: "DBA claim exposure", value: 1.08 },
      ],
      series: [{ dataKey: "value", name: "Annual exposure", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "exposure model",
      fullWidth: true,
    },
    {
      id: "maximus-injuries-by-business-line",
      title: "Expected injuries by Maximus Federal business line",
      subtitle: "Uploaded report: VES clinicians and contact-center workers dominate modeled injury volume.",
      type: "bar",
      xKey: "businessLine",
      data: [
        { businessLine: "VES clinicians", injuries: 90 },
        { businessLine: "Clinical admin", injuries: 32 },
        { businessLine: "Contact center", injuries: 48 },
        { businessLine: "IT / tech", injuries: 15 },
        { businessLine: "PM / corporate", injuries: 10 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/yr", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "injury concentration",
      fullWidth: true,
    },
    {
      id: "maximus-bls-trir-by-line",
      title: "BLS benchmark TRIR by workforce lane",
      subtitle: "Clinical MDE work carries higher benchmark risk than the usual federal IT services profile.",
      type: "bar",
      xKey: "businessLine",
      data: [
        { businessLine: "VES clinicians", trir: 1.8 },
        { businessLine: "Clinical admin", trir: 0.8 },
        { businessLine: "Contact center", trir: 0.6 },
        { businessLine: "Technology / IT", trir: 0.5 },
        { businessLine: "PM / corporate", trir: 0.5 },
      ],
      series: [{ dataKey: "trir", name: "BLS TRIR benchmark", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 2],
      headline: "TRIR benchmark",
    },
    {
      id: "maximus-pact-act-surge",
      title: "PACT Act surge: VES clinician hires vs MDE volume index",
      subtitle: "Uploaded chart: new clinician hiring rose sharply after PACT Act enactment and VES contract volume caps were exceeded.",
      type: "line",
      xKey: "year",
      data: [
        { year: "2021", clinicianHires: 200, mdeIndex: 100 },
        { year: "2022", clinicianHires: 350, mdeIndex: 115 },
        { year: "2023", clinicianHires: 900, mdeIndex: 180 },
        { year: "2024", clinicianHires: 1100, mdeIndex: 240 },
        { year: "2025", clinicianHires: 800, mdeIndex: 285 },
      ],
      series: [
        { dataKey: "clinicianHires", name: "New clinician hires", color: "#ef4444" },
        { dataKey: "mdeIndex", name: "MDE volume index", color: "#22d3ee" },
      ],
      headline: "surge hiring",
      fullWidth: true,
    },
    {
      id: "maximus-contact-center-ergo",
      title: "Contact-center CTD burden by ergonomic intervention level",
      subtitle: "Uploaded chart: full ergonomic + Occu-Med integration reduces CTD injuries by 63% and burden from $14.1M to $5.2M.",
      type: "bar",
      xKey: "intervention",
      data: [
        { intervention: "No ergonomic program", injuries: 48, burden: 14.1 },
        { intervention: "Workstation assessment", injuries: 36, burden: 10.6 },
        { intervention: "Annual surveillance", injuries: 26, burden: 7.5 },
        { intervention: "Full ergo + Occu-Med", injuries: 18, burden: 5.2 },
      ],
      series: [{ dataKey: "injuries", name: "CTD injuries/yr", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "ergonomic gap",
      fullWidth: true,
    },
    {
      id: "maximus-contact-center-burden",
      title: "Contact-center annual economic burden by intervention level",
      subtitle: "Same uploaded intervention model rendered as annual burden in $M.",
      type: "bar",
      xKey: "intervention",
      data: [
        { intervention: "No ergonomic program", burden: 14.1 },
        { intervention: "Workstation assessment", burden: 10.6 },
        { intervention: "Annual surveillance", burden: 7.5 },
        { intervention: "Full ergo + Occu-Med", burden: 5.2 },
      ],
      series: [{ dataKey: "burden", name: "Annual burden", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "CTD burden",
    },
    {
      id: "maximus-revenue-potential",
      title: "Maximus Federal Occu-Med annual revenue potential",
      subtitle: "Uploaded report: full program opportunity range of $1.49M-$2.25M/year across core exam and ergonomic lanes.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Pre-employment", low: 495, high: 792 },
        { examType: "TB / clinical pre-employ", low: 75, high: 131 },
        { examType: "Ergonomic assessments", low: 600, high: 800 },
        { examType: "Annual TB surveillance", low: 250, high: 425 },
        { examType: "DBA pre-deploy", low: 70, high: 100 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "maximus-global-employees", label: "Global employees", value: 36000, unit: "count", category: "workforce" },
    { id: "maximus-us-federal-workers", label: "US Federal workers", value: 22000, unit: "count", category: "workforce" },
    { id: "maximus-expected-injuries", label: "Expected injuries/yr", value: 195, unit: "count", category: "safety" },
    { id: "maximus-direct-cost", label: "Direct injury cost", value: 8.38, unit: "usd", category: "financial" },
    { id: "maximus-economic-burden", label: "Total economic burden", value: 46.1, unit: "usd", category: "financial" },
    { id: "maximus-first-year-burden", label: "First-year injury burden", value: 16.6, unit: "usd", category: "risk" },
    { id: "maximus-dba-exposure", label: "Annual DBA claim exposure", value: 1.08, unit: "usd", category: "risk" },
    { id: "maximus-occumed-revenue-high", label: "Occu-Med revenue potential high", value: 2.25, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "VES clinicians", revenue: 3.07, risk: 8.5, workers: 5000 },
    { name: "Contact centers", revenue: 1.2, risk: 7.0, workers: 8000 },
    { name: "Clinical admin", revenue: 0.8, risk: 5.5, workers: 4000 },
    { name: "Technology / IT", revenue: 0.6, risk: 3.0, workers: 3000 },
    { name: "PM / corporate", revenue: 0.4, risk: 2.5, workers: 2000 },
  ],
  opportunityMatrix: [
    { name: "Ergonomic Assessments", revenuePotential: 800, implementationComplexity: 5, strategicValue: 10 },
    { name: "Pre-Employment Physicals", revenuePotential: 792, implementationComplexity: 4, strategicValue: 9 },
    { name: "Annual TB Surveillance", revenuePotential: 425, implementationComplexity: 5, strategicValue: 8 },
    { name: "TB / Clinical Pre-Employment", revenuePotential: 131, implementationComplexity: 5, strategicValue: 8 },
    { name: "DBA Pre-Deployment", revenuePotential: 100, implementationComplexity: 6, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Maximus Federal is best understood as a federal clinical assessment and benefits-administration entity. The uploaded report identifies Maximus as a $5.43B public company whose US Federal Services segment generated $3.07B in FY2025 revenue and whose VES subsidiary conducts VA Medical Disability Exams across all seven regions.",
      bullets: [
        "Maximus Federal is not a defense manufacturer or traditional cleared IT entity; it is a clinical assessment and benefits-processing engine.",
        "VES conducts Medical Disability Exams for the VA Veterans Benefits Administration.",
        "PACT Act claim volume overwhelmed original VES contract caps and forced early 2025 recompetes.",
        "The report models roughly 22,000 US Federal Services workers and 195 expected injuries per year.",
      ],
      metricIds: ["maximus-us-federal-workers", "maximus-expected-injuries", "maximus-economic-burden"],
    },
    {
      type: "workforce",
      title: "The workforce nobody expects to have injuries",
      narrative:
        "The core finding is that VES clinicians performing 20-30 MDE exams per day face repetitive musculoskeletal risk from range-of-motion testing, manual muscle testing, patient positioning, and keyboard documentation. These are progressive CTD injuries, not sudden trauma.",
      bullets: [
        "VES clinicians are modeled at 5,000 headcount with BLS NAICS 6211 TRIR benchmark of 1.80.",
        "Clinical admin and MDE support are modeled at 4,000 workers with 16 injuries per year.",
        "Contact centers are modeled at 8,000 workers with 48 CTD injuries per year without full ergonomic intervention.",
        "Pre-employment musculoskeletal baselines are positioned as the defensibility document before high-volume MDE work begins.",
      ],
      metricIds: ["maximus-expected-injuries", "maximus-direct-cost"],
    },
    {
      type: "safety",
      title: "PACT Act first-year injury cohort",
      narrative:
        "The uploaded report ties PACT Act claim-volume surge to a first-year injury cohort. New VES clinician hiring increased sharply in 2023-2024, while Travelers data cited by the report says 36% of all workplace injuries occur in first-year employees.",
      bullets: [
        "Estimated new VES clinician hires increased to 900 in 2023 and 1,100 in 2024.",
        "At 3,960 new hires per year across US Federal, the report models 70 of 195 expected injuries as first-year worker injuries.",
        "Those 70 first-year injuries create a modeled $16.6M annual economic burden.",
        "The sales frame is documenting baseline conditions before high-volume clinical work creates a difficult-to-defend claim.",
      ],
      metricIds: ["maximus-first-year-burden"],
    },
    {
      type: "locations",
      title: "VES Region 7 OCONUS DBA exposure",
      narrative:
        "The report identifies VES Region 7 OCONUS as a DBA-covered clinical deployment lane. OCONUS MDE locations include military bases in Europe, INDOPACOM, and CENTCOM, creating a need for pre-deployment baselines before clinicians leave CONUS.",
      bullets: [
        "Example OCONUS environments include Germany, Italy, UK, Spain, Japan, South Korea, Guam, Kuwait, and Bahrain.",
        "Every VES clinician deployed OCONUS on the Region 7 contract is treated as DBA-covered from departure.",
        "The modeled annual DBA claim exposure is $1.08M.",
        "The foundational defense document is a pre-deployment medical baseline for lumbar spine and musculoskeletal conditions.",
      ],
      metricIds: ["maximus-dba-exposure"],
    },
    {
      type: "safety",
      title: "Contact-center CTD and ergonomic intervention",
      narrative:
        "Maximus Federal's contact-center population is modeled at 8,000 workers doing repetitive keyboard and mouse work for 8+ hours daily. The uploaded report says full ergonomic and Occu-Med integration reduces CTD injuries by 63% and saves $8.9M in annual burden compared with no program.",
      bullets: [
        "No ergonomic program baseline: 48 CTD injuries per year and $14.1M annual burden.",
        "Workstation assessment: 36 injuries per year and $10.6M annual burden.",
        "Annual ergonomic surveillance: 26 injuries per year and $7.5M annual burden.",
        "Full ergonomic + Occu-Med integration: 18 injuries per year and $5.2M annual burden.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "ESG disclosure gap",
      narrative:
        "The report notes that Maximus files a 10-K and publishes investor/ESG materials but does not publish TRIR, injury count, or workers' compensation performance data. The absence of published safety metrics is framed as a signal and a potential Occu-Med value proposition.",
      bullets: [
        "The report compares this disclosure gap to SAIC: operational risk is disclosed, but safety performance is not benchmarkable.",
        "Institutional ESG investors have no published safety metric to compare against peers.",
        "Occu-Med's proposed value is to help produce and manage the number, not just perform exams.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded model estimates $1.49M-$2.25M in annual Occu-Med revenue potential across pre-employment physicals, TB/clinical pre-employment, contact-center ergonomic assessments, annual TB surveillance, and DBA pre-deployment exams.",
      bullets: [
        "Pre-employment physicals: 3,960 new hires; modeled $495K-$792K per year.",
        "TB / clinical pre-employment: 750 new VES clinicians; modeled $75K-$131K per year.",
        "Contact center ergonomic assessments: 8,000 workstations; modeled $600K-$800K per year.",
        "Annual TB surveillance: 5,000 clinicians; modeled $250K-$425K per year.",
        "DBA pre-deployment for OCONUS VES Region 7: 200 volume; modeled $70K-$100K per year.",
      ],
      metricIds: ["maximus-occumed-revenue-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "Maximus values in this profile are source-backed but model-driven. The charts should be interpreted as Occu-Med intelligence estimates derived from the uploaded Maximus report, BLS benchmarks, NSC/OSHA cost assumptions, DBA assumptions, PACT Act surge analysis, and ergonomic intervention modeling.",
      bullets: [
        "Do not present modeled injury, DBA, ergonomic savings, or revenue projections as audited Maximus disclosures.",
        "Label the profile as an uploaded Occu-Med intelligence model.",
        "Treat MDE volume, first-year injury, and ergonomic savings as prospecting intelligence requiring validation with Maximus/VES operational data.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "executive-summary",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: false,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
