import type { CompanyConfig } from "./types";

export const missionEssentialConfig: CompanyConfig = {
  companyId: "mission-essential",
  displayName: "Mission Essential / The Mission Group",
  shortName: "Mission Essential",
  sector:
    "Defense intelligence, linguist services, ISR analysis, cyber operations, OSINT/GEOINT/SIGINT support, cleared program management, INSCOM support, EUCOM linguist contracts, and intelligence-community hiring footprint",
  headquarters: "New Albany, Ohio",
  employees: 7500,
  employeesAsOf:
    "Uploaded Mission Essential city-by-city hiring analysis: company context estimates 5,000-10,000 employees, HQ in New Albany OH, 17 domestic U.S. locations and 45+ countries",
  summary:
    "Mission Essential is a defense and intelligence contractor headquartered in New Albany, Ohio, founded in 2004 and specializing in intelligence analysis, ISR, cyber, linguist services, and IC/DoD/State Department support. The uploaded city-by-city hiring file shows the current visible U.S. hiring footprint is concentrated in one active intelligence-community hub, three moderate operational nodes, and three quieter support nodes. Chantilly/Herndon is the active 10+ posting hub tied to IC program management, OSINT, GEOINT, program support, and language instructors. Augusta, Dayton, and New Albany are moderate nodes tied to Fort Eisenhower cyber/INSCOM, Wright-Patterson ISR/OPIR, and corporate HQ functions. The file also notes Mission Essential recently merged with Ghostdog Inc. in August 2025 to form The Mission Group, and that its historical core remains linguist/interpreter services with strong EUCOM DLITE II support.",
  tags: [
    "Entity profile",
    "Mission Essential",
    "The Mission Group",
    "Ghostdog merger",
    "Linguist services",
    "Intelligence analysis",
    "ISR",
    "OSINT",
    "GEOINT",
    "SIGINT",
    "Cyber operations",
    "INSCOM",
    "EUCOM",
    "DLITE II",
    "TS/SCI",
  ],
  aliases: ["Mission Essential", "Mission Essential Personnel", "Mission Essential Group", "The Mission Group", "Ghostdog Inc."],
  sourceFilters: {
    sam: { legalNames: ["Mission Essential", "Mission Essential Personnel", "Mission Essential Group"] },
    usaSpending: { recipientNames: ["Mission Essential", "Mission Essential Personnel", "Mission Essential Group"] },
    jobSources: { linkedin: "mission-essential", careerSite: "https://www.missionessential.com/careers/" },
    newsSources: {
      aliases: ["Mission Essential", "The Mission Group", "Ghostdog", "DLITE II", "EUCOM linguist", "INSCOM cyber"],
    },
  },
  executiveSignals: [
    {
      label: "Estimated workforce",
      value: "5K-10K",
      note: "Uploaded hiring analysis gives company context range of 5,000-10,000 employees.",
    },
    {
      label: "Domestic footprint",
      value: "17 locations",
      note: "Uploaded file says Mission Essential has 17 domestic U.S. locations plus 45+ countries globally.",
    },
    {
      label: "Active U.S. hub",
      value: "Chantilly/Herndon",
      note: "Only active 10+ posting location in the uploaded city-by-city hiring analysis.",
    },
    {
      label: "Clearance profile",
      value: "Secret-TS/SCI",
      note: "Most roles require Secret to TS/SCI, many with polygraph, according to the hiring analysis.",
    },
  ],
  curveTitle: "Mission Essential intelligence, linguist, and cleared-workforce hiring curve",
  curveSubtitle:
    "Uploaded city-by-city hiring analysis normalized into an entity profile. Activity levels are based on visible postings and should be refreshed against current career-site/ClearanceJobs data.",
  chartDefinitions: [
    {
      id: "mission-essential-us-activity",
      title: "Mission Essential U.S. hiring activity by city",
      subtitle: "Uploaded city-by-city analysis: one active IC hub, three moderate nodes, and three quiet locations.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Chantilly/Herndon VA", activityScore: 10, postingsLow: 10 },
        { location: "Augusta GA", activityScore: 6, postingsLow: 3 },
        { location: "Dayton OH", activityScore: 6, postingsLow: 3 },
        { location: "New Albany OH", activityScore: 6, postingsLow: 3 },
        { location: "Columbus GA", activityScore: 2, postingsLow: 0 },
        { location: "Baltimore MD", activityScore: 2, postingsLow: 0 },
        { location: "Columbus OH", activityScore: 2, postingsLow: 0 },
      ],
      series: [{ dataKey: "activityScore", name: "Hiring activity score", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "hiring footprint",
      fullWidth: true,
    },
    {
      id: "mission-essential-activity-summary",
      title: "Activity-level summary",
      subtitle: "The uploaded file groups Mission Essential locations into active, moderate, and quiet buckets.",
      type: "bar",
      xKey: "level",
      data: [
        { level: "Active", locations: 1 },
        { level: "Moderate", locations: 3 },
        { level: "Quiet", locations: 3 },
      ],
      series: [{ dataKey: "locations", name: "Location count", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "activity mix",
    },
    {
      id: "mission-essential-customer-map",
      title: "Primary customer and mission alignment",
      subtitle: "Customer signals from the uploaded hiring pattern summary.",
      type: "bar",
      xKey: "customer",
      data: [
        { customer: "Intelligence Community", priority: 10 },
        { customer: "INSCOM / Fort Eisenhower", priority: 9 },
        { customer: "EUCOM / DLITE II", priority: 9 },
        { customer: "Wright-Patterson / ONI", priority: 8 },
        { customer: "Army training facilities", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Mission relevance", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "customer map",
    },
    {
      id: "mission-essential-job-families",
      title: "Job-family exposure model",
      subtitle: "The hiring file identifies intelligence analysis, linguists, cyber, ISR/imagery, PM, and training operations as core families.",
      type: "bar",
      xKey: "family",
      data: [
        { family: "Intelligence analysis", priority: 10 },
        { family: "Linguists/translators", priority: 10 },
        { family: "Cyber operations", priority: 8 },
        { family: "ISR/imagery", priority: 8 },
        { family: "Program management", priority: 6 },
        { family: "Training operations", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med protocol priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "job families",
      fullWidth: true,
    },
    {
      id: "mission-essential-occumed-wedges",
      title: "Mission Essential Occu-Med service wedges",
      subtitle: "Small physical-injury burden, but strong cleared-workforce, OCONUS, behavioral-health, and linguist protocol value.",
      type: "bar",
      xKey: "wedge",
      data: [
        { wedge: "DBA / OCONUS baseline", priority: 9 },
        { wedge: "Clearance-preservation BH", priority: 10 },
        { wedge: "Linguist hearing/voice", priority: 8 },
        { wedge: "Analyst ergonomics/visual strain", priority: 7 },
        { wedge: "Cyber/SCIF fatigue", priority: 8 },
        { wedge: "Pre-deployment medicals", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Service priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "medical wedge",
    },
  ],
  metricDefinitions: [
    { id: "mission-essential-employees-mid", label: "Estimated employees midpoint", value: 7500, unit: "count", category: "workforce" },
    { id: "mission-essential-employees-low", label: "Estimated employees low", value: 5000, unit: "count", category: "workforce" },
    { id: "mission-essential-employees-high", label: "Estimated employees high", value: 10000, unit: "count", category: "workforce" },
    { id: "mission-essential-domestic-locations", label: "Domestic U.S. locations", value: 17, unit: "count", category: "workforce" },
    { id: "mission-essential-country-footprint", label: "Global country footprint", value: 45, unit: "count", category: "workforce" },
    { id: "mission-essential-active-hubs", label: "Active U.S. hiring hubs", value: 1, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "IC / NoVA cleared workforce", revenue: 10, risk: 8.5, workers: 1500 },
    { name: "Linguists / translators", revenue: 9, risk: 8.0, workers: 2500 },
    { name: "OCONUS / EUCOM support", revenue: 8, risk: 9.0, workers: 1000 },
    { name: "Cyber / INSCOM support", revenue: 7, risk: 7.5, workers: 750 },
    { name: "Corporate / HQ", revenue: 3, risk: 3.0, workers: 500 },
  ],
  opportunityMatrix: [
    { name: "Clearance-Preservation Behavioral Health", revenuePotential: 180, implementationComplexity: 8, strategicValue: 10 },
    { name: "DBA / OCONUS Medical Baselines", revenuePotential: 150, implementationComplexity: 6, strategicValue: 9 },
    { name: "Linguist Hearing / Voice Surveillance", revenuePotential: 120, implementationComplexity: 5, strategicValue: 8 },
    { name: "Analyst Ergonomics / Visual Strain", revenuePotential: 100, implementationComplexity: 5, strategicValue: 7 },
    { name: "Pre-Employment / Deployment Physicals", revenuePotential: 90, implementationComplexity: 4, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Mission Essential is a defense and intelligence contractor with a linguist/interpreter heritage and current activity across intelligence analysis, ISR, cyber, OSINT/GEOINT, program support, and cleared operations.",
      bullets: [
        "Headquartered at 6525 W Campus Oval in New Albany, Ohio, according to the uploaded hiring file.",
        "Founded in 2004 and known for linguist/interpreter services as the original core business.",
        "The file estimates 5,000-10,000 employees, 17 domestic U.S. locations, and 45+ countries.",
        "Recent merger with Ghostdog Inc. in August 2025 formed The Mission Group.",
      ],
      metricIds: ["mission-essential-employees-mid", "mission-essential-domestic-locations", "mission-essential-country-footprint"],
    },
    {
      type: "locations",
      title: "City-by-city hiring footprint",
      narrative:
        "The visible U.S. footprint is concentrated. Chantilly/Herndon is the only active 10+ posting hub, while Augusta, Dayton, and New Albany show moderate activity. Columbus GA, Baltimore, and Columbus OH are quiet in the uploaded snapshot.",
      bullets: [
        "Chantilly/Herndon VA: IC program management hub, OSINT/GEOINT roles, program support, and language instructors.",
        "Augusta GA: Fort Eisenhower cyber and intelligence support.",
        "Dayton OH: Wright-Patterson ISR, OPIR exploitation, and maritime intelligence roles.",
        "New Albany OH: corporate HQ, recruiting, program management, and administrative functions.",
      ],
      metricIds: ["mission-essential-active-hubs"],
    },
    {
      type: "workforce",
      title: "Cleared job-family pattern",
      narrative:
        "Most occupational medicine value comes from cleared workforce realities rather than heavy physical injury volume. The file identifies Secret to TS/SCI requirements, many with polygraph, and job families that carry behavioral health, visual strain, ergonomic, and OCONUS readiness issues.",
      bullets: [
        "Core job families: all-source, GEOINT, SIGINT, CI/HUMINT, OSINT, maritime intelligence, linguists/translators, cyber operations, ISR/imagery, program management, and training operations.",
        "Primary customers include INSCOM, the Intelligence Community, EUCOM, Wright-Patterson/ONI, and Army training facilities.",
        "NoVA/Chantilly shows sustained hiring; Augusta and Dayton show episodic/specialized hiring; HQ locations are stable corporate nodes.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The account should be approached like an IC-adjacent linguist and analyst workforce, not a manufacturing employer. The best wedges are DBA/OCONUS baselines, clearance-preservation behavioral health, linguist hearing/voice surveillance, cyber/SCIF fatigue, and ergonomic/visual-strain protocols.",
      bullets: [
        "DBA and pre-deployment baselines matter for EUCOM and overseas linguist/intelligence support.",
        "Clearance-preservation behavioral health can be framed as a mission-readiness protocol rather than therapy access alone.",
        "Linguist/interpreter work supports headset/hearing, voice strain, visual strain, and ergonomic baselines.",
      ],
      metricIds: [],
    },
  ],
};
