import type { CompanyConfig } from "./types";

export const multiClientLocationIntelligenceConfig: CompanyConfig = {
  companyId: "multi-client-location-intelligence",
  displayName: "Multi-Client Location Intelligence",
  shortName: "Multi-Client Locations",
  sector:
    "Global client co-location analysis, CONUS/OCONUS provider-network strategy, contractor-pair overlap, V2X dependency risk, data-gap detection, provider monopoly risk, and recurring exam demand mapping",
  headquarters: "Occu-Med portfolio-level location intelligence",
  employees: 0,
  employeesAsOf:
    "Uploaded expanded location analysis: 224 global multi-client locations, including 86 CONUS and 138 OCONUS locations with two or more active defense contractors",
  summary:
    "Multi-Client Location Intelligence captures the expanded co-location analysis showing that the network opportunity is far bigger than the first top-10 city view. The uploaded file identifies 224 distinct global locations where two or more active defense contractors co-locate: 86 CONUS and 138 OCONUS. It also adds deeper structural signals: V2X dependency, provider monopoly risk, South Carolina as a CONUS coverage gap, countries with contractor presence but zero or minimal referrals, non-client primes hiring in overlapping cities, and an exam mix where 44% of referrals are annual/periodic and therefore recurring. This profile is meant to drive the network map and provider-build strategy: identify multi-client cities, rank provider risk, separate real gaps from data-capture gaps, and convert location coverage into outreach to multiple clients at once.",
  tags: [
    "Entity profile",
    "Location intelligence",
    "224 locations",
    "86 CONUS",
    "138 OCONUS",
    "Multi-client cities",
    "Provider monopoly risk",
    "V2X dependency",
    "South Carolina gap",
    "Stuttgart gap",
    "Herndon gap",
    "Annual exams",
    "Network map",
  ],
  aliases: ["Multi-Client Locations", "224 Location Map", "Client Co-Location Intelligence", "Network Gap Intelligence"],
  sourceFilters: {
    newsSources: { aliases: ["Occu-Med multi-client locations", "defense contractor co-location", "OCONUS provider gap"] },
  },
  executiveSignals: [
    { label: "Global locations", value: "224", note: "Uploaded analysis identifies 224 locations with two or more active defense contractors." },
    { label: "CONUS / OCONUS", value: "86 / 138", note: "86 CONUS and 138 OCONUS multi-client locations are identified." },
    { label: "Recurring exams", value: "44%", note: "Annual/periodic referrals represent 4,899 referrals and 44% of total referral character in the report." },
    { label: "Critical risk", value: "V2X 49%", note: "The report flags V2X as 49% of defense volume and LOGCAP V as 36% of everything." },
  ],
  curveTitle: "Multi-client location, provider gap, and recurring exam demand curve",
  curveSubtitle:
    "Uploaded expanded location report normalized into a portfolio intelligence entity. Use values as operating intelligence; separate confirmed provider gaps from data-capture gaps before outreach.",
  chartDefinitions: [
    {
      id: "multi-client-location-scale",
      title: "Full scale of multi-client location map",
      subtitle: "224 locations total: 86 CONUS and 138 OCONUS.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "CONUS", locations: 86 },
        { region: "OCONUS", locations: 138 },
      ],
      series: [{ dataKey: "locations", name: "Locations", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "224 locations",
      fullWidth: true,
    },
    {
      id: "multi-client-theaters",
      title: "Multi-client locations by theater",
      subtitle: "OCONUS theater count from uploaded expanded analysis, with CONUS shown as the largest block.",
      type: "bar",
      xKey: "theater",
      data: [
        { theater: "CONUS", locations: 86 },
        { theater: "Middle East & Africa", locations: 42 },
        { theater: "Europe", locations: 34 },
        { theater: "Indo-Pacific", locations: 24 },
        { theater: "Americas", locations: 14 },
      ],
      series: [{ dataKey: "locations", name: "Locations", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "theater spread",
    },
    {
      id: "conus-tier-locations",
      title: "CONUS multi-client city tiers",
      subtitle: "Tier table from uploaded report: Huntsville, Herndon, San Diego, Chantilly, and Arlington anchor the 10+ client tier.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "Tier 1: 10+ clients", locations: 5 },
        { tier: "Tier 2: 7-9 clients", locations: 8 },
        { tier: "Tier 3: 5-6 clients", locations: 10 },
        { tier: "Tier 4: 3-4 clients", locations: 22 },
        { tier: "Tier 5: 2 clients", locations: 41 },
      ],
      series: [{ dataKey: "locations", name: "Locations", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      headline: "CONUS tiers",
      fullWidth: true,
    },
    {
      id: "contractor-co-location-pairs",
      title: "Highest-value contractor co-location pairs",
      subtitle: "Winning one account can warm-introduce the adjacent account in the same city network.",
      type: "bar",
      xKey: "pair",
      data: [
        { pair: "Applus + Weatherford", locations: 21 },
        { pair: "Amentum + PAE", locations: 20 },
        { pair: "Amentum + Peraton", locations: 17 },
        { pair: "CACI + Leidos", locations: 17 },
        { pair: "CACI + GDIT", locations: 16 },
        { pair: "CACI + Camber", locations: 14 },
        { pair: "Amentum + CACI", locations: 13 },
        { pair: "BAE + Leidos", locations: 12 },
      ],
      series: [{ dataKey: "locations", name: "Shared locations", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "co-location pairs",
      fullWidth: true,
    },
    {
      id: "provider-monopoly-risk",
      title: "Provider monopoly risk concentrations",
      subtitle: "Single-provider dependence creates business-continuity risk if pricing, capacity, or accreditation fails.",
      type: "bar",
      xKey: "city",
      data: [
        { city: "Erbil Iraq", visits: 1975 },
        { city: "Mangaf Kuwait", visits: 1765 },
        { city: "Al Warah Qatar", visits: 649 },
        { city: "Sacramento CA", visits: 463 },
        { city: "Fresno CA", visits: 402 },
        { city: "Kwajalein", visits: 332 },
        { city: "Patuxent River MD", visits: 234 },
      ],
      series: [{ dataKey: "visits", name: "Single-provider visits", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "monopoly risk",
    },
    {
      id: "data-gap-locations",
      title: "Immediate investigation targets",
      subtitle: "Locations with documented client presence/referrals but zero or minimal clinic capture in the expanded report.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Stuttgart", clients: 16, referrals: 8 },
        { location: "Herndon VA", clients: 14, referrals: 2 },
        { location: "Washington DC", clients: 9, referrals: 12 },
        { location: "Kuwait City", clients: 8, referrals: 14 },
        { location: "Mexico City", clients: 4, referrals: 6 },
        { location: "Hollywood MD", clients: 5, referrals: 4 },
      ],
      series: [{ dataKey: "clients", name: "Client count", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "gap targets",
    },
    {
      id: "exam-type-breakdown",
      title: "Referral demand by exam character",
      subtitle: "Annual/periodic exams and LOGCAP dominate; both are recurring contract-driven volume.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Annual/Periodic", referrals: 4899 },
        { examType: "LOGCAP", referrals: 3980 },
        { examType: "AFCAP", referrals: 648 },
        { examType: "WPS", referrals: 610 },
        { examType: "NAVMED", referrals: 221 },
        { examType: "Pre-hire", referrals: 144 },
      ],
      series: [{ dataKey: "referrals", name: "Referrals", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "exam mix",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "multi-locations-total", label: "Multi-client locations", value: 224, unit: "count", category: "workforce" },
    { id: "multi-conus", label: "CONUS locations", value: 86, unit: "count", category: "workforce" },
    { id: "multi-oconus", label: "OCONUS locations", value: 138, unit: "count", category: "workforce" },
    { id: "multi-annual-referrals", label: "Annual/periodic referrals", value: 4899, unit: "count", category: "financial" },
    { id: "multi-logcap-referrals", label: "LOGCAP referrals", value: 3980, unit: "count", category: "financial" },
    { id: "multi-v2x-share", label: "V2X defense volume share", value: 49, unit: "percent", category: "risk" },
    { id: "multi-provider-monopoly-cities", label: "Single-provider cities >90%", value: 44, unit: "count", category: "risk" },
  ],
  riskMatrix: [
    { name: "V2X / LOGCAP concentration", revenue: 3980, risk: 10.0, workers: 5427 },
    { name: "Provider monopoly cities", revenue: 44, risk: 9.0, workers: 5400 },
    { name: "Stuttgart data gap", revenue: 16, risk: 8.5, workers: 16 },
    { name: "South Carolina coverage gap", revenue: 278, risk: 8.0, workers: 278 },
    { name: "OCONUS dependency", revenue: 6385, risk: 9.0, workers: 6385 },
  ],
  opportunityMatrix: [
    { name: "Stuttgart / Germany Gap Audit", revenuePotential: 500, implementationComplexity: 7, strategicValue: 10 },
    { name: "Herndon / NoVA Capture Audit", revenuePotential: 400, implementationComplexity: 4, strategicValue: 9 },
    { name: "Provider Backup Program", revenuePotential: 750, implementationComplexity: 8, strategicValue: 10 },
    { name: "South Carolina V2X Fix", revenuePotential: 278, implementationComplexity: 5, strategicValue: 9 },
    { name: "Annual Exam Retention Program", revenuePotential: 4899, implementationComplexity: 6, strategicValue: 10 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "The first pass was too small",
      narrative:
        "The uploaded expanded analysis moves the network map from a top-city list to a full co-location system. It identifies 224 global multi-client locations with 2+ active defense contractors.",
      bullets: [
        "86 CONUS and 138 OCONUS locations are identified.",
        "Middle East/Africa, Europe, Indo-Pacific, and the Americas each have meaningful multi-client clusters.",
        "The app should treat this as a location intelligence layer, not just a company profile list.",
      ],
      metricIds: ["multi-locations-total", "multi-conus", "multi-oconus"],
    },
    {
      type: "locations",
      title: "Structural risks and gaps",
      narrative:
        "The deeper insights are business-model risks: V2X/LOGCAP concentration, provider monopoly exposure, OCONUS dependency, and apparent data gaps where client presence exists but clinic visit capture is missing.",
      bullets: [
        "V2X generates 49% of defense volume and LOGCAP V is 36% of the total defense referral base.",
        "44 cities have one provider handling 90%+ of visits.",
        "Stuttgart and Herndon are flagged as major gap/data-capture audit targets.",
        "South Carolina has a large CONUS coverage deficit driven by V2X Greenville volume.",
      ],
      metricIds: ["multi-v2x-share", "multi-provider-monopoly-cities"],
    },
    {
      type: "medical-opportunities",
      title: "Why this should drive the network map",
      narrative:
        "The most useful output is not a static list. The app should surface co-located clients, current providers, referral character, monopoly risk, and next provider-action at the city level.",
      bullets: [
        "Annual/periodic exams are recurring, predictable, and contract driven.",
        "Provider backup agreements should be prioritized in monopoly-risk cities.",
        "Co-location pairs create bundled outreach opportunities: CACI/Leidos, CACI/GDIT, Amentum/PAE, and Leidos/V2X.",
      ],
      metricIds: ["multi-annual-referrals", "multi-logcap-referrals"],
    },
  ],
};
