import type { CompanyConfig } from "./types";

export const networkGapResearchIntelligenceConfig: CompanyConfig = {
  companyId: "network-gap-research-intelligence",
  displayName: "Network Gap Research Intelligence",
  shortName: "Network Gaps",
  sector:
    "Prospect gap mapping, warm-introduction strategy, sector white-space analysis, defense-prime gaps, oil and gas underpenetration, humanitarian/development DBA opportunities, Alaska Native Corporation targeting, and Chase network research actions",
  headquarters: "Occu-Med network research branch",
  employees: 0,
  employeesAsOf:
    "Uploaded network research branch file: 37 existing clients, 7 sectors, 45 should-be-client companies, and 23 highest-priority targets",
  summary:
    "Network Gap Research Intelligence converts the uploaded branch-research memo into an action profile. The memo says Occu-Med has strong penetration in defense mid-tier accounts but major gaps everywhere else. The client roster functions as a proof-of-concept list to open doors at 45 companies that should be clients. The 23 highest-priority targets include defense-prime gaps such as SAIC, Peraton, KBR, Mission Essential, and Parsons; oil and gas targets such as Halliburton, SLB, Baker Hughes, and Wood Group; humanitarian/development targets such as Chemonics and DAI Global; and Alaska Native Corporation targets such as Akima, Chenega, and Chugach Government Solutions. The operational play for Chase is practical: mine warm intros from existing V2X/Amentum/Leidos/Weatherford relationships, target industry convenings, and use Weatherford as the reference case to open the oilfield-services vertical.",
  tags: [
    "Entity profile",
    "Network research",
    "Prospect gaps",
    "Warm intros",
    "Defense primes",
    "Oil and gas",
    "Humanitarian development",
    "Alaska Native Corps",
    "SAIC",
    "Peraton",
    "KBR",
    "Mission Essential",
    "Parsons",
    "Halliburton",
    "SLB",
    "Baker Hughes",
    "Chemonics",
    "DAI Global",
    "Akima",
    "Chenega",
    "Chugach",
  ],
  aliases: ["Network Research Branch", "Prospect Gap Map", "Should Be Clients", "Warm Intro Intelligence"],
  sourceFilters: {
    newsSources: { aliases: ["Occu-Med prospect gap map", "defense contractor warm intro", "oilfield services occupational health prospects"] },
  },
  executiveSignals: [
    { label: "Existing clients", value: "37", note: "Uploaded memo says the roster includes 37 existing clients across seven sectors." },
    { label: "Should-be clients", value: "45", note: "The memo frames 45 companies as should-be-client targets unlocked by the current client roster." },
    { label: "Priority targets", value: "23", note: "The memo identifies 23 highest-priority targets across defense, oil/gas, humanitarian, and ANC sectors." },
    { label: "Biggest white space", value: "Oil & Gas", note: "Weatherford is the only client in a sector with several global peer targets." },
  ],
  curveTitle: "Network gap, warm intro, and sector white-space curve",
  curveSubtitle:
    "Uploaded network research branch memo normalized into a portfolio profile. Treat target lists as outreach intelligence requiring account/contact verification.",
  chartDefinitions: [
    {
      id: "network-gap-target-sectors",
      title: "Highest-priority target sectors",
      subtitle: "The memo groups the biggest gaps by sector and warm-introduction strategy.",
      type: "bar",
      xKey: "sector",
      data: [
        { sector: "Defense primes", targets: 5 },
        { sector: "Oil & Gas", targets: 4 },
        { sector: "Humanitarian / Development", targets: 2 },
        { sector: "Alaska Native Corps", targets: 3 },
        { sector: "Other priority gaps", targets: 9 },
      ],
      series: [{ dataKey: "targets", name: "Priority targets", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "target sectors",
      fullWidth: true,
    },
    {
      id: "defense-prime-warm-intros",
      title: "Defense-prime warm-intro map",
      subtitle: "The memo identifies specific warm-introduction paths from existing relationship sectors.",
      type: "bar",
      xKey: "target",
      data: [
        { target: "SAIC", priority: 10 },
        { target: "Peraton", priority: 9 },
        { target: "KBR", priority: 10 },
        { target: "Mission Essential", priority: 9 },
        { target: "Parsons", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Intro priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "defense intros",
    },
    {
      id: "oil-gas-white-space",
      title: "Oil & gas white-space targets",
      subtitle: "Weatherford is the reference case; the peers represent the largest underpenetrated vertical.",
      type: "bar",
      xKey: "target",
      data: [
        { target: "Halliburton", priority: 10 },
        { target: "SLB", priority: 10 },
        { target: "Baker Hughes", priority: 9 },
        { target: "Wood Group", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Vertical priority", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "oil & gas",
    },
    {
      id: "chase-actions",
      title: "Network research actions for Chase",
      subtitle: "Three practical actions extracted from the memo.",
      type: "bar",
      xKey: "action",
      data: [
        { action: "Mine warm intros", priority: 10 },
        { action: "Target PSC / AFCEA / AUSA", priority: 9 },
        { action: "Lead Weatherford into oil/gas", priority: 10 },
        { action: "Build ANC referral lane", priority: 9 },
        { action: "Map humanitarian DBA buyers", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Action priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "Chase actions",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "network-gap-existing-clients", label: "Existing clients in roster", value: 37, unit: "count", category: "workforce" },
    { id: "network-gap-sectors", label: "Roster sectors", value: 7, unit: "count", category: "workforce" },
    { id: "network-gap-should-be", label: "Should-be clients", value: 45, unit: "count", category: "financial" },
    { id: "network-gap-priority-targets", label: "Highest-priority targets", value: 23, unit: "count", category: "financial" },
  ],
  riskMatrix: [
    { name: "Defense-prime gaps", revenue: 5, risk: 8.5, workers: 100000 },
    { name: "Oil & gas white space", revenue: 4, risk: 9.0, workers: 200000 },
    { name: "Humanitarian DBA", revenue: 2, risk: 8.5, workers: 20000 },
    { name: "ANC expansion", revenue: 3, risk: 8.0, workers: 25000 },
    { name: "Warm-intro execution", revenue: 45, risk: 6.0, workers: 45000 },
  ],
  opportunityMatrix: [
    { name: "Weatherford-to-Oilfield Campaign", revenuePotential: 4, implementationComplexity: 6, strategicValue: 10 },
    { name: "Defense Prime Warm Intros", revenuePotential: 5, implementationComplexity: 5, strategicValue: 10 },
    { name: "ANC Community Expansion", revenuePotential: 3, implementationComplexity: 5, strategicValue: 9 },
    { name: "Humanitarian DBA Campaign", revenuePotential: 2, implementationComplexity: 7, strategicValue: 9 },
    { name: "Conference Targeting Plan", revenuePotential: 23, implementationComplexity: 4, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Prospect gap map in disguise",
      narrative:
        "The uploaded memo reframes the client roster as a sales asset. It says Occu-Med has proof-of-concept penetration in defense mid-tier work, but that the same proof can open doors across 45 companies that should be clients.",
      bullets: [
        "37 existing clients across seven sectors provide the warm-intro base.",
        "23 highest-priority targets are broken into practical categories.",
        "Defense primes, oilfield services, humanitarian/development, and Alaska Native Corps are the highest-value lanes.",
      ],
      metricIds: ["network-gap-existing-clients", "network-gap-should-be", "network-gap-priority-targets"],
    },
    {
      type: "medical-opportunities",
      title: "Chase action plan",
      narrative:
        "The memo gives three concrete actions: mine current client relationships for warm introductions, target the industry convenings where the same HR/HSE leaders gather, and use Weatherford as the reference case for oilfield services.",
      bullets: [
        "V2X, Amentum, Leidos, ManTech, CACI, Fluor, Jacobs, IDS, and Valiant relationships can map to adjacent targets.",
        "PSC, AFCEA, AUSA, and IADC are the event ecosystems mentioned or implied by the memo's strategy.",
        "The strongest sector white space is oil and gas because Occu-Med already has Weatherford as a reference point.",
      ],
      metricIds: [],
    },
  ],
};
