import type { CompanyConfig } from "./types";

export const networkExpansionIntelligenceConfig: CompanyConfig = {
  companyId: "network-expansion-intelligence",
  displayName: "Network Expansion Intelligence",
  shortName: "Network Expansion",
  sector:
    "Portfolio location overlap, proactive provider-network buildout, prospect/client co-location, OCONUS coverage gaps, clinic utilization, and referral-demand infrastructure strategy",
  headquarters: "Occu-Med portfolio-level network strategy",
  employees: 0,
  employeesAsOf: "Uploaded location, prospect overlap, and clinic-visit strategy files; enhanced with chart packs 2 and 3 network operations data",
  summary:
    "Network Expansion Intelligence converts Alex's core strategic idea into an entity profile: do not wait for an employer to send a referral and then scramble for a clinic. Map where clients, prospects, referral demand, and actual clinic utilization overlap, then build the provider network in advance. The uploaded files identify 872 client location rows across 49 clients, 111 common client locations with three or more clients, 135 strategic prospect locations, 160 prospect/client overlap locations, and 16,387 historic clinic visits across 325 clinics in 40+ countries. The most urgent operational gap highlighted is UAE/Dubai, where the OCONUS coverage scorecard shows 1,003 defense referrals against only 184 clinic visits — roughly 18% coverage — despite Dubai functioning as a transit staging hub for Iraq theater workers. Chart packs 2 and 3 add clinic expansion timeline, exam-type demand, active network clinic volume, OCONUS personal-physician gap analysis, and no-show rate intelligence.",
  tags: [
    "Entity profile",
    "Network strategy",
    "Build before the need",
    "Provider network",
    "Location overlap",
    "Prospect overlap",
    "Clinic utilization",
    "OCONUS coverage",
    "Dubai gap",
    "Referral demand",
    "Infrastructure play",
  ],
  aliases: ["Network Strategy", "Common Locations", "Prospect Network Intelligence", "Clinic Visit Coverage", "Provider Network Expansion"],
  sourceFilters: {
    newsSources: {
      aliases: ["Occu-Med common locations", "Occu-Med clinic visits", "Occu-Med prospect overlap", "network expansion intelligence"],
    },
  },
  executiveSignals: [
    {
      label: "Client location rows",
      value: "872",
      note: "Uploaded common-location file cross-references 872 total location rows across 49 clients.",
    },
    {
      label: "Common client cities",
      value: "111",
      note: "Locations with three or more clients sharing the same city — the proactive provider-network priority list.",
    },
    {
      label: "Clinic visits",
      value: "16,387",
      note: "Uploaded clinic-visit file maps actual provider utilization across 325 clinics in 40+ countries.",
    },
    {
      label: "Dubai coverage",
      value: "18%",
      note: "The uploaded OCONUS scorecard identifies UAE/Dubai as the critical gap: 1,003 referrals vs 184 clinic visits.",
    },
    {
      label: "Top active clinic",
      value: "LabCorp 3,045",
      note: "Chart pack 3 shows LabCorp Solutions as the highest-volume active network clinic.",
    },
    {
      label: "Top no-show rate",
      value: "Trace 8.9%",
      note: "Chart pack 3 no-show chart: Trace Systems leads clients with 100+ events; portfolio average 4.5%.",
    },
  ],
  curveTitle: "Build-the-network-before-the-need curve",
  curveSubtitle:
    "Uploaded client/prospect/common-location and clinic-visit files normalized into a network-expansion intelligence profile. Values are internal strategic planning signals and should be refreshed when location or visit data changes.",
  chartDefinitions: [
    {
      id: "network-data-layers",
      title: "Three-layer network intelligence model",
      subtitle: "Client/prospect locations show where demand could happen; clinic visits show where the existing provider network already works.",
      type: "bar",
      xKey: "layer",
      data: [
        { layer: "Client location rows", value: 872 },
        { layer: "Common client locations", value: 111 },
        { layer: "Strategic prospect locations", value: 135 },
        { layer: "Prospect/client overlaps", value: 160 },
        { layer: "Clinics used", value: 325 },
      ],
      series: [{ dataKey: "value", name: "Count", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "data layers",
      fullWidth: true,
    },
    {
      id: "oconus-coverage-scorecard",
      title: "OCONUS referral demand vs clinic-visit coverage",
      subtitle: "Clinic visits divided by defense referral demand; Dubai is the critical under-covered hub.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Kuwait", referrals: 1787, visits: 1765, coverage: 99 },
        { country: "Iraq", referrals: 1192, visits: 2000, coverage: 168 },
        { country: "UAE / Dubai", referrals: 1003, visits: 184, coverage: 18 },
        { country: "Qatar", referrals: 729, visits: 768, coverage: 105 },
        { country: "Marshall Islands", referrals: 415, visits: 336, coverage: 81 },
        { country: "Jordan", referrals: 261, visits: 269, coverage: 103 },
        { country: "Djibouti", referrals: 176, visits: 179, coverage: 102 },
        { country: "Kenya", referrals: 148, visits: 159, coverage: 107 },
      ],
      series: [{ dataKey: "coverage", name: "Coverage %", color: "#ef4444", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      headline: "OCONUS coverage",
      fullWidth: true,
    },
    {
      id: "oconus-demand-volume",
      title: "OCONUS defense referrals by country",
      subtitle: "Referral demand side of the coverage scorecard.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Kuwait", referrals: 1787 },
        { country: "Iraq", referrals: 1192 },
        { country: "UAE / Dubai", referrals: 1003 },
        { country: "Qatar", referrals: 729 },
        { country: "Marshall Islands", referrals: 415 },
        { country: "Jordan", referrals: 261 },
        { country: "Djibouti", referrals: 176 },
        { country: "Kenya", referrals: 148 },
      ],
      series: [{ dataKey: "referrals", name: "Defense referrals", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "demand volume",
    },
    {
      id: "prospect-critical-locations",
      title: "Tier 1 prospect-dense locations",
      subtitle: "Uploaded prospect network report: cities with 10+ prospect companies maintaining facilities.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "San Diego CA", prospects: 26 },
        { location: "Huntsville AL", prospects: 20 },
        { location: "Arlington VA", prospects: 19 },
        { location: "Washington DC", prospects: 16 },
        { location: "Chantilly VA", prospects: 15 },
        { location: "Doha Qatar", prospects: 15 },
        { location: "Abu Dhabi UAE", prospects: 14 },
        { location: "Colorado Springs CO", prospects: 14 },
        { location: "Norfolk VA", prospects: 14 },
        { location: "Riyadh Saudi Arabia", prospects: 13 },
      ],
      series: [{ dataKey: "prospects", name: "Prospect count", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      headline: "prospect density",
      fullWidth: true,
    },
    {
      id: "network-action-priority",
      title: "Network expansion action priority",
      subtitle: "Priority combines demand volume, provider coverage, prospect/client overlap, and strategic value.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Dubai / UAE", priority: 10 },
        { location: "San Diego CA", priority: 10 },
        { location: "Huntsville AL", priority: 10 },
        { location: "Arlington / DC / Chantilly", priority: 9 },
        { location: "Doha Qatar", priority: 9 },
        { location: "Abu Dhabi UAE", priority: 9 },
        { location: "Riyadh Saudi Arabia", priority: 8 },
        { location: "Marshall Islands", priority: 8 },
        { location: "Norfolk VA", priority: 8 },
        { location: "Colorado Springs CO", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "build priority",
    },
    {
      id: "network-exam-types-completed",
      title: "Exam types — top 12 completed",
      subtitle: "Chart pack 2: drug screens exceed 2,000; medical panels dominate completed volume.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Drug Screen (Pre-Deploy)", completed: 1240 },
        { examType: "M (34 and younger)", completed: 1222 },
        { examType: "M (49 and older)", completed: 857 },
        { examType: "Drug Screen (Random)", completed: 767 },
        { examType: "M (39-48)", completed: 748 },
        { examType: "OVS M (39-48)", completed: 714 },
        { examType: "Saudi Visa", completed: 689 },
        { examType: "M (40-49)", completed: 675 },
        { examType: "M (50 and older)", completed: 604 },
        { examType: "Kuwait Annual", completed: 568 },
        { examType: "OVS M (49 and older)", completed: 463 },
        { examType: "Male (39 and older)", completed: 400 },
      ],
      series: [{ dataKey: "completed", name: "Completed exams", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "exam demand",
      fullWidth: true,
    },
    {
      id: "network-clinic-expansion-timeline",
      title: "Clinic network expansion timeline",
      subtitle: "Chart pack 2: Phase 1 Q2 → Phase 2 Q3 → Phase 3 Q4 → Phase 4 2027. Dates are directional from image labels.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "Dubai Clinic", phase: 1, monthIndex: 4 },
        { site: "Doha Clinic", phase: 1, monthIndex: 5 },
        { site: "Greenville SC", phase: 2, monthIndex: 6 },
        { site: "Fort Worth TX", phase: 2, monthIndex: 6 },
        { site: "CA Central Valley Hub", phase: 2, monthIndex: 7 },
        { site: "Bahrain Clinic", phase: 2, monthIndex: 7 },
        { site: "Stuttgart DE", phase: 3, monthIndex: 10 },
        { site: "Manila PH", phase: 3, monthIndex: 11 },
        { site: "NoVA Cluster", phase: 4, monthIndex: 13 },
        { site: "Saudi Arabia", phase: 4, monthIndex: 14 },
      ],
      series: [{ dataKey: "phase", name: "Phase", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 4],
      headline: "expansion plan",
    },
    {
      id: "network-active-clinics",
      title: "Top active network clinics by exam volume",
      subtitle: "Chart pack 3: LabCorp Solutions, Swedish Specialist Hospital, British Medical Centre, and Concentra dominate completed volume.",
      type: "bar",
      xKey: "clinic",
      data: [
        { clinic: "LabCorp Solutions", completed: 3045 },
        { clinic: "Swedish Specialist Hospital", completed: 1978 },
        { clinic: "British Medical Centre", completed: 1792 },
        { clinic: "Concentra", completed: 1732 },
        { clinic: "Occu-Med Internal", completed: 813 },
        { clinic: "Tracy Lee, MD", completed: 747 },
        { clinic: "Asian Medical Centre", completed: 699 },
        { clinic: "NAVAIR Patuxent Onsite", completed: 680 },
        { clinic: "Fort Liberty Onsite", completed: 659 },
        { clinic: "Fort Moore Onsite", completed: 572 },
        { clinic: "LabCorp at Walgreens", completed: 504 },
        { clinic: "Kwajalein Hospital", completed: 463 },
        { clinic: "Mission Critical Psych", completed: 446 },
        { clinic: "GMC Clinics Dubai", completed: 383 },
        { clinic: "American Family Care", completed: 251 },
        { clinic: "Atrion partial", completed: 180 },
        { clinic: "MIOT Intl / ISOS India", completed: 172 },
        { clinic: "Lancet Labs Kenya", completed: 167 },
        { clinic: "Caduceus Occ Med", completed: 162 },
        { clinic: "Unknown / Blank", completed: 160 },
      ],
      series: [{ dataKey: "completed", name: "Completed exams", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "active clinics",
      fullWidth: true,
    },
    {
      id: "network-oconus-personal-physician-gaps",
      title: "OCONUS network gaps: personal physician used",
      subtitle: "Chart pack 3: Australia and Kenya are the top gaps where a personal physician was used.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Australia", examsNoClinic: 24 },
        { country: "Kenya", examsNoClinic: 14 },
        { country: "Iraq", examsNoClinic: 8 },
        { country: "Japan", examsNoClinic: 8 },
        { country: "Marshall Islands", examsNoClinic: 7 },
        { country: "Colombia", examsNoClinic: 6 },
        { country: "Qatar", examsNoClinic: 5 },
        { country: "Dominican Republic", examsNoClinic: 4 },
        { country: "Djibouti", examsNoClinic: 4 },
        { country: "Germany", examsNoClinic: 4 },
        { country: "Malaysia", examsNoClinic: 4 },
        { country: "Mexico", examsNoClinic: 4 },
        { country: "Thailand", examsNoClinic: 3 },
        { country: "Somalia", examsNoClinic: 3 },
        { country: "South Korea", examsNoClinic: 3 },
      ],
      series: [{ dataKey: "examsNoClinic", name: "Exams with no network clinic", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "OCONUS gaps",
      fullWidth: true,
    },
    {
      id: "network-no-show-rate-client",
      title: "No-show rate by client",
      subtitle: "Chart pack 3: minimum 100 events; red line portfolio average 4.5%.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "Trace Systems", noShowRate: 8.9 },
        { client: "International SOS", noShowRate: 8.3 },
        { client: "ASRC Federal", noShowRate: 7.5 },
        { client: "ManTech", noShowRate: 7.2 },
        { client: "Platform Aerospace", noShowRate: 6.6 },
        { client: "IAP", noShowRate: 6.4 },
        { client: "IDS International", noShowRate: 5.9 },
        { client: "Valiant", noShowRate: 5.9 },
        { client: "Amentum", noShowRate: 5.4 },
        { client: "Versar", noShowRate: 4.9 },
        { client: "Leidos", noShowRate: 4.7 },
        { client: "Fluor", noShowRate: 4.5 },
        { client: "CACI", noShowRate: 4.2 },
        { client: "Sierra Nevada Corporation", noShowRate: 3.8 },
        { client: "V2X", noShowRate: 3.8 },
      ],
      series: [{ dataKey: "noShowRate", name: "No-show %", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 10],
      referenceLines: [{ y: 4.5, stroke: "#ef4444", strokeDasharray: "4 4", label: { value: "Portfolio avg 4.5%", fill: "#ef4444", fontSize: 11 } }],
      headline: "no-shows",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "network-client-location-rows", label: "Client location rows", value: 872, unit: "count", category: "workforce" },
    { id: "network-client-common-cities", label: "Common client locations", value: 111, unit: "count", category: "workforce" },
    { id: "network-prospect-locations", label: "Strategic prospect locations", value: 135, unit: "count", category: "workforce" },
    { id: "network-overlap-locations", label: "Prospect/client overlap locations", value: 160, unit: "count", category: "workforce" },
    { id: "network-clinic-visits", label: "Clinic visits", value: 16387, unit: "count", category: "workforce" },
    { id: "network-clinics-used", label: "Clinics used", value: 325, unit: "count", category: "workforce" },
    { id: "network-dubai-referrals", label: "Dubai referrals", value: 1003, unit: "count", category: "workforce" },
    { id: "network-dubai-coverage", label: "Dubai coverage", value: 18, unit: "score", category: "risk" },
    { id: "network-labcorp-volume", label: "LabCorp Solutions volume", value: 3045, unit: "count", category: "workforce" },
    { id: "network-trace-noshow", label: "Trace no-show rate", value: 8.9, unit: "percent", category: "risk" },
  ],
  riskMatrix: [
    { name: "Dubai / UAE provider gap", revenue: 819, risk: 10.0, workers: 1003 },
    { name: "Prospect dense CONUS hubs", revenue: 135, risk: 7.5, workers: 160 },
    { name: "Client common locations", revenue: 111, risk: 8.0, workers: 872 },
    { name: "Existing clinic network", revenue: 325, risk: 4.0, workers: 16387 },
    { name: "Marshall Islands gap", revenue: 79, risk: 8.0, workers: 415 },
  ],
  opportunityMatrix: [
    { name: "Dubai Provider Buildout", revenuePotential: 1003, implementationComplexity: 8, strategicValue: 10 },
    { name: "San Diego Prospect Hub", revenuePotential: 26, implementationComplexity: 5, strategicValue: 10 },
    { name: "Huntsville Prospect Hub", revenuePotential: 20, implementationComplexity: 5, strategicValue: 10 },
    { name: "DC/NoVA Corridor", revenuePotential: 50, implementationComplexity: 6, strategicValue: 9 },
    { name: "Doha/Abu Dhabi/Riyadh GCC Network", revenuePotential: 42, implementationComplexity: 8, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Build the network before the need",
      narrative:
        "The uploaded strategy note explains the actual purpose of the project: turn Occu-Med from a reactive referral handler into a proactive network-infrastructure operator. Instead of waiting for a client to need a clinic, identify overlapping client and prospect locations and build provider coverage before the referral arrives.",
      bullets: [
        "Traditional model: client calls, Occu-Med scrambles for provider, response slows, quality varies, revenue can be lost.",
        "Proactive model: map every location where multiple clients and prospects converge, build provider relationships there first, and enter each referral with coverage already available.",
        "The common-location file identifies 872 location rows across 49 clients and 111 locations with three or more clients sharing the same city.",
      ],
      metricIds: ["network-client-location-rows", "network-client-common-cities"],
    },
    {
      type: "locations",
      title: "Prospect overlap shows where sales and network buildout should meet",
      narrative:
        "The prospect report identifies 135 strategic prospect locations and 160 overlap locations. The densest hubs are not random; they are defense, aerospace, shipyard, cyber, and OCONUS operational clusters where one provider relationship can support multiple entities.",
      bullets: [
        "San Diego, Huntsville, Arlington, Washington DC, Chantilly, Doha, Abu Dhabi, Colorado Springs, Norfolk, and Riyadh are Tier 1 prospect-density hubs.",
        "These locations should be treated as provider-network and sales-priority cities, not just static addresses.",
        "Where existing clients and prospects co-locate, Occu-Med can use current referral demand to justify network expansion before prospect conversion.",
      ],
      metricIds: ["network-prospect-locations", "network-overlap-locations"],
    },
    {
      type: "medical-opportunities",
      title: "Clinic-visit data reveals coverage strength and gaps",
      narrative:
        "The clinic visit file captures the actual providers Occu-Med has used: 16,387 visits across 325 clinics in 40+ countries. Comparing this to referral demand creates a coverage scorecard that identifies strong countries and urgent gaps.",
      bullets: [
        "Kuwait, Iraq, Qatar, Jordan, Djibouti, and Kenya show strong or above-demand coverage in the uploaded OCONUS scorecard.",
        "UAE/Dubai is the critical gap: 1,003 defense referrals versus only 184 clinic visits, about 18% coverage.",
        "Marshall Islands is a secondary gap: 415 referrals versus 336 visits, about 81% coverage.",
        "The Dubai gap matters because the file identifies Dubai as a transit staging hub for Iraq theater workers.",
      ],
      metricIds: ["network-clinic-visits", "network-clinics-used", "network-dubai-coverage"],
    },
  ],
};
