import type { CompanyConfig } from "./types";

export const networkExpansionIntelligenceConfig: CompanyConfig = {
  companyId: "network-expansion-intelligence",
  displayName: "Network Expansion Intelligence",
  shortName: "Network Expansion",
  sector:
    "Portfolio location overlap, proactive provider-network buildout, prospect/client co-location, OCONUS coverage gaps, clinic utilization, and referral-demand infrastructure strategy",
  headquarters: "Occu-Med portfolio-level network strategy",
  employees: 0,
  employeesAsOf: "Uploaded location, prospect overlap, and clinic-visit strategy files",
  summary:
    "Network Expansion Intelligence converts Alex's core strategic idea into an entity profile: do not wait for an employer to send a referral and then scramble for a clinic. Map where clients, prospects, referral demand, and actual clinic utilization overlap, then build the provider network in advance. The uploaded files identify 872 client location rows across 49 clients, 111 common client locations with three or more clients, 135 strategic prospect locations, 160 prospect/client overlap locations, and 16,387 historic clinic visits across 325 clinics in 40+ countries. The most urgent operational gap highlighted is UAE/Dubai, where the OCONUS coverage scorecard shows 1,003 defense referrals against only 184 clinic visits — roughly 18% coverage — despite Dubai functioning as a transit staging hub for Iraq theater workers.",
  tags: [
    "Entity profile",
    "Network strategy",
    "Build before the need",
    "Provider network",
    "Location overlap",
    "Prospect overlap",
    "Clinic utilization",
    "OCONUS coverage",
    "Dubai gap",
    "Referral demand",
    "Infrastructure play",
  ],
  aliases: ["Network Strategy", "Common Locations", "Prospect Network Intelligence", "Clinic Visit Coverage", "Provider Network Expansion"],
  sourceFilters: {
    newsSources: {
      aliases: ["Occu-Med common locations", "Occu-Med clinic visits", "Occu-Med prospect overlap", "network expansion intelligence"],
    },
  },
  executiveSignals: [
    {
      label: "Client location rows",
      value: "872",
      note: "Uploaded common-location file cross-references 872 total location rows across 49 clients.",
    },
    {
      label: "Common client cities",
      value: "111",
      note: "Locations with three or more clients sharing the same city — the proactive provider-network priority list.",
    },
    {
      label: "Clinic visits",
      value: "16,387",
      note: "Uploaded clinic-visit file maps actual provider utilization across 325 clinics in 40+ countries.",
    },
    {
      label: "Dubai coverage",
      value: "18%",
      note: "The uploaded OCONUS scorecard identifies UAE/Dubai as the critical gap: 1,003 referrals vs 184 clinic visits.",
    },
  ],
  curveTitle: "Build-the-network-before-the-need curve",
  curveSubtitle:
    "Uploaded client/prospect/common-location and clinic-visit files normalized into a network-expansion intelligence profile. Values are internal strategic planning signals and should be refreshed when location or visit data changes.",
  chartDefinitions: [
    {
      id: "network-data-layers",
      title: "Three-layer network intelligence model",
      subtitle: "Client/prospect locations show where demand could happen; clinic visits show where the existing provider network already works.",
      type: "bar",
      xKey: "layer",
      data: [
        { layer: "Client location rows", value: 872 },
        { layer: "Common client locations", value: 111 },
        { layer: "Strategic prospect locations", value: 135 },
        { layer: "Prospect/client overlaps", value: 160 },
        { layer: "Clinics used", value: 325 },
      ],
      series: [{ dataKey: "value", name: "Count", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "data layers",
      fullWidth: true,
    },
    {
      id: "oconus-coverage-scorecard",
      title: "OCONUS referral demand vs clinic-visit coverage",
      subtitle: "Clinic visits divided by defense referral demand; Dubai is the critical under-covered hub.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Kuwait", referrals: 1787, visits: 1765, coverage: 99 },
        { country: "Iraq", referrals: 1192, visits: 2000, coverage: 168 },
        { country: "UAE / Dubai", referrals: 1003, visits: 184, coverage: 18 },
        { country: "Qatar", referrals: 729, visits: 768, coverage: 105 },
        { country: "Marshall Islands", referrals: 415, visits: 336, coverage: 81 },
        { country: "Jordan", referrals: 261, visits: 269, coverage: 103 },
        { country: "Djibouti", referrals: 176, visits: 179, coverage: 102 },
        { country: "Kenya", referrals: 148, visits: 159, coverage: 107 },
      ],
      series: [{ dataKey: "coverage", name: "Coverage %", color: "#ef4444", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      headline: "OCONUS coverage",
      fullWidth: true,
    },
    {
      id: "oconus-demand-volume",
      title: "OCONUS defense referrals by country",
      subtitle: "Referral demand side of the coverage scorecard.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Kuwait", referrals: 1787 },
        { country: "Iraq", referrals: 1192 },
        { country: "UAE / Dubai", referrals: 1003 },
        { country: "Qatar", referrals: 729 },
        { country: "Marshall Islands", referrals: 415 },
        { country: "Jordan", referrals: 261 },
        { country: "Djibouti", referrals: 176 },
        { country: "Kenya", referrals: 148 },
      ],
      series: [{ dataKey: "referrals", name: "Defense referrals", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "demand volume",
    },
    {
      id: "prospect-critical-locations",
      title: "Tier 1 prospect-dense locations",
      subtitle: "Uploaded prospect network report: cities with 10+ prospect companies maintaining facilities.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "San Diego CA", prospects: 26 },
        { location: "Huntsville AL", prospects: 20 },
        { location: "Arlington VA", prospects: 19 },
        { location: "Washington DC", prospects: 16 },
        { location: "Chantilly VA", prospects: 15 },
        { location: "Doha Qatar", prospects: 15 },
        { location: "Abu Dhabi UAE", prospects: 14 },
        { location: "Colorado Springs CO", prospects: 14 },
        { location: "Norfolk VA", prospects: 14 },
        { location: "Riyadh Saudi Arabia", prospects: 13 },
      ],
      series: [{ dataKey: "prospects", name: "Prospect count", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      headline: "prospect density",
      fullWidth: true,
    },
    {
      id: "network-action-priority",
      title: "Network expansion action priority",
      subtitle: "Priority combines demand volume, provider coverage, prospect/client overlap, and strategic value.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Dubai / UAE", priority: 10 },
        { location: "San Diego CA", priority: 10 },
        { location: "Huntsville AL", priority: 10 },
        { location: "Arlington / DC / Chantilly", priority: 9 },
        { location: "Doha Qatar", priority: 9 },
        { location: "Abu Dhabi UAE", priority: 9 },
        { location: "Riyadh Saudi Arabia", priority: 8 },
        { location: "Marshall Islands", priority: 8 },
        { location: "Norfolk VA", priority: 8 },
        { location: "Colorado Springs CO", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "build priority",
    },
  ],
  metricDefinitions: [
    { id: "network-client-location-rows", label: "Client location rows", value: 872, unit: "count", category: "workforce" },
    { id: "network-client-common-cities", label: "Common client locations", value: 111, unit: "count", category: "workforce" },
    { id: "network-prospect-locations", label: "Strategic prospect locations", value: 135, unit: "count", category: "workforce" },
    { id: "network-overlap-locations", label: "Prospect/client overlap locations", value: 160, unit: "count", category: "workforce" },
    { id: "network-clinic-visits", label: "Clinic visits", value: 16387, unit: "count", category: "workforce" },
    { id: "network-clinics-used", label: "Clinics used", value: 325, unit: "count", category: "workforce" },
    { id: "network-dubai-referrals", label: "Dubai referrals", value: 1003, unit: "count", category: "workforce" },
    { id: "network-dubai-coverage", label: "Dubai coverage", value: 18, unit: "score", category: "risk" },
  ],
  riskMatrix: [
    { name: "Dubai / UAE provider gap", revenue: 819, risk: 10.0, workers: 1003 },
    { name: "Prospect dense CONUS hubs", revenue: 135, risk: 7.5, workers: 160 },
    { name: "Client common locations", revenue: 111, risk: 8.0, workers: 872 },
    { name: "Existing clinic network", revenue: 325, risk: 4.0, workers: 16387 },
    { name: "Marshall Islands gap", revenue: 79, risk: 8.0, workers: 415 },
  ],
  opportunityMatrix: [
    { name: "Dubai Provider Buildout", revenuePotential: 1003, implementationComplexity: 8, strategicValue: 10 },
    { name: "San Diego Prospect Hub", revenuePotential: 26, implementationComplexity: 5, strategicValue: 10 },
    { name: "Huntsville Prospect Hub", revenuePotential: 20, implementationComplexity: 5, strategicValue: 10 },
    { name: "DC/NoVA Corridor", revenuePotential: 50, implementationComplexity: 6, strategicValue: 9 },
    { name: "Doha/Abu Dhabi/Riyadh GCC Network", revenuePotential: 42, implementationComplexity: 8, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Build the network before the need",
      narrative:
        "The uploaded strategy note explains the actual purpose of the project: turn Occu-Med from a reactive referral handler into a proactive network-infrastructure operator. Instead of waiting for a client to need a clinic, identify overlapping client and prospect locations and build provider coverage before the referral arrives.",
      bullets: [
        "Traditional model: client calls, Occu-Med scrambles for provider, response slows, quality varies, revenue can be lost.",
        "Proactive model: map every location where multiple clients and prospects converge, build provider relationships there first, and enter each referral with coverage already available.",
        "The common-location file identifies 872 location rows across 49 clients and 111 locations with three or more clients sharing the same city.",
      ],
      metricIds: ["network-client-location-rows", "network-client-common-cities"],
    },
    {
      type: "locations",
      title: "Prospect overlap shows where sales and network buildout should meet",
      narrative:
        "The prospect report identifies 135 strategic prospect locations and 160 overlap locations. The densest hubs are not random; they are defense, aerospace, shipyard, cyber, and OCONUS operational clusters where one provider relationship can support multiple entities.",
      bullets: [
        "San Diego, Huntsville, Arlington, Washington DC, Chantilly, Doha, Abu Dhabi, Colorado Springs, Norfolk, and Riyadh are Tier 1 prospect-density hubs.",
        "These locations should be treated as provider-network and sales-priority cities, not just static addresses.",
        "Where existing clients and prospects co-locate, Occu-Med can use current referral demand to justify network expansion before prospect conversion.",
      ],
      metricIds: ["network-prospect-locations", "network-overlap-locations"],
    },
    {
      type: "medical-opportunities",
      title: "Clinic-visit data reveals coverage strength and gaps",
      narrative:
        "The clinic visit file captures the actual providers Occu-Med has used: 16,387 visits across 325 clinics in 40+ countries. Comparing this to referral demand creates a coverage scorecard that identifies strong countries and urgent gaps.",
      bullets: [
        "Kuwait, Iraq, Qatar, Jordan, Djibouti, and Kenya show strong or above-demand coverage in the uploaded OCONUS scorecard.",
        "UAE/Dubai is the critical gap: 1,003 defense referrals versus only 184 clinic visits, about 18% coverage.",
        "Marshall Islands is a secondary gap: 415 referrals versus 336 visits, about 81% coverage.",
        "The Dubai gap matters because the file identifies Dubai as a transit staging hub for Iraq theater workers.",
      ],
      metricIds: ["network-clinic-visits", "network-clinics-used", "network-dubai-coverage"],
    },
  ],
};
