import type { CompanyConfig } from "./types";

export const northropGrummanConfig: CompanyConfig = {
  companyId: "northrop-grumman",
  displayName: "Northrop Grumman Corporation",
  shortName: "Northrop Grumman",
  sector:
    "Defense and aerospace manufacturing, B-21 Raider production, solid rocket motors, missile systems, space systems, mission systems, C4ISR, ordnance manufacturing, composite manufacturing, and OCONUS defense support",
  headquarters: "Falls Church, Virginia",
  employees: 100000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 20, 2026",
  summary:
    "Northrop Grumman Corporation is a public defense and aerospace manufacturing entity with nearly 100,000 employees and four major business segments: Aeronautics Systems, Defense Systems, Mission Systems, and Space Systems. The uploaded Occu-Med intelligence report frames Northrop Grumman as fundamentally different from the services-heavy entities in the portfolio: it manufactures aircraft, solid rocket motors, ICBM components, satellites, radar systems, electronic warfare systems, and ordnance, creating high-volume occupational medicine demand and rare tail-risk surveillance needs.",
  tags: [
    "Entity profile",
    "Defense manufacturing",
    "Aerospace manufacturing",
    "B-21 Raider",
    "Solid rocket motors",
    "GBSD Sentinel",
    "Ammonium perchlorate",
    "Confined space",
    "Composite manufacturing",
    "Hearing conservation",
    "Respirator clearance",
    "DBA exposure",
  ],
  aliases: ["Northrop Grumman", "Northrop Grumman Corporation", "NOC", "NG"],
  sourceFilters: {
    sec: { ticker: "NOC", legalEntities: ["Northrop Grumman Corporation"] },
    sam: { legalNames: ["Northrop Grumman Corporation", "Northrop Grumman Systems Corporation"] },
    usaSpending: { recipientNames: ["Northrop Grumman", "Northrop Grumman Corporation", "Northrop Grumman Systems"] },
    jobSources: { linkedin: "northrop-grumman-corporation", careerSite: "https://www.northropgrumman.com/careers" },
    newsSources: {
      aliases: ["Northrop Grumman", "NOC", "B-21 Raider", "Sentinel ICBM", "Promontory explosion", "Bacchus Works"],
    },
  },
  executiveSignals: [
    {
      label: "Reported injuries",
      value: "840/yr",
      note: "Reported/company TRIR 0.84 applied to roughly 100,000 employees.",
    },
    {
      label: "Economic burden",
      value: "$198.7M/yr",
      note: "Direct annual injury cost of $36.1M multiplied by OSHA indirect cost factor.",
    },
    {
      label: "DBA exposure",
      value: "$9.5M/yr",
      note: "Modeled from 31.5 OCONUS injuries at $300K average DBA claim exposure.",
    },
    {
      label: "Occu-Med potential",
      value: "$9.55M–$22.3M/yr",
      note: "Largest modeled opportunity in the uploaded portfolio, driven by 100,000 employees, high manufacturing volume, and specialty surveillance needs.",
    },
  ],
  curveTitle: "Northrop Grumman defense manufacturing and tail-risk medical surveillance curve",
  curveSubtitle:
    "Uploaded Occu-Med intelligence values normalized for entity-profile scanning; modeled estimates should be treated as assumption-driven signals, not audited employer disclosures.",
  chartDefinitions: [
    {
      id: "northrop-five-numbers",
      title: "Northrop Grumman five exposure numbers that matter",
      subtitle: "Source: uploaded Northrop Grumman Occu-Med intelligence report; modeled injury, cost, DBA, and fatality expected-value metrics.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Direct injury cost", value: 36.1 },
        { metric: "Economic burden", value: 198.7 },
        { metric: "DBA claim exposure", value: 9.5 },
        { metric: "Fatality EV", value: 0.297 },
      ],
      series: [{ dataKey: "value", name: "Annual exposure", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "exposure model",
      fullWidth: true,
    },
    {
      id: "northrop-trir-trend",
      title: "Northrop Grumman TRIR trend 2020-2024",
      subtitle: "Uploaded report: TRIR improved from 1.35 in 2020 to 0.84 in 2024, below the OSHA world-class benchmark of 1.0.",
      type: "line",
      xKey: "year",
      data: [
        { year: "2020", trir: 1.35 },
        { year: "2021", trir: 1.08 },
        { year: "2022", trir: 0.96 },
        { year: "2023", trir: 0.90 },
        { year: "2024", trir: 0.84 },
      ],
      series: [{ dataKey: "trir", name: "Northrop Grumman TRIR", color: "#22c55e" }],
      referenceLines: [
        { y: 1.0, stroke: "#94a3b8", strokeDasharray: "4 4", label: { value: "OSHA world-class 1.0", fill: "#94a3b8", fontSize: 11 } },
        { y: 1.6, stroke: "#ef4444", strokeDasharray: "4 4", label: { value: "BLS avg", fill: "#ef4444", fontSize: 11 } },
      ],
      domain: [0, 1.6],
      headline: "TRIR progress",
      fullWidth: true,
    },
    {
      id: "northrop-trir-roi",
      title: "TRIR improvement to annual burden savings",
      subtitle: "Uploaded report: achieved 2020-2024 improvement removed 510 injuries/year; next 0.10 TRIR reduction is worth $23.7M/year.",
      type: "bar",
      xKey: "scenario",
      data: [
        { scenario: "Achieved 2020-2024", savings: 120.5 },
        { scenario: "Next 0.10 reduction", savings: 23.7 },
        { scenario: "Next 0.05 reduction", savings: 11.8 },
      ],
      series: [{ dataKey: "savings", name: "Annual burden savings", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "ROI story",
    },
    {
      id: "northrop-segment-risk-gap",
      title: "BLS benchmark expected vs pro-rata reported injuries by segment",
      subtitle: "Defense Systems and Aeronautics Systems show the largest gap between BLS manufacturing benchmarks and blended company TRIR allocation.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "Aeronautics", expected: 396, reported: 185 },
        { segment: "Defense Systems", expected: 525, reported: 126 },
        { segment: "Mission Systems", expected: 200, reported: 210 },
        { segment: "Space Systems", expected: 270, reported: 151 },
        { segment: "Engineering/PM", expected: 84, reported: 118 },
        { segment: "Corporate/Admin", expected: 24, reported: 50 },
      ],
      series: [
        { dataKey: "expected", name: "BLS expected", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "reported", name: "Pro-rata reported", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "segment gap",
      fullWidth: true,
    },
    {
      id: "northrop-segment-gap-only",
      title: "Segment injury gap hidden by blended TRIR",
      subtitle: "The uploaded report identifies Defense Systems as the largest concern: +399 injuries/year gap versus pro-rata reported allocation.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "Defense Systems", gap: 399 },
        { segment: "Aeronautics", gap: 211 },
        { segment: "Space Systems", gap: 119 },
        { segment: "Mission Systems", gap: -10 },
        { segment: "Engineering/PM", gap: -34 },
        { segment: "Corporate/Admin", gap: -26 },
      ],
      series: [{ dataKey: "gap", name: "Expected vs pro-rata gap", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "hidden risk",
    },
    {
      id: "northrop-regulatory-priority",
      title: "Regulatory and medical surveillance priority map",
      subtitle: "Specialty programs implied by ammonium perchlorate, confined-space, composite, noise, OCONUS, and new-hire exposure lanes.",
      type: "bar",
      xKey: "population",
      data: [
        { population: "SRM/AP thyroid", priority: 10 },
        { population: "Confined space", priority: 10 },
        { population: "B-21 composites", priority: 9 },
        { population: "Manufacturing noise", priority: 8 },
        { population: "OCONUS support", priority: 8 },
        { population: "New hires", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Priority score", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "surveillance priorities",
    },
    {
      id: "northrop-revenue-potential",
      title: "Northrop Grumman Occu-Med annual revenue potential",
      subtitle: "Uploaded report: full-program opportunity range of $9.55M-$22.3M/year, the largest modeled account in the portfolio.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Pre-employment", low: 2100, high: 4500 },
        { examType: "Hearing", low: 3000, high: 5000 },
        { examType: "Respirator", low: 1500, high: 2250 },
        { examType: "Chemical surveillance", low: 300, high: 1500 },
        { examType: "Confined space", low: 100, high: 525 },
        { examType: "DBA pre-deploy", low: 1050, high: 2500 },
        { examType: "MSK baseline", low: 1500, high: 6000 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "northrop-employees", label: "Employees", value: 100000, unit: "count", category: "workforce" },
    { id: "northrop-revenue", label: "FY2024 revenue", value: 43.7, unit: "usd", category: "financial" },
    { id: "northrop-reported-injuries", label: "Reported injuries/yr", value: 840, unit: "count", category: "safety" },
    { id: "northrop-trir-2024", label: "2024 TRIR", value: 0.84, unit: "score", category: "safety" },
    { id: "northrop-direct-cost", label: "Direct annual injury cost", value: 36.1, unit: "usd", category: "financial" },
    { id: "northrop-economic-burden", label: "Total economic burden", value: 198.7, unit: "usd", category: "financial" },
    { id: "northrop-dba-exposure", label: "Annual DBA claim exposure", value: 9.5, unit: "usd", category: "risk" },
    { id: "northrop-occumed-revenue-high", label: "Occu-Med revenue potential high", value: 22.3, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Defense Systems / SRM", revenue: 8.6, risk: 10.0, workers: 15000 },
    { name: "Aeronautics / B-21", revenue: 12.0, risk: 8.5, workers: 22000 },
    { name: "Space Systems", revenue: 11.7, risk: 7.5, workers: 18000 },
    { name: "Mission Systems", revenue: 11.4, risk: 5.0, workers: 25000 },
    { name: "Engineering / PM", revenue: 4.0, risk: 3.0, workers: 14000 },
    { name: "Corporate / Admin", revenue: 1.5, risk: 2.0, workers: 6000 },
  ],
  opportunityMatrix: [
    { name: "MSK Baseline", revenuePotential: 6000, implementationComplexity: 8, strategicValue: 10 },
    { name: "Hearing Conservation", revenuePotential: 5000, implementationComplexity: 5, strategicValue: 9 },
    { name: "Pre-Employment Physicals", revenuePotential: 4500, implementationComplexity: 6, strategicValue: 9 },
    { name: "DBA Pre-Deployment", revenuePotential: 2500, implementationComplexity: 7, strategicValue: 8 },
    { name: "Respirator Clearances", revenuePotential: 2250, implementationComplexity: 5, strategicValue: 8 },
    { name: "Chemical Surveillance", revenuePotential: 1500, implementationComplexity: 9, strategicValue: 10 },
    { name: "Confined Space Medical", revenuePotential: 525, implementationComplexity: 8, strategicValue: 10 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Northrop Grumman is the first profile in this batch where manufacturing is the dominant occupational medicine fact. The uploaded report says Northrop builds B-21 Raiders, solid rocket motors, Sentinel ICBM components, satellites, radar systems, and other advanced defense systems, so its injury profile reflects physical manufacturing realities rather than IT-services exposure.",
      bullets: [
        "$43.7B FY2024 public defense and aerospace manufacturing company.",
        "Nearly 100,000 employees across Aeronautics Systems, Defense Systems, Mission Systems, and Space Systems.",
        "The company reports TRIR and has shown real safety progress from 1.35 in 2020 to 0.84 in 2024.",
        "At Northrop's scale, 0.84 TRIR still equals roughly 840 recordable injuries per year and $198.7M in modeled annual economic burden.",
      ],
      metricIds: ["northrop-employees", "northrop-revenue", "northrop-trir-2024", "northrop-economic-burden"],
    },
    {
      type: "safety",
      title: "TRIR progress and remaining ROI",
      narrative:
        "The report emphasizes that Northrop's TRIR progress is real and should be acknowledged. The sales frame is not that the safety program is broken; it is that the next marginal reduction is still extremely valuable because the denominator is 100,000 employees.",
      bullets: [
        "TRIR dropped from 1.35 in 2020 to 0.84 in 2024, a 38% reduction.",
        "The achieved improvement removed an estimated 510 injuries per year and $120.5M in annual economic burden.",
        "The next 0.10 TRIR reduction, from 0.84 to 0.74, is modeled as 100 fewer injuries and $23.7M in annual burden savings.",
        "The next 0.05 TRIR reduction is modeled as $11.8M in annual burden savings.",
      ],
      metricIds: ["northrop-trir-2024", "northrop-reported-injuries"],
    },
    {
      type: "workforce",
      title: "Segment risk: Defense Systems is the problem",
      narrative:
        "The uploaded segment model says Defense Systems has the largest hidden-risk gap. Ordnance manufacturing, solid rocket motor work, GBSD/Sentinel work, and hypersonic weapon systems carry BLS benchmark risk much higher than the blended company-wide TRIR implies.",
      bullets: [
        "Defense Systems: 15,000 headcount, BLS TRIR benchmark 3.50, 525 expected injuries/year, 126 pro-rata reported injuries, +399 gap.",
        "Aeronautics Systems: 22,000 headcount, BLS benchmark 1.80, 396 expected injuries/year, +211 gap.",
        "Space Systems: 18,000 headcount, BLS benchmark 1.50, 270 expected injuries/year, +119 gap.",
        "Mission Systems, engineering/PM, and corporate/admin appear closer to or below pro-rata reported allocation.",
      ],
      metricIds: [],
    },
    {
      type: "safety",
      title: "Tail-risk incidents: Promontory and Bacchus Works",
      narrative:
        "Two documented Utah incidents define the catastrophic tail risk that blended TRIR does not capture: a Promontory ammonium perchlorate building explosion and Bacchus Works argon-asphyxiation fatalities tied to Sentinel ICBM supply-chain work.",
      bullets: [
        "In April 2025, an explosion destroyed a building at Northrop's Promontory, Utah facility used to produce ammonium perchlorate oxidizer.",
        "In 2024, two workers were asphyxiated by leaking argon gas in a basement area of Bacchus Works in Magna, Utah.",
        "The report frames Bacchus as an OSHA 1910.146 confined-space program failure with two worker fatalities.",
        "TRIR describes median injury experience; it does not describe catastrophic event probability in high-energy propellant and inert-gas environments.",
      ],
      metricIds: [],
    },
    {
      type: "workforce",
      title: "Ammonium perchlorate and solid rocket motor worker profile",
      narrative:
        "The uploaded report identifies ammonium perchlorate exposure in solid rocket motor production as a specialty occupational medicine lane requiring industrial toxicology expertise, not commodity clinic screening.",
      bullets: [
        "Ammonium perchlorate is described as a thyroid disruptor that inhibits iodine uptake and can suppress thyroid function at chronic low-level exposure.",
        "The report recommends pre-employment and annual TSH, free T4, and T3 surveillance for AP/SRM workers.",
        "AP mixed with aluminum fuel powder creates deflagration/detonation conditions under mechanical shock or heat.",
        "Confined-space medical evaluation and SCBA fitness are required around argon/inert-gas displacement hazards.",
      ],
      metricIds: [],
    },
    {
      type: "safety",
      title: "B-21 Raider composite manufacturing respiratory risk",
      narrative:
        "B-21 Raider production at Palmdale introduces composite-manufacturing respiratory hazards: carbon fiber dust, epoxy resin sensitizers, and classified radar-absorbing coatings. The report frames baseline spirometry as essential because sensitization and occupational asthma may emerge after years of exposure.",
      bullets: [
        "Carbon fiber dust is treated as a respirable pulmonary hazard requiring baseline spirometry.",
        "Epoxy resin systems are respiratory sensitizers that can cause occupational asthma after chronic low-level exposure.",
        "Radar-absorbing materials may involve carbon-loaded polymers and specialty coatings with inhalation risk during application and grinding.",
        "Baseline PFT and respirator medical clearance are the key documentation tools for composite manufacturing workers.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded model estimates $9.55M-$22.3M in annual Occu-Med revenue potential, making Northrop the largest account in the portfolio. The account is large because of scale, turnover, manufacturing headcount, hearing conservation volume, respirator clearance needs, DBA deployment support, and MSK baseline demand.",
      bullets: [
        "Pre-employment physicals: 12,000-15,000 volume; modeled $2.1M-$4.5M per year.",
        "Hearing conservation: 40,000 manufacturing workers; modeled $3.0M-$5.0M per year.",
        "Respirator clearances: 15,000 chemical/composite workers; modeled $1.5M-$2.25M per year.",
        "Chemical surveillance: 2,000-5,000 AP/SRM workers; modeled $300K-$1.5M per year.",
        "MSK baseline: 20,000-40,000 aircraft/missile manufacturing workers; modeled $1.5M-$6.0M per year.",
      ],
      metricIds: ["northrop-occumed-revenue-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "Northrop Grumman values in this profile are source-backed but model-driven. The charts should be interpreted as Occu-Med intelligence estimates derived from the uploaded Northrop report, public ESG/SEC data, BLS benchmarks, NSC/OSHA cost assumptions, DBA assumptions, and specialized industrial toxicology analysis.",
      bullets: [
        "Do not present modeled segment risk gaps, DBA exposure, fatality expected value, or revenue projections as audited Northrop disclosures.",
        "Acknowledge Northrop's real TRIR progress before presenting remaining opportunity.",
        "Treat AP thyroid surveillance, confined-space medical evaluation, and composite respiratory baseline protocols as high-value specialty recommendations requiring clinical/industrial hygiene review.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "deep-analysis",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
