import type { CompanyConfig } from "./types";

export const paeAmentumConfig: CompanyConfig = {
  companyId: "pae-amentum",
  displayName: "Amentum Holdings / PAE Legacy",
  shortName: "Amentum / PAE",
  sector:
    "Government services, logistics, base operations, engineering, program management, DOE/nuclear support, NASA support, OCONUS support, legacy PAE programs, aviation and airfield support, biometric processing, Jacobs CMS / Cyber & Intelligence, and DOE 10 CFR 851 medical surveillance",
  headquarters: "Chantilly, Virginia",
  employees: 50000,
  employeesAsOf:
    "Uploaded Amentum Holdings, PAE trend, city-by-city hiring, and addendum files: approximately 50,000 employees in 70+ countries, $14.4B FY2025 revenue, and two reportable segments after the Jacobs CMS / Cyber & Intelligence merger",
  summary:
    "Amentum Holdings / PAE Legacy now combines four layers: the current publicly traded Amentum Holdings parent, the PAE legacy risk tail, the city-by-city global hiring footprint, and the new addendum's regulatory/exam-population logic. Amentum Holdings, Inc. was formed September 27, 2024 from legacy Amentum and Jacobs Critical Mission Solutions / Cyber & Intelligence. It operates through Digital Solutions and Global Engineering Solutions, with approximately 50,000 employees in 70+ countries and about $14.4B FY2025 revenue. The newest addendum is the action layer for Occu-Med: Amentum has four distinct exam populations — DOE/environmental remediation, aviation/airfield operations, engineering/technical services, and logistics/base operations — and the DOE/nuclear lane requires DOE 10 CFR 851 occupational medicine fluency, not generic pre-employment physicals. PAE no longer exists as an independent company, but its legacy work adds USCIS/CBP biometric processing, Army CFT aviation maintenance, diplomatic/security support, Africa logistics, and OCONUS DBA tail exposure. Occu-Med's message should be: Amentum has built an exceptional safety and EMR advantage, and Occu-Med's value is protecting that advantage with DOE surveillance, NAICS-specific benchmarking, return-to-work documentation, and onboarding support for the new Jacobs CMS workforce.",
  tags: [
    "Entity profile",
    "Amentum Holdings",
    "AMTM",
    "PAE legacy programs",
    "Jacobs CMS",
    "Digital Solutions",
    "Global Engineering Solutions",
    "DOE 10 CFR 851",
    "Hanford",
    "Y-12",
    "Pantex",
    "Savannah River Site",
    "Aviation airfield support",
    "City-by-city hiring",
    "OCONUS workforce",
    "USCIS biometric processing",
    "Claims reserves",
  ],
  aliases: ["Amentum", "Amentum Holdings", "Amentum Holdings Inc.", "PAE", "PAE Incorporated", "PAE Applied Technologies", "PAE Government Services", "Jacobs CMS"],
  sourceFilters: {
    sec: { ticker: "AMTM", legalEntities: ["Amentum Holdings, Inc."] },
    sam: { legalNames: ["Amentum Holdings", "Amentum Services", "PAE Incorporated", "PAE Applied Technologies", "PAE Government Services"] },
    usaSpending: { recipientNames: ["Amentum", "PAE"], parentOrgs: ["Amentum Holdings"] },
    jobSources: { linkedin: "amentum", careerSite: "https://www.amentum.com/careers/" },
    newsSources: { aliases: ["Amentum", "Amentum Holdings", "Amentum SafeUp", "Amentum NSC safety awards", "PAE Incorporated", "Jacobs CMS", "Amentum DOE 10 CFR 851"] },
  },
  executiveSignals: [
    { label: "FY2025 revenue", value: "$14.4B", note: "Uploaded Amentum Holdings file identifies $14.4B annual revenue for FY2025." },
    { label: "DOE mandate", value: "10 CFR 851", note: "DOE covered-workplace medical surveillance is a specialized exam mandate most general occ med providers miss." },
    { label: "Jacobs CMS impact", value: "+~7K workers", note: "The merger added intelligence, cyber, energy/nuclear, and digital-engineering personnel into the Amentum exam population." },
    { label: "KSC hiring hub", value: "122 postings", note: "City-by-city hiring file identifies Merritt Island / Kennedy Space Center as the largest visible U.S. hiring hub." },
  ],
  curveTitle: "Amentum Holdings safety trend, DOE surveillance, PAE legacy, and global hiring footprint curve",
  curveSubtitle:
    "Uploaded Amentum Holdings file, addendum, trend analysis, PAE addendum, and city-by-city hiring analysis normalized into one entity profile. Treat values as strategic intelligence and refresh against current Amentum program data before operational use.",
  chartDefinitions: [
    {
      id: "amentum-exam-populations",
      title: "Amentum exam populations by regulatory / work lane",
      subtitle: "The addendum separates Amentum into four medical populations rather than one generic account.",
      type: "bar",
      xKey: "population",
      data: [
        { population: "DOE / environmental", priority: 10 },
        { population: "Aviation / airfield", priority: 9 },
        { population: "Engineering / technical", priority: 7 },
        { population: "Logistics / BOS", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "exam lanes",
      fullWidth: true,
    },
    {
      id: "amentum-doe-sites",
      title: "DOE / nuclear surveillance sites named in addendum",
      subtitle: "DOE 10 CFR 851 medical surveillance is the highest-specificity account wedge.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "Hanford HITDC", priority: 10 },
        { site: "Y-12 Oak Ridge", priority: 10 },
        { site: "Pantex Amarillo", priority: 10 },
        { site: "Savannah River Site", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Surveillance priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "DOE sites",
    },
    {
      id: "amentum-naics-benchmarks",
      title: "Amentum NAICS benchmark translation",
      subtitle: "Different Amentum populations map to materially different BLS TRIR benchmarks.",
      type: "bar",
      xKey: "businessLine",
      data: [
        { businessLine: "Airfield / aviation", benchmark: 4.1 },
        { businessLine: "Environmental remediation", benchmark: 2.4 },
        { businessLine: "Logistics / facilities", benchmark: 2.5 },
        { businessLine: "Engineering services", benchmark: 1.25 },
      ],
      series: [{ dataKey: "benchmark", name: "BLS TRIR benchmark", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 5],
      headline: "benchmarks",
    },
    {
      id: "amentum-injury-rate-trend",
      title: "Amentum injury rates declining FY2022-FY2024",
      subtitle: "Uploaded trend analysis: TRIR and LWCR declined materially against much higher composite industry averages.",
      type: "line",
      xKey: "year",
      data: [
        { year: "FY2022 est.", trir: 0.82, lwcr: 0.15, industryTrir: 2.77, industryLwcr: 1.63 },
        { year: "FY2023", trir: 0.64, lwcr: 0.11, industryTrir: 2.77, industryLwcr: 1.63 },
        { year: "FY2024", trir: 0.47, lwcr: 0.09, industryTrir: 2.77, industryLwcr: 1.63 },
      ],
      series: [
        { dataKey: "trir", name: "Amentum TRIR", color: "#ef4444" },
        { dataKey: "lwcr", name: "Amentum LWCR", color: "#22c55e" },
        { dataKey: "industryTrir", name: "Industry avg TRIR", color: "#94a3b8" },
        { dataKey: "industryLwcr", name: "Industry avg LWCR", color: "#a78bfa" },
      ],
      domain: [0, 3],
      headline: "injury trend",
      fullWidth: true,
    },
    {
      id: "amentum-jacobs-cms-impact",
      title: "Jacobs CMS merger impact on exam population",
      subtitle: "The merger added intelligence, cyber, energy/nuclear, and digital engineering workers into the medical-support universe.",
      type: "bar",
      xKey: "impact",
      data: [
        { impact: "Added workers", value: 7000 },
        { impact: "Combined backlog $B", value: 47 },
        { impact: "FY2025 revenue $B", value: 14.4 },
        { impact: "Rapid Solutions divestiture $M", value: 360 },
      ],
      series: [{ dataKey: "value", name: "Value", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "merger impact",
      fullWidth: true,
    },
    {
      id: "pae-us-hiring-hubs",
      title: "Amentum / PAE U.S. active hiring hubs",
      subtitle: "City-by-city hiring analysis: NASA, DoD, DOE, and naval-systems locations drive current visibility.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Kennedy Space Center FL", postings: 122 },
        { location: "Washington DC", postings: 81 },
        { location: "Houston TX", postings: 69 },
        { location: "Dahlgren VA", postings: 45 },
        { location: "Las Vegas/Creech NV", postings: 21 },
        { location: "Huntsville AL", postings: 19 },
        { location: "Tullahoma TN", postings: 16 },
        { location: "Oak Ridge TN", postings: 12 },
        { location: "Englewood CO", postings: 11 },
        { location: "Chantilly VA", postings: 9 },
      ],
      series: [{ dataKey: "postings", name: "Current postings", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "U.S. hiring",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "amentum-employees", label: "Amentum employees", value: 50000, unit: "count", category: "workforce" },
    { id: "amentum-fy25-revenue", label: "FY2025 revenue", value: 14.4, unit: "usd", category: "financial" },
    { id: "amentum-backlog", label: "Combined backlog", value: 47, unit: "usd", category: "financial" },
    { id: "amentum-jacobs-workers", label: "Jacobs CMS employees added", value: 7000, unit: "count", category: "workforce" },
    { id: "amentum-emr", label: "EMR advantage", value: 0.46, unit: "score", category: "safety" },
    { id: "amentum-doe-sites", label: "DOE/nuclear priority sites", value: 4, unit: "count", category: "risk" },
    { id: "amentum-fy24-trir", label: "FY2024 TRIR", value: 0.47, unit: "score", category: "safety" },
    { id: "amentum-fy24-lwcr", label: "FY2024 LWCR", value: 0.09, unit: "score", category: "safety" },
    { id: "pae-ksc-postings", label: "KSC postings", value: 122, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "DOE / nuclear surveillance", revenue: 10, risk: 10.0, workers: 4000 },
    { name: "Aviation / airfield", revenue: 9, risk: 8.5, workers: 2500 },
    { name: "Logistics / BOS", revenue: 9, risk: 8.5, workers: 8000 },
    { name: "Engineering / cyber / IC", revenue: 7, risk: 5.5, workers: 7000 },
    { name: "Antarctic NSF support", revenue: 43, risk: 8.5, workers: 500 },
    { name: "Iraq base operations", revenue: 59, risk: 9.5, workers: 1000 },
  ],
  opportunityMatrix: [
    { name: "DOE 10 CFR 851 Surveillance", revenuePotential: 900, implementationComplexity: 8, strategicValue: 10 },
    { name: "Aviation / Airfield Support Exams", revenuePotential: 350, implementationComplexity: 6, strategicValue: 9 },
    { name: "Jacobs CMS Onboarding Baselines", revenuePotential: 500, implementationComplexity: 7, strategicValue: 9 },
    { name: "RTW / Five-Day Absence Protocol", revenuePotential: 300, implementationComplexity: 5, strategicValue: 9 },
    { name: "NAICS Benchmark Account Defense", revenuePotential: 200, implementationComplexity: 4, strategicValue: 8 },
    { name: "PAE Legacy OCONUS Tail", revenuePotential: 170, implementationComplexity: 7, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Amentum report standard: numbers first",
      narrative:
        "This profile follows the Amentum-report standard: start with exam populations, TRIR/LWCR, EMR, reserves, regulatory obligations, and dollars. The company history only matters when it explains a medical action.",
      bullets: [
        "Amentum Holdings is now the publicly traded parent formed from legacy Amentum and Jacobs CMS / Cyber & Intelligence.",
        "Digital Solutions and Global Engineering Solutions create different medical risk lanes.",
        "PAE legacy still matters because it brought OCONUS, biometric, aviation, diplomatic/security, and DBA-tail populations into Amentum.",
      ],
      metricIds: ["amentum-employees", "amentum-fy25-revenue", "amentum-backlog"],
    },
    {
      type: "safety",
      title: "DOE 10 CFR 851 is the specialized wedge",
      narrative:
        "For DOE covered workplaces, the occupational medicine program is not a generic annual physical. It includes placement evaluations, hazard-based monitoring, fitness-for-duty, diagnostic exams, five-day absence notification, return-to-work monitoring, written restrictions, and principal morbidity prevention.",
      bullets: [
        "Hanford, Y-12, Pantex, and Savannah River Site are the key Amentum DOE/nuclear signals.",
        "DOE 10 CFR 851 creates higher-complexity, higher-value medical surveillance than standard pre-employment exams.",
        "Occu-Med should treat 10 CFR 851 fluency as an account-defense and expansion product.",
      ],
      metricIds: ["amentum-doe-sites", "amentum-emr"],
    },
    {
      type: "medical-opportunities",
      title: "The sales message",
      narrative:
        "The correct pitch is: Amentum has built an exceptional safety/EMR advantage. Occu-Med's value is protecting that advantage with higher-quality DOE surveillance, return-to-work documentation, NAICS-specific benchmarking, and onboarding support for new CMS/C&I populations.",
      bullets: [
        "Do not say Amentum is unsafe; say their performance is exceptional and must be protected.",
        "Use DOE 10 CFR 851, NAICS benchmarks, claims reserve improvement, and EMR as proof language.",
        "The new Jacobs CMS workers change the medical-support population and should be explicitly surfaced.",
      ],
      metricIds: ["amentum-jacobs-workers", "amentum-fy24-trir", "amentum-fy24-lwcr"],
    },
  ],
};
