import type { CompanyConfig } from "./types";

export const paeAmentumConfig: CompanyConfig = {
  companyId: "pae-amentum",
  displayName: "Amentum Holdings / PAE Legacy",
  shortName: "Amentum",
  sector:
    "Government services, environmental remediation, DOE and defense logistics, OCONUS support, legacy PAE programs, biometric processing, aviation maintenance, and safety-performance trend intelligence",
  headquarters: "Germantown, Maryland",
  employees: 53000,
  employeesAsOf: "Uploaded Amentum trend analysis: post-September 2024 Jacobs CMS merger",
  summary:
    "Amentum Holdings / PAE Legacy is an active Occu-Med-facing entity profile focused on public safety trend signals, pre-employment and annual exam leverage, legacy PAE program risk, and OCONUS support exposure. The uploaded Amentum trend analysis shows a sharp FY2022-FY2024 decline in TRIR and LWCR, expanding National Safety Council award counts, and a major decline in balance-sheet claim reserves. The profile treats those signals as consistent with a stronger prevention and occupational medicine system, while avoiding a direct causation claim because Amentum does not share internal Occu-Med exam outcome data.",
  tags: [
    "Entity profile",
    "Amentum",
    "PAE legacy programs",
    "Occu-Med account intelligence",
    "TRIR trend",
    "LWCR trend",
    "Claims reserves",
    "NSC safety awards",
    "Pre-employment screens",
    "Annual exams",
    "Return-to-work leverage",
    "OCONUS workforce",
  ],
  aliases: ["Amentum", "Amentum Holdings", "Amentum Holdings Inc.", "PAE", "PAE Incorporated", "Jacobs CMS"],
  sourceFilters: {
    sec: { ticker: "AMTM", legalEntities: ["Amentum Holdings, Inc."] },
    sam: { legalNames: ["Amentum Holdings", "Amentum Services", "PAE Incorporated"] },
    usaSpending: { recipientNames: ["Amentum", "PAE"], parentOrgs: ["Amentum Holdings"] },
    jobSources: { linkedin: "amentum", careerSite: "https://www.amentum.com/careers/" },
    newsSources: { aliases: ["Amentum", "Amentum Holdings", "Amentum SafeUp", "Amentum NSC safety awards"], acquisitionAliases: ["PAE Incorporated", "Jacobs CMS"] },
  },
  executiveSignals: [
    {
      label: "FY24 TRIR",
      value: "0.47",
      note: "Uploaded trend analysis shows TRIR falling from ~0.82 in FY2022 to 0.47 in FY2024, a 43% decline.",
    },
    {
      label: "FY24 LWCR",
      value: "0.09",
      note: "Lost Workday Case Rate fell from ~0.15 in FY2022 to 0.09 in FY2024, a 40% decline.",
    },
    {
      label: "Claims reserves",
      value: "$235M → $159M",
      note: "Uploaded analysis shows current + long-term reserves declining by $76M from Sep 2024 to Oct 2025.",
    },
    {
      label: "Occu-Med leverage",
      value: "Prevention signal",
      note: "Public trend data supports the value story for pre-employment, annual, surveillance, and return-to-work exams without proving standalone causation.",
    },
  ],
  curveTitle: "Amentum safety trend, claims reserve, and Occu-Med leverage curve",
  curveSubtitle:
    "Uploaded public-record trend analysis normalized for entity-profile scanning. Trend signals support Occu-Med value positioning but should not be presented as proof of direct causation without internal Amentum exam/outcome data.",
  chartDefinitions: [
    {
      id: "amentum-injury-rate-trend",
      title: "Amentum injury rates declining FY2022-FY2024",
      subtitle: "Uploaded trend analysis: TRIR declined 43% and LWCR declined 40% in two years, against much higher composite industry averages.",
      type: "line",
      xKey: "year",
      data: [
        { year: "FY2022 est.", trir: 0.82, lwcr: 0.15, industryTrir: 2.77, industryLwcr: 1.63 },
        { year: "FY2023", trir: 0.64, lwcr: 0.11, industryTrir: 2.77, industryLwcr: 1.63 },
        { year: "FY2024", trir: 0.47, lwcr: 0.09, industryTrir: 2.77, industryLwcr: 1.63 },
      ],
      series: [
        { dataKey: "trir", name: "Amentum TRIR", color: "#ef4444" },
        { dataKey: "lwcr", name: "Amentum LWCR", color: "#22c55e" },
        { dataKey: "industryTrir", name: "Industry avg TRIR", color: "#94a3b8" },
        { dataKey: "industryLwcr", name: "Industry avg LWCR", color: "#a78bfa" },
      ],
      domain: [0, 3],
      headline: "injury trend",
      fullWidth: true,
    },
    {
      id: "amentum-2027-target-progress",
      title: "Progress toward 50% injury reduction target by 2027",
      subtitle: "Uploaded analysis: FY2024 actuals are already 86% of the way to TRIR target and 80% of the way to LWCR target.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "TRIR baseline", baseline: 0.82, target: 0.41, actual: 0.47, progress: 86 },
        { metric: "LWCR baseline", baseline: 0.15, target: 0.075, actual: 0.09, progress: 80 },
      ],
      series: [{ dataKey: "progress", name: "Progress to 2027 target", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 100],
      headline: "target progress",
    },
    {
      id: "amentum-nsc-safety-awards",
      title: "Amentum NSC safety awards growing 2023-2025",
      subtitle: "Uploaded chart/page 6: awards show improvement across hundreds of programs, not just one site.",
      type: "grouped",
      xKey: "year",
      data: [
        { year: "2023", perfectRecord: 89, millionHours: 37, safetyLeader: 30, industryLeader: 6, superiorSafety: 10 },
        { year: "2024", perfectRecord: 113, millionHours: 40, safetyLeader: 29, industryLeader: 6, superiorSafety: 8 },
        { year: "2025", perfectRecord: 152, millionHours: 45, safetyLeader: 43, industryLeader: 10, superiorSafety: 9 },
      ],
      series: [
        { dataKey: "perfectRecord", name: "Perfect Record", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "millionHours", name: "Million Hours", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "safetyLeader", name: "Safety Leader", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "industryLeader", name: "Industry Leader", color: "#a78bfa", radius: [8, 8, 0, 0] },
        { dataKey: "superiorSafety", name: "Superior Safety", color: "#f97316", radius: [8, 8, 0, 0] },
      ],
      headline: "award breadth",
      fullWidth: true,
    },
    {
      id: "amentum-claims-reserves",
      title: "Amentum Holdings reserves declining FY2024-FY2025",
      subtitle: "Uploaded chart/page 7: current + long-term reserves declined $76M, from $235M to $159M.",
      type: "stacked",
      xKey: "period",
      data: [
        { period: "Sep 2024", current: 50, longTerm: 185 },
        { period: "Oct 2025", current: 46, longTerm: 113 },
      ],
      series: [
        { dataKey: "current", name: "Current reserves", color: "#22d3ee", stackId: "reserves" },
        { dataKey: "longTerm", name: "Long-term reserves", color: "#ef4444", stackId: "reserves", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "reserve decline",
      fullWidth: true,
    },
    {
      id: "amentum-reserve-change",
      title: "Claims reserve change by reserve type",
      subtitle: "Uploaded analysis: long-term reserves drove most of the decline, dropping $72M year over year.",
      type: "bar",
      xKey: "reserveType",
      data: [
        { reserveType: "Current reserves", decline: 4 },
        { reserveType: "Long-term reserves", decline: 72 },
        { reserveType: "Total reserves", decline: 76 },
      ],
      series: [{ dataKey: "decline", name: "Reserve decline", color: "#22c55e", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "money trail",
    },
    {
      id: "amentum-occumed-leverage-map",
      title: "Occu-Med leverage points in Amentum trend story",
      subtitle: "Trend-linked occupational medicine lanes where Occu-Med can credibly support ongoing safety improvement.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "Pre-employment screens", priority: 10 },
        { lane: "Annual surveillance", priority: 9 },
        { lane: "Return-to-work evals", priority: 9 },
        { lane: "Respirator/PFT/audio", priority: 8 },
        { lane: "DOT / fit-for-duty", priority: 7 },
        { lane: "Fresno regional support", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Leverage score", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "Occu-Med leverage",
    },
    {
      id: "pae-acquisition",
      title: "PAE acquisition impact",
      subtitle: "Legacy profile visual: Amentum baseline plus PAE added.",
      type: "stacked",
      xKey: "name",
      data: [
        { name: "Revenue ($B)", amentum: 6, added: 3 },
        { name: "Employees (K)", amentum: 35, added: 18 },
      ],
      series: [
        { dataKey: "amentum", name: "Amentum", color: "#22d3ee", stackId: "stack" },
        { dataKey: "added", name: "PAE added", color: "#ef4444", stackId: "stack", radius: [10, 10, 0, 0] },
      ],
      headline: "acquisition impact",
    },
    {
      id: "pae-revenue",
      title: "PAE legacy revenue potential",
      subtitle: "Legacy profile visual; $K/year opportunity lanes.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "USCIS/CBP", value: 140 },
        { name: "Army CFT", value: 95 },
        { name: "OCONUS DBA", value: 170 },
        { name: "Fresno CFT", value: 50 },
      ],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "legacy revenue",
    },
    {
      id: "pae-oconus",
      title: "PAE historical peak OCONUS headcount",
      subtitle: "Legacy profile visual; peak deployed workers.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "State/Embassy", value: 3000 },
        { name: "Afghanistan", value: 4500 },
        { name: "Africa", value: 1500 },
        { name: "Iraq/CENTCOM", value: 2500 },
        { name: "Europe BOS", value: 2000 },
      ],
      series: [{ dataKey: "value", color: "#dc2626", radius: [10, 10, 0, 0] }],
      headline: "OCONUS headcount",
    },
    {
      id: "pae-trir",
      title: "PAE legacy worker TRIR by type",
      subtitle: "Legacy profile visual; BLS TRIR benchmark.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "USCIS/CBP", trir: 0.8 },
        { name: "Army CFT", trir: 3.4 },
        { name: "OCONUS BOS", trir: 2.5 },
        { name: "DOS Overseas", trir: 2.0 },
        { name: "Training/Tech", trir: 0.6 },
      ],
      series: [{ dataKey: "trir", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "legacy TRIR",
    },
    {
      id: "pae-biometric-risk",
      title: "USCIS/CBP biometric worker risk",
      subtitle: "Legacy profile visual; severity vs frequency.",
      type: "grouped",
      xKey: "name",
      data: [
        { name: "Disease", severity: 4, frequency: 5 },
        { name: "Ergonomic", severity: 3, frequency: 5 },
        { name: "Stress", severity: 4, frequency: 4 },
        { name: "Needle-stick", severity: 2, frequency: 3 },
        { name: "Skin contact", severity: 2, frequency: 3 },
      ],
      series: [
        { dataKey: "severity", name: "Severity", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "frequency", name: "Frequency", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      headline: "biometric risk",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "amentum-employees", label: "Employees after Jacobs CMS merger", value: 53000, unit: "count", category: "workforce" },
    { id: "amentum-trir-fy2024", label: "FY2024 TRIR", value: 0.47, unit: "score", category: "safety" },
    { id: "amentum-lwcr-fy2024", label: "FY2024 LWCR", value: 0.09, unit: "score", category: "safety" },
    { id: "amentum-trir-decline", label: "FY2022-FY2024 TRIR decline", value: 43, unit: "percent", category: "safety" },
    { id: "amentum-lwcr-decline", label: "FY2022-FY2024 LWCR decline", value: 40, unit: "percent", category: "safety" },
    { id: "amentum-reserve-decline", label: "Reserve decline", value: 76, unit: "usd", category: "financial" },
    { id: "amentum-reserve-decline-percent", label: "Reserve decline percentage", value: 32, unit: "percent", category: "financial" },
    { id: "amentum-perfect-record-2025", label: "2025 Perfect Record awards", value: 152, unit: "count", category: "safety" },
  ],
  riskMatrix: [
    { name: "Amentum safety trend", revenue: 76, risk: 4.0, workers: 53000 },
    { name: "Claims reserve leverage", revenue: 76, risk: 6.0, workers: 53000 },
    { name: "Pre-employment / annual exams", revenue: 1.0, risk: 7.0, workers: 53000 },
    { name: "Legacy PAE OCONUS", revenue: 170, risk: 8.0, workers: 13500 },
    { name: "Fresno / Central Valley support", revenue: 50, risk: 6.0, workers: 1000 },
  ],
  opportunityMatrix: [
    { name: "Safety Trend Narrative", revenuePotential: 76000, implementationComplexity: 6, strategicValue: 10 },
    { name: "Pre-Employment Screens", revenuePotential: 1000, implementationComplexity: 4, strategicValue: 9 },
    { name: "Annual Surveillance", revenuePotential: 1500, implementationComplexity: 5, strategicValue: 9 },
    { name: "Return-to-Work Evaluations", revenuePotential: 750, implementationComplexity: 5, strategicValue: 8 },
    { name: "Legacy PAE DBA", revenuePotential: 170, implementationComplexity: 7, strategicValue: 8 },
    { name: "Fresno Regional Support", revenuePotential: 50, implementationComplexity: 3, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "This profile now combines Amentum public safety trend intelligence with the existing PAE legacy opportunity model. The uploaded trend document is explicitly from Occu-Med's perspective: Occu-Med performs pre-employment and annual exams and wants a public-record way to understand whether Amentum's injury and claims outcomes are improving.",
      bullets: [
        "Amentum's TRIR fell from approximately 0.82 in FY2022 to 0.47 in FY2024.",
        "Amentum's LWCR fell from approximately 0.15 in FY2022 to 0.09 in FY2024.",
        "The uploaded analysis frames Occu-Med as part of the prevention infrastructure, while acknowledging Amentum does not share direct exam-outcome data.",
        "Headcount increased to 53,000+ after the September 2024 Jacobs CMS merger, meaning exam volume should grow even if rates decline.",
      ],
      metricIds: ["amentum-employees", "amentum-trir-fy2024", "amentum-lwcr-fy2024"],
    },
    {
      type: "safety",
      title: "Public safety trend: injury rates are falling fast",
      narrative:
        "The uploaded trend analysis reconstructs FY2022-FY2024 TRIR and LWCR values from Amentum public ESG/impact disclosures and shows a dramatic two-year improvement. That trend supports a value story for prevention-focused occupational medicine, although it does not prove Occu-Med alone caused the decline.",
      bullets: [
        "TRIR declined 43% from FY2022 estimate to FY2024 actual.",
        "LWCR declined 40% from FY2022 estimate to FY2024 actual.",
        "FY2024 TRIR of 0.47 is far below the composite industry average of 2.77 cited in the uploaded analysis.",
        "FY2024 LWCR of 0.09 is far below the composite industry average of 1.63 cited in the uploaded analysis.",
      ],
      metricIds: ["amentum-trir-decline", "amentum-lwcr-decline"],
    },
    {
      type: "medical-opportunities",
      title: "What this means for Occu-Med",
      narrative:
        "The uploaded document's central business question is how Occu-Med can understand its value when Amentum does not share internal data. The public trend record gives a defensible narrative: injury rates, lost-workday cases, safety awards, and reserves are all moving in the right direction, and Occu-Med's pre-employment and annual exam work supports the upstream prevention system.",
      bullets: [
        "Pre-employment screens help catch musculoskeletal, respiratory, fitness-for-duty, and surveillance concerns before they become recordable or lost-time events.",
        "Annual exams and surveillance can catch deterioration in hearing, lung function, and functional capacity before a claim occurs.",
        "Return-to-work evaluations directly influence LWCR by helping employees return to modified or full duty faster.",
        "The correct claim is 'consistent with Occu-Med value,' not 'proof Occu-Med caused the entire decline.'",
      ],
      metricIds: [],
    },
    {
      type: "safety",
      title: "2027 injury-reduction goal pressure",
      narrative:
        "The uploaded trend analysis states that Amentum set a company-wide goal to reduce workplace injuries by 50% by 2027. Based on FY2024 actuals, the company appears ahead of schedule, which means pressure to sustain improvement will remain high.",
      bullets: [
        "FY2024 TRIR progress is calculated at 86% of the way to the 2027 target.",
        "FY2024 LWCR progress is calculated at 80% of the way to the 2027 target.",
        "That creates a reason for Amentum to preserve, not cut, preventive occupational medicine services.",
      ],
      metricIds: [],
    },
    {
      type: "safety",
      title: "NSC awards show program breadth",
      narrative:
        "The uploaded analysis uses National Safety Council awards as breadth evidence. Perfect Record awards rose from 89 to 113 to 152 programs from 2023 to 2025, and total awards rose from roughly 172 to 300+ to 400+.",
      bullets: [
        "Perfect Record awards: 89 in 2023, 113 in 2024, 152 in 2025.",
        "Industry Leader awards: 6 in 2023, 6 in 2024, 10 in 2025.",
        "The improvement appears distributed across many programs, not limited to one site.",
      ],
      metricIds: ["amentum-perfect-record-2025"],
    },
    {
      type: "procurement",
      title: "Balance-sheet reserves: the insurance money trail",
      narrative:
        "The uploaded document treats claims reserves as the indirect financial signal. Amentum Holdings' current plus long-term reserves declined from $235M in Sep 2024 to $159M in Oct 2025, a $76M or 32% decline.",
      bullets: [
        "Current reserves declined from $50M to $46M.",
        "Long-term reserves declined from $185M to $113M.",
        "The analysis says these reserve lines include workers' compensation, general liability, and other claims accruals.",
        "Lower reserves are consistent with fewer and/or smaller claims, but they are not a pure workers' compensation-only measure.",
      ],
      metricIds: ["amentum-reserve-decline", "amentum-reserve-decline-percent"],
    },
    {
      type: "contracts",
      title: "Legacy PAE and Fresno/Central Valley relevance",
      narrative:
        "The profile preserves the earlier PAE legacy opportunity model because Amentum still carries legacy PAE operations, OCONUS headcount, biometric processing risk, and Fresno/Central Valley support relevance.",
      bullets: [
        "Legacy PAE lanes include USCIS/CBP biometric operations, Army CFT aviation mechanics, OCONUS DBA support, and Fresno CFT support.",
        "Historical OCONUS peak headcount remains relevant to DBA and deployment medical planning.",
        "Fresno/Central Valley support should be positioned as part of a growing post-merger exam footprint.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "Amentum values in this profile are extracted from the uploaded trend analysis and legacy profile data. The trend is useful for Occu-Med value positioning but must be worded carefully because Amentum does not share direct internal exam/outcome attribution data with Occu-Med.",
      bullets: [
        "Do not claim Occu-Med alone caused Amentum's TRIR, LWCR, award, or reserve improvements.",
        "Use language such as 'consistent with prevention-focused occupational medicine value' and 'supports the value story.'",
        "Reserve decline includes workers' compensation, general liability, and other claims accruals; do not describe it as workers' comp-only savings.",
        "Preserve the uploaded analysis as evidence for extracted trend tables, charts, and sales narrative.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "comparative-benchmark",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
