import type { CompanyConfig } from "./types";

export const paeAmentumConfig: CompanyConfig = {
  companyId: "pae-amentum",
  displayName: "PAE / Amentum",
  shortName: "PAE",
  sector: "Legacy PAE programs, Amentum integration, OCONUS support, biometric processing, aviation maintenance, and government services",
  headquarters: "Germantown, Maryland (Amentum HQ)",
  employees: 53000,
  employeesAsOf: "Combined modeled workforce after PAE acquisition visual",
  summary: "PAE / Amentum has been added as an acquisition and legacy-program opportunity dossier connecting PAE's $1.9B acquisition, combined Amentum scale, PAE legacy revenue lanes, historical OCONUS headcount, worker-risk segmentation, and USCIS/CBP biometric operational hazards.",
  tags: ["Amentum acquisition", "PAE legacy programs", "OCONUS workforce", "Biometric processing", "Revenue opportunity"],
  aliases: ["PAE", "Amentum", "PAE Incorporated"],
  sourceFilters: {
    sam: { legalNames: ["Amentum Holdings", "PAE Incorporated"] },
    usaSpending: { recipientNames: ["PAE", "Amentum"], parentOrgs: ["Amentum Holdings"] },
    newsSources: { aliases: ["PAE", "Amentum"], acquisitionAliases: ["PAE Incorporated"] },
  },
  executiveSignals: [
    { label: "Combined scale", value: "$9B / 53K", note: "Amentum plus PAE modeled combined scale." },
    { label: "PAE added", value: "$3B / 18K", note: "PAE added revenue and workers to Amentum baseline." },
    { label: "Legacy revenue", value: "$455K/yr", note: "Modeled revenue across legacy program lanes." },
    { label: "Worker-risk peak", value: "TRIR 3.4", note: "Army CFT aviation mechanics are highest-risk category." },
  ],
  curveTitle: "PAE acquisition and legacy opportunity curve",
  curveSubtitle: "Acquisition scale, legacy revenue, OCONUS headcount, and worker-risk values normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "pae-acquisition",
      title: "PAE acquisition impact",
      subtitle: "Source: uploaded PAE visual; Amentum baseline plus PAE added.",
      type: "stacked",
      xKey: "name",
      data: [{ name: "Revenue ($B)", amentum: 6, added: 3 }, { name: "Employees (K)", amentum: 35, added: 18 }],
      series: [
        { dataKey: "amentum", name: "Amentum", color: "#22d3ee", stackId: "stack" },
        { dataKey: "added", name: "PAE added", color: "#ef4444", stackId: "stack", radius: [10, 10, 0, 0] },
      ],
      headline: "acquisition impact",
    },
    {
      id: "pae-revenue",
      title: "PAE legacy revenue potential",
      subtitle: "Source: uploaded PAE visual; $K/yr.",
      type: "bar",
      xKey: "name",
      data: [{ name: "USCIS/CBP", value: 140 }, { name: "Army CFT", value: 95 }, { name: "OCONUS DBA", value: 170 }, { name: "Fresno CFT", value: 50 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "revenue potential",
    },
    {
      id: "pae-oconus",
      title: "PAE historical peak OCONUS headcount",
      subtitle: "Source: uploaded PAE visual; peak deployed workers.",
      type: "bar",
      xKey: "name",
      data: [{ name: "State/Embassy", value: 3000 }, { name: "Afghanistan", value: 4500 }, { name: "Africa", value: 1500 }, { name: "Iraq/CENTCOM", value: 2500 }, { name: "Europe BOS", value: 2000 }],
      series: [{ dataKey: "value", color: "#dc2626", radius: [10, 10, 0, 0] }],
      headline: "OCONUS headcount",
    },
    {
      id: "pae-trir",
      title: "PAE legacy worker TRIR by type",
      subtitle: "Source: uploaded PAE visual; BLS TRIR benchmark.",
      type: "bar",
      xKey: "name",
      data: [{ name: "USCIS/CBP", trir: 0.8 }, { name: "Army CFT", trir: 3.4 }, { name: "OCONUS BOS", trir: 2.5 }, { name: "DOS Overseas", trir: 2.0 }, { name: "Training/Tech", trir: 0.6 }],
      series: [{ dataKey: "trir", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "TRIR benchmark",
    },
    {
      id: "pae-biometric-risk",
      title: "USCIS/CBP biometric worker risk",
      subtitle: "Source: uploaded PAE visual; severity vs frequency.",
      type: "grouped",
      xKey: "name",
      data: [{ name: "Disease", severity: 4, frequency: 5 }, { name: "Ergonomic", severity: 3, frequency: 5 }, { name: "Stress", severity: 4, frequency: 4 }, { name: "Needle-stick", severity: 2, frequency: 3 }, { name: "Skin contact", severity: 2, frequency: 3 }],
      series: [
        { dataKey: "severity", name: "Severity", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "frequency", name: "Frequency", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      headline: "biometric risk",
      fullWidth: true,
    },
  ],
};
