import type { CompanyConfig } from "./types";

export const parsonsConfig: CompanyConfig = {
  companyId: "parsons",
  displayName: "Parsons Corporation",
  shortName: "Parsons",
  sector: "Federal solutions, critical infrastructure, engineering, construction management, environmental remediation, and defense facilities support",
  headquarters: "Chantilly, Virginia",
  employees: 21000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 20, 2026",
  summary:
    "Parsons Corporation is a public engineering, federal solutions, and critical infrastructure entity with a two-segment risk profile: lower-injury Federal Solutions work and higher-exposure Critical Infrastructure, construction management, PFAS remediation, and OCONUS military construction work. The uploaded Occu-Med intelligence model flags DBA-covered Indo-Pacific construction and PFAS biomonitoring as the most strategic occupational medicine lanes.",
  tags: [
    "Entity profile",
    "Federal contractor",
    "Critical infrastructure",
    "OCONUS construction",
    "PFAS remediation",
    "DBA exposure",
    "Engineering services",
  ],
  aliases: ["Parsons", "Parsons Corp", "PSN", "Parsons Corporation"],
  sourceFilters: {
    sec: { ticker: "PSN", legalEntities: ["Parsons Corporation"] },
    sam: { legalNames: ["Parsons Corporation"] },
    usaSpending: { recipientNames: ["Parsons", "Parsons Corporation"] },
    jobSources: { linkedin: "parsons", careerSite: "https://jobs.parsons.com/" },
    newsSources: { aliases: ["Parsons", "Parsons Corporation", "PSN"] },
  },
  executiveSignals: [
    {
      label: "Expected injuries",
      value: "222/yr",
      note: "Occu-Med model estimate using BLS TRIR benchmarks applied to 21,000 employees and segment mix.",
    },
    {
      label: "Economic burden",
      value: "$52.6M/yr",
      note: "Modeled direct annual injury cost multiplied by OSHA indirect cost factor.",
    },
    {
      label: "TRIR gap",
      value: "4.4×",
      note: "Reported 2018 TRIR of 0.24 compared with modeled BLS benchmark expected TRIR of 1.06.",
    },
    {
      label: "Occu-Med potential",
      value: "$1.4M–$3.4M/yr",
      note: "Modeled annual revenue potential across pre-employment, DBA, PFAS, hearing, respirator, and DOT services.",
    },
  ],
  curveTitle: "Parsons risk, DBA, and PFAS opportunity curve",
  curveSubtitle:
    "Uploaded Occu-Med intelligence values normalized for entity-profile scanning; modeled estimates should be treated as assumption-driven signals, not audited disclosures.",
  chartDefinitions: [
    {
      id: "parsons-five-numbers",
      title: "Parsons five exposure numbers that matter",
      subtitle: "Source: uploaded Parsons Occu-Med intelligence report; modeled annual cost and DBA exposure values.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Direct injury cost", value: 9.6 },
        { metric: "Economic burden", value: 52.6 },
        { metric: "DBA claim exposure", value: 14.6 },
        { metric: "Fatality expected value", value: 0.482 },
      ],
      series: [{ dataKey: "value", name: "Annual exposure", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "modeled exposure",
    },
    {
      id: "parsons-trir-gap",
      title: "Reported TRIR vs modeled benchmark exposure",
      subtitle: "Reported 2018 TRIR compared with BLS benchmark expected TRIR and construction industry TRIR.",
      type: "bar",
      xKey: "source",
      data: [
        { source: "Reported TRIR", value: 0.24 },
        { source: "BLS expected TRIR", value: 1.06 },
        { source: "Construction TRIR", value: 2.3 },
      ],
      series: [{ dataKey: "value", name: "TRIR", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 2.5],
      headline: "TRIR gap",
    },
    {
      id: "parsons-injuries-by-segment",
      title: "Expected recordable injuries by segment",
      subtitle: "BLS TRIR benchmarks applied to Parsons workforce mix; total modeled estimate: 222 recordable injuries per year.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "Federal cyber/intel", injuries: 37.5 },
        { segment: "Federal engineering", injuries: 24.5 },
        { segment: "CI civil engineering", injuries: 21.0 },
        { segment: "CI construction/site", injuries: 69.0 },
        { segment: "Environmental/PFAS", injuries: 18.0 },
        { segment: "OCONUS PDI-AFCEC", injuries: 45.0 },
        { segment: "Admin/corporate", injuries: 7.5 },
      ],
      series: [{ dataKey: "injuries", name: "Recordable injuries/yr", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "injury segments",
    },
    {
      id: "parsons-dba-ramp",
      title: "DBA exposure ramp as PDI MACC / AFCEC MATOC scale",
      subtitle: "Modeled DBA claim exposure as OCONUS construction headcount expands with task-order volume.",
      type: "bar",
      xKey: "scenario",
      data: [
        { scenario: "Current", claimExposure: 13.5 },
        { scenario: "PDI partial", claimExposure: 22.5 },
        { scenario: "Full PDI+AFCEC", claimExposure: 36.0 },
        { scenario: "Max task order", claimExposure: 54.0 },
      ],
      series: [{ dataKey: "claimExposure", name: "DBA claim exposure", color: "#f97316", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "DBA ramp",
    },
    {
      id: "parsons-revenue-potential",
      title: "Occu-Med annual revenue potential by exam lane",
      subtitle: "Modeled opportunity range from uploaded Parsons report; values shown in $K per year.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Pre-employment", low: 551, high: 788 },
        { examType: "DBA pre-deploy", low: 525, high: 1500 },
        { examType: "PFAS biomonitoring", low: 100, high: 400 },
        { examType: "Hearing", low: 150, high: 500 },
        { examType: "Respirator", low: 50, high: 150 },
        { examType: "DOT CDL", low: 25, high: 100 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
    },
    {
      id: "parsons-regulatory-obligations",
      title: "Regulatory obligation map",
      subtitle: "Populations and likely medical-surveillance requirements identified in uploaded Occu-Med intelligence report.",
      type: "bar",
      xKey: "population",
      data: [
        { population: "OCONUS construction", priority: 10 },
        { population: "PFAS remediation", priority: 9 },
        { population: "Construction sites", priority: 8 },
        { population: "CDL operators", priority: 6 },
        { population: "Environmental field", priority: 7 },
        { population: "New hires", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Priority score", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "surveillance priorities",
    },
  ],
  metricDefinitions: [
    { id: "parsons-employees", label: "Employees", value: 21000, unit: "count", category: "workforce" },
    { id: "parsons-expected-injuries", label: "Expected recordable injuries/yr", value: 222, unit: "count", category: "safety" },
    { id: "parsons-direct-injury-cost", label: "Direct injury cost", value: 9.6, unit: "usd", category: "financial" },
    { id: "parsons-economic-burden", label: "Economic burden", value: 52.6, unit: "usd", category: "financial" },
    { id: "parsons-dba-exposure", label: "Annual DBA claim exposure", value: 14.6, unit: "usd", category: "risk" },
    { id: "parsons-occumed-revenue-high", label: "Occu-Med revenue potential high", value: 3.4, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Federal Solutions", revenue: 3.26, risk: 3.5, workers: 14500 },
    { name: "Critical Infrastructure", revenue: 3.14, risk: 8.5, workers: 6500 },
    { name: "PFAS remediation", revenue: 0.4, risk: 9.0, workers: 1000 },
    { name: "OCONUS construction", revenue: 1.2, risk: 9.5, workers: 3000 },
  ],
  opportunityMatrix: [
    { name: "DBA Pre-Deployment", revenuePotential: 1500, implementationComplexity: 7, strategicValue: 10 },
    { name: "Pre-Employment Physicals", revenuePotential: 788, implementationComplexity: 4, strategicValue: 8 },
    { name: "Hearing Conservation", revenuePotential: 500, implementationComplexity: 5, strategicValue: 8 },
    { name: "PFAS Biomonitoring", revenuePotential: 400, implementationComplexity: 9, strategicValue: 10 },
    { name: "Respirator Clearances", revenuePotential: 150, implementationComplexity: 4, strategicValue: 7 },
    { name: "DOT CDL Physicals", revenuePotential: 100, implementationComplexity: 3, strategicValue: 5 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Parsons is positioned as a dual-segment engineering and infrastructure entity. The uploaded report frames its occupational medicine opportunity around the gap between reported corporate TRIR and the higher-risk work actually managed across construction, environmental remediation, and OCONUS military infrastructure programs.",
      bullets: [
        "$6.4B public company headquartered in Chantilly, Virginia.",
        "21,000+ employees operating in 30+ countries.",
        "Revenue is split nearly evenly between Federal Solutions and Critical Infrastructure.",
        "Employee-owned through an ESOP holding roughly 39% of outstanding shares, making injury-cost control a shareholder-value argument.",
      ],
      metricIds: ["parsons-employees", "parsons-economic-burden"],
    },
    {
      type: "workforce",
      title: "Two-segment injury profile",
      narrative:
        "Federal Solutions is lower-injury but has DBA-sensitive OCONUS engineering exposure. Critical Infrastructure carries most of the modeled injury volume through construction management, PFAS remediation, and military construction lanes.",
      bullets: [
        "Federal Solutions: roughly 51% of revenue and approximately 14,500 workers.",
        "Critical Infrastructure: roughly 49% of revenue and approximately 6,500 workers.",
        "Critical Infrastructure generates an estimated 160 recordable injuries per year in the uploaded model.",
        "The total modeled injury burden is 222 recordable injuries per year.",
      ],
      metricIds: ["parsons-expected-injuries"],
    },
    {
      type: "contracts",
      title: "DBA and OCONUS construction ramp",
      narrative:
        "The report identifies the $15B PDI MACC and $15B AFCEC Comprehensive Construction & Engineering MATOC as the key OCONUS construction triggers. These vehicles do not guarantee revenue, but they position Parsons for DBA-covered construction work on U.S. military infrastructure in high-tension overseas theaters.",
      bullets: [
        "PDI MACC: NAVFAC vehicle for Indo-Pacific military infrastructure construction.",
        "AFCEC MATOC: global military facilities work including airfields, power systems, water treatment, and communications networks.",
        "Current estimated OCONUS construction headcount is modeled at 1,500 and could scale toward 4,000-6,000.",
        "Annual DBA exposure is modeled from $13.5M to $32.4M+ depending on task-order volume.",
      ],
      metricIds: ["parsons-dba-exposure"],
    },
    {
      type: "safety",
      title: "PFAS remediation medical-surveillance gap",
      narrative:
        "Parsons' PFAS remediation work creates a rare occupational medicine lane because no OSHA PFAS worker exposure standard is currently established in the uploaded report's model. The report argues that serum PFAS baseline biomonitoring can become a differentiating protocol for workers in direct remediation contact.",
      bullets: [
        "PFAS remediation workers may face dermal and inhalation exposure during soil and groundwater remediation.",
        "The report links PFAS exposure concerns to thyroid disease, kidney cancer, testicular cancer, immune suppression, and reproductive harm at elevated exposures.",
        "Pre-employment serum PFAS baseline biomonitoring is presented as an emerging worker-protection protocol.",
        "Occu-Med is positioned as a potential early-mover provider for PFAS worker biomonitoring.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded model estimates $1.4M-$3.4M in annual Occu-Med revenue potential across pre-employment, DBA, PFAS, hearing conservation, respirator clearance, and DOT CDL physical lanes.",
      bullets: [
        "Pre-employment physicals: 3,150 new hires; modeled $551K-$788K per year.",
        "DBA pre-deployment exams: 1,500-3,000 workers; modeled $525K-$1.5M per year.",
        "PFAS biomonitoring: 500-1,000 workers; modeled $100K-$400K per year.",
        "Hearing conservation: 2,000-4,000 workers; modeled $150K-$500K per year.",
        "Respirator clearances and DOT CDL physicals add smaller but operationally important lanes.",
      ],
      metricIds: ["parsons-occumed-revenue-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "Parsons values in this profile are source-backed but model-driven. The charts should be interpreted as Occu-Med intelligence estimates derived from the uploaded Parsons report, public-company information, BLS benchmarks, OSHA/NSC assumptions, and DBA exposure modeling.",
      bullets: [
        "Do not present modeled injury, DBA, or revenue projections as audited Parsons disclosures.",
        "Label the profile as an uploaded Occu-Med intelligence model.",
        "Preserve the source file as evidence for the extracted tables, charts, and sales narrative.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "executive-summary",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: false,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
