import type { CompanyConfig } from "./types";

export const peckhamConfig: CompanyConfig = {
  companyId: "peckham",
  displayName: "Peckham, Inc.",
  shortName: "Peckham",
  sector:
    "Nonprofit social enterprise, AbilityOne manufacturing, federal contact centers, facilities services, janitorial operations, vocational programs, and IT/document services",
  headquarters: "Lansing, Michigan",
  employees: 4000,
  employeesAsOf: "Uploaded Occu-Med intelligence report",
  summary:
    "Peckham, Inc. is a Lansing-based nonprofit social enterprise and AbilityOne participant serving federal and state customers through contact center, manufacturing, janitorial, IT, document services, and vocational programs. The uploaded Occu-Med intelligence model treats Peckham as a uniquely complex occupational medicine entity because the majority of its workforce includes individuals with documented disabilities, wounded warriors, veterans with service-connected disabilities, behavioral health conditions, and physical or cognitive disabilities.",
  tags: [
    "Entity profile",
    "AbilityOne",
    "Nonprofit social enterprise",
    "Disability workforce",
    "ADA compliance",
    "Post-offer pre-placement",
    "Ergonomics",
    "Janitorial risk",
    "Manufacturing surveillance",
  ],
  aliases: ["Peckham", "Peckham, Inc.", "Peckham Inc", "Peckham Vocational Industries", "Peckham Vocational Industries, Inc."],
  sourceFilters: {
    sam: { legalNames: ["Peckham Vocational Industries, Inc.", "Peckham, Inc."] },
    usaSpending: { recipientNames: ["Peckham", "Peckham Vocational Industries"] },
    jobSources: { careerSite: "https://www.peckham.org/" },
    newsSources: { aliases: ["Peckham", "Peckham Inc", "Peckham Vocational Industries", "AbilityOne Peckham"] },
  },
  executiveSignals: [
    {
      label: "Expected injuries",
      value: "61/yr",
      note: "Disability-adjusted Occu-Med model estimate using BLS benchmarks and a 1.25-1.40 disability workforce premium.",
    },
    {
      label: "BLS baseline",
      value: "49/yr",
      note: "Modeled injury count before pre-existing-condition/disability workforce premium adjustment.",
    },
    {
      label: "Economic burden",
      value: "$14.4M/yr",
      note: "Modeled total annual burden: 61 injuries multiplied by $43K and OSHA indirect cost multiplier.",
    },
    {
      label: "Occu-Med potential",
      value: "$520K–$770K/yr",
      note: "Modeled annual opportunity across ADA-compliant post-offer physicals, FCEs, hearing conservation, ergonomics, and fitness-for-duty.",
    },
  ],
  curveTitle: "Peckham disability workforce and ADA-compliant occupational medicine curve",
  curveSubtitle:
    "Uploaded Occu-Med intelligence values normalized for entity-profile scanning; modeled estimates should be treated as assumption-driven signals, not audited employer disclosures.",
  chartDefinitions: [
    {
      id: "peckham-five-numbers",
      title: "Peckham five exposure numbers that matter",
      subtitle: "Source: uploaded Peckham Occu-Med intelligence report; modeled injury, cost, and revenue values.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Expected injuries", value: 61.0 },
        { metric: "BLS baseline", value: 49.0 },
        { metric: "Disability premium", value: 12.0 },
      ],
      series: [{ dataKey: "value", name: "Injuries/yr", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "injury model",
    },
    {
      id: "peckham-cost-burden",
      title: "Modeled cost burden and disability workforce premium",
      subtitle: "Economic burden and incremental premium from undocumented pre-existing conditions at hire.",
      type: "bar",
      xKey: "costType",
      data: [
        { costType: "Total economic burden", value: 14.4 },
        { costType: "Disability premium", value: 2.81 },
      ],
      series: [{ dataKey: "value", name: "Annual burden", color: "#f97316", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "cost burden",
    },
    {
      id: "peckham-division-injury-rate",
      title: "BLS baseline vs disability-adjusted injury rate by division",
      subtitle: "Workers with pre-existing conditions drive a higher expected claim rate; chart compares baseline and disability-adjusted TRIR by division.",
      type: "bar",
      xKey: "division",
      data: [
        { division: "Contact Center", bls: 0.6, adjusted: 0.8, injuries: 16.0 },
        { division: "AbilityOne Mfg", bls: 1.5, adjusted: 2.0, injuries: 16.0 },
        { division: "Janitorial", bls: 3.25, adjusted: 3.75, injuries: 26.25 },
        { division: "IT / Doc Svcs", bls: 0.5, adjusted: 0.6, injuries: 1.8 },
        { division: "Voc / Admin", bls: 0.4, adjusted: 0.45, injuries: 0.9 },
      ],
      series: [
        { dataKey: "bls", name: "BLS benchmark TRIR", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "adjusted", name: "Disability-adjusted TRIR", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      domain: [0, 4],
      headline: "division TRIR",
    },
    {
      id: "peckham-injuries-by-division",
      title: "Expected injuries by division",
      subtitle: "Janitorial/facilities drives the highest injury volume despite a smaller headcount share.",
      type: "bar",
      xKey: "division",
      data: [
        { division: "Contact Center", injuries: 16.0 },
        { division: "AbilityOne Mfg", injuries: 16.0 },
        { division: "Janitorial", injuries: 26.25 },
        { division: "IT / Doc Svcs", injuries: 1.8 },
        { division: "Voc / Admin", injuries: 0.9 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/yr", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "injury concentration",
    },
    {
      id: "peckham-claim-cost-premium",
      title: "Average workers' comp claim cost by worker category",
      subtitle: "Uploaded model: pre-existing conditions and service-connected disabilities increase average claim cost and claim complexity.",
      type: "bar",
      xKey: "category",
      data: [
        { category: "General population", cost: 43 },
        { category: "Physical disability", cost: 62 },
        { category: "Behavioral health", cost: 71 },
        { category: "Service-connected disability", cost: 78 },
      ],
      series: [{ dataKey: "cost", name: "Average claim cost", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "claim premium",
    },
    {
      id: "peckham-ada-exam-framework",
      title: "ADA-compliant medical examination framework",
      subtitle: "Wrong exam at the wrong stage creates EEOC exposure; post-offer, pre-placement is the key defensible window.",
      type: "bar",
      xKey: "stage",
      data: [
        { stage: "Before offer", compliance: 0, risk: 10 },
        { stage: "After conditional offer", compliance: 10, risk: 3 },
        { stage: "During employment", compliance: 8, risk: 4 },
      ],
      series: [
        { dataKey: "compliance", name: "Permitted/defensible", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "risk", name: "Legal risk if mishandled", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      domain: [0, 10],
      headline: "ADA timing",
    },
    {
      id: "peckham-revenue-potential",
      title: "Occu-Med annual revenue potential by exam lane",
      subtitle: "Modeled opportunity range from uploaded Peckham report; values shown in $K per year.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Post-offer physicals", low: 210, high: 300 },
        { examType: "FCEs", low: 60, high: 100 },
        { examType: "Hearing", low: 60, high: 100 },
        { examType: "Ergonomics", low: 150, high: 200 },
        { examType: "Fitness-for-duty", low: 40, high: 70 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
    },
  ],
  metricDefinitions: [
    { id: "peckham-employees", label: "Employees", value: 4000, unit: "count", category: "workforce" },
    { id: "peckham-expected-injuries", label: "Disability-adjusted injuries/yr", value: 61, unit: "count", category: "safety" },
    { id: "peckham-baseline-injuries", label: "BLS baseline injuries/yr", value: 49, unit: "count", category: "safety" },
    { id: "peckham-economic-burden", label: "Total economic burden", value: 14.4, unit: "usd", category: "financial" },
    { id: "peckham-disability-premium", label: "Disability workforce burden premium", value: 2.81, unit: "usd", category: "risk" },
    { id: "peckham-occumed-revenue-high", label: "Occu-Med revenue potential high", value: 0.77, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Contact Center", revenue: 158.5, risk: 4.5, workers: 2000 },
    { name: "AbilityOne Manufacturing", revenue: 25, risk: 7.0, workers: 800 },
    { name: "Facilities / Janitorial", revenue: 21.5, risk: 9.0, workers: 700 },
    { name: "IT / Document Services", revenue: 10, risk: 3.0, workers: 300 },
    { name: "Vocational / Admin", revenue: 5, risk: 2.0, workers: 200 },
  ],
  opportunityMatrix: [
    { name: "Post-Offer Physicals", revenuePotential: 300, implementationComplexity: 8, strategicValue: 10 },
    { name: "Ergonomic Assessments", revenuePotential: 200, implementationComplexity: 5, strategicValue: 8 },
    { name: "FCEs", revenuePotential: 100, implementationComplexity: 7, strategicValue: 9 },
    { name: "Hearing Conservation", revenuePotential: 100, implementationComplexity: 4, strategicValue: 7 },
    { name: "Fitness-for-Duty", revenuePotential: 70, implementationComplexity: 6, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Peckham is modeled as the most legally complex occupational medicine entity in the portfolio because its workforce mission centers on people with disabilities and other barriers to employment. The core opportunity is not generic physicals; it is ADA-compliant, post-offer, job-specific documentation that protects both workers and the employer.",
      bullets: [
        "Lansing, Michigan-based nonprofit social enterprise and AbilityOne Program participant.",
        "Approximately 4,000 workers across contact center, manufacturing, janitorial, IT/document services, and vocational/admin programs.",
        "Major federal and state work includes State Department contact center operations, Army Corps contract work, and Michigan facilities services.",
        "The workforce includes wounded warriors, veterans with service-connected disabilities, behavioral health conditions, and physical/cognitive disabilities.",
      ],
      metricIds: ["peckham-employees", "peckham-economic-burden"],
    },
    {
      type: "workforce",
      title: "Disability-adjusted workforce risk model",
      narrative:
        "The uploaded model applies a disability workforce premium to BLS baseline injury expectations. The incremental 12 injuries per year are treated as the cost of not documenting pre-existing conditions at hire and not matching functional capacity to essential job demands.",
      bullets: [
        "Expected disability-adjusted injuries: 61 per year.",
        "BLS baseline injuries without adjustment: 49 per year.",
        "Incremental disability workforce premium: 12 injuries per year.",
        "Janitorial/facilities is the highest-risk division, generating 26.25 modeled injuries per year.",
      ],
      metricIds: ["peckham-expected-injuries", "peckham-baseline-injuries", "peckham-disability-premium"],
    },
    {
      type: "safety",
      title: "ADA-compliant exam framework",
      narrative:
        "The report frames the timing of medical exams as the central legal risk. Medical inquiries before a conditional offer are prohibited; after conditional offer and before start, uniform job-related examinations are permitted; during employment, exams must be job-related, such as fitness-for-duty, surveillance, or return-to-work clearance.",
      bullets: [
        "Before conditional offer: medical exam/inquiry is prohibited and creates ADA/EEOC risk.",
        "After conditional offer: post-offer, pre-placement physical is permitted if uniform, job-related, and confidential.",
        "During employment: fitness-for-duty, OSHA surveillance, and return-to-work exams are permitted when job-related.",
        "Generic urgent-care physicals are not the same as defensible occupational medicine post-offer evaluations.",
      ],
      metricIds: [],
    },
    {
      type: "workforce",
      title: "AbilityOne manufacturing and janitorial exposure",
      narrative:
        "Manufacturing and janitorial divisions require physical-capacity and ergonomic controls because workers may have mobility impairment, upper extremity limitations, vision impairment, neurological conditions, PTSD/TBI, or other pre-existing conditions that can interact with job demands.",
      bullets: [
        "AbilityOne manufacturing includes uniforms, PPE, cutting, sewing, pressing, packing, and inspection work.",
        "Manufacturing needs baseline audiometry, ergonomic evaluation, and job-specific physical capacity assessment.",
        "Janitorial/facilities work carries slips/falls, chemical exposure, and musculoskeletal overexertion risk.",
        "Workers with balance impairment or lower-extremity disability have elevated fall risk in janitorial settings.",
      ],
      metricIds: ["peckham-expected-injuries"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded model estimates $520K-$770K in annual Occu-Med revenue potential across post-offer pre-placement exams, complex-placement FCEs, AbilityOne hearing conservation, contact center ergonomic assessments, and fitness-for-duty evaluations.",
      bullets: [
        "Post-offer pre-placement physicals: 1,200 new hires; modeled $210K-$300K per year.",
        "Functional Capacity Evaluations: 200 complex placements; modeled $60K-$100K per year.",
        "Manufacturing hearing conservation: 800 workers; modeled $60K-$100K per year.",
        "Contact center ergonomic assessments: 2,000 workstations; modeled $150K-$200K per year.",
        "Fitness-for-duty evaluations: 200 per year; modeled $40K-$70K per year.",
      ],
      metricIds: ["peckham-occumed-revenue-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "Peckham values in this profile are source-backed but model-driven. The charts should be interpreted as Occu-Med intelligence estimates derived from the uploaded Peckham report, BLS benchmarks, NSC/OSHA cost assumptions, ADA framework analysis, and disability workforce risk modeling.",
      bullets: [
        "Do not present modeled injury, disability premium, or revenue projections as audited Peckham disclosures.",
        "Label the profile as an uploaded Occu-Med intelligence model.",
        "Preserve the source file as evidence for the extracted tables, charts, and sales narrative.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "executive-summary",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: false,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
