import type { CompanyConfig } from "./types";

export const peratonConfig: CompanyConfig = {
  companyId: "peraton",
  displayName: "Peraton",
  shortName: "Peraton",
  sector:
    "Private national security technology, space and intelligence systems, cyber mission support, ground station operations, DHA connected health, enterprise IT, and government mission services",
  headquarters: "Reston, Virginia",
  employees: 18000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: estimated 2024 workforce after post-Perspecta rationalization",
  summary:
    "Peraton is a privately held national security and technology entity headquartered in Reston, Virginia and owned by Veritas Capital. The uploaded Occu-Med report estimates about $8.0B in 2024 revenue and about 18,000 employees, down from 24,000 after post-merger rationalization following the Perspecta acquisition. The report's core thesis is not high injury volume; it is hidden specialty exposure inside a knowledge-worker company: RF/EMF risk for ground station technicians, OCONUS DBA exposure, DHA Connected Health communicable disease and vicarious trauma, and classified-work behavioral health for space, intelligence, and cyber mission workers. It also frames Peraton's lack of public TRIR, sustainability report, and fatality data as an IPO-readiness visibility gap.",
  tags: [
    "Entity profile",
    "Peraton",
    "Veritas Capital",
    "Private contractor",
    "IPO readiness",
    "Space and intelligence",
    "Cyber mission support",
    "Ground station operations",
    "RF/EMF exposure",
    "DHA Connected Health",
    "OCONUS DBA",
    "Behavioral health",
    "Clearance preservation",
    "No public TRIR",
  ],
  aliases: ["Peraton", "Peraton Inc", "Peraton Corporation", "Perspecta legacy", "Veritas Capital Peraton"],
  sourceFilters: {
    sam: { legalNames: ["Peraton Inc", "Peraton Corporation", "Perspecta"] },
    usaSpending: { recipientNames: ["Peraton", "Perspecta"], parentOrgs: ["Veritas Capital"] },
    jobSources: { linkedin: "peraton", careerSite: "https://www.peraton.com/careers/" },
    newsSources: {
      aliases: ["Peraton", "Veritas Capital", "Perspecta", "DHA Connected Health"],
      acquisitionAliases: ["Perspecta", "Northrop Grumman IT services", "Harris IT services"],
    },
  },
  executiveSignals: [
    {
      label: "Workforce",
      value: "~18,000",
      note: "Uploaded report estimates headcount after post-merger rationalization from a prior 24,000-worker level.",
    },
    {
      label: "Revenue",
      value: "~$8.0B",
      note: "Uploaded report frames Peraton as a large private government IT/national security contractor.",
    },
    {
      label: "Visibility gap",
      value: "No public TRIR",
      note: "Report says Peraton publishes no TRIR, sustainability report, or fatality data.",
    },
    {
      label: "Injury range",
      value: "55-75/yr",
      note: "BLS-modeled injuries are modest in volume but concentrated in unusual exposure populations.",
    },
  ],
  curveTitle: "Peraton hidden specialty exposure and IPO-readiness curve",
  curveSubtitle:
    "Uploaded Peraton report normalized into entity-profile charts; modeled values should be treated as Occu-Med intelligence assumptions requiring verification with Peraton's actual program data.",
  chartDefinitions: [
    {
      id: "peraton-worker-risk",
      title: "Peraton worker risk by BLS TRIR benchmark",
      subtitle: "Uploaded report: knowledge-worker profile overall, but ground station and DHA/OCONUS populations carry specialty exposure.",
      type: "bar",
      xKey: "category",
      data: [
        { category: "Space & Intel Analysts", workers: 5000, trir: 0.5 },
        { category: "Cyber Mission", workers: 3000, trir: 0.5 },
        { category: "Ground Station Ops", workers: 1000, trir: 2.2 },
        { category: "DHA Health IT OCONUS", workers: 1500, trir: 1.2 },
        { category: "Enterprise IT", workers: 7500, trir: 0.5 },
      ],
      series: [{ dataKey: "trir", name: "BLS TRIR benchmark", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 2.5],
      headline: "worker risk",
      fullWidth: true,
    },
    {
      id: "peraton-segment-headcount",
      title: "Estimated Peraton workforce composition",
      subtitle: "Uploaded report: five primary business populations across 18,000 employees.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "Space & Intelligence", workers: 5000 },
        { segment: "Cyber Mission", workers: 3000 },
        { segment: "Ground Station Ops", workers: 1000 },
        { segment: "DHA Connected Health", workers: 1500 },
        { segment: "Enterprise IT", workers: 7500 },
      ],
      series: [{ dataKey: "workers", name: "Estimated headcount", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "workforce mix",
    },
    {
      id: "peraton-injury-cost-range",
      title: "Modeled annual injury and direct-cost range",
      subtitle: "Uploaded report: modest volume, specialty exposure concentration.",
      type: "grouped",
      xKey: "metric",
      data: [
        { metric: "Recordable injuries", low: 55, high: 75 },
        { metric: "Direct cost ($M)", low: 2.2, high: 4.0 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "injury range",
    },
    {
      id: "peraton-ipo-gap",
      title: "IPO-readiness gap: Peraton vs public peer standards",
      subtitle: "Uploaded report: no public TRIR, sustainability report, or fatality data creates diligence exposure before an S-1.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "TRIR published", peer: 5, peraton: 0 },
        { metric: "Fatality data", peer: 5, peraton: 0 },
        { metric: "Sustainability report", peer: 5, peraton: 0 },
        { metric: "OCONUS medical program", peer: 4, peraton: 1 },
        { metric: "Behavioral health protocol", peer: 3, peraton: 0 },
        { metric: "RF/EMF surveillance", peer: 3, peraton: 0 },
      ],
      series: [
        { dataKey: "peer", name: "Public peer expectation", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "peraton", name: "Peraton current visibility", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      domain: [0, 5],
      headline: "IPO readiness",
      fullWidth: true,
    },
    {
      id: "peraton-specialty-exposure",
      title: "Peraton specialty exposure map",
      subtitle: "The sales opportunity concentrates where standard walk-in occupational medicine does not fit the work.",
      type: "bar",
      xKey: "exposure",
      data: [
        { exposure: "RF/EMF antenna arrays", priority: 10 },
        { exposure: "Classified-work behavioral health", priority: 10 },
        { exposure: "OCONUS DBA baseline", priority: 9 },
        { exposure: "DHA communicable disease", priority: 8 },
        { exposure: "SCIF ergonomics", priority: 7 },
        { exposure: "Data center physical risk", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "specialty exposure",
    },
    {
      id: "peraton-revenue",
      title: "Peraton Occu-Med revenue potential by exam type",
      subtitle: "Prior visual model retained for portfolio comparison; update with Peraton-verified volumes before pricing.",
      type: "bar",
      xKey: "exam",
      data: [
        { exam: "Pre-employment physicals", revenue: 938 },
        { exam: "DBA pre-deploy OCONUS", revenue: 462 },
        { exam: "Behavioral health IC workers", revenue: 1550 },
        { exam: "RF/EMF surveillance", revenue: 155 },
        { exam: "Ergonomic assessments", revenue: 375 },
        { exam: "Audiometry", revenue: 82 },
      ],
      series: [{ dataKey: "revenue", name: "Annual revenue", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "revenue potential",
    },
  ],
  metricDefinitions: [
    { id: "peraton-employees", label: "Employees", value: 18000, unit: "count", category: "workforce" },
    { id: "peraton-revenue", label: "Estimated revenue", value: 8.0, unit: "usd", category: "financial" },
    { id: "peraton-low-injuries", label: "Recordable injuries low", value: 55, unit: "count", category: "safety" },
    { id: "peraton-high-injuries", label: "Recordable injuries high", value: 75, unit: "count", category: "safety" },
    { id: "peraton-direct-cost-low", label: "Direct injury cost low", value: 2.2, unit: "usd", category: "financial" },
    { id: "peraton-direct-cost-high", label: "Direct injury cost high", value: 4.0, unit: "usd", category: "financial" },
    { id: "peraton-ground-station-trir", label: "Ground station TRIR benchmark", value: 2.2, unit: "score", category: "risk" },
    { id: "peraton-revenue-potential", label: "Occu-Med revenue model", value: 3.562, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Ground station RF/EMF", revenue: 155, risk: 9.5, workers: 1000 },
    { name: "IC behavioral health", revenue: 1550, risk: 10.0, workers: 5000 },
    { name: "Cyber mission behavioral health", revenue: 600, risk: 9.0, workers: 3000 },
    { name: "DHA Connected Health OCONUS", revenue: 462, risk: 8.5, workers: 1500 },
    { name: "Enterprise IT ergonomics", revenue: 375, risk: 6.0, workers: 7500 },
  ],
  opportunityMatrix: [
    { name: "Behavioral Health / Clearance-Preservation", revenuePotential: 1550, implementationComplexity: 9, strategicValue: 10 },
    { name: "Pre-Employment Physicals", revenuePotential: 938, implementationComplexity: 4, strategicValue: 8 },
    { name: "DBA Pre-Deploy OCONUS", revenuePotential: 462, implementationComplexity: 6, strategicValue: 10 },
    { name: "Ergonomic Assessments", revenuePotential: 375, implementationComplexity: 5, strategicValue: 7 },
    { name: "RF/EMF Surveillance", revenuePotential: 155, implementationComplexity: 8, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Peraton is a PE-owned national security technology contractor. The uploaded report emphasizes that Peraton's injury count is not remarkable by volume, but its exposure profile is unusual because the highest-value risks sit in classified mission work, antenna-array operations, DHA OCONUS health work, and IPO-readiness visibility gaps.",
      bullets: [
        "Privately held and owned by Veritas Capital.",
        "Headquartered in Reston, Virginia.",
        "Estimated 2024 revenue is about $8.0B.",
        "Estimated workforce is about 18,000 after post-Perspecta rationalization.",
        "The report says Peraton publishes no TRIR, no sustainability report, and no fatality data.",
      ],
      metricIds: ["peraton-employees", "peraton-revenue", "peraton-high-injuries"],
    },
    {
      type: "workforce",
      title: "Five-segment workforce risk model",
      narrative:
        "The uploaded report segments Peraton into Space & Intelligence, Cyber Mission, Ground Station Operations & Technicians, DHA Connected Health OCONUS, and Enterprise IT & Services. The ground-station and DHA lanes produce the highest conventional occupational risk while classified analysts and cyber operators create behavioral-health complexity.",
      bullets: [
        "Space & Intelligence: about 5,000 workers with behavioral-health and ground-station RF/EMF exposure.",
        "Cyber Mission: about 3,000 workers with cyber operations and clearance-preservation behavioral-health risk.",
        "Ground Station Ops & Techs: about 1,000 workers with RF/EMF exposure, falls from antenna arrays, and DBA exposure.",
        "DHA Connected Health OCONUS: about 1,500 workers with communicable disease, OCONUS DBA, and vicarious-trauma exposure.",
        "Enterprise IT & Services: about 7,500 workers with ergonomic CTD and data-center physical risk.",
      ],
      metricIds: ["peraton-ground-station-trir"],
    },
    {
      type: "safety",
      title: "IPO-readiness and public-reporting gap",
      narrative:
        "The uploaded report frames Peraton's private-company reporting posture as a future IPO diligence issue. The readiness problem is that Peraton would need to represent health and safety compliance without public TRIR, fatality, sustainability, OCONUS medical, RF/EMF, or behavioral-health program visibility.",
      bullets: [
        "No public TRIR means Peraton cannot be benchmarked against public peers without internal data.",
        "No public sustainability report or fatality data is normal for PE-backed private status but a gap if IPO planning accelerates.",
        "RF/EMF and pre-deployment medical protocols should be built before diligence questions force the issue.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The profile should not sell generic pre-employment physicals first. The distinctive opportunity is specialty protocols: RF/EMF ophthalmological baseline and exposure assessment, DBA pre-deployment medicals, clearance-preservation behavioral-health screening, SCIF ergonomics, and DHA connected-health surveillance.",
      bullets: [
        "Ground station technicians working near satellite uplink arrays need RF/EMF surveillance and ophthalmological baseline logic.",
        "Classified imaging, SIGINT, and cyber workers need behavioral-health support that respects clearance and classified work-content constraints.",
        "DHA Connected Health OCONUS personnel require communicable disease and pre-deployment baselines.",
        "Enterprise IT and SCIF environments create ergonomic CTD and visual-fatigue lanes.",
      ],
      metricIds: ["peraton-revenue-potential"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "This profile is derived from the uploaded Peraton Occu-Med report and should be treated as modeled strategic intelligence. Validate workforce counts, OCONUS program populations, RF/EMF exposure groups, and IPO timing before using this in outreach or pricing.",
      bullets: [
        "Do not present the injury range as Peraton-published TRIR; the report says Peraton publishes no TRIR.",
        "The RF/EMF and behavioral-health claims are opportunity theses requiring program confirmation.",
        "Preserve Veritas/private-company/IPO-readiness framing because that is the account-opening logic.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "deep-analysis",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
