import type { CompanyConfig } from "./types";

export const peratonConfig: CompanyConfig = {
  companyId: "peraton",
  displayName: "Peraton",
  shortName: "Peraton",
  sector: "Space, intelligence, cyber, defense, classified programs, health IT, and government mission support",
  headquarters: "Herndon, Virginia",
  employees: 33000,
  employeesAsOf: "2025 estimate",
  summary: "Peraton is framed as a Space & Intel dominant private company with IPO-readiness maturity gaps, high-clearance workforce concentration, and occupational-health revenue potential across pre-employment, DBA, behavioral health, RF/EMF, ergonomic, and audiometric exam lanes.",
  tags: ["Space & Intel", "IPO readiness", "Classified workforce", "Behavioral health", "DBA", "RF/EMF"],
  aliases: ["Peraton Inc"],
  executiveSignals: [
    { label: "Revenue potential", value: "$3.562M/yr", note: "Total modeled Occu-Med opportunity across exam types." },
    { label: "Classified awards", value: "$1.15B", note: "2024 classified awards remain above $1B." },
    { label: "IPO gap", value: "0/5 maturity", note: "No public TRIR, fatality, or sustainability reporting." },
    { label: "Worker risk peak", value: "TRIR 2.2", note: "Ground station ops and techs carry highest risk." },
  ],
  curveTitle: "Peraton intelligence and opportunity curve",
  curveSubtitle: "Classified awards, IPO-readiness gaps, revenue potential, and worker-risk segmentation normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "peraton-classified",
      title: "Peraton Space & Intel: Annual classified awards",
      subtitle: "Source: uploaded Peraton visual; classified awards remain above $1B in 2023 and 2024.",
      type: "bar",
      xKey: "year",
      data: [{ year: "2022", awards: 0.36 }, { year: "2023", awards: 1.2 }, { year: "2024", awards: 1.15 }],
      series: [{ dataKey: "awards", name: "Classified Awards", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      domain: [0, 1.3],
      headline: "classified awards",
    },
    {
      id: "peraton-ipo-gap",
      title: "IPO-readiness gap: Peraton vs public peer standards",
      subtitle: "Source: uploaded Peraton ESG/safety maturity visual; public-peer maturity compared with current Peraton visibility.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "TRIR Published?", peer: 5, peraton: 0 },
        { metric: "Fatality Data Published?", peer: 5, peraton: 0 },
        { metric: "Sustainability Report?", peer: 5, peraton: 0 },
        { metric: "Occ Med Program Docs?", peer: 4, peraton: 1 },
        { metric: "Behavioral Health Protocol?", peer: 2, peraton: 0 },
        { metric: "RF/EMF Surveillance?", peer: 3, peraton: 0 },
      ],
      series: [
        { dataKey: "peer", name: "Public Peer Avg", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "peraton", name: "Peraton Current", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      domain: [0, 5],
      headline: "IPO readiness",
    },
    {
      id: "peraton-revenue",
      title: "Peraton: Occu-Med revenue potential by exam type",
      subtitle: "Source: uploaded Peraton model; total modeled opportunity approximately $3.562M per year.",
      type: "bar",
      xKey: "exam",
      data: [
        { exam: "Pre-Employment Physicals", revenue: 938 },
        { exam: "DBA Pre-Deploy OCONUS", revenue: 462 },
        { exam: "Behavioral Health IC Workers", revenue: 1550 },
        { exam: "RF/EMF Surveillance", revenue: 155 },
        { exam: "Ergonomic Assessments", revenue: 375 },
        { exam: "Audiometry", revenue: 82 },
      ],
      series: [{ dataKey: "revenue", name: "Annual Revenue", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "revenue potential",
    },
    {
      id: "peraton-revenue-build",
      title: "Peraton revenue build-up: 2017-2024",
      subtitle: "Source: uploaded Peraton visual; Perspecta acquisition creates the largest scale jump.",
      type: "area",
      xKey: "year",
      data: [{ year: "2017", revenue: 0.7 }, { year: "2019", revenue: 1.5 }, { year: "2021", revenue: 7.1 }, { year: "2022", revenue: 7.4 }, { year: "2024", revenue: 8.1 }],
      series: [{ dataKey: "revenue", color: "#38bdf8" }],
      formatter: "currencyM",
      domain: [0, 9],
      headline: "revenue build",
    },
    {
      id: "peraton-worker-risk",
      title: "Peraton worker risk by BLS TRIR benchmark",
      subtitle: "Source: uploaded Peraton visual; benchmarked TRIR by worker category.",
      type: "bar",
      xKey: "category",
      data: [
        { category: "Space & Intel Analysts", trir: 0.5 },
        { category: "Cyber Mission", trir: 0.5 },
        { category: "Ground Station Ops & Techs", trir: 2.2 },
        { category: "DHA Health IT OCONUS", trir: 1.2 },
        { category: "Enterprise IT", trir: 0.5 },
      ],
      series: [{ dataKey: "trir", name: "BLS TRIR", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "worker risk",
      fullWidth: true,
    },
  ],
};
