import type { CompanyConfig } from "./types";

export const perfectCoverageProspectsConfig: CompanyConfig = {
  companyId: "perfect-coverage-prospects",
  displayName: "Perfect Coverage Prospect Intelligence",
  shortName: "Perfect Coverage",
  sector:
    "Prospect targeting, clinic-coverage overlap, defense/federal sales prioritization, provider-network leverage, Chase outreach cards, 100% coverage prospects, and near-perfect coverage opportunities",
  headquarters: "Occu-Med portfolio-level prospect and coverage analysis",
  employees: 0,
  employeesAsOf:
    "Uploaded perfect-coverage research: seven 100% coverage prospects plus five near-perfect 90-96% prospects extracted from the provided table",
  summary:
    "Perfect Coverage Prospect Intelligence converts the uploaded perfect-coverage research into an action profile for Chase. The report identifies seven companies where every listed location is already served by existing Occu-Med network/client coverage: Bodwe Professional Services Group, The Source Group, Tecmotiv, MITRE, Crowley Government Services, Guidehouse, and Skanska USA Civil. It also flags near-perfect coverage targets: Walsh Federal at 27/28 locations, Leidos at 57/61, KBR at 35/38, Maximus Federal at 30/33, and SAIC at 46/51. The sales logic is simple: instead of first building clinics and then selling, Occu-Med can lead with proof that coverage already exists. The top outreach target is Bodwe because the report frames it as a fast-growing federal services prospect with expeditionary logistics and DHA relevance. Tecmotiv is already represented as a high-specificity surveillance profile in this PR. Walsh Federal is the highest near-perfect construction target, while Maximus requires a strategic partner-versus-competitor review because it already operates a massive VA disability examination provider network.",
  tags: [
    "Entity profile",
    "Perfect coverage",
    "Prospect targeting",
    "Chase outreach",
    "Bodwe",
    "The Source Group",
    "Tecmotiv",
    "MITRE",
    "Crowley Government Services",
    "Guidehouse",
    "Skanska USA Civil",
    "Walsh Federal",
    "Leidos expansion",
    "KBR",
    "Maximus flag",
    "SAIC",
  ],
  aliases: ["Perfect Coverage", "Coverage Overlap Prospects", "Sign Here Prospects", "Zero Ramp Up Prospects"],
  sourceFilters: {
    newsSources: { aliases: ["Occu-Med perfect coverage prospects", "Bodwe NAVSUP expeditionary logistics", "Walsh Federal NAVFAC MATOC"] },
  },
  executiveSignals: [
    { label: "Perfect coverage", value: "7 prospects", note: "Every listed location is already covered for seven prospects in the uploaded table." },
    { label: "Near-perfect", value: "5 prospects", note: "Walsh, Leidos, KBR, Maximus Federal, and SAIC are 90-96% covered in the table." },
    { label: "Best cold target", value: "Bodwe", note: "The report labels Bodwe Professional Services Group as the single best prospect in the dataset." },
    { label: "Strategic flag", value: "Maximus", note: "Maximus could be a referral partner or competitive threat because it operates a very large exam network." },
  ],
  curveTitle: "Perfect-coverage prospect, near-perfect gap, and Chase outreach curve",
  curveSubtitle:
    "Uploaded perfect-coverage research normalized into a portfolio profile. Coverage counts should be verified against current clinic network and actual prospect worksite list before external pitch use.",
  chartDefinitions: [
    {
      id: "perfect-coverage-prospects",
      title: "100% coverage prospects",
      subtitle: "These prospects have every listed location already served by existing Occu-Med network/client coverage.",
      type: "bar",
      xKey: "prospect",
      data: [
        { prospect: "Bodwe", covered: 24, total: 24 },
        { prospect: "The Source Group", covered: 24, total: 24 },
        { prospect: "Tecmotiv", covered: 23, total: 23 },
        { prospect: "MITRE", covered: 6, total: 6 },
        { prospect: "Crowley Gov", covered: 4, total: 4 },
        { prospect: "Guidehouse", covered: 4, total: 4 },
        { prospect: "Skanska USA Civil", covered: 4, total: 4 },
      ],
      series: [{ dataKey: "covered", name: "Covered locations", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "100% coverage",
      fullWidth: true,
    },
    {
      id: "perfect-coverage-conus-oconus",
      title: "CONUS / OCONUS mix for perfect-coverage targets",
      subtitle: "Bodwe, The Source Group, and Tecmotiv are more powerful because they include OCONUS coverage, not only domestic office coverage.",
      type: "stacked",
      xKey: "prospect",
      data: [
        { prospect: "Bodwe", conus: 10, oconus: 14 },
        { prospect: "The Source Group", conus: 10, oconus: 14 },
        { prospect: "Tecmotiv", conus: 10, oconus: 13 },
        { prospect: "MITRE", conus: 6, oconus: 0 },
        { prospect: "Crowley Gov", conus: 4, oconus: 0 },
        { prospect: "Guidehouse", conus: 4, oconus: 0 },
        { prospect: "Skanska USA Civil", conus: 4, oconus: 0 },
      ],
      series: [
        { dataKey: "conus", name: "CONUS", color: "#22d3ee", stackId: "coverage" },
        { dataKey: "oconus", name: "OCONUS", color: "#ef4444", stackId: "coverage", radius: [10, 10, 0, 0] },
      ],
      headline: "coverage mix",
      fullWidth: true,
    },
    {
      id: "near-perfect-coverage",
      title: "Near-perfect coverage prospects",
      subtitle: "Tiny gaps should not block sales outreach; these are account-management or gap-closure opportunities.",
      type: "bar",
      xKey: "prospect",
      data: [
        { prospect: "Walsh Federal", coverage: 96, examsLow: 80, examsHigh: 150 },
        { prospect: "Leidos", coverage: 93, examsLow: 200, examsHigh: 400 },
        { prospect: "KBR", coverage: 92, examsLow: 300, examsHigh: 500 },
        { prospect: "Maximus Federal", coverage: 91, examsLow: 0, examsHigh: 0 },
        { prospect: "SAIC", coverage: 90, examsLow: 200, examsHigh: 350 },
      ],
      series: [{ dataKey: "coverage", name: "Coverage %", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [80, 100],
      headline: "near-perfect",
    },
    {
      id: "chase-call-priority",
      title: "Chase Monday call priority",
      subtitle: "Bodwe, Tecmotiv, and Walsh are the most actionable first calls from the uploaded analysis.",
      type: "bar",
      xKey: "target",
      data: [
        { target: "Bodwe", priority: 10 },
        { target: "Tecmotiv", priority: 9 },
        { target: "Walsh Federal", priority: 9 },
        { target: "The Source Group", priority: 8 },
        { target: "KBR", priority: 8 },
        { target: "SAIC", priority: 7 },
        { target: "Maximus review", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Call priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "Chase calls",
    },
    {
      id: "coverage-sales-logic",
      title: "Coverage-first sales logic",
      subtitle: "The pitch changes when Occu-Med can say the network is already there.",
      type: "bar",
      xKey: "message",
      data: [
        { message: "No ramp-up", priority: 10 },
        { message: "No clinic vetting", priority: 10 },
        { message: "OCONUS coverage proof", priority: 9 },
        { message: "Existing client overlap", priority: 9 },
        { message: "Fast launch", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Message strength", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "sales logic",
    },
  ],
  metricDefinitions: [
    { id: "coverage-perfect-count", label: "100% coverage prospects", value: 7, unit: "count", category: "financial" },
    { id: "coverage-near-perfect-count", label: "90-96% prospects", value: 5, unit: "count", category: "financial" },
    { id: "coverage-bodwe-locations", label: "Bodwe covered locations", value: 24, unit: "count", category: "workforce" },
    { id: "coverage-source-group-locations", label: "Source Group covered locations", value: 24, unit: "count", category: "workforce" },
    { id: "coverage-tecmotiv-locations", label: "Tecmotiv covered locations", value: 23, unit: "count", category: "workforce" },
    { id: "coverage-walsh-percent", label: "Walsh coverage", value: 96, unit: "percent", category: "financial" },
  ],
  riskMatrix: [
    { name: "Bodwe", revenue: 24, risk: 9.0, workers: 500 },
    { name: "Tecmotiv", revenue: 23, risk: 9.0, workers: 150 },
    { name: "Walsh Federal", revenue: 27, risk: 8.5, workers: 700 },
    { name: "KBR expansion", revenue: 35, risk: 8.0, workers: 5000 },
    { name: "Maximus strategic review", revenue: 30, risk: 9.5, workers: 3000 },
  ],
  opportunityMatrix: [
    { name: "Bodwe Outreach", revenuePotential: 225, implementationComplexity: 3, strategicValue: 10 },
    { name: "Tecmotiv Surveillance Pitch", revenuePotential: 90, implementationComplexity: 4, strategicValue: 9 },
    { name: "Walsh Federal MATOC Pitch", revenuePotential: 150, implementationComplexity: 5, strategicValue: 9 },
    { name: "KBR Account Expansion", revenuePotential: 500, implementationComplexity: 7, strategicValue: 8 },
    { name: "Maximus Partner/Competitor Review", revenuePotential: 0, implementationComplexity: 8, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Coverage-first prospect strategy",
      narrative:
        "This file gives Chase a different type of sales list. These are not just attractive companies; they are companies whose listed locations are already covered by Occu-Med's existing network or existing client coverage footprint.",
      bullets: [
        "Seven prospects are listed at 100% coverage.",
        "Five additional prospects are listed at 90-96% coverage.",
        "The strongest pitch is operational readiness: no ramp-up, no new clinic vetting, and immediate launch potential.",
        "This profile should be used with the referral-demand and network-expansion profiles, not in isolation.",
      ],
      metricIds: ["coverage-perfect-count", "coverage-near-perfect-count"],
    },
    {
      type: "medical-opportunities",
      title: "The three first calls",
      narrative:
        "The uploaded analysis names Bodwe, Tecmotiv, and Walsh Federal as Chase's highest-priority first calls. Bodwe is the best cold prospect, Tecmotiv has specialty surveillance need, and Walsh is a near-perfect construction/MATOC target.",
      bullets: [
        "Bodwe: expeditionary logistics and DHA relevance with 24/24 listed locations covered.",
        "Tecmotiv: military vehicle overhaul and high-specificity occupational surveillance with 23/23 listed locations covered.",
        "Walsh Federal: 27/28 coverage and a Navy construction MATOC angle.",
      ],
      metricIds: ["coverage-bodwe-locations", "coverage-tecmotiv-locations", "coverage-walsh-percent"],
    },
    {
      type: "competitors",
      title: "Important flags before outreach",
      narrative:
        "Two categories require care: existing clients should be treated as expansion/account-management conversations, and Maximus should be researched before outreach because it may be a partner or competitor depending on its occupational-health strategy.",
      bullets: [
        "Leidos and Valiant-related opportunities should be handled as existing relationship expansion, not cold outreach.",
        "Maximus Federal is flagged as special because its large medical examination network could make it a referral partner or a competitor.",
        "KBR and SAIC are strong coverage targets but need account-specific messaging rather than a generic pitch.",
      ],
      metricIds: [],
    },
  ],
};
