import type { CompanyConfig } from "./types";

export const prospectPipelineIntelligenceConfig: CompanyConfig = {
  companyId: "prospect-pipeline-intelligence",
  displayName: "Prospect Pipeline Intelligence",
  shortName: "Prospect Pipeline",
  sector:
    "Potential client discovery, defense contractor targeting, healthcare staffing prospects, logistics and environmental targets, OCONUS medical support, TRICARE network-adjacent targets, and occupational-health sales prioritization",
  headquarters: "Occu-Med portfolio-level business development strategy",
  employees: 0,
  employeesAsOf: "Uploaded Potential Clients for Occu-Med Beyond Current Contractor List report: 2025-2026 candidate universe",
  summary:
    "Prospect Pipeline Intelligence converts the uploaded potential-client report into a structured entity profile. The report identifies new Occu-Med client opportunities beyond the current contractor list across large prime defense contractors, mid-tier defense and aerospace firms, healthcare staffing firms, medical readiness providers, OCONUS/global health contractors, TRICARE-adjacent administrators, environmental/industrial hygiene targets, medical simulation and training programs, digital health partners, construction/facility support firms, and emerging IT/health-IT contractors. The key insight is that the prospect list should not be treated as one flat sales list. Each segment has a different occupational-health wedge: manufacturing and test surveillance for primes, hazardous-materials and warehousing exams for logistics firms, clinical staffing and credentialing for DHA vendors, DBA/pre-deployment for OCONUS medical partners, provider-network coordination for TRICARE administrators, and industrial hygiene/medical surveillance for environmental and construction firms.",
  tags: [
    "Entity profile",
    "Prospect pipeline",
    "New client opportunities",
    "Defense primes",
    "Healthcare staffing",
    "OCONUS contractors",
    "TRICARE administrators",
    "Industrial hygiene",
    "Medical readiness",
    "Construction facilities",
    "Sales prioritization",
  ],
  aliases: [
    "Potential Clients",
    "Prospect Intelligence",
    "Occu-Med Sales Pipeline",
    "Client Discovery",
    "Beyond Current Contractor List",
  ],
  sourceFilters: {
    newsSources: {
      aliases: [
        "Potential Clients for Occu-Med",
        "defense contractor occupational health prospects",
        "DHA medical staffing contractors",
        "TRICARE provider network contractors",
      ],
    },
  },
  executiveSignals: [
    {
      label: "Pipeline categories",
      value: "15+",
      note: "The uploaded report segments prospects across primes, mid-tier firms, healthcare staffing, OCONUS health, TRICARE, simulation/training, construction, and health IT.",
    },
    {
      label: "Large primes",
      value: "9",
      note: "Lockheed Martin, Northrop Grumman, RTX, Boeing, Parsons, SAIC, KBR, Serco, and ULA are listed as large-prime opportunity targets.",
    },
    {
      label: "Healthcare/DHA vendors",
      value: "15+",
      note: "The report lists multiple medical staffing, DHA, military health, and provider-network contractors as direct or adjacent prospects.",
    },
    {
      label: "Highest new wedge",
      value: "Segmented targeting",
      note: "The useful insight is not the names alone; it is matching each prospect class to the correct Occu-Med service wedge.",
    },
  ],
  curveTitle: "Occu-Med prospect pipeline and service-wedge curve",
  curveSubtitle:
    "Uploaded potential-client report normalized into an entity-profile view. Candidate lists should be validated against existing client status before outreach.",
  chartDefinitions: [
    {
      id: "prospect-category-map",
      title: "Prospect universe by target category",
      subtitle: "Candidate counts are grouped from the uploaded report sections; several aggregate sections contain multiple vendors.",
      type: "bar",
      xKey: "category",
      data: [
        { category: "Large defense primes", count: 9 },
        { category: "Mid-tier logistics/environmental", count: 8 },
        { category: "Healthcare staffing / DHA", count: 17 },
        { category: "OCONUS/global health", count: 4 },
        { category: "TRICARE/admin networks", count: 2 },
        { category: "Simulation/training/digital health", count: 3 },
        { category: "Construction / facilities / health IT", count: 4 },
      ],
      series: [{ dataKey: "count", name: "Prospect count", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "pipeline map",
      fullWidth: true,
    },
    {
      id: "prime-targets",
      title: "Large-prime opportunity targets",
      subtitle: "The uploaded report lists these as major defense/government-contracting prospects; several already have profile coverage elsewhere in the app.",
      type: "bar",
      xKey: "entity",
      data: [
        { entity: "Lockheed Martin", priority: 10 },
        { entity: "Boeing", priority: 10 },
        { entity: "ULA", priority: 8 },
        { entity: "Northrop", priority: 8 },
        { entity: "RTX", priority: 8 },
        { entity: "Parsons", priority: 7 },
        { entity: "SAIC", priority: 7 },
        { entity: "KBR", priority: 7 },
        { entity: "Serco", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Sales priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "large primes",
    },
    {
      id: "healthcare-dha-targets",
      title: "Healthcare staffing and DHA prospect cluster",
      subtitle: "Medical staffing and military-health vendors align directly with credentialing, readiness, staffing, and occupational health support.",
      type: "bar",
      xKey: "target",
      data: [
        { target: "Advancia", priority: 8 },
        { target: "CentralCare", priority: 8 },
        { target: "Millennium H&F", priority: 8 },
        { target: "Eagle Integrated", priority: 7 },
        { target: "Maxmed", priority: 7 },
        { target: "Great Hill", priority: 7 },
        { target: "Distinctive Spectrum", priority: 7 },
        { target: "Loyal Source", priority: 9 },
        { target: "Spectrum Healthcare", priority: 9 },
        { target: "The Arora Group", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med fit", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "DHA cluster",
      fullWidth: true,
    },
    {
      id: "logistics-environmental-targets",
      title: "Logistics, environmental, and facility-service targets",
      subtitle: "These candidates are not glamorous, but their worker populations create practical occupational-health demand.",
      type: "bar",
      xKey: "target",
      data: [
        { target: "Applied Solutions Logistics", priority: 8 },
        { target: "The Source Group", priority: 8 },
        { target: "Bodwé / Seven Generations", priority: 8 },
        { target: "Tecmotiv", priority: 7 },
        { target: "TOTE Services", priority: 8 },
        { target: "ECC", priority: 9 },
        { target: "Walsh Federal", priority: 8 },
        { target: "Monterey Technologies", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med fit", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "practical targets",
    },
    {
      id: "service-wedge-map",
      title: "Best Occu-Med service wedge by prospect class",
      subtitle: "The report is most useful when each prospect class is tied to a specific medical sales lane.",
      type: "bar",
      xKey: "wedge",
      data: [
        { wedge: "Manufacturing surveillance", priority: 10 },
        { wedge: "DHA staffing/credentialing", priority: 10 },
        { wedge: "DBA / OCONUS readiness", priority: 9 },
        { wedge: "Industrial hygiene", priority: 9 },
        { wedge: "Provider-network admin", priority: 8 },
        { wedge: "Medical simulation/training", priority: 7 },
        { wedge: "Construction/facility FFD", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Strategic fit", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "service wedge",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "prospect-large-primes", label: "Large-prime prospects", value: 9, unit: "count", category: "workforce" },
    { id: "prospect-healthcare-vendors", label: "Healthcare/DHA vendors", value: 17, unit: "count", category: "workforce" },
    { id: "prospect-mid-tier-targets", label: "Mid-tier practical targets", value: 8, unit: "count", category: "workforce" },
    { id: "prospect-total-categories", label: "Pipeline categories", value: 15, unit: "count", category: "workforce" },
    { id: "prospect-priority-score", label: "Segmented targeting value", value: 10, unit: "score", category: "financial" },
  ],
  riskMatrix: [
    { name: "Healthcare staffing / DHA", revenue: 17, risk: 8.5, workers: 10000 },
    { name: "Large primes", revenue: 9, risk: 8.0, workers: 100000 },
    { name: "Logistics/environmental", revenue: 8, risk: 9.0, workers: 5000 },
    { name: "OCONUS/global health", revenue: 4, risk: 9.5, workers: 5000 },
    { name: "TRICARE networks", revenue: 2, risk: 6.0, workers: 1000 },
  ],
  opportunityMatrix: [
    { name: "Healthcare/DHA Vendor Outreach", revenuePotential: 17, implementationComplexity: 6, strategicValue: 10 },
    { name: "Lockheed / Boeing / ULA Prime Push", revenuePotential: 9, implementationComplexity: 9, strategicValue: 10 },
    { name: "Environmental / IH Targets", revenuePotential: 8, implementationComplexity: 6, strategicValue: 9 },
    { name: "OCONUS Health Partner Channel", revenuePotential: 4, implementationComplexity: 8, strategicValue: 9 },
    { name: "TRICARE Network-Admin Channel", revenuePotential: 2, implementationComplexity: 9, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "What this prospect report should become inside Insight Hub",
      narrative:
        "The uploaded report should not sit as a static PDF. It should become a prospect taxonomy that separates who to target, why they fit, which Occu-Med service lane applies, and whether the app already has a profile for that entity.",
      bullets: [
        "Large primes require manufacturing, test, sustainment, deployment, and industrial-hygiene surveillance arguments.",
        "Healthcare staffing and DHA vendors require credentialing, readiness, staffing, medical admin, and occupational-health support arguments.",
        "OCONUS/global health and TRICARE-adjacent targets require network coordination, DBA, medical readiness, and claims/admin logic.",
        "Environmental, logistics, construction, and facility firms create more immediate practical exam demand than some higher-profile primes.",
      ],
      metricIds: ["prospect-total-categories", "prospect-priority-score"],
    },
    {
      type: "competitors",
      title: "Targets already covered versus new targets",
      narrative:
        "Several names in the uploaded report already have current Insight Hub profiles or profile work in PR #24. The value of this new profile is to surface the uncovered targets and prevent duplicate work.",
      bullets: [
        "Already covered or partially covered in this PR: Northrop, RTX, Parsons, SAIC, KBR, Serco, Leidos, Maximus, Peckham, and related defense primes.",
        "High-value uncovered large-prime targets include Lockheed Martin, Boeing, and United Launch Alliance.",
        "High-value uncovered practical targets include Applied Solutions Logistics, The Source Group, Bodwé/Seven Generations, Tecmotiv, TOTE Services, ECC, Walsh Federal, and Monterey Technologies.",
      ],
      metricIds: ["prospect-large-primes", "prospect-mid-tier-targets"],
    },
    {
      type: "medical-opportunities",
      title: "Service-wedge matching",
      narrative:
        "Each category needs its own outreach message. Sending the same occupational-health pitch to Boeing, TriWest, ECC, and Loyal Source would waste the useful structure of the report.",
      bullets: [
        "Large primes: manufacturing surveillance, test-site medicine, respiratory/hearing, and deployment readiness.",
        "Healthcare staffing/DHA vendors: credentialing, staffing support, health screenings, readiness workflows, and program support.",
        "Logistics/environmental/construction targets: hazmat, respirator clearance, HAZWOPER, DOT/CDL, heat, fit-for-duty, and injury-management support.",
        "OCONUS/TRICARE/admin targets: provider network, DBA, claims workflow, medical coordination, and international readiness.",
      ],
      metricIds: ["prospect-healthcare-vendors"],
    },
  ],
};
