import type { CompanyConfig } from "./types";

export const prospectNetworkIntelligenceConfig: CompanyConfig = {
  companyId: "prospect-network-intelligence",
  displayName: "Prospect Network Intelligence",
  shortName: "Prospect Network",
  sector:
    "Prospect location density, prospect-client overlap, 135 strategic prospect locations, 160 overlap locations, Northern Virginia corridor, OCONUS prospect clusters, sales targeting, and network-coverage prioritization",
  headquarters: "Occu-Med prospect network research layer",
  employees: 0,
  employeesAsOf:
    "Uploaded prospect network report: 135 strategic prospect locations and 160 prospect/client overlap locations across 30+ countries",
  summary:
    "Prospect Network Intelligence captures the uploaded prospect-location and overlap report. The report identifies 135 strategic prospect locations across 30+ countries and 160 cities where prospects and existing clients co-locate. The highest-density prospect cities are San Diego, Huntsville, Arlington, Washington DC, Chantilly, Doha, Abu Dhabi, Colorado Springs, Norfolk, Riyadh, Tampa, Los Angeles, Jacksonville, London, Singapore, and Stuttgart. The overlap table is even more important for sales execution: San Diego combines 26 prospects and 12 clients, Huntsville combines 20 prospects and 14 clients, Arlington combines 19 prospects and 11 clients, Chantilly combines 15 prospects and 11 clients, and Washington DC combines 16 prospects and 9 clients. The report's core point is that one converted prospect can become a beachhead for many more at the same location.",
  tags: [
    "Entity profile",
    "Prospect network",
    "135 locations",
    "160 overlap locations",
    "San Diego",
    "Huntsville",
    "Arlington",
    "Chantilly",
    "Doha",
    "Abu Dhabi",
    "Stuttgart",
    "Northern Virginia corridor",
    "Client overlap",
    "Prospect density",
    "Network targeting",
  ],
  aliases: ["Prospect Network", "Prospect Overlap", "135 Prospect Locations", "160 Overlap Locations"],
  sourceFilters: {
    newsSources: { aliases: ["Occu-Med prospect network intelligence", "prospect location overlap", "defense contractor prospect overlap"] },
  },
  executiveSignals: [
    { label: "Prospect locations", value: "135", note: "Uploaded report includes every city with two or more prospect companies." },
    { label: "Overlap cities", value: "160", note: "Report maps prospect/client co-location cities for sales targeting." },
    { label: "Top density", value: "San Diego 38", note: "San Diego combines 26 prospects and 12 existing clients." },
    { label: "NoVA corridor", value: "65+ instances", note: "Arlington, Chantilly, Herndon, Reston, McLean, and Falls Church form a single corridor cluster." },
  ],
  curveTitle: "Prospect density, client overlap, and sales-beachhead curve",
  curveSubtitle:
    "Uploaded prospect network report normalized into a portfolio profile. Counts are strategic source-report values and should be verified before campaign execution.",
  chartDefinitions: [
    {
      id: "tier-one-prospect-locations",
      title: "Tier 1 critical prospect locations",
      subtitle: "Locations with 10+ prospect companies from the uploaded report.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "San Diego", prospects: 26 },
        { location: "Huntsville", prospects: 20 },
        { location: "Arlington", prospects: 19 },
        { location: "Washington DC", prospects: 16 },
        { location: "Chantilly", prospects: 15 },
        { location: "Doha", prospects: 15 },
        { location: "Abu Dhabi", prospects: 14 },
        { location: "Colorado Springs", prospects: 14 },
        { location: "Norfolk", prospects: 14 },
        { location: "Riyadh", prospects: 13 },
        { location: "Tampa", prospects: 12 },
        { location: "Los Angeles", prospects: 11 },
        { location: "Jacksonville", prospects: 11 },
        { location: "London", prospects: 10 },
        { location: "Singapore", prospects: 10 },
        { location: "Stuttgart", prospects: 10 },
      ],
      series: [{ dataKey: "prospects", name: "Prospects", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "tier 1 locations",
      fullWidth: true,
    },
    {
      id: "prospect-client-overlap-mega-clusters",
      title: "Mega-cluster overlap locations",
      subtitle: "Cities where prospect density and existing client presence combine into the strongest sales-beachhead opportunities.",
      type: "grouped",
      xKey: "location",
      data: [
        { location: "San Diego", prospects: 26, clients: 12, combined: 38 },
        { location: "Huntsville", prospects: 20, clients: 14, combined: 34 },
        { location: "Arlington", prospects: 19, clients: 11, combined: 30 },
        { location: "Chantilly", prospects: 15, clients: 11, combined: 26 },
        { location: "Washington DC", prospects: 16, clients: 9, combined: 25 },
        { location: "Colorado Springs", prospects: 14, clients: 9, combined: 23 },
        { location: "London", prospects: 10, clients: 13, combined: 23 },
        { location: "Norfolk", prospects: 14, clients: 8, combined: 22 },
        { location: "Doha", prospects: 15, clients: 6, combined: 21 },
        { location: "Abu Dhabi", prospects: 14, clients: 6, combined: 20 },
      ],
      series: [
        { dataKey: "prospects", name: "Prospects", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "clients", name: "Clients", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "overlap clusters",
      fullWidth: true,
    },
    {
      id: "prospect-tier-counts",
      title: "Prospect location tier counts",
      subtitle: "The report organizes 135 locations into four prospect-density tiers.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "Critical: 10+ prospects", locations: 16 },
        { tier: "High: 6-9 prospects", locations: 26 },
        { tier: "Significant: 4-5 prospects", locations: 28 },
        { tier: "Moderate: 2-3 prospects", locations: 65 },
      ],
      series: [{ dataKey: "locations", name: "Locations", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "tier counts",
    },
    {
      id: "no-va-corridor",
      title: "Northern Virginia corridor concentration",
      subtitle: "Arlington + Chantilly + Herndon + Reston + McLean + Falls Church behave like one super-cluster.",
      type: "bar",
      xKey: "node",
      data: [
        { node: "Arlington", score: 30 },
        { node: "Chantilly", score: 26 },
        { node: "Herndon", score: 18 },
        { node: "Reston", score: 16 },
        { node: "McLean", score: 11 },
        { node: "Falls Church", score: 12 },
      ],
      series: [{ dataKey: "score", name: "Combined density", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      headline: "NoVA corridor",
    },
    {
      id: "oconus-sales-beachheads",
      title: "OCONUS prospect beachheads",
      subtitle: "High-density OCONUS locations deserve provider/network verification before sales campaigns.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Doha Qatar", prospects: 15 },
        { location: "Abu Dhabi UAE", prospects: 14 },
        { location: "Riyadh Saudi Arabia", prospects: 13 },
        { location: "London UK", prospects: 10 },
        { location: "Singapore", prospects: 10 },
        { location: "Stuttgart Germany", prospects: 10 },
        { location: "Camp Arifjan Kuwait", prospects: 9 },
        { location: "Madrid Spain", prospects: 9 },
        { location: "Tokyo Japan", prospects: 8 },
      ],
      series: [{ dataKey: "prospects", name: "Prospects", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "OCONUS targets",
    },
  ],
  metricDefinitions: [
    { id: "prospect-network-locations", label: "Strategic prospect locations", value: 135, unit: "count", category: "workforce" },
    { id: "prospect-network-overlap", label: "Prospect/client overlap locations", value: 160, unit: "count", category: "workforce" },
    { id: "prospect-network-tier1", label: "Critical 10+ prospect locations", value: 16, unit: "count", category: "financial" },
    { id: "prospect-network-san-diego-total", label: "San Diego combined density", value: 38, unit: "count", category: "financial" },
    { id: "prospect-network-huntsville-total", label: "Huntsville combined density", value: 34, unit: "count", category: "financial" },
  ],
  riskMatrix: [
    { name: "San Diego", revenue: 38, risk: 8.0, workers: 38 },
    { name: "Huntsville", revenue: 34, risk: 8.5, workers: 34 },
    { name: "NoVA corridor", revenue: 65, risk: 7.0, workers: 65 },
    { name: "Doha / Qatar", revenue: 21, risk: 9.0, workers: 21 },
    { name: "Stuttgart / Germany", revenue: 18, risk: 8.5, workers: 18 },
  ],
  opportunityMatrix: [
    { name: "San Diego Beachhead", revenuePotential: 38, implementationComplexity: 5, strategicValue: 10 },
    { name: "Huntsville Defense Cluster", revenuePotential: 34, implementationComplexity: 5, strategicValue: 10 },
    { name: "NoVA Corridor Campaign", revenuePotential: 65, implementationComplexity: 4, strategicValue: 10 },
    { name: "Doha / Qatar OCONUS Coverage", revenuePotential: 21, implementationComplexity: 8, strategicValue: 9 },
    { name: "Stuttgart Provider Verification", revenuePotential: 18, implementationComplexity: 7, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "What the prospect network report proves",
      narrative:
        "The uploaded report is not just a prospect list. It is a location-density and overlap map showing where one provider/network investment or one converted account can support many sales targets.",
      bullets: [
        "135 strategic prospect locations were identified across 30+ countries.",
        "160 overlap locations connect prospects to existing Occu-Med clients.",
        "San Diego, Huntsville, Arlington, Chantilly, Washington DC, London, Doha, and Abu Dhabi are the strongest combined-density hubs.",
      ],
      metricIds: ["prospect-network-locations", "prospect-network-overlap"],
    },
    {
      type: "medical-opportunities",
      title: "Sales execution logic",
      narrative:
        "Any one converted prospect in a dense market becomes proof for the rest. The app should show prospects, existing clients, current provider coverage, service wedge, and next action on the same city card.",
      bullets: [
        "NoVA should be treated as a corridor, not six separate cities.",
        "San Diego and Huntsville are the strongest CONUS prospect/client overlap targets.",
        "Doha, Abu Dhabi, Riyadh, Stuttgart, Singapore, London, and Camp Arifjan require provider verification before aggressive outreach.",
      ],
      metricIds: ["prospect-network-san-diego-total", "prospect-network-huntsville-total"],
    },
  ],
};
