import type { CompanyConfig } from "./types";

export const qinetiqConfig: CompanyConfig = {
  companyId: "qinetiq",
  displayName: "QinetiQ Group plc",
  shortName: "QinetiQ",
  sector:
    "Sovereign test, trials, training and evaluation infrastructure; advanced defense technology; robotics; directed energy; autonomy; maritime systems; and mission support",
  headquarters: "Farnborough, United Kingdom / Reston, Virginia (US HQ)",
  employees: 8500,
  employeesAsOf: "Uploaded research report: FY25 / 2025 public estimate",
  summary:
    "QinetiQ Group plc is a UK-headquartered defense technology entity created from the privatization of the Defence Evaluation and Research Agency. The uploaded research report frames QinetiQ as the custodian of the UK's sovereign Test, Trials, Training and Evaluation infrastructure under the Long Term Partnering Agreement, with global growth centered on the United States, Australia, Germany, Belgium, Canada, Sweden, and advanced defense technology programs such as DragonFire, Banshee target systems, HERA crewed-uncrewed teaming, and maritime/space mission support.",
  tags: [
    "Entity profile",
    "UK sovereign T&E",
    "LTPA",
    "FTSE 250",
    "Defense technology",
    "DragonFire",
    "Banshee drones",
    "ETPS",
    "Autonomy",
    "Maritime systems",
    "AUKUS",
  ],
  aliases: ["QinetiQ", "QinetiQ Group", "QinetiQ Group plc", "QinetiQ US", "QinetiQ North America", "Foster-Miller"],
  sourceFilters: {
    sec: { legalEntities: ["QinetiQ Group plc"] },
    sam: { legalNames: ["QinetiQ US", "QinetiQ Inc", "QinetiQ North America"] },
    usaSpending: { recipientNames: ["QinetiQ", "QinetiQ US", "QinetiQ North America"] },
    jobSources: { linkedin: "qinetiq", careerSite: "https://careers.qinetiq.com/" },
    newsSources: {
      aliases: ["QinetiQ", "QinetiQ Group", "QinetiQ US", "LTPA", "DragonFire", "Banshee drones", "Empire Test Pilots' School"],
      acquisitionAliases: ["Westar", "Foster-Miller", "V2X Federal IT Services divestment"],
    },
  },
  executiveSignals: [
    {
      label: "FY25 revenue",
      value: "£1.93B",
      note: "Uploaded report shows Group FY25 revenue of £1,931.6M across EMEA Services and Global Solutions.",
    },
    {
      label: "Funded backlog",
      value: "£4.3B",
      note: "Report conclusion cites funded order backlog of £4.3B and record order intake of £1.95B.",
    },
    {
      label: "LTPA extension",
      value: "£1.54B to 2033",
      note: "May 2025 extension modernizes UK test and evaluation infrastructure for hypersonics, directed energy, and future warfare.",
    },
    {
      label: "Global footprint",
      value: "~30 countries",
      note: "Report identifies a presence across roughly 30 countries, with major concentrations in the UK, US, Australia, Germany, Belgium, Canada, and Sweden.",
    },
  ],
  curveTitle: "QinetiQ sovereign T&E and advanced defense technology curve",
  curveSubtitle:
    "Uploaded research report normalized into entity-profile charts; values should be treated as source-backed strategic intelligence and verified against current company filings before operational use.",
  chartDefinitions: [
    {
      id: "qinetiq-segment-revenue",
      title: "FY25 revenue by reporting segment",
      subtitle: "Uploaded report: EMEA Services generated ~77% of Group turnover; Global Solutions is the restructuring/growth segment.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "EMEA Services", revenue: 1477.7, margin: 11.4, bookToBill: 1.2 },
        { segment: "Global Solutions", revenue: 453.9, margin: 3.6, bookToBill: 1.1 },
        { segment: "Group Total", revenue: 1931.6, margin: 9.6, bookToBill: 1.2 },
      ],
      series: [{ dataKey: "revenue", name: "FY25 revenue", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "segment revenue",
      fullWidth: true,
    },
    {
      id: "qinetiq-segment-margin",
      title: "Underlying operating margin by segment",
      subtitle: "Margin contrast shows why the US/Global Solutions restructuring matters.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "EMEA Services", margin: 11.4 },
        { segment: "Global Solutions", margin: 3.6 },
        { segment: "Group Total", margin: 9.6 },
      ],
      series: [{ dataKey: "margin", name: "Underlying margin", color: "#22c55e", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 14],
      headline: "margin profile",
    },
    {
      id: "qinetiq-ltpa-milestones",
      title: "Corporate and LTPA milestone timeline",
      subtitle: "From DERA split to LTPA extension; numeric year used for chart rendering.",
      type: "bar",
      xKey: "milestone",
      data: [
        { milestone: "DERA split", year: 2001, importance: 8 },
        { milestone: "Carlyle stake", year: 2002, importance: 6 },
        { milestone: "LTPA signing", year: 2003, importance: 10 },
        { milestone: "US entry", year: 2004, importance: 7 },
        { milestone: "LSE IPO", year: 2006, importance: 7 },
        { milestone: "LTPA extension", year: 2025, importance: 10 },
      ],
      series: [{ dataKey: "importance", name: "Strategic importance", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "milestones",
    },
    {
      id: "qinetiq-global-footprint",
      title: "Global operational footprint by region",
      subtitle: "Facility counts derived from the uploaded operations directory and concentration notes.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "UK sovereign sites", facilities: 18 },
        { region: "United States", facilities: 8 },
        { region: "Australia", facilities: 3 },
        { region: "Germany", facilities: 2 },
        { region: "Belgium", facilities: 1 },
        { region: "Canada", facilities: 1 },
        { region: "Sweden", facilities: 1 },
        { region: "Malaysia", facilities: 1 },
      ],
      series: [{ dataKey: "facilities", name: "Named facilities/offices", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "footprint",
      fullWidth: true,
    },
    {
      id: "qinetiq-t3e-domain-criticality",
      title: "LTPA T3E domain criticality",
      subtitle: "Strategic criticality score for the four LTPA delivery domains described in the uploaded report.",
      type: "bar",
      xKey: "domain",
      data: [
        { domain: "Maritime / BUTEC", criticality: 10 },
        { domain: "Air / Boscombe Down", criticality: 9 },
        { domain: "Land & weapons", criticality: 9 },
        { domain: "Mission rehearsal", criticality: 8 },
      ],
      series: [{ dataKey: "criticality", name: "Criticality score", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "T3E domains",
    },
    {
      id: "qinetiq-us-core-four",
      title: "Post-divestment QinetiQ US core-four focus",
      subtitle: "After the 2025 V2X divestment, the report says QinetiQ US is centered on four differentiated pillars.",
      type: "bar",
      xKey: "pillar",
      data: [
        { pillar: "Maritime systems", priority: 10 },
        { pillar: "Advanced sensors", priority: 9 },
        { pillar: "Space/missile support", priority: 9 },
        { pillar: "Persistent surveillance", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Strategic priority", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "US focus",
    },
    {
      id: "qinetiq-technology-frontiers",
      title: "Advanced technology frontiers",
      subtitle: "Strategic technology lines identified in the uploaded report.",
      type: "bar",
      xKey: "technology",
      data: [
        { technology: "DragonFire DEW", priority: 10 },
        { technology: "Banshee drones", priority: 9 },
        { technology: "Project HERA CUC-T", priority: 9 },
        { technology: "DroneWorks", priority: 8 },
        { technology: "ETPS", priority: 8 },
        { technology: "Shoeburyness ETC", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Strategic technology priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "tech frontier",
    },
  ],
  metricDefinitions: [
    { id: "qinetiq-employees", label: "Employees", value: 8500, unit: "count", category: "workforce" },
    { id: "qinetiq-fy25-revenue", label: "FY25 revenue", value: 1931.6, unit: "usd", category: "financial" },
    { id: "qinetiq-emea-revenue", label: "EMEA Services revenue", value: 1477.7, unit: "usd", category: "financial" },
    { id: "qinetiq-global-solutions-revenue", label: "Global Solutions revenue", value: 453.9, unit: "usd", category: "financial" },
    { id: "qinetiq-funded-backlog", label: "Funded order backlog", value: 4300, unit: "usd", category: "financial" },
    { id: "qinetiq-ltpa-extension", label: "LTPA extension value", value: 1540, unit: "usd", category: "financial" },
    { id: "qinetiq-country-footprint", label: "Country footprint", value: 30, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "UK sovereign T&E / LTPA", revenue: 1477.7, risk: 6.0, workers: 5500 },
    { name: "US maritime/sensors/space", revenue: 250.0, risk: 5.0, workers: 1500 },
    { name: "Australia MSP / AUKUS", revenue: 120.0, risk: 5.5, workers: 700 },
    { name: "Target systems / Banshee", revenue: 80.0, risk: 7.0, workers: 500 },
    { name: "Shoeburyness / ordnance testing", revenue: 90.0, risk: 8.5, workers: 400 },
  ],
  opportunityMatrix: [
    { name: "LTPA modernization", revenuePotential: 1540, implementationComplexity: 9, strategicValue: 10 },
    { name: "DragonFire / directed energy", revenuePotential: 316, implementationComplexity: 9, strategicValue: 10 },
    { name: "QinetiQ US core four", revenuePotential: 454, implementationComplexity: 7, strategicValue: 9 },
    { name: "AUKUS maritime support", revenuePotential: 250, implementationComplexity: 8, strategicValue: 9 },
    { name: "DroneWorks / autonomy", revenuePotential: 150, implementationComplexity: 6, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "QinetiQ is a unique defense-privatization entity: a publicly listed company that still operates sovereign national-security infrastructure through the UK Ministry of Defence's Long Term Partnering Agreement. The uploaded report frames QinetiQ as both a commercial defense technology business and a semi-sovereign test/evaluation custodian.",
      bullets: [
        "Created in 2001 through the split of the UK's Defence Evaluation and Research Agency into QinetiQ and Dstl.",
        "Listed on the London Stock Exchange in 2006 and now operates as a FTSE 250 defense technology entity.",
        "UK Government retains a Special Share / Golden Share that protects national-security interests.",
        "Workforce is about 8,500 employees, largely scientists and engineers.",
      ],
      metricIds: ["qinetiq-employees", "qinetiq-fy25-revenue", "qinetiq-funded-backlog"],
    },
    {
      type: "contracts",
      title: "LTPA and sovereign T3E infrastructure",
      narrative:
        "The LTPA is the core strategic asset. It gives QinetiQ operational control of irreplaceable MOD-owned test, trials, training and evaluation sites and was extended in 2025 through 2033 for future-warfare modernization.",
      bullets: [
        "The 2003 LTPA created long-term facility-management and test/evaluation rights over 16 core MOD-owned sites.",
        "The May 2025 extension is valued at £1.54B and runs to 2033.",
        "Modernization themes include hypersonics, directed energy, uncrewed systems, digital twins, and modeling-based certification.",
        "Core T3E domains include maritime, air, land/weapons, and multi-domain mission rehearsal.",
      ],
      metricIds: ["qinetiq-ltpa-extension"],
    },
    {
      type: "locations",
      title: "Global operational footprint",
      narrative:
        "The uploaded operations directory identifies a footprint across approximately 30 countries, with dense UK sovereign infrastructure and targeted US, Australian, German, Belgian, Canadian, Swedish, and Malaysian operations.",
      bullets: [
        "UK hubs include Farnborough, Boscombe Down, Hebrides Range, Shoeburyness, Aberporth, Pendine, BUTEC, West Freugh, Eskmeals, Loch Fyne, Loch Goil, Rosneath, Haslar, Winfrith, Malvern, Bristol, Ashford, Fort Halstead, Portland Bill, and Plymouth/Eastern Kings.",
        "US sites include Reston, Waltham, Pittsburgh, Lorton, Franklin, Stafford, and Fredericksburg.",
        "International sites include Canberra, Port Wakefield, Nowra, Mönchengladbach, Kruibeke, Medicine Hat, Linköping, and Kuala Lumpur.",
        "Facility risk varies from low-risk corporate offices to high-hazard ordnance, flight test, underwater range, and drone/target-system environments.",
      ],
      metricIds: ["qinetiq-country-footprint"],
    },
    {
      type: "acquisitions",
      title: "US restructuring and V2X divestment",
      narrative:
        "The report identifies the 2025 sale of QinetiQ's non-core US Federal IT Services business to V2X as a major strategic pivot. The divestment lets QinetiQ US focus on higher-differentiation maritime, sensor, space/missile, and persistent-surveillance domains.",
      bullets: [
        "QinetiQ sold the US Federal IT Services business to V2X in August 2025 for $31M enterprise value.",
        "The divested business had about 70 employees and was viewed as lower-margin, commoditized work.",
        "Post-divestment US focus areas are maritime systems, advanced sensors, space/missile defense mission support, and persistent surveillance.",
        "The restructuring is meant to improve margin quality and sharpen differentiation against digital/mission services competitors.",
      ],
      metricIds: ["qinetiq-global-solutions-revenue"],
    },
    {
      type: "safety",
      title: "High-hazard technical operating environments",
      narrative:
        "QinetiQ's occupational risk profile is not ordinary office defense contracting. It includes flight test, explosive ordnance, environmental testing, hypersonic/directed-energy experimentation, underwater ranges, drone target systems, and live multi-domain mission rehearsal.",
      bullets: [
        "MOD Shoeburyness occupies a large ordnance testing/disposal environment with firing areas, environmental testing, shock/vibration testing, radiography, and munitions disposal.",
        "MOD Boscombe Down and ETPS introduce flight test, aircraft modification, and systems-rich training exposure.",
        "BUTEC, Loch Goil, and Loch Fyne include underwater ranging and acoustic/signature testing for submarines and vessels.",
        "Target systems and Banshee drone production introduce manufacturing, test-range, and UAV operational exposures.",
      ],
      metricIds: [],
    },
    {
      type: "competitors",
      title: "Competitive position",
      narrative:
        "QinetiQ sits between Tier 1 primes and specialized technology firms. Its moat comes from irreplaceable infrastructure, sovereign relationships, proprietary IP, and high-density scientific/engineering talent.",
      bullets: [
        "Global primes such as BAE Systems, Northrop Grumman, Lockheed Martin, and RTX can be both partners and competitors.",
        "Digital and mission service providers such as Leidos and Booz Allen compete in US intelligence/data support lanes.",
        "Specialized firms such as Ultra Electronics and Kratos compete in target systems, secure communications, and uncrewed platforms.",
        "The LTPA infrastructure creates a barrier that cannot be replicated quickly by competitors.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "Technology frontiers and geopolitical drivers",
      narrative:
        "The uploaded report frames QinetiQ's future around directed energy, autonomy, AI-enabled mission systems, AUKUS maritime growth, and the operational lessons of Ukraine and Indo-Pacific tensions.",
      bullets: [
        "DragonFire is a directed energy program where QinetiQ contributes coherent beam combining technology.",
        "Banshee target drones and Project HERA support crewed-uncrewed teaming and affordable combat mass.",
        "DroneWorks provides SMEs access to prototyping, testing, and regulatory pathways.",
        "AUKUS creates multi-decade opportunity for UK maritime expertise to support Australian nuclear-submarine and US Navy fleet expansion requirements.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "QinetiQ values in this profile are source-backed but should be treated as uploaded research intelligence. Financial values, facility counts, and strategic priorities should be verified against current filings and live source records before operational use.",
      bullets: [
        "The profile relies on the uploaded QinetiQ research report and its cited public sources.",
        "Revenue values are in GBP millions but rendered through the app's generic currency format until multi-currency formatting is added.",
        "Facility counts are derived from the uploaded directory and should be reviewed when exact site counts matter.",
        "Do not treat strategic priority scores as audited figures; they are visual intelligence weights.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "deep-analysis",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
