import type { CompanyConfig } from "./types";

export const referralDemandIntelligenceConfig: CompanyConfig = {
  companyId: "referral-demand-intelligence",
  displayName: "Referral Demand Intelligence",
  shortName: "Referral Demand",
  sector:
    "Defense/federal referral-volume analysis, contract-generated exam demand, OCONUS provider mapping, CONUS staging-city intelligence, V2X LOGCAP recurring exams, and proactive clinic-network outreach strategy",
  headquarters: "Occu-Med portfolio-level referral analysis",
  employees: 0,
  employeesAsOf:
    "Uploaded referral-demand report: 10,203 defense/federal referrals after excluding traditional municipal clients; 36 defense/federal clients analyzed; enhanced with chart packs 1 and 4 referral data",
  summary:
    "Referral Demand Intelligence converts the uploaded contract/referral analysis into an entity profile focused on what already happened, not theoretical market size. The report explicitly excludes traditional clients such as counties, cities, fire districts, water agencies, colleges, and National Guard-style municipal/public entities for this study. The filtered defense/federal core shows 10,203 referrals across 36 clients, with V2X/Vectrus alone generating 5,427 referrals, or about 52% of the defense contractor volume. The key insight is that referrals cluster by contract and staging geography: V2X LOGCAP V annual exams dominate Iraq, Kuwait, and Kwajalein; Dubai functions as an Iraq-theater pre/post-deployment staging hub; Qatar is Al Udeid-adjacent; and Greenville, South Carolina appears as a primary CONUS V2X mobilization center. Chart packs 1 and 4 add scheduling event concentration, client concentration analysis, and completed exams by country intelligence. This profile should drive the network buildout engine: add or confirm providers in the highest-demand cities, then notify existing clients that Occu-Med already has ready coverage there.",
  tags: [
    "Entity profile",
    "Referral demand",
    "Defense federal only",
    "Traditional clients excluded",
    "V2X",
    "LOGCAP V",
    "Kuwait",
    "Iraq",
    "Dubai staging hub",
    "Qatar",
    "Kwajalein",
    "Greenville SC",
    "Provider network",
    "Clinic outreach",
  ],
  aliases: ["Referral Demand", "Contract Referral Intelligence", "Defense Federal Referral Map", "Network Demand Map"],
  sourceFilters: {
    newsSources: {
      aliases: ["Occu-Med defense referral demand", "V2X LOGCAP referral volume", "Greenville LOGCAP mobilization"],
    },
  },
  executiveSignals: [
    { label: "Defense/federal refs", value: "10,203", note: "Uploaded referral report excludes traditional municipal/public clients for this study." },
    { label: "V2X share", value: "5,427", note: "V2X generates about 52% of all defense contractor volume in the filtered file." },
    { label: "Top OCONUS cluster", value: "Kuwait 1,778", note: "Kuwait is the largest location cluster, driven by Camp Arifjan, Camp Buehring, Kuwait City, and V2X LOGCAP." },
    { label: "Top CONUS staging", value: "Greenville 192", note: "Greenville, SC is identified as V2X's primary CONUS LOGCAP mobilization center." },
  ],
  curveTitle: "Defense/federal referral demand, OCONUS provider, and CONUS staging-city curve",
  curveSubtitle:
    "Uploaded referral report normalized into a portfolio entity. Traditional municipal/public clients are excluded by design; the profile focuses on defense/federal contract-generated demand.",
  chartDefinitions: [
    {
      id: "referral-client-concentration",
      title: "Defense/federal referral concentration",
      subtitle: "V2X alone generated 5,427 of 10,203 filtered defense/federal referrals.",
      type: "bar",
      xKey: "clientGroup",
      data: [
        { clientGroup: "V2X / Vectrus", referrals: 5427 },
        { clientGroup: "All other defense/federal clients", referrals: 4776 },
      ],
      series: [{ dataKey: "referrals", name: "Referrals", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "client concentration",
      fullWidth: true,
    },
    {
      id: "v2x-top-contracts",
      title: "Top V2X contracts generating recurring referrals",
      subtitle: "Top LOGCAP and OMDAC lanes are recurring, mandated, and predictable rather than discretionary.",
      type: "bar",
      xKey: "contract",
      data: [
        { contract: "LOGCAP V Iraq OCN annual", referrals: 1312 },
        { contract: "LOGCAP V Kuwait annual", referrals: 880 },
        { contract: "OMDAC-SWACA Kuwait/Qatar", referrals: 472 },
        { contract: "LOGCAP V Iraq annual", referrals: 281 },
        { contract: "LOGCAP V Kwajalein annual", referrals: 217 },
      ],
      series: [{ dataKey: "referrals", name: "Referrals", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "V2X contracts",
      fullWidth: true,
    },
    {
      id: "oconus-provider-demand",
      title: "OCONUS provider demand map by actual referrals",
      subtitle: "Top five OCONUS demand areas represent 5,032 referrals from locations where Occu-Med had to schedule or source provider coverage.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Kuwait", referrals: 1778 },
        { location: "Iraq", referrals: 1157 },
        { location: "UAE / Dubai", referrals: 964 },
        { location: "Qatar", referrals: 718 },
        { location: "Marshall Islands", referrals: 415 },
      ],
      series: [{ dataKey: "referrals", name: "Referrals", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "OCONUS demand",
      fullWidth: true,
    },
    {
      id: "conus-staging-cities",
      title: "CONUS pre-deployment staging-city intelligence",
      subtitle: "These cities show where workers get exams before leaving the country.",
      type: "bar",
      xKey: "city",
      data: [
        { city: "Fort Worth TX", referrals: 199 },
        { city: "Greenville SC", referrals: 192 },
        { city: "Corpus Christi TX", referrals: 103 },
        { city: "San Antonio TX", referrals: 55 },
        { city: "El Paso TX", referrals: 48 },
        { city: "Fayetteville NC", referrals: 45 },
        { city: "Jacksonville FL", referrals: 42 },
        { city: "Milton FL", referrals: 41 },
      ],
      series: [{ dataKey: "referrals", name: "Referrals", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      headline: "CONUS staging",
    },
    {
      id: "provider-outreach-priority",
      title: "Clinic-network outreach priority",
      subtitle: "Where one provider relationship can unlock recurring client demand across contracts.",
      type: "bar",
      xKey: "target",
      data: [
        { target: "Kuwait provider", priority: 10 },
        { target: "Greenville SC provider", priority: 10 },
        { target: "Dubai staging provider", priority: 9 },
        { target: "Qatar provider", priority: 9 },
        { target: "Kwajalein solution", priority: 8 },
        { target: "Fort Worth TX provider", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "network action",
    },
    {
      id: "referral-scheduling-events",
      title: "Scheduling events by client — top 15",
      subtitle: "Chart pack 1: complete event labels shown; V2X is about 48% of all events.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "V2X", complete: 12056 },
        { client: "Amentum", complete: 2761 },
        { client: "Valiant", complete: 2113 },
        { client: "Leidos", complete: 960 },
        { client: "IAP", complete: 954 },
        { client: "Vertex", complete: 776 },
        { client: "CACI", complete: 603 },
        { client: "Sierra Nevada Corporation", complete: 505 },
        { client: "International SOS", complete: 442 },
        { client: "IDS International", complete: 364 },
        { client: "ManTech", complete: 336 },
        { client: "GDC Middle East", complete: 317 },
        { client: "Freeport", complete: 308 },
        { client: "Alutiiq", complete: 268 },
        { client: "Trace Systems", complete: 236 },
      ],
      series: [{ dataKey: "complete", name: "Complete events", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "schedule events",
      fullWidth: true,
    },
    {
      id: "referral-client-concentration",
      title: "Referral concentration by client",
      subtitle: "Chart pack 1: V2X alone is roughly 49% of all defense referrals; top concentration creates account-retention risk.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "V2X / Vectrus", referrals: 5418, share: 49 },
        { client: "All Others", referrals: 2270, share: 20 },
        { client: "Amentum", referrals: 852, share: 8 },
        { client: "Constellis", referrals: 610, share: 5 },
        { client: "GDIT", referrals: 437, share: 4 },
        { client: "Valiant", referrals: 423, share: 4 },
        { client: "IAP", referrals: 409, share: 4 },
        { client: "Deployment Ctr", referrals: 283, share: 3 },
        { client: "Vertex", referrals: 234, share: 2 },
        { client: "Leidos", referrals: 226, share: 2 },
      ],
      series: [{ dataKey: "referrals", name: "Referrals", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "concentration",
    },
    {
      id: "referral-completed-exams-country",
      title: "Completed exams by country — top 12",
      subtitle: "Chart pack 1: OCONUS = 39% of completions.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "United States", completed: 14937 },
        { country: "Kuwait", completed: 2277 },
        { country: "United Arab Emirates", completed: 1617 },
        { country: "Iraq", completed: 1332 },
        { country: "Qatar", completed: 834 },
        { country: "Marshall Islands", completed: 819 },
        { country: "Jordan", completed: 456 },
        { country: "Kenya", completed: 288 },
        { country: "Djibouti", completed: 242 },
        { country: "India", completed: 216 },
        { country: "Bahrain", completed: 122 },
        { country: "Unknown / nan", completed: 114 },
      ],
      series: [{ dataKey: "completed", name: "Completed exams", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "completions",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "referral-total-defense", label: "Defense/federal referrals", value: 10203, unit: "count", category: "workforce" },
    { id: "referral-client-count", label: "Filtered defense/federal clients", value: 36, unit: "count", category: "workforce" },
    { id: "referral-v2x", label: "V2X referrals", value: 5427, unit: "count", category: "workforce" },
    { id: "referral-v2x-share", label: "V2X share", value: 52, unit: "percent", category: "financial" },
    { id: "referral-kuwait", label: "Kuwait referrals", value: 1778, unit: "count", category: "workforce" },
    { id: "referral-greenville", label: "Greenville referrals", value: 192, unit: "count", category: "workforce" },
    { id: "referral-v2x-events", label: "V2X scheduling events", value: 12056, unit: "count", category: "workforce" },
    { id: "referral-v2x-concentration", label: "V2X concentration share", value: 49, unit: "percent", category: "risk" },
  ],
  riskMatrix: [
    { name: "Kuwait provider coverage", revenue: 1778, risk: 10.0, workers: 1778 },
    { name: "Iraq theater coverage", revenue: 1157, risk: 9.5, workers: 1157 },
    { name: "Dubai staging coverage", revenue: 964, risk: 9.0, workers: 964 },
    { name: "Qatar provider coverage", revenue: 718, risk: 8.5, workers: 718 },
    { name: "Greenville mobilization", revenue: 192, risk: 9.0, workers: 192 },
  ],
  opportunityMatrix: [
    { name: "Kuwait Provider Agreement", revenuePotential: 1778, implementationComplexity: 8, strategicValue: 10 },
    { name: "Greenville LOGCAP Clinic", revenuePotential: 192, implementationComplexity: 4, strategicValue: 10 },
    { name: "Dubai Pre/Post Deployment Hub", revenuePotential: 964, implementationComplexity: 7, strategicValue: 9 },
    { name: "Qatar / Al Udeid Coverage", revenuePotential: 718, implementationComplexity: 7, strategicValue: 9 },
    { name: "Kwajalein Provider Solution", revenuePotential: 415, implementationComplexity: 9, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "What the referral data actually proves",
      narrative:
        "The uploaded report turns historical scheduling pain into a network strategy. These are not hypothetical market opportunities; they are referrals that already occurred, showing where Occu-Med either had coverage or had to scramble.",
      bullets: [
        "Traditional municipal/public clients are excluded for this defense/federal study.",
        "The filtered core contains 10,203 referrals across 36 defense/federal clients.",
        "V2X produces 5,427 referrals, about 52% of defense contractor volume.",
        "The dominant demand lanes are recurring LOGCAP annual exams, not one-off medical events.",
      ],
      metricIds: ["referral-total-defense", "referral-client-count", "referral-v2x", "referral-v2x-share"],
    },
    {
      type: "locations",
      title: "OCONUS provider map built from actual demand",
      narrative:
        "Kuwait, Iraq, Dubai, Qatar, and the Marshall Islands are the most important OCONUS/provider-network signals. The Dubai finding is especially important because it functions as an Iraq-theater staging hub even when the contract name says Iraq.",
      bullets: [
        "Kuwait: 1,778 referrals tied to Camp Arifjan, Camp Buehring, Kuwait City, and V2X LOGCAP.",
        "Iraq: 1,157 referrals tied to V2X LOGCAP V and ManTech ALECS.",
        "Dubai/UAE: 964 referrals functioning as Iraq-theater pre/post-deployment staging.",
        "Qatar: 718 referrals tied to V2X AFCAP and GDIT CTSS 3 renewal.",
        "Marshall Islands: 415 referrals tied to Kwajalein, a remote high-friction location.",
      ],
      metricIds: ["referral-kuwait"],
    },
    {
      type: "medical-opportunities",
      title: "Clinic outreach mechanism",
      narrative:
        "The practical workflow is simple: add or confirm a clinic in a high-demand city, then tell existing clients that Occu-Med already has a vetted provider there. Greenville is the clearest CONUS proof of concept.",
      bullets: [
        "Greenville, SC: 192 referrals tied to V2X LOGCAP Iraq/Kuwait/Kwajalein mobilization.",
        "Fort Worth, TX: security contractor mobilization hub.",
        "Corpus Christi and Milton: Amentum T-44 / NAVMED recurring naval aviation requirements.",
        "El Paso and Fayetteville: Fort Bliss and Fort Bragg/SOF-adjacent staging logic.",
      ],
      metricIds: ["referral-greenville"],
    },
  ],
};
