import type { CompanyConfig } from "./types";

export const reportMethodologyIntelligenceConfig: CompanyConfig = {
  companyId: "report-methodology-intelligence",
  displayName: "Report Methodology Intelligence",
  shortName: "Report Methodology",
  sector: "Occu-Med internal report standard, executive data-first writing, modeled value framework, addendum assumptions, exam outcome analytics, and client-ready EHS messaging",
  headquarters: "Occu-Med internal intelligence standard",
  employees: 0,
  employeesAsOf: "Uploaded report-quality and methodology files: internal methodology layer rather than employer entity profile",
  summary:
    "Report Methodology Intelligence captures the user's correction that entity reports should not drift into company introductions. The Amentum report standard is the model: lead with TRIR, DART, EMR, reserve signals, severe incident signals, injury mix, dollar values, location hotspots, and the single action number. When employers do not share detailed internal values, the report should label assumptions clearly and use public benchmarks plus Occu-Med's own exam outcome data. This profile is the operating standard for future reports: no generic background unless it directly explains an Occu-Med action.",
  tags: ["Entity profile", "Report methodology", "Executive report", "Data-first report", "Exam outcome data", "Value model", "Addendum standard", "No company intros"],
  aliases: ["Report Standard", "Amentum Report Standard", "Statistical Addendum Standard"],
  sourceFilters: { newsSources: { aliases: ["occupational health value model", "EHS report methodology"] } },
  executiveSignals: [
    { label: "Report rule", value: "Lead with data", note: "TRIR, DART, EMR, reserve signals, severe events, injury mix, dollars, and hotspots come before company background." },
    { label: "Assumptions", value: "Label clearly", note: "When exact employer values are unavailable, use conservative public benchmarks and label them as modeled." },
    { label: "Best asset", value: "Exam outcomes", note: "Clearance rates, conditional outcomes, and common findings become the proof layer." },
    { label: "Hidden revenue", value: "Exam menu", note: "Chemical exposure, heat, DOE, functional capacity, and ergonomic lanes should be surfaced when relevant." },
  ],
  curveTitle: "Data-first report method and modeled-value curve",
  curveSubtitle: "Internal methodology profile created from uploaded report-quality and value-model files.",
  chartDefinitions: [
    {
      id: "report-opening-standard",
      title: "Required opening-section data order",
      subtitle: "The first 200 words should contain the action value, not a company biography.",
      type: "bar",
      xKey: "openingElement",
      data: [
        { openingElement: "TRIR / DART / EMR", priority: 10 },
        { openingElement: "Dollar signals", priority: 10 },
        { openingElement: "Severe-event signals", priority: 9 },
        { openingElement: "Injury mix", priority: 9 },
        { openingElement: "Hotspot locations", priority: 9 },
        { openingElement: "Single action number", priority: 10 },
        { openingElement: "Company intro", priority: 2 },
      ],
      series: [{ dataKey: "priority", name: "Opening priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "lead with data",
      fullWidth: true,
    },
    {
      id: "value-model-paths",
      title: "Value model paths when internal values are unavailable",
      subtitle: "Use conservative public data, Occu-Med records, and partner validation instead of overclaiming.",
      type: "bar",
      xKey: "path",
      data: [
        { path: "Public benchmark model", priority: 8 },
        { path: "Occu-Med exam outcomes", priority: 10 },
        { path: "Partner data study", priority: 9 },
        { path: "Conservative exposure model", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Usefulness", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "value model",
    },
    {
      id: "hidden-exam-menu",
      title: "Hidden exam menu to surface",
      subtitle: "The unique-points memo calls out medical lanes that first-draft reports often miss.",
      type: "bar",
      xKey: "examLane",
      data: [
        { examLane: "Chemical exposure", priority: 9 },
        { examLane: "Exposure-specific labs", priority: 8 },
        { examLane: "DOE 10 CFR 851", priority: 10 },
        { examLane: "Heat testing", priority: 9 },
        { examLane: "FCE", priority: 8 },
        { examLane: "Ergonomic consults", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "hidden menu",
    },
  ],
  metricDefinitions: [
    { id: "methodology-data-first", label: "Data-first report priority", value: 10, unit: "score", category: "financial" },
    { id: "methodology-exam-outcomes", label: "Exam outcome data priority", value: 10, unit: "score", category: "financial" },
    { id: "methodology-assumption-labeling", label: "Assumption-labeling priority", value: 10, unit: "score", category: "risk" },
  ],
  riskMatrix: [
    { name: "Reports become company intros", revenue: 10, risk: 9.5, workers: 1 },
    { name: "Internal values unavailable", revenue: 9, risk: 8.5, workers: 1 },
    { name: "Exam outcomes uncaptured", revenue: 10, risk: 10.0, workers: 1 },
  ],
  opportunityMatrix: [
    { name: "Standard Report Template", revenuePotential: 100, implementationComplexity: 3, strategicValue: 10 },
    { name: "Exam Outcome Data Capture", revenuePotential: 500, implementationComplexity: 7, strategicValue: 10 },
    { name: "Value Model Template", revenuePotential: 250, implementationComplexity: 5, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "No more company-introduction reports",
      narrative: "Every report should open like the Amentum report: numbers, dollars, site hotspots, and the single Occu-Med action first. Company background is only included when it explains the medical opportunity.",
      bullets: [
        "Lead with TRIR, DART, EMR, reserve signals, severe events, injury mix, and location hotspots.",
        "Every section must answer: so what for Occu-Med?",
        "If someone reads only the first 200 words, they should know the action number and the pitch.",
      ],
      metricIds: ["methodology-data-first", "methodology-exam-outcomes"],
    },
  ],
};
