import type { CompanyConfig } from "./types";

export const rheinmetallConfig: CompanyConfig = {
  companyId: "rheinmetall",
  displayName: "Rheinmetall AG / American Rheinmetall",
  shortName: "Rheinmetall",
  sector:
    "Defense manufacturing, armored vehicles, munitions, military track systems, heavy metal fabrication, welding, and U.S. Army vehicle modernization",
  headquarters: "Düsseldorf, Germany / Sterling Heights, Michigan (American Rheinmetall)",
  employees: 37000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 20, 2026; U.S. workforce modeled at ~1,500 current and ~7,000 OMFV scenario",
  summary:
    "Rheinmetall AG is Germany's largest defense company with a rapidly expanding U.S. subsidiary, American Rheinmetall. The uploaded Occu-Med intelligence report frames the account as a scale-timing opportunity: today's U.S. footprint is about 1,500 workers across Michigan, Arkansas, Maine, and Virginia, but an XM30 OMFV production award could create a 5,000-10,000 worker U.S. heavy-manufacturing footprint. The occupational medicine story is not generic defense contracting; it is heavy vehicle, track, welding, heat-treatment, and munitions work with first-year worker injury concentration, hearing conservation, respirator clearance, and munitions chemical surveillance needs.",
  tags: [
    "Entity profile",
    "Defense manufacturing",
    "American Rheinmetall",
    "OMFV / XM30",
    "Armored vehicles",
    "Military track systems",
    "Munitions",
    "Welding fumes",
    "Lead surveillance",
    "Hearing conservation",
    "High-growth workforce",
  ],
  aliases: [
    "Rheinmetall",
    "Rheinmetall AG",
    "American Rheinmetall",
    "American Rheinmetall Vehicles",
    "American Rheinmetall Munitions",
    "RHM",
  ],
  sourceFilters: {
    sec: { legalEntities: ["Rheinmetall AG"] },
    sam: { legalNames: ["American Rheinmetall", "American Rheinmetall Vehicles", "American Rheinmetall Munitions"] },
    usaSpending: { recipientNames: ["American Rheinmetall", "Rheinmetall"] },
    jobSources: { linkedin: "rheinmetall", careerSite: "https://www.rheinmetall.com/en/career" },
    newsSources: {
      aliases: ["Rheinmetall", "American Rheinmetall", "XM30", "OMFV", "T-158 track", "Camden munitions"],
    },
  },
  executiveSignals: [
    {
      label: "U.S. scale risk",
      value: "1.5K → 7K",
      note: "Uploaded report models current U.S. workforce at ~1,500 and OMFV production scenario at ~7,000 workers.",
    },
    {
      label: "Expected injuries",
      value: "35.5 → 183/yr",
      note: "BLS-modeled injuries increase sharply under the OMFV production scenario.",
    },
    {
      label: "Economic burden",
      value: "$8.41M → $43.3M",
      note: "Modeled total annual economic burden rises more than fivefold if U.S. manufacturing scales.",
    },
    {
      label: "Occu-Med potential",
      value: "$337K-$3.1M/yr",
      note: "Current opportunity is modeled at $337K-$540K/year; OMFV scenario is $1.05M-$3.1M/year.",
    },
  ],
  curveTitle: "Rheinmetall U.S. manufacturing scale and munitions-risk curve",
  curveSubtitle:
    "Uploaded Occu-Med report normalized into entity-profile charts; modeled values should be treated as strategic sales intelligence, not audited Rheinmetall disclosures.",
  chartDefinitions: [
    {
      id: "rheinmetall-five-numbers",
      title: "Rheinmetall current vs OMFV production exposure",
      subtitle: "Uploaded report: U.S. workforce scale changes the occupational medicine economics.",
      type: "grouped",
      xKey: "metric",
      data: [
        { metric: "Expected injuries/yr", current: 35.5, omfv: 183 },
        { metric: "Direct cost ($M)", current: 1.53, omfv: 7.88 },
        { metric: "Economic burden ($M)", current: 8.41, omfv: 43.3 },
        { metric: "Fatality EV ($K)", current: 35.8, omfv: 166 },
      ],
      series: [
        { dataKey: "current", name: "Current", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "omfv", name: "OMFV scenario", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "scale inflection",
      fullWidth: true,
    },
    {
      id: "rheinmetall-accident-trend",
      title: "Parent safety trajectory: accident count worsening",
      subtitle: "Uploaded report: Rheinmetall Group LTI accidents rose from 309 to 386 from 2022-2024.",
      type: "bar",
      xKey: "year",
      data: [
        { year: "2022", accidents: 309, perThousand: 11.0 },
        { year: "2023", accidents: 325, perThousand: 9.8 },
        { year: "2024", accidents: 386, perThousand: 10.4 },
      ],
      series: [{ dataKey: "accidents", name: "LTI accidents", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "worsening trend",
    },
    {
      id: "rheinmetall-german-osha-translation",
      title: "German LTIR to OSHA TRIR translation",
      subtitle: "German 1+ day absence standard translated to OSHA all-recordable scope.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "German LTIR", rate: 1.04 },
        { metric: "OSHA TRIR equivalent", rate: 2.61 },
        { metric: "BLS ordnance mfg", rate: 3.5 },
        { metric: "BLS heavy vehicle mfg", rate: 2.5 },
      ],
      series: [{ dataKey: "rate", name: "Rate", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 4],
      headline: "TRIR translation",
    },
    {
      id: "rheinmetall-revenue-potential",
      title: "Occu-Med annual revenue potential",
      subtitle: "Uploaded report: current U.S. footprint vs OMFV production scenario.",
      type: "grouped",
      xKey: "examType",
      data: [
        { examType: "Pre-employment", currentLow: 101, currentHigh: 146, omfvLow: 338, omfvHigh: 975 },
        { examType: "Hearing conservation", currentLow: 79, currentHigh: 131, omfvLow: 300, omfvHigh: 1000 },
        { examType: "Respirator clearance", currentLow: 105, currentHigh: 158, omfvLow: 300, omfvHigh: 900 },
        { examType: "Munitions surveillance", currentLow: 52, currentHigh: 105, omfvLow: 113, omfvHigh: 225 },
      ],
      series: [
        { dataKey: "currentHigh", name: "Current high", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "omfvHigh", name: "OMFV high", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue range",
      fullWidth: true,
    },
    {
      id: "rheinmetall-medical-priority",
      title: "Rheinmetall occupational medicine priority lanes",
      subtitle: "Heavy track, welding, heat treatment, and munitions work drive the protocol stack.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "First-year physicals", priority: 10 },
        { lane: "Hearing conservation", priority: 9 },
        { lane: "Respirator clearance", priority: 9 },
        { lane: "Lead surveillance", priority: 10 },
        { lane: "RDX/munitions surveillance", priority: 8 },
        { lane: "MSK/cardiovascular baseline", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "protocol stack",
    },
  ],
  metricDefinitions: [
    { id: "rheinmetall-us-current-workers", label: "Current U.S. workers", value: 1500, unit: "count", category: "workforce" },
    { id: "rheinmetall-omfv-workers", label: "OMFV scenario U.S. workers", value: 7000, unit: "count", category: "workforce" },
    { id: "rheinmetall-current-injuries", label: "Current expected injuries/yr", value: 35.5, unit: "count", category: "safety" },
    { id: "rheinmetall-omfv-injuries", label: "OMFV expected injuries/yr", value: 183, unit: "count", category: "safety" },
    { id: "rheinmetall-current-burden", label: "Current economic burden", value: 8.41, unit: "usd", category: "financial" },
    { id: "rheinmetall-omfv-burden", label: "OMFV economic burden", value: 43.3, unit: "usd", category: "financial" },
    { id: "rheinmetall-omfv-revenue-high", label: "OMFV revenue potential high", value: 3.1, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Munitions chemical surveillance", revenue: 225, risk: 9.5, workers: 900 },
    { name: "Respirator / welding fumes", revenue: 900, risk: 8.5, workers: 3000 },
    { name: "Hearing conservation", revenue: 1000, risk: 8.0, workers: 7000 },
    { name: "Pre-employment MSK/cardio", revenue: 975, risk: 7.5, workers: 3900 },
    { name: "Current U.S. footprint", revenue: 540, risk: 7.0, workers: 1500 },
  ],
  opportunityMatrix: [
    { name: "OMFV pre-award relationship", revenuePotential: 3100, implementationComplexity: 7, strategicValue: 10 },
    { name: "Hearing conservation program", revenuePotential: 1000, implementationComplexity: 5, strategicValue: 9 },
    { name: "Respirator clearances", revenuePotential: 900, implementationComplexity: 5, strategicValue: 9 },
    { name: "Lead / munitions surveillance", revenuePotential: 225, implementationComplexity: 7, strategicValue: 10 },
    { name: "First-year worker baseline", revenuePotential: 975, implementationComplexity: 4, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Rheinmetall should be treated as a growth-and-timing account. The U.S. workforce is already meaningful, but the uploaded report says the OMFV/XM30 scenario would change the scale of the occupational medicine problem entirely.",
      bullets: [
        "Rheinmetall AG is Germany's largest defense company and American Rheinmetall is its U.S. operating platform.",
        "The uploaded report models about 1,500 current U.S. workers and an OMFV production scenario of about 7,000 U.S. workers.",
        "Key U.S. manufacturing footprint states include Michigan, Arkansas, Maine, and Virginia.",
        "The account should be approached before the production workforce scales, not after the injury burden has already materialized.",
      ],
      metricIds: ["rheinmetall-us-current-workers", "rheinmetall-omfv-workers", "rheinmetall-omfv-burden"],
    },
    {
      type: "safety",
      title: "Parent safety trajectory is moving the wrong direction",
      narrative:
        "The uploaded report contrasts Rheinmetall against peers by highlighting that parent-company LTI accidents rose from 309 to 386 from 2022 to 2024 while the workforce was also growing quickly.",
      bullets: [
        "Total LTI accidents increased 25% from 2022 to 2024.",
        "The accident rate per 1,000 workers dipped in 2023 then rebounded in 2024.",
        "The report argues that rapid hiring loads the highest-risk first-year cohort into the workforce every year.",
      ],
      metricIds: ["rheinmetall-current-injuries", "rheinmetall-omfv-injuries"],
    },
    {
      type: "workforce",
      title: "Heavy manufacturing and munitions exposure",
      narrative:
        "American Rheinmetall is not a low-risk white-collar defense profile. The uploaded report centers the U.S. risk on armored vehicle, track, welding, heat treatment, and munitions manufacturing work.",
      bullets: [
        "Michigan vehicle and track operations include heavy steel press stamping, arc welding, heat treatment, and precision assembly.",
        "Munitions operations create surveillance needs around lead, explosives-related materials, respiratory protection, and hearing conservation.",
        "Pre-employment musculoskeletal and cardiovascular baselines are positioned as first-year injury controls.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded report estimates current annual Occu-Med potential at $337K-$540K and OMFV scenario potential at $1.05M-$3.1M, concentrated in pre-employment, hearing, respirator, and munitions surveillance lanes.",
      bullets: [
        "Pre-employment physicals: current $101K-$146K; OMFV scenario $338K-$975K.",
        "Manufacturing hearing conservation: current $79K-$131K; OMFV scenario $300K-$1M.",
        "Respirator clearances for welding and munitions: current $105K-$158K; OMFV scenario $300K-$900K.",
        "Munitions chemical surveillance: current $52K-$105K; OMFV scenario $113K-$225K.",
      ],
      metricIds: ["rheinmetall-omfv-revenue-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "This profile is derived from the uploaded Occu-Med intelligence report. Treat injury, cost, TRIR translation, and revenue values as strategic modeling assumptions requiring validation with American Rheinmetall's actual OSHA logs and workforce counts.",
      bullets: [
        "Do not present German LTIR-to-OSHA TRIR translation as an audited U.S. TRIR.",
        "OMFV/XM30 workforce and revenue values are scenario values, not current-state values.",
        "The pitch should emphasize scale timing and first-year worker risk, not generic occupational medicine education.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "deep-analysis",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
