import type { CompanyConfig } from "./types";

export const rtxConfig: CompanyConfig = {
  companyId: "rtx",
  displayName: "RTX Corporation",
  shortName: "RTX",
  sector:
    "Aerospace and defense manufacturing, missiles, engines, avionics, field service representatives, OCONUS sustainment, and advanced defense systems",
  headquarters: "Arlington, Virginia",
  employees: 185000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 20, 2026; FY2025 global workforce estimate",
  summary:
    "RTX Corporation is framed in the uploaded Occu-Med report as the largest aerospace and defense entity in the portfolio: 185,000 employees, $88.6B FY2025 revenue, $268B backlog, and three operating segments: Collins Aerospace, Pratt & Whitney, and Raytheon. The report explicitly acknowledges RTX's excellent published safety performance, including a 0.30 TRIR and four consecutive years with zero work-related fatalities, then reframes the opportunity around absolute burden at scale, Raytheon OCONUS FSR DBA exposure, manufacturing surveillance, hearing conservation, respirator clearance, ergonomics, and pre-deployment medical baselines.",
  tags: [
    "Entity profile",
    "Aerospace and defense",
    "RTX",
    "Raytheon",
    "Collins Aerospace",
    "Pratt & Whitney",
    "F135",
    "Patriot",
    "OCONUS FSR",
    "DBA exposure",
    "Hearing conservation",
    "Respirator clearance",
    "Exceptional safety baseline",
  ],
  aliases: ["RTX", "RTX Corporation", "Raytheon Technologies", "Raytheon", "Collins Aerospace", "Pratt & Whitney", "NYSE: RTX"],
  sourceFilters: {
    sec: { ticker: "RTX", legalEntities: ["RTX Corporation", "Raytheon Technologies Corporation"] },
    sam: { legalNames: ["RTX Corporation", "Raytheon Company", "Collins Aerospace", "Pratt & Whitney"] },
    usaSpending: { recipientNames: ["RTX", "Raytheon", "Collins Aerospace", "Pratt & Whitney"] },
    jobSources: { linkedin: "rtx", careerSite: "https://careers.rtx.com/" },
    newsSources: { aliases: ["RTX", "Raytheon", "Collins Aerospace", "Pratt & Whitney", "Patriot", "F135", "LTAMDS"] },
  },
  executiveSignals: [
    {
      label: "Published TRIR",
      value: "0.30",
      note: "Uploaded report says RTX's 2024 TRIR is about 4.3x better than the BLS aerospace manufacturing benchmark.",
    },
    {
      label: "Published injuries",
      value: "544/yr",
      note: "Even exceptional safety performance still produces 544 reported incidents at 185,000 employees.",
    },
    {
      label: "Economic burden",
      value: "$128.7M/yr",
      note: "Modeled total annual economic burden from reported injuries using direct and indirect cost assumptions.",
    },
    {
      label: "Occu-Med potential",
      value: "$17.35M-$32.6M/yr",
      note: "Largest revenue opportunity in the uploaded portfolio because of workforce scale and exam volume, not poor safety performance.",
    },
  ],
  curveTitle: "RTX safety excellence, absolute burden, and DBA exposure curve",
  curveSubtitle:
    "Uploaded Occu-Med report normalized into entity-profile charts; RTX values should be framed respectfully as scale economics and DBA coverage gaps, not as safety failure.",
  chartDefinitions: [
    {
      id: "rtx-five-numbers",
      title: "RTX five exposure numbers that matter",
      subtitle: "Uploaded report: published injuries, cost burden, DBA claim exposure, and fatality expected value.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Direct injury cost", value: 23.4 },
        { metric: "Economic burden", value: 128.7 },
        { metric: "Annual DBA exposure", value: 54.3 },
        { metric: "Fatality EV", value: 1.17 },
      ],
      series: [{ dataKey: "value", name: "Annual value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "absolute burden",
      fullWidth: true,
    },
    {
      id: "rtx-safety-trend",
      title: "RTX published safety trend",
      subtitle: "TRIR remains excellent while incident count remains material at global scale.",
      type: "grouped",
      xKey: "year",
      data: [
        { year: "2021", trir: 0.36, incidents: 650, serious: 13 },
        { year: "2022", trir: 0.32, incidents: 593, serious: 13 },
        { year: "2023", trir: 0.30, incidents: 547, serious: 7 },
        { year: "2024", trir: 0.30, incidents: 544, serious: 3 },
      ],
      series: [
        { dataKey: "incidents", name: "Incidents", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "serious", name: "Serious incidents", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "safety maturity",
    },
    {
      id: "rtx-segment-injury-gap",
      title: "BLS expected vs RTX pro-rata injuries by segment",
      subtitle: "Uploaded report: RTX outperforms BLS benchmarks across manufacturing, technical, and field service segments.",
      type: "grouped",
      xKey: "segment",
      data: [
        { segment: "Collins Mfg", expected: 630, reported: 105 },
        { segment: "Collins Tech", expected: 240, reported: 90 },
        { segment: "P&W Mfg", expected: 630, reported: 105 },
        { segment: "P&W Tech", expected: 160, reported: 60 },
        { segment: "Raytheon Mfg", expected: 450, reported: 90 },
        { segment: "Raytheon FSR", expected: 110, reported: 15 },
        { segment: "Raytheon Tech/PM", expected: 180, reported: 90 },
      ],
      series: [
        { dataKey: "expected", name: "BLS expected", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "reported", name: "Reported pro-rata", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "benchmark gap",
      fullWidth: true,
    },
    {
      id: "rtx-revenue-potential",
      title: "RTX annual Occu-Med revenue potential",
      subtitle: "Uploaded report: total modeled opportunity of $17.35M-$32.6M/year.",
      type: "grouped",
      xKey: "examType",
      data: [
        { examType: "Pre-employment", low: 3.9, high: 8.1 },
        { examType: "Hearing conservation", low: 5.25, high: 8.75 },
        { examType: "Respirator clearance", low: 3.0, high: 4.5 },
        { examType: "Ergonomic baseline", low: 3.0, high: 6.0 },
        { examType: "DBA pre-deployment", low: 1.75, high: 4.0 },
        { examType: "Chemical surveillance", low: 0.45, high: 1.25 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "largest opportunity",
      fullWidth: true,
    },
    {
      id: "rtx-dba-hotspots",
      title: "Raytheon FSR DBA exposure hotspots",
      subtitle: "OCONUS field service support for air-defense and missile systems drives the DBA discussion.",
      type: "bar",
      xKey: "theater",
      data: [
        { theater: "Poland/Romania", exposure: 9 },
        { theater: "Saudi Arabia", exposure: 9 },
        { theater: "South Korea", exposure: 8 },
        { theater: "Eastern Med", exposure: 8 },
        { theater: "Other OCONUS", exposure: 6 },
      ],
      series: [{ dataKey: "exposure", name: "DBA exposure score", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "DBA field risk",
    },
    {
      id: "rtx-protocol-priority",
      title: "RTX Occu-Med protocol priority map",
      subtitle: "Respect mature safety program; focus on absolute scale, DBA, and surveillance lanes.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "DBA pre-deployment", priority: 10 },
        { lane: "Hearing conservation", priority: 9 },
        { lane: "Respirator clearance", priority: 8 },
        { lane: "Pre-employment baseline", priority: 8 },
        { lane: "Ergonomic baseline", priority: 7 },
        { lane: "Chemical surveillance", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "service lanes",
    },
  ],
  metricDefinitions: [
    { id: "rtx-employees", label: "Global employees", value: 185000, unit: "count", category: "workforce" },
    { id: "rtx-fy25-revenue", label: "FY2025 revenue", value: 88.6, unit: "usd", category: "financial" },
    { id: "rtx-backlog", label: "Backlog", value: 268, unit: "usd", category: "financial" },
    { id: "rtx-trir", label: "Published TRIR", value: 0.30, unit: "score", category: "safety" },
    { id: "rtx-incidents", label: "Published injuries/yr", value: 544, unit: "count", category: "safety" },
    { id: "rtx-economic-burden", label: "Total economic burden", value: 128.7, unit: "usd", category: "financial" },
    { id: "rtx-dba-exposure", label: "Annual DBA exposure", value: 54.3, unit: "usd", category: "risk" },
    { id: "rtx-revenue-high", label: "Occu-Med revenue high", value: 32.6, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Raytheon OCONUS FSRs", revenue: 4000, risk: 9.5, workers: 8000 },
    { name: "Hearing conservation", revenue: 8750, risk: 7.5, workers: 70000 },
    { name: "Respirator clearances", revenue: 4500, risk: 7.0, workers: 30000 },
    { name: "Ergonomic baseline", revenue: 6000, risk: 6.0, workers: 40000 },
    { name: "Chemical surveillance", revenue: 1250, risk: 7.5, workers: 5000 },
  ],
  opportunityMatrix: [
    { name: "Hearing conservation", revenuePotential: 8750, implementationComplexity: 6, strategicValue: 9 },
    { name: "Pre-employment physicals", revenuePotential: 8100, implementationComplexity: 5, strategicValue: 9 },
    { name: "Ergonomic baseline", revenuePotential: 6000, implementationComplexity: 7, strategicValue: 8 },
    { name: "DBA pre-deployment", revenuePotential: 4000, implementationComplexity: 7, strategicValue: 10 },
    { name: "Respirator clearances", revenuePotential: 4500, implementationComplexity: 5, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "RTX should be approached as a safety-mature, high-scale aerospace and defense entity. The uploaded report says the correct frame is not poor safety performance; it is absolute cost, huge exam volume, and OCONUS DBA exposure that may not be visible in OSHA TRIR reporting.",
      bullets: [
        "RTX is modeled as the largest aerospace and defense company in the portfolio: $88.6B FY2025 revenue, 185,000 employees, and $268B backlog.",
        "Operating segments are Collins Aerospace, Pratt & Whitney, and Raytheon.",
        "Published 2024 TRIR is 0.30 with 544 total incidents and zero work-related fatalities for four consecutive years.",
        "The report explicitly says RTX knows what it is doing in safety; the sales story is targeted burden and DBA exposure.",
      ],
      metricIds: ["rtx-employees", "rtx-trir", "rtx-economic-burden"],
    },
    {
      type: "safety",
      title: "Exceptional safety still creates material absolute burden",
      narrative:
        "At 185,000 employees, even a 0.30 TRIR produces 544 injuries per year. The uploaded report models $23.4M in direct annual injury cost and $128.7M in total economic burden.",
      bullets: [
        "TRIR improved from 0.36 in 2021 to 0.30 in 2023-2024.",
        "Serious incidents declined from 13 to 3 from 2021 to 2024.",
        "The right positioning is respectful benchmarking: preserve the safety-excellence acknowledgment while showing the residual economics.",
      ],
      metricIds: ["rtx-incidents", "rtx-economic-burden"],
    },
    {
      type: "workforce",
      title: "Segment profile and field-service exception",
      narrative:
        "The uploaded segment model separates Collins manufacturing, Pratt & Whitney manufacturing, Raytheon manufacturing, technical populations, and Raytheon FSRs. The FSR group is the key DBA edge case.",
      bullets: [
        "Collins and Pratt & Whitney manufacturing workers drive hearing, respirator, ergonomics, and chemical surveillance volume.",
        "Raytheon FSRs support Patriot, LTAMDS, NASAMS, AIM-9X, and AMRAAM systems in OCONUS theaters.",
        "The report flags that OCONUS injuries may not appear in OSHA TRIR the same way domestic injuries do.",
      ],
      metricIds: ["rtx-dba-exposure"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded report estimates $17.35M-$32.6M in annual Occu-Med potential. The largest lanes are hearing conservation, pre-employment physicals, ergonomic baseline work, respirator clearance, and DBA pre-deployment exams.",
      bullets: [
        "Pre-employment physicals: 22,000-27,000 new hires; modeled $3.9M-$8.1M per year.",
        "Hearing conservation: 70,000 manufacturing workers; modeled $5.25M-$8.75M per year.",
        "DBA pre-deployment: 5,000-8,000 OCONUS FSRs; modeled $1.75M-$4M per year.",
        "Core pre-employment and DBA lanes alone represent about $5.65M-$12.1M annually in the uploaded model.",
      ],
      metricIds: ["rtx-revenue-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "This profile is derived from the uploaded Occu-Med intelligence report and RTX public safety-performance framing. Modeled revenue and DBA values should be treated as sales intelligence assumptions requiring verification with RTX's actual program population and FSR deployment counts.",
      bullets: [
        "Do not imply RTX lacks a mature safety program; the report says the opposite.",
        "Separate domestic OSHA TRIR discussion from OCONUS DBA exposure discussion.",
        "Use the profile to identify targeted protocol gaps, not to criticize RTX safety maturity.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "comparative-benchmark",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
