import type { CompanyConfig } from "./types";

export const s3InternationalConfig: CompanyConfig = {
  companyId: "s3-international",
  displayName: "S3 International",
  shortName: "S3",
  sector: "International aviation maintenance, Saudi Arabia support, OCONUS deployment, and defense contractor workforce services",
  headquarters: "Huntsville, Alabama",
  employees: 680,
  employeesAsOf: "Modeled workforce deployment from uploaded S3 visual set",
  summary: "S3 International has been added as a Saudi Arabia and OCONUS aviation-support dossier connecting aircraft maintenance noise exposure, extreme heat and chemical hazards, Saudi-based DBA medical risk, international deployment headcount, and Occu-Med revenue opportunities.",
  tags: ["Saudi Arabia", "Aviation maintenance", "Noise exposure", "DBA pre-deploy", "OCONUS workforce", "Hazard gap"],
  aliases: ["S3I", "S3 Inc"],
  executiveSignals: [
    { label: "Peak aircraft noise", value: "118 dB", note: "All platforms exceed OSHA action lines." },
    { label: "Saudi risk node", value: "300 / 9-10", note: "Largest and highest-risk international workforce node." },
    { label: "Revenue potential", value: "$414K/yr", note: "DBA pre-deploy is the largest modeled lane." },
    { label: "Hazard gap", value: "5/5", note: "DBA unlimited medical liability has maximum gap score." },
  ],
  curveTitle: "S3 aviation hazard and revenue curve",
  curveSubtitle: "Aviation noise, Saudi risk, worker deployment, and revenue potential normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "s3-aircraft-noise",
      title: "S3 aircraft fleet noise vs OSHA thresholds",
      subtitle: "Source: uploaded S3 visual; maintenance/run-up noise in dB.",
      type: "bar",
      xKey: "name",
      data: [{ name: "AH-64E", noise: 115 }, { name: "UH-60M", noise: 112 }, { name: "AH-6I", noise: 108 }, { name: "MD-530F", noise: 105 }, { name: "CH-47F", noise: 118 }],
      series: [{ dataKey: "noise", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 125],
      referenceLines: [
        { y: 85, stroke: "#f59e0b", strokeDasharray: "4 4" },
        { y: 90, stroke: "#ef4444", strokeDasharray: "4 4" },
      ],
      headline: "aircraft noise",
    },
    {
      id: "s3-hazard-gap",
      title: "S3 Saudi hazard severity vs Occu-Med gap",
      subtitle: "Source: uploaded S3 visual; scores 1-5.",
      type: "grouped",
      xKey: "name",
      data: [{ name: "Extreme Heat", severity: 5, gap: 4 }, { name: "JP-8/Skydrol", severity: 4, gap: 4 }, { name: "Helicopter Noise", severity: 4, gap: 3 }, { name: "Lead Exposure", severity: 3, gap: 4 }, { name: "Aviation Fatality", severity: 5, gap: 3 }, { name: "DBA Liability", severity: 5, gap: 5 }],
      series: [
        { dataKey: "severity", name: "Severity", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "gap", name: "Gap", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      headline: "hazard gap",
    },
    {
      id: "s3-workforce",
      title: "S3 workforce deployment by location",
      subtitle: "Source: uploaded S3 visual; worker count by location.",
      type: "bar",
      xKey: "name",
      data: [{ name: "Saudi Arabia", workers: 300 }, { name: "Africa/MENA", workers: 80 }, { name: "S/SE Asia", workers: 60 }, { name: "Europe/NATO", workers: 40 }, { name: "CONUS", workers: 200 }],
      series: [{ dataKey: "workers", color: "#dc2626", radius: [10, 10, 0, 0] }],
      headline: "workforce",
    },
    {
      id: "s3-revenue",
      title: "S3 Occu-Med revenue potential",
      subtitle: "Source: uploaded S3 visual; annual revenue in $K.",
      type: "bar",
      xKey: "name",
      data: [{ name: "DBA Pre-Deploy", value: 220 }, { name: "Heat Illness", value: 40 }, { name: "Hearing", value: 32 }, { name: "JP-8", value: 48 }, { name: "Lead", value: 28 }, { name: "Pilot Physicals", value: 26 }, { name: "Pre-Employment", value: 20 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "revenue potential",
    },
  ],
};
