import type { CompanyConfig } from "./types";

export const s3InternationalConfig: CompanyConfig = {
  companyId: "s3-international",
  displayName: "S3 International, Inc.",
  shortName: "S3I",
  sector:
    "OCONUS aviation training, maintenance, logistics, simulation support, C4ISR operations, FMS support, Saudi aviation sustainment, and DBA-covered expeditionary workforce services",
  headquarters: "Huntsville, Alabama / Riyadh, Saudi Arabia (S3 Arabia operational node)",
  employees: 680,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 19, 2026; modeled OCONUS + CONUS workforce deployment",
  summary:
    "S3 International, Inc. is the OCONUS arm of System Studies and Simulation, Inc. (S³), a woman-owned defense services company headquartered at 615 Discovery Drive in Huntsville, Alabama and led by founder and CEO Jan Smith. The uploaded Occu-Med intelligence report reframes the profile around S3I and S3 Arabia's aviation maintenance, flight operations, training, logistics, simulation support, and C4ISR work for partner nations. The core risk node is Team GDC ME in Riyadh, where 300+ workers support Saudi Arabian Ministry of National Guard aviation platforms under extreme heat, JP-8/Skydrol chemical exposure, high-noise helicopter maintenance, armament work, and DBA-covered OCONUS liability.",
  tags: [
    "Entity profile",
    "S3 International",
    "S3 Arabia",
    "S³ Inc.",
    "Saudi Arabia",
    "OCONUS aviation",
    "FMS",
    "SANG",
    "Team GDC ME",
    "DBA pre-deploy",
    "Extreme heat",
    "JP-8 exposure",
    "Skydrol exposure",
    "Helicopter noise",
    "Lead monitoring",
  ],
  aliases: ["S3I", "S3 International", "S3 International Inc", "S³", "S3 Inc", "System Studies and Simulation", "S3 Arabia", "Team GDC ME"],
  sourceFilters: {
    sam: { legalNames: ["S3 International, Inc.", "System Studies and Simulation, Inc.", "S3 Arabia"] },
    usaSpending: { recipientNames: ["S3 International", "System Studies and Simulation", "S3 Inc"] },
    jobSources: { linkedin: "s3-inc", careerSite: "https://www.s3inc.com/" },
    newsSources: {
      aliases: ["S3 International", "S3 Arabia", "System Studies and Simulation", "Team GDC ME", "Saudi Arabian Ministry of National Guard"],
      subsidiaries: ["Kachemak Bay Flying Services", "Global Logistics Support Services", "S3 AeroDefense"],
    },
  },
  executiveSignals: [
    {
      label: "Saudi risk node",
      value: "300+ workers",
      note: "Uploaded report identifies Team GDC ME / S3 Arabia in Riyadh as the operational center of gravity.",
    },
    {
      label: "Peak aircraft noise",
      value: "115+ dB",
      note: "AH-64E, UH-60M, AH-6i, MD-530F, and related aircraft maintenance exceed OSHA hearing-conservation thresholds.",
    },
    {
      label: "DBA liability gap",
      value: "5/5",
      note: "Every U.S. worker deployed OCONUS can trigger DBA coverage with no lifetime medical cap.",
    },
    {
      label: "Occu-Med potential",
      value: "$231K-$600K/yr",
      note: "Uploaded report models revenue across DBA pre-deployment, heat illness, hearing, chemical surveillance, lead monitoring, pilot physicals, and pre-employment exams.",
    },
  ],
  curveTitle: "S3 OCONUS aviation hazard, DBA liability, and surveillance curve",
  curveSubtitle:
    "Uploaded S3 International Occu-Med intelligence report normalized for entity-profile scanning; values are modeled operational risk and revenue signals, not audited S3 disclosures.",
  chartDefinitions: [
    {
      id: "s3-aircraft-noise",
      title: "S3 aircraft fleet noise vs OSHA thresholds",
      subtitle: "Uploaded report: helicopter maintenance and run-up noise creates hearing-conservation need.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "AH-64E", noise: 115 },
        { name: "UH-60M", noise: 112 },
        { name: "AH-6i", noise: 108 },
        { name: "MD-530F", noise: 105 },
        { name: "CH-47F", noise: 118 },
      ],
      series: [{ dataKey: "noise", name: "Noise dB", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 125],
      referenceLines: [
        { y: 85, stroke: "#f59e0b", strokeDasharray: "4 4", label: { value: "OSHA action level", fill: "#f59e0b", fontSize: 11 } },
        { y: 90, stroke: "#ef4444", strokeDasharray: "4 4", label: { value: "PEL", fill: "#ef4444", fontSize: 11 } },
      ],
      headline: "aircraft noise",
    },
    {
      id: "s3-hazard-gap",
      title: "S3 Saudi hazard severity vs Occu-Med gap",
      subtitle: "Uploaded report: hazard and gap scores for Riyadh aviation support operations.",
      type: "grouped",
      xKey: "name",
      data: [
        { name: "Extreme heat", severity: 5, gap: 4 },
        { name: "JP-8/Skydrol", severity: 4, gap: 4 },
        { name: "Helicopter noise", severity: 4, gap: 3 },
        { name: "Lead exposure", severity: 3, gap: 4 },
        { name: "Aviation fatality", severity: 5, gap: 3 },
        { name: "DBA liability", severity: 5, gap: 5 },
      ],
      series: [
        { dataKey: "severity", name: "Severity", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "gap", name: "Occu-Med gap", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      domain: [0, 5],
      headline: "hazard gap",
      fullWidth: true,
    },
    {
      id: "s3-workforce",
      title: "S3 workforce deployment by location",
      subtitle: "Uploaded report: Saudi Arabia is the highest-risk workforce concentration.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "Saudi Arabia", workers: 300, risk: 9 },
        { name: "Africa/MENA", workers: 80, risk: 7 },
        { name: "S/SE Asia", workers: 60, risk: 6 },
        { name: "Europe/NATO", workers: 40, risk: 4 },
        { name: "CONUS", workers: 200, risk: 0 },
      ],
      series: [{ dataKey: "workers", name: "Estimated workers", color: "#dc2626", radius: [10, 10, 0, 0] }],
      headline: "workforce",
    },
    {
      id: "s3-revenue",
      title: "S3 Occu-Med revenue potential",
      subtitle: "Uploaded report: total modeled potential of $231K-$600K/year.",
      type: "grouped",
      xKey: "name",
      data: [
        { name: "DBA pre-deploy", low: 140, high: 300 },
        { name: "Heat illness", low: 20, high: 60 },
        { name: "Hearing", low: 15, high: 50 },
        { name: "JP-8/benzene", low: 23, high: 75 },
        { name: "Lead monitoring", low: 10, high: 45 },
        { name: "Pilot physicals", low: 13, high: 40 },
        { name: "Pre-employment", low: 10, high: 30 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
      fullWidth: true,
    },
    {
      id: "s3-platform-hazards",
      title: "Aircraft platform hazard profile",
      subtitle: "Uploaded report: SANG aviation platforms drive armament, fuel, noise, vibration, and compressed gas exposure.",
      type: "bar",
      xKey: "platform",
      data: [
        { platform: "AH-64E Apache", risk: 10 },
        { platform: "UH-60M Black Hawk", risk: 8 },
        { platform: "AH-6i Little Bird", risk: 8 },
        { platform: "MD-530F Cayuse", risk: 7 },
      ],
      series: [{ dataKey: "risk", name: "Hazard priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "platform risk",
    },
  ],
  metricDefinitions: [
    { id: "s3-total-workers", label: "Modeled workers", value: 680, unit: "count", category: "workforce" },
    { id: "s3-saudi-workers", label: "Saudi Arabia workers", value: 300, unit: "count", category: "workforce" },
    { id: "s3-contract-locations", label: "Contract locations", value: 50, unit: "count", category: "workforce" },
    { id: "s3-states", label: "U.S. states", value: 15, unit: "count", category: "workforce" },
    { id: "s3-revenue-low", label: "Occu-Med revenue low", value: 0.231, unit: "usd", category: "financial" },
    { id: "s3-revenue-high", label: "Occu-Med revenue high", value: 0.6, unit: "usd", category: "financial" },
    { id: "s3-dba-high", label: "DBA pre-deploy revenue high", value: 0.3, unit: "usd", category: "risk" },
  ],
  riskMatrix: [
    { name: "Saudi aviation maintenance", revenue: 300, risk: 9.5, workers: 300 },
    { name: "DBA pre-deployment", revenue: 300, risk: 10.0, workers: 600 },
    { name: "Heat illness surveillance", revenue: 60, risk: 9.0, workers: 400 },
    { name: "JP-8 / benzene surveillance", revenue: 75, risk: 8.0, workers: 300 },
    { name: "Hearing conservation", revenue: 50, risk: 7.5, workers: 400 },
    { name: "Pilot physicals", revenue: 40, risk: 7.0, workers: 100 },
  ],
  opportunityMatrix: [
    { name: "DBA Pre-Deployment", revenuePotential: 300, implementationComplexity: 6, strategicValue: 10 },
    { name: "JP-8 / Benzene Surveillance", revenuePotential: 75, implementationComplexity: 8, strategicValue: 9 },
    { name: "Heat Illness Assessment", revenuePotential: 60, implementationComplexity: 6, strategicValue: 9 },
    { name: "Hearing Conservation", revenuePotential: 50, implementationComplexity: 4, strategicValue: 8 },
    { name: "Lead Monitoring", revenuePotential: 45, implementationComplexity: 7, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "S3 International is the OCONUS operating arm of S³, Inc. The uploaded report says S3I is the legal and operational vehicle for aviation training, maintenance, logistics, simulation support, and C4ISR work under FMS and IMET programs.",
      bullets: [
        "S3 International, Inc. is a wholly owned subsidiary of System Studies and Simulation, Inc.",
        "S³ is a woman-owned defense services company founded in 1991 and headquartered in Huntsville, Alabama.",
        "Founder and CEO Jan Smith is identified in the uploaded report.",
        "S³ operates at more than 50 contract locations across 15 U.S. states and multiple OCONUS locations.",
      ],
      metricIds: ["s3-total-workers", "s3-contract-locations", "s3-states"],
    },
    {
      type: "locations",
      title: "Saudi Arabia is the anchor risk node",
      narrative:
        "The uploaded report identifies Team GDC ME, a collaboration between GDC Middle East and S3 Arabia, as S3 International's operational center of gravity. The report says 300+ professionals support the Saudi Arabian Ministry of National Guard fleet from Riyadh.",
      bullets: [
        "Saudi Arabia workforce includes U.S. and Saudi pilots, trainers, maintainers, logisticians, and safety/quality-control specialists.",
        "Supported platforms include AH-64E Apache, UH-60M Black Hawk, AH-6i, and MD-530F aircraft.",
        "Workers perform full-spectrum military aviation maintenance and flight operations in extreme heat and OCONUS conditions.",
      ],
      metricIds: ["s3-saudi-workers"],
    },
    {
      type: "safety",
      title: "Extreme heat, JP-8, Skydrol, noise, and lead exposure",
      narrative:
        "The uploaded report is specific about the exposure stack: Riyadh flight-line heat, JP-8 fuel, Skydrol hydraulic fluid, helicopter run-up noise, armament lead exposure, and aviation fatality risk.",
      bullets: [
        "Riyadh summer ramp conditions can exceed standard WBGT heat category controls and require cardiovascular, acclimatization, and medication review protocols.",
        "JP-8 and benzene exposure create chronic occupational disease risk in aviation fuel and fuel-cell work.",
        "Skydrol is framed as an eye, skin, respiratory, and sensitizer exposure concern.",
        "Helicopter and armament work requires baseline and annual hearing conservation plus lead monitoring for applicable roles.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded report estimates $231K-$600K in annual Occu-Med potential. DBA pre-deployment is the largest lane, followed by heat illness, JP-8/benzene, hearing conservation, lead monitoring, pilot physicals, and pre-employment exams.",
      bullets: [
        "DBA pre-deployment: 400-600 annual volume; modeled $140K-$300K per year.",
        "Heat illness assessment: 200-400 annual volume; modeled $20K-$60K per year.",
        "JP-8/benzene chemical surveillance: 150-300 annual volume; modeled $23K-$75K per year.",
        "Hearing conservation: 200-400 annual volume; modeled $15K-$50K per year.",
      ],
      metricIds: ["s3-revenue-high", "s3-dba-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "This profile is derived from the uploaded S3 International Occu-Med intelligence report. Treat the workforce, hazard, and revenue values as modeled account intelligence rather than audited S3 disclosures.",
      bullets: [
        "Do not collapse S3 International, S3 Arabia, Kachemak Bay Flying Services, and Global Logistics Support Services into one undifferentiated workforce without preserving the relationship structure.",
        "Use DBA exposure and Saudi aviation hazards as the profile's primary sales thesis.",
        "Validate U.S. vs Saudi worker counts before operational pricing or service rollout.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "deep-analysis",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
