import type { CompanyConfig } from "./types";

export const saicConfig: CompanyConfig = {
  companyId: "saic",
  displayName: "SAIC (Science Applications International Corporation)",
  shortName: "SAIC",
  sector:
    "Federal mission integration, defense and intelligence IT, systems engineering, OCONUS support, training, cyber, and civilian agency technology services",
  headquarters: "McLean, Virginia",
  employees: 24000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 20, 2026; FY2025 workforce estimate",
  summary:
    "SAIC is a publicly traded federal mission integrator with approximately 24,000 employees and two FY2025 segments: Defense and Intelligence and Civilian. The uploaded Occu-Med report frames SAIC as a technology-services company whose physical injury rate is probably modest but whose disclosure gap, first-year worker injury concentration, ergonomic risk, OCONUS DBA exposure, and surge-hiring pattern still create a meaningful occupational medicine opportunity. The report's core point is that SAIC publishes no TRIR, no injury count, and no safety metrics in its annual reports or investor materials.",
  tags: [
    "Entity profile",
    "Federal mission integrator",
    "Defense and intelligence",
    "Cleared IT",
    "Systems engineering",
    "ESG disclosure gap",
    "First-year worker burden",
    "OCONUS DBA",
    "Ergonomics",
    "Navy FDTP",
    "COBRA",
  ],
  aliases: ["SAIC", "Science Applications International Corporation", "NASDAQ: SAIC"],
  sourceFilters: {
    sec: { ticker: "SAIC", legalEntities: ["Science Applications International Corporation"] },
    sam: { legalNames: ["Science Applications International Corporation", "SAIC"] },
    usaSpending: { recipientNames: ["SAIC", "Science Applications International"] },
    jobSources: { linkedin: "saicinc", careerSite: "https://jobs.saic.com/" },
    newsSources: { aliases: ["SAIC", "Science Applications International", "Navy FDTP", "COBRA contract"] },
  },
  executiveSignals: [
    {
      label: "Expected injuries",
      value: "147/yr",
      note: "Uploaded report models expected injuries using BLS benchmarks across a 24,000-person workforce.",
    },
    {
      label: "Disclosure gap",
      value: "No TRIR",
      note: "Report states SAIC publishes no TRIR, no injury count, and no safety metrics in annual/investor materials.",
    },
    {
      label: "First-year burden",
      value: "$12.5M/yr",
      note: "Modeled first-year worker share: 36% of injuries and 34% of claim costs, applied to roughly 3,600 new hires per year.",
    },
    {
      label: "Occu-Med potential",
      value: "$1.98M-$3.28M/yr",
      note: "Modeled opportunity across pre-employment, DBA pre-deployment, ergonomics, and drug screening lanes.",
    },
  ],
  curveTitle: "SAIC disclosure gap, first-year worker, and OCONUS DBA curve",
  curveSubtitle:
    "Uploaded Occu-Med report normalized into entity-profile charts; modeled estimates should be validated against SAIC's actual OSHA logs, hiring data, and deployed workforce counts.",
  chartDefinitions: [
    {
      id: "saic-five-numbers",
      title: "SAIC five exposure numbers that matter",
      subtitle: "Uploaded report: expected injuries, direct cost, total burden, DBA exposure, and fatality expected value.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Direct injury cost", value: 6.3 },
        { metric: "Economic burden", value: 34.8 },
        { metric: "Annual DBA exposure", value: 6.75 },
        { metric: "Fatality EV", value: 0.216 },
      ],
      series: [{ dataKey: "value", name: "Annual value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "modeled burden",
      fullWidth: true,
    },
    {
      id: "saic-segment-injuries",
      title: "SAIC expected injuries by workforce segment",
      subtitle: "Uploaded chart: cleared IT, systems engineering, analysts, OCONUS, and admin populations.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "Cleared IT & cyber", injuries: 50.0 },
        { segment: "Systems engineering", injuries: 42.0 },
        { segment: "Intel / mission analysts", injuries: 20.0 },
        { segment: "OCONUS deployed", injuries: 22.5 },
        { segment: "PM / admin", injuries: 12.5 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/yr", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "injury model",
      fullWidth: true,
    },
    {
      id: "saic-first-year-burden",
      title: "First-year worker injury concentration",
      subtitle: "Uploaded report applies Travelers 36% first-year injury concentration to SAIC hiring.",
      type: "bar",
      xKey: "cohort",
      data: [
        { cohort: "Remaining workforce", injuries: 94, burden: 22.3 },
        { cohort: "First-year workers", injuries: 53, burden: 12.5 },
      ],
      series: [
        { dataKey: "injuries", name: "Injuries/yr", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "burden", name: "Burden ($M)", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "new-hire burden",
    },
    {
      id: "saic-revenue-potential",
      title: "SAIC annual Occu-Med revenue potential",
      subtitle: "Uploaded report: total modeled opportunity of $1.98M-$3.28M/year.",
      type: "grouped",
      xKey: "examType",
      data: [
        { examType: "Pre-employment", low: 630, high: 900 },
        { examType: "DBA pre-deployment", low: 525, high: 750 },
        { examType: "Ergonomic assessment", low: 750, high: 1500 },
        { examType: "Drug screening", low: 72, high: 126 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
      fullWidth: true,
    },
    {
      id: "saic-risk-priority",
      title: "SAIC occupational medicine priority map",
      subtitle: "Report frames the opportunity around disclosure, first-year workers, ergonomics, and OCONUS DBA.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "Safety disclosure / TRIR", priority: 10 },
        { lane: "First-year pre-employment", priority: 9 },
        { lane: "OCONUS DBA baseline", priority: 9 },
        { lane: "SCIF ergonomics", priority: 8 },
        { lane: "Drug screening", priority: 5 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "risk lanes",
    },
  ],
  metricDefinitions: [
    { id: "saic-employees", label: "Employees", value: 24000, unit: "count", category: "workforce" },
    { id: "saic-fy25-revenue", label: "FY2025 revenue", value: 7.48, unit: "usd", category: "financial" },
    { id: "saic-expected-injuries", label: "Expected injuries/yr", value: 147, unit: "count", category: "safety" },
    { id: "saic-direct-cost", label: "Direct annual injury cost", value: 6.3, unit: "usd", category: "financial" },
    { id: "saic-economic-burden", label: "Total economic burden", value: 34.8, unit: "usd", category: "financial" },
    { id: "saic-dba-exposure", label: "Annual DBA exposure", value: 6.75, unit: "usd", category: "risk" },
    { id: "saic-first-year-burden", label: "First-year worker burden", value: 12.5, unit: "usd", category: "risk" },
    { id: "saic-revenue-high", label: "Occu-Med revenue high", value: 3.28, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "First-year workers", revenue: 900, risk: 8.5, workers: 3600 },
    { name: "OCONUS deployed", revenue: 750, risk: 9.0, workers: 1500 },
    { name: "SCIF ergonomics", revenue: 1500, risk: 7.0, workers: 15000 },
    { name: "Cleared IT / cyber", revenue: 400, risk: 4.5, workers: 8000 },
    { name: "Mission analysts", revenue: 300, risk: 5.5, workers: 4000 },
  ],
  opportunityMatrix: [
    { name: "Ergonomic assessment", revenuePotential: 1500, implementationComplexity: 6, strategicValue: 8 },
    { name: "Pre-employment physicals", revenuePotential: 900, implementationComplexity: 4, strategicValue: 9 },
    { name: "DBA pre-deployment", revenuePotential: 750, implementationComplexity: 6, strategicValue: 10 },
    { name: "Drug screening", revenuePotential: 126, implementationComplexity: 2, strategicValue: 5 },
    { name: "Disclosure benchmarking", revenuePotential: 250, implementationComplexity: 7, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "SAIC is a publicly traded federal mission integrator. The uploaded report argues that its occupational medicine problem is not classic industrial risk; it is the combination of no published safety metrics, rapid hiring, SCIF/ergonomics exposure, and OCONUS DBA work.",
      bullets: [
        "SAIC is modeled as a $7.48B federal mission integrator headquartered in McLean, Virginia.",
        "The workforce is approximately 24,000 employees, dominated by cleared IT professionals, systems engineers, and intelligence analysts.",
        "FY2025 segments are Defense and Intelligence at about $5.73B and Civilian at about $1.75B.",
        "The uploaded report says SAIC publishes no TRIR, no injury count, and no safety metrics in annual or investor materials.",
      ],
      metricIds: ["saic-employees", "saic-fy25-revenue", "saic-economic-burden"],
    },
    {
      type: "safety",
      title: "The IT-company assumption is incomplete",
      narrative:
        "The uploaded report says the technology-services framing is partly correct because expected TRIR is modest. But 147 injuries per year still create a modeled $34.8M total annual burden and a meaningful first-year worker risk concentration.",
      bullets: [
        "BLS-modeled expected TRIR is about 0.61 across SAIC's professional and mission-support workforce.",
        "The report models 147 expected injuries per year and $6.3M direct annual injury cost.",
        "First-year workers are the sales wedge: approximately 3,600 new hires per year and 53 expected injuries in that cohort.",
      ],
      metricIds: ["saic-expected-injuries", "saic-first-year-burden"],
    },
    {
      type: "contracts",
      title: "OCONUS and contract-driven risk",
      narrative:
        "SAIC's OCONUS exposure is less visible than KBR or IAP, but the uploaded report identifies Navy FDTP, COBRA, and other mission-support work as pathways to DBA-covered deployment or reach-back support.",
      bullets: [
        "Navy Fleet Deployment Training Program support creates reach-back support to deployed strike groups and amphibious ready groups.",
        "COBRA and similar warfighting support programs create classified mission environments where baseline documentation can matter.",
        "DBA exposure is modeled at $6.75M annually using 22.5 OCONUS injuries and a $300K average claim assumption.",
      ],
      metricIds: ["saic-dba-exposure"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded report estimates $1.98M-$3.28M in annual Occu-Med potential, concentrated in pre-employment physicals, DBA pre-deployment exams, remote/hybrid ergonomic assessment, and pre-employment drug screening.",
      bullets: [
        "Pre-employment physicals: 3,600 new hires; modeled $630K-$900K per year.",
        "DBA pre-deployment exams: 1,500 OCONUS workers; modeled $525K-$750K per year.",
        "Ergonomic assessments: 10,000-15,000 workers; modeled $750K-$1.5M per year.",
        "Drug screening: 3,600 screens; modeled $72K-$126K per year.",
      ],
      metricIds: ["saic-revenue-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "This profile is derived from the uploaded Occu-Med intelligence report. Treat injury, DBA, and revenue values as BLS/NSC/OSHA/Travelers-modeled sales intelligence rather than audited SAIC safety disclosures.",
      bullets: [
        "Do not state that SAIC has a poor safety program; the report says SAIC does not publish enough data to benchmark it.",
        "Use the disclosure gap and first-year worker concentration as the account-opening logic.",
        "Validate all OCONUS and DBA worker counts with SAIC before operational pricing.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "executive-summary",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
