import type { CompanyConfig } from "./types";

export const sercoConfig: CompanyConfig = {
  companyId: "serco",
  displayName: "Serco Group plc / Serco Inc.",
  shortName: "Serco",
  sector:
    "Government services, defense support, military transition counseling, facilities maintenance, Navy vessel operations, air traffic control, intelligence IT, and federal healthcare staffing",
  headquarters: "Hook, United Kingdom / Herndon, Virginia (Serco Inc. US HQ)",
  employees: 50000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 20, 2026",
  summary:
    "Serco Group plc is a British government services entity with approximately 50,000 global employees and a large North America division. The uploaded Occu-Med intelligence report focuses on Serco Inc., the US subsidiary headquartered in Herndon, Virginia, with roughly 20,000 US workers across a diverse occupational portfolio: Army facilities maintenance and repair, DoD/VA clinical staffing, Navy vessel operations, TAP counselors, intelligence/IT, air traffic control, and corporate support. The report argues that Serco's UK RIDDOR safety disclosures do not translate cleanly to US OSHA TRIR, creating a visibility gap for North America leadership.",
  tags: [
    "Entity profile",
    "Government services",
    "Serco Inc.",
    "North America growth",
    "RIDDOR to OSHA gap",
    "TAP counselors",
    "DBA exposure",
    "Clinical staffing",
    "Facilities maintenance",
    "Navy vessel operations",
    "Air traffic control",
  ],
  aliases: ["Serco", "Serco Group plc", "Serco Group PLC", "Serco Inc.", "Serco Inc", "SRP"],
  sourceFilters: {
    sec: { legalEntities: ["Serco Group plc"] },
    sam: { legalNames: ["Serco Inc.", "Serco Inc"] },
    usaSpending: { recipientNames: ["Serco", "Serco Inc", "Serco Group"] },
    jobSources: { linkedin: "serco", careerSite: "https://www.serco.com/na/careers" },
    newsSources: { aliases: ["Serco", "Serco Group", "Serco Inc", "Serco North America", "Serco TAP"] },
  },
  executiveSignals: [
    {
      label: "Expected injuries",
      value: "200.5/yr",
      note: "Uploaded model applies BLS benchmarks to roughly 20,000 US workers across seven occupational lanes.",
    },
    {
      label: "Economic burden",
      value: "$47.4M/yr",
      note: "Modeled direct annual injury cost of $8.62M multiplied by OSHA indirect cost factor.",
    },
    {
      label: "DBA exposure",
      value: "$360K/yr",
      note: "Modeled annual DBA exposure from OCONUS TAP/support injuries; core risk is missing pre-deployment baseline documentation.",
    },
    {
      label: "Occu-Med potential",
      value: "$1.52M–$2.34M/yr",
      note: "Modeled annual opportunity across pre-employment physicals, clinical/TB screening, hearing, respirator, and DBA pre-deployment lanes.",
    },
  ],
  curveTitle: "Serco US workforce, OSHA visibility, and occupational medicine curve",
  curveSubtitle:
    "Uploaded Occu-Med intelligence values normalized for entity-profile scanning; modeled estimates should be treated as assumption-driven signals, not audited employer disclosures.",
  chartDefinitions: [
    {
      id: "serco-five-numbers",
      title: "Serco five exposure numbers that matter",
      subtitle: "Source: uploaded Serco Occu-Med intelligence report; modeled injury, cost, DBA, and fatality values.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Direct injury cost", value: 8.62 },
        { metric: "Economic burden", value: 47.4 },
        { metric: "DBA claim exposure", value: 0.36 },
        { metric: "Fatality EV", value: 0.0198 },
      ],
      series: [{ dataKey: "value", name: "Annual exposure", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "exposure model",
      fullWidth: true,
    },
    {
      id: "serco-injuries-by-business-line",
      title: "Expected injuries by US business line",
      subtitle: "Uploaded chart: Army facilities and healthcare staffing dominate modeled injury volume.",
      type: "bar",
      xKey: "businessLine",
      data: [
        { businessLine: "TAP counseling", injuries: 12.0 },
        { businessLine: "Army facilities", injuries: 75.0 },
        { businessLine: "Navy vessel", injuries: 18.0 },
        { businessLine: "ATC ops", injuries: 3.0 },
        { businessLine: "Intel / IT", injuries: 25.0 },
        { businessLine: "Healthcare clinical", injuries: 37.5 },
        { businessLine: "PM / corporate", injuries: 30.0 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/yr", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "injury concentration",
      fullWidth: true,
    },
    {
      id: "serco-business-line-trir",
      title: "BLS benchmark TRIR by Serco US business line",
      subtitle: "BLS risk profile from uploaded report; facilities maintenance is the highest modeled TRIR lane.",
      type: "bar",
      xKey: "businessLine",
      data: [
        { businessLine: "Army facilities", trir: 2.5 },
        { businessLine: "Healthcare", trir: 1.5 },
        { businessLine: "Navy vessel", trir: 1.8 },
        { businessLine: "TAP counselors", trir: 0.6 },
        { businessLine: "Intel / IT", trir: 0.5 },
        { businessLine: "ATC / tower", trir: 0.6 },
        { businessLine: "PM / corporate", trir: 0.5 },
      ],
      series: [{ dataKey: "trir", name: "BLS TRIR benchmark", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 3],
      headline: "TRIR benchmark",
    },
    {
      id: "serco-tap-oconus-dba",
      title: "TAP counselors: OCONUS deployment and DBA exposure",
      subtitle: "Uploaded chart: about 2,000 TAP counselors across 250+ installations; active OCONUS share creates DBA baseline need.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "CONUS", counselors: 1600 },
        { region: "Europe", counselors: 150 },
        { region: "INDOPACOM", counselors: 120 },
        { region: "CENTCOM", counselors: 80 },
        { region: "Other OCONUS", counselors: 50 },
      ],
      series: [{ dataKey: "counselors", name: "TAP counselors", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "TAP footprint",
    },
    {
      id: "serco-riddor-osha-gap",
      title: "UK RIDDOR metric vs OSHA TRIR translation",
      subtitle: "Uploaded report: Serco's UK LTI/RIDDOR safety metric cannot be benchmarked directly against US OSHA TRIR.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "UK RIDDOR equivalent", rate: 0.65 },
        { metric: "OSHA TRIR sensitivity", rate: 1.0 },
        { metric: "OSHA WC benchmark", rate: 1.0 },
      ],
      series: [{ dataKey: "rate", name: "Relative capture rate", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 1.2],
      headline: "metric gap",
    },
    {
      id: "serco-revenue-potential",
      title: "Serco Inc. Occu-Med annual revenue potential",
      subtitle: "Uploaded report: full-service opportunity range of $1.52M-$2.34M/year across core exam lanes.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Pre-employment", low: 525, high: 750 },
        { examType: "TB / clinical", low: 250, high: 438 },
        { examType: "Hearing", low: 300, high: 500 },
        { examType: "Respirator", low: 300, high: 450 },
        { examType: "DBA pre-deploy", low: 140, high: 200 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
      fullWidth: true,
    },
    {
      id: "serco-compliance-priority",
      title: "Serco occupational medicine compliance priority map",
      subtitle: "High-value medical protocol lanes implied by the uploaded risk model.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "OSHA 300/TRIR consolidation", priority: 10 },
        { lane: "Clinical BBP/TB protocol", priority: 10 },
        { lane: "DBA pre-deploy baseline", priority: 9 },
        { lane: "Facilities respirator/hearing", priority: 9 },
        { lane: "Ergonomics / CTD", priority: 7 },
        { lane: "ATC fatigue/acoustics", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Priority score", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "compliance lanes",
    },
  ],
  metricDefinitions: [
    { id: "serco-global-employees", label: "Global employees", value: 50000, unit: "count", category: "workforce" },
    { id: "serco-us-employees", label: "US employees", value: 20000, unit: "count", category: "workforce" },
    { id: "serco-expected-injuries", label: "Expected US injuries/yr", value: 200.5, unit: "count", category: "safety" },
    { id: "serco-direct-cost", label: "Direct injury cost", value: 8.62, unit: "usd", category: "financial" },
    { id: "serco-economic-burden", label: "Total economic burden", value: 47.4, unit: "usd", category: "financial" },
    { id: "serco-dba-exposure", label: "Annual DBA claim exposure", value: 0.36, unit: "usd", category: "risk" },
    { id: "serco-occumed-revenue-high", label: "Occu-Med revenue potential high", value: 2.34, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Army facilities maintenance", revenue: 323, risk: 8.5, workers: 3000 },
    { name: "Healthcare / clinical staffing", revenue: 250, risk: 8.0, workers: 2500 },
    { name: "Navy vessel operations", revenue: 150, risk: 7.0, workers: 1000 },
    { name: "TAP counselors OCONUS", revenue: 193, risk: 6.5, workers: 2000 },
    { name: "Intel / IT", revenue: 300, risk: 3.5, workers: 5000 },
    { name: "ATC / tower ops", revenue: 80, risk: 5.0, workers: 500 },
  ],
  opportunityMatrix: [
    { name: "Pre-Employment Physicals", revenuePotential: 750, implementationComplexity: 4, strategicValue: 9 },
    { name: "Clinical TB / BBP Protocol", revenuePotential: 438, implementationComplexity: 7, strategicValue: 10 },
    { name: "Hearing Conservation", revenuePotential: 500, implementationComplexity: 5, strategicValue: 8 },
    { name: "Respirator Clearances", revenuePotential: 450, implementationComplexity: 5, strategicValue: 8 },
    { name: "DBA Pre-Deployment", revenuePotential: 200, implementationComplexity: 6, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Serco is a UK parent with a large and strategically important North America division. The uploaded report says North America generated more than 40% of group divisional underlying operating profit in H1 2025, making Serco Inc.'s occupational medicine posture material to the group.",
      bullets: [
        "Serco Group plc is a £4.8B British government services company with approximately 50,000 global employees.",
        "Serco Inc. is headquartered in Herndon, Virginia and has roughly 20,000 US workers.",
        "North America is the group's most valuable division by underlying operating profit share in the uploaded report.",
        "The US workforce spans facilities trades, clinical staffing, vessel operations, TAP counseling, IT/intelligence, ATC, and corporate support.",
      ],
      metricIds: ["serco-global-employees", "serco-us-employees", "serco-economic-burden"],
    },
    {
      type: "workforce",
      title: "Seven-lane US workforce risk model",
      narrative:
        "Serco looks like a professional services entity at the parent-brand level, but the uploaded model shows that its US workforce includes construction-like facilities maintenance, clinical staffing, vessel operations, and DBA-covered TAP counselors.",
      bullets: [
        "Army facilities maintenance and repair is the largest modeled injury lane, driven by HVAC, electrical, carpentry, painting, and facility repair work.",
        "Clinical staffing introduces bloodborne pathogen, TB, needlestick, patient-handling, and N95 respirator clearance requirements.",
        "Navy vessel operations involve marine environment, confined-space, heavy equipment, and hearing conservation exposure.",
        "Intel/IT, ATC, and corporate populations add ergonomic, fatigue, acoustic, and sedentary CTD risk.",
      ],
      metricIds: ["serco-expected-injuries", "serco-direct-cost"],
    },
    {
      type: "safety",
      title: "RIDDOR to OSHA visibility gap",
      narrative:
        "The report says Serco's headline safety metric is UK RIDDOR-based, while its US operations are governed by OSHA. RIDDOR over-7-day injury reporting misses medical-treatment and restricted-duty cases that OSHA TRIR captures, making the UK metric unsuitable for benchmarking the US workforce.",
      bullets: [
        "Serco reported a 22% reduction in Lost Time Incidents in 2024 under its Zero Harm framing.",
        "The uploaded report argues that RIDDOR captures fewer incidents than OSHA TRIR because OSHA includes medical treatment beyond first aid and restricted duty.",
        "Serco's US OSHA 300 logs may be maintained at contract level instead of consolidated into a company-wide US TRIR.",
        "The sales frame is visibility and consolidation, not accusing Serco of having a poor safety culture.",
      ],
      metricIds: [],
    },
    {
      type: "contracts",
      title: "TAP OCONUS deployment and DBA protocol",
      narrative:
        "The uploaded report highlights Serco's DOL Veterans' Employment and Training Services TAP contract as a DBA baseline-documentation problem. TAP counselors are not physically high-risk like construction workers, but OCONUS placement creates unlimited DBA medical benefit exposure without a pre-deployment baseline.",
      bullets: [
        "The TAP contract is identified as a $193M, five-year recompete supporting roughly 200,000 transitioning service members annually.",
        "The report says Serco places approximately 2,000 TAP counselors at 250+ US military installations, both CONUS and OCONUS.",
        "Example OCONUS locations include Ramstein Air Base, Camp Humphreys, Yokota Air Base, and NAS Rota.",
        "The DBA pre-deployment medical is framed as pre-existing-condition documentation before an injury becomes a DBA claim.",
      ],
      metricIds: ["serco-dba-exposure"],
    },
    {
      type: "safety",
      title: "Clinical worker compliance blind spot",
      narrative:
        "Serco's DoD and VA healthcare staffing operation introduces an occupational medicine requirement that generic walk-in pre-employment physicals do not usually cover: TB screening, hepatitis B status, OSHA bloodborne pathogen documentation, post-exposure protocols, patient-handling ergonomics, and respirator clearance.",
      bullets: [
        "Clinical workers may include nurses, medical technicians, dental assistants, behavioral health counselors, and health educators.",
        "OSHA 1910.1030 bloodborne pathogen compliance requires documentation before exposure.",
        "N95 or other respirator-required clinical environments require OSHA 1910.134 medical clearance.",
        "Pre-employment QuantiFERON/TST and annual TB surveillance are key clinical placement controls.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The uploaded model estimates $1.52M-$2.34M in annual Occu-Med revenue potential across pre-employment physicals, clinical/TB screening, hearing conservation, respirator clearance, and DBA pre-deployment exams.",
      bullets: [
        "Pre-employment physicals: 3,000+ new hires; modeled $525K-$750K per year.",
        "TB / clinical pre-employment: 2,500 healthcare workers; modeled $250K-$438K per year.",
        "Hearing conservation: 4,000 facilities and vessel-operations workers; modeled $300K-$500K per year.",
        "Respirator clearances: 3,000 facilities-maintenance workers; modeled $300K-$450K per year.",
        "DBA pre-deployment: 400 OCONUS TAP counselors; modeled $140K-$200K per year.",
      ],
      metricIds: ["serco-occumed-revenue-high"],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "Serco values in this profile are source-backed but model-driven. The charts should be interpreted as Occu-Med intelligence estimates derived from the uploaded Serco report, BLS benchmarks, NSC/OSHA cost assumptions, DBA assumptions, and the RIDDOR-to-OSHA translation analysis.",
      bullets: [
        "Do not present modeled injury, DBA, cost, or revenue projections as audited Serco disclosures.",
        "Label the profile as an uploaded Occu-Med intelligence model.",
        "Treat the RIDDOR-to-OSHA gap as a sales/visibility thesis requiring verification with Serco's actual US OSHA 300 logs.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "executive-summary",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: false,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
