import type { CompanyConfig } from "./types";

export const sierraNevadaConfig: CompanyConfig = {
  companyId: "sierra-nevada",
  displayName: "Sierra Nevada Corporation",
  shortName: "SNC",
  sector:
    "Aerospace, national security systems, aircraft modification, ISR platforms, high-altitude balloons, SAOC modernization, HADES integration, defense electronics, stratospheric ISR, and international aerospace manufacturing",
  headquarters: "Sparks, Nevada",
  employees: 4500,
  employeesAsOf:
    "Uploaded Gemini operational presence file: existing public estimate retained; profile upgraded from stub with 40+ global locations and major aviation/ISR hubs",
  summary:
    "Sierra Nevada Corporation is a privately held aerospace and national security systems integrator headquartered in Sparks, Nevada. The uploaded operational presence file upgrades SNC from a pending stub into a location-specific profile. SNC operates through more than 40 locations worldwide, with major hubs in the United States, the United Kingdom, Germany, and Turkey. The highest-value Occu-Med interpretation is aviation modification and ISR readiness: Hagerstown converts Bombardier Global 6500 aircraft into HADES deep-sensing ISR platforms; Dayton/Vandalia hosts 747-sized hangars for the $13B Survivable Airborne Operations Center modernization effort; Wichita supports testing, digital twin, and risk-reduction work; St Athan in the UK supports Project Aether stratospheric ISR; and Deutsche Aircraft in Leipzig/Wessling supports D328eco engineering and manufacturing. This is not a generic office-IT account. The medical lanes are aviation MRO, confined/hangar work, hearing conservation, respirator/chemical exposure, travel/deployment readiness, ergonomic/industrial strain, and specialized flight/field support.",
  tags: [
    "Entity profile",
    "Sierra Nevada Corporation",
    "SNC",
    "HADES",
    "SAOC",
    "Aviation Innovation Center",
    "Dayton AITC",
    "Hagerstown",
    "Stratospheric ISR",
    "Project Aether",
    "Deutsche Aircraft",
    "TRJet",
    "D328eco",
    "Aircraft modification",
    "Aviation MRO",
  ],
  aliases: ["SNC", "Sierra Nevada Corp", "Sierra Nevada Corporation", "SNC Mission Systems UK", "Deutsche Aircraft", "TRJet"],
  sourceFilters: {
    sam: { legalNames: ["Sierra Nevada Corporation", "Sierra Nevada Company"] },
    usaSpending: { recipientNames: ["Sierra Nevada Corporation", "SNC"] },
    jobSources: { linkedin: "sierra-nevada-corporation", careerSite: "https://www.sncorp.com/careers/" },
    newsSources: { aliases: ["Sierra Nevada Corporation", "SNC HADES", "SNC SAOC", "Project Aether", "Deutsche Aircraft D328eco"] },
  },
  executiveSignals: [
    { label: "Global footprint", value: "40+ locations", note: "Uploaded operational presence file says SNC operates through more than 40 locations worldwide." },
    { label: "SAOC program", value: "$13B", note: "Uploaded file identifies Dayton AITC as supporting the $13B Survivable Airborne Operations Center modernization program." },
    { label: "HADES hub", value: "Hagerstown", note: "Hagerstown converts Bombardier Global 6500 aircraft into HADES ISR platforms." },
    { label: "International ISR", value: "UK / Germany / Turkey", note: "St Athan, Leipzig/Wessling, and Ankara are major international operational nodes." },
  ],
  curveTitle: "Sierra Nevada aviation modification, ISR, SAOC, and international hub curve",
  curveSubtitle:
    "Uploaded operational presence file normalized into an entity profile. Workforce and exposure counts require validation against current program staffing.",
  chartDefinitions: [
    {
      id: "snc-operational-hubs",
      title: "SNC operational hub priority",
      subtitle: "Major hubs from the uploaded operational presence file.",
      type: "bar",
      xKey: "hub",
      data: [
        { hub: "Sparks NV", priority: 8 },
        { hub: "Hagerstown MD", priority: 10 },
        { hub: "Dayton OH", priority: 10 },
        { hub: "Wichita KS", priority: 8 },
        { hub: "Fayetteville NC", priority: 7 },
        { hub: "Herndon/DC", priority: 7 },
        { hub: "St Athan UK", priority: 9 },
        { hub: "Leipzig/Wessling DE", priority: 8 },
        { hub: "Ankara TR", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Operational priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "hub priority",
      fullWidth: true,
    },
    {
      id: "snc-program-medical-fit",
      title: "SNC program medical fit",
      subtitle: "Aviation modification, ISR integration, and hangar work drive the occupational-health logic.",
      type: "bar",
      xKey: "program",
      data: [
        { program: "HADES aircraft conversion", fit: 10 },
        { program: "SAOC heavy modification", fit: 10 },
        { program: "Project Aether HAB", fit: 8 },
        { program: "Deutsche Aircraft OEM", fit: 8 },
        { program: "RF geolocation services", fit: 6 },
        { program: "TRJet production", fit: 7 },
      ],
      series: [{ dataKey: "fit", name: "Medical fit", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "medical fit",
    },
    {
      id: "snc-occumed-wedges",
      title: "SNC Occu-Med service wedges",
      subtitle: "Aerospace modification and fielded ISR systems create non-office occupational health demand.",
      type: "bar",
      xKey: "wedge",
      data: [
        { wedge: "Aviation MRO physicals", priority: 10 },
        { wedge: "Hearing conservation", priority: 9 },
        { wedge: "Respirator / chemical clearance", priority: 8 },
        { wedge: "Hangar ergonomics", priority: 8 },
        { wedge: "Travel/deployment readiness", priority: 7 },
        { wedge: "Flight support baseline", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "service wedges",
    },
  ],
  metricDefinitions: [
    { id: "snc-global-locations", label: "Global locations", value: 40, unit: "count", category: "workforce" },
    { id: "snc-employees", label: "Employees estimate", value: 4500, unit: "count", category: "workforce" },
    { id: "snc-saoc-value", label: "SAOC program value", value: 13, unit: "usd", category: "financial" },
    { id: "snc-operational-fit", label: "Aviation/MRO fit score", value: 10, unit: "score", category: "risk" },
  ],
  riskMatrix: [
    { name: "Hagerstown HADES", revenue: 200, risk: 9.0, workers: 500 },
    { name: "Dayton SAOC", revenue: 300, risk: 9.5, workers: 700 },
    { name: "St Athan Project Aether", revenue: 120, risk: 8.0, workers: 250 },
    { name: "Deutsche Aircraft", revenue: 160, risk: 8.0, workers: 400 },
    { name: "Sparks HQ/R&D", revenue: 90, risk: 5.5, workers: 600 },
  ],
  opportunityMatrix: [
    { name: "Aviation MRO Surveillance", revenuePotential: 250, implementationComplexity: 6, strategicValue: 9 },
    { name: "SAOC Program Readiness", revenuePotential: 300, implementationComplexity: 7, strategicValue: 10 },
    { name: "HADES Integration Exams", revenuePotential: 200, implementationComplexity: 6, strategicValue: 9 },
    { name: "UK / Project Aether Readiness", revenuePotential: 120, implementationComplexity: 8, strategicValue: 8 },
    { name: "Germany OEM Provider Coverage", revenuePotential: 150, implementationComplexity: 8, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Aerospace and ISR systems entity",
      narrative:
        "SNC should be treated as a specialty aerospace and national-security systems integrator, not a standard federal IT contractor.",
      bullets: [
        "Hagerstown is the HADES aircraft-conversion hub.",
        "Dayton/Vandalia hosts AITC heavy modification work for SAOC.",
        "St Athan supports UK Project Aether stratospheric ISR.",
        "Germany and Turkey subsidiaries create international aviation/manufacturing exposure.",
      ],
      metricIds: ["snc-global-locations", "snc-saoc-value"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The correct pitch is aviation and fielded-systems readiness: MRO exams, hearing conservation, respirator/chemical clearance, hangar ergonomics, travel readiness, and specialty program support.",
      bullets: [
        "Do not pitch only office physicals.",
        "Tie the medical argument to aircraft conversion, hangar work, ISR field support, and global program sites.",
      ],
      metricIds: ["snc-operational-fit"],
    },
  ],
};
