import type { CompanyConfig } from "./types";

export const skybridgeTacticalConfig: CompanyConfig = {
  companyId: "skybridge-tactical",
  displayName: "SkyBridge Tactical, LLC",
  shortName: "SkyBridge Tactical",
  sector:
    "SOF logistics, expeditionary training, mobile technology repair, GLOBALCAP/AFRICAP support, ALECS/VEMOS maintenance, sUAS/live-fire training, OCONUS field support, and DBA-covered deployed workforce readiness",
  headquarters: "Tampa, Florida",
  employees: 300,
  employeesAsOf:
    "Uploaded Gemini operational presence file: workforce not verified; modeled as small-to-mid specialty expeditionary contractor pending roster confirmation",
  summary:
    "SkyBridge Tactical is a Service-Disabled Veteran-Owned Small Business headquartered in Tampa, Florida. The uploaded operational presence file describes a specialized SOF-adjacent contractor with CONUS headquarters/training nodes and OCONUS project sites supporting peacekeeping, expeditionary logistics, SOF maintenance, robotics, and training missions. Key facilities include Tampa headquarters, the Granite Creek Range Complex in Sheridan, Montana, Crane, Indiana for Mobile Technology Repair Complex work, Bloomington, Fort Leonard Wood, Selfridge ANGB, Orlando, El Paso, San Diego, Coronado, Savannah, and Pensacola. OCONUS work includes Kabul, Kampala, Ouagadougou, Kaduna, Kuwait, Iraq, and Italy. This is a high-specificity occupational medicine profile: live-fire/sUAS training, SOF equipment repair, robotics support, MRAP/RCV maintenance, desert training, travel readiness, OCONUS DBA baselines, and expeditionary medical documentation.",
  tags: [
    "Entity profile",
    "SkyBridge Tactical",
    "SDVOSB",
    "SOF support",
    "Granite Creek Range Complex",
    "MTRC",
    "GLOBALCAP",
    "AFRICAP",
    "ALECS",
    "VEMOS",
    "sUAS training",
    "Live-fire range",
    "Robotics logistics",
    "OCONUS",
    "DBA",
  ],
  aliases: ["SkyBridge Tactical", "SBT", "SkyBridge Tactical LLC", "Granite Creek Range Complex"],
  sourceFilters: {
    sam: { legalNames: ["SkyBridge Tactical, LLC", "SkyBridge Tactical"] },
    usaSpending: { recipientNames: ["SkyBridge Tactical"] },
    jobSources: { careerSite: "https://www.skybridgetactical.com/" },
    newsSources: { aliases: ["SkyBridge Tactical", "Granite Creek Range Complex", "Mobile Technology Repair Complex", "AFRICAP", "GLOBALCAP"] },
  },
  executiveSignals: [
    { label: "HQ", value: "Tampa", note: "Uploaded file identifies Tampa, Florida as the corporate headquarters and program-management node." },
    { label: "Training range", value: "6,000 acres", note: "Granite Creek Range Complex in Sheridan, Montana is described as a 6,000-acre high-altitude live-fire/sUAS training site." },
    { label: "Core mission", value: "MTRC / SOF", note: "Crane, Indiana and Kabul are tied to Mobile Technology Repair Complex support for SOF systems." },
    { label: "OCONUS nodes", value: "7+", note: "Uploaded file lists Afghanistan, Uganda, Burkina Faso, Nigeria, Kuwait, Iraq, and Italy project lanes." },
  ],
  curveTitle: "SkyBridge Tactical expeditionary training, SOF repair, and OCONUS readiness curve",
  curveSubtitle:
    "Uploaded operational presence file normalized into an entity profile. Workforce and exam volume are strategic estimates pending staffing validation.",
  chartDefinitions: [
    {
      id: "skybridge-operational-nodes",
      title: "SkyBridge Tactical operational node priority",
      subtitle: "CONUS and OCONUS nodes from the uploaded operational presence file.",
      type: "bar",
      xKey: "node",
      data: [
        { node: "Tampa FL", priority: 8 },
        { node: "Sheridan MT GCRC", priority: 10 },
        { node: "Crane IN MTRC", priority: 10 },
        { node: "Fort Leonard Wood", priority: 8 },
        { node: "El Paso / Fort Bliss", priority: 8 },
        { node: "San Diego / Coronado", priority: 8 },
        { node: "Kabul", priority: 9 },
        { node: "Kampala", priority: 8 },
        { node: "Italy ALECS", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Operational priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "nodes",
      fullWidth: true,
    },
    {
      id: "skybridge-exposure-map",
      title: "SkyBridge occupational exposure map",
      subtitle: "This is a small specialty contractor with high field-risk specificity.",
      type: "bar",
      xKey: "exposure",
      data: [
        { exposure: "Live-fire / sUAS range", priority: 10 },
        { exposure: "SOF equipment repair", priority: 9 },
        { exposure: "Robotics support", priority: 8 },
        { exposure: "MRAP / RCV maintenance", priority: 9 },
        { exposure: "Desert training", priority: 8 },
        { exposure: "OCONUS DBA", priority: 10 },
      ],
      series: [{ dataKey: "priority", name: "Medical priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "exposure map",
    },
    {
      id: "skybridge-occumed-wedges",
      title: "SkyBridge Occu-Med service wedges",
      subtitle: "Training and expeditionary missions need pre-deployment baselines, injury documentation, and specialty readiness exams.",
      type: "bar",
      xKey: "wedge",
      data: [
        { wedge: "DBA pre-deployment", priority: 10 },
        { wedge: "Range / live-fire baseline", priority: 9 },
        { wedge: "Hearing conservation", priority: 9 },
        { wedge: "Respirator / dust exposure", priority: 7 },
        { wedge: "Heat / austere readiness", priority: 8 },
        { wedge: "RTW documentation", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "service wedge",
    },
  ],
  metricDefinitions: [
    { id: "skybridge-gcrc-acres", label: "GCRC acres", value: 6000, unit: "count", category: "risk" },
    { id: "skybridge-oconus-nodes", label: "OCONUS nodes", value: 7, unit: "count", category: "workforce" },
    { id: "skybridge-medical-fit", label: "DBA/readiness fit", value: 10, unit: "score", category: "risk" },
  ],
  riskMatrix: [
    { name: "Granite Creek Range", revenue: 100, risk: 9.5, workers: 60 },
    { name: "MTRC / SOF repair", revenue: 120, risk: 9.0, workers: 80 },
    { name: "OCONUS deployments", revenue: 150, risk: 10.0, workers: 120 },
    { name: "Robotics support", revenue: 60, risk: 7.5, workers: 50 },
    { name: "ALECS / MRAP maintenance", revenue: 100, risk: 8.5, workers: 80 },
  ],
  opportunityMatrix: [
    { name: "DBA Readiness Program", revenuePotential: 150, implementationComplexity: 6, strategicValue: 10 },
    { name: "Live-Fire / sUAS Baselines", revenuePotential: 100, implementationComplexity: 6, strategicValue: 9 },
    { name: "Hearing Conservation", revenuePotential: 75, implementationComplexity: 4, strategicValue: 8 },
    { name: "SOF Repair Team Baselines", revenuePotential: 120, implementationComplexity: 5, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Small specialty contractor with high mission specificity",
      narrative:
        "SkyBridge Tactical is not a high-headcount account. It is valuable because the work is specialized, deployable, and risky: live-fire training, SOF repair, robotics, MRAP/RCV maintenance, and OCONUS project support.",
      bullets: [
        "Tampa is the corporate/program node.",
        "Sheridan, Montana hosts the Granite Creek Range Complex.",
        "Crane, Indiana and Kabul are tied to Mobile Technology Repair Complex work.",
        "Kampala, Burkina Faso, Nigeria, Kuwait, Iraq, and Italy create OCONUS readiness lanes.",
      ],
      metricIds: ["skybridge-gcrc-acres", "skybridge-oconus-nodes"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The pitch should center on expeditionary readiness and documentation: DBA baselines, hearing conservation, live-fire/range fitness, heat and austere-environment screening, and return-to-work documentation.",
      bullets: [
        "This should be positioned as a specialty support account, not generic physical volume.",
        "Provider coverage should align to Tampa, Sheridan, Crane/Bloomington, El Paso, San Diego/Coronado, and OCONUS project nodes.",
      ],
      metricIds: ["skybridge-medical-fit"],
    },
  ],
};
