import type { CompanyConfig } from "./types";

export const sosiConfig: CompanyConfig = {
  companyId: "sosi",
  displayName: "SOSi (SOS International LLC)",
  shortName: "SOSi",
  sector:
    "Intelligence analysis, cyber, IT, language services, base operations, OCONUS maintenance, CARE mission support, EUCOM/AFCENT network operations, translation/interpreting, and deployed mission support",
  headquarters: "Reston, Virginia",
  employees: 2200,
  employeesAsOf:
    "Uploaded Gemini operational presence file: existing public estimate retained; profile upgraded from stub with OCONUS and domestic mission-site detail",
  summary:
    "SOSi is a private mid-tier mission-solutions contractor headquartered in Reston, Virginia. The uploaded operational presence file upgrades SOSi from a pending stub into a location-specific intelligence profile. SOSi operates across domestic and international locations with heavy concentration in active military theaters and command headquarters. Domestic nodes include Reston, Vienna, Tampa/MacDill, Pearl Harbor, Fort Huachuca, Fort Belvoir, New York, Fort Liberty, Redstone Arsenal, El Paso/Fort Bliss, Fort Eisenhower, Chantilly, and Charleston. OCONUS nodes include Al Udeid, Doha, As Sayliyah, Camp Taji, Balad Air Base, Besmaya, Camp Arifjan, Wiesbaden, Ramstein, Kaiserslautern, Frankfurt, Grafenwoehr, NSA Bahrain, Camp Zama, Soto Cano, Kabul, and South Sudan. The Occu-Med wedge is mixed: deployed/OCONUS readiness, base operations and O&M, electrical/facility work, linguist/interpreter strain, intelligence analyst behavioral health/ergonomics, and DBA baselines.",
  tags: [
    "Entity profile",
    "SOSi",
    "SOS International",
    "Intelligence analysis",
    "Language services",
    "OCONUS",
    "Al Udeid",
    "CARE Mission",
    "Camp Taji",
    "Wiesbaden",
    "Ramstein",
    "NSA Bahrain",
    "Camp Zama",
    "DBA",
    "Base operations",
  ],
  aliases: ["SOSi", "SOS International", "SOS International LLC", "SOSi Mission Solutions"],
  sourceFilters: {
    sam: { legalNames: ["SOS International LLC", "SOSi"] },
    usaSpending: { recipientNames: ["SOS International", "SOSi"] },
    jobSources: { linkedin: "sosi", careerSite: "https://www.sosi.com/careers/" },
    newsSources: { aliases: ["SOSi", "SOS International", "CARE mission Doha", "SOSi Wiesbaden", "SOSi Al Udeid"] },
  },
  executiveSignals: [
    { label: "HQ", value: "Reston", note: "Uploaded file identifies Reston, Virginia as SOSi headquarters." },
    { label: "Regional hub", value: "Qatar / Iraq", note: "Qatar and Iraq are described as primary OCONUS base operations and CARE mission lanes." },
    { label: "European hub", value: "Wiesbaden", note: "Wiesbaden is identified as an intelligence support hub for USAREUR-AF G2." },
    { label: "Service mix", value: "Intel + O&M", note: "The profile combines intelligence/language work with facility O&M and base-support exposure." },
  ],
  curveTitle: "SOSi intelligence, OCONUS base operations, and language-support medical curve",
  curveSubtitle:
    "Uploaded operational presence file normalized into an entity profile. Workforce and exam-volume assumptions require validation by program/site.",
  chartDefinitions: [
    {
      id: "sosi-operational-nodes",
      title: "SOSi operational node priority",
      subtitle: "Domestic and OCONUS nodes from the uploaded operational presence file.",
      type: "bar",
      xKey: "node",
      data: [
        { node: "Reston / Vienna VA", priority: 8 },
        { node: "Tampa / MacDill", priority: 8 },
        { node: "Al Udeid / Doha", priority: 10 },
        { node: "Iraq sites", priority: 10 },
        { node: "Camp Arifjan", priority: 8 },
        { node: "Wiesbaden / Ramstein", priority: 9 },
        { node: "NSA Bahrain", priority: 8 },
        { node: "Camp Zama", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Operational priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "nodes",
      fullWidth: true,
    },
    {
      id: "sosi-service-risk-lanes",
      title: "SOSi service and risk lanes",
      subtitle: "SOSi is both knowledge-workforce and field-support/base-ops exposure.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "Intelligence analysis", priority: 8 },
        { lane: "Language / interpreting", priority: 8 },
        { lane: "Base O&M", priority: 9 },
        { lane: "Electrical/facility support", priority: 8 },
        { lane: "OCONUS logistics", priority: 9 },
        { lane: "DBA readiness", priority: 10 },
      ],
      series: [{ dataKey: "priority", name: "Risk priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "risk lanes",
    },
    {
      id: "sosi-occumed-wedges",
      title: "SOSi Occu-Med service wedges",
      subtitle: "Deployed personnel, interpreters, analysts, and base-support workers need different medical lanes.",
      type: "bar",
      xKey: "wedge",
      data: [
        { wedge: "DBA pre-deployment", priority: 10 },
        { wedge: "Base O&M physicals", priority: 9 },
        { wedge: "Electrical/respirator clearances", priority: 8 },
        { wedge: "Interpreter voice/hearing", priority: 7 },
        { wedge: "Behavioral health / STS", priority: 8 },
        { wedge: "Ergonomics / visual strain", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "service wedges",
    },
  ],
  metricDefinitions: [
    { id: "sosi-employees", label: "Employees estimate", value: 2200, unit: "count", category: "workforce" },
    { id: "sosi-node-count", label: "Modeled nodes", value: 30, unit: "count", category: "workforce" },
    { id: "sosi-dba-fit", label: "DBA readiness fit", value: 10, unit: "score", category: "risk" },
    { id: "sosi-base-ops-fit", label: "Base O&M medical fit", value: 9, unit: "score", category: "risk" },
  ],
  riskMatrix: [
    { name: "Qatar / CARE mission", revenue: 180, risk: 9.0, workers: 300 },
    { name: "Iraq base support", revenue: 220, risk: 10.0, workers: 400 },
    { name: "Germany intelligence hub", revenue: 120, risk: 7.5, workers: 250 },
    { name: "Language/interpreting", revenue: 90, risk: 6.5, workers: 300 },
    { name: "Domestic intel/cyber", revenue: 100, risk: 5.5, workers: 800 },
  ],
  opportunityMatrix: [
    { name: "DBA / OCONUS Baseline Program", revenuePotential: 250, implementationComplexity: 6, strategicValue: 10 },
    { name: "Base O&M Medical Surveillance", revenuePotential: 180, implementationComplexity: 6, strategicValue: 9 },
    { name: "Interpreter Hearing / Voice Program", revenuePotential: 75, implementationComplexity: 4, strategicValue: 7 },
    { name: "Analyst Behavioral Health Protocol", revenuePotential: 100, implementationComplexity: 7, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Mixed intelligence and base-operations profile",
      narrative:
        "SOSi should not be treated as purely office-based intelligence work or purely field operations. The uploaded file shows both: intelligence/language/cyber support plus OCONUS base operations, maintenance, and facility support.",
      bullets: [
        "Reston and Vienna anchor the corporate/intelligence presence.",
        "Qatar and Iraq are the highest-priority OCONUS base operations and CARE mission lanes.",
        "Wiesbaden/Ramstein/Kaiserslautern create a Germany intelligence/network corridor.",
        "NSA Bahrain, Camp Zama, Soto Cano, Kabul, and South Sudan add distributed OCONUS exposure.",
      ],
      metricIds: ["sosi-employees", "sosi-node-count"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The best pitch combines DBA readiness with site-specific occupational medicine: base O&M exams, electrical/facility support, interpreter hearing/voice concerns, analyst behavioral health, and ergonomic/visual-strain programs.",
      bullets: [
        "OCONUS and base operations create higher medical need than a normal IT profile.",
        "Language and intelligence work create behavioral-health, voice, hearing, ergonomic, and clearance-sensitive documentation needs.",
      ],
      metricIds: ["sosi-dba-fit", "sosi-base-ops-fit"],
    },
  ],
};
