import type { CompanyConfig } from "./types";

export const sourceGroupConfig: CompanyConfig = {
  companyId: "source-group",
  displayName: "The Source Group, Inc. / SGI Environmental / Apex-SGI",
  shortName: "The Source Group",
  sector:
    "Environmental consulting, petroleum HAZMAT remediation, DLA Energy remediation, HAZWOPER medical surveillance, benzene surveillance, respirator clearance, hazardous-waste operations, and long-retention occupational medicine documentation",
  headquarters: "California-based environmental consulting and remediation firm / Apex-SGI brand following Apex Companies acquisition",
  employees: 120,
  employeesAsOf:
    "Uploaded The Source Group report: approximately 120 field workers, including about 105 workers requiring annual HAZWOPER surveillance through March 2030",
  summary:
    "The Source Group, Inc. is modeled here as SGI Environmental / Apex-SGI, a California-based environmental engineering and remediation firm with DLA Energy work at Southern California petroleum fuel facilities. The uploaded report identifies the active contract lane as DLA Energy remediation at DFSP Norwalk and DFSP San Pedro under a $42.3M ceiling contract running from September 2025 through March 2030. This is not a generic physical-exam account. SGI's petroleum HAZMAT workforce is among the most regulated small workforces in the portfolio: HAZWOPER medical surveillance under OSHA 29 CFR 1910.120(f), benzene-specific surveillance under 1910.1028, respirator clearance under 1910.134, physician written opinions within 15 working days, and medical-record retention for employment duration plus 30 years. The Occu-Med opportunity is mandatory, recurring, physician-intensive surveillance revenue — roughly $92K-$136K per year — not discretionary wellness spending.",
  tags: [
    "Entity profile",
    "The Source Group",
    "SGI Environmental",
    "Apex-SGI",
    "Apex Companies",
    "DLA Energy",
    "DFSP Norwalk",
    "DFSP San Pedro",
    "HAZWOPER",
    "Benzene surveillance",
    "Respirator clearance",
    "Physician written opinion",
    "30-year retention",
    "Petroleum remediation",
  ],
  aliases: ["The Source Group", "The Source Group, Inc.", "SGI Environmental", "Apex-SGI", "Apex SGI", "Apex Companies"],
  sourceFilters: {
    sam: { legalNames: ["The Source Group, Inc.", "SGI Environmental", "Apex Companies"] },
    usaSpending: { recipientNames: ["The Source Group", "SGI Environmental", "Apex Companies"] },
    newsSources: { aliases: ["The Source Group", "SGI Environmental", "Apex-SGI", "DFSP Norwalk", "DFSP San Pedro", "DLA Energy remediation"] },
  },
  executiveSignals: [
    {
      label: "Mandatory exams",
      value: "~105/yr",
      note: "Uploaded report models about 105 workers requiring annual HAZWOPER surveillance under OSHA 1910.120(f).",
    },
    {
      label: "Benzene surveillance",
      value: "~90 workers",
      note: "Petroleum HAZMAT sites routinely trigger benzene action-level surveillance assumptions in the uploaded report.",
    },
    {
      label: "Contract runway",
      value: "2025-2030",
      note: "DLA Energy contract lane runs from September 2025 through March 2030.",
    },
    {
      label: "Occu-Med revenue",
      value: "$92K-$136K/yr",
      note: "Mandatory recurring HAZWOPER, benzene, and respirator medical surveillance revenue estimate.",
    },
  ],
  curveTitle: "The Source Group HAZWOPER, benzene, and mandatory surveillance curve",
  curveSubtitle:
    "Uploaded The Source Group report normalized into an entity profile. Treat surveillance counts and revenue as strategic estimates pending actual worker roster and exposure-monitoring validation.",
  chartDefinitions: [
    {
      id: "source-group-five-numbers",
      title: "The Source Group five numbers that matter",
      subtitle: "Mandatory surveillance model from uploaded SGI / Apex-SGI report.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Direct injury cost", value: 0.091 },
        { metric: "Economic burden", value: 0.503 },
        { metric: "Occu-Med low", value: 0.092 },
        { metric: "Occu-Med high", value: 0.136 },
      ],
      series: [{ dataKey: "value", name: "Annual value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "mandatory spend",
      fullWidth: true,
    },
    {
      id: "source-group-surveillance-cascade",
      title: "HAZWOPER medical surveillance cascade",
      subtitle: "OSHA-triggered exam population from uploaded report; exams are mandatory, not discretionary.",
      type: "bar",
      xKey: "exam",
      data: [
        { exam: "Pre-employment HAZWOPER", workers: 24 },
        { exam: "Annual HAZWOPER", workers: 105 },
        { exam: "Benzene surveillance", workers: 90 },
        { exam: "Respirator clearance", workers: 89 },
        { exam: "Termination exam", workers: 12 },
      ],
      series: [{ dataKey: "workers", name: "Workers / exams", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "surveillance cascade",
    },
    {
      id: "source-group-revenue-by-exam",
      title: "Estimated annual Occu-Med revenue by surveillance lane",
      subtitle: "Uploaded report: total annual opportunity of $92K-$136K across mandatory exam categories.",
      type: "grouped",
      xKey: "exam",
      data: [
        { exam: "Pre-employment", low: 9.6, high: 14.4 },
        { exam: "Annual HAZWOPER", low: 42, high: 63 },
        { exam: "Benzene CBC+diff", low: 31.5, high: 45 },
        { exam: "Respirator clearance", low: 8.9, high: 13.3 },
      ],
      series: [
        { dataKey: "low", name: "Low", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "high", name: "High", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "recurring revenue",
      fullWidth: true,
    },
    {
      id: "source-group-clinic-gap",
      title: "Why this is not a walk-in clinic account",
      subtitle: "The uploaded report emphasizes physician written opinions, benzene CBC interpretation, respirator clearance, and 30-year record retention.",
      type: "bar",
      xKey: "requirement",
      data: [
        { requirement: "PWO within 15 days", priority: 10 },
        { requirement: "HAZWOPER history", priority: 9 },
        { requirement: "Benzene CBC+diff", priority: 10 },
        { requirement: "Respirator clearance", priority: 9 },
        { requirement: "30-year records", priority: 10 },
      ],
      series: [{ dataKey: "priority", name: "Specialty requirement", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "clinic gap",
    },
    {
      id: "source-group-site-priority",
      title: "DLA Energy site priority",
      subtitle: "Uploaded report centers SGI work at Southern California petroleum fuel facilities.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "DFSP Norwalk", priority: 10 },
        { site: "DFSP San Pedro", priority: 10 },
        { site: "Petroleum groundwater O&M", priority: 9 },
        { site: "Soil remediation", priority: 9 },
        { site: "Vapor monitoring", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Medical surveillance priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "site logic",
    },
  ],
  metricDefinitions: [
    { id: "source-group-workers", label: "Approximate workforce", value: 120, unit: "count", category: "workforce" },
    { id: "source-group-hazwoper-workers", label: "Annual HAZWOPER workers", value: 105, unit: "count", category: "risk" },
    { id: "source-group-benzene-workers", label: "Benzene surveillance workers", value: 90, unit: "count", category: "risk" },
    { id: "source-group-injuries", label: "Expected injuries/yr", value: 2.1, unit: "count", category: "safety" },
    { id: "source-group-direct-cost", label: "Direct annual injury cost", value: 0.091, unit: "usd", category: "financial" },
    { id: "source-group-economic-burden", label: "Total economic burden", value: 0.503, unit: "usd", category: "financial" },
    { id: "source-group-revenue-low", label: "Occu-Med revenue low", value: 0.092, unit: "usd", category: "financial" },
    { id: "source-group-revenue-high", label: "Occu-Med revenue high", value: 0.136, unit: "usd", category: "financial" },
    { id: "source-group-contract-end", label: "Contract end year", value: 2030, unit: "count", category: "financial" },
  ],
  riskMatrix: [
    { name: "HAZWOPER field workers", revenue: 63, risk: 10.0, workers: 105 },
    { name: "Benzene surveillance", revenue: 45, risk: 10.0, workers: 90 },
    { name: "Respirator users", revenue: 13.3, risk: 8.0, workers: 89 },
    { name: "Pre-employment HAZWOPER", revenue: 14.4, risk: 8.5, workers: 24 },
    { name: "Termination exams", revenue: 6, risk: 7.5, workers: 12 },
  ],
  opportunityMatrix: [
    { name: "Annual HAZWOPER Surveillance", revenuePotential: 63, implementationComplexity: 7, strategicValue: 10 },
    { name: "Benzene CBC + Differential Program", revenuePotential: 45, implementationComplexity: 8, strategicValue: 10 },
    { name: "Pre-Employment HAZWOPER Exams", revenuePotential: 14.4, implementationComplexity: 6, strategicValue: 8 },
    { name: "Respirator Medical Clearance", revenuePotential: 13.3, implementationComplexity: 5, strategicValue: 8 },
    { name: "30-Year Record Retention Program", revenuePotential: 10, implementationComplexity: 8, strategicValue: 9 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "The Source Group / SGI Environmental is a small account by headcount, but unusually strong as an occupational medicine fit because the work creates mandatory federal surveillance requirements.",
      bullets: [
        "California-based environmental consulting and remediation firm now operating under Apex-SGI after Apex Companies acquired SGI in 2016.",
        "Uploaded report identifies DLA Energy remediation at DFSP Norwalk and DFSP San Pedro as the active contract lane.",
        "Contract period runs September 2025 through March 2030 with a $42.3M ceiling in the uploaded report.",
        "The account is driven by HAZWOPER and benzene surveillance, not generic injury volume.",
      ],
      metricIds: ["source-group-workers", "source-group-hazwoper-workers", "source-group-revenue-high"],
    },
    {
      type: "safety",
      title: "HAZWOPER and benzene mandates",
      narrative:
        "The uploaded report's central claim is that nearly every field worker at contaminated petroleum remediation sites is subject to non-discretionary surveillance requirements. A generic pre-employment physical is not enough.",
      bullets: [
        "OSHA 1910.120(f) drives pre-employment, annual, exposure-triggered, and termination medical surveillance.",
        "OSHA 1910.1028 benzene surveillance requires CBC with differential and platelet count in the proper occupational context.",
        "Respirator use triggers OSHA 1910.134 medical clearance.",
        "A physician's written opinion must be provided within 15 working days for HAZWOPER surveillance.",
      ],
      metricIds: ["source-group-benzene-workers"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The selling point is compliance precision and record durability. SGI needs a provider that understands HAZWOPER medical opinions, benzene testing, respirator clearance, and 30-year record retention.",
      bullets: [
        "Mandatory annual HAZWOPER surveillance creates the largest recurring revenue lane.",
        "Benzene-specific surveillance creates a lab-and-physician interpretation lane that walk-in clinics often miss.",
        "Employment-plus-30-year record retention is both a compliance requirement and a litigation defense asset.",
        "This is a small account, but it is one of the clearest compliance-fit accounts in the portfolio.",
      ],
      metricIds: ["source-group-revenue-low", "source-group-revenue-high"],
    },
  ],
};
