import type { CompanyConfig } from "./types";

const defaultSignals = [
  { label: "Status", value: "Pending", note: "Detailed intelligence report not yet uploaded." },
  { label: "Sector", value: "—", note: "Sector-specific signals will populate when data is available." },
  { label: "Workforce", value: "—", note: "Workforce sizing pending uploaded report." },
  { label: "Risk profile", value: "—", note: "Risk profile pending uploaded report analysis." },
];

export const jacobsConfig: CompanyConfig = {
  companyId: "jacobs",
  displayName: "Jacobs Solutions Inc.",
  shortName: "Jacobs",
  sector: "Engineering, technology, cyber, scientific consulting, and government services",
  headquarters: "Dallas, Texas",
  employees: 60000,
  employeesAsOf: "2025 public estimate",
  summary: "Global engineering and technology services company with government, infrastructure, and advanced facilities programs.",
  tags: ["Engineering", "Government services", "Cyber", "Infrastructure"],
  aliases: ["Jacobs Engineering", "Jacobs Solutions"],
  sourceFilters: {
    sec: { ticker: "J", legalEntities: ["Jacobs Solutions Inc."] },
    newsSources: { aliases: ["Jacobs", "Jacobs Engineering"] },
  },
  executiveSignals: [
    { label: "Employees", value: "~60,000", note: "Large global engineering and technology workforce." },
    { label: "Sector", value: "Engineering", note: "Engineering, construction, and government services." },
    { label: "Headquarters", value: "Dallas, TX", note: "Relocated from Pasadena to Dallas." },
    { label: "Risk profile", value: "Pending", note: "Detailed risk analysis pending uploaded intelligence report." },
  ],
  curveTitle: "Jacobs engineering and services curve",
  curveSubtitle: "Global engineering, government services, and infrastructure values normalized for executive scanning.",
  chartDefinitions: [],
};

export const baeConfig: CompanyConfig = {
  companyId: "bae-systems",
  displayName: "BAE Systems",
  shortName: "BAE",
  sector: "Defense, aerospace, electronic systems, intelligence, and security",
  headquarters: "Falls Church, Virginia (US HQ)",
  employees: 93500,
  employeesAsOf: "2025 public estimate",
  summary: "BAE Systems is one of the world's largest defense contractors with electronic systems, platforms and services, intelligence, and security operations across the US, UK, Saudi Arabia, and Australia.",
  tags: ["Defense", "Aerospace", "Electronic systems", "Intelligence", "Shipbuilding"],
  aliases: ["BAE Systems Inc", "BAE Systems plc"],
  sourceFilters: {
    sec: { legalEntities: ["BAE Systems plc"] },
    newsSources: { aliases: ["BAE Systems", "BAE"] },
  },
  executiveSignals: [
    { label: "Employees", value: "~93,500", note: "One of the world's largest defense workforces." },
    { label: "US presence", value: "~35,000", note: "Major US defense electronics and shipbuilding presence." },
    { label: "Sector", value: "Defense/Aerospace", note: "Electronic warfare, vehicle systems, and naval defense." },
    { label: "Risk profile", value: "Pending", note: "Detailed risk analysis pending uploaded intelligence report." },
  ],
  curveTitle: "BAE Systems defense and aerospace curve",
  curveSubtitle: "Defense, electronic systems, and intelligence values normalized for executive scanning.",
  chartDefinitions: [],
};

export const qinetiqConfig: CompanyConfig = {
  companyId: "qinetiq",
  displayName: "QinetiQ Group plc",
  shortName: "QinetiQ",
  sector: "Defense technology, test and evaluation, training, advisory, and mission-critical solutions",
  headquarters: "Farnborough, UK / McLean, Virginia (US)",
  employees: 8500,
  employeesAsOf: "2025 public estimate",
  summary: "UK-headquartered defense technology company with US operations in test and evaluation, training, advisory services, and mission-critical solution delivery.",
  tags: ["Defense technology", "Test & evaluation", "Training", "UK-based"],
  aliases: ["QinetiQ US", "QinetiQ Group"],
  executiveSignals: defaultSignals,
  curveTitle: "QinetiQ defense technology curve",
  curveSubtitle: "Test and evaluation, training, and advisory services normalized for executive scanning.",
  chartDefinitions: [],
};

export const asrcFederalConfig: CompanyConfig = {
  companyId: "asrc-federal",
  displayName: "ASRC Federal Holding Company",
  shortName: "ASRC Federal",
  sector: "IT modernization, engineering, cyber, intelligence, and mission support",
  headquarters: "Beltsville, Maryland",
  employees: 4000,
  employeesAsOf: "2025 public estimate",
  summary: "Alaska Native Corporation-owned federal contractor delivering IT modernization, engineering, cybersecurity, intelligence, and mission-support services to federal agencies.",
  tags: ["ANC", "IT modernization", "Cybersecurity", "Intelligence", "8(a)"],
  aliases: ["ASRC Federal"],
  executiveSignals: defaultSignals,
  curveTitle: "ASRC Federal services and technology curve",
  curveSubtitle: "IT modernization, engineering, and intelligence values normalized for executive scanning.",
  chartDefinitions: [],
};

export const alutiiqConfig: CompanyConfig = {
  companyId: "alutiiq",
  displayName: "Alutiiq, LLC",
  shortName: "Alutiiq",
  sector: "Facilities management, security, logistics, IT, and government services",
  headquarters: "Anchorage, Alaska",
  employees: 3500,
  employeesAsOf: "2025 public estimate",
  summary: "Alaska Native Corporation subsidiary providing facilities management, base operations, security, logistics, and IT services to government agencies.",
  tags: ["ANC", "Facilities management", "Security", "Logistics", "8(a)"],
  aliases: ["Alutiiq LLC", "Afognak Native Corporation"],
  executiveSignals: defaultSignals,
  curveTitle: "Alutiiq facilities and services curve",
  curveSubtitle: "Facilities management, security, and logistics values normalized for executive scanning.",
  chartDefinitions: [],
};

export const internationalSosConfig: CompanyConfig = {
  companyId: "international-sos",
  displayName: "International SOS",
  shortName: "Intl SOS",
  sector: "Medical assistance, security risk management, travel security, and expatriate healthcare",
  headquarters: "London, UK / Trevose, Pennsylvania (Americas HQ)",
  employees: 12000,
  employeesAsOf: "2025 public estimate",
  summary: "Global medical assistance and security risk management company providing expatriate healthcare, travel security, and occupational health services to government and corporate clients worldwide.",
  tags: ["Medical assistance", "Travel security", "Expatriate healthcare", "Global operations"],
  aliases: ["International SOS", "Intl SOS", "iSOS"],
  executiveSignals: defaultSignals,
  curveTitle: "International SOS medical and security curve",
  curveSubtitle: "Medical assistance, travel security, and expatriate healthcare normalized for executive scanning.",
  chartDefinitions: [],
};

export const hiiMissionTechConfig: CompanyConfig = {
  companyId: "hii-mission-technologies",
  displayName: "HII Mission Technologies",
  shortName: "HII MT",
  sector: "C5ISR, cyber, electronic warfare, fleet modernization, unmanned systems, and defense technology",
  headquarters: "McLean, Virginia",
  employees: 44000,
  employeesAsOf: "2025 HII total estimate",
  summary: "Mission Technologies division of Huntington Ingalls Industries providing C5ISR, cyber, electronic warfare, fleet modernization, unmanned systems, and defense technology solutions.",
  tags: ["C5ISR", "Cyber", "Electronic warfare", "Unmanned systems", "HII"],
  aliases: ["HII Mission Technologies", "Huntington Ingalls Industries"],
  sourceFilters: {
    sec: { ticker: "HII", legalEntities: ["Huntington Ingalls Industries, Inc."] },
    newsSources: { aliases: ["HII", "Huntington Ingalls", "HII Mission Technologies"] },
  },
  executiveSignals: defaultSignals,
  curveTitle: "HII Mission Technologies defense curve",
  curveSubtitle: "C5ISR, cyber, electronic warfare, and unmanned systems values normalized for executive scanning.",
  chartDefinitions: [],
};

export const sosiConfig: CompanyConfig = {
  companyId: "sosi",
  displayName: "SOSi (SOS International LLC)",
  shortName: "SOSi",
  sector: "Intelligence analysis, cyber, IT, logistics, and language services",
  headquarters: "Reston, Virginia",
  employees: 2200,
  employeesAsOf: "2025 public estimate",
  summary: "SOSi delivers intelligence analysis, IT, cyber, logistics, and language services to defense and intelligence community customers with OCONUS deployment exposure.",
  tags: ["Intelligence", "Cyber", "Logistics", "Language services", "OCONUS"],
  aliases: ["SOSi", "SOS International"],
  executiveSignals: defaultSignals,
  curveTitle: "SOSi intelligence and services curve",
  curveSubtitle: "Intelligence, cyber, and OCONUS deployment values normalized for executive scanning.",
  chartDefinitions: [],
};

export const sierraConfig: CompanyConfig = {
  companyId: "sierra-nevada",
  displayName: "Sierra Nevada Corporation",
  shortName: "SNC",
  sector: "Aerospace, defense electronics, space systems, aircraft modification, and tactical systems",
  headquarters: "Sparks, Nevada",
  employees: 4500,
  employeesAsOf: "2025 public estimate",
  summary: "Privately held aerospace and defense contractor specializing in aircraft modification, space systems, electronic warfare, and tactical ISR systems.",
  tags: ["Aerospace", "Space systems", "Electronic warfare", "Aircraft modification"],
  aliases: ["SNC", "Sierra Nevada Corp"],
  executiveSignals: defaultSignals,
  curveTitle: "Sierra Nevada aerospace and defense curve",
  curveSubtitle: "Aerospace, space systems, and electronic warfare values normalized for executive scanning.",
  chartDefinitions: [],
};

export const datapathConfig: CompanyConfig = {
  companyId: "datapath",
  displayName: "DataPath Inc.",
  shortName: "DataPath",
  sector: "Satellite communications, managed network services, cybersecurity, and defense communications",
  headquarters: "Duluth, Georgia",
  employees: 800,
  employeesAsOf: "2025 public estimate",
  summary: "Satellite communications and managed network services provider supporting military, government, and enterprise customers with OCONUS deployment and field-service exposure.",
  tags: ["SATCOM", "Managed networks", "Cybersecurity", "Field service"],
  aliases: ["DataPath", "DataPath Inc"],
  executiveSignals: defaultSignals,
  curveTitle: "DataPath communications and services curve",
  curveSubtitle: "SATCOM, managed networks, and cybersecurity values normalized for executive scanning.",
  chartDefinitions: [],
};

export const omniplexConfig: CompanyConfig = {
  companyId: "omniplex",
  displayName: "Omniplex World Services",
  shortName: "Omniplex",
  sector: "Background investigations, security clearance processing, and government personnel security",
  headquarters: "Chantilly, Virginia",
  employees: 1500,
  employeesAsOf: "2025 public estimate",
  summary: "Omniplex provides background investigations and personnel security services for federal agencies, with field-investigator ergonomic and driving exposure.",
  tags: ["Background investigations", "Security clearance", "Field investigators", "DCSA"],
  aliases: ["Omniplex World Services", "OWS"],
  executiveSignals: defaultSignals,
  curveTitle: "Omniplex investigations and security curve",
  curveSubtitle: "Background investigations, field-investigator risk, and security processing values normalized for executive scanning.",
  chartDefinitions: [],
};

export const ssiConfig: CompanyConfig = {
  companyId: "ssi",
  displayName: "SSI (Strategic Solutions International)",
  shortName: "SSI",
  sector: "Intelligence, training, security, OCONUS deployment, and defense advisory",
  headquarters: "Fayetteville, North Carolina",
  employees: 500,
  employeesAsOf: "2025 public estimate",
  summary: "Strategic Solutions International provides intelligence, training, security, and advisory services with OCONUS deployment exposure in hostile environments.",
  tags: ["Intelligence", "Training", "Security", "OCONUS", "SOF support"],
  aliases: ["SSI", "Strategic Solutions International"],
  executiveSignals: defaultSignals,
  curveTitle: "SSI intelligence and training curve",
  curveSubtitle: "Intelligence, OCONUS training, and security values normalized for executive scanning.",
  chartDefinitions: [],
};

export const platformAerospaceConfig: CompanyConfig = {
  companyId: "platform-aerospace",
  displayName: "Platform Aerospace",
  shortName: "Platform",
  sector: "ISR aviation, unmanned aircraft, intelligence collection, and defense aviation support",
  headquarters: "Huntsville, Alabama",
  employees: 300,
  employeesAsOf: "2025 public estimate",
  summary: "ISR and unmanned aircraft systems operator providing intelligence collection and defense aviation support services. Aviation maintenance and flight-operations safety exposure.",
  tags: ["ISR", "UAS", "Aviation", "Intelligence collection"],
  aliases: ["Platform Aerospace", "Platform"],
  executiveSignals: defaultSignals,
  curveTitle: "Platform Aerospace ISR and aviation curve",
  curveSubtitle: "ISR, unmanned aircraft, and aviation maintenance values normalized for executive scanning.",
  chartDefinitions: [],
};

export const celConfig: CompanyConfig = {
  companyId: "cel",
  displayName: "CEL (Computer & Engineering Leaders)",
  shortName: "CEL",
  sector: "IT staffing, engineering services, government technology support, and professional services",
  headquarters: "Washington, D.C.",
  employees: 400,
  employeesAsOf: "2025 public estimate",
  summary: "IT staffing and engineering services provider supporting government technology programs. Low operational-hazard profile with standard office and data-center exposure.",
  tags: ["IT staffing", "Engineering services", "Government technology"],
  aliases: ["CEL"],
  executiveSignals: defaultSignals,
  curveTitle: "CEL technology and staffing curve",
  curveSubtitle: "IT staffing, engineering services, and government technology support normalized for executive scanning.",
  chartDefinitions: [],
};
