import type { CompanyConfig } from "./types";

export const tecmotivConfig: CompanyConfig = {
  companyId: "tecmotiv",
  displayName: "Tecmotiv (USA), Inc.",
  shortName: "Tecmotiv",
  sector:
    "Military vehicle engine overhaul, AVDS 1790 diesel engine remanufacturing, legacy combat vehicle powertrain support, DLA/TACOM/FMS support, asbestos surveillance, diesel exhaust, carbon monoxide, noise/HCP, machine shop hazards, and OCONUS field service support",
  headquarters: "Niagara Falls, Ontario / US facility at 1500 James Avenue, Niagara Falls, New York",
  employees: 150,
  employeesAsOf:
    "Uploaded Tecmotiv Occu-Med report: approximately 150 US workers, including 45 engine overhaul workers, 40 machine shop workers, 20 engine test-cell workers, 25 parts/warehouse workers, 15 FSRs, and 5 engineering/admin workers",
  summary:
    "Tecmotiv (USA), Inc. is the US subsidiary of Tecmotiv Corporation and is modeled in the uploaded report as the premier vendor for remanufactured, rebuilt, and overhauled AVDS 1790 Series diesel engines and powertrain components for legacy US military combat vehicles: M60 Patton, M88 Hercules, M109 Paladin, M113, and V150 Commando fleets. It is small by headcount but high in surveillance complexity. The uploaded report's core point is that Tecmotiv workers are tearing down, machining, rebuilding, and testing engines built from 1959 through the 1980s, including legacy asbestos-containing gaskets, diesel exhaust exposure, CO exposure in test cells, machine-shop noise, heavy lift, solvents, cutting fluids, forklift/warehouse hazards, and OCONUS field service support across more than 20 countries. The Occu-Med wedge is not injury volume; it is the difference between a generic urgent-care physical and a proper medical surveillance program for asbestos, hearing conservation, respirator/solvent exposures, CO/cardiovascular risk, diesel-exhaust respiratory surveillance, and DBA baseline documentation.",
  tags: [
    "Entity profile",
    "Tecmotiv",
    "AVDS 1790",
    "Military engine overhaul",
    "M60 Patton",
    "M88 Hercules",
    "M109 Paladin",
    "M113",
    "Asbestos surveillance",
    "Diesel exhaust",
    "Carbon monoxide",
    "Noise HCP",
    "Machine shop",
    "DLA Land & Maritime",
    "TACOM",
    "Foreign Military Sales",
    "DBA FSR",
  ],
  aliases: ["Tecmotiv", "Tecmotiv (USA), Inc.", "Tecmotiv USA", "Tecmotiv Corporation"],
  sourceFilters: {
    sam: { legalNames: ["Tecmotiv (USA), Inc.", "Tecmotiv Corporation", "Tecmotiv USA"] },
    usaSpending: { recipientNames: ["Tecmotiv", "Tecmotiv USA", "Tecmotiv Corporation"] },
    newsSources: { aliases: ["Tecmotiv", "AVDS 1790", "DLA Land & Maritime", "TACOM engine overhaul", "M88 Hercules engine"] },
  },
  executiveSignals: [
    {
      label: "US workers",
      value: "~150",
      note: "Uploaded report models roughly 150 US workers at the Niagara Falls, New York facility and related support lanes.",
    },
    {
      label: "Expected injuries",
      value: "4.4/yr",
      note: "BLS benchmark model applied to Tecmotiv's work lanes.",
    },
    {
      label: "Asbestos surveillance",
      value: "~27 workers",
      note: "60% of 45 engine overhaul workers modeled as requiring asbestos surveillance due to legacy AVDS engine gasket exposure.",
    },
    {
      label: "Noise HCP",
      value: "~100 workers",
      note: "Machine shop and engine test cells exceed or approach OSHA noise action levels in the uploaded report.",
    },
  ],
  curveTitle: "Tecmotiv legacy combat-vehicle engine surveillance and high-specificity medical curve",
  curveSubtitle:
    "Uploaded Tecmotiv Occu-Med report normalized into an entity profile. Surveillance counts are modeled assumptions pending actual exposure monitoring and roster validation.",
  chartDefinitions: [
    {
      id: "tecmotiv-five-numbers",
      title: "Tecmotiv five numbers that matter",
      subtitle: "Uploaded report: expected injuries, economic burden, asbestos surveillance, noise HCP, and DBA exposure.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Expected injuries", value: 4.4 },
        { metric: "Economic burden $M", value: 1.05 },
        { metric: "Asbestos surveillance", value: 27 },
        { metric: "Noise HCP", value: 100 },
        { metric: "DBA exposure $K", value: 90 },
      ],
      series: [{ dataKey: "value", name: "Modeled value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "surveillance profile",
      fullWidth: true,
    },
    {
      id: "tecmotiv-injuries-by-operation",
      title: "Expected injuries by operation",
      subtitle: "Uploaded report: engine overhaul and machine shop dominate modeled injury volume despite small headcount.",
      type: "bar",
      xKey: "operation",
      data: [
        { operation: "Engine overhaul", workers: 45, injuries: 1.58, trir: 3.5 },
        { operation: "Machine shop", workers: 40, injuries: 1.30, trir: 3.25 },
        { operation: "Engine testing", workers: 20, injuries: 0.60, trir: 3.0 },
        { operation: "Parts/warehouse", workers: 25, injuries: 0.63, trir: 2.5 },
        { operation: "FSR/field tech", workers: 15, injuries: 0.30, trir: 2.0 },
        { operation: "Engineering/admin", workers: 5, injuries: 0.03, trir: 0.6 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/yr", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "injury model",
      fullWidth: true,
    },
    {
      id: "tecmotiv-surveillance-cascade",
      title: "Tecmotiv medical surveillance cascade",
      subtitle: "Legacy engines, test cells, and machine shop hazards trigger specialty surveillance lanes.",
      type: "bar",
      xKey: "surveillance",
      data: [
        { surveillance: "Asbestos baseline", workers: 27 },
        { surveillance: "Chest X-ray / PFT", workers: 27 },
        { surveillance: "Noise HCP", workers: 100 },
        { surveillance: "CO/cardiovascular", workers: 20 },
        { surveillance: "Diesel exhaust/PFT", workers: 20 },
        { surveillance: "DBA FSR baseline", workers: 15 },
      ],
      series: [{ dataKey: "workers", name: "Workers", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      headline: "surveillance",
    },
    {
      id: "tecmotiv-asbestos-mandate",
      title: "Legacy AVDS 1790 asbestos surveillance logic",
      subtitle: "Uploaded report: AVDS engines built 1959-1980 carry legacy gasket exposure assumptions until air monitoring proves otherwise.",
      type: "bar",
      xKey: "stage",
      data: [
        { stage: "AVDS engine age", percent: 100 },
        { stage: "Asbestos gasket risk", percent: 85 },
        { stage: "Action-level concern", percent: 60 },
        { stage: "Medical surveillance", percent: 60 },
        { stage: "CXR + PFT baseline", percent: 60 },
      ],
      series: [{ dataKey: "percent", name: "% overhaul workers affected", color: "#f97316", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      headline: "asbestos mandate",
      fullWidth: true,
    },
    {
      id: "tecmotiv-exposure-priority",
      title: "Exposure priority map",
      subtitle: "This is a small account with unusually high exposure specificity.",
      type: "bar",
      xKey: "exposure",
      data: [
        { exposure: "Asbestos gaskets", priority: 10 },
        { exposure: "Machine-shop noise", priority: 9 },
        { exposure: "CO in test cells", priority: 9 },
        { exposure: "Diesel exhaust", priority: 9 },
        { exposure: "Solvents/cutting fluids", priority: 8 },
        { exposure: "Heavy lift/forklift", priority: 7 },
        { exposure: "OCONUS FSR DBA", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "exposure map",
    },
  ],
  metricDefinitions: [
    { id: "tecmotiv-us-workers", label: "US workers", value: 150, unit: "count", category: "workforce" },
    { id: "tecmotiv-expected-injuries", label: "Expected injuries/yr", value: 4.4, unit: "count", category: "safety" },
    { id: "tecmotiv-economic-burden", label: "Total economic burden", value: 1.05, unit: "usd", category: "financial" },
    { id: "tecmotiv-asbestos-workers", label: "Asbestos surveillance workers", value: 27, unit: "count", category: "risk" },
    { id: "tecmotiv-noise-hcp", label: "Noise HCP workers", value: 100, unit: "count", category: "risk" },
    { id: "tecmotiv-dba-exposure", label: "Annual DBA exposure", value: 0.09, unit: "usd", category: "risk" },
    { id: "tecmotiv-fsr-workers", label: "OCONUS FSR workers", value: 15, unit: "count", category: "workforce" },
  ],
  riskMatrix: [
    { name: "Engine overhaul / asbestos", revenue: 27, risk: 10.0, workers: 45 },
    { name: "Machine shop noise", revenue: 100, risk: 9.0, workers: 40 },
    { name: "Engine test cells", revenue: 20, risk: 9.0, workers: 20 },
    { name: "Parts/warehouse", revenue: 25, risk: 7.0, workers: 25 },
    { name: "OCONUS FSR", revenue: 15, risk: 8.5, workers: 15 },
  ],
  opportunityMatrix: [
    { name: "Asbestos Medical Surveillance", revenuePotential: 80, implementationComplexity: 8, strategicValue: 10 },
    { name: "Hearing Conservation Program", revenuePotential: 60, implementationComplexity: 5, strategicValue: 9 },
    { name: "CO / Cardiovascular Test-Cell Baseline", revenuePotential: 45, implementationComplexity: 7, strategicValue: 9 },
    { name: "Diesel Exhaust Respiratory Surveillance", revenuePotential: 40, implementationComplexity: 7, strategicValue: 8 },
    { name: "DBA FSR Pre-Deployment", revenuePotential: 30, implementationComplexity: 6, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Tecmotiv is small, but it is not a simple small account. The work involves legacy military engine overhaul where the medical surveillance requirements are more specialized than headcount alone suggests.",
      bullets: [
        "US facility at 1500 James Avenue, Niagara Falls, New York, according to the uploaded report.",
        "Primary work includes AVDS 1790 diesel engine and powertrain overhaul for legacy combat vehicles.",
        "Active support lanes include DLA Land & Maritime, TACOM overhaul contracts, and FMS support across 20+ countries.",
        "Estimated US workforce is approximately 150 workers.",
      ],
      metricIds: ["tecmotiv-us-workers", "tecmotiv-expected-injuries", "tecmotiv-economic-burden"],
    },
    {
      type: "safety",
      title: "Legacy-engine asbestos and test-cell exposure",
      narrative:
        "The uploaded report's strongest occupational medicine point is that AVDS 1790 engines were built before modern asbestos controls and are rebuilt today in a facility that must treat gasket removal and component cleaning as medical-surveillance triggers unless monitoring proves otherwise.",
      bullets: [
        "Approximately 27 of 45 engine overhaul workers are modeled as needing asbestos surveillance.",
        "Baseline chest X-ray and PFT are part of the asbestos surveillance logic in the uploaded report.",
        "Engine test cells create carbon monoxide and diesel exhaust exposure lanes.",
        "Machine shop and test-cell noise supports hearing conservation enrollment for about 100 workers.",
      ],
      metricIds: ["tecmotiv-asbestos-workers", "tecmotiv-noise-hcp"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The sales case is a high-specificity surveillance program: asbestos, noise, CO/cardiovascular baseline, diesel exhaust respiratory surveillance, respirator/solvent clearance, and DBA pre-deployment for field service personnel.",
      bullets: [
        "This account exposes the gap between generic urgent-care physicals and actual occupational medicine surveillance.",
        "Asbestos and diesel/CO baselines become long-tail workers' compensation defense documents years later.",
        "FSRs supporting legacy combat vehicle systems across 20+ countries create a small but meaningful DBA baseline lane.",
      ],
      metricIds: ["tecmotiv-dba-exposure", "tecmotiv-fsr-workers"],
    },
  ],
};
