import type { CompanyConfig } from "./types";

export const thalesConfig: CompanyConfig = {
  companyId: "thales",
  displayName: "Thales Group / Thales Defense & Security Inc.",
  shortName: "Thales",
  sector:
    "French multinational defense and aerospace group, US tactical communications manufacturing, defense electronics, aerospace, cyber/digital identity, OCONUS field service support, SOF radio systems, DBA exposure, and TF1-to-OSHA metric translation",
  headquarters: "Paris, France / US subsidiary headquartered in Clarksburg, Maryland",
  employees: 81005,
  employeesAsOf:
    "Uploaded Thales Group Occu-Med report: 81,005 employees in 68 countries globally; approximately 3,000 US-employed workers across TDSI and related US operations",
  summary:
    "Thales Group is a €20.6B French multinational defense and aerospace group operating across Aerospace, Defence, and Cybersecurity & Digital Identity. The uploaded Occu-Med report focuses on the US occupational medicine gap created by Thales's global French safety-reporting framework. Thales publishes TF1, a French lost-time injury frequency metric, rather than US OSHA TRIR. The report translates Thales's 2024 TF1 of 1.47 to an OSHA TRIR-equivalent of roughly 0.88, which is strong, but the translation itself matters: US employees report restricted-duty and medical-treatment cases on OSHA logs that French TF1 does not count. Thales Defense & Security Inc. in Clarksburg, Maryland produces tactical radios, expeditionary satellite terminals, helmet-mounted displays, radars, and undersea sensing systems. The US workforce includes electronics manufacturing, undersea/EW technicians, software/systems engineers, OCONUS FSRs supporting SOF radio and naval/HMD systems, and program/corporate workers. The Occu-Med wedge is US regulatory translation: OSHA 300 logic, respirator/hearing surveillance, soldering/solvent exposure, DBA baselines for field service representatives, and US-specific medical surveillance that cannot be inferred from French parent-company TF1 reporting.",
  tags: [
    "Entity profile",
    "Thales",
    "Thales Defense & Security",
    "TDSI",
    "French TF1",
    "OSHA TRIR equivalent",
    "Metric translation",
    "Tactical radios",
    "AN/PRC-148",
    "AN/PRC-154",
    "SOF support",
    "OCONUS FSR",
    "DBA exposure",
    "Defense electronics",
    "Clarksburg Maryland",
  ],
  aliases: ["Thales", "Thales Group", "Thales Defense & Security", "Thales Defense & Security Inc.", "TDSI", "Tampa Microwave", "Advanced Acoustic Concepts", "Trusted Cyber Technologies"],
  sourceFilters: {
    sam: { legalNames: ["Thales Defense & Security Inc.", "Thales Group", "Thales USA"] },
    usaSpending: { recipientNames: ["Thales", "Thales Defense & Security", "Tampa Microwave", "Advanced Acoustic Concepts"] },
    jobSources: { linkedin: "thales", careerSite: "https://www.thalesgroup.com/en/careers" },
    newsSources: { aliases: ["Thales Group", "Thales Defense & Security", "TDSI", "AN/PRC-148", "AN/PRC-154", "Thales TF1"] },
  },
  executiveSignals: [
    {
      label: "Global workforce",
      value: "81K",
      note: "Uploaded report identifies 81,005 employees in 68 countries.",
    },
    {
      label: "US workforce",
      value: "~3K",
      note: "Uploaded report models roughly 3,000 US-employed workers across TDSI and US subsidiaries/operations.",
    },
    {
      label: "TF1 2024",
      value: "1.47",
      note: "French lost-time injury frequency metric; not equivalent to OSHA TRIR.",
    },
    {
      label: "OSHA TRIR equiv.",
      value: "~0.88",
      note: "Uploaded report translates current TF1 to approximate OSHA TRIR equivalent for US comparison.",
    },
  ],
  curveTitle: "Thales TF1-to-OSHA metric translation and US defense-electronics risk curve",
  curveSubtitle:
    "Uploaded Thales Occu-Med report normalized into an entity profile. Translation values are model-based and should be validated against US OSHA logs where available.",
  chartDefinitions: [
    {
      id: "thales-five-numbers",
      title: "Thales US five numbers that matter",
      subtitle: "Uploaded report: US operations expected injury, economic burden, DBA, and fatality expected-value model.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "Direct injury cost", value: 1.25 },
        { metric: "Economic burden", value: 6.86 },
        { metric: "DBA exposure", value: 1.35 },
        { metric: "Fatality EV", value: 0.0432 },
      ],
      series: [{ dataKey: "value", name: "Annual exposure", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "US exposure",
      fullWidth: true,
    },
    {
      id: "thales-tf1-trend",
      title: "Thales global TF1 trend vs OSHA equivalent",
      subtitle: "Uploaded report: TF1 improved from 2.17 in 2018 to 1.47 in 2024; current OSHA TRIR-equivalent is modeled around 0.88.",
      type: "line",
      xKey: "year",
      data: [
        { year: "2018", tf1: 2.17, oshaEquivalent: 1.30, target2030: 1.0 },
        { year: "2019", tf1: 2.0, oshaEquivalent: 1.20, target2030: 1.0 },
        { year: "2020", tf1: 1.85, oshaEquivalent: 1.11, target2030: 1.0 },
        { year: "2021", tf1: 1.61, oshaEquivalent: 0.97, target2030: 1.0 },
        { year: "2022", tf1: 1.55, oshaEquivalent: 0.93, target2030: 1.0 },
        { year: "2023", tf1: 1.50, oshaEquivalent: 0.90, target2030: 1.0 },
        { year: "2024", tf1: 1.47, oshaEquivalent: 0.88, target2030: 1.0 },
      ],
      series: [
        { dataKey: "tf1", name: "Thales TF1", color: "#22d3ee" },
        { dataKey: "oshaEquivalent", name: "OSHA TRIR equivalent", color: "#ef4444" },
        { dataKey: "target2030", name: "2030 TF1 target", color: "#22c55e" },
      ],
      domain: [0.5, 2.3],
      headline: "metric translation",
      fullWidth: true,
    },
    {
      id: "thales-metric-translation",
      title: "What TF1 = 1.47 actually means",
      subtitle: "French TF1 counts lost-time injuries only; OSHA TRIR includes medical treatment and restricted duty.",
      type: "bar",
      xKey: "metric",
      data: [
        { metric: "French TF1", value: 1.47 },
        { metric: "OSHA TRIR equivalent", value: 0.88 },
        { metric: "OSHA world-class", value: 1.0 },
        { metric: "Thales 2030 target", value: 1.0 },
      ],
      series: [{ dataKey: "value", name: "Rate value", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 1.6],
      headline: "translation gap",
    },
    {
      id: "thales-us-workforce-risk",
      title: "Thales US workforce risk by lane",
      subtitle: "Uploaded report: about 3,000 US workers across electronics manufacturing, undersea/EW, software, OCONUS FSR, and corporate lanes.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "Electronics mfg", workers: 900, injuries: 13.5 },
        { lane: "Undersea/EW techs", workers: 200, injuries: 3.0 },
        { lane: "Software/systems", workers: 800, injuries: 4.0 },
        { lane: "OCONUS FSRs", workers: 300, injuries: 4.5 },
        { lane: "PM/corporate", workers: 800, injuries: 4.0 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/yr", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "US workforce",
      fullWidth: true,
    },
    {
      id: "thales-occumed-wedges",
      title: "Thales Occu-Med service wedges",
      subtitle: "US-specific occupational medicine gaps created by defense electronics manufacturing and OCONUS FSR support.",
      type: "bar",
      xKey: "wedge",
      data: [
        { wedge: "OSHA metric translation", priority: 10 },
        { wedge: "Hearing conservation", priority: 8 },
        { wedge: "Respirator/solvent clearance", priority: 8 },
        { wedge: "DBA pre-deployment", priority: 9 },
        { wedge: "SOF FSR baselines", priority: 9 },
        { wedge: "US OSHA 300 support", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "service wedges",
    },
    {
      id: "thales-dba-exposure",
      title: "Thales OCONUS FSR DBA exposure",
      subtitle: "Uploaded report: 300 OCONUS FSRs create modeled $1.35M annual DBA claim exposure.",
      type: "bar",
      xKey: "scenario",
      data: [
        { scenario: "OCONUS FSRs", value: 300 },
        { scenario: "Expected OCONUS injuries", value: 4.5 },
        { scenario: "DBA exposure $M", value: 1.35 },
      ],
      series: [{ dataKey: "value", name: "Modeled value", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "DBA exposure",
    },
  ],
  metricDefinitions: [
    { id: "thales-global-employees", label: "Global employees", value: 81005, unit: "count", category: "workforce" },
    { id: "thales-countries", label: "Countries", value: 68, unit: "count", category: "workforce" },
    { id: "thales-us-workers", label: "US workers", value: 3000, unit: "count", category: "workforce" },
    { id: "thales-expected-injuries", label: "Expected US injuries/yr", value: 29, unit: "count", category: "safety" },
    { id: "thales-direct-cost", label: "Direct annual injury cost", value: 1.25, unit: "usd", category: "financial" },
    { id: "thales-economic-burden", label: "Total economic burden", value: 6.86, unit: "usd", category: "financial" },
    { id: "thales-dba-exposure", label: "Annual DBA exposure", value: 1.35, unit: "usd", category: "risk" },
    { id: "thales-tf1-2024", label: "2024 TF1", value: 1.47, unit: "score", category: "safety" },
    { id: "thales-osha-equivalent", label: "OSHA TRIR equivalent", value: 0.88, unit: "score", category: "safety" },
  ],
  riskMatrix: [
    { name: "Electronics manufacturing", revenue: 13.5, risk: 8.0, workers: 900 },
    { name: "OCONUS FSRs", revenue: 4.5, risk: 9.0, workers: 300 },
    { name: "Undersea/EW technicians", revenue: 3, risk: 7.5, workers: 200 },
    { name: "Software/systems engineers", revenue: 4, risk: 3.5, workers: 800 },
    { name: "Program/corporate", revenue: 4, risk: 2.5, workers: 800 },
  ],
  opportunityMatrix: [
    { name: "DBA FSR Baseline Program", revenuePotential: 250, implementationComplexity: 7, strategicValue: 10 },
    { name: "OSHA/TRIR Translation Audit", revenuePotential: 180, implementationComplexity: 8, strategicValue: 10 },
    { name: "Electronics Manufacturing Surveillance", revenuePotential: 160, implementationComplexity: 6, strategicValue: 8 },
    { name: "Hearing Conservation", revenuePotential: 140, implementationComplexity: 5, strategicValue: 8 },
    { name: "Respirator / Solvent Clearance", revenuePotential: 120, implementationComplexity: 6, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Thales should be treated as a multinational defense electronics entity with a US-specific reporting and compliance gap. The global safety metric is useful but not sufficient for US occupational medicine strategy.",
      bullets: [
        "Global group: €20.6B revenue, 81,005 employees, and 68 countries in the uploaded report.",
        "US subsidiary TDSI is headquartered in Clarksburg, Maryland and produces tactical radios, expeditionary terminals, helmet-mounted displays, radars, and undersea sensing systems.",
        "US workforce is modeled at about 3,000 workers across TDSI, Tampa Microwave, Advanced Acoustic Concepts, Trusted Cyber Technologies, and Thales Avionics operations.",
      ],
      metricIds: ["thales-global-employees", "thales-us-workers", "thales-expected-injuries"],
    },
    {
      type: "safety",
      title: "The TF1-to-OSHA translation problem",
      narrative:
        "The uploaded report's strongest insight is that Thales's French TF1 metric is not the same as US TRIR. TF1 counts lost-time injuries only, while OSHA recordability includes medical treatment and restricted-duty cases.",
      bullets: [
        "Thales reported TF1 of 1.47 in 2024, down from 2.17 in 2018.",
        "The uploaded model translates current TF1 to roughly 0.88 OSHA TRIR equivalent.",
        "A US restricted-duty shoulder injury may appear on OSHA logs but not in global TF1.",
        "This creates an Occu-Med wedge around US OSHA 300 logging, medical treatment/restricted duty capture, and US regulatory interpretation.",
      ],
      metricIds: ["thales-tf1-2024", "thales-osha-equivalent"],
    },
    {
      type: "medical-opportunities",
      title: "US-specific Occu-Med opportunity",
      narrative:
        "Thales USA needs occupational medicine support that understands US defense electronics manufacturing and DBA-covered OCONUS field support, not only global French HSE targets.",
      bullets: [
        "Electronics manufacturing workers need hearing conservation, respirator/solvent clearance, and soldering/chemical exposure baselines.",
        "OCONUS FSRs supporting SOF radio and naval/HMD systems need pre-deployment DBA baselines.",
        "US OSHA records should be interpreted separately from the global TF1 metric.",
      ],
      metricIds: ["thales-dba-exposure", "thales-economic-burden"],
    },
  ],
};
