import type { CompanyConfig } from "./types";

export const traceSystemsConfig: CompanyConfig = {
  companyId: "trace-systems",
  displayName: "Trace Systems Inc.",
  shortName: "Trace Systems",
  sector:
    "Tactical communications, SATCOM field service representatives, VSAT terminal modernization, RF/EMF surveillance, CRC processing, OCONUS deployment, DBA-covered communications support, and defense network services",
  headquarters: "Tampa, Florida",
  employees: 500,
  employeesAsOf: "Uploaded Trace Systems Occu-Med report: current estimated 300-500 employees; projected growth toward 1,150 workers as 2025 awards scale",
  summary:
    "Trace Systems Inc. is a privately held tactical communications and satellite infrastructure company headquartered in Tampa, Florida. The uploaded report frames Trace as a small company that suddenly acquired large exposure: in a twelve-month window between April and May 2025, Trace was awarded more than $937M in new federal contracts, including a $564M Global FSR Support / GTACS II award and a $352M VSAT IV award. This shifts Trace from a boutique SATCOM provider into a major Army program-of-record contractor with field service representatives deployed to more than 30 countries across CENTCOM, EUCOM, AFRICOM, and INDOPACOM. The occupational medicine risk is not help-desk IT. It is OCONUS field technicians installing, aligning, troubleshooting, and maintaining high-power satellite earth stations and VSAT terminals in military environments, with up to 75% travel, 24/7 emergent support, CRC processing, RF/EMF exposure, falls, heat stress, blast/noise exposure, ergonomic load, and DBA-covered hostile-environment work.",
  tags: [
    "Entity profile",
    "Trace Systems",
    "SATCOM",
    "FSR",
    "GTACS II",
    "VSAT IV",
    "SNAP terminals",
    "OCONUS",
    "CENTCOM",
    "EUCOM",
    "AFRICOM",
    "INDOPACOM",
    "RF/EMF surveillance",
    "CRC processing",
    "DBA medicals",
    "Contract surge",
  ],
  aliases: ["Trace Systems", "Trace Systems Inc", "Trace Systems Inc.", "Trace"],
  sourceFilters: {
    sam: { legalNames: ["Trace Systems Inc", "Trace Systems Inc."] },
    usaSpending: { recipientNames: ["Trace Systems"] },
    jobSources: { linkedin: "trace-systems", careerSite: "https://www.tracesystems.com/careers/" },
    newsSources: { aliases: ["Trace Systems", "GTACS II", "VSAT IV", "SNAP terminal", "Global FSR Support"] },
  },
  executiveSignals: [
    { label: "Award surge", value: "$937M+", note: "Uploaded report says April-May 2025 awards transformed Trace from boutique SATCOM provider to major Army program contractor." },
    { label: "Global FSR", value: "$564M", note: "Mission-critical contract for 200+ SATCOM FSR personnel across 30+ countries." },
    { label: "Current workforce", value: "300-500", note: "Private company with limited public safety documentation and no published TRIR/safety report." },
    { label: "Projected workforce", value: "1,150", note: "Projected 2026-2027 workforce as VSAT IV, Global FSR, and AFCENT lanes scale." },
  ],
  curveTitle: "Trace Systems contract surge, FSR deployment, and RF/DBA readiness curve",
  curveSubtitle:
    "Uploaded Trace Systems Occu-Med report normalized into entity-profile charts. Modeled workforce and revenue projections should be validated against actual task-order staffing before operational use.",
  chartDefinitions: [
    {
      id: "trace-contract-surge",
      title: "Trace Systems contract award surge",
      subtitle: "The uploaded report identifies more than $937M in new federal contracts in the 2025 award window.",
      type: "bar",
      xKey: "award",
      data: [
        { award: "Pre-2024 avg", value: 40 },
        { award: "FY2024 partial", value: 60 },
        { award: "Satellite Modernization", value: 21 },
        { award: "VSAT IV", value: 352 },
        { award: "Global FSR", value: 564 },
        { award: "2025 Total", value: 937 },
      ],
      series: [{ dataKey: "value", name: "Contract value", color: "#dc2626", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "contract surge",
      fullWidth: true,
    },
    {
      id: "trace-contract-portfolio",
      title: "Trace contract portfolio detail",
      subtitle: "Four contract lanes from the uploaded report, including the contested AFCENT communications-support opportunity.",
      type: "bar",
      xKey: "contract",
      data: [
        { contract: "Global FSR / GTACS II", value: 564, priority: 10 },
        { contract: "VSAT IV / PM TN", value: 352, priority: 9 },
        { contract: "AFCENT Comms", value: 121.4, priority: 8 },
        { contract: "Terminal Modernization", value: 21, priority: 5 },
      ],
      series: [{ dataKey: "priority", name: "Medical priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "portfolio priority",
    },
    {
      id: "trace-workforce-growth",
      title: "Trace workforce growth projection",
      subtitle: "Projected total workforce and OCONUS DBA-covered headcount as the contract surge scales.",
      type: "grouped",
      xKey: "scenario",
      data: [
        { scenario: "Current", total: 350, oconus: 180 },
        { scenario: "VSAT IV", total: 550, oconus: 310 },
        { scenario: "Global FSR", total: 900, oconus: 600 },
        { scenario: "AFCENT", total: 1150, oconus: 750 },
      ],
      series: [
        { dataKey: "total", name: "Total workforce", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "oconus", name: "OCONUS DBA-covered", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "workforce growth",
      fullWidth: true,
    },
    {
      id: "trace-ccmd-risk",
      title: "Trace FSR OCONUS risk by combatant command",
      subtitle: "FSR deployment spans CENTCOM, EUCOM, AFRICOM, and INDOPACOM, with highest hostile-environment risk in CENTCOM.",
      type: "bar",
      xKey: "command",
      data: [
        { command: "CENTCOM", risk: 9 },
        { command: "EUCOM", risk: 7 },
        { command: "AFRICOM", risk: 6 },
        { command: "INDOPACOM", risk: 5 },
        { command: "NORTHCOM", risk: 2 },
      ],
      series: [{ dataKey: "risk", name: "Hostile environment risk", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "theater risk",
    },
    {
      id: "trace-fsr-work-reality",
      title: "Trace FSR work reality scorecard",
      subtitle: "The uploaded report stresses that FSRs are field technicians in military environments, not desk IT workers.",
      type: "bar",
      xKey: "workFactor",
      data: [
        { workFactor: "75% travel", priority: 10 },
        { workFactor: "24/7 emergent support", priority: 9 },
        { workFactor: "Physical VSAT install", priority: 9 },
        { workFactor: "CRC / Fort Bliss", priority: 9 },
        { workFactor: "Secret clearance", priority: 7 },
        { workFactor: "30+ countries", priority: 10 },
      ],
      series: [{ dataKey: "priority", name: "Readiness priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "FSR reality",
    },
    {
      id: "trace-hazards",
      title: "Trace FSR occupational hazards",
      subtitle: "RF/EMF, DBA hostile-environment exposure, heat stress, falls, blast/noise, and ergonomic load define the medical protocol lanes.",
      type: "grouped",
      xKey: "hazard",
      data: [
        { hazard: "RF/EMF", severity: 4, frequency: 5 },
        { hazard: "Falls", severity: 3, frequency: 3 },
        { hazard: "Heat Stress", severity: 4, frequency: 4 },
        { hazard: "Blast/Noise", severity: 3, frequency: 2 },
        { hazard: "DBA Hostile", severity: 4, frequency: 5 },
        { hazard: "Ergonomic", severity: 3, frequency: 5 },
      ],
      series: [
        { dataKey: "severity", name: "Severity", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "frequency", name: "Frequency", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      headline: "hazards",
    },
    {
      id: "trace-revenue",
      title: "Trace Systems Occu-Med revenue now vs 2027",
      subtitle: "Projected revenue opportunity as FSR staffing and OCONUS headcount scale.",
      type: "grouped",
      xKey: "exam",
      data: [
        { exam: "DBA Pre-Deploy", current: 76, projected: 262 },
        { exam: "Pre-Employment", current: 20, projected: 89 },
        { exam: "RF/EMF", current: 65, projected: 170 },
        { exam: "CRC Medicals", current: 0, projected: 118 },
        { exam: "Hearing", current: 16, projected: 32 },
      ],
      series: [
        { dataKey: "current", name: "Current", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "projected", name: "Projected 2027", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "trace-current-workers", label: "Current workforce estimate", value: 500, unit: "count", category: "workforce" },
    { id: "trace-projected-workers", label: "Projected workforce", value: 1150, unit: "count", category: "workforce" },
    { id: "trace-current-revenue", label: "Estimated annual revenue before surge", value: 85.8, unit: "usd", category: "financial" },
    { id: "trace-award-surge", label: "2025 award surge", value: 937, unit: "usd", category: "financial" },
    { id: "trace-global-fsr", label: "Global FSR award", value: 564, unit: "usd", category: "financial" },
    { id: "trace-vsat", label: "VSAT IV award", value: 352, unit: "usd", category: "financial" },
    { id: "trace-countries", label: "Deployment countries", value: 30, unit: "count", category: "workforce" },
    { id: "trace-oconus-projected", label: "Projected OCONUS DBA-covered workers", value: 750, unit: "count", category: "workforce" },
    { id: "trace-revenue-projected", label: "Projected Occu-Med revenue", value: 0.671, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "OCONUS SATCOM FSRs", revenue: 262, risk: 10.0, workers: 750 },
    { name: "RF/EMF transmitter work", revenue: 170, risk: 9.5, workers: 600 },
    { name: "CRC / CENTCOM deployers", revenue: 118, risk: 9.0, workers: 400 },
    { name: "Heat / austere field work", revenue: 90, risk: 8.0, workers: 500 },
    { name: "VSAT modernization techs", revenue: 89, risk: 7.5, workers: 300 },
  ],
  opportunityMatrix: [
    { name: "DBA Pre-Deployment Medicals", revenuePotential: 262, implementationComplexity: 6, strategicValue: 10 },
    { name: "RF/EMF Surveillance", revenuePotential: 170, implementationComplexity: 8, strategicValue: 10 },
    { name: "CRC Medical Processing", revenuePotential: 118, implementationComplexity: 6, strategicValue: 9 },
    { name: "Pre-Employment Physicals", revenuePotential: 89, implementationComplexity: 4, strategicValue: 7 },
    { name: "Hearing Conservation", revenuePotential: 32, implementationComplexity: 4, strategicValue: 6 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Small company with suddenly large exposure",
      narrative:
        "The uploaded Trace report's core point is that the absence of public TRIR or safety reporting is normal for a small private contractor, but it becomes a problem once the company scales into a global FSR program with hundreds of DBA-covered workers in forward military environments.",
      bullets: [
        "Privately held tactical communications and satellite infrastructure company headquartered in Tampa, Florida.",
        "Current estimated workforce is 300-500 employees with about $85.8M estimated annual revenue before the award surge.",
        "A 2025 award window added more than $937M in new federal contract value.",
        "The Global FSR / GTACS II contract places SATCOM technicians across more than 30 countries.",
      ],
      metricIds: ["trace-current-workers", "trace-current-revenue", "trace-award-surge"],
    },
    {
      type: "contracts",
      title: "The Global FSR contract changes the medical risk profile",
      narrative:
        "The uploaded report identifies Global FSR Support under GTACS II as the mission-critical contract because it creates the worldwide field technician population that physically supports Army tactical communications infrastructure.",
      bullets: [
        "Global FSR Support / GTACS II: $564M, 200+ personnel, SATCOM FSR support to 30+ countries.",
        "VSAT IV: $352M for SNAP terminal maintenance and modernization.",
        "Satellite terminal modernization: $21M recent modernization support.",
        "AFCENT communications support: $121.4M contested / GAO re-evaluation lane in the CENTCOM AOR.",
      ],
      metricIds: ["trace-global-fsr", "trace-vsat"],
    },
    {
      type: "workforce",
      title: "FSRs are field technicians, not IT help desk workers",
      narrative:
        "Trace FSRs install, align, troubleshoot, and maintain high-power satellite earth stations and VSAT terminals. The medical profile follows field technician and deployment logic, not office IT logic.",
      bullets: [
        "Up to 75% travel, CONUS and OCONUS.",
        "24/7 operations for emergent support.",
        "Physical installation and maintenance of satellite earth stations and VSAT terminals.",
        "CRC requirement for CENTCOM AOR deployments through Fort Bliss.",
        "Secret clearance minimum, with many positions requiring higher clearances.",
      ],
      metricIds: ["trace-countries", "trace-oconus-projected"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The strongest wedge is a deployable FSR medical-readiness program that combines DBA pre-deployment medicals, CRC preparation, RF/EMF surveillance, heat/field readiness, hearing conservation, and ergonomic/physical-capacity baselines.",
      bullets: [
        "DBA pre-deployment documentation should exist before the first claim arrives, not after.",
        "RF/EMF surveillance should be specific to high-power transmitter and antenna work.",
        "CRC medical preparation is operationally valuable because FSRs deploying to CENTCOM must clear military processing.",
      ],
      metricIds: ["trace-revenue-projected"],
    },
  ],
};
