import type { CompanyConfig } from "./types";

export const traceSystemsConfig: CompanyConfig = {
  companyId: "trace-systems",
  displayName: "Trace Systems",
  shortName: "Trace",
  sector: "FSR communications support, OCONUS deployment, RF/EMF surveillance, CRC processing, and defense network services",
  headquarters: "Vienna, Virginia",
  employees: 1150,
  employeesAsOf: "Projected 2026-2027 workforce from uploaded Trace visual model",
  summary: "Trace Systems has been added as an FSR OCONUS growth and occupational-hazard dossier connecting combatant-command hostile-environment exposure, a 2024-2025 contract award surge, workforce growth through 2027, RF/EMF and DBA hostile-environment hazards, and a sharply expanding Occu-Med revenue opportunity.",
  tags: ["FSR", "OCONUS", "CENTCOM", "RF/EMF surveillance", "CRC processing", "Contract surge", "DBA medicals"],
  aliases: ["Trace Systems Inc"],
  executiveSignals: [
    { label: "Award surge", value: "$937M", note: "2025 total awards modeled across VSAT IV and Global FSR." },
    { label: "Projected workforce", value: "1,150", note: "Projected total workforce by 2026-2027." },
    { label: "OCONUS DBA", value: "750", note: "Projected DBA-covered OCONUS headcount." },
    { label: "Revenue upside", value: "$671K/yr", note: "Projected 2027 Occu-Med revenue potential." },
  ],
  curveTitle: "Trace growth and readiness curve",
  curveSubtitle: "Award surge, workforce growth, OCONUS DBA exposure, and revenue upside normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "trace-ccmd-risk",
      title: "Trace FSR OCONUS risk by combatant command",
      subtitle: "Source: uploaded Trace visual; hostile environment risk 1-10.",
      type: "bar",
      xKey: "name",
      data: [{ name: "CENTCOM", risk: 9 }, { name: "EUCOM", risk: 7 }, { name: "AFRICOM", risk: 6 }, { name: "INDOPACOM", risk: 5 }, { name: "NORTHCOM", risk: 2 }],
      series: [{ dataKey: "risk", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "OCONUS risk",
    },
    {
      id: "trace-contract-surge",
      title: "Trace Systems contract award surge",
      subtitle: "Source: uploaded Trace visual; contract value shown in $M.",
      type: "bar",
      xKey: "name",
      data: [{ name: "Pre-2024", value: 40 }, { name: "FY2024", value: 60 }, { name: "VSAT IV", value: 352 }, { name: "Global FSR", value: 564 }, { name: "2025 Total", value: 937 }],
      series: [{ dataKey: "value", color: "#dc2626", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "contract surge",
    },
    {
      id: "trace-workforce-growth",
      title: "Trace workforce growth projection",
      subtitle: "Source: uploaded Trace visual; total workforce and OCONUS DBA-covered headcount.",
      type: "stacked",
      xKey: "name",
      data: [{ name: "Current", total: 350, oconus: 180 }, { name: "VSAT IV", total: 550, oconus: 310 }, { name: "Global FSR", total: 900, oconus: 600 }, { name: "AFCENT", total: 1150, oconus: 750 }],
      series: [
        { dataKey: "oconus", name: "OCONUS DBA-covered", color: "#22d3ee", stackId: "stack" },
        { dataKey: "total", name: "Total workforce", color: "#ef4444", stackId: "stack", radius: [10, 10, 0, 0] },
      ],
      headline: "workforce growth",
    },
    {
      id: "trace-hazards",
      title: "Trace FSR occupational hazards",
      subtitle: "Source: uploaded Trace visual; severity vs frequency scored 1-5.",
      type: "grouped",
      xKey: "name",
      data: [{ name: "RF/EMF", severity: 4, frequency: 5 }, { name: "Falls", severity: 3, frequency: 3 }, { name: "Heat Stress", severity: 4, frequency: 4 }, { name: "Blast/Noise", severity: 3, frequency: 2 }, { name: "DBA Hostile", severity: 4, frequency: 5 }, { name: "Ergonomic", severity: 3, frequency: 5 }],
      series: [
        { dataKey: "severity", name: "Severity", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "frequency", name: "Frequency", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      headline: "hazard profile",
    },
    {
      id: "trace-revenue",
      title: "Trace Systems Occu-Med revenue now vs 2027",
      subtitle: "Source: uploaded Trace visual; current vs projected annual revenue shown in $K.",
      type: "grouped",
      xKey: "name",
      data: [{ name: "DBA Pre-Deploy", current: 76, projected: 262 }, { name: "Pre-Employment", current: 20, projected: 89 }, { name: "RF/EMF", current: 65, projected: 170 }, { name: "CRC Medicals", current: 0, projected: 118 }, { name: "Hearing", current: 16, projected: 32 }],
      series: [
        { dataKey: "current", name: "Current 2025", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "projected", name: "Projected 2027", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "revenue potential",
      fullWidth: true,
    },
  ],
};
