import type { CompanyConfig } from "./types";

export const uploadedChartPackFourthIntelligenceConfig: CompanyConfig = {
  companyId: "uploaded-chart-pack-fourth-intelligence",
  displayName: "Uploaded Chart Pack Fourth Batch Intelligence",
  shortName: "Chart Batch 4",
  sector:
    "Portfolio economic burden, DBA exposure, headcount, revenue midpoint, TRIR distribution, priority tiers, provider network share, defense referral volume, and OCONUS referral-country coverage intelligence",
  headquarters: "Occu-Med chart-intake layer",
  employees: 630945,
  employeesAsOf:
    "Uploaded fourth chart batch: portfolio charts showing 630,945 workers across 21 accounts, $2.59B annual burden, $255M annual DBA exposure, and $56.2M-$84.8M modeled annual Occu-Med revenue",
  summary:
    "Uploaded Chart Pack Fourth Batch Intelligence captures the fourth PNG dashboard upload into the same PR #26 intake branch. This batch is mostly portfolio-level account sizing and prioritization. The charts show an estimated $2.59B/year economic burden across the portfolio, with RTX, Northrop, KBR, Amentum, L3Harris, Leidos, PAE, GDIT, Serco, and Maximus carrying the top burden positions. DBA exposure is estimated at $255M/year, with Amentum, KBR, PAE, Vectrus, DynCorp, Leidos, and GDIT making up the largest OCONUS/DBA exposure pool. The headcount chart frames 630,945 workers across 21 accounts, led by RTX at 185,000, Northrop at 95,000, Amentum at 53,000, L3Harris at 50,000, and Leidos at 48,000. The revenue chart estimates $56.2M-$84.8M annual Occu-Med opportunity, with a $70.5M/year midpoint and RTX, Northrop, Amentum, KBR, L3Harris, Leidos, PAE, GDIT, SAIC, and Serco as the main portfolio revenue lanes. The provider-network charts show 97.9% third-party provider dependence, only 2.1% own-facility share, Concentra at 16.4%, Swedish Specialist at 12%, British Medical Kuwait at 10.8%, and Agile OccMed CA at 10.5%. OCONUS referrals remain led by Kuwait, Iraq, UAE, Qatar, and the Marshall Islands. This should later be split into Master Portfolio, DBA Exposure, Provider Network Share, and OCONUS Referral Coverage sections.",
  tags: [
    "Entity profile",
    "Chart pack fourth batch",
    "Portfolio burden",
    "DBA exposure",
    "Headcount",
    "Revenue potential",
    "TRIR distribution",
    "Provider network",
    "Priority tiers",
    "OCONUS referrals",
    "Defense referrals",
    "Market share",
  ],
  aliases: ["Chart Batch 4", "Portfolio Account Charts", "Provider Share Charts", "OCONUS Referral Charts"],
  sourceFilters: {
    newsSources: {
      aliases: ["Occu-Med portfolio burden", "Occu-Med DBA exposure", "Occu-Med provider network share", "Occu-Med OCONUS referrals"],
    },
  },
  executiveSignals: [
    { label: "Portfolio burden", value: "$2.59B/yr", note: "Uploaded chart shows total annual economic burden across the portfolio." },
    { label: "DBA exposure", value: "$255M/yr", note: "Uploaded chart shows total annual DBA exposure, with Amentum, KBR, and PAE driving 46% of OCONUS risk." },
    { label: "Revenue midpoint", value: "$70.5M/yr", note: "Uploaded chart models total annual Occu-Med revenue at $56.2M-$84.8M with a $70.5M midpoint." },
    { label: "Network dependency", value: "97.9% third-party", note: "Uploaded provider share charts show Occu-Med own facilities at 2.1% and third-party providers at 97.9%." },
  ],
  curveTitle: "Fourth chart batch: portfolio sizing, DBA exposure, provider share, and OCONUS referral curve",
  curveSubtitle:
    "Fourth uploaded chart batch captured as source-specific intake. Values are screenshot-derived and should be replaced with spreadsheet source data when available.",
  chartDefinitions: [
    {
      id: "fourth-portfolio-economic-burden",
      title: "Top accounts by annual economic burden",
      subtitle: "Uploaded chart: total portfolio burden $2.59B/year; top three accounts equal 53% of total burden.",
      type: "bar",
      xKey: "account",
      data: [
        { account: "RTX", burden: 262.5 },
        { account: "Northrop", burden: 188.7 },
        { account: "KBR", burden: 114.9 },
        { account: "Amentum", burden: 112.8 },
        { account: "L3Harris", burden: 88.7 },
        { account: "Leidos", burden: 68.1 },
        { account: "PAE", burden: 51.6 },
        { account: "GDIT", burden: 50.8 },
        { account: "Serco", burden: 47.4 },
        { account: "Maximus", burden: 46.1 },
      ],
      series: [{ dataKey: "burden", name: "Annual economic burden", color: "#ef4444", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "burden",
      fullWidth: true,
    },
    {
      id: "fourth-portfolio-dba-exposure",
      title: "Annual DBA claim exposure by account",
      subtitle: "Uploaded chart: total DBA exposure $255M/year; Amentum, KBR, and PAE drive 46% of OCONUS risk.",
      type: "bar",
      xKey: "account",
      data: [
        { account: "Amentum", dbaExposure: 54.0 },
        { account: "KBR", dbaExposure: 45.6 },
        { account: "PAE", dbaExposure: 37.5 },
        { account: "Vectrus", dbaExposure: 25.5 },
        { account: "DynCorp", dbaExposure: 24.0 },
        { account: "Leidos", dbaExposure: 18.0 },
        { account: "GDIT", dbaExposure: 12.6 },
        { account: "IAP Worldwide", dbaExposure: 9.8 },
        { account: "SAIC", dbaExposure: 9.6 },
        { account: "Peraton", dbaExposure: 8.7 },
        { account: "ECC", dbaExposure: 6.7 },
        { account: "RTX", dbaExposure: 6.0 },
        { account: "L3Harris", dbaExposure: 4.5 },
        { account: "Valiant", dbaExposure: 3.2 },
        { account: "Northrop", dbaExposure: 2.4 },
        { account: "Maximus", dbaExposure: 1.0 },
        { account: "Serco", dbaExposure: 0.4 },
        { account: "Tecmotiv", dbaExposure: 0.1 },
      ],
      series: [{ dataKey: "dbaExposure", name: "Annual DBA exposure", color: "#f97316", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "DBA exposure",
      fullWidth: true,
    },
    {
      id: "fourth-portfolio-headcount",
      title: "Top accounts by headcount",
      subtitle: "Uploaded chart: total portfolio 630,945 workers across 21 accounts.",
      type: "bar",
      xKey: "account",
      data: [
        { account: "RTX", workers: 185000 },
        { account: "Northrop", workers: 95000 },
        { account: "Amentum", workers: 53000 },
        { account: "L3Harris", workers: 50000 },
        { account: "Leidos", workers: 48000 },
        { account: "KBR", workers: 38000 },
        { account: "GDIT", workers: 30000 },
        { account: "SAIC", workers: 27000 },
        { account: "Maximus", workers: 22000 },
        { account: "Serco", workers: 20000 },
      ],
      series: [{ dataKey: "workers", name: "Workers", color: "#2563eb", radius: [10, 10, 0, 0] }],
      headline: "headcount",
      fullWidth: true,
    },
    {
      id: "fourth-portfolio-revenue-midpoint",
      title: "Occu-Med revenue potential by account midpoint",
      subtitle: "Uploaded chart: total annual revenue $56.2M-$84.8M; portfolio midpoint $70.5M/year.",
      type: "bar",
      xKey: "account",
      data: [
        { account: "RTX", revenue: 17344 },
        { account: "Northrop", revenue: 8900 },
        { account: "Amentum", revenue: 4985 },
        { account: "KBR", revenue: 4750 },
        { account: "L3Harris", revenue: 4688 },
        { account: "Leidos", revenue: 4500 },
        { account: "PAE", revenue: 3400 },
        { account: "GDIT", revenue: 2650 },
        { account: "SAIC", revenue: 2550 },
        { account: "Serco", revenue: 1900 },
        { account: "Maximus", revenue: 1870 },
        { account: "ECC", revenue: 1785 },
        { account: "Peraton", revenue: 1700 },
        { account: "Vectrus", revenue: 1312 },
        { account: "DynCorp", revenue: 1032 },
        { account: "Valiant", revenue: 841 },
        { account: "Peckham", revenue: 645 },
        { account: "IAP Worldwide", revenue: 262 },
        { account: "Kongsberg", revenue: 224 },
        { account: "Source Group", revenue: 114 },
        { account: "Tecmotiv", revenue: 96 },
      ],
      series: [{ dataKey: "revenue", name: "Annual revenue", color: "#22c55e", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "revenue midpoint",
      fullWidth: true,
    },
    {
      id: "fourth-portfolio-trir-distribution",
      title: "Portfolio TRIR distribution",
      subtitle: "Uploaded chart: portfolio-weighted TRIR 1.83; manufacturing accounts in green versus OCONUS services in red.",
      type: "bar",
      xKey: "account",
      data: [
        { account: "RTX", trir: 0.30 },
        { account: "L3Harris", trir: 0.75 },
        { account: "Northrop", trir: 0.84 },
        { account: "Leidos", trir: 1.20 },
        { account: "SAIC", trir: 1.22 },
        { account: "Peraton", trir: 1.31 },
        { account: "GDIT", trir: 1.43 },
        { account: "Maximus", trir: 1.77 },
        { account: "Amentum", trir: 1.80 },
        { account: "Serco", trir: 2.00 },
        { account: "PAE", trir: 2.42 },
        { account: "KBR", trir: 2.56 },
        { account: "Kongsberg", trir: 2.94 },
        { account: "Peckham", trir: 3.05 },
        { account: "Source Group", trir: 3.50 },
        { account: "Valiant", trir: 4.10 },
        { account: "Vectrus", trir: 4.80 },
        { account: "DynCorp", trir: 5.09 },
        { account: "IAP Worldwide", trir: 5.43 },
        { account: "ECC", trir: 5.66 },
        { account: "Tecmotiv", trir: 5.87 },
      ],
      series: [{ dataKey: "trir", name: "TRIR per 200K hrs", color: "#ef4444", radius: [10, 10, 0, 0] }],
      referenceLines: [{ y: 1.0, label: "TRIR 1.0", color: "#94a3b8" }],
      headline: "TRIR distribution",
      fullWidth: true,
    },
    {
      id: "fourth-priority-tier-exam-volume",
      title: "Exam volume distribution by priority tier",
      subtitle: "Uploaded chart: Tier 1 critical locations carry most annual exam volume.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "Tier 1 Critical", annualExamVolume: 2229 },
        { tier: "Tier 2 High", annualExamVolume: 454 },
        { tier: "Tier 3 Medium", annualExamVolume: 194 },
      ],
      series: [{ dataKey: "annualExamVolume", name: "Annual exam volume", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "priority volume",
    },
    {
      id: "fourth-priority-tier-location-count",
      title: "Location count by priority tier",
      subtitle: "Uploaded chart: Tier 3 has more locations, but Tier 1 carries the demand concentration.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "Tier 1 Critical", locations: 10 },
        { tier: "Tier 2 High", locations: 3 },
        { tier: "Tier 3 Medium", locations: 13 },
      ],
      series: [{ dataKey: "locations", name: "Number of locations", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "priority locations",
    },
    {
      id: "fourth-provider-network-visit-share",
      title: "Provider network visit share",
      subtitle: "Uploaded chart: Occu-Med own facilities = 2.1%; 97.9% third-party provider reliance.",
      type: "bar",
      xKey: "provider",
      data: [
        { provider: "All Others", visits: 5979, share: 36.5 },
        { provider: "Concentra", visits: 2691, share: 16.4 },
        { provider: "Swedish Specialist (Erbil)", visits: 1975, share: 12.0 },
        { provider: "British Medical (Kuwait)", visits: 1785, share: 10.8 },
        { provider: "Agile OccMed (CA)", visits: 1723, share: 10.5 },
        { provider: "Asian Medical (Qatar)", visits: 652, share: 4.0 },
        { provider: "Apollo Medical", visits: 402, share: 2.5 },
        { provider: "Occu-Med Own", visits: 355, share: 2.1 },
        { provider: "Kwajalein Hospital", visits: 332, share: 2.0 },
        { provider: "AFC", visits: 277, share: 1.7 },
        { provider: "Akeso", visits: 240, share: 1.5 },
      ],
      series: [{ dataKey: "visits", name: "Clinic visits", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "provider share",
      fullWidth: true,
    },
    {
      id: "fourth-defense-referrals-by-client",
      title: "Total referrals by defense contractor client",
      subtitle: "Uploaded chart: V2X LOGCAP dominates at 5,427, about 52% of all defense referrals; Amentum #2 at 852.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "V2X", referrals: 5427 },
        { client: "Amentum", referrals: 852 },
        { client: "Constellis", referrals: 610 },
        { client: "GDIT", referrals: 437 },
        { client: "Valiant Integrated Services", referrals: 423 },
        { client: "IAP", referrals: 409 },
        { client: "Leidos", referrals: 307 },
        { client: "Deployment Center", referrals: 283 },
        { client: "Vertex", referrals: 234 },
        { client: "ManTech International", referrals: 188 },
        { client: "IDS International", referrals: 155 },
        { client: "International SOS", referrals: 150 },
        { client: "CACI International", referrals: 146 },
        { client: "Sierra Nevada Corporation", referrals: 146 },
        { client: "Trace Systems", referrals: 127 },
      ],
      series: [{ dataKey: "referrals", name: "Total referrals", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "defense refs",
      fullWidth: true,
    },
    {
      id: "fourth-oconus-referral-countries",
      title: "OCONUS referral countries where provider network is critical",
      subtitle: "Uploaded chart: Kuwait #1 at 1,778; UAE/Dubai #3 at 964; Iraq workers route through Dubai pre/post deployment.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Kuwait", referrals: 1778 },
        { country: "Iraq", referrals: 1157 },
        { country: "United Arab Emirates", referrals: 964 },
        { country: "Qatar", referrals: 718 },
        { country: "Marshall Islands", referrals: 416 },
        { country: "Jordan", referrals: 255 },
        { country: "Djibouti", referrals: 174 },
        { country: "Kenya", referrals: 146 },
        { country: "India", referrals: 121 },
        { country: "Bahrain", referrals: 78 },
        { country: "Saudi Arabia", referrals: 58 },
        { country: "Germany", referrals: 52 },
        { country: "Philippines", referrals: 51 },
        { country: "Thailand", referrals: 34 },
      ],
      series: [{ dataKey: "referrals", name: "Referrals", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "OCONUS refs",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "fourth-total-burden", label: "Total portfolio burden", value: 2590, unit: "usd", category: "financial" },
    { id: "fourth-total-dba", label: "Total DBA exposure", value: 255, unit: "usd", category: "risk" },
    { id: "fourth-total-workers", label: "Portfolio workers", value: 630945, unit: "count", category: "workforce" },
    { id: "fourth-revenue-midpoint", label: "Occu-Med revenue midpoint", value: 70.5, unit: "usd", category: "financial" },
    { id: "fourth-own-facility-share", label: "Own-facility share", value: 2.1, unit: "percent", category: "risk" },
    { id: "fourth-third-party-share", label: "Third-party provider share", value: 97.9, unit: "percent", category: "risk" },
    { id: "fourth-v2x-referrals", label: "V2X defense referrals", value: 5427, unit: "count", category: "workforce" },
    { id: "fourth-kuwait-referrals", label: "Kuwait OCONUS referrals", value: 1778, unit: "count", category: "risk" },
  ],
  riskMatrix: [
    { name: "RTX economic burden", revenue: 262.5, risk: 8.5, workers: 185000 },
    { name: "Amentum DBA exposure", revenue: 54.0, risk: 9.5, workers: 53000 },
    { name: "Third-party provider dependence", revenue: 97.9, risk: 8.0, workers: 16387 },
    { name: "Kuwait OCONUS referrals", revenue: 1778, risk: 9.0, workers: 1778 },
    { name: "Tier 1 exam volume", revenue: 2229, risk: 8.5, workers: 2229 },
  ],
  opportunityMatrix: [
    { name: "RTX Portfolio Revenue Lane", revenuePotential: 17344, implementationComplexity: 7, strategicValue: 10 },
    { name: "Northrop Revenue Lane", revenuePotential: 8900, implementationComplexity: 7, strategicValue: 9 },
    { name: "Amentum DBA Exposure Lane", revenuePotential: 54000, implementationComplexity: 6, strategicValue: 10 },
    { name: "Provider Share Governance", revenuePotential: 5979, implementationComplexity: 5, strategicValue: 9 },
    { name: "Kuwait / Iraq / UAE Coverage", revenuePotential: 3899, implementationComplexity: 6, strategicValue: 10 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Fourth batch: portfolio-level prioritization",
      narrative:
        "This batch is primarily a portfolio and network-share intake package. It should eventually enrich Master Portfolio Intelligence, DBA Carrier/Exposure Intelligence, Provider Network Intelligence, and OCONUS Referral Coverage rather than remain as a standalone chart-pack profile.",
      bullets: [
        "Top three burden accounts represent 53% of the total modeled $2.59B annual burden.",
        "Amentum, KBR, and PAE drive 46% of modeled OCONUS/DBA exposure.",
        "The modeled annual Occu-Med revenue midpoint is $70.5M across the portfolio.",
      ],
      metricIds: ["fourth-total-burden", "fourth-total-dba", "fourth-revenue-midpoint"],
    },
    {
      type: "locations",
      title: "Provider and OCONUS coverage implications",
      narrative:
        "Provider-share and OCONUS-referral charts show where the network needs governance. Occu-Med is overwhelmingly dependent on third-party clinics, while Kuwait, Iraq, UAE, Qatar, and the Marshall Islands remain the highest-volume OCONUS countries.",
      bullets: [
        "Occu-Med own facilities account for only 2.1% of provider-network visits in the uploaded chart.",
        "Concentra, Swedish Specialist Erbil, British Medical Kuwait, and Agile OccMed CA are major named providers in the visit-share charts.",
        "Kuwait, Iraq, and UAE/Dubai remain the highest OCONUS referral concentrations.",
      ],
      metricIds: ["fourth-own-facility-share", "fourth-third-party-share", "fourth-kuwait-referrals"],
    },
    {
      type: "medical-opportunities",
      title: "Later cleanup target",
      narrative:
        "After the upload cycle is finished, split this data into the right themed sections and remove chart-pack clutter from the top of the dropdown.",
      bullets: [
        "Master Portfolio should own burden, headcount, revenue midpoint, and TRIR distribution.",
        "DBA/Claims Intelligence should own the account DBA exposure model.",
        "Network Intelligence should own priority tier, provider-share, defense-referral, and OCONUS country charts.",
      ],
      metricIds: ["fourth-v2x-referrals"],
    },
  ],
};
