import type { CompanyConfig } from "./types";

export const uploadedChartPackIntelligenceConfig: CompanyConfig = {
  companyId: "uploaded-chart-pack-intelligence",
  displayName: "Uploaded Chart Pack Intelligence",
  shortName: "Chart Pack",
  sector:
    "Uploaded dashboard chart capture, economic burden modeling, DBA exposure, fatality expected value, referral concentration, OCONUS demand, prospect coverage, scheduling volume, facility footprint, hiring activity, and network hotspot intelligence",
  headquarters: "Occu-Med chart-intake layer",
  employees: 0,
  employeesAsOf:
    "Uploaded June chart pack: 19 PNG dashboard exports covering injury economics, referral demand, client concentration, provider-network gaps, facility footprint, hiring activity, and prospect pipeline signals",
  summary:
    "Uploaded Chart Pack Intelligence preserves the latest chart-only upload as one source-specific intelligence layer so the data is captured now and can be reorganized later. The charts add a compact view across multiple existing themes: injury economics for GDIT/IAP/PAE/KBR/Peraton/Valiant/Trace/S3, OCONUS demand led by Kuwait/Iraq/UAE/Qatar, client concentration dominated by V2X, prospect coverage where Occu-Med is already present, contractor concentration hotspots such as Stuttgart/Herndon/Huntsville/London/San Diego, scheduling event concentration, CONUS vs OCONUS facility mix, and hiring/prospect pipeline anomalies. This file should eventually be broken into the correct future sections — Portfolio Intelligence, Network & Location Intelligence, Prospect / Sales Intelligence, and Entity Profiles — but for now it intentionally captures the charts without forcing another premature dropdown cleanup.",
  tags: [
    "Entity profile",
    "Chart pack",
    "Dashboard upload",
    "Economic burden",
    "DBA exposure",
    "Fatality expected value",
    "Referral concentration",
    "OCONUS demand",
    "Client concentration",
    "Prospect coverage",
    "Network hotspots",
    "Facility footprint",
    "Hiring activity",
    "Data quality flag",
  ],
  aliases: ["Chart Pack", "Uploaded Dashboard Charts", "Chart Intake", "Dashboard Export Batch"],
  sourceFilters: {
    newsSources: {
      aliases: ["Occu-Med chart pack", "Occu-Med client concentration", "Occu-Med OCONUS demand", "Occu-Med DBA exposure"],
    },
  },
  executiveSignals: [
    { label: "Largest burden", value: "KBR $114.94M", note: "Uploaded economic burden chart: KBR leads the modeled workplace-injury burden set." },
    { label: "Largest DBA exposure", value: "KBR $45.0M", note: "Uploaded DBA chart: KBR and PAE-Legacy are the largest annual DBA claim-exposure bars." },
    { label: "Referral concentration", value: "V2X ~49%", note: "Uploaded concentration charts show V2X as roughly half of defense referral volume." },
    { label: "OCONUS demand", value: "Kuwait 1,778", note: "Uploaded OCONUS demand chart shows Kuwait as the highest referral-demand country." },
  ],
  curveTitle: "Uploaded chart pack: burden, DBA, referral concentration, provider gaps, and prospect curve",
  curveSubtitle:
    "Chart-only upload captured as a temporary intelligence profile. Some chart labels are exact from the image; ambiguous/low-legibility items are preserved as directional signals for later structured intake.",
  chartDefinitions: [
    {
      id: "uploaded-economic-burden",
      title: "Total economic burden of workplace injuries",
      subtitle: "Source chart: NSC $43K/injury × 5.5 indirect multiplier. Values are $M/yr.",
      type: "bar",
      xKey: "company",
      data: [
        { company: "GDIT", burden: 50.85 },
        { company: "IAP Worldwide", burden: 8.99 },
        { company: "PAE-Legacy", burden: 51.56 },
        { company: "KBR", burden: 114.94 },
        { company: "Peraton", burden: 27.79 },
        { company: "Valiant", burden: 21.78 },
        { company: "Trace Systems", burden: 1.14 },
        { company: "S3 International", burden: 4.04 },
      ],
      series: [{ dataKey: "burden", name: "Economic burden", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "injury burden",
      fullWidth: true,
    },
    {
      id: "uploaded-dba-exposure",
      title: "Annual DBA claim exposure by company",
      subtitle: "Source chart: OCONUS injuries × $300K average DBA claim. Values are $M/yr.",
      type: "bar",
      xKey: "company",
      data: [
        { company: "GDIT", dba: 12.60 },
        { company: "IAP Worldwide", dba: 9.83 },
        { company: "PAE-Legacy", dba: 37.50 },
        { company: "KBR", dba: 45.00 },
        { company: "Peraton", dba: 8.70 },
        { company: "Valiant", dba: 3.24 },
        { company: "Trace Systems", dba: 1.19 },
        { company: "S3 International", dba: 4.95 },
      ],
      series: [{ dataKey: "dba", name: "DBA exposure", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "DBA exposure",
      fullWidth: true,
    },
    {
      id: "uploaded-fatality-expected-value",
      title: "Annual fatality expected value by company",
      subtitle: "Source chart: OCONUS workers × BLS fatal rate × $3M DBA death benefit; domestic × $1.46M. Values are $K/yr.",
      type: "bar",
      xKey: "company",
      data: [
        { company: "GDIT", fatalityEv: 216 },
        { company: "IAP Worldwide", fatalityEv: 190 },
        { company: "PAE-Legacy", fatalityEv: 918 },
        { company: "KBR", fatalityEv: 864 },
        { company: "Peraton", fatalityEv: 198 },
        { company: "Valiant", fatalityEv: 115 },
        { company: "Trace Systems", fatalityEv: 18 },
        { company: "S3 International", fatalityEv: 82 },
      ],
      series: [{ dataKey: "fatalityEv", name: "Fatality EV", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "fatality EV",
    },
    {
      id: "uploaded-recordable-injuries",
      title: "Expected recordable injuries by company",
      subtitle: "Source chart: BLS benchmark method; not company-reported figures.",
      type: "bar",
      xKey: "company",
      data: [
        { company: "GDIT", injuries: 215.0 },
        { company: "IAP Worldwide", injuries: 38.0 },
        { company: "PAE-Legacy", injuries: 218.0 },
        { company: "KBR", injuries: 486.0 },
        { company: "Peraton", injuries: 117.5 },
        { company: "Valiant", injuries: 92.1 },
        { company: "Trace Systems", injuries: 4.8 },
        { company: "S3 International", injuries: 17.1 },
      ],
      series: [{ dataKey: "injuries", name: "Expected recordables", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "recordables",
      fullWidth: true,
    },
    {
      id: "uploaded-core-revenue",
      title: "Occu-Med core revenue: pre-employment + DBA pre-deployment",
      subtitle: "Source chart: primary revenue drivers; all other services are upsell after relationship established. Values are $K/yr.",
      type: "stacked",
      xKey: "company",
      data: [
        { company: "GDIT", preEmployment: 1088, dbaPreDeploy: 0 },
        { company: "IAP Worldwide", preEmployment: 65, dbaPreDeploy: 245 },
        { company: "PAE-Legacy", preEmployment: 315, dbaPreDeploy: 380 },
        { company: "KBR", preEmployment: 1375, dbaPreDeploy: 1350 },
        { company: "Peraton", preEmployment: 938, dbaPreDeploy: 462 },
        { company: "Valiant", preEmployment: 172, dbaPreDeploy: 202 },
        { company: "Trace Systems", preEmployment: 50, dbaPreDeploy: 76 },
        { company: "S3 International", preEmployment: 24, dbaPreDeploy: 220 },
      ],
      series: [
        { dataKey: "preEmployment", name: "Pre-employment physicals", color: "#22d3ee", stackId: "revenue" },
        { dataKey: "dbaPreDeploy", name: "DBA pre-deployment medicals", color: "#ef4444", stackId: "revenue", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "core revenue",
      fullWidth: true,
    },
    {
      id: "uploaded-oconus-demand-country",
      title: "OCONUS provider network demand by country",
      subtitle: "Source chart: Kuwait leads overseas medical exam referrals.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Kuwait", referrals: 1778 },
        { country: "Iraq", referrals: 1157 },
        { country: "UAE / Dubai", referrals: 964 },
        { country: "Qatar", referrals: 718 },
        { country: "Marshall Islands", referrals: 415 },
        { country: "Jordan", referrals: 255 },
        { country: "Djibouti", referrals: 174 },
        { country: "Kenya", referrals: 146 },
        { country: "India", referrals: 121 },
        { country: "Bahrain", referrals: 78 },
        { country: "Saudi Arabia", referrals: 58 },
        { country: "Germany", referrals: 52 },
        { country: "Philippines", referrals: 51 },
        { country: "Thailand", referrals: 34 },
      ],
      series: [{ dataKey: "referrals", name: "Referral count", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "OCONUS demand",
      fullWidth: true,
    },
    {
      id: "uploaded-defense-referrals-client",
      title: "Defense contractor referrals by client",
      subtitle: "Source chart: V2X / Vectrus dominates referral volume.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "V2X / Vectrus", referrals: 5427 },
        { client: "Amentum", referrals: 852 },
        { client: "Constellis", referrals: 610 },
        { client: "GDIT", referrals: 437 },
        { client: "Valiant Integrated Services", referrals: 423 },
        { client: "IAP Worldwide", referrals: 409 },
        { client: "Leidos", referrals: 307 },
        { client: "Deployment Center", referrals: 283 },
        { client: "Vertex", referrals: 234 },
        { client: "ManTech International", referrals: 199 },
        { client: "IDS International", referrals: 155 },
        { client: "International SOS", referrals: 150 },
        { client: "CACI International", referrals: 148 },
        { client: "Sierra Nevada Corp", referrals: 146 },
        { client: "Trace Systems", referrals: 127 },
      ],
      series: [{ dataKey: "referrals", name: "Total referrals", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "referral volume",
      fullWidth: true,
    },
    {
      id: "uploaded-client-concentration",
      title: "Referral concentration by client",
      subtitle: "Source chart: V2X alone is roughly 49% of all defense referrals; top concentration creates account-retention risk.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "V2X / Vectrus", referrals: 5418, share: 49 },
        { client: "All Others", referrals: 2270, share: 20 },
        { client: "Amentum", referrals: 852, share: 8 },
        { client: "Constellis", referrals: 610, share: 5 },
        { client: "GDIT", referrals: 437, share: 4 },
        { client: "Valiant", referrals: 423, share: 4 },
        { client: "IAP", referrals: 409, share: 4 },
        { client: "Deployment Ctr", referrals: 283, share: 3 },
        { client: "Vertex", referrals: 234, share: 2 },
        { client: "Leidos", referrals: 226, share: 2 },
      ],
      series: [{ dataKey: "referrals", name: "Referrals", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "concentration",
    },
    {
      id: "uploaded-contractor-hotspots",
      title: "Contractor concentration hotspots",
      subtitle: "Source chart statuses: red = no clinic coverage, orange = underserved, green = covered.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Stuttgart, DE", clients: 16, status: "no coverage" },
        { location: "Herndon, VA", clients: 14, status: "no coverage" },
        { location: "Huntsville, AL", clients: 14, status: "no coverage" },
        { location: "London, UK", clients: 13, status: "no coverage" },
        { location: "San Diego, CA", clients: 12, status: "underserved" },
        { location: "Chantilly, VA", clients: 11, status: "no coverage" },
        { location: "Doha, Qatar", clients: 11, status: "covered" },
        { location: "Arlington, VA", clients: 11, status: "no coverage" },
        { location: "Baghdad, Iraq", clients: 11, status: "covered" },
        { location: "Riyadh, KSA", clients: 10, status: "no coverage" },
        { location: "Colorado Springs, CO", clients: 9, status: "underserved" },
        { location: "Falls Church, VA", clients: 8, status: "no coverage" },
        { location: "Manila, PH", clients: 8, status: "no coverage" },
        { location: "Kuwait City", clients: 8, status: "covered" },
        { location: "Fort Belvoir, VA", clients: 7, status: "no coverage" },
        { location: "Tampa, FL", clients: 7, status: "no coverage" },
      ],
      series: [{ dataKey: "clients", name: "# of clients", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "hotspots",
      fullWidth: true,
    },
    {
      id: "uploaded-scheduling-events",
      title: "Scheduling events by client — top 15",
      subtitle: "Source chart: complete event labels shown; V2X is about 48% of all events.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "V2X", complete: 12056 },
        { client: "Amentum", complete: 2761 },
        { client: "Valiant", complete: 2113 },
        { client: "Leidos", complete: 960 },
        { client: "IAP", complete: 954 },
        { client: "Vertex", complete: 776 },
        { client: "CACI", complete: 603 },
        { client: "Sierra Nevada Corporation", complete: 505 },
        { client: "International SOS", complete: 442 },
        { client: "IDS International", complete: 364 },
        { client: "ManTech", complete: 336 },
        { client: "GDC Middle East", complete: 317 },
        { client: "Freeport", complete: 308 },
        { client: "Alutiiq", complete: 268 },
        { client: "Trace Systems", complete: 236 },
      ],
      series: [{ dataKey: "complete", name: "Complete events", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "schedule events",
      fullWidth: true,
    },
    {
      id: "uploaded-conus-oconus-split",
      title: "Geographic footprint split",
      subtitle: "Source chart: 913 OCONUS sites = DBA compliance critical.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "OCONUS", share: 62.6 },
        { region: "CONUS", share: 37.4 },
      ],
      series: [{ dataKey: "share", name: "Facility share", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 100],
      headline: "global split",
    },
    {
      id: "uploaded-completed-exams-country",
      title: "Completed exams by country — top 12",
      subtitle: "Source chart: OCONUS = 39% of completions.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "United States", completed: 14937 },
        { country: "Kuwait", completed: 2277 },
        { country: "United Arab Emirates", completed: 1617 },
        { country: "Iraq", completed: 1332 },
        { country: "Qatar", completed: 834 },
        { country: "Marshall Islands", completed: 819 },
        { country: "Jordan", completed: 456 },
        { country: "Kenya", completed: 288 },
        { country: "Djibouti", completed: 242 },
        { country: "India", completed: 216 },
        { country: "Bahrain", completed: 122 },
        { country: "Unknown / nan", completed: 114 },
      ],
      series: [{ dataKey: "completed", name: "Completed exams", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "completions",
      fullWidth: true,
    },
    {
      id: "uploaded-facility-footprint",
      title: "Client portfolio: facility footprint top 15",
      subtitle: "Source chart: 49 clients, 1,446 facility records, 62% OCONUS. Values are approximated from chart labels/bar heights where label text is not fully legible.",
      type: "stacked",
      xKey: "client",
      data: [
        { client: "Weatherford", us: 10, oconus: 125 },
        { client: "Leidos", us: 41, oconus: 50 },
        { client: "Applus+", us: 2, oconus: 88 },
        { client: "World Vision", us: 8, oconus: 78 },
        { client: "V2X", us: 46, oconus: 34 },
        { client: "Amentum", us: 16, oconus: 53 },
        { client: "Versar Global", us: 14, oconus: 48 },
        { client: "GDC", us: 27, oconus: 33 },
        { client: "Peraton", us: 26, oconus: 29 },
        { client: "CACI", us: 29, oconus: 23 },
        { client: "PAE", us: 26, oconus: 16 },
        { client: "BAE Systems", us: 11, oconus: 27 },
        { client: "Valiant", us: 14, oconus: 23 },
        { client: "SOS International", us: 14, oconus: 22 },
        { client: "QinetiQ", us: 4, oconus: 31 },
      ],
      series: [
        { dataKey: "us", name: "US facilities", color: "#2563eb", stackId: "facilities" },
        { dataKey: "oconus", name: "OCONUS facilities", color: "#f97316", stackId: "facilities", radius: [10, 10, 0, 0] },
      ],
      headline: "facility footprint",
      fullWidth: true,
    },
    {
      id: "uploaded-oconus-countries-facility-count",
      title: "Top OCONUS countries by facility count",
      subtitle: "Source chart: 901 OCONUS facilities; UK + Germany + Philippines + Canada = 47% of all OCONUS presence.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "UK", facilities: 76 },
        { country: "Germany", facilities: 60 },
        { country: "Philippines", facilities: 53 },
        { country: "Canada", facilities: 44 },
        { country: "Australia", facilities: 38 },
        { country: "Kuwait", facilities: 33 },
        { country: "Iraq", facilities: 31 },
        { country: "Italy", facilities: 26 },
        { country: "Qatar", facilities: 24 },
        { country: "Saudi Arabia", facilities: 23 },
        { country: "Japan", facilities: 23 },
        { country: "Afghanistan", facilities: 16 },
        { country: "Russia", facilities: 16 },
        { country: "South Korea", facilities: 14 },
        { country: "Bahrain", facilities: 14 },
      ],
      series: [{ dataKey: "facilities", name: "Facility count", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      headline: "OCONUS footprint",
    },
    {
      id: "uploaded-prospect-pipeline-postings",
      title: "Prospect pipeline: top non-clients by total job postings",
      subtitle: "Source chart includes a likely scrape/data-quality outlier for Leidos Holdings Inc.; preserve but flag before use.",
      type: "bar",
      xKey: "prospect",
      data: [
        { prospect: "Leidos Holdings, Inc.", postings: 875739, quality: "outlier / verify" },
        { prospect: "Boeing", postings: 1660, quality: "usable" },
        { prospect: "Parsons", postings: 2203, quality: "usable" },
        { prospect: "Northrop Grumman", postings: 2130, quality: "usable" },
        { prospect: "RTX", postings: 1701, quality: "usable" },
        { prospect: "Safran", postings: 875, quality: "usable" },
        { prospect: "Thales", postings: 738, quality: "usable" },
        { prospect: "SAIC", postings: 675, quality: "usable" },
        { prospect: "Leonardo", postings: 654, quality: "usable" },
        { prospect: "Rheinmetall", postings: 590, quality: "usable" },
        { prospect: "Peckham Inc.", postings: 90, quality: "usable" },
        { prospect: "Valiant Technical Services", postings: 77, quality: "usable" },
        { prospect: "Kongsberg", postings: 75, quality: "usable" },
        { prospect: "Bodwé Professional Services", postings: 51, quality: "usable" },
        { prospect: "ULA", postings: 43, quality: "usable" },
      ],
      series: [{ dataKey: "postings", name: "Total job postings", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "pipeline postings",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "chartpack-largest-burden", label: "Largest modeled burden", value: 114.94, unit: "usd", category: "financial" },
    { id: "chartpack-largest-dba", label: "Largest DBA exposure", value: 45.0, unit: "usd", category: "risk" },
    { id: "chartpack-v2x-referrals", label: "V2X defense referrals", value: 5427, unit: "count", category: "workforce" },
    { id: "chartpack-kuwait-demand", label: "Kuwait OCONUS referrals", value: 1778, unit: "count", category: "workforce" },
    { id: "chartpack-oconus-share", label: "OCONUS facility share", value: 62.6, unit: "percent", category: "risk" },
    { id: "chartpack-oconus-facilities", label: "OCONUS facility count", value: 913, unit: "count", category: "workforce" },
    { id: "chartpack-top-hotspot-clients", label: "Stuttgart hotspot clients", value: 16, unit: "count", category: "risk" },
  ],
  riskMatrix: [
    { name: "V2X referral concentration", revenue: 5427, risk: 10.0, workers: 5427 },
    { name: "KBR burden / DBA", revenue: 114.94, risk: 9.5, workers: 486 },
    { name: "Kuwait OCONUS demand", revenue: 1778, risk: 9.5, workers: 1778 },
    { name: "Stuttgart no-coverage hotspot", revenue: 16, risk: 9.0, workers: 16 },
    { name: "Leidos posting outlier", revenue: 875739, risk: 8.0, workers: 1 },
  ],
  opportunityMatrix: [
    { name: "Kuwait Provider Network", revenuePotential: 1778, implementationComplexity: 7, strategicValue: 10 },
    { name: "Stuttgart Gap Fix", revenuePotential: 16, implementationComplexity: 7, strategicValue: 9 },
    { name: "KBR / PAE DBA Revenue Lane", revenuePotential: 2730, implementationComplexity: 7, strategicValue: 10 },
    { name: "V2X Concentration Risk Program", revenuePotential: 5427, implementationComplexity: 6, strategicValue: 10 },
    { name: "Prospect Posting Data Cleanup", revenuePotential: 875739, implementationComplexity: 3, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Why this chart pack matters",
      narrative:
        "This upload is not a normal company report. It is a set of dashboard outputs that should feed several future themes: portfolio burden, referral demand, location gaps, prospect coverage, facility footprint, and hiring pipeline.",
      bullets: [
        "KBR is the largest modeled economic-burden and DBA-exposure bar in the core injury economics charts.",
        "V2X dominates referral and scheduling concentration, creating both revenue dependence and account-retention risk.",
        "Kuwait, Iraq, UAE/Dubai, Qatar, and the Marshall Islands remain the most important OCONUS referral-demand geographies.",
        "Stuttgart, Herndon, Huntsville, London, San Diego, and Chantilly are high-value hotspot/gap targets.",
      ],
      metricIds: ["chartpack-largest-burden", "chartpack-largest-dba", "chartpack-v2x-referrals", "chartpack-kuwait-demand"],
    },
    {
      type: "locations",
      title: "Network and provider-coverage implications",
      narrative:
        "The location charts reinforce that provider-network strategy should be built around OCONUS country demand, contractor concentration hotspots, single-market client density, and facility footprint concentration.",
      bullets: [
        "OCONUS facilities represent roughly 62.6% of the facility footprint in the uploaded split chart.",
        "The top OCONUS facility countries are UK, Germany, Philippines, Canada, Australia, Kuwait, Iraq, Italy, Qatar, Saudi Arabia, and Japan.",
        "Hotspots should be triaged by current status: no coverage, underserved, or covered.",
      ],
      metricIds: ["chartpack-oconus-share", "chartpack-oconus-facilities", "chartpack-top-hotspot-clients"],
    },
    {
      type: "medical-opportunities",
      title: "Data quality and next cleanup",
      narrative:
        "Some chart outputs should not be blindly promoted into client-facing materials. In particular, the Leidos Holdings posting count appears to be a scrape/data-quality outlier and should be verified before use. The future cleanup pass should split this one chart-pack profile into portfolio, network, prospect, and scheduling sections.",
      bullets: [
        "Preserve the images and extracted values now; reorganize later.",
        "Treat ambiguous chart labels and approximate stacked-bar values as intake signals until the underlying spreadsheet is available.",
        "The next best improvement is to load the source spreadsheets directly rather than screenshot charts.",
      ],
      metricIds: [],
    },
  ],
};
