import type { CompanyConfig } from "./types";

export const uploadedChartPackThirdIntelligenceConfig: CompanyConfig = {
  companyId: "uploaded-chart-pack-third-intelligence",
  displayName: "Uploaded Chart Pack Third Batch Intelligence",
  shortName: "Chart Batch 3",
  sector:
    "Freeport-McMoRan peer-performance modeling, GDIT contract and injury-cost modeling, hiring and prospect growth signals, active network clinic volume, OCONUS personal-physician gap analysis, no-show rate analysis, Amentum NSC safety award trend, and multi-client provider-network density nodes",
  headquarters: "Occu-Med chart-intake layer",
  employees: 0,
  employeesAsOf:
    "Uploaded third chart batch: 19 PNG dashboard exports covering FCX avoided injuries, GDIT contract/revenue/risk modeling, network gaps, no-show rates, active clinics, overlap nodes, prospect footprint, and Amentum award trend",
  summary:
    "Uploaded Chart Pack Third Batch Intelligence preserves the third chart-only upload into the same PR #26 intake branch. This batch adds stronger entity-level signals for Freeport-McMoRan and GDIT while also adding network operations and provider-network prioritization. The FCX charts show peer-performance value: using a BLS peer benchmark of 1.80 versus FCX actual 0.69 over roughly 238M hours, the chart estimates about 972 expected recordable injuries, about 270 actual recordables, and roughly 702 injuries avoided annually versus peers. The GDIT charts show a 2025 award portfolio around $3.4B, direct injury-cost modeling by worker type, pre-employment revenue sensitivity by turnover rate, and a service-line revenue stack led by pre-employment physicals and DBA pre-deployment medicals. The network charts identify active clinic volume leaders, OCONUS personal-physician gaps led by Australia and Kenya, high no-show clients led by Trace Systems and International SOS, Amentum NSC award growth from 2023-2025, and multi-client provider-network density nodes with Stuttgart, Herndon, Huntsville, London, San Diego, Baghdad, Doha, Chantilly, Arlington, and Kabul as high-priority overlap markets. Hiring activity by country is preserved with explicit data-quality caution because the USA and UK values appear to be scrape outliers.",
  tags: [
    "Entity profile",
    "Chart pack third batch",
    "Freeport-McMoRan",
    "FCX",
    "GDIT",
    "Injuries avoided",
    "GDIT contracts",
    "Pre-employment revenue",
    "Network clinics",
    "OCONUS gaps",
    "No-show rate",
    "Amentum NSC awards",
    "Provider network",
    "Multi-client density",
    "Data quality flag",
  ],
  aliases: ["Chart Batch 3", "GDIT FCX Network Addendum", "Third Chart Upload", "Provider Network Density Charts"],
  sourceFilters: {
    newsSources: {
      aliases: ["Occu-Med GDIT chart pack", "Occu-Med FCX avoided injuries", "Occu-Med network gap chart", "Occu-Med no-show rate chart"],
    },
  },
  executiveSignals: [
    { label: "FCX avoided injuries", value: "~702/year", note: "Uploaded FCX peer chart estimates about 702 recordable injuries avoided annually versus BLS peers." },
    { label: "GDIT 2025 awards", value: "$3.4B", note: "Uploaded GDIT contract portfolio chart totals major 2025 awards across STRATCOM IT, EMITS 2, SOCOM IT, NOAA, and Army base-readiness work." },
    { label: "Top no-show rate", value: "Trace 8.9%", note: "Uploaded no-show chart: Trace Systems leads clients with 100+ events; portfolio average marked at 4.5%." },
    { label: "Top density node", value: "Stuttgart 16", note: "Uploaded overlap-node chart: Stuttgart has the largest multi-client density signal." },
  ],
  curveTitle: "Third chart batch: FCX avoided injuries, GDIT revenue/risk model, and network operations curve",
  curveSubtitle:
    "Third uploaded chart batch captured as source-specific intelligence. Several values are screenshot-derived; outliers are explicitly flagged for later replacement with source spreadsheets.",
  chartDefinitions: [
    {
      id: "third-fcx-injuries-avoided-peers",
      title: "FCX injuries avoided versus BLS peers",
      subtitle: "Uploaded chart: BLS peer benchmark 1.80 vs FCX actual 0.69 over ~238M hours = about 702 avoided recordables/year.",
      type: "bar",
      xKey: "scenario",
      data: [
        { scenario: "Expected at BLS Benchmark", recordables: 972 },
        { scenario: "FCX Actual", recordables: 270 },
        { scenario: "Injuries Avoided / Year", recordables: 702 },
      ],
      series: [{ dataKey: "recordables", name: "Annual recordable injuries", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "FCX avoided injuries",
      fullWidth: true,
    },
    {
      id: "third-gdit-contract-portfolio",
      title: "GDIT contract portfolio: major 2025 awards",
      subtitle: "Uploaded chart: about $3.4B in highlighted 2025 awards.",
      type: "bar",
      xKey: "contract",
      data: [
        { contract: "STRATCOM IT", valueB: 1.50 },
        { contract: "EMITS 2 Army Europe", valueB: 1.25 },
        { contract: "SOCOM IT Enterprise", valueB: 0.396 },
        { contract: "NOAA NWS Supercomputing", valueB: 0.180 },
        { contract: "Army Base Readiness", valueB: 0.120 },
      ],
      series: [{ dataKey: "valueB", name: "Contract value ($B)", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "GDIT awards",
      fullWidth: true,
    },
    {
      id: "third-gdit-injury-cost-worker-type",
      title: "GDIT estimated annual direct injury cost by worker type",
      subtitle: "Uploaded chart: direct injury cost model by worker category.",
      type: "bar",
      xKey: "workerCategory",
      data: [
        { workerCategory: "Cleared IT/Engineering", workers: 22000, directCost: 2.5 },
        { workerCategory: "Data Center Tech", workers: 2000, directCost: 1.1 },
        { workerCategory: "OCONUS Deployed", workers: 1500, directCost: 1.3 },
        { workerCategory: "Mission Support", workers: 4500, directCost: 0.8 },
      ],
      series: [{ dataKey: "directCost", name: "Direct injury cost", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "GDIT injury cost",
      fullWidth: true,
    },
    {
      id: "third-gdit-occumed-revenue",
      title: "GDIT Occu-Med annual revenue potential",
      subtitle: "Uploaded chart: annual revenue potential by exam/service type. Values are $K/year.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Pre-Employment Physicals", revenue: 1088 },
        { examType: "DBA Pre-Deploy Medicals", revenue: 338 },
        { examType: "Ergonomic Assessments", revenue: 200 },
        { examType: "Behavioral Health Screen", revenue: 155 },
        { examType: "Data Center Audiometry", revenue: 39 },
        { examType: "Drug Screen", revenue: 145 },
      ],
      series: [{ dataKey: "revenue", name: "Annual revenue", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "GDIT revenue",
      fullWidth: true,
    },
    {
      id: "third-gdit-bls-risk",
      title: "GDIT worker risk by BLS TRIR benchmark",
      subtitle: "Uploaded chart: OCONUS deployed IT personnel carry the highest benchmark risk despite smaller headcount.",
      type: "bar",
      xKey: "workerCategory",
      data: [
        { workerCategory: "Cleared IT Analysts & Engineers", trir: 0.5, expectedInjuries: 55 },
        { workerCategory: "Data Center Technicians", trir: 1.8, expectedInjuries: 18 },
        { workerCategory: "OCONUS Deployed IT Personnel", trir: 2.8, expectedInjuries: 21 },
        { workerCategory: "Mission Support", trir: 0.6, expectedInjuries: 14 },
      ],
      series: [{ dataKey: "trir", name: "BLS TRIR benchmark", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 3],
      headline: "GDIT risk",
      fullWidth: true,
    },
    {
      id: "third-gdit-turnover-revenue",
      title: "GDIT pre-employment exam revenue by annual turnover rate",
      subtitle: "Uploaded chart: low $150/exam and additional high $250/exam scenario stacked by turnover.",
      type: "stacked",
      xKey: "scenario",
      data: [
        { scenario: "10% Turnover", hires: 3000, low: 450, additionalHigh: 300 },
        { scenario: "15% Turnover", hires: 4500, low: 675, additionalHigh: 450 },
        { scenario: "20% Turnover", hires: 6000, low: 900, additionalHigh: 600 },
        { scenario: "25% Turnover", hires: 7500, low: 1125, additionalHigh: 750 },
      ],
      series: [
        { dataKey: "low", name: "Low scenario", color: "#22d3ee", stackId: "revenue" },
        { dataKey: "additionalHigh", name: "Additional high scenario", color: "#ef4444", stackId: "revenue", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyK",
      headline: "turnover revenue",
      fullWidth: true,
    },
    {
      id: "third-growth-potential",
      title: "Growth potential: current clients vs tracked prospects",
      subtitle: "Uploaded chart: tracked prospects represent roughly 66% of current client footprint.",
      type: "bar",
      xKey: "group",
      data: [
        { group: "Current Clients", sites: 1458 },
        { group: "Tracked Prospects", sites: 956 },
      ],
      series: [{ dataKey: "sites", name: "Total sites", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "growth potential",
    },
    {
      id: "third-hiring-activity-country",
      title: "Hiring activity by country",
      subtitle: "Uploaded chart: open-position demand signal. USA and UK values are obvious scrape/data-quality outliers and require verification.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "USA", postings: 197878408, quality: "outlier / verify" },
        { country: "UK", postings: 2518635, quality: "outlier / verify" },
        { country: "Australia", postings: 6813, quality: "verify" },
        { country: "Indonesia", postings: 320, quality: "usable" },
        { country: "Saudi Arabia", postings: 256, quality: "usable" },
        { country: "Iraq", postings: 79, quality: "usable" },
        { country: "Antarctica", postings: 43, quality: "usable" },
        { country: "Germany", postings: 40, quality: "usable" },
        { country: "Guam", postings: 39, quality: "usable" },
        { country: "Philippines", postings: 33, quality: "usable" },
        { country: "Madrid", postings: 30, quality: "usable" },
        { country: "Catalunya", postings: 25, quality: "usable" },
        { country: "Qatar", postings: 22, quality: "usable" },
        { country: "Japan", postings: 14, quality: "usable" },
        { country: "Canada", postings: 12, quality: "usable" },
      ],
      series: [{ dataKey: "postings", name: "Postings", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "hiring activity",
      fullWidth: true,
    },
    {
      id: "third-active-network-clinics",
      title: "Top active network clinics by exam volume",
      subtitle: "Uploaded chart: LabCorp Solutions, Swedish Specialist Hospital, British Medical Centre, and Concentra dominate completed volume.",
      type: "bar",
      xKey: "clinic",
      data: [
        { clinic: "LabCorp Solutions", completed: 3045 },
        { clinic: "Swedish Specialist Hospital", completed: 1978 },
        { clinic: "British Medical Centre", completed: 1792 },
        { clinic: "Concentra", completed: 1732 },
        { clinic: "Occu-Med Internal", completed: 813 },
        { clinic: "Tracy Lee, MD", completed: 747 },
        { clinic: "Asian Medical Centre", completed: 699 },
        { clinic: "NAVAIR Patuxent Onsite", completed: 680 },
        { clinic: "Fort Liberty Onsite", completed: 659 },
        { clinic: "Fort Moore Onsite", completed: 572 },
        { clinic: "LabCorp at Walgreens", completed: 504 },
        { clinic: "Kwajalein Hospital", completed: 463 },
        { clinic: "Mission Critical Psych", completed: 446 },
        { clinic: "GMC Clinics Dubai", completed: 383 },
        { clinic: "American Family Care", completed: 251 },
        { clinic: "Atrion partial", completed: 180 },
        { clinic: "MIOT Intl / ISOS India", completed: 172 },
        { clinic: "Lancet Labs Kenya", completed: 167 },
        { clinic: "Caduceus Occ Med", completed: 162 },
        { clinic: "Unknown / Blank", completed: 160 },
      ],
      series: [{ dataKey: "completed", name: "Completed exams", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "active clinics",
      fullWidth: true,
    },
    {
      id: "third-oconus-personal-physician-gaps",
      title: "OCONUS network gaps: personal physician used",
      subtitle: "Uploaded chart: Australia and Kenya are the top gaps where a personal physician was used.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Australia", examsNoClinic: 24 },
        { country: "Kenya", examsNoClinic: 14 },
        { country: "Iraq", examsNoClinic: 8 },
        { country: "Japan", examsNoClinic: 8 },
        { country: "Marshall Islands", examsNoClinic: 7 },
        { country: "Colombia", examsNoClinic: 6 },
        { country: "Qatar", examsNoClinic: 5 },
        { country: "Dominican Republic", examsNoClinic: 4 },
        { country: "Djibouti", examsNoClinic: 4 },
        { country: "Germany", examsNoClinic: 4 },
        { country: "Malaysia", examsNoClinic: 4 },
        { country: "Mexico", examsNoClinic: 4 },
        { country: "Thailand", examsNoClinic: 3 },
        { country: "Somalia", examsNoClinic: 3 },
        { country: "South Korea", examsNoClinic: 3 },
      ],
      series: [{ dataKey: "examsNoClinic", name: "Exams with no network clinic", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "OCONUS gaps",
      fullWidth: true,
    },
    {
      id: "third-no-show-rate-client",
      title: "No-show rate by client",
      subtitle: "Uploaded chart: minimum 100 events; red line portfolio average 4.5%.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "Trace Systems", noShowRate: 8.9 },
        { client: "International SOS", noShowRate: 8.3 },
        { client: "ASRC Federal", noShowRate: 7.5 },
        { client: "ManTech", noShowRate: 7.2 },
        { client: "Platform Aerospace", noShowRate: 6.6 },
        { client: "IAP", noShowRate: 6.4 },
        { client: "IDS International", noShowRate: 5.9 },
        { client: "Valiant", noShowRate: 5.9 },
        { client: "Amentum", noShowRate: 5.4 },
        { client: "Versar", noShowRate: 4.9 },
        { client: "Leidos", noShowRate: 4.7 },
        { client: "Fluor", noShowRate: 4.5 },
        { client: "CACI", noShowRate: 4.2 },
        { client: "Sierra Nevada Corporation", noShowRate: 3.8 },
        { client: "V2X", noShowRate: 3.8 },
      ],
      series: [{ dataKey: "noShowRate", name: "No-show %", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 10],
      referenceLines: [{ y: 4.5, label: "Portfolio avg 4.5%", color: "#ef4444" }],
      headline: "no-shows",
      fullWidth: true,
    },
    {
      id: "third-amentum-nsc-awards",
      title: "Amentum NSC safety awards growing 2023-2025",
      subtitle: "Uploaded chart: National Safety Council annual award data by award category.",
      type: "grouped",
      xKey: "year",
      data: [
        { year: "2023", perfectRecord: 89, millionHours: 37, safetyLeader: 30, industryLeader: 5, superiorSafety: 10 },
        { year: "2024", perfectRecord: 113, millionHours: 40, safetyLeader: 28, industryLeader: 5, superiorSafety: 8 },
        { year: "2025", perfectRecord: 152, millionHours: 45, safetyLeader: 43, industryLeader: 10, superiorSafety: 9 },
      ],
      series: [
        { dataKey: "perfectRecord", name: "Perfect Record", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "millionHours", name: "Million Hours", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "safetyLeader", name: "Safety Leader", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "industryLeader", name: "Industry Leader", color: "#94a3b8", radius: [8, 8, 0, 0] },
        { dataKey: "superiorSafety", name: "Superior Safety", color: "#facc15", radius: [8, 8, 0, 0] },
      ],
      headline: "NSC awards",
      fullWidth: true,
    },
    {
      id: "third-oconus-demand-coverage-gap",
      title: "OCONUS demand versus clinic coverage gap",
      subtitle: "Uploaded chart: immediate opportunity status by country; UAE is partial, Bahrain/Philippines/Saudi Arabia/Germany have no coverage in the chart.",
      type: "bar",
      xKey: "country",
      data: [
        { country: "Kuwait", referrals: 1787, clients: 8, status: "covered" },
        { country: "Iraq", referrals: 1182, clients: 1, status: "covered" },
        { country: "UAE", referrals: 972, clients: 6, status: "partial" },
        { country: "Qatar", referrals: 729, clients: 11, status: "covered" },
        { country: "Marshall Islands", referrals: 415, clients: 2, status: "covered" },
        { country: "Jordan", referrals: 261, clients: 8, status: "covered" },
        { country: "Djibouti", referrals: 176, clients: 5, status: "covered" },
        { country: "Kenya", referrals: 148, clients: 4, status: "covered" },
        { country: "India", referrals: 123, clients: 4, status: "covered" },
        { country: "Bahrain", referrals: 80, clients: 7, status: "none" },
        { country: "Philippines", referrals: 57, clients: 8, status: "none" },
        { country: "Saudi Arabia", referrals: 53, clients: 10, status: "none" },
        { country: "Germany", referrals: 53, clients: 6, status: "none" },
      ],
      series: [{ dataKey: "referrals", name: "Annual referrals", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "OCONUS coverage",
      fullWidth: true,
    },
    {
      id: "third-overlap-network-gap",
      title: "Provider network gap analysis: 120 multi-client locations uncovered",
      subtitle: "Uploaded chart: tiered by number of clients sharing the same location.",
      type: "bar",
      xKey: "tier",
      data: [
        { tier: "2 clients / Watch Nodes", locations: 113, revenueRiskTier: 2 },
        { tier: "3-4 clients / Opportunity Nodes", locations: 66, revenueRiskTier: 4 },
        { tier: "5-9 clients / Priority Nodes", locations: 34, revenueRiskTier: 9 },
        { tier: "10+ clients / Elite Nodes", locations: 11, revenueRiskTier: 10 },
      ],
      series: [{ dataKey: "locations", name: "Number of locations", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "gap tiers",
    },
    {
      id: "third-overlap-density-top20",
      title: "Top multi-client density nodes",
      subtitle: "Uploaded chart: Stuttgart #1 globally with 16 clients sharing the location.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Stuttgart, Germany", clients: 16, region: "OCONUS" },
        { location: "Herndon, VA", clients: 14, region: "US" },
        { location: "Huntsville, AL", clients: 14, region: "US" },
        { location: "London, UK", clients: 13, region: "OCONUS" },
        { location: "San Diego, CA", clients: 12, region: "US" },
        { location: "Baghdad, Iraq", clients: 11, region: "OCONUS" },
        { location: "Doha, Qatar", clients: 11, region: "OCONUS" },
        { location: "Chantilly, VA", clients: 11, region: "US" },
        { location: "Arlington, VA", clients: 11, region: "US" },
        { location: "Kabul, Afghanistan", clients: 11, region: "OCONUS" },
        { location: "Riyadh, Saudi Arabia", clients: 10, region: "OCONUS" },
        { location: "Colorado Springs, CO", clients: 9, region: "US" },
        { location: "Houston, TX", clients: 9, region: "US" },
        { location: "Washington, DC", clients: 9, region: "US" },
        { location: "San Antonio, TX", clients: 9, region: "US" },
        { location: "Kuwait City, Kuwait", clients: 8, region: "OCONUS" },
        { location: "Camp Arifjan, Kuwait", clients: 8, region: "OCONUS" },
        { location: "Reston, VA", clients: 8, region: "US" },
        { location: "Falls Church, VA", clients: 8, region: "US" },
        { location: "Norfolk, VA", clients: 8, region: "US" },
      ],
      series: [{ dataKey: "clients", name: "Clients sharing location", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "density nodes",
      fullWidth: true,
    },
    {
      id: "third-nova-corridor-density",
      title: "Northern Virginia intel corridor client density by city",
      subtitle: "Uploaded chart: Herndon + Chantilly + Arlington = 36 combined client slots.",
      type: "bar",
      xKey: "city",
      data: [
        { city: "Herndon", clientSlots: 14 },
        { city: "Arlington", clientSlots: 11 },
        { city: "Chantilly", clientSlots: 11 },
        { city: "Reston", clientSlots: 8 },
        { city: "Norfolk", clientSlots: 8 },
        { city: "Falls Church", clientSlots: 8 },
        { city: "Fort Belvoir", clientSlots: 7 },
        { city: "Fairfax", clientSlots: 6 },
      ],
      series: [{ dataKey: "clientSlots", name: "Client slots", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "NoVA density",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "third-fcx-avoided", label: "FCX avoided recordables", value: 702, unit: "count", category: "safety" },
    { id: "third-gdit-awards", label: "GDIT 2025 highlighted awards", value: 3.4, unit: "usd", category: "financial" },
    { id: "third-gdit-preemployment", label: "GDIT pre-employment revenue", value: 1088, unit: "usd", category: "financial" },
    { id: "third-trace-noshow", label: "Trace no-show rate", value: 8.9, unit: "percent", category: "risk" },
    { id: "third-active-labcorp", label: "LabCorp Solutions volume", value: 3045, unit: "count", category: "workforce" },
    { id: "third-australia-gap", label: "Australia personal-physician gap", value: 24, unit: "count", category: "risk" },
    { id: "third-stuttgart-density", label: "Stuttgart client density", value: 16, unit: "count", category: "risk" },
    { id: "third-nova-top3", label: "NoVA top-three client slots", value: 36, unit: "count", category: "risk" },
  ],
  riskMatrix: [
    { name: "Trace Systems no-show rate", revenue: 8.9, risk: 9.0, workers: 100 },
    { name: "Australia OCONUS clinic gap", revenue: 24, risk: 8.5, workers: 24 },
    { name: "Stuttgart density node", revenue: 16, risk: 10.0, workers: 16 },
    { name: "GDIT OCONUS deployed risk", revenue: 2.8, risk: 8.0, workers: 1500 },
    { name: "Hiring scrape outliers", revenue: 197878408, risk: 7.0, workers: 1 },
  ],
  opportunityMatrix: [
    { name: "GDIT Pre-Employment + DBA Program", revenuePotential: 1426, implementationComplexity: 5, strategicValue: 10 },
    { name: "Active Clinic Volume Governance", revenuePotential: 3045, implementationComplexity: 4, strategicValue: 9 },
    { name: "No-Show Reduction Program", revenuePotential: 890, implementationComplexity: 5, strategicValue: 9 },
    { name: "Australia / Kenya OCONUS Gap Fix", revenuePotential: 38, implementationComplexity: 7, strategicValue: 8 },
    { name: "NoVA Provider Density Buildout", revenuePotential: 36, implementationComplexity: 6, strategicValue: 10 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Third batch: the useful split",
      narrative:
        "This upload separates into four useful future lanes: FCX peer-performance enrichment, GDIT account/value modeling, network operations dashboards, and multi-client provider-density planning.",
      bullets: [
        "FCX should be framed as a strong peer-performance story but still watched for severe-event and contractor-risk signals already captured in the prior addendum.",
        "GDIT has a clean account pitch: major 2025 contract awards, large cleared IT workforce, turnover-driven pre-employment demand, and DBA/OCONUS add-ons.",
        "Network operations charts add concrete active-clinic, no-show, and personal-physician gap signals.",
      ],
      metricIds: ["third-fcx-avoided", "third-gdit-awards", "third-gdit-preemployment", "third-trace-noshow"],
    },
    {
      type: "locations",
      title: "Provider network density and gap actions",
      narrative:
        "The provider-network charts identify both urgent OCONUS gaps and dense multi-client corridors. These should later move into Network & Location Intelligence rather than remain as a chart-pack profile.",
      bullets: [
        "Stuttgart is the highest-density multi-client node with 16 clients.",
        "Northern Virginia has a strong corridor signal with Herndon, Arlington, Chantilly, Reston, Falls Church, Fort Belvoir, and Fairfax.",
        "Australia and Kenya are top personal-physician-use OCONUS gaps, meaning network clinics were not used for those exam completions.",
      ],
      metricIds: ["third-active-labcorp", "third-australia-gap", "third-stuttgart-density", "third-nova-top3"],
    },
    {
      type: "medical-opportunities",
      title: "Data quality flags",
      narrative:
        "The hiring activity chart has obvious scrape or aggregation outliers for USA and UK and should not be used in client-facing materials until the underlying table is cleaned. The chart is preserved only because it is part of the upload set.",
      bullets: [
        "Replace screenshot-derived data with source spreadsheets when available.",
        "Split this batch later into FCX, GDIT, Network Operations, and Provider Density sections.",
        "Do not clean the dropdown structure until the upload cycle is finished.",
      ],
      metricIds: [],
    },
  ],
};
