import type { CompanyConfig } from "./types";

export const uploadedChartPackAddendumIntelligenceConfig: CompanyConfig = {
  companyId: "uploaded-chart-pack-addendum-intelligence",
  displayName: "Uploaded Chart Pack Addendum Intelligence",
  shortName: "Chart Addendum",
  sector:
    "DBA carrier concentration, carrier/entity volume mapping, high OCONUS audit-risk clients, ECC injury/DBA/revenue/ESOP pitch modeling, exam-type demand, clinic expansion timing, and Freeport-McMoRan safety/revenue/MSHA trend charts",
  headquarters: "Occu-Med chart-intake layer",
  employees: 0,
  employeesAsOf:
    "Uploaded chart addendum: 20 PNG dashboard exports covering DBA carriers, ECC opportunity modeling, exam types, network expansion timing, and Freeport-McMoRan safety/financial charts",
  summary:
    "Uploaded Chart Pack Addendum Intelligence preserves the second chart-only upload into the same PR #26 intake branch. This addendum captures four distinct data clusters: DBA carrier concentration, ECC opportunity modeling, exam-type/network expansion demand, and Freeport-McMoRan safety/financial trends. The carrier charts show AIG dominating the Occu-Med entity volume at roughly 72.8%, followed by CNA at 15.6%, self-insured at 8.82%, unknown at 2.4%, and ACE/Chubb at 0.465%. The ECC charts model 2,500 workers, TRIR 2.83, roughly 70 injuries/year, $16.7M burden, 22 OCONUS injuries, and $6.7M DBA exposure, with a core Occu-Med revenue lane of roughly $1.06M-$1.58M and full revenue potential of $1.44M-$2.13M/year. The Freeport-McMoRan charts show revenue rising to $25.5B in 2024, recordable events down 19% over five years, total TRIR at 0.69 in 2024, five fatalities in 2024, Sierrita as the 2025 MSHA penalty hotspot, and CEO AIP safety weighting at 15%. This addendum should later be split into Carrier / Claims Intelligence, ECC entity profile work, Exam Demand Intelligence, and Freeport-McMoRan entity enrichment.",
  tags: [
    "Entity profile",
    "Chart pack addendum",
    "DBA carrier",
    "AIG",
    "CNA",
    "ACE/Chubb",
    "ECC",
    "ESOP pitch",
    "Freeport-McMoRan",
    "FCX",
    "MSHA",
    "Fatalities",
    "TRIR",
    "Exam types",
    "Network expansion",
  ],
  aliases: ["Chart Addendum", "Carrier ECC FCX Chart Pack", "DBA Carrier Addendum", "FCX Chart Addendum"],
  sourceFilters: {
    newsSources: {
      aliases: ["Occu-Med DBA carrier share", "ECC DBA exposure", "Freeport-McMoRan safety trend", "Freeport-McMoRan MSHA penalties"],
    },
  },
  executiveSignals: [
    { label: "Carrier concentration", value: "AIG 72.8%", note: "Uploaded DBA carrier-share chart shows AIG dominating Occu-Med entity volume." },
    { label: "Highest audit risk", value: "Applus+ 98%", note: "Uploaded high-risk DBA audit chart shows Applus+, Weatherford, World Vision, International SOS, Kapsuun, and QinetiQ with very high OCONUS mix." },
    { label: "ECC opportunity", value: "$1.44M-$2.13M", note: "Uploaded ECC revenue chart gives full Occu-Med revenue potential range per year." },
    { label: "FCX 2024 fatalities", value: "5", note: "Uploaded Freeport-McMoRan chart shows five workforce fatalities in 2024, worst since 2015." },
  ],
  curveTitle: "Carrier, ECC, exam demand, network expansion, and FCX addendum curve",
  curveSubtitle:
    "Second uploaded chart batch captured as source-specific intelligence. Some charts are duplicates/revisions; repeated FCX fatality/MSHA charts are consolidated into single normalized chart definitions.",
  chartDefinitions: [
    {
      id: "addendum-dba-carrier-share",
      title: "DBA carrier share by referral volume",
      subtitle: "Uploaded chart: AIG dominates with roughly 72.8% of all Occu-Med entity volume.",
      type: "bar",
      xKey: "carrier",
      data: [
        { carrier: "AIG", share: 72.8 },
        { carrier: "CNA", share: 15.6 },
        { carrier: "Self-Insured", share: 8.82 },
        { carrier: "Unknown", share: 2.4 },
        { carrier: "ACE/Chubb", share: 0.465 },
      ],
      series: [{ dataKey: "share", name: "Referral volume share", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 100],
      headline: "carrier share",
      fullWidth: true,
    },
    {
      id: "addendum-dba-audit-risk-clients",
      title: "Highest DBA audit-risk clients",
      subtitle: "Uploaded chart: companies with >75% OCONUS footprint.",
      type: "bar",
      xKey: "client",
      data: [
        { client: "Weatherford", oconusShare: 93 },
        { client: "Applus+", oconusShare: 98 },
        { client: "World Vision", oconusShare: 91 },
        { client: "Amentum", oconusShare: 77 },
        { client: "Versar Global", oconusShare: 77 },
        { client: "QinetiQ", oconusShare: 89 },
        { client: "Group SSI", oconusShare: 79 },
        { client: "Kapsuun", oconusShare: 90 },
        { client: "International SOS", oconusShare: 92 },
        { client: "Fluor", oconusShare: 78 },
      ],
      series: [{ dataKey: "oconusShare", name: "OCONUS %", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 100],
      headline: "audit risk",
      fullWidth: true,
    },
    {
      id: "addendum-entities-by-carrier",
      title: "Top entities by volume and DBA carrier",
      subtitle: "Uploaded chart: carrier/color map translated into grouped bars by primary carrier.",
      type: "bar",
      xKey: "entity",
      data: [
        { entity: "V2X / Vectrus", annualRefs: 5427, carrier: "AIG" },
        { entity: "Amentum (PAE/DynCorp)", annualRefs: 852, carrier: "AIG" },
        { entity: "Lockheed Martin", annualRefs: 676, carrier: "Self-Insured" },
        { entity: "Akima", annualRefs: 525, carrier: "AIG" },
        { entity: "Booz Allen Hamilton", annualRefs: 425, carrier: "ACE/Chubb" },
        { entity: "Valiant Integrated Services", annualRefs: 423, carrier: "AIG" },
        { entity: "IAP Worldwide", annualRefs: 409, carrier: "AIG" },
        { entity: "Cherokee Nation Businesses", annualRefs: 350, carrier: "AIG" },
        { entity: "AECOM", annualRefs: 350, carrier: "ACE/Chubb" },
        { entity: "Leidos", annualRefs: 307, carrier: "Self-Insured" },
        { entity: "HII", annualRefs: 260, carrier: "Self-Insured" },
        { entity: "Bechtel", annualRefs: 250, carrier: "ACE/Chubb" },
        { entity: "ManTech", annualRefs: 198, carrier: "AIG" },
        { entity: "Textron / Bell", annualRefs: 175, carrier: "ACE/Chubb" },
        { entity: "SOSi", annualRefs: 167, carrier: "AIG" },
      ],
      series: [{ dataKey: "annualRefs", name: "Annual refs", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "carrier map",
      fullWidth: true,
    },
    {
      id: "addendum-ecc-dba-deployment",
      title: "ECC OCONUS DBA exposure by deployment type",
      subtitle: "Uploaded chart: 600 OCONUS workers, 22.3 expected injuries/year, $6.7M total DBA claim exposure.",
      type: "bar",
      xKey: "deploymentType",
      data: [
        { deploymentType: "UXO/EOD", dbaExposure: 2.70, expectedInjuries: 9.0 },
        { deploymentType: "Fuels Infrastructure", dbaExposure: 1.80, expectedInjuries: 6.0 },
        { deploymentType: "Design-Build", dbaExposure: 1.35, expectedInjuries: 4.5 },
        { deploymentType: "Environmental Remediation", dbaExposure: 0.75, expectedInjuries: 2.5 },
        { deploymentType: "PM / Engineering", dbaExposure: 0.09, expectedInjuries: 0.3 },
      ],
      series: [{ dataKey: "dbaExposure", name: "Annual DBA exposure", color: "#ef4444", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "ECC DBA",
      fullWidth: true,
    },
    {
      id: "addendum-ecc-injuries-division",
      title: "ECC expected injuries per year by division",
      subtitle: "Uploaded chart: 2,500 workers, TRIR 2.83, 70 injuries/year, $16.7M burden, 22 OCONUS injuries = $6.7M DBA exposure.",
      type: "bar",
      xKey: "division",
      data: [
        { division: "UXO/EOD", injuries: 9.0 },
        { division: "Fuels Infrastructure", injuries: 18.0 },
        { division: "Environmental Remediation", injuries: 12.5 },
        { division: "Design-Build Construction", injuries: 21.0 },
        { division: "Disaster Debris", injuries: 8.8 },
        { division: "PM/Engineering & Office", injuries: 1.5 },
      ],
      series: [{ dataKey: "injuries", name: "Expected injuries/year", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "ECC injuries",
      fullWidth: true,
    },
    {
      id: "addendum-ecc-occumed-revenue",
      title: "ECC Occu-Med revenue potential",
      subtitle: "Uploaded chart: core $1.06M-$1.58M; full $1.44M-$2.13M/year.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Pre-Employment HAZWOPER / Construction", revenue: 312 },
        { examType: "Annual HAZWOPER Surveillance", revenue: 750 },
        { examType: "Fuels/Benzene Chemical Surveillance", revenue: 340 },
        { examType: "DBA Pre-Deploy", revenue: 255 },
        { examType: "UXO Fitness Certification", revenue: 125 },
      ],
      series: [{ dataKey: "revenue", name: "Annual revenue", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "ECC revenue",
      fullWidth: true,
    },
    {
      id: "addendum-ecc-esop-savings",
      title: "ECC ESOP pitch: injury burden vs Occu-Med investment",
      subtitle: "Uploaded chart: employee-owners bear injury costs directly; five-year program modeled at $18.7M saved / $6,700 per ESOP share.",
      type: "grouped",
      xKey: "year",
      data: [
        { year: "Year 1", withoutProgram: 16.7, withProgram: 16.7, cumulativeEsopSavings: 0 },
        { year: "Year 2", withoutProgram: 16.7, withProgram: 13.4, cumulativeEsopSavings: 1300 },
        { year: "Year 3", withoutProgram: 16.7, withProgram: 10.9, cumulativeEsopSavings: 3500 },
        { year: "Year 4", withoutProgram: 16.7, withProgram: 9.2, cumulativeEsopSavings: 6700 },
        { year: "Year 5", withoutProgram: 16.7, withProgram: 8.4, cumulativeEsopSavings: 10000 },
      ],
      series: [
        { dataKey: "withoutProgram", name: "Without Occu-Med Program", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "withProgram", name: "With Occu-Med Program", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "ESOP pitch",
      fullWidth: true,
    },
    {
      id: "addendum-exam-types-completed",
      title: "Exam types — top 12 completed",
      subtitle: "Uploaded chart: drug screens exceed 2,000; medical panels dominate completed volume.",
      type: "bar",
      xKey: "examType",
      data: [
        { examType: "Drug Screen (Pre-Deploy)", completed: 1240 },
        { examType: "M (34 and younger)", completed: 1222 },
        { examType: "M (49 and older)", completed: 857 },
        { examType: "Drug Screen (Random)", completed: 767 },
        { examType: "M (39-48)", completed: 748 },
        { examType: "OVS M (39-48)", completed: 714 },
        { examType: "Saudi Visa", completed: 689 },
        { examType: "M (40-49)", completed: 675 },
        { examType: "M (50 and older)", completed: 604 },
        { examType: "Kuwait Annual", completed: 568 },
        { examType: "OVS M (49 and older)", completed: 463 },
        { examType: "Male (39 and older)", completed: 400 },
      ],
      series: [{ dataKey: "completed", name: "Completed exams", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "exam demand",
      fullWidth: true,
    },
    {
      id: "addendum-clinic-expansion-timeline",
      title: "Clinic network expansion timeline",
      subtitle: "Uploaded chart: Phase 1 Q2 → Phase 2 Q3 → Phase 3 Q4 → Phase 4 2027. Dates are directional from image labels.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "Dubai Clinic", phase: 1, monthIndex: 4 },
        { site: "Doha Clinic", phase: 1, monthIndex: 5 },
        { site: "Greenville SC", phase: 2, monthIndex: 6 },
        { site: "Fort Worth TX", phase: 2, monthIndex: 6 },
        { site: "CA Central Valley Hub", phase: 2, monthIndex: 7 },
        { site: "Bahrain Clinic", phase: 2, monthIndex: 7 },
        { site: "Stuttgart DE", phase: 3, monthIndex: 10 },
        { site: "Manila PH", phase: 3, monthIndex: 11 },
        { site: "NoVA Cluster", phase: 4, monthIndex: 13 },
        { site: "Saudi Arabia", phase: 4, monthIndex: 14 },
      ],
      series: [{ dataKey: "phase", name: "Phase", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 4],
      headline: "expansion plan",
    },
    {
      id: "addendum-fcx-revenue",
      title: "FCX revenue trend",
      subtitle: "Uploaded chart: revenue reached $25.5B in 2024, +12% year over year.",
      type: "area",
      xKey: "year",
      data: [
        { year: "2020", revenue: 14.2 },
        { year: "2021", revenue: 22.8 },
        { year: "2022", revenue: 22.8 },
        { year: "2023", revenue: 22.9 },
        { year: "2024", revenue: 25.5 },
      ],
      series: [{ dataKey: "revenue", name: "Revenue", color: "#22d3ee" }],
      formatter: "currencyM",
      headline: "FCX revenue",
    },
    {
      id: "addendum-fcx-trir-trend",
      title: "FCX TRIR trend 2020-2024",
      subtitle: "Uploaded charts: employee TRIR improved from 2021 peak; contractor TRIR remains higher than 2020.",
      type: "line",
      xKey: "year",
      data: [
        { year: "2020", employees: 0.78, contractors: 0.36, total: 0.52, nearMiss: 1.25 },
        { year: "2021", employees: 1.03, contractors: 0.35, total: 0.60, nearMiss: 0.92 },
        { year: "2022", employees: 0.93, contractors: 0.60, total: 0.77, nearMiss: 1.17 },
        { year: "2023", employees: 0.75, contractors: 0.62, total: 0.70, nearMiss: 1.78 },
        { year: "2024", employees: 0.77, contractors: 0.57, total: 0.69, nearMiss: 1.61 },
      ],
      series: [
        { dataKey: "employees", name: "Employees", color: "#22d3ee" },
        { dataKey: "contractors", name: "Contractors", color: "#ef4444" },
        { dataKey: "total", name: "Total", color: "#22c55e" },
      ],
      domain: [0, 1.1],
      headline: "FCX TRIR",
      fullWidth: true,
    },
    {
      id: "addendum-fcx-benchmark",
      title: "FCX TRIR vs mining industry benchmarks",
      subtitle: "Uploaded chart: FCX remains below BLS copper, BLS metal, and ICMM average benchmarks.",
      type: "bar",
      xKey: "benchmark",
      data: [
        { benchmark: "FCX Total", trir: 0.69 },
        { benchmark: "FCX Employees", trir: 0.77 },
        { benchmark: "BLS Copper", trir: 1.80 },
        { benchmark: "BLS Metal", trir: 2.10 },
        { benchmark: "ICMM Avg", trir: 2.40 },
      ],
      series: [{ dataKey: "trir", name: "TRIR", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 2.5],
      headline: "FCX benchmark",
    },
    {
      id: "addendum-fcx-fatalities",
      title: "FCX fatalities 2020-2024",
      subtitle: "Uploaded charts: five fatalities in 2024; four contractors and one employee; worst since 2015.",
      type: "bar",
      xKey: "year",
      data: [
        { year: "2020", fatalities: 2 },
        { year: "2021", fatalities: 1 },
        { year: "2022", fatalities: 1 },
        { year: "2023", fatalities: 2 },
        { year: "2024", fatalities: 5 },
      ],
      series: [{ dataKey: "fatalities", name: "Workforce fatalities", color: "#ef4444", radius: [10, 10, 0, 0] }],
      headline: "FCX fatalities",
    },
    {
      id: "addendum-fcx-recordables",
      title: "FCX recordable events: down 19% over five years",
      subtitle: "Uploaded chart: incidents declined from 516 in 2020 to 419 in 2024 after 2021-2022 peak.",
      type: "bar",
      xKey: "year",
      data: [
        { year: "2020", incidents: 516 },
        { year: "2021", incidents: 605 },
        { year: "2022", incidents: 590 },
        { year: "2023", incidents: 457 },
        { year: "2024", incidents: 419 },
      ],
      series: [{ dataKey: "incidents", name: "Incidents", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "recordables",
    },
    {
      id: "addendum-fcx-msha-penalties",
      title: "FCX 2025 MSHA penalties by Arizona mine site",
      subtitle: "Uploaded chart: Sierrita is the hotspot with $61.2K and two S&S violations.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "Morenci", penalties: 53.6, citations: 9, substantial: 0 },
        { site: "Bagdad", penalties: 7.7, citations: 1, substantial: 0 },
        { site: "Safford", penalties: 14.6, citations: 1, substantial: 0 },
        { site: "Sierrita", penalties: 61.2, citations: 4, substantial: 2 },
      ],
      series: [{ dataKey: "penalties", name: "2025 MSHA penalties", color: "#ef4444", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "MSHA hotspot",
      fullWidth: true,
    },
    {
      id: "addendum-fcx-aip-safety-weight",
      title: "FCX CEO bonus weighting: safety is 15% of AIP",
      subtitle: "Uploaded chart: operational 45%, financial 30%, safety 15%, sustainability 10%. Safety tied to TRIR.",
      type: "bar",
      xKey: "category",
      data: [
        { category: "Operational", weight: 45 },
        { category: "Financial", weight: 30 },
        { category: "Safety", weight: 15 },
        { category: "Sustainability", weight: 10 },
      ],
      series: [{ dataKey: "weight", name: "AIP weight", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 50],
      headline: "AIP safety",
    },
  ],
  metricDefinitions: [
    { id: "chartadd-aig-share", label: "AIG carrier share", value: 72.8, unit: "percent", category: "risk" },
    { id: "chartadd-high-risk-applus", label: "Applus+ OCONUS share", value: 98, unit: "percent", category: "risk" },
    { id: "chartadd-ecc-workers", label: "ECC workers modeled", value: 2500, unit: "count", category: "workforce" },
    { id: "chartadd-ecc-injuries", label: "ECC expected injuries/year", value: 70, unit: "count", category: "safety" },
    { id: "chartadd-ecc-dba", label: "ECC total DBA exposure", value: 6.7, unit: "usd", category: "risk" },
    { id: "chartadd-ecc-revenue-high", label: "ECC full revenue high", value: 2.13, unit: "usd", category: "financial" },
    { id: "chartadd-fcx-revenue", label: "FCX 2024 revenue", value: 25.5, unit: "usd", category: "financial" },
    { id: "chartadd-fcx-fatalities", label: "FCX 2024 fatalities", value: 5, unit: "count", category: "safety" },
    { id: "chartadd-fcx-trir", label: "FCX 2024 total TRIR", value: 0.69, unit: "score", category: "safety" },
    { id: "chartadd-sierrita-penalties", label: "Sierrita MSHA penalties", value: 61.2, unit: "usd", category: "risk" },
  ],
  riskMatrix: [
    { name: "AIG carrier concentration", revenue: 72.8, risk: 9.5, workers: 5427 },
    { name: "Applus+ OCONUS audit risk", revenue: 98, risk: 10.0, workers: 100 },
    { name: "ECC DBA exposure", revenue: 6.7, risk: 9.0, workers: 600 },
    { name: "FCX 2024 fatalities", revenue: 5, risk: 10.0, workers: 5 },
    { name: "Sierrita MSHA hotspot", revenue: 61.2, risk: 9.0, workers: 4 },
  ],
  opportunityMatrix: [
    { name: "AIG DBA Carrier Partnership", revenuePotential: 72.8, implementationComplexity: 7, strategicValue: 10 },
    { name: "ECC HAZWOPER / DBA Program", revenuePotential: 2130, implementationComplexity: 6, strategicValue: 10 },
    { name: "FCX Contractor Safety Program", revenuePotential: 500, implementationComplexity: 7, strategicValue: 9 },
    { name: "Sierrita MSHA Surveillance Focus", revenuePotential: 120, implementationComplexity: 5, strategicValue: 8 },
    { name: "Exam Demand Productization", revenuePotential: 1240, implementationComplexity: 4, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Second chart batch captured without reorganizing the app yet",
      narrative:
        "This addendum should not be treated as a final UX category. It exists to capture the data now while the upload pile is still moving. Later it should be split into the correct themed sections.",
      bullets: [
        "AIG dominates the DBA carrier-share chart at 72.8% of referral volume.",
        "ECC has a credible ESOP/DBA/HAZWOPER sales story with $1.44M-$2.13M full annual revenue potential.",
        "Freeport-McMoRan has a mixed story: recordables down and TRIR below benchmarks, but fatalities rose to five in 2024 and Sierrita is the MSHA hotspot.",
      ],
      metricIds: ["chartadd-aig-share", "chartadd-ecc-dba", "chartadd-fcx-fatalities", "chartadd-sierrita-penalties"],
    },
    {
      type: "medical-opportunities",
      title: "How to use the addendum later",
      narrative:
        "Carrier charts should feed Carrier / Claims Intelligence; ECC charts should become an ECC entity or prospect profile; FCX charts should enrich the Freeport-McMoRan profile; exam-type and expansion charts should feed Network & Demand Intelligence.",
      bullets: [
        "Do not manually clean the dropdown yet; finish the data intake first.",
        "Treat duplicate FCX fatality and MSHA charts as consolidated signals, not separate profile entries.",
        "Replace screenshot-derived values with the source spreadsheets when they become available.",
      ],
      metricIds: ["chartadd-ecc-revenue-high", "chartadd-fcx-revenue", "chartadd-fcx-trir"],
    },
  ],
};
