import type { CompanyConfig } from "./types";

export const v2xGlobalFootprintIntelligenceConfig: CompanyConfig = {
  companyId: "v2x-global-footprint-intelligence",
  displayName: "V2X Global Footprint Intelligence",
  shortName: "V2X Footprint",
  sector:
    "V2X global locations, Vectrus/Vertex integration, aerospace MRO, base operations support, training ranges, engineering offices, LOGCAP, Smart Warehouse, and provider-network planning",
  headquarters: "McLean / Reston, Virginia",
  employees: 16000,
  employeesAsOf:
    "Uploaded Gemini V2X presence research: approximately 16,000 employees, nearly 330 locations, and 47-51 countries/territories after the Vectrus-Vertex merger",
  summary:
    "V2X Global Footprint Intelligence turns the uploaded 79-page V2X location research into a network and provider-planning layer. The file frames V2X as the 2022 combination of Vectrus and Vertex Aerospace, with a mission footprint spanning nearly 330 locations across roughly 47-51 countries and territories. The operational mix matters for Occu-Med: V2X is not only LOGCAP base operations; it also includes aerospace MRO, FAA Part 145 repair stations, engineering and technical design offices, training innovation, supply-chain logistics, Smart Warehouse initiatives, AETC base operations, Guantanamo Bay base support, and Vertex engineering/professional services sites across the United States. This profile should sit beside the existing V2X safety profile and the Referral Demand / Multi-Client Location profiles: the safety profile explains why V2X needs action; this profile explains where the provider network must be ready.",
  tags: [
    "Entity profile",
    "V2X",
    "Vectrus",
    "Vertex Aerospace",
    "Global footprint",
    "330 locations",
    "Aerospace MRO",
    "FAA Part 145",
    "Base operations",
    "AETC",
    "Smart Warehouse",
    "Training innovation",
    "Guantanamo Bay",
    "Indianapolis",
    "Madison Mississippi",
    "Orlando",
  ],
  aliases: ["V2X Global Footprint", "Vectrus Vertex Global Footprint", "V2X Client Presence", "V2X Site Research"],
  sourceFilters: {
    sec: { ticker: "VVX", legalEntities: ["V2X, Inc."], formerNames: ["Vectrus, Inc."] },
    sam: { legalNames: ["V2X, Inc.", "Vectrus", "Vertex Aerospace"] },
    usaSpending: { recipientNames: ["V2X", "Vectrus", "Vertex Aerospace"] },
    newsSources: { aliases: ["V2X global footprint", "Vectrus Vertex merger", "V2X Smart Warehouse", "V2X MRO", "V2X base operations"] },
  },
  executiveSignals: [
    { label: "Global footprint", value: "~330 locations", note: "Uploaded research frames V2X as operating at nearly 330 locations after the Vectrus-Vertex merger." },
    { label: "Country spread", value: "47-51", note: "The uploaded research gives a 47-51 country/territory range for operational presence." },
    { label: "Workforce", value: "~16K", note: "The report cites approximately 16,000 employees, with a high veteran workforce share." },
    { label: "Provider logic", value: "Network-first", note: "V2X's distributed footprint requires pre-built clinic coverage, not one-off provider searches." },
  ],
  curveTitle: "V2X global footprint, MRO, base operations, and provider-network curve",
  curveSubtitle:
    "Uploaded Gemini V2X client-presence research normalized into a source-specific footprint profile. Site details should be validated before scheduling use.",
  chartDefinitions: [
    {
      id: "v2x-corporate-technical-nodes",
      title: "V2X corporate and technical command nodes",
      subtitle: "Primary U.S. branches and operations centers from the uploaded presence report.",
      type: "bar",
      xKey: "node",
      data: [
        { node: "Reston VA HQ", priority: 10 },
        { node: "McLean VA", priority: 9 },
        { node: "Glen Allen VA", priority: 8 },
        { node: "Colorado Springs", priority: 8 },
        { node: "Indianapolis", priority: 9 },
        { node: "Madison MS", priority: 9 },
        { node: "Orlando FL", priority: 8 },
        { node: "Fayetteville NC", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Operational priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "command nodes",
      fullWidth: true,
    },
    {
      id: "v2x-engineering-network",
      title: "V2X engineering / professional service network",
      subtitle: "Vertex engineering office network gives V2X a broader professional-services footprint than LOGCAP alone.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "Northeast", sites: 9 },
        { region: "Southeast", sites: 5 },
        { region: "Texas / Energy / Space", sites: 3 },
        { region: "Mountain / West", sites: 5 },
        { region: "Midwest", sites: 4 },
        { region: "Pacific Northwest", sites: 1 },
      ],
      series: [{ dataKey: "sites", name: "Engineering sites", color: "#22c55e", radius: [10, 10, 0, 0] }],
      headline: "engineering net",
    },
    {
      id: "v2x-mro-aerospace-sites",
      title: "V2X aerospace and MRO infrastructure",
      subtitle: "Uploaded report highlights FAA Part 145 and dedicated aerospace sustainment sites.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "Fort Worth Alliance", priority: 10 },
        { site: "Crestview FL", priority: 10 },
        { site: "Madison MS", priority: 9 },
        { site: "Indianapolis IN", priority: 8 },
        { site: "Fairchild Road", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "MRO priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "MRO sites",
    },
    {
      id: "v2x-base-ops-sites",
      title: "V2X base operations and training support sites",
      subtitle: "The uploaded report lists AETC and near-OCONUS support sites where physical work and medical clearance needs concentrate.",
      type: "bar",
      xKey: "installation",
      data: [
        { installation: "Maxwell AFB", priority: 8 },
        { installation: "Sheppard AFB", priority: 8 },
        { installation: "Keesler AFB", priority: 8 },
        { installation: "US Naval Academy", priority: 6 },
        { installation: "Guantanamo Bay", priority: 10 },
        { installation: "Marine Corps Logistics Cmd", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Medical/network priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "BOSS sites",
      fullWidth: true,
    },
    {
      id: "v2x-provider-network-use",
      title: "How this footprint should drive Occu-Med network work",
      subtitle: "Footprint intelligence becomes provider pre-build, hotspot validation, and client-coverage messaging.",
      type: "bar",
      xKey: "useCase",
      data: [
        { useCase: "Provider-radius check", priority: 10 },
        { useCase: "MRO clinic match", priority: 9 },
        { useCase: "Base ops exam setup", priority: 9 },
        { useCase: "Engineering-office ergonomics", priority: 5 },
        { useCase: "OCONUS staging coverage", priority: 10 },
        { useCase: "Smart Warehouse logistics", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Network value", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "network use",
    },
  ],
  metricDefinitions: [
    { id: "v2x-footprint-locations", label: "Global locations", value: 330, unit: "count", category: "workforce" },
    { id: "v2x-footprint-countries-low", label: "Country/territory low", value: 47, unit: "count", category: "workforce" },
    { id: "v2x-footprint-countries-high", label: "Country/territory high", value: 51, unit: "count", category: "workforce" },
    { id: "v2x-footprint-workforce", label: "Employees", value: 16000, unit: "count", category: "workforce" },
    { id: "v2x-footprint-provider-fit", label: "Provider-network fit", value: 10, unit: "score", category: "financial" },
  ],
  riskMatrix: [
    { name: "OCONUS base operations", revenue: 10, risk: 9.5, workers: 4000 },
    { name: "Aerospace MRO", revenue: 9, risk: 8.5, workers: 2500 },
    { name: "Engineering network", revenue: 5, risk: 4.0, workers: 3000 },
    { name: "Smart Warehouse logistics", revenue: 8, risk: 7.5, workers: 1500 },
    { name: "Training innovation", revenue: 6, risk: 5.5, workers: 1000 },
  ],
  opportunityMatrix: [
    { name: "MRO Provider Network", revenuePotential: 450, implementationComplexity: 6, strategicValue: 9 },
    { name: "BOSS / AETC Exam Coverage", revenuePotential: 600, implementationComplexity: 7, strategicValue: 10 },
    { name: "Guantanamo Bay Coverage", revenuePotential: 250, implementationComplexity: 8, strategicValue: 9 },
    { name: "Smart Warehouse Logistics Exams", revenuePotential: 200, implementationComplexity: 5, strategicValue: 8 },
    { name: "Engineering Site Ergonomics", revenuePotential: 100, implementationComplexity: 4, strategicValue: 6 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Why this is separate from the V2X safety profile",
      narrative:
        "The existing V2X profile already captures safety metrics. This profile captures where V2X operates and what kind of provider network the footprint demands.",
      bullets: [
        "V2X was formed through the Vectrus / Vertex Aerospace merger in 2022.",
        "The uploaded research cites nearly 330 locations across roughly 47-51 countries and territories.",
        "Aerospace MRO, base operations, engineering services, and training innovation require different clinic/provider matches.",
      ],
      metricIds: ["v2x-footprint-locations", "v2x-footprint-countries-low", "v2x-footprint-workforce"],
    },
    {
      type: "locations",
      title: "Network-map action layer",
      narrative:
        "Every location line should eventually become a structured network record: country, city/base, facility type, likely exam menu, current provider coverage, backup provider status, and source confidence.",
      bullets: [
        "MRO locations need clinics capable of occupational exams, hearing, respiratory, DOT/CDL where relevant, and return-to-work documentation.",
        "Base operations sites need provider redundancy, especially at OCONUS or remote installations.",
        "Engineering offices create less physical risk but still matter for ergonomic and visual-strain programs.",
      ],
      metricIds: ["v2x-footprint-provider-fit"],
    },
  ],
};
