import type { CompanyConfig } from "./types";

export const v2xDbaCarrierAccessConfig: CompanyConfig = {
  companyId: "v2x-dba-carrier-access",
  displayName: "V2X DBA Carrier Access Intelligence",
  shortName: "V2X DBA Access",
  sector:
    "V2X Defense Base Act carrier stack, workers' compensation provider-network access, insurer nomination strategy, claims routing, QBE/Allianz/Applied/Falls Lake/Coventry/Texas carrier reconnaissance, and Chase outreach planning",
  headquarters: "Occu-Med carrier-network strategy entity",
  employees: 0,
  employeesAsOf:
    "Uploaded V2X DBA carrier brief: carrier-access intelligence entity, not an employer workforce profile",
  summary:
    "V2X DBA Carrier Access Intelligence converts the uploaded V2X insurer reconnaissance into a provider-network action profile for Chase. The report identifies a layered V2X DBA carrier stack: Allianz Global Corporate & Specialty / Allianz Commercial, Texas Insurance Company, Applied Risk Services / Applied Underwriters, Falls Lake National Insurance Company, and QBE Insurance Corporation / QBE North America. The strategic point is that Occu-Med should not only be positioned with V2X directly. Occu-Med needs access to the medical provider networks that route DBA and workers' compensation cases through the carriers and TPAs behind V2X. The uploaded report identifies immediate provider-access plays: Allianz Commercial provider nomination plus Matt Sayre outreach, Applied Risk / Promesa Health / National Broker Services, Falls Lake through Coventry Workers' Comp Services, QBE provider nomination plus Ted Turner and Lori Donohue, and a Texas Insurance Company confirmation step through V2X Risk/HR because the exact TPA/fronting carrier relationship needs verification.",
  tags: [
    "Entity profile",
    "V2X",
    "DBA insurance",
    "Carrier access",
    "Allianz Commercial",
    "Applied Risk Services",
    "Promesa Health",
    "Falls Lake",
    "Coventry WCS",
    "QBE North America",
    "Texas Insurance Company",
    "Provider nomination",
    "Chase outreach",
    "Network effect",
  ],
  aliases: [
    "V2X DBA Carrier Stack",
    "V2X DBA Insurance",
    "V2X carrier access",
    "V2X provider nomination",
    "V2X insurer network",
  ],
  sourceFilters: {
    newsSources: {
      aliases: [
        "V2X DBA carrier",
        "Allianz Commercial provider nomination",
        "Applied Risk Services Promesa Health",
        "Falls Lake Coventry WCS",
        "QBE workers compensation provider nomination",
      ],
    },
  },
  executiveSignals: [
    { label: "Confirmed stack", value: "5 carriers", note: "Uploaded V2X brief lists Allianz, Texas Insurance Company, Applied Risk Services, Falls Lake, and QBE." },
    { label: "Do today", value: "4 channels", note: "Allianz, Applied/Promesa, Falls Lake/Coventry, and QBE are all marked immediate action lanes." },
    { label: "Unclear lane", value: "Texas Insurance", note: "Report says to confirm the TPA/claims administrator directly with V2X because the name is generic." },
    { label: "Bigger play", value: "Carrier network effect", note: "Provider access can protect V2X renewals and unlock other defense contractors using the same carrier networks." },
  ],
  curveTitle: "V2X DBA carrier access and provider-network nomination curve",
  curveSubtitle:
    "Uploaded V2X carrier brief normalized into an action profile. Person/contact references are source-report intelligence and should be verified before external outreach.",
  chartDefinitions: [
    {
      id: "v2x-carrier-action-priority",
      title: "V2X carrier access priority",
      subtitle: "Four channels are immediate action lanes; Texas Insurance Company requires verification of TPA/claims routing.",
      type: "bar",
      xKey: "carrier",
      data: [
        { carrier: "Allianz Commercial", priority: 10 },
        { carrier: "Applied / Promesa", priority: 10 },
        { carrier: "Falls Lake / Coventry", priority: 10 },
        { carrier: "QBE North America", priority: 10 },
        { carrier: "Texas Insurance Co.", priority: 6 },
      ],
      series: [{ dataKey: "priority", name: "Action priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "carrier stack",
      fullWidth: true,
    },
    {
      id: "v2x-entry-points",
      title: "Provider-network entry point by carrier",
      subtitle: "The uploaded brief separates direct provider nomination, TPA/network access, and V2X confirmation lanes.",
      type: "bar",
      xKey: "entryPoint",
      data: [
        { entryPoint: "Allianz nomination", effort: 4, payoff: 10 },
        { entryPoint: "Promesa credentialing", effort: 5, payoff: 10 },
        { entryPoint: "Coventry WCS", effort: 5, payoff: 9 },
        { entryPoint: "QBE PPO nomination", effort: 4, payoff: 10 },
        { entryPoint: "V2X Texas confirmation", effort: 3, payoff: 6 },
      ],
      series: [
        { dataKey: "payoff", name: "Strategic payoff", color: "#22c55e", radius: [8, 8, 0, 0] },
        { dataKey: "effort", name: "Implementation effort", color: "#a78bfa", radius: [8, 8, 0, 0] },
      ],
      headline: "entry points",
    },
    {
      id: "v2x-key-people-map",
      title: "Named contact / team map for Chase",
      subtitle: "Source-report contact intelligence; verify before outreach.",
      type: "bar",
      xKey: "contact",
      data: [
        { contact: "Matt Sayre / Allianz", priority: 10 },
        { contact: "Promesa / Broker Services", priority: 10 },
        { contact: "Coventry WCS team", priority: 10 },
        { contact: "Ted Turner / QBE", priority: 9 },
        { contact: "Lori Donohue / QBE", priority: 8 },
        { contact: "V2X Risk Manager", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Follow-up priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "people map",
      fullWidth: true,
    },
    {
      id: "v2x-network-effect",
      title: "Why carrier access matters beyond V2X",
      subtitle: "Carrier-network access protects renewals and unlocks other defense-contractor books using the same networks.",
      type: "bar",
      xKey: "benefit",
      data: [
        { benefit: "Protect V2X if carrier changes", priority: 10 },
        { benefit: "Unlock Allianz book", priority: 9 },
        { benefit: "Unlock QBE book", priority: 9 },
        { benefit: "Unlock Coventry users", priority: 8 },
        { benefit: "Applied/Promesa referrals", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Network effect", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "bigger play",
    },
  ],
  metricDefinitions: [
    { id: "v2x-carrier-count", label: "V2X carrier stack count", value: 5, unit: "count", category: "risk" },
    { id: "v2x-immediate-actions", label: "Immediate action lanes", value: 4, unit: "count", category: "financial" },
    { id: "v2x-credentialing-priority", label: "Credentialing priority", value: 10, unit: "score", category: "financial" },
    { id: "v2x-texas-uncertainty", label: "Texas confirmation gap", value: 1, unit: "count", category: "risk" },
  ],
  riskMatrix: [
    { name: "Allianz Commercial", revenue: 10, risk: 6.0, workers: 1200 },
    { name: "Applied / Promesa", revenue: 10, risk: 6.0, workers: 1200 },
    { name: "Falls Lake / Coventry", revenue: 9, risk: 6.5, workers: 1000 },
    { name: "QBE North America", revenue: 10, risk: 6.0, workers: 1200 },
    { name: "Texas Insurance confirmation", revenue: 6, risk: 8.0, workers: 500 },
  ],
  opportunityMatrix: [
    { name: "Allianz Provider Nomination", revenuePotential: 1200, implementationComplexity: 4, strategicValue: 10 },
    { name: "Promesa Health Credentialing", revenuePotential: 1200, implementationComplexity: 5, strategicValue: 10 },
    { name: "Coventry WCS Credentialing", revenuePotential: 1000, implementationComplexity: 5, strategicValue: 9 },
    { name: "QBE Provider Nomination", revenuePotential: 1200, implementationComplexity: 4, strategicValue: 10 },
    { name: "V2X Texas Carrier Verification", revenuePotential: 500, implementationComplexity: 3, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Why this is a major network-access finding",
      narrative:
        "The uploaded brief reframes V2X access from a single-client relationship into a carrier-network strategy. Occu-Med can protect V2X continuity and potentially gain access to other defense-contractor claim flows by entering the carrier and TPA provider networks behind V2X.",
      bullets: [
        "V2X is not tied to one DBA insurer; the source brief lists five carrier entities/layers.",
        "Provider-network access needs to cover every layer, not just the primary client relationship.",
        "Carrier access protects Occu-Med if V2X changes carriers at renewal.",
        "The same carrier networks can route other defense-contractor referrals.",
      ],
      metricIds: ["v2x-carrier-count", "v2x-immediate-actions"],
    },
    {
      type: "procurement",
      title: "Carrier-by-carrier access plan",
      narrative:
        "The action plan is practical: submit provider nominations where available, call or credential with the delegated network where the carrier outsources provider access, and use V2X to clarify the ambiguous Texas Insurance Company lane.",
      bullets: [
        "Allianz Commercial: submit provider nomination and follow up with the workers' comp claims leadership lane.",
        "Applied Risk Services: call for Promesa Health network credentialing or National Broker Services.",
        "Falls Lake: credential with Coventry Workers' Comp Services while also introducing Occu-Med to Falls Lake.",
        "QBE: use the PPO nomination route and follow up through claims/underwriting contacts.",
        "Texas Insurance Company: confirm the actual TPA or claims administrator with V2X first.",
      ],
      metricIds: ["v2x-credentialing-priority", "v2x-texas-uncertainty"],
    },
    {
      type: "medical-opportunities",
      title: "Chase outreach angle",
      narrative:
        "The pitch should not sound like a random provider trying to join a network. It should lead with Occu-Med's existing V2X relationship, DBA/OCONUS coordination capability, and ability to coordinate occupational medicine across domestic staging cities and international referral locations.",
      bullets: [
        "Lead with existing V2X exam volume and defense-contractor experience.",
        "Explain international coordination and OCONUS provider coverage as the differentiator.",
        "Ask for provider-network entry, provider nomination, or vendor credentialing depending on the carrier lane.",
      ],
      metricIds: [],
    },
  ],
};
