import type { CompanyConfig } from "./types";

export const v2xConfig: CompanyConfig = {
  companyId: "v2x",
  displayName: "V2X, Inc.",
  shortName: "V2X",
  sector:
    "Defense services, logistics, training, mission support, aerospace MRO, base operations, engineering offices, LOGCAP, Smart Warehouse, AETC support, and global provider-network planning",
  headquarters: "McLean / Reston, Virginia",
  employees: 16100,
  employeesAsOf:
    "Uploaded V2X EHS screenshots and Gemini client-presence research: roughly 16,000 workers, nearly 330 locations, and 47-51 countries/territories after the Vectrus-Vertex merger",
  summary:
    "V2X is now modeled from two source layers: verified safety metrics from uploaded EHS screenshots and a 79-page global client-presence research file. The EHS screenshots confirm CY2024 deterioration: TRIR rose from 0.47 to 0.62, DART rose from 0.34 to 0.45, and near-miss rate rose from 0.63 to 0.93. The footprint file explains why that matters operationally: V2X is not only LOGCAP base operations; it includes aerospace MRO, FAA Part 145 repair stations, engineering and technical design offices, training innovation, supply-chain logistics, Smart Warehouse initiatives, AETC base operations, Guantanamo Bay base support, and Vertex engineering/professional services sites across the United States. Occu-Med's strongest V2X argument is a safety-plus-footprint argument: worsening safety indicators, sprain/strain concentration, large workers' compensation reserve growth, and a globally distributed base-ops/MRO/logistics workforce require pre-built provider coverage rather than one-off scheduling searches.",
  tags: [
    "Federal contractor",
    "Global footprint",
    "High operational complexity",
    "V2X",
    "Vectrus",
    "Vertex Aerospace",
    "Verified EHS metrics",
    "TRIR increase",
    "DART increase",
    "Near miss increase",
    "Aerospace MRO",
    "FAA Part 145",
    "Base operations",
    "AETC",
    "Smart Warehouse",
    "Guantanamo Bay",
  ],
  aliases: ["Vectrus", "Vertex", "Vertex Aerospace", "V2X Global Footprint"],
  sourceFilters: {
    sec: { cik: "1601548", ticker: "VVX", legalEntities: ["V2X, Inc."], formerNames: ["Vectrus, Inc."] },
    sam: { legalNames: ["V2X, Inc.", "Vectrus", "Vertex Aerospace"] },
    usaSpending: { recipientNames: ["V2X", "Vectrus", "Vertex Aerospace"] },
    jobSources: { linkedin: "v2x-inc", clearanceJobs: "V2X" },
    newsSources: { aliases: ["V2X", "Vectrus", "Vertex Aerospace", "V2X Smart Warehouse", "V2X MRO"], acquisitionAliases: ["Vertex Aerospace"] },
  },
  executiveSignals: [
    { label: "CY2024 TRIR", value: "0.62", note: "Uploaded EHS screenshot shows TRIR rose from 0.47 in CY2023 to 0.62 in CY2024, a 32% increase." },
    { label: "CY2024 DART", value: "0.45", note: "Uploaded EHS screenshot shows DART rose from 0.34 in CY2023 to 0.45 in CY2024, a 32% increase." },
    { label: "Global footprint", value: "~330 locations", note: "Uploaded Gemini research frames V2X as operating at nearly 330 locations across roughly 47-51 countries/territories." },
    { label: "WC reserve signal", value: "$9.5M", note: "Public reserve/accrual disclosure elevates claims-control and documentation relevance." },
  ],
  curveTitle: "V2X safety deterioration, global footprint, and provider-network curve",
  curveSubtitle:
    "Uploaded V2X EHS screenshots plus V2X global presence research normalized for executive scanability. Site details should be validated before scheduling use.",
  chartDefinitions: [
    {
      id: "v2x-annual-safety",
      title: "V2X annual safety rates: CY2023 vs CY2024",
      subtitle: "Uploaded V2X YTD chart: TRIR +32%, DART +32%, near miss +48% year over year.",
      type: "bar",
      xKey: "year",
      data: [
        { year: "CY2023", dart: 0.34, trir: 0.47, nearMiss: 0.63 },
        { year: "CY2024", dart: 0.45, trir: 0.62, nearMiss: 0.93 },
      ],
      series: [
        { dataKey: "dart", name: "DART", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "trir", name: "TRIR", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "nearMiss", name: "Near Miss", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      domain: [0, 1],
      headline: "annual safety",
      fullWidth: true,
    },
    {
      id: "v2x-safety-monthly",
      title: "V2X CY2024 safety metrics by month",
      subtitle: "Uploaded V2X EHS visual: January and July spikes plus November near-miss peak.",
      type: "area",
      xKey: "month",
      data: [
        { month: "Jan", trir: 0.97, dart: 0.66, nearMiss: 1.03 },
        { month: "Feb", trir: 0.81, dart: 0.54, nearMiss: 1.03 },
        { month: "Mar", trir: 0.53, dart: 0.34, nearMiss: 0.96 },
        { month: "Apr", trir: 0.67, dart: 0.64, nearMiss: 0.70 },
        { month: "May", trir: 0.36, dart: 0.31, nearMiss: 0.60 },
        { month: "Jun", trir: 0.55, dart: 0.35, nearMiss: 0.96 },
        { month: "Jul", trir: 0.82, dart: 0.48, nearMiss: 1.13 },
        { month: "Aug", trir: 0.58, dart: 0.50, nearMiss: 0.67 },
        { month: "Sep", trir: 0.45, dart: 0.34, nearMiss: 0.88 },
        { month: "Oct", trir: 0.63, dart: 0.43, nearMiss: 0.74 },
        { month: "Nov", trir: 0.64, dart: 0.50, nearMiss: 1.48 },
        { month: "Dec", trir: 0.52, dart: 0.30, nearMiss: 1.10 },
      ],
      series: [
        { dataKey: "nearMiss", name: "Near Miss", color: "#22c55e" },
        { dataKey: "trir", name: "TRIR", color: "#ef4444" },
        { dataKey: "dart", name: "DART", color: "#f97316" },
      ],
      domain: [0, 1.6],
      headline: "safety metrics",
    },
    {
      id: "v2x-corporate-technical-nodes",
      title: "V2X corporate and technical command nodes",
      subtitle: "Primary U.S. branches and operations centers from the uploaded presence report.",
      type: "bar",
      xKey: "node",
      data: [
        { node: "Reston VA HQ", priority: 10 },
        { node: "McLean VA", priority: 9 },
        { node: "Glen Allen VA", priority: 8 },
        { node: "Colorado Springs", priority: 8 },
        { node: "Indianapolis", priority: 9 },
        { node: "Madison MS", priority: 9 },
        { node: "Orlando FL", priority: 8 },
        { node: "Fayetteville NC", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Operational priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "command nodes",
      fullWidth: true,
    },
    {
      id: "v2x-mro-aerospace-sites",
      title: "V2X aerospace and MRO infrastructure",
      subtitle: "Uploaded report highlights FAA Part 145 and dedicated aerospace sustainment sites.",
      type: "bar",
      xKey: "site",
      data: [
        { site: "Fort Worth Alliance", priority: 10 },
        { site: "Crestview FL", priority: 10 },
        { site: "Madison MS", priority: 9 },
        { site: "Indianapolis IN", priority: 8 },
        { site: "Fairchild Road", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "MRO priority", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "MRO sites",
    },
    {
      id: "v2x-base-ops-sites",
      title: "V2X base operations and training support sites",
      subtitle: "The uploaded report lists AETC and near-OCONUS support sites where physical work and medical clearance needs concentrate.",
      type: "bar",
      xKey: "installation",
      data: [
        { installation: "Maxwell AFB", priority: 8 },
        { installation: "Sheppard AFB", priority: 8 },
        { installation: "Keesler AFB", priority: 8 },
        { installation: "US Naval Academy", priority: 6 },
        { installation: "Guantanamo Bay", priority: 10 },
        { installation: "Marine Corps Logistics Cmd", priority: 9 },
      ],
      series: [{ dataKey: "priority", name: "Medical/network priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "BOSS sites",
      fullWidth: true,
    },
    {
      id: "v2x-injury-mix",
      title: "V2X recordable injury mix 2022-2024",
      subtitle: "Uploaded V2X EHS metrics visual: sprains/strains are the leading category at 45% in 2024.",
      type: "bar",
      xKey: "type",
      data: [
        { type: "Sprain/Strain", y2022: 41.7, y2023: 38.3, y2024: 45 },
        { type: "Laceration", y2022: 17.3, y2023: 15.9, y2024: 15 },
        { type: "Bruise", y2022: 9.0, y2023: 9.2, y2024: 11 },
        { type: "Fracture", y2022: 3.2, y2023: 5.8, y2024: 6 },
        { type: "Swelling", y2022: 0, y2023: 1.7, y2024: 2 },
      ],
      series: [
        { dataKey: "y2022", name: "2022", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "y2023", name: "2023", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "y2024", name: "2024", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "percent",
      headline: "injury mix",
    },
    {
      id: "v2x-wc-reserve",
      title: "V2X workers compensation reserve trend",
      subtitle: "Uploaded SEC 10-K visual: reserve grew from $2.8M to $9.5M.",
      type: "line",
      xKey: "period",
      data: [
        { period: "Dec 2022", value: 2.8 },
        { period: "Dec 2023", value: 7.0 },
        { period: "Dec 2024", value: 9.5 },
      ],
      series: [{ dataKey: "value", name: "Reserve", color: "#22d3ee" }],
      formatter: "currencyM",
      headline: "reserve trend",
    },
  ],
  metricDefinitions: [
    { id: "v2x-workers", label: "Employees", value: 16100, unit: "count", category: "workforce" },
    { id: "v2x-footprint-locations", label: "Global locations", value: 330, unit: "count", category: "workforce" },
    { id: "v2x-footprint-countries-low", label: "Country/territory low", value: 47, unit: "count", category: "workforce" },
    { id: "v2x-footprint-countries-high", label: "Country/territory high", value: 51, unit: "count", category: "workforce" },
    { id: "v2x-trir-2024", label: "CY2024 TRIR", value: 0.62, unit: "score", category: "safety" },
    { id: "v2x-dart-2024", label: "CY2024 DART", value: 0.45, unit: "score", category: "safety" },
    { id: "v2x-near-miss-2024", label: "CY2024 near miss rate", value: 0.93, unit: "score", category: "safety" },
    { id: "v2x-wc-reserve-2024", label: "WC reserve", value: 9.5, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Europe", revenue: 0.21, risk: 3.5, workers: 150 },
    { name: "INDOPACOM", revenue: 0.33, risk: 6.0, workers: 260 },
    { name: "CONUS Aviation / MRO", revenue: 1.10, risk: 8.0, workers: 600 },
    { name: "CONUS Base Ops", revenue: 1.28, risk: 5.0, workers: 520 },
    { name: "Kuwait/Iraq", revenue: 1.40, risk: 9.0, workers: 760 },
  ],
  opportunityMatrix: [
    { name: "Pre-Employment Physicals", revenuePotential: 85, implementationComplexity: 2, strategicValue: 7 },
    { name: "DBA Pre-Deploy Exams", revenuePotential: 90, implementationComplexity: 4, strategicValue: 9 },
    { name: "MRO Provider Network", revenuePotential: 450, implementationComplexity: 6, strategicValue: 9 },
    { name: "Base Ops / AETC Exam Coverage", revenuePotential: 600, implementationComplexity: 7, strategicValue: 10 },
    { name: "Hearing Conservation", revenuePotential: 50, implementationComplexity: 3, strategicValue: 6 },
    { name: "Behavioral Health", revenuePotential: 70, implementationComplexity: 5, strategicValue: 8 },
  ],
};
