import type { CompanyConfig } from "./types";

export const v2xConfig: CompanyConfig = {
  companyId: "v2x",
  displayName: "V2X, Inc.",
  shortName: "V2X",
  sector: "Defense services, logistics, training, and mission support",
  headquarters: "McLean, Virginia",
  employees: 16100,
  employeesAsOf: "2024-12-31",
  summary: "Global mission-support contractor with distributed field operations, aviation, logistics, facilities, and expeditionary workforce exposure.",
  tags: ["Federal contractor", "Global footprint", "High operational complexity"],
  aliases: ["Vectrus", "Vertex"],
  sourceFilters: {
    sec: { cik: "1601548", ticker: "VVX", legalEntities: ["V2X, Inc."], formerNames: ["Vectrus, Inc."] },
    sam: { legalNames: ["V2X, Inc."] },
    usaSpending: { recipientNames: ["V2X", "Vectrus"] },
    jobSources: { linkedin: "v2x-inc", clearanceJobs: "V2X" },
    newsSources: { aliases: ["V2X", "Vectrus"], acquisitionAliases: ["Vertex Aerospace"] },
  },
  executiveSignals: [
    { label: "Global workforce exposure", value: "16,100 employees", note: "Large distributed workforce creates broad service aperture." },
    { label: "WC reserve signal", value: "$9.5M", note: "Public reserve/accrual disclosure elevates claims-control relevance." },
    { label: "Footprint intensity", value: "80+ mapped sites", note: "Workbook geography indicates multi-region complexity." },
    { label: "Operating environment", value: "High complexity", note: "Defense and overseas support increase readiness needs." },
  ],
  curveTitle: "V2X exposure curve",
  curveSubtitle: "Workbook values normalized for executive scanability.",
  chartDefinitions: [
    {
      id: "v2x-safety-monthly",
      title: "V2X CY2024 all three safety metrics by month",
      subtitle: "Source: uploaded V2X EHS visual; January and July spikes plus November near-miss peak.",
      type: "area",
      xKey: "month",
      data: [
        { month: "Jan", trir: 0.97, dart: 0.66, nearMiss: 1.03 },
        { month: "Feb", trir: 0.81, dart: 0.54, nearMiss: 1.03 },
        { month: "Mar", trir: 0.53, dart: 0.34, nearMiss: 0.96 },
        { month: "Apr", trir: 0.67, dart: 0.64, nearMiss: 0.70 },
        { month: "May", trir: 0.36, dart: 0.31, nearMiss: 0.60 },
        { month: "Jun", trir: 0.55, dart: 0.35, nearMiss: 0.96 },
        { month: "Jul", trir: 0.82, dart: 0.48, nearMiss: 1.13 },
        { month: "Aug", trir: 0.58, dart: 0.50, nearMiss: 0.67 },
        { month: "Sep", trir: 0.45, dart: 0.34, nearMiss: 0.88 },
        { month: "Oct", trir: 0.63, dart: 0.43, nearMiss: 0.74 },
        { month: "Nov", trir: 0.64, dart: 0.50, nearMiss: 1.48 },
        { month: "Dec", trir: 0.52, dart: 0.30, nearMiss: 1.10 },
      ],
      series: [
        { dataKey: "nearMiss", name: "Near Miss", color: "#22c55e" },
        { dataKey: "trir", name: "TRIR", color: "#ef4444" },
        { dataKey: "dart", name: "DART", color: "#f97316" },
      ],
      domain: [0, 1.6],
      headline: "safety metrics",
    },
    {
      id: "v2x-annual-safety",
      title: "V2X annual safety rates: CY2023 vs CY2024",
      subtitle: "Source: uploaded V2X YTD chart; TRIR +32%, DART +32%, near miss +48% YoY.",
      type: "bar",
      xKey: "year",
      data: [
        { year: "CY2023", dart: 0.34, trir: 0.47, nearMiss: 0.63 },
        { year: "CY2024", dart: 0.45, trir: 0.62, nearMiss: 0.93 },
      ],
      series: [
        { dataKey: "dart", name: "DART", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "trir", name: "TRIR", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "nearMiss", name: "Near Miss", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      domain: [0, 1],
      headline: "annual safety",
    },
    {
      id: "v2x-customer-mix",
      title: "V2X FY2024 revenue by customer",
      subtitle: "Source: uploaded SEC 10-K visual; customer mix percentage.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "Army", value: 42.5 },
        { name: "Navy", value: 33.3 },
        { name: "Other", value: 13.0 },
        { name: "Air Force", value: 11.1 },
      ],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "percent",
      domain: [0, 50],
      headline: "V2X metric",
    },
    {
      id: "v2x-revenue-growth",
      title: "V2X revenue growth FY2020-FY2024",
      subtitle: "Source: uploaded SEC 10-K visual; 2022 Vectrus-Vertex merger doubled revenue.",
      type: "area",
      xKey: "year",
      data: [
        { year: "FY2020", revenue: 1400 },
        { year: "FY2021", revenue: 1400 },
        { year: "FY2022", revenue: 2900 },
        { year: "FY2023", revenue: 4000 },
        { year: "FY2024", revenue: 4300 },
      ],
      series: [{ dataKey: "revenue", color: "#22d3ee" }],
      formatter: "currencyM",
      headline: "revenue growth",
    },
    {
      id: "v2x-region-revenue",
      title: "V2X revenue by region FY2022-FY2024",
      subtitle: "Source: uploaded SEC 10-K visual; Middle East and United States are largest shown regions.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "United States", fy2022: 1500, fy2023: 2300, fy2024: 2400 },
        { region: "Middle East", fy2022: 1000, fy2023: 1200, fy2024: 1400 },
        { region: "Asia/INDOPACOM", fy2022: 200, fy2023: 300, fy2024: 300 },
        { region: "Europe", fy2022: 200, fy2023: 200, fy2024: 200 },
      ],
      series: [
        { dataKey: "fy2022", name: "FY2022", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "fy2023", name: "FY2023", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "fy2024", name: "FY2024", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "regional revenue",
    },
    {
      id: "v2x-region-growth",
      title: "V2X revenue growth by region",
      subtitle: "Source: uploaded SEC 10-K visual; latest period shows Europe decline and INDOPACOM still positive.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "Middle East", old: 16.5, latest: 17.2 },
        { region: "INDOPACOM", old: 57.6, latest: 23.7 },
        { region: "Europe", old: 7.4, latest: -5.5 },
        { region: "United States", old: 52.9, latest: 4.5 },
      ],
      series: [
        { dataKey: "old", name: "FY2022-FY2023", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "latest", name: "FY2023-FY2024", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      formatter: "percent",
      headline: "regional growth",
    },
    {
      id: "v2x-injury-mix",
      title: "V2X recordable injury mix 2022-2024",
      subtitle: "Source: uploaded V2X EHS metrics visual; sprains/strains are the leading cause at 45% in 2024.",
      type: "bar",
      xKey: "type",
      data: [
        { type: "Sprain/Strain", y2022: 41.7, y2023: 38.3, y2024: 45 },
        { type: "Laceration", y2022: 17.3, y2023: 15.9, y2024: 15 },
        { type: "Bruise", y2022: 9.0, y2023: 9.2, y2024: 11 },
        { type: "Fracture", y2022: 3.2, y2023: 5.8, y2024: 6 },
        { type: "Swelling", y2022: 0, y2023: 1.7, y2024: 2 },
      ],
      series: [
        { dataKey: "y2022", name: "2022", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "y2023", name: "2023", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "y2024", name: "2024", color: "#22c55e", radius: [8, 8, 0, 0] },
      ],
      formatter: "percent",
      headline: "injury mix",
    },
    {
      id: "v2x-near-miss-trend",
      title: "V2X near-miss reporting trend",
      subtitle: "Source: uploaded Good Catch Program visual; near-miss rate grows from 0.09 to 0.93.",
      type: "area",
      xKey: "year",
      data: [
        { year: "2021", value: 0.09 },
        { year: "2022", value: 0.25 },
        { year: "2023", value: 0.60 },
        { year: "2024", value: 0.93 },
      ],
      series: [{ dataKey: "value", color: "#22c55e" }],
      domain: [0, 1],
      headline: "near miss trend",
    },
    {
      id: "v2x-hours-worked",
      title: "V2X total hours worked",
      subtitle: "Source: uploaded V2X EHS metrics visual; 2024 excludes training sites and classified operations.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "2022", hours: 99.9 },
        { name: "2023", hours: 105.2 },
        { name: "2024", hours: 86.4 },
      ],
      series: [{ dataKey: "hours", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "hoursM",
      domain: [0, 120],
      headline: "V2X metric",
    },
    {
      id: "v2x-wc-reserve",
      title: "V2X workers compensation reserve trend",
      subtitle: "Source: uploaded SEC 10-K visual; reserve grew from $2.8M to $9.5M.",
      type: "line",
      xKey: "period",
      data: [
        { period: "Dec 2022", value: 2.8 },
        { period: "Dec 2023", value: 7.0 },
        { period: "Dec 2024", value: 9.5 },
      ],
      series: [{ dataKey: "value", name: "Reserve", color: "#22d3ee" }],
      formatter: "currencyM",
      headline: "reserve trend",
    },
  ],
  riskMatrix: [
    { name: "Europe", revenue: 0.21, risk: 3.5, workers: 150 },
    { name: "INDOPACOM", revenue: 0.33, risk: 6.0, workers: 260 },
    { name: "CONUS Aviation", revenue: 1.10, risk: 8.0, workers: 600 },
    { name: "CONUS Base Ops", revenue: 1.28, risk: 5.0, workers: 520 },
    { name: "Kuwait/Iraq", revenue: 1.40, risk: 9.0, workers: 760 },
  ],
  opportunityMatrix: [
    { name: "Pre-Employment Physicals", revenuePotential: 85, implementationComplexity: 2, strategicValue: 7 },
    { name: "DBA Pre-Deploy Exams", revenuePotential: 90, implementationComplexity: 4, strategicValue: 9 },
    { name: "Hearing Conservation", revenuePotential: 50, implementationComplexity: 3, strategicValue: 6 },
    { name: "Behavioral Health", revenuePotential: 70, implementationComplexity: 5, strategicValue: 8 },
  ],
};
