import type { CompanyConfig } from "./types";

export const valiantConfig: CompanyConfig = {
  companyId: "valiant",
  displayName: "Valiant Integrated Services",
  shortName: "Valiant",
  sector:
    "Military training, simulation, special operations support, linguistics, logistics, medical facility operations, base operations, mission readiness, blast overpressure exposure, and OCONUS support",
  headquarters: "Herndon, Virginia",
  employees: 4500,
  employeesAsOf: "Uploaded Valiant reports: 4,500 employees across 120+ project sites worldwide; location analysis cites approximately 4,500-5,000 employees and 130+ project sites",
  summary:
    "Valiant Integrated Services is a privately held government services contractor headquartered in Herndon, Virginia, with about 4,500 employees across more than 120 project sites worldwide. The uploaded Occu-Med report frames Valiant as a training-heavy contractor where the signature occupational medicine gap is blast overpressure and impulse noise exposure on live-fire ranges. The companion locations report adds the global operating map: domestic nodes in Herndon, Clarksville, Fayetteville, Orlando, San Diego, Fort Stewart, JBLM, Fort Johnson, Wright-Patterson AFB, and NAS Corpus Christi; European/Mediterranean activity in Germany, Italy, Romania, Naples, and Sigonella; and Middle East / Central Asian activity in the UAE, Iraq, Jordan, Kuwait, and Bahrain. The account should be treated as mission-readiness medicine, not generic government services: enhanced audiometry, EHF testing, heat-readiness, SOF/training cadre fitness, OCONUS DBA, linguist/psychological readiness, and medical facility support all sit in the same entity profile.",
  tags: [
    "Entity profile",
    "Valiant Integrated Services",
    "Training ranges",
    "Blast overpressure",
    "Impulse noise",
    "Extended high-frequency audiometry",
    "XCTC",
    "USASOC",
    "Heat illness",
    "DBA",
    "Mission readiness",
    "Linguistics",
    "Medical facility O&M",
    "Veteran workforce",
  ],
  aliases: ["Valiant Integrated Services", "Valiant Integrated Services LLC", "GC Valiant LLC", "Valiant"],
  sourceFilters: {
    sam: { legalNames: ["Valiant Integrated Services LLC", "Valiant Integrated Services"] },
    usaSpending: { recipientNames: ["Valiant Integrated Services", "Valiant"] },
    jobSources: { linkedin: "valiant-integrated-services", careerSite: "https://www.onevaliant.com/careers/" },
    newsSources: { aliases: ["Valiant Integrated Services", "XCTC", "USASOC Advanced Training", "Winn Army Community Hospital", "Valiant linguist"] },
  },
  executiveSignals: [
    { label: "Employees", value: "4.5K", note: "Uploaded report identifies 4,500 employees; location analysis gives approximately 4,500-5,000 employees." },
    { label: "Project sites", value: "120+", note: "Uploaded report identifies 120+ project sites worldwide; location analysis cites 130+ project sites." },
    { label: "Peak blast/noise", value: "158-180 dB", note: "Training munitions generate impulse noise far above the OSHA continuous-noise framework." },
    { label: "Cumulative awards", value: "$5.1B+", note: "Uploaded report states cumulative federal contract awards exceed $5.1B since Valiant's founding." },
  ],
  curveTitle: "Valiant mission-readiness, blast exposure, and global training-support curve",
  curveSubtitle:
    "Uploaded Valiant Occu-Med report and location analysis normalized into entity-profile charts; values are strategic intelligence assumptions requiring validation with Valiant program data.",
  chartDefinitions: [
    {
      id: "valiant-blast-noise",
      title: "Training range noise vs OSHA thresholds",
      subtitle: "Impulse-noise levels from the uploaded Valiant report; OSHA 1910.95 was designed for continuous industrial noise, not blast overpressure.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "OSHA Action", value: 85 },
        { name: "OSHA Permissible", value: 90 },
        { name: "M16/M4", value: 158 },
        { name: "M249 SAW", value: 162 },
        { name: "M2 .50 Cal", value: 165 },
        { name: "Pyro Blast", value: 170 },
        { name: "Artillery Sim", value: 180 },
      ],
      series: [{ dataKey: "value", name: "Peak dB", color: "#dc2626", radius: [10, 10, 0, 0] }],
      domain: [0, 185],
      referenceLines: [
        { y: 85, stroke: "#22c55e", strokeDasharray: "4 4", label: { value: "85 dB OSHA action", fill: "#bbf7d0", fontSize: 10 } },
        { y: 90, stroke: "#16a34a", strokeDasharray: "4 4", label: { value: "90 dB OSHA permissible", fill: "#bbf7d0", fontSize: 10 } },
        { y: 140, stroke: "#f59e0b", strokeDasharray: "4 4", label: { value: "140 dB impulse concern", fill: "#fde68a", fontSize: 10 } },
      ],
      headline: "blast exposure",
      fullWidth: true,
    },
    {
      id: "valiant-contracts",
      title: "Valiant federal contract portfolio",
      subtitle: "Training and sustainment contracts define the workforce and medical-readiness profile.",
      type: "bar",
      xKey: "contract",
      data: [
        { contract: "XCTC Army Natl Guard", value: 555 },
        { contract: "Army IDIQ", value: 530 },
        { contract: "USASOC SOF Training", value: 150 },
        { contract: "Winn Army Hospital", value: 8.6 },
        { contract: "NATO/Canadian Linguist", value: 2.4 },
      ],
      series: [{ dataKey: "value", name: "Contract value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "contract drivers",
    },
    {
      id: "valiant-domestic-nodes",
      title: "Valiant domestic operational nodes",
      subtitle: "Locations and service types from uploaded locations report.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Herndon VA HQ", priority: 8 },
        { location: "Clarksville TN", priority: 7 },
        { location: "Fayetteville NC", priority: 8 },
        { location: "Orlando FL", priority: 9 },
        { location: "San Diego CA", priority: 8 },
        { location: "Fort Stewart GA", priority: 9 },
        { location: "JBLM WA", priority: 8 },
        { location: "Fort Johnson LA", priority: 10 },
        { location: "Wright-Patterson OH", priority: 7 },
        { location: "NAS Corpus Christi TX", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Network priority", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "CONUS nodes",
      fullWidth: true,
    },
    {
      id: "valiant-global-theaters",
      title: "Valiant global theater footprint",
      subtitle: "Global regions from the uploaded location analysis; scored by mission-readiness medical complexity.",
      type: "bar",
      xKey: "theater",
      data: [
        { theater: "Germany / EUCOM", priority: 8 },
        { theater: "Italy / Naples-Sigonella", priority: 8 },
        { theater: "Romania linguists", priority: 7 },
        { theater: "UAE", priority: 8 },
        { theater: "Iraq", priority: 10 },
        { theater: "Jordan", priority: 9 },
        { theater: "Kuwait", priority: 9 },
        { theater: "Bahrain logistics", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Medical complexity", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "global footprint",
    },
    {
      id: "valiant-heat",
      title: "XCTC training site peak summer temperatures",
      subtitle: "Heat illness readiness matters because training moves across hot CONUS ranges.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "Fort Irwin", temp: 116, risk: 9 },
        { name: "Fort Bliss", temp: 113, risk: 8 },
        { name: "Fort Cavazos", temp: 110, risk: 8 },
        { name: "Fort Johnson", temp: 102, risk: 8 },
        { name: "CMTC Europe", temp: 90, risk: 4 },
        { name: "Grafenwoehr", temp: 88, risk: 4 },
      ],
      series: [
        { dataKey: "risk", name: "Risk score", color: "#ef4444", radius: [10, 10, 0, 0] },
        { dataKey: "temp", name: "Peak temp", color: "#22d3ee", radius: [10, 10, 0, 0] },
      ],
      headline: "heat risk",
    },
    {
      id: "valiant-worker-risk",
      title: "Valiant worker risk by BLS / analog TRIR benchmark",
      subtitle: "Training cadre, SOF trainers, mechanics, logistics, linguists, hospital/base operations, and program/admin workers carry different exam logic.",
      type: "bar",
      xKey: "workerType",
      data: [
        { workerType: "Range Cadre", trir: 2.0 },
        { workerType: "SOF Trainers", trir: 2.2 },
        { workerType: "Mechanics", trir: 3.2 },
        { workerType: "Logistics", trir: 3.9 },
        { workerType: "Linguists", trir: 0.5 },
        { workerType: "Hospital/Base", trir: 1.8 },
        { workerType: "Program/Admin", trir: 0.6 },
      ],
      series: [{ dataKey: "trir", name: "TRIR benchmark", color: "#f97316", radius: [10, 10, 0, 0] }],
      headline: "worker risk",
      fullWidth: true,
    },
    {
      id: "valiant-revenue",
      title: "Valiant Occu-Med revenue by exam type",
      subtitle: "Blast audiometry and DBA pre-deployment are the strongest modeled service lanes.",
      type: "bar",
      xKey: "exam",
      data: [
        { exam: "Blast Audio / EHF", value: 344 },
        { exam: "DBA Pre-Deploy", value: 202 },
        { exam: "Pre-Employment", value: 172 },
        { exam: "Heat Illness", value: 100 },
        { exam: "Standard Audio", value: 69 },
        { exam: "DOT/CDL", value: 35 },
        { exam: "Drug Screen", value: 23 },
      ],
      series: [{ dataKey: "value", name: "Annual potential", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "revenue potential",
    },
  ],
  metricDefinitions: [
    { id: "valiant-employees", label: "Employees", value: 4500, unit: "count", category: "workforce" },
    { id: "valiant-sites", label: "Project sites", value: 120, unit: "count", category: "workforce" },
    { id: "valiant-cumulative-awards", label: "Cumulative federal awards", value: 5.1, unit: "usd", category: "financial" },
    { id: "valiant-revenue-low", label: "Estimated revenue low", value: 400, unit: "usd", category: "financial" },
    { id: "valiant-revenue-high", label: "Estimated revenue high", value: 650, unit: "usd", category: "financial" },
    { id: "valiant-blast-peak", label: "Peak impulse noise", value: 180, unit: "score", category: "risk" },
    { id: "valiant-xctc", label: "XCTC contract", value: 555, unit: "usd", category: "financial" },
    { id: "valiant-occumed-revenue", label: "Modeled Occu-Med revenue", value: 0.945, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "Blast / impulse-noise cadre", revenue: 344, risk: 10.0, workers: 800 },
    { name: "XCTC heat/training cadre", revenue: 250, risk: 9.5, workers: 1200 },
    { name: "SOF trainers", revenue: 150, risk: 9.0, workers: 400 },
    { name: "OCONUS linguists/support", revenue: 202, risk: 8.5, workers: 700 },
    { name: "Hospital/base O&M", revenue: 100, risk: 7.0, workers: 600 },
  ],
  opportunityMatrix: [
    { name: "Blast/EHF Audiometry", revenuePotential: 344, implementationComplexity: 8, strategicValue: 10 },
    { name: "DBA Pre-Deployment", revenuePotential: 202, implementationComplexity: 6, strategicValue: 9 },
    { name: "Pre-Employment Physicals", revenuePotential: 172, implementationComplexity: 4, strategicValue: 7 },
    { name: "Heat Illness Readiness", revenuePotential: 100, implementationComplexity: 5, strategicValue: 8 },
    { name: "Medical Facility O&M Screening", revenuePotential: 75, implementationComplexity: 5, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Valiant should be profiled as a mission-readiness and training-range account. The uploaded report emphasizes that its signature exposure is not ordinary office work or even ordinary logistics; it is repeated blast overpressure and impulse-noise exposure absorbed by training cadre on live-fire ranges.",
      bullets: [
        "Privately held government services contractor headquartered in Herndon, Virginia.",
        "Approximately 4,500 employees across more than 120 project sites worldwide.",
        "Cumulative federal contract awards exceed $5.1B since founding.",
        "Business lines include training/simulation, special operations support, logistics, intelligence analysis, language services, and base/medical facility operations.",
      ],
      metricIds: ["valiant-employees", "valiant-sites", "valiant-cumulative-awards"],
    },
    {
      type: "safety",
      title: "Blast overpressure and audiometry protocol gap",
      narrative:
        "The uploaded report says OSHA 1910.95 is insufficient for Valiant's training-range workforce because it was written for continuous industrial noise, while training munitions produce microsecond impulse-noise events at 158-180 dB.",
      bullets: [
        "Blast overpressure can mechanically damage cochlear structures before standard audiometry reliably captures the loss.",
        "High-frequency threshold shifts at 6 kHz and 8 kHz can be early signals of blast-induced hearing loss.",
        "Extended high-frequency audiometry at 10 kHz, 12.5 kHz, and 16 kHz is the differentiated protocol opportunity.",
        "Standard walk-in clinic audiometry should not be treated as sufficient for this workforce.",
      ],
      metricIds: ["valiant-blast-peak"],
    },
    {
      type: "locations",
      title: "Domestic and global mission footprint",
      narrative:
        "The locations report shows a distributed operational footprint where provider network buildout should follow training centers, SOF support nodes, medical facility O&M sites, and OCONUS theater support locations.",
      bullets: [
        "CONUS nodes include Herndon, Clarksville, Fayetteville, Orlando, San Diego, Fort Stewart, JBLM, Fort Johnson, Wright-Patterson AFB, and NAS Corpus Christi.",
        "European and Mediterranean activity includes Germany, Italy, Naples, Sigonella, and Romania linguist support.",
        "Middle East and Central Asian activity includes UAE, Iraq, Jordan, Kuwait, and Bahrain logistics/sustainment support.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The strongest opportunity is not generic physicals. It is an integrated readiness program that pairs training-range hearing protocols with heat readiness, DBA pre-deployment, SOF/training-cadre fitness, linguist psychological readiness, and medical facility O&M occupational screening.",
      bullets: [
        "Blast/EHF audiometry is the anchor differentiator.",
        "DBA pre-deployment and OCONUS readiness apply to deployed training, linguist, logistics, and mission-support populations.",
        "Heat illness screening and hydration/readiness protocols matter for XCTC and hot-weather training locations.",
      ],
      metricIds: ["valiant-occumed-revenue"],
    },
  ],
};
