import type { CompanyConfig } from "./types";

export const valiantConfig: CompanyConfig = {
  companyId: "valiant",
  displayName: "Valiant Integrated Services",
  shortName: "Valiant",
  sector: "Military training, simulation, logistics, language services, base operations, and defense support",
  headquarters: "Herndon, Virginia",
  employees: 4500,
  employeesAsOf: "Uploaded report: ~4,500 employees across 120+ project sites worldwide",
  summary: "Training-heavy government services contractor focused on live-fire range cadre, blast overpressure, impulse noise, XCTC heat stress, OCONUS DBA work, Fort Riley maintenance, and CBA-driven drug testing.",
  tags: ["Training ranges", "Blast overpressure", "Impulse noise", "XCTC", "USASOC", "Heat illness", "DBA", "Fort Riley CBA"],
  aliases: ["Valiant Integrated Services LLC"],
  executiveSignals: [
    { label: "Peak blast/noise", value: "180 dB", note: "Artillery simulator peak level exceeds OSHA and NIH impulse-noise lines." },
    { label: "Largest contract", value: "$555M", note: "XCTC Army National Guard is the largest modeled federal contract value." },
    { label: "Revenue potential", value: "$945K/yr", note: "Blast audiometry and DBA pre-deploy are the strongest modeled service lanes." },
    { label: "Heat risk", value: "116\u00B0F", note: "NTC Fort Irwin is the highest modeled peak summer temperature." },
  ],
  curveTitle: "Valiant training-range exposure curve",
  curveSubtitle: "Blast/noise, contract value, heat risk, TRIR benchmark, and revenue potential normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "valiant-blast-noise",
      title: "Training range noise vs OSHA thresholds",
      subtitle: "Source: uploaded Valiant visual; peak sound levels in dB with OSHA and NIH reference lines.",
      type: "bar",
      xKey: "name",
      data: [{ name: "OSHA Action", value: 85 }, { name: "OSHA Permissible", value: 90 }, { name: "M16/M4", value: 158 }, { name: "M249 SAW", value: 162 }, { name: "M2 .50 Cal", value: 165 }, { name: "Artillery Sim", value: 180 }, { name: "Pyro Blast", value: 170 }],
      series: [{ dataKey: "value", color: "#dc2626", radius: [10, 10, 0, 0] }],
      domain: [0, 185],
      referenceLines: [
        { y: 85, stroke: "#22c55e", strokeDasharray: "4 4", label: { value: "85 dB OSHA action", fill: "#bbf7d0", fontSize: 10 } },
        { y: 90, stroke: "#16a34a", strokeDasharray: "4 4", label: { value: "90 dB OSHA permissible", fill: "#bbf7d0", fontSize: 10 } },
        { y: 140, stroke: "#f59e0b", strokeDasharray: "4 4", label: { value: "140 dB NIH", fill: "#fde68a", fontSize: 10 } },
      ],
      headline: "noise exposure",
    },
    {
      id: "valiant-contracts",
      title: "Valiant federal contract portfolio",
      subtitle: "Source: uploaded Valiant visual; contract value shown in $M.",
      type: "bar",
      xKey: "name",
      data: [{ name: "XCTC ANG", value: 555 }, { name: "Army IDIQ", value: 530 }, { name: "USASOC SOF", value: 150 }, { name: "Winn Army", value: 8.6 }, { name: "NATO Linguist", value: 2.4 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "Valiant metric",
    },
    {
      id: "valiant-heat",
      title: "XCTC training site peak summer temperatures",
      subtitle: "Source: uploaded Valiant visual; peak summer temperature by training site.",
      type: "bar",
      xKey: "name",
      data: [{ name: "Fort Irwin", temp: 116, risk: 9 }, { name: "Fort Johnson", temp: 102, risk: 8 }, { name: "Grafenwoehr", temp: 88, risk: 4 }, { name: "Fort Cavazos", temp: 110, risk: 8 }, { name: "Fort Bliss", temp: 113, risk: 8 }, { name: "CMTC Europe", temp: 90, risk: 4 }],
      series: [
        { dataKey: "risk", name: "Risk score", color: "#ef4444", radius: [10, 10, 0, 0] },
        { dataKey: "temp", name: "Peak temp", color: "#22d3ee", radius: [10, 10, 0, 0] },
      ],
      headline: "Valiant metric",
    },
    {
      id: "valiant-revenue",
      title: "Valiant Occu-Med revenue by exam type",
      subtitle: "Source: uploaded Valiant visual; annual revenue potential shown in $K.",
      type: "bar",
      xKey: "name",
      data: [{ name: "Blast Audio", value: 344 }, { name: "Pre-Employ", value: 172 }, { name: "DBA Pre-Deploy", value: 202 }, { name: "Heat Illness", value: 100 }, { name: "Standard Audio", value: 69 }, { name: "Drug Screen", value: 23 }, { name: "DOT/CDL", value: 35 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "Valiant metric",
    },
    {
      id: "valiant-trir",
      title: "Valiant worker risk by BLS TRIR benchmark",
      subtitle: "Source: uploaded Valiant visual; worker category TRIR benchmark.",
      type: "bar",
      xKey: "name",
      data: [{ name: "Range Cadre", value: 2.0 }, { name: "SOF Trainers", value: 2.2 }, { name: "Mechanics", value: 3.2 }, { name: "Logistics", value: 3.9 }, { name: "Linguists", value: 0.5 }, { name: "Hospital/Base", value: 1.8 }, { name: "Program/Admin", value: 0.6 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "Valiant metric",
      fullWidth: true,
    },
  ],
};
