import type { CompanyConfig } from "./types";

export const versarConfig: CompanyConfig = {
  companyId: "versar-global-solutions",
  displayName: "Versar Global Solutions",
  shortName: "Versar",
  sector:
    "Environmental remediation, HTRW services, munitions/UXO response, OCONUS construction management, security systems, BayFirst IT/cyber, and government infrastructure support",
  headquarters: "Springfield, Virginia",
  employees: 2000,
  employeesAsOf: "Uploaded Occu-Med intelligence report: February 19, 2026",
  summary:
    "Versar Global Solutions is a PE-owned environmental, munitions response, and construction management entity backed by Kingswood Capital. The uploaded report frames Versar as an immediate OSHA/HAZWOPER and PE-exit-value account: HTRW environmental field workers and munitions/UXO crews generate the largest injury and compliance exposure, while the WSP/Louis Berger acquisition created a potential inherited-baseline gap across roughly 1,400 employees.",
  tags: [
    "Entity profile",
    "HTRW",
    "HAZWOPER",
    "UXO",
    "Munitions response",
    "Kingswood Capital",
    "PE exit",
    "Louis Berger acquisition",
    "Middle East CPSS",
    "DBA exposure",
    "CENTCOM heat readiness",
  ],
  aliases: ["Versar", "Versar Global Solutions", "Versar Inc", "BayFirst", "Louis Berger legacy", "WSP/Louis Berger"],
  sourceFilters: {
    sam: { legalNames: ["Versar Global Solutions", "Versar Inc", "BayFirst Solutions"] },
    usaSpending: { recipientNames: ["Versar", "Versar Global Solutions", "BayFirst"] },
    jobSources: { linkedin: "versar", careerSite: "https://www.versar.com/careers/" },
    newsSources: { aliases: ["Versar", "Versar Global Solutions", "Kingswood Capital Versar", "Parsons Versar CPSS", "WSP Louis Berger Versar"] },
  },
  executiveSignals: [
    {
      label: "Expected injuries",
      value: "17–18/yr",
      note: "BLS benchmark model for HTRW, UXO, construction management, security systems, and IT/cyber worker groups.",
    },
    {
      label: "Direct injury cost",
      value: "$1.1M–$1.7M/yr",
      note: "Modeled direct annual cost from uploaded Versar workforce table and injury-cost chart.",
    },
    {
      label: "Mandatory HAZWOPER lane",
      value: "$280K–$600K/yr",
      note: "Annual recurring HAZWOPER medical revenue potential across 800-1,000 workers at $350-$600/exam.",
    },
    {
      label: "Inherited baseline gap",
      value: "~1,400 workers",
      note: "WSP/Louis Berger acquisition may have moved workers into Versar without Versar-standard HAZWOPER baselines.",
    },
  ],
  curveTitle: "Versar HAZWOPER, UXO, DBA, and PE-exit risk curve",
  curveSubtitle:
    "Uploaded Occu-Med intelligence values normalized for entity-profile scanning; modeled estimates should be treated as assumption-driven signals, not audited employer disclosures.",
  chartDefinitions: [
    {
      id: "versar-injury-cost-by-workforce",
      title: "Versar expected annual injury costs by workforce",
      subtitle: "Uploaded chart/page 8: injury-cost exposure by field-heavy worker category, shown in $K.",
      type: "bar",
      xKey: "category",
      data: [
        { category: "HTRW Field", injuries: 8.5, cost: 620 },
        { category: "Munitions / UXO", injuries: 6, cost: 390 },
        { category: "Construction Mgmt", injuries: 2, cost: 200 },
        { category: "Security Systems", injuries: 1, cost: 65 },
        { category: "IT / Cyber", injuries: 0.5, cost: 40 },
      ],
      series: [{ dataKey: "cost", name: "Estimated annual cost", color: "#f97316", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "injury cost",
      fullWidth: true,
    },
    {
      id: "versar-worker-trir-benchmarks",
      title: "Versar BLS TRIR benchmarks by worker category",
      subtitle: "Uploaded table/pages 7-8: UXO and HTRW field work carry the highest modeled injury risk.",
      type: "bar",
      xKey: "category",
      data: [
        { category: "HTRW Field", trir: 1.7 },
        { category: "Munitions / UXO", trir: 3.0 },
        { category: "Construction Mgmt", trir: 1.0 },
        { category: "Security Systems", trir: 1.1 },
        { category: "IT / Cyber", trir: 0.5 },
      ],
      series: [{ dataKey: "trir", name: "BLS / analog TRIR", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 4],
      headline: "worker risk",
    },
    {
      id: "versar-hazwoper-revenue",
      title: "Versar HAZWOPER mandatory exam revenue potential",
      subtitle: "Uploaded chart/page 9 and table/page 10: recurring annual revenue for federally mandated HAZWOPER exams.",
      type: "bar",
      xKey: "scenario",
      data: [
        { scenario: "Conservative", workers: 800, fee: 350, revenue: 280 },
        { scenario: "Mid-range", workers: 900, fee: 450, revenue: 405 },
        { scenario: "Full scope", workers: 1000, fee: 600, revenue: 600 },
      ],
      series: [{ dataKey: "revenue", name: "Annual mandatory revenue", color: "#22c55e", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "HAZWOPER revenue",
      fullWidth: true,
    },
    {
      id: "versar-pe-exit-value",
      title: "Safety savings to PE exit value",
      subtitle: "Uploaded chart/page 12: recurring cost reduction multiplied by 8x and 10x EBITDA exit multiples.",
      type: "stacked",
      xKey: "scenario",
      data: [
        { scenario: "25% TRIR reduction", at8x: 3.6, add10x: 0.9 },
        { scenario: "33% TRIR reduction", at8x: 4.8, add10x: 1.2 },
        { scenario: "50% TRIR reduction", at8x: 7.2, add10x: 1.8 },
      ],
      series: [
        { dataKey: "at8x", name: "8x EBITDA value", color: "#22d3ee", stackId: "value" },
        { dataKey: "add10x", name: "Additional at 10x", color: "#ef4444", stackId: "value", radius: [10, 10, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "PE exit value",
      fullWidth: true,
    },
    {
      id: "versar-oconus-cpss-revenue",
      title: "Versar Middle East CPSS OCONUS exam opportunity",
      subtitle: "Uploaded page 11: pre- and post-deployment exams for ~200 rotating OCONUS workers could produce $60K-$120K annually.",
      type: "bar",
      xKey: "scenario",
      data: [
        { scenario: "Low annual", revenue: 60 },
        { scenario: "High annual", revenue: 120 },
        { scenario: "CPSS contract value", revenue: 75000 },
      ],
      series: [{ dataKey: "revenue", name: "Revenue / contract value", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      formatter: "currencyK",
      headline: "OCONUS exams",
    },
    {
      id: "versar-compliance-gap-priority",
      title: "Versar compliance and surveillance priority map",
      subtitle: "Priority lanes derived from uploaded HAZWOPER, UXO, CPSS, and acquisition-risk sections.",
      type: "bar",
      xKey: "gap",
      data: [
        { gap: "HAZWOPER baseline", priority: 10 },
        { gap: "Inherited Louis Berger baselines", priority: 10 },
        { gap: "UXO audiometry", priority: 9 },
        { gap: "Blast exposure history", priority: 9 },
        { gap: "CWM toxicology", priority: 8 },
        { gap: "CENTCOM heat readiness", priority: 8 },
        { gap: "DBA pre/post deploy", priority: 8 },
        { gap: "Psych resilience", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Priority score", color: "#ef4444", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "compliance map",
    },
  ],
  metricDefinitions: [
    { id: "versar-employees", label: "Employees", value: 2000, unit: "count", category: "workforce" },
    { id: "versar-field-workers", label: "Field + field support workers", value: 1100, unit: "count", category: "workforce" },
    { id: "versar-expected-injuries", label: "Expected injuries/yr", value: 18, unit: "count", category: "safety" },
    { id: "versar-direct-cost-low", label: "Direct injury cost low", value: 1.1, unit: "usd", category: "financial" },
    { id: "versar-direct-cost-high", label: "Direct injury cost high", value: 1.7, unit: "usd", category: "financial" },
    { id: "versar-total-cost-high", label: "Total cost high with indirect", value: 8.5, unit: "usd", category: "financial" },
    { id: "versar-hazwoper-revenue-high", label: "HAZWOPER recurring revenue high", value: 0.6, unit: "usd", category: "financial" },
    { id: "versar-inherited-workers", label: "Inherited WSP/Louis Berger workers", value: 1400, unit: "count", category: "risk" },
    { id: "versar-cpss-contract", label: "Middle East CPSS contract", value: 75, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "HTRW field workers", revenue: 0.72, risk: 8.5, workers: 500 },
    { name: "Munitions / UXO crews", revenue: 0.6, risk: 10.0, workers: 200 },
    { name: "OCONUS construction mgmt", revenue: 75.0, risk: 8.0, workers: 200 },
    { name: "Security systems", revenue: 0.1, risk: 5.0, workers: 100 },
    { name: "IT / Cyber / BayFirst", revenue: 0.05, risk: 2.5, workers: 100 },
  ],
  opportunityMatrix: [
    { name: "HAZWOPER Annual Physicals", revenuePotential: 600, implementationComplexity: 7, strategicValue: 10 },
    { name: "Inherited Baseline Catch-Up", revenuePotential: 840, implementationComplexity: 8, strategicValue: 10 },
    { name: "UXO Audiometry / Blast Baseline", revenuePotential: 140, implementationComplexity: 7, strategicValue: 9 },
    { name: "CWM Toxicology Panels", revenuePotential: 160, implementationComplexity: 9, strategicValue: 9 },
    { name: "CPSS DBA Pre/Post Deployment", revenuePotential: 120, implementationComplexity: 6, strategicValue: 8 },
    { name: "Heat Readiness Protocol", revenuePotential: 90, implementationComplexity: 7, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Versar is a PE-owned environmental and munitions response entity where the key sales frame is not commodity physicals. The report frames Versar around OSHA compliance exposure, inherited baseline gaps, PE exit value, and mandatory HAZWOPER medical surveillance.",
      bullets: [
        "PE-owned by Kingswood Capital, with estimated revenue around $400M-$500M and roughly 2,000 employees.",
        "Field + field support population is modeled at roughly 1,100 workers and 17-18 expected injuries per year.",
        "Direct injury cost is modeled at $1.1M-$1.7M annually, rising to $2.2M-$8.5M with indirect costs.",
        "Because Versar is PE-owned, recurring safety savings can multiply into exit value at 8x-10x EBITDA.",
      ],
      metricIds: ["versar-employees", "versar-field-workers", "versar-expected-injuries", "versar-direct-cost-high"],
    },
    {
      type: "safety",
      title: "HAZWOPER mandate: largest mandatory exam obligation",
      narrative:
        "The report identifies HAZWOPER as Versar's largest mandatory medical obligation. 29 CFR 1910.120 applies to workers who handle, investigate, remediate, or respond to hazardous substances; exams are pre-placement, annual, termination, and post-exposure when applicable.",
      bullets: [
        "Conservative scenario: 800 workers at $350/exam equals $280K/year.",
        "Mid-range scenario: 900 workers at $450/exam equals $405K/year.",
        "Full-scope scenario: 1,000 workers at $600/exam equals $600K/year.",
        "Site-specific lab panels may include heavy metals, lead/arsenic, hepatic, neurological, and chlorinated solvent panels depending on site exposures.",
      ],
      metricIds: ["versar-hazwoper-revenue-high"],
    },
    {
      type: "acquisitions",
      title: "Compliance time bomb: inherited Louis Berger baselines",
      narrative:
        "The uploaded report says Versar acquired the WSP/Louis Berger engineering and environmental unit in August 2023, adding roughly 1,400 employees. The central risk is that legacy workers may not have Versar-standard HAZWOPER-compliant pre-placement baselines on file.",
      bullets: [
        "Inherited workers may have come from different occupational medicine providers and exam templates.",
        "An OSHA inspection after an incident at a legacy Louis Berger-managed HTRW site could surface missing baseline documentation.",
        "The corrective action is a post-acquisition baseline exam program for inherited HAZWOPER populations.",
        "This is an immediately actionable Occu-Med program because the exam requirement is mandatory, not discretionary.",
      ],
      metricIds: ["versar-inherited-workers"],
    },
    {
      type: "contracts",
      title: "New OCONUS exposure: $75M Middle East CPSS contract",
      narrative:
        "The report identifies the July 2025 Parsons-Versar JV award for USACE Middle East District Construction Phase Support Services as Versar's first major CENTCOM deployment under the current corporate structure.",
      bullets: [
        "Contract covers CENTCOM, Foreign Military Sales, and military construction programs across Saudi Arabia, Qatar, UAE, and Kuwait.",
        "About 200 rotating OCONUS construction-management workers may require DBA pre-deployment and post-deployment exams.",
        "CENTCOM summer temperatures can exceed 48°C / 118°F, creating cardiovascular heat-strain screening need.",
        "Pre/post deployment exams alone are modeled at $60K-$120K in annual recurring exam revenue.",
      ],
      metricIds: ["versar-cpss-contract"],
    },
    {
      type: "workforce",
      title: "Munitions workforce: highest-risk, least-protected population",
      narrative:
        "Versar's UXO/MEC crews perform live ordnance excavation and disposal under USACE EMR2 MATOC and legacy MMRP contracts. The report notes that no BLS category captures this work cleanly, so demolition/EOD analogues imply TRIR in the 3.0-4.5 range and high fatality risk.",
      bullets: [
        "Audiometric baseline and annual surveillance are critical because controlled detonations can exceed 140 dB impulse noise.",
        "Blast exposure history documentation is often absent in acquired workforces but essential for baseline defense.",
        "Chemical Warfare Materiel sites require specific toxicological screening.",
        "Psychological resilience screening is relevant because repeated ordnance exposure increases anxiety/PTSD/substance-use risk.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "PE exit multiplier",
      narrative:
        "Kingswood Capital acquired Versar in November 2017, which the report frames as beyond a standard 5-7 year PE hold period. Recurring safety savings flow directly into EBITDA and can become $3.6M-$9.0M in added enterprise value depending on improvement and exit multiple.",
      bullets: [
        "$450K annual safety savings at 8x EBITDA equals $3.6M added enterprise value; at 10x equals $4.5M.",
        "$600K annual savings at 8x equals $4.8M; at 10x equals $6.0M.",
        "$900K annual savings at 8x equals $7.2M; at 10x equals $9.0M.",
        "Clean workers' compensation records and documented OSHA compliance can also reduce due-diligence liability discounts.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med sales narrative",
      narrative:
        "The report says the conversation with Versar should center on compliance exposure, PE exit value, and the Louis Berger time bomb rather than generic physicals.",
      bullets: [
        "Ask how many inherited WSP/Louis Berger workers on active HTRW sites have Versar-standard HAZWOPER pre-placement physicals on file.",
        "Frame the cost to fix the gap as $350-$600 per worker, versus a materially larger OSHA/due-diligence liability problem.",
        "Lead with mandatory HAZWOPER annual exams, post-acquisition baseline catch-up, UXO surveillance, and CENTCOM DBA/heat-readiness protocols.",
      ],
      metricIds: [],
    },
    {
      type: "procurement",
      title: "Source and assumption handling",
      narrative:
        "Versar values in this profile are source-backed but model-driven. The charts should be interpreted as Occu-Med intelligence estimates derived from the uploaded Versar report, BLS/analog benchmarks, OSHA HAZWOPER requirements, acquisition history, DBA assumptions, and PE-exit value modeling.",
      bullets: [
        "Do not present modeled injury, HAZWOPER revenue, DBA revenue, or PE exit value as audited Versar disclosures.",
        "Validate active HAZWOPER headcount, inherited baseline status, CPSS staffing, and current occ med provider before external presentation.",
        "Preserve the uploaded report as evidence for extracted charts, tables, and sales narrative.",
      ],
      metricIds: [],
    },
  ],
  interactionConfig: {
    preset: "deep-analysis",
    enableLinkedHighlighting: true,
    enableDrillDown: true,
    enableFilters: true,
    enableZoomPan: false,
    detailPanelPosition: "right",
    defaultTransition: { enter: "fade", duration: 240, animateData: true },
    defaultFocusEffect: { type: "radiant-gradient", intensity: 0.35, radius: 280, color: "#22d3ee" },
    defaultGridEffect: { type: "concentric-ripple", amplitude: 0.12, frequency: 0.6, animate: true },
    defaultDepthLayers: true,
  },
};
