import type { CompanyConfig } from "./types";

export const weatherfordConfig: CompanyConfig = {
  companyId: "weatherford",
  displayName: "Weatherford International",
  shortName: "WFRD",
  sector: "Oilfield services, drilling support, global operations, industrial safety, and international workforce exposure",
  headquarters: "Houston, Texas",
  employees: 19000,
  employeesAsOf: "Uploaded WFRD 2024 GRI visual model",
  summary: "Weatherford has been added as an oilfield-services safety and global workforce dossier connecting record-low TRIR, international workforce concentration, geographic revenue exposure, man-hours at risk, recordable incident reduction, near-miss intensity, and revenue trend signals.",
  tags: ["Oilfield services", "Global workforce", "TRIR benchmark", "Near misses", "International revenue", "Safety performance"],
  aliases: ["Weatherford International", "WFRD"],
  sourceFilters: {
    sec: { ticker: "WFRD", legalEntities: ["Weatherford International plc"] },
    newsSources: { aliases: ["Weatherford", "WFRD"] },
  },
  executiveSignals: [
    { label: "2024 TRIR", value: "0.12", note: "Record-low TRIR shown far below OFS and drilling benchmarks." },
    { label: "Global workforce", value: "19K", note: "Uploaded visual shows approximately 19,000 employees globally." },
    { label: "International exposure", value: "81%", note: "Only 19% of workforce is shown in North America." },
    { label: "Near misses", value: "~6,380", note: "About 152 near misses per recordable injury in 2024." },
  ],
  curveTitle: "Weatherford safety and global exposure curve",
  curveSubtitle: "TRIR, international workforce, near-miss volume, recordables, and revenue peak normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "wfrd-trir-bench",
      title: "WFRD TRIR vs OFS industry benchmark",
      subtitle: "Source: uploaded Weatherford visual; TRIR per 200K hours.",
      type: "bar",
      xKey: "name",
      data: [{ name: "WFRD", value: 0.12 }, { name: "SLB est", value: 0.19 }, { name: "Baker Hughes", value: 0.22 }, { name: "Halliburton", value: 0.27 }, { name: "BLS OFS", value: 1.6 }, { name: "BLS Drilling", value: 1.9 }],
      series: [{ dataKey: "value", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 2],
      headline: "TRIR benchmark",
    },
    {
      id: "wfrd-geo-revenue",
      title: "Weatherford geographic exposure",
      subtitle: "Source: uploaded Weatherford visuals; FY2024 revenue in $M and employees by region.",
      type: "grouped",
      xKey: "name",
      data: [{ name: "MENA/Asia", revenue: 2123, employees: 6716 }, { name: "Latin America", revenue: 1393, employees: 3724 }, { name: "North America", revenue: 1046, employees: 3518 }, { name: "Europe/SSA/Russia", revenue: 951, employees: 4501 }],
      series: [
        { dataKey: "revenue", name: "Revenue ($M)", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "employees", name: "Employees", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      headline: "geographic exposure",
    },
    {
      id: "wfrd-region-trend",
      title: "Weatherford revenue by region FY2024 vs FY2025",
      subtitle: "Source: uploaded Weatherford visual; Latin America shown down 36% in 2025.",
      type: "grouped",
      xKey: "name",
      data: [{ name: "MENA/Asia", fy2024: 2123, fy2025: 2116 }, { name: "Latin America", fy2024: 1393, fy2025: 898 }, { name: "North America", fy2024: 1046, fy2025: 983 }, { name: "Europe/SSA/Russia", fy2024: 951, fy2025: 921 }],
      series: [
        { dataKey: "fy2024", name: "FY2024 ($M)", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "fy2025", name: "FY2025 ($M)", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      headline: "regional revenue",
    },
    {
      id: "wfrd-incidents",
      title: "Recordable incidents by type",
      subtitle: "Source: uploaded Weatherford safety visual; 2024 down 46% YoY vs 2023.",
      type: "stacked",
      xKey: "name",
      data: [{ name: "2020", medical: 23, restricted: 32, lost: 21 }, { name: "2021", medical: 21, restricted: 29, lost: 10 }, { name: "2022", medical: 38, restricted: 21, lost: 16 }, { name: "2023", medical: 25, restricted: 30, lost: 20 }, { name: "2024", medical: 17, restricted: 16, lost: 8 }],
      series: [
        { dataKey: "medical", name: "Medical", color: "#22d3ee", stackId: "stack" },
        { dataKey: "restricted", name: "Restricted Duty", color: "#ef4444", stackId: "stack" },
        { dataKey: "lost", name: "Lost Time", color: "#22c55e", stackId: "stack", radius: [10, 10, 0, 0] },
      ],
      headline: "incident types",
    },
    {
      id: "wfrd-man-hours",
      title: "Workforce exposure: man-hours at risk",
      subtitle: "Source: uploaded Weatherford visual; man-hours shown in millions.",
      type: "bar",
      xKey: "name",
      data: [{ name: "2020", value: 76 }, { name: "2021", value: 63 }, { name: "2022", value: 66 }, { name: "2023", value: 68.1 }, { name: "2024", value: 64.6 }],
      series: [{ dataKey: "value", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      headline: "man-hours",
    },
    {
      id: "wfrd-near-miss",
      title: "Near misses vs recordable injuries",
      subtitle: "Source: uploaded Weatherford visual; approximately 152 near misses per recordable injury.",
      type: "bar",
      xKey: "name",
      data: [{ name: "Recordables", value: 42 }, { name: "Near Misses", value: 6380 }],
      series: [{ dataKey: "value", color: "#dc2626", radius: [10, 10, 0, 0] }],
      headline: "near miss ratio",
    },
    {
      id: "wfrd-revenue-trend",
      title: "Weatherford revenue trend",
      subtitle: "Source: uploaded Weatherford visual; peak $5.5B in 2024, decline in 2025.",
      type: "area",
      xKey: "year",
      data: [{ year: "2020", revenue: 3600 }, { year: "2021", revenue: 3600 }, { year: "2022", revenue: 4300 }, { year: "2023", revenue: 5100 }, { year: "2024", revenue: 5500 }, { year: "2025", revenue: 4900 }],
      series: [{ dataKey: "revenue", color: "#22d3ee" }],
      formatter: "currencyM",
      headline: "revenue trend",
    },
    {
      id: "wfrd-trir-ltir",
      title: "Weatherford TRIR / LTIR trend",
      subtitle: "Source: uploaded Weatherford visual; TRIR and LTIR trajectory 2020-2024.",
      type: "line",
      xKey: "year",
      data: [{ year: "2020", trir: 0.2, ltir: 0.06 }, { year: "2021", trir: 0.19, ltir: 0.03 }, { year: "2022", trir: 0.24, ltir: 0.05 }, { year: "2023", trir: 0.22, ltir: 0.06 }, { year: "2024", trir: 0.12, ltir: 0.02 }],
      series: [
        { dataKey: "trir", name: "TRIR", color: "#22d3ee" },
        { dataKey: "ltir", name: "LTIR", color: "#ef4444" },
      ],
      headline: "TRIR/LTIR trend",
    },
  ],
};
