import type { CompanyConfig } from "./types";

export const weatherfordConfig: CompanyConfig = {
  companyId: "weatherford",
  displayName: "Weatherford International",
  shortName: "WFRD",
  sector: "Oilfield services, drilling support, global operations, industrial safety, H2S exposure, pressure-control work, wireline, and international workforce exposure",
  headquarters: "Houston, Texas",
  employees: 19000,
  employeesAsOf: "Uploaded Weatherford Occu-Med intelligence report: 2024 GRI / safety model",
  summary:
    "Weatherford is an oilfield-services entity with an extraordinary 2024 safety profile: 19,000 workers across 75 countries, 71 million hours, 0.12 TRIR, zero 2024 fatalities, and eight lost-time injuries. The uploaded report argues that Weatherford is not a volume-driven injury account; it is a safety-sustainment account. The key issue is that 6,380 near misses and a near-miss frequency rate of 17.87 show the underlying energy-hazard exposure remains very high even while the recordable injury rate is world-class. The Occu-Med conversation should focus on sustaining the advantage through high-quality upstream medical screening, regulatory surveillance, EMR/premium control, and severe-event readiness.",
  tags: ["Entity profile", "Weatherford", "Oilfield services", "Global workforce", "TRIR benchmark", "Near misses", "H2S", "Pressure-control", "International revenue", "Safety sustainment"],
  aliases: ["Weatherford", "Weatherford International", "WFRD", "Weatherford International plc"],
  sourceFilters: {
    sec: { ticker: "WFRD", legalEntities: ["Weatherford International plc"] },
    sam: { legalNames: ["Weatherford International", "Weatherford International plc"] },
    usaSpending: { recipientNames: ["Weatherford"] },
    newsSources: { aliases: ["Weatherford", "WFRD", "Weatherford International"] },
  },
  executiveSignals: [
    { label: "2024 TRIR", value: "0.12", note: "Record-low TRIR shown far below OFS and drilling benchmarks; uploaded report says it is 93% below the BLS benchmark." },
    { label: "Global workforce", value: "19K / 75 countries", note: "Uploaded report identifies about 19,000 employees across 75 countries." },
    { label: "North America", value: "~3,518 workers", note: "Only about 19% of the workforce is in North America; estimated recordables are about 21 per year." },
    { label: "Near misses", value: "6,380", note: "About 152 near misses per recordable injury; NMFR rose to 17.87." },
  ],
  curveTitle: "Weatherford safety-sustainment and near-miss exposure curve",
  curveSubtitle: "TRIR, global workforce, near-miss volume, recordables, and revenue signals normalized for executive scanning.",
  chartDefinitions: [
    {
      id: "wfrd-trir-bench",
      title: "WFRD TRIR vs OFS industry benchmark",
      subtitle: "Source: uploaded Weatherford report; TRIR per 200K hours.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "WFRD", value: 0.12 },
        { name: "SLB est", value: 0.19 },
        { name: "Baker Hughes", value: 0.22 },
        { name: "Halliburton", value: 0.27 },
        { name: "BLS OFS", value: 1.6 },
        { name: "BLS Drilling", value: 1.9 },
      ],
      series: [{ dataKey: "value", name: "TRIR", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 2],
      headline: "TRIR benchmark",
    },
    {
      id: "wfrd-geo-revenue",
      title: "Weatherford geographic exposure",
      subtitle: "Source: uploaded Weatherford report; FY2024 revenue in $M and employees by region.",
      type: "grouped",
      xKey: "name",
      data: [
        { name: "MENA/Asia", revenue: 2123, employees: 6716 },
        { name: "Latin America", revenue: 1393, employees: 3724 },
        { name: "North America", revenue: 1046, employees: 3518 },
        { name: "Europe/SSA/Russia", revenue: 951, employees: 4501 },
      ],
      series: [
        { dataKey: "revenue", name: "Revenue ($M)", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "employees", name: "Employees", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      headline: "geographic exposure",
      fullWidth: true,
    },
    {
      id: "wfrd-near-miss",
      title: "Near misses vs recordable injuries",
      subtitle: "Uploaded report: roughly 152 near misses per recordable injury, with NMFR rising.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "Recordables", value: 42 },
        { name: "Near Misses", value: 6380 },
      ],
      series: [{ dataKey: "value", name: "Events", color: "#dc2626", radius: [10, 10, 0, 0] }],
      headline: "near miss ratio",
      fullWidth: true,
    },
    {
      id: "wfrd-incidents",
      title: "Recordable incidents by type",
      subtitle: "Source: uploaded Weatherford safety model; 2024 recordables down sharply year over year.",
      type: "stacked",
      xKey: "name",
      data: [
        { name: "2020", medical: 23, restricted: 32, lost: 21 },
        { name: "2021", medical: 21, restricted: 29, lost: 10 },
        { name: "2022", medical: 38, restricted: 21, lost: 16 },
        { name: "2023", medical: 25, restricted: 30, lost: 20 },
        { name: "2024", medical: 17, restricted: 16, lost: 8 },
      ],
      series: [
        { dataKey: "medical", name: "Medical", color: "#22d3ee", stackId: "stack" },
        { dataKey: "restricted", name: "Restricted Duty", color: "#ef4444", stackId: "stack" },
        { dataKey: "lost", name: "Lost Time", color: "#22c55e", stackId: "stack", radius: [10, 10, 0, 0] },
      ],
      headline: "incident types",
    },
    {
      id: "wfrd-region-trend",
      title: "Weatherford revenue by region FY2024 vs FY2025",
      subtitle: "Uploaded model: Latin America revenue shown down materially in 2025.",
      type: "grouped",
      xKey: "name",
      data: [
        { name: "MENA/Asia", fy2024: 2123, fy2025: 2116 },
        { name: "Latin America", fy2024: 1393, fy2025: 898 },
        { name: "North America", fy2024: 1046, fy2025: 983 },
        { name: "Europe/SSA/Russia", fy2024: 951, fy2025: 921 },
      ],
      series: [
        { dataKey: "fy2024", name: "FY2024 ($M)", color: "#22d3ee", radius: [10, 10, 0, 0] },
        { dataKey: "fy2025", name: "FY2025 ($M)", color: "#ef4444", radius: [10, 10, 0, 0] },
      ],
      headline: "regional revenue",
    },
    {
      id: "wfrd-sustainment-priority",
      title: "Weatherford Occu-Med sustainment priority map",
      subtitle: "The opportunity is protecting an exceptional safety system, not fixing a broken one.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "H2S / toxic exposure readiness", priority: 10 },
        { lane: "Pressure-control fitness", priority: 9 },
        { lane: "Remote-location medical", priority: 9 },
        { lane: "Near-miss medical analytics", priority: 8 },
        { lane: "Driver / rollover readiness", priority: 8 },
        { lane: "EMR / premium protection", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "sustainment lanes",
    },
  ],
  metricDefinitions: [
    { id: "wfrd-employees", label: "Employees", value: 19000, unit: "count", category: "workforce" },
    { id: "wfrd-north-america-workers", label: "North America workers", value: 3518, unit: "count", category: "workforce" },
    { id: "wfrd-trir", label: "2024 TRIR", value: 0.12, unit: "score", category: "safety" },
    { id: "wfrd-lost-time", label: "2024 lost-time injuries", value: 8, unit: "count", category: "safety" },
    { id: "wfrd-near-misses", label: "Near misses", value: 6380, unit: "count", category: "safety" },
    { id: "wfrd-nmfr", label: "Near miss frequency rate", value: 17.87, unit: "score", category: "safety" },
    { id: "wfrd-na-recordables", label: "Estimated NA recordables", value: 21, unit: "count", category: "safety" },
  ],
  riskMatrix: [
    { name: "H2S / toxic exposure", revenue: 500, risk: 9.5, workers: 1200 },
    { name: "Pressure-control operations", revenue: 450, risk: 9.0, workers: 1500 },
    { name: "Remote drilling locations", revenue: 350, risk: 8.5, workers: 1800 },
    { name: "Vehicle / rollover exposure", revenue: 250, risk: 8.0, workers: 2000 },
    { name: "North America recordables", revenue: 21, risk: 5.0, workers: 3518 },
  ],
  opportunityMatrix: [
    { name: "H2S / toxic exposure screening", revenuePotential: 350, implementationComplexity: 7, strategicValue: 9 },
    { name: "Remote-location fitness", revenuePotential: 300, implementationComplexity: 6, strategicValue: 8 },
    { name: "Pressure-control medical", revenuePotential: 250, implementationComplexity: 7, strategicValue: 9 },
    { name: "Near-miss medical analytics", revenuePotential: 200, implementationComplexity: 8, strategicValue: 8 },
    { name: "EMR / premium support", revenuePotential: 150, implementationComplexity: 5, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Weatherford should be approached as a world-class safety sustainment account. The uploaded report says the TRIR is exceptional and externally assured, but the near-miss pool proves the hazard environment remains active.",
      bullets: [
        "2024 TRIR of 0.12 is about 93% below the BLS oil and gas field services benchmark.",
        "Weatherford operates across approximately 75 countries with 19,000 workers.",
        "Only about 19% of the workforce is in North America, roughly 3,518 workers.",
        "North America recordable injury burden is estimated at about 21 cases per year.",
      ],
      metricIds: ["wfrd-employees", "wfrd-trir", "wfrd-north-america-workers"],
    },
    {
      type: "safety",
      title: "Near-miss intensity is the leading signal",
      narrative:
        "The uploaded report identifies the near-miss number as the real alarm. The ratio of near misses to recordables shows a mature reporting culture, but also a large pool of serious hazards being intercepted before injury.",
      bullets: [
        "Weatherford reported approximately 6,380 near misses against 42 recordable injuries.",
        "That is about 152 near misses per recordable injury.",
        "The near-miss frequency rate of 17.87 increased from 2023.",
        "The next major loss event is most likely to emerge from this near-miss exposure pool.",
      ],
      metricIds: ["wfrd-near-misses", "wfrd-nmfr"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "Given Weatherford's small North American injury burden and excellent TRIR, the pitch should not be volume. It should be quality, regulatory surveillance, EMR/premium control, and protection of a safety advantage.",
      bullets: [
        "The correct message is sustaining the extraordinary, not fixing the broken.",
        "Priority lanes include H2S exposure, pressure-control fitness, remote-location readiness, vehicle/rollover medical readiness, and near-miss medical analytics.",
        "The financial frame should center on EMR and premium control rather than direct self-insured reserves.",
      ],
      metricIds: ["wfrd-na-recordables"],
    },
  ],
};
