import type { CompanyConfig } from "./types";

export const weatherfordConfig: CompanyConfig = {
  companyId: "weatherford",
  displayName: "Weatherford International plc",
  shortName: "WFRD",
  sector:
    "Oilfield services, drilling and evaluation, well construction and completions, production and intervention, global operations, H2S exposure, pressure-control work, wireline, high-pressure equipment, and international workforce exposure",
  headquarters: "Houston, Texas / incorporated in Ireland",
  employees: 17000,
  employeesAsOf: "Uploaded Weatherford International full Occu-Med report: February 19, 2026; approximately 17,000 employees across 75 countries and 330 operating locations",
  summary:
    "Weatherford International plc is a global oilfield services company headquartered in Houston and incorporated in Ireland, operating in approximately 75 countries through 330 operating locations with about 17,000 employees across 110+ nationalities. The uploaded full Weatherford report corrects the account framing: Weatherford is roughly one-third the size of Amentum by revenue but operates in an entirely different hazard universe — oil and gas field services, not defense services. FY2024 revenue reached $5.513B before declining to about $4.918B in FY2025, driven by Latin America and North America softness. The safety story remains exceptional: 2024 TRIR of 0.12, LTIR of 0.02, and only 41 recordable incidents across 64.65M man-hours. The Occu-Med play is not fixing a broken safety program; it is sustaining a world-class safety performer in high-hazard oilfield work through high-quality pre-placement, surveillance, H2S/chemical readiness, remote-location fitness, EMR/premium support, and near-miss-driven medical analytics.",
  tags: [
    "Entity profile",
    "Weatherford",
    "Oilfield services",
    "Global workforce",
    "TRIR 0.12",
    "LTIR 0.02",
    "H2S",
    "Pressure-control",
    "Wireline",
    "Well construction",
    "MENA/Asia",
    "Saudi Arabia",
    "Mexico",
    "Bakersfield",
    "Safety sustainment",
  ],
  aliases: ["Weatherford", "Weatherford International", "WFRD", "Weatherford International plc"],
  sourceFilters: {
    sec: { ticker: "WFRD", legalEntities: ["Weatherford International plc"] },
    sam: { legalNames: ["Weatherford International", "Weatherford International plc"] },
    usaSpending: { recipientNames: ["Weatherford"] },
    newsSources: { aliases: ["Weatherford", "WFRD", "Weatherford International", "Pemex", "Bakersfield Weatherford"] },
  },
  executiveSignals: [
    { label: "2024 TRIR", value: "0.12", note: "Breakout safety year: 41 total recordables across 64.65M man-hours." },
    { label: "FY2024 revenue", value: "$5.513B", note: "FY2024 peak revenue before FY2025 decline to about $4.918B." },
    { label: "Global footprint", value: "75 countries / 330 sites", note: "Full report identifies 330 operating locations including manufacturing, R&D, service, and training facilities." },
    { label: "International mix", value: "81%", note: "81% of FY2024 revenue was outside North America; MENA/Asia alone represented about 39%." },
  ],
  curveTitle: "Weatherford global oilfield safety-sustainment curve",
  curveSubtitle:
    "Full uploaded Weatherford report normalized into an entity profile; values are strategic account intelligence and should be refreshed against current WFRD disclosures before external use.",
  chartDefinitions: [
    {
      id: "wfrd-revenue-trend",
      title: "Weatherford revenue peak and FY2025 decline",
      subtitle: "Uploaded report: FY2024 revenue peaked at $5.513B before FY2025 declined to about $4.918B.",
      type: "line",
      xKey: "year",
      data: [
        { year: "2020", revenue: 3.0 },
        { year: "2021", revenue: 3.0 },
        { year: "2022", revenue: 4.3 },
        { year: "2023", revenue: 5.1 },
        { year: "2024", revenue: 5.513 },
        { year: "2025", revenue: 4.918 },
      ],
      series: [{ dataKey: "revenue", name: "Revenue", color: "#22d3ee" }],
      formatter: "currencyM",
      headline: "revenue trend",
      fullWidth: true,
    },
    {
      id: "wfrd-segment-revenue",
      title: "Weatherford FY2024 segment revenue and hazard profile",
      subtitle: "Drilling & Evaluation, Well Construction & Completions, and Production & Intervention carry distinct exam protocols.",
      type: "bar",
      xKey: "segment",
      data: [
        { segment: "Drilling & Evaluation", revenue: 1581, hazardPriority: 9 },
        { segment: "Well Construction & Completions", revenue: 2017, hazardPriority: 10 },
        { segment: "Production & Intervention", revenue: 1401, hazardPriority: 8 },
      ],
      series: [{ dataKey: "revenue", name: "FY2024 revenue", color: "#22c55e", radius: [10, 10, 0, 0] }],
      formatter: "currencyM",
      headline: "segments",
    },
    {
      id: "wfrd-geo-revenue",
      title: "Weatherford geographic revenue mix FY2024",
      subtitle: "Uploaded report: 81% international, with MENA/Asia at about 39% of total revenue.",
      type: "bar",
      xKey: "region",
      data: [
        { region: "MENA/Asia", fy2024: 2123, fy2025: 2116, percent2024: 39 },
        { region: "Latin America", fy2024: 1393, fy2025: 898, percent2024: 25 },
        { region: "North America", fy2024: 1046, fy2025: 983, percent2024: 19 },
        { region: "Europe/SSA/Russia", fy2024: 951, fy2025: 921, percent2024: 17 },
      ],
      series: [
        { dataKey: "fy2024", name: "FY2024 revenue", color: "#22d3ee", radius: [8, 8, 0, 0] },
        { dataKey: "fy2025", name: "FY2025 revenue", color: "#ef4444", radius: [8, 8, 0, 0] },
      ],
      formatter: "currencyM",
      headline: "geography",
      fullWidth: true,
    },
    {
      id: "wfrd-safety-trend",
      title: "Weatherford safety performance trend 2020-2024",
      subtitle: "Uploaded full report: recordables fell 46%, lost-time incidents fell 62%, TRIR fell 40%, and LTIR fell 67% over five years.",
      type: "line",
      xKey: "year",
      data: [
        { year: "2020", trir: 0.20, ltir: 0.06, recordables: 76, lostTime: 21 },
        { year: "2021", trir: 0.19, ltir: 0.03, recordables: 60, lostTime: 10 },
        { year: "2022", trir: 0.24, ltir: 0.05, recordables: 75, lostTime: 16 },
        { year: "2023", trir: 0.22, ltir: 0.06, recordables: 75, lostTime: 20 },
        { year: "2024", trir: 0.12, ltir: 0.02, recordables: 41, lostTime: 8 },
      ],
      series: [
        { dataKey: "trir", name: "TRIR", color: "#22c55e" },
        { dataKey: "ltir", name: "LTIR", color: "#22d3ee" },
      ],
      domain: [0, 0.3],
      headline: "safety trend",
      fullWidth: true,
    },
    {
      id: "wfrd-recordables-trend",
      title: "Weatherford recordable and lost-time incident trend",
      subtitle: "The 2024 breakout year produced only 41 recordables and 8 lost-time incidents.",
      type: "bar",
      xKey: "year",
      data: [
        { year: "2020", recordables: 76, lostTime: 21 },
        { year: "2021", recordables: 60, lostTime: 10 },
        { year: "2022", recordables: 75, lostTime: 16 },
        { year: "2023", recordables: 75, lostTime: 20 },
        { year: "2024", recordables: 41, lostTime: 8 },
      ],
      series: [
        { dataKey: "recordables", name: "Recordables", color: "#ef4444", radius: [8, 8, 0, 0] },
        { dataKey: "lostTime", name: "Lost time", color: "#f97316", radius: [8, 8, 0, 0] },
      ],
      headline: "incident trend",
    },
    {
      id: "wfrd-near-miss",
      title: "Near misses vs recordable injuries",
      subtitle: "Prior uploaded Weatherford model: near-miss intensity is the real leading indicator even with world-class TRIR.",
      type: "bar",
      xKey: "name",
      data: [
        { name: "Recordables", value: 41 },
        { name: "Near Misses", value: 6380 },
      ],
      series: [{ dataKey: "value", name: "Events", color: "#dc2626", radius: [10, 10, 0, 0] }],
      headline: "near-miss ratio",
      fullWidth: true,
    },
    {
      id: "wfrd-location-signals",
      title: "Location signals that matter to Occu-Med",
      subtitle: "International concentration plus nearby Bakersfield operating sites define the practical network strategy.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "MENA/Asia", priority: 10 },
        { location: "Saudi Arabia", priority: 10 },
        { location: "Mexico", priority: 8 },
        { location: "Bakersfield CA", priority: 9 },
        { location: "North America", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "location signals",
    },
    {
      id: "wfrd-sustainment-priority",
      title: "Weatherford Occu-Med sustainment priority map",
      subtitle: "The opportunity is protecting an exceptional safety system, not fixing a broken one.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "H2S / toxic exposure readiness", priority: 10 },
        { lane: "Pressure-control fitness", priority: 9 },
        { lane: "Remote-location medical", priority: 9 },
        { lane: "Near-miss medical analytics", priority: 8 },
        { lane: "Driver / rollover readiness", priority: 8 },
        { lane: "EMR / premium protection", priority: 7 },
        { lane: "Bakersfield provider network", priority: 8 },
      ],
      series: [{ dataKey: "priority", name: "Priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "sustainment lanes",
    },
  ],
  metricDefinitions: [
    { id: "wfrd-employees", label: "Employees", value: 17000, unit: "count", category: "workforce" },
    { id: "wfrd-countries", label: "Countries", value: 75, unit: "count", category: "workforce" },
    { id: "wfrd-operating-locations", label: "Operating locations", value: 330, unit: "count", category: "workforce" },
    { id: "wfrd-revenue-2024", label: "FY2024 revenue", value: 5.513, unit: "usd", category: "financial" },
    { id: "wfrd-revenue-2025", label: "FY2025 revenue", value: 4.918, unit: "usd", category: "financial" },
    { id: "wfrd-trir", label: "2024 TRIR", value: 0.12, unit: "score", category: "safety" },
    { id: "wfrd-ltir", label: "2024 LTIR", value: 0.02, unit: "score", category: "safety" },
    { id: "wfrd-recordables", label: "2024 recordables", value: 41, unit: "count", category: "safety" },
    { id: "wfrd-lost-time", label: "2024 lost-time injuries", value: 8, unit: "count", category: "safety" },
    { id: "wfrd-man-hours", label: "2024 man-hours at risk", value: 64.65, unit: "count", category: "workforce" },
    { id: "wfrd-near-misses", label: "Near misses", value: 6380, unit: "count", category: "safety" },
    { id: "wfrd-mena-revenue", label: "MENA/Asia FY2024 revenue", value: 2.123, unit: "usd", category: "financial" },
    { id: "wfrd-na-revenue", label: "North America FY2024 revenue", value: 1.046, unit: "usd", category: "financial" },
  ],
  riskMatrix: [
    { name: "H2S / toxic exposure", revenue: 350, risk: 9.5, workers: 1200 },
    { name: "Well construction pinch/crush", revenue: 2017, risk: 9.0, workers: 6000 },
    { name: "Pressure-control operations", revenue: 250, risk: 9.0, workers: 1500 },
    { name: "Remote drilling locations", revenue: 300, risk: 8.5, workers: 1800 },
    { name: "Bakersfield / Kern County", revenue: 150, risk: 7.0, workers: 300 },
  ],
  opportunityMatrix: [
    { name: "H2S / toxic exposure screening", revenuePotential: 350, implementationComplexity: 7, strategicValue: 9 },
    { name: "Remote-location fitness", revenuePotential: 300, implementationComplexity: 6, strategicValue: 8 },
    { name: "Pressure-control medical", revenuePotential: 250, implementationComplexity: 7, strategicValue: 9 },
    { name: "Near-miss medical analytics", revenuePotential: 200, implementationComplexity: 8, strategicValue: 8 },
    { name: "Bakersfield network expansion", revenuePotential: 150, implementationComplexity: 4, strategicValue: 8 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "Weatherford is a global oilfield services account, not a defense-contracting analogue. The full uploaded report emphasizes that the hazard profile, workers' compensation class logic, regulatory environment, and exam protocols are fundamentally different from Amentum, CACI, or V2X.",
      bullets: [
        "Approximately 17,000 employees across 75 countries and 330 operating locations.",
        "FY2024 revenue was $5.513B, followed by FY2025 revenue of approximately $4.918B.",
        "Business segments are Drilling & Evaluation, Well Construction & Completions, and Production & Intervention.",
        "Oilfield hazards include falls, struck-by, confined space, chemical exposure, noise, crush injuries, torque/pinch points, electrical, high-pressure releases, and remote-location work.",
      ],
      metricIds: ["wfrd-employees", "wfrd-countries", "wfrd-operating-locations", "wfrd-revenue-2024"],
    },
    {
      type: "locations",
      title: "Geographic footprint and nearby provider opportunity",
      narrative:
        "The uploaded report says 81% of Weatherford's FY2024 revenue was international. For a U.S.-based provider network, North America volume and U.S. training/pre-deployment touchpoints matter most, especially Bakersfield, California, which is close enough to Fresno to be strategically actionable.",
      bullets: [
        "MENA/Asia represented approximately $2.123B, or about 39% of FY2024 revenue.",
        "Latin America represented about $1.393B in FY2024 but declined sharply in FY2025.",
        "North America represented about $1.046B in FY2024 and about $983M in FY2025.",
        "The report identifies active Weatherford locations in Bakersfield, California serving Kern County oilfield operations.",
      ],
      metricIds: ["wfrd-mena-revenue", "wfrd-na-revenue"],
    },
    {
      type: "safety",
      title: "Best safety performer in the portfolio conversation",
      narrative:
        "The full Weatherford report calls the safety record extraordinary. The 2024 TRIR of 0.12 is the lowest in the report's five-year table, with only 41 recordables and 8 lost-time injuries across 64.65M man-hours at risk.",
      bullets: [
        "TRIR fell from 0.20 in 2020 to 0.12 in 2024.",
        "Lost Time Incident Rate fell from 0.06 in 2020 to 0.02 in 2024.",
        "Total recordable incidents fell from 76 in 2020 to 41 in 2024.",
        "Lost-time incidents fell from 21 in 2020 to 8 in 2024.",
      ],
      metricIds: ["wfrd-trir", "wfrd-ltir", "wfrd-recordables", "wfrd-lost-time"],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "The correct account frame is safety sustainment. Weatherford already looks excellent on paper, so the Occu-Med pitch should be about protecting the advantage, supporting EMR/premium control, and using medical surveillance to keep high-hazard work from becoming a severe-event story.",
      bullets: [
        "Prioritize H2S/toxic exposure readiness, pressure-control fitness, remote-location fitness, hearing/respiratory surveillance, and near-miss medical analytics.",
        "Use Bakersfield/Kern County as a practical local network buildout point for California oilfield operations.",
        "Do not pitch this as basic injury-volume reduction; pitch it as preventing the next severe event inside a world-class safety system.",
      ],
      metricIds: ["wfrd-near-misses"],
    },
  ],
};
