import type { CompanyConfig } from "./types";

export const worldVisionConfig: CompanyConfig = {
  companyId: "world-vision",
  displayName: "World Vision International",
  shortName: "World Vision",
  sector:
    "International NGO operations, humanitarian relief, emergency response, child protection, WASH, health and education programs, regional hubs, donor operations, logistics, field offices, and global provider-network planning",
  headquarters: "Global humanitarian organization / uploaded location file lists support, national, regional, and field offices",
  employees: 0,
  employeesAsOf:
    "Uploaded World Vision location table: country/city facility and service-type rows across national offices, regional hubs, support offices, field offices, humanitarian logistics, and program sites",
  summary:
    "World Vision International is represented in the uploaded files as a global NGO / humanitarian entity with a wide international office and field-program footprint. The uploaded location table lists national offices, support offices, regional hubs, humanitarian development hubs, project implementation offices, emergency relief hubs, protection/WASH/food security programs, regional logistics hubs, and international humanitarian logistics nodes. For Insight Hub, this profile matters less as a conventional employer-injury account and more as a provider-network, international referral, and NGO field-operations footprint: World Vision locations overlap with countries and cities that already matter to Occu-Med's global network strategy, including Nairobi, Addis Ababa, Kinshasa, Baghdad/Erbil, Nicosia, Brindisi, Chennai, Quezon City, Accra, Beirut, and other humanitarian field locations.",
  tags: [
    "Entity profile",
    "World Vision",
    "International NGO",
    "Humanitarian relief",
    "WASH",
    "Child protection",
    "Field offices",
    "Regional hubs",
    "Emergency response",
    "Provider network",
    "Global footprint",
    "NGO operations",
  ],
  aliases: ["World Vision", "World Vision International", "World Vision Intl.", "WVI"],
  sourceFilters: {
    sam: { legalNames: ["World Vision International", "World Vision"] },
    usaSpending: { recipientNames: ["World Vision", "World Vision International"] },
    jobSources: { linkedin: "world-vision", careerSite: "https://www.wvi.org/careers" },
    newsSources: {
      aliases: ["World Vision International", "World Vision", "WVI", "World Vision humanitarian response"],
    },
  },
  executiveSignals: [
    {
      label: "Footprint type",
      value: "Global NGO",
      note: "Uploaded table lists national offices, regional hubs, support offices, field offices, and emergency/project implementation locations.",
    },
    {
      label: "Major hub examples",
      value: "Nairobi / Addis / Kinshasa",
      note: "Uploaded tables identify East Africa, Ethiopia, and DRC locations with national/regional or strategic administration roles.",
    },
    {
      label: "Iraq signal",
      value: "Baghdad / Erbil",
      note: "World Vision file lists Iraq national office / conflict response / MHPSS activity in Baghdad and Erbil.",
    },
    {
      label: "Network value",
      value: "International coverage",
      note: "Useful as global provider-network planning data, especially where NGO field locations overlap with defense or contractor footprints.",
    },
  ],
  curveTitle: "World Vision global humanitarian footprint and provider-network curve",
  curveSubtitle:
    "Uploaded World Vision location table normalized into an entity profile. Facility/service rows are planning signals and should be validated before outreach or scheduling use.",
  chartDefinitions: [
    {
      id: "world-vision-facility-types",
      title: "World Vision facility / service type priority",
      subtitle: "The uploaded table includes national offices, support offices, regional hubs, field program offices, logistics hubs, and emergency response locations.",
      type: "bar",
      xKey: "facilityType",
      data: [
        { facilityType: "National offices", priority: 10 },
        { facilityType: "Regional hubs", priority: 9 },
        { facilityType: "Emergency relief", priority: 9 },
        { facilityType: "Protection / WASH", priority: 8 },
        { facilityType: "Logistics hubs", priority: 8 },
        { facilityType: "Support offices", priority: 6 },
        { facilityType: "Project implementation", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Network priority", color: "#22d3ee", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "facility types",
      fullWidth: true,
    },
    {
      id: "world-vision-regional-hubs",
      title: "High-value regional and field hubs from uploaded table",
      subtitle: "Selected locations that matter because they appear as regional, national, conflict response, logistics, or large-scale relief nodes.",
      type: "bar",
      xKey: "location",
      data: [
        { location: "Nairobi Kenya", priority: 10 },
        { location: "Addis Ababa Ethiopia", priority: 9 },
        { location: "Kinshasa DRC", priority: 9 },
        { location: "Baghdad / Erbil Iraq", priority: 9 },
        { location: "Brindisi Italy", priority: 8 },
        { location: "Nicosia Cyprus", priority: 8 },
        { location: "Accra Ghana", priority: 8 },
        { location: "Chennai India", priority: 7 },
        { location: "Quezon City Philippines", priority: 7 },
        { location: "Beirut Lebanon", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Provider-network priority", color: "#22c55e", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "global hubs",
    },
    {
      id: "world-vision-operational-risk",
      title: "World Vision operational medical-support lanes",
      subtitle: "NGO/humanitarian field operations create different medical support logic than defense manufacturing or IT services.",
      type: "bar",
      xKey: "lane",
      data: [
        { lane: "Field travel readiness", priority: 9 },
        { lane: "Vaccination / travel medicine", priority: 9 },
        { lane: "MHPSS / conflict response", priority: 8 },
        { lane: "Emergency response clearance", priority: 8 },
        { lane: "WASH / field exposure", priority: 7 },
        { lane: "Ergonomics / admin hubs", priority: 5 },
      ],
      series: [{ dataKey: "priority", name: "Occu-Med planning priority", color: "#a78bfa", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "medical lanes",
    },
    {
      id: "world-vision-overlap-relevance",
      title: "World Vision overlap relevance to network expansion",
      subtitle: "Locations overlap with existing defense, NGO, and international provider-network priorities from the uploaded common-location files.",
      type: "bar",
      xKey: "overlap",
      data: [
        { overlap: "East Africa hubs", priority: 10 },
        { overlap: "Iraq conflict response", priority: 9 },
        { overlap: "Philippines / APAC", priority: 8 },
        { overlap: "Cyprus / MENA regional", priority: 8 },
        { overlap: "Italy logistics", priority: 8 },
        { overlap: "India operations", priority: 7 },
      ],
      series: [{ dataKey: "priority", name: "Overlap priority", color: "#f97316", radius: [10, 10, 0, 0] }],
      domain: [0, 10],
      headline: "network overlap",
      fullWidth: true,
    },
  ],
  metricDefinitions: [
    { id: "world-vision-priority-hubs", label: "Priority hub examples", value: 10, unit: "count", category: "workforce" },
    { id: "world-vision-facility-types", label: "Modeled facility types", value: 7, unit: "count", category: "workforce" },
    { id: "world-vision-network-fit", label: "Network planning fit", value: 9, unit: "score", category: "financial" },
    { id: "world-vision-field-risk", label: "Field-readiness priority", value: 9, unit: "score", category: "risk" },
  ],
  riskMatrix: [
    { name: "Conflict response / MHPSS", revenue: 9, risk: 8.5, workers: 500 },
    { name: "Emergency relief / WASH", revenue: 8, risk: 8.0, workers: 700 },
    { name: "Regional hubs", revenue: 7, risk: 6.5, workers: 500 },
    { name: "National offices", revenue: 6, risk: 5.0, workers: 1000 },
    { name: "Support offices", revenue: 4, risk: 3.5, workers: 300 },
  ],
  opportunityMatrix: [
    { name: "International Provider-Network Mapping", revenuePotential: 150, implementationComplexity: 8, strategicValue: 9 },
    { name: "Travel / Deployment Readiness", revenuePotential: 120, implementationComplexity: 6, strategicValue: 8 },
    { name: "Vaccination / Field Medicine", revenuePotential: 100, implementationComplexity: 5, strategicValue: 8 },
    { name: "Conflict-Response Baseline Program", revenuePotential: 90, implementationComplexity: 7, strategicValue: 8 },
    { name: "Regional Hub Clinic Coverage", revenuePotential: 80, implementationComplexity: 6, strategicValue: 7 },
  ],
  dossierSections: [
    {
      type: "overview",
      title: "Entity overview",
      narrative:
        "World Vision International enters Insight Hub as an NGO/global humanitarian footprint entity. The uploaded data is location-heavy rather than injury-rate-heavy, so the correct use is provider-network and international-readiness planning.",
      bullets: [
        "The uploaded table lists national offices, support offices, regional hubs, emergency relief locations, project implementation sites, and logistics hubs.",
        "Representative locations include Nairobi, Addis Ababa, Kinshasa, Baghdad/Erbil, Brindisi, Nicosia, Chennai, Quezon City, Accra, and Beirut.",
        "This should not be forced into a defense-contractor injury model without additional workforce and claims data.",
      ],
      metricIds: ["world-vision-priority-hubs", "world-vision-network-fit"],
    },
    {
      type: "locations",
      title: "Global location signals",
      narrative:
        "The location table gives enough structured footprint data to support the network-expansion idea: where international NGO operations, humanitarian logistics, field programs, and regional offices exist, clinic coverage can be pre-mapped before a referral arrives.",
      bullets: [
        "Africa and Middle East signals include Nairobi, Addis Ababa, Accra, Kinshasa/Goma/Bukavu, Baghdad/Erbil, Beirut, Nicosia, and Brindisi logistics.",
        "APAC signals include Chennai, Kolkata, Bangalore, Jakarta Pusat, Phnom Penh, Quezon City, and other regional office locations.",
        "Latin America and support-office rows include Sao Paulo, Bogota, Quito, Guatemala City, Tegucigalpa, Petion-Ville, and Mississauga.",
      ],
      metricIds: [],
    },
    {
      type: "medical-opportunities",
      title: "Occu-Med service opportunity",
      narrative:
        "For World Vision, the initial value is not a standard injury-cost sales pitch. It is international clinic coverage, travel medicine, vaccination readiness, field-deployment baselines, conflict-response support, and provider-network planning around global NGO operations.",
      bullets: [
        "Treat the file as location intelligence first.",
        "Prioritize provider-network mapping around regional hubs and conflict/emergency response locations.",
        "Do not invent TRIR or claims exposure until a workforce and injury dataset is available.",
      ],
      metricIds: ["world-vision-field-risk"],
    },
  ],
};
