export default [
  {
    "title": "Zika",
    "aliases": ["zika"],
    "pages": [1,7],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Zika virus",
    "endemicity": "Worldwide, periodic outbreaks in tropical and subtropical regions",
    "atRisk": "Adventure tourists Long-term travelers and expatriates Travelers visiting friends and relatives Pregnant women and women planning pregnancy (infection during pregnancy can cause…",
    "prevention": "Avoid mosquito bites Use condoms or abstain from sex if exposed (or possibly exposed)",
    "diagnosticSupport": "A clinical laboratory certified in high complexity testing; state health department; or contact CDC Arboviral Diseases Branch (970-221-6400; dvbid@cdc.gov)",
    "transmission": "Transmission occurs through the bite of an infected Aedes species mosquito. Intrauterine, perinatal, sexual, laboratory, and possible transfusionassociated transmission have been reported.",
    "clinical": "Most Zika virus infections are either asymptomatic or result in mild clinical illness characterized by acute onset of fever, arthralgia, non-purulent conjunctivitis, and maculopapular rash.",
    "diagnosis": "Consider Zika virus infection in patients with acute onset of fever, arthralgia, conjunctivitis, or maculopapular rash who, within 2 weeks of illness onset, lived in or recently traveled to areas with current or past…",
    "treatment": "No specific antiviral treatment is available for Zika virus disease. Treatment is generally supportive and can include use of analgesics and antipyretics, fluids, and rest.",
    "keyNotes": ["Zika virus has been detected in breast milk, but the risk for transmission through breastfeeding is unknown.","Zika virus infection during pregnancy can result in congenital Zika virus infection; sequelae include microcephaly with brain and ocular anomalies, other serious neurologic consequences, and fetal loss."],
    "flags": {"vaccinePreventable":false,"mosquitoBorne":true,"tickBorne":false,"foodWater":false,"respiratory":false,"animalExposure":false,"freshwater":false,"sexualTransmission":true,"notifiable":true,"postExposure":false}
  },
  {
    "title": "Yellow Fever",
    "aliases": ["yellow fever","yellow-fever"],
    "pages": [8,33],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Yellow fever virus",
    "endemicity": "Sub-Saharan Africa Tropical South America",
    "atRisk": "Unimmunized people visiting forested or savanna regions of endemic areas, or visiting destinations with ongoing yellow fever outbreaks",
    "prevention": "Avoid insect bites Yellow fever is a vaccine-preventable disease",
    "diagnosticSupport": "State health department Contact CDC’s Arboviral Diseases Branch: 970-221-6400; dvbid@cdc.gov",
    "transmission": "Vector-borne transmission of YF virus occurs via the bite of an infected mosquito, primarily Aedes or Haemagogus spp. Non-human primates and humans are the main reservoirs of the virus, and anthroponotic…",
    "clinical": "Most people infected with YF virus have minimal or no symptoms and are unlikely to seek medical attention. For those who develop symptomatic illness, the incubation period is typically 3–6 days.",
    "diagnosis": "YF is a nationally notifiable disease. A preliminary diagnosis is based on clinical presentation and exposure details.",
    "treatment": "No specific medications are available to treat YF virus infections. Following the recent large outbreaks in Brazil, a systematic review was conducted on specific treatments for YF, including…",
    "keyNotes": ["A traveler's risk for acquiring YF is determined by their immunization status as well as destination-specific (e.g., local rate of virus transmission) and travel-associated (e.g., exposure duration, occupational and…","In West Africa, YF virus transmission increases during the middle of the rainy season (around August) and peaks during the early dry season (October)."],
    "flags": {"vaccinePreventable":true,"mosquitoBorne":true,"tickBorne":false,"foodWater":false,"respiratory":false,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":true,"postExposure":false}
  },
  {
    "title": "Measles (Rubeola)",
    "aliases": ["measles","rubeola","measles (rubeola)"],
    "pages": [34,42],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Measles virus",
    "endemicity": "Worldwide",
    "atRisk": "All travelers, especially unvaccinated travelers",
    "prevention": "Measles is a vaccine-preventable disease",
    "diagnosticSupport": "A clinical laboratory certified in moderate complexity testing; state health department; or CDC Measles Virus Laboratory",
    "transmission": "Measles is transmitted from person to person via respiratory droplets and by the airborne route as aerosolized droplet nuclei. Infected people are usually contagious from 4 days before until 4 days after rash onset.",
    "clinical": "The incubation period for measles averages 11–12 days from exposure to onset of prodrome; rash usually appears approximately 14 days after exposure.",
    "diagnosis": "Measles is a nationally notifiable disease. Laboratory criteria for diagnosis include a positive serologic test for measles-specific IgM, IgG seroconversion, or a significant rise in measles IgG level by any standard…",
    "treatment": "Treatment is supportive. The WHO recommends vitamin A for all children with acute measles, regardless of their country of residence, to reduce the risk for complications.",
    "keyNotes": ["In addition to personal productivity losses, infected people can incur direct costs for the management of their illness, including treatment, isolation, and caregiving, and their susceptible close contacts may be…","The Advisory Committee on Immunization Practices recommends that separate MMR and varicella vaccines be given for the first dose in children aged 12–47 months;"],
    "flags": {"vaccinePreventable":true,"mosquitoBorne":false,"tickBorne":false,"foodWater":false,"respiratory":true,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":true,"postExposure":true}
  },
  {
    "title": "Meningococcal Disease",
    "aliases": ["meningococcal","meningitis","meningococcal disease"],
    "pages": [43,55],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Neisseria meningitidis",
    "endemicity": "Worldwide, but greatest incidence occurs in the meningitis belt of Africa (Map 4.12.1)",
    "atRisk": "Unvaccinated travelers to countries in the meningitis belt, particularly travelers having prolonged contact with local populations during an epidemic",
    "prevention": "Most types of meningococcal disease are vaccine-preventable",
    "diagnosticSupport": "A clinical laboratory certified in moderate complexity testing; state health department",
    "transmission": "Meningococci spread through respiratory secretions and require close contact for transmission. Both asymptomatic carriers and people with overt meningococcal disease can be sources of infection.",
    "clinical": "Meningococcal disease generally occurs 1–10 days after exposure and presents as meningitis in approximately 50% of cases in the United States.",
    "diagnosis": "Early diagnosis and treatment are critical. If bacterial meningitis is suspected, collect blood for culture right away and perform a lumbar puncture (LP) to collect cerebrospinal fluid (CSF) for microscopic examination…",
    "treatment": "Meningococcal disease can be rapidly fatal and should always be viewed as a medical emergency. As soon as disease is suspected and blood cultures and CSF have been collected, deliver appropriate…",
    "keyNotes": ["Meningococcal disease is hyperendemic in this region, and periodic epidemics during the dry season (roughly December–June) reach an incidence of up to 1,000 cases per 100,000 population.","Two pentavalent meningococcal vaccines including both a MenACWY and a MenB component are licensed in the United States and may be used when both MenACWY and MenB vaccines are indicated at the same visit."],
    "flags": {"vaccinePreventable":true,"mosquitoBorne":false,"tickBorne":false,"foodWater":false,"respiratory":true,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":true,"postExposure":true}
  },
  {
    "title": "Norovirus",
    "aliases": ["norovirus"],
    "pages": [56,61],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Norovirus",
    "endemicity": "Worldwide",
    "atRisk": "All travelers",
    "prevention": "Practice good hand hygiene with soap and water, if possible Carefully clean and disinfect surfaces and toilet areas contaminated with fecal material or vomit",
    "diagnosticSupport": "A clinical laboratory certified in moderate complexity testing, state and local health departments during outbreak investigations",
    "transmission": "Norovirus transmission occurs primarily through the fecal-oral route, either through direct person-to-person contact or indirectly via contaminated food or water.",
    "clinical": "Infected people usually experience acute onset of vomiting and non-bloody diarrhea. The incubation period ranges from 12 to 48 hours.",
    "diagnosis": "Norovirus infection is generally diagnosed based on clinical symptoms. Diagnostic testing is not widely performed to guide clinical management of individual patients, but laboratory testing of stool specimens to confirm…",
    "treatment": "Supportive care is the mainstay of norovirus treatment, especially oral or intravenous rehydration. Antidiarrheals and antiemetics are not recommended for the routine management of acute…",
    "keyNotes": ["Norovirus infections can occur year-round, but, in temperate climates, activity peaks during the winter.","In some cases, especially among young children, the elderly, and immunocompromised individuals, dehydration can occur which may require medical attention."],
    "flags": {"vaccinePreventable":false,"mosquitoBorne":false,"tickBorne":false,"foodWater":true,"respiratory":false,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":false,"postExposure":false}
  },
  {
    "title": "Poliomyelitis",
    "aliases": ["polio","poliomyelitis","poliovirus"],
    "pages": [62,70],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Poliovirus (serotypes 1, 2, 3)",
    "endemicity": "Type 1 wild poliovirus (WPV): endemic to Afghanistan and Pakistan only Circulating vaccine-derived poliovirus (cVDPV):",
    "atRisk": "Any unvaccinated or under-vaccinated traveler to countries with current or recent poliovirus circulation",
    "prevention": "Polio is a vaccine-preventable disease",
    "diagnosticSupport": "CDC Emergency Operations Center (770-488-7100; ask to speak to the on-call polio subject matter expert)",
    "transmission": "Transmission occurs when the virus enters through the mouth and multiplies in the throat and gastrointestinal tract. Virus can be excreted in nasopharyngeal secretions for 1–2 weeks and in stool for 3–6 weeks, even in…",
    "clinical": "Most poliovirus infections are asymptomatic; approximately 25% cause minor short-term illness. Depending on poliovirus serotype, approximately 1 in 200 to 1 in 2,000 infections are associated with paralysis.",
    "diagnosis": "Information on diagnostic testing for poliovirus is available from CDC's Polio Laboratory Testing website and Test Directory: Submitting Specimens to CDC.",
    "treatment": "No licensed treatment exists for poliovirus infection, and only supportive care for symptoms is available. Two antiviral agents are undergoing clinical testing for the treatment of people with…",
    "keyNotes": ["Before a vaccine was available, infection with wild poliovirus (WPV) was common worldwide and had seasonal peaks and epidemics in the summer and fall in temperate areas.","Type 2 WPV was last isolated in 1999 and was declared eradicated in 2015; type 3 WPV was last detected in November 2012 and was declared eradicated in 2019."],
    "flags": {"vaccinePreventable":true,"mosquitoBorne":false,"tickBorne":false,"foodWater":false,"respiratory":false,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":true,"postExposure":false}
  }
] as const;
