// Source-table evidence preserved from Bongomin et al., Journal of Fungi 2017, Tables 2, 3, 4, 6 and 8.
// Keys are the AOR fungal disease key and ISO-3166 alpha-2 code used by the map layer.

export const FUNGAL_SOURCE_NOTE_LABELS: Record<string, string> = {
  candidemia: "Source comment",
  "invasive-aspergillosis": "Source assumptions",
  pcp: "Source assumptions",
  abpa: "Source comment / assumptions",
  "fungal-keratitis": "Source assumption / basis",
};

export const FUNGAL_SOURCE_NOTES: Record<string, Record<string, string>> = {
  candidemia: {
    BR: "No local incidence data",
    PK: "1.6 per 100,000 + 50% of candida peritonitis",
    QA: "15.4 per 100,000 from previous studies",
    TH: "94% of non-neutropenic patients with fungaemia + 4.5% of neutropenic patients",
    HU: "3–10 per 100,000 from previous studies + 780 cases in chronic ambulatory peritoneal dialysis",
    IL: "Incidence rate from nationwide surveillance (2005–2007), adjusted to ICU hospital days in 2012.",
    DK: "Data from Arendrup et al.",
    RU: "0.37 per 1000 hospitalised patients based on previous report",
    ES: "8.1 per 100,000 from previous study",
    GB: "38% of probable or proven invasive candidiasis tested by blood culture techniques in England, Wales and Northern Ireland, plus 4.8 cases per 100,000 in Scotland",
    IE: "Statistics and Research records office voluntary laboratory reporting programme.",
    NG: "6 per 100,000 + 50% of candida peritonitis.",
    UZ: "Data from Ministry of Health",
    DZ: "No local incidence data",
    BD: "No local incidence data",
    BE: "No local incidence data",
    CL: "No local incidence data",
    CZ: "No local incidence data",
    DO: "No local incidence data",
    EC: "No local incidence data",
    EG: "5 per 100,000 and 0.98 per 100,000 of intra-abdominal peritonitis.",
    GR: "No local incidence data.",
    GT: "No local incidence data",
    JM: "5.5 per 100,000",
    KE: "No local incidence data",
    MX: "5 per 100,000 + 285 in candida peritonitis",
    PE: "2–11 per 100,000 + 50% of candida peritonitis",
    TZ: "No local incidence data",
    TT: "5 per 100,000 + 285 in candida peritonitis",
    UA: "5 per 100,000 + 285 in candida peritonitis",
    VN: "No local incidence data",
    DE: "Data from Statistisches Bundesamt Wiesbaden 2015",
    KR: "0.22 per 1000 patients",
    FR: "No local incidence data",
    CA: "Average from two studies: 2.8 and 3.3 cases per 100,000 over a five-year period.",
    AT: "No additional comment supplied in Table 2.",
    LK: "Unpublished data from the department of mycology",
    PT: "Data from Portuguese multicentre survey",
    PH: "2 per 100,000 + 50% candida peritonitis",
  },
  "invasive-aspergillosis": {
    VN: "10% AML; 10% non-AML; 0.5% renal transplant; 4% lung and liver transplant; 6% heart transplant; 3.9% COPD admissions.",
    EG: "2.6% COPD admissions; 10% AML; 10% other predisposing haematological malignancies; 1% renal transplant; 4% liver transplant; 2.6% lung transplant.",
    GR: "10% AML; 8% HSCT; 6% heart transplant; 4% lung and liver transplant; 1% kidney transplant; 1.3% COPD admissions.",
    DZ: "1.3% COPD admissions; 2.6% lung cancer; 7.7% neutropenic patients.",
    IE: "10% AML; 8% HSCT; 0.5% renal transplant; 2% heart transplant; 0.9% liver transplant; 9.1% lung transplant; 1.3% COPD admissions.",
    IL: "10% AML; 10% HSCT; 0.5% renal transplant; 4% lung transplant; 6% heart transplant; 4% liver transplant; 1.3% COPD admissions.",
    BE: "10% AML; 0.5% renal transplant; 4% lung and liver transplant; 6% heart transplant; 1.3% COPD admissions.",
    PK: "3.9% COPD admissions; 2.6% lung cancer; 10% AML; 10% non-AML.",
    EC: "10% AML; 8% HSCT; 1% liver transplant; 0.5% renal transplant; 2% heart transplant; 9% lung transplant; 1.3% COPD admissions.",
    DK: "10% HSCT; 6% heart and lung transplant; 4% liver transplant; 1% renal transplant; 1.3% COPD admissions.",
    BD: "1.3% of COPD admissions (only COPD included in assumptions).",
    DE: "5% AML; 5% non-AML haematological malignancies; 1% renal transplant; 20% lung transplant; 6% heart transplant; 4% liver transplant; 1.3% COPD admissions.",
    PE: "10% AML; 10% non-AML haematological malignancies; 1.3% COPD admissions; 0.3% renal transplant; 0.8% liver transplant; 4.8% heart transplant; 42% HSCT.",
    UZ: "50% AML; 1.3% COPD admissions.",
    GB: "9% HSCT; 10% solid-organ transplant; 0.6% HIV; 15% haematological disease; 1.3% COPD admissions.",
    BR: "13.4% AML; 2.3% HSCT recipients; 0.5% renal transplant; 13.3% lung transplant; no COPD data.",
    KR: "14.7% HSCT; 0.76% liver transplant; 0.24% renal transplant; 8.8% lung transplant; 0.8% heart transplant; 5% AML/non-AML haematological malignancy; 1.6% COPD admissions.",
    GT: "10% AML; 10% non-AML haematological malignancies; 1.3% COPD admissions.",
    AT: "No additional assumption supplied in Table 3.",
    MX: "1.3% COPD admissions; 8% haematological conditions; 0.7% solid-organ transplant.",
    NP: "3.9% COPD admissions; 10% AML; 10% non-AML haematological malignancies.",
    UG: "7% in haematological malignancy; 1.3% COPD admissions.",
    HU: "12% AML; 6–8% HSCT; 8.6% lung transplant; 3.4% heart transplant; 4.7% liver transplant; 1.3% renal transplant; 1.35% COPD admissions.",
    PH: "10% AML; 10% non-AML; 0.5% renal transplant; 4% liver transplant; 1.3% COPD admissions.",
    CZ: "1.3% COPD admissions; 10% AML; 1% renal transplant; 5% lung transplant; 5.5% heart transplant; 4% liver transplant.",
    ES: "10% HSCT; 6% heart transplant; 4% lung/liver transplant; 1% kidney transplant; 7% AML; 7.7% non-AML haematological disease; 1.3% admitted COPD cases.",
    UA: "10% AML; 10% non-AML; 3.6% COPD admissions.",
    PT: "1.3% COPD admissions; 2.63% lung cancers; 31% HSCT; 6% heart transplant; 4% lung/liver transplant; 1% kidney transplant.",
    RU: "10% AML; 20% HSCT; 1% renal transplant; 4% liver transplant; 6% heart transplant; 1.3% admitted COPD patients.",
    FR: "1.8 per 100,000 from previous studies and 1,300 cases a year in COPD.",
    CL: "10% leukaemia; 1.3% COPD admissions; 2.6% lung cancers.",
    CA: "8.9% AML; 0.2% kidney transplant; 0.5% liver transplant; 3.8% lung transplant; 0.8% heart transplant; 0.2% pancreas transplant; 7.5% HSCT; 3.6/1000 COPD admissions.",
    TH: "13.5% AML; 3% renal transplant; 4% lung and liver transplant; 1.3% COPD.",
    LK: "10% AML; 100% non-AML; 0.5% renal transplant; 4% liver transplant.",
    DO: "10% AML; 10% non-AML haematological patients; 13.4% of COPD over 40 years.",
    KE: "10% AML; 10% non-AML haematological patients; COPD not included.",
    NG: "10% AML; 10% non-AML haematological malignancies; COPD not included.",
    QA: "11 cases recorded in the reference laboratory.",
    TT: "10% AML; COPD population not included.",
    TZ: "10% AML; COPD population not included.",
  },
  pcp: {
    NG: "40% of new AIDS cases in children and 10% in adults",
    KE: "10% in HIV with CD4 <200",
    TT: "80% of HIV patients with CD4 <200",
    TZ: "10.4% of adults living with HIV",
    UA: "60% of HIV patients",
    JM: "255 in HIV HAART-naive (as printed in Table 4)",
    SN: "22% of new AIDS",
    UZ: "60% of HIV with CD4 <200",
    GT: "4.7% in HIV patients",
    PE: "13% in AIDS",
    MX: "24% in HIV",
    CL: "35% of new HIV cases",
    NP: "16.7% of new AIDS cases in children and 22.4% of adults",
    ES: "3.4/100,000 from previously published studies",
    EC: "10.7% of HIV with CD4 <200 from previous study",
    TH: "21% of new AIDS cases",
    DO: "80% of HIV HAART-naive patients with CD4 <200",
    BR: "4.7% of AIDS patients with CD4 <350",
    DE: "Epidemiological data from Robert Koch Institute 2012",
    PK: "16% in HIV",
    BE: "Unpublished data from an AIDS reference centre in Leuven, Belgium.",
    FR: "Data from retrospective study in 2014.",
    GR: "26.2% of new AIDS cases",
    UG: "2.6% of non-HIV pneumonia deaths in children under 15 + 36.8% of HIV adults with CD4 <100 + 10–49% of pneumonia admissions in children with HIV.",
    IE: "25% in HIV.",
    QA: "15 cases reported to the reference laboratory",
    CA: "Cases from a single tertiary centre in Montreal",
    CZ: "Internal registry of the Department of Tropical and Infectious Diseases in Prague.",
    VN: "13% of new AIDS diagnoses.",
    PT: "0.61/100,000 in a previous study",
    KR: "20% of new HIV patients with low CD4",
    PH: "31% of new AIDS diagnoses",
    GB: "Incidence rates in HIV and solid-organ transplant recipients from previous studies.",
    IL: "Records from Clinical Microbiological laboratory at Tel Aviv.",
    DZ: "15% in HIV with CD4 <200 from various studies",
    RU: "2.1% of new HIV",
    EG: "1.9% of HIV based on previous study",
    HU: "Records from clinical laboratory",
    BD: "17% of HIV",
    DK: "35% in new AIDS patients from 1997–2009 data and 255 in non-AIDS based on a previous study.",
  },
  abpa: {
    GB: "2.5% of asthma + 12.5% of adult cystic fibrosis + 7.5% of children with cystic fibrosis.",
    TT: "2.5% of asthma.",
    DO: "2.5% of asthma",
    BE: "2.5% of asthma patients and 15% in cystic fibrosis",
    BR: "2.1% of adult asthmatics and 22% of adults with cystic fibrosis",
    GR: "2.5% of asthma and 17.7% of cystic fibrosis",
    JM: "2.5% of asthma",
    EC: "2.5% of asthma",
    CA: "2.5% of asthma and 18% of cystic fibrosis",
    EG: "2.5% of asthma",
    ES: "2.5% of asthma",
    DE: "2.5% of asthma and 4.8% of cystic fibrosis",
    FR: "2.5% of asthma",
    IE: "2.5% of asthma and 17.75% in cystic fibrosis",
    HU: "2.5% of asthma and 15% in cystic fibrosis",
    DK: "2.5% of asthma and 5% cystic fibrosis",
    PH: "2.5% of asthma",
    RU: "2.5% of asthma",
    PT: "2.5% of asthma",
    IN: "2.5% (0.7–3.5%) of asthma",
    IL: "2.5% of asthma and 6.6% in cystic fibrosis",
    CL: "2.5% of asthma",
    AT: "No additional comment supplied in Table 6.",
    DZ: "2.5% of asthma patients",
    PE: "2.5% of asthma",
    SN: "2.5% of asthma",
    UA: "2.5% of asthma.",
    NG: "2.5% of asthma",
    QA: "2.5% of asthma",
    MX: "2.5% of asthma",
    TH: "2.5% of asthma",
    KR: "2.5% of asthma",
    BD: "2.5% of asthma patients",
    PK: "2.5% of asthma",
    LK: "2.5% of asthma",
    UG: "2.5% of asthma",
    CZ: "2.5% of asthma and 18% cystic fibrosis",
    KE: "2.5% of asthma",
    TZ: "2.5% of asthma",
    GT: "2.5% of asthma",
    NP: "2.5% of asthma",
    VN: "2.5% of asthma",
    UZ: "2.5% of asthma + 15% of cystic fibrosis.",
  },
  "fungal-keratitis": {
    NP: "27–62% of microbial keratitis",
    PK: "0.15% of general population based on the Chinese study",
    TH: "15% of microbial keratitis",
    EG: "40% of microbial keratitis",
    MX: "0.15% of general population based on the Chinese study",
    VN: "Based on previous Vietnamese study reporting a rate of 7 per 100,000",
    LK: "40% direct-microscopy positivity rate for fungal elements in corneal buttons and scrapings.",
    QA: "6 cases recorded in the mycology reference laboratory.",
    CN: "0.15% of general population",
    PH: "Based on cases seen at a tertiary government hospital in the national capital region in 2015.",
    KR: "Based on a previous Danish study.",
    DK: "Based on a previous Danish study.",
    DE: "Based on a previous Danish study.",
  },
};
