export default [
  {
    "title": "Zika",
    "aliases": ["zika"],
    "pages": [1,7],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Zika virus",
    "endemicity": "Worldwide, with periodic outbreaks in tropical and subtropical regions",
    "atRisk": "Adventure tourists; long-term travelers and expatriates; travelers visiting friends and relatives; pregnant women and people planning pregnancy because infection during pregnancy can cause severe fetal complications",
    "prevention": "Avoid mosquito bites. After possible exposure, use condoms or abstain from sex for the CDC-recommended interval; pregnancy and pregnancy planning require additional travel counseling.",
    "diagnosticSupport": "A clinical laboratory certified in high complexity testing; state health department; or CDC Arboviral Diseases Branch (970-221-6400; dvbid@cdc.gov)",
    "transmission": "Transmission occurs mainly through bites from infected Aedes mosquitoes. Intrauterine, perinatal, sexual, laboratory, and possible transfusion-associated transmission have also been reported.",
    "clinical": "Most infections are asymptomatic or mild. Symptomatic illness commonly includes acute fever, arthralgia, non-purulent conjunctivitis, and maculopapular rash; neurologic complications are uncommon but recognized.",
    "diagnosis": "Consider Zika in a traveler with compatible symptoms who lived in or recently traveled to an area with current or past transmission, or who had recent sexual exposure to someone with relevant travel. Testing strategy depends on timing and should also consider dengue because geography and clinical features overlap.",
    "treatment": "No specific antiviral treatment is available. Management is supportive with fluids, rest, analgesics, and antipyretics; avoid aspirin and other NSAIDs until dengue has been ruled out.",
    "keyNotes": ["Zika virus has been detected in breast milk, but the risk for transmission through breastfeeding is unknown.","Infection during pregnancy can cause congenital Zika syndrome, including microcephaly, brain and ocular abnormalities, other serious neurologic effects, and fetal loss."],
    "flags": {"vaccinePreventable":false,"mosquitoBorne":true,"tickBorne":false,"foodWater":false,"respiratory":false,"animalExposure":false,"freshwater":false,"sexualTransmission":true,"notifiable":true,"postExposure":false}
  },
  {
    "title": "Yellow Fever",
    "aliases": ["yellow fever","yellow-fever"],
    "pages": [8,33],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Yellow fever virus",
    "endemicity": "Sub-Saharan Africa and tropical South America, with country- and subnational-area differences in transmission risk",
    "atRisk": "Unimmunized travelers visiting forested or savanna regions of endemic areas, travelers to destinations with ongoing outbreaks, and people whose itinerary places them in areas where vaccination is recommended",
    "prevention": "Avoid mosquito bites and use yellow fever vaccination when indicated after screening for contraindications and precautions. Entry-documentation requirements are separate from clinical vaccine recommendations.",
    "diagnosticSupport": "State health department; CDC Arboviral Diseases Branch (970-221-6400; dvbid@cdc.gov)",
    "transmission": "Yellow fever virus is transmitted by infected mosquitoes, principally Aedes and Haemagogus species. Sylvatic, intermediate, and urban transmission cycles involve humans, non-human primates, and mosquito vectors.",
    "clinical": "Most infections are asymptomatic or mild. Symptomatic illness usually begins after a 3–6 day incubation with fever, headache, myalgia, nausea, and vomiting; a minority progress after brief improvement to jaundice, hemorrhage, shock, and multiorgan failure.",
    "diagnosis": "Yellow fever is nationally notifiable. Diagnosis uses exposure history plus clinical findings and laboratory testing such as RT-PCR early in illness and serology later; flavivirus antibody cross-reactivity can complicate interpretation.",
    "treatment": "No specific antiviral treatment is proven. Management is supportive with fluids, rest, analgesics, and antipyretics; avoid medications such as aspirin or NSAIDs that can increase bleeding risk.",
    "keyNotes": ["Traveler risk depends on vaccination status, local transmission, outbreak activity, travel duration, season, and occupational/recreational mosquito exposure.","West African transmission increases during the rainy season and peaks around early dry season; South American sylvatic risk is greatest during the rainy season, especially early in the year."],
    "flags": {"vaccinePreventable":true,"mosquitoBorne":true,"tickBorne":false,"foodWater":false,"respiratory":false,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":true,"postExposure":false}
  },
  {
    "title": "Measles (Rubeola)",
    "aliases": ["measles","rubeola","measles (rubeola)"],
    "pages": [34,42],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Measles virus",
    "endemicity": "Worldwide",
    "atRisk": "All travelers, especially people without presumptive immunity or age- and travel-appropriate measles vaccination",
    "prevention": "Measles is vaccine-preventable. Travelers without presumptive immunity should receive the appropriate MMR/MMRV schedule before travel when not contraindicated.",
    "diagnosticSupport": "A clinical laboratory certified in moderate complexity testing; state health department; or CDC Measles Virus Laboratory",
    "transmission": "Measles spreads person-to-person through respiratory droplets and airborne aerosolized droplet nuclei. Infected people are usually contagious from 4 days before through 4 days after rash onset.",
    "clinical": "Incubation averages 11–12 days to prodrome and about 14 days to rash. Typical illness includes fever, cough, coryza, conjunctivitis, Koplik spots, and a generalized maculopapular rash; complications include pneumonia, otitis, diarrhea, encephalitis, and rarely death.",
    "diagnosis": "Measles is nationally notifiable. Laboratory confirmation can use measles-specific IgM, seroconversion/rise in IgG, virus isolation, or real-time RT-PCR. Suspected cases require rapid isolation and public-health coordination.",
    "treatment": "Treatment is supportive. WHO recommends vitamin A for children with acute measles using age-specific dosing because it can reduce complication risk.",
    "keyNotes": ["Nearly 90% of imported U.S. measles cases described in the chapter were considered preventable by vaccination.","MMR given within 72 hours of exposure or immune globulin within 6 days can be used as post-exposure prophylaxis for appropriate susceptible contacts."],
    "flags": {"vaccinePreventable":true,"mosquitoBorne":false,"tickBorne":false,"foodWater":false,"respiratory":true,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":true,"postExposure":true}
  },
  {
    "title": "Meningococcal Disease",
    "aliases": ["meningococcal","meningitis","meningococcal disease"],
    "pages": [43,55],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Neisseria meningitidis",
    "endemicity": "Worldwide, with greatest incidence and recurrent epidemics in the meningitis belt of Sub-Saharan Africa",
    "atRisk": "Unvaccinated travelers to meningitis-belt countries, particularly those with prolonged close contact with local populations during epidemics; Hajj/Umrah pilgrims have additional vaccination-documentation requirements",
    "prevention": "Most major meningococcal serogroups are vaccine-preventable. MenACWY vaccination is recommended for relevant meningitis-belt travel and close contacts of invasive cases require prompt antibiotic chemoprophylaxis.",
    "diagnosticSupport": "A clinical laboratory certified in moderate complexity testing; state health department",
    "transmission": "Meningococci spread through respiratory secretions and require close contact. Both asymptomatic carriers and people with invasive disease can transmit the organism.",
    "clinical": "Disease usually occurs 1–10 days after exposure and can present as meningitis, meningococcemia/sepsis, or bacteremic pneumonia. It can progress rapidly to shock, purpura fulminans, multiorgan failure, and death.",
    "diagnosis": "Early diagnosis and treatment are critical. Blood cultures and cerebrospinal fluid should be obtained when feasible, with culture and PCR used to identify N. meningitidis. Reporting to public health should not be delayed.",
    "treatment": "Meningococcal disease is a medical emergency. Empiric third-generation cephalosporin therapy should begin promptly after appropriate specimens are obtained; treatment should not wait for final test results.",
    "keyNotes": ["The African meningitis belt has its highest epidemic risk during the dry season, approximately December–June.","Even with antimicrobial treatment, the case-fatality rate is about 10–15%, and survivors can have hearing loss, amputations, or other long-term sequelae."],
    "flags": {"vaccinePreventable":true,"mosquitoBorne":false,"tickBorne":false,"foodWater":false,"respiratory":true,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":true,"postExposure":true}
  },
  {
    "title": "Norovirus",
    "aliases": ["norovirus"],
    "pages": [56,61],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Norovirus",
    "endemicity": "Worldwide",
    "atRisk": "All travelers, especially those in cruise ships, camps, dormitories, hotels, long-term care facilities, group housing, or other congregate settings",
    "prevention": "Wash hands thoroughly with soap and water, use safe food and water practices, and carefully clean/disinfect surfaces and toilet areas contaminated with feces or vomit.",
    "diagnosticSupport": "A clinical laboratory certified in moderate complexity testing; state and local health departments during outbreak investigations",
    "transmission": "Transmission is primarily fecal-oral through direct person-to-person spread or contaminated food/water, but fomites and aerosols generated by vomitus also contribute.",
    "clinical": "Incubation is 12–48 hours. Illness usually causes abrupt vomiting, non-bloody diarrhea, abdominal cramps, nausea, and sometimes low-grade fever and typically resolves in 1–3 days.",
    "diagnosis": "Most individual cases are diagnosed clinically. Stool RT-qPCR and multiplex molecular panels are useful for outbreak confirmation and cluster investigation; public-health laboratories can provide support.",
    "treatment": "Supportive care, especially oral or intravenous rehydration, is the mainstay. Antibiotics are ineffective; selected symptom-control medications can be used in adults but are not routine pediatric therapy.",
    "keyNotes": ["Norovirus is common year-round but peaks during winter in temperate climates.","Environmental contamination can persist and cause recurrent outbreaks, so cleaning/disinfection is an operational control rather than a cosmetic measure."],
    "flags": {"vaccinePreventable":false,"mosquitoBorne":false,"tickBorne":false,"foodWater":true,"respiratory":false,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":false,"postExposure":false}
  },
  {
    "title": "Poliomyelitis",
    "aliases": ["polio","poliomyelitis","poliovirus"],
    "pages": [62,70],
    "sourceDate": "Apr. 23, 2025",
    "agent": "Poliovirus (serotypes 1, 2, 3)",
    "endemicity": "Wild poliovirus type 1 remains endemic in Afghanistan and Pakistan; circulating vaccine-derived poliovirus outbreaks occur dynamically in parts of Africa, Asia, and occasionally other regions",
    "atRisk": "Unvaccinated or under-vaccinated travelers to countries with current or recent WPV/cVDPV circulation, plus selected travelers with high exposure in neighboring or humanitarian/healthcare settings",
    "prevention": "Polio is vaccine-preventable. Complete age-appropriate IPV vaccination before travel; adults who completed a primary series may receive a single lifetime booster for travel to areas with active circulation.",
    "diagnosticSupport": "CDC Emergency Operations Center (770-488-7100; ask for the on-call polio subject matter expert)",
    "transmission": "Poliovirus enters through the mouth, multiplies in the oropharynx and gastrointestinal tract, and spreads person-to-person through fecal-oral and oral routes. Virus can be shed in respiratory secretions for 1–2 weeks and stool for 3–6 weeks.",
    "clinical": "Most infections are asymptomatic; about one quarter cause a minor illness. Depending on serotype, approximately 1 in 200 to 1 in 2,000 infections cause paralysis, which can lead to respiratory failure, residual weakness, or death.",
    "diagnosis": "Stool is the preferred specimen for virus isolation and PCR characterization. Paralytic polio is immediately notifiable and requires urgent state/local and CDC coordination, including specialized specimen handling.",
    "treatment": "No licensed antiviral treatment exists for acute poliovirus infection; management is supportive, including respiratory and rehabilitation care when paralysis occurs.",
    "keyNotes": ["Current cVDPV status changes frequently, so live CDC/GPEI country information should supersede the static booklet snapshot.","Some affected countries can implement temporary IHR departure-vaccination documentation requirements for residents and long-term travelers."],
    "flags": {"vaccinePreventable":true,"mosquitoBorne":false,"tickBorne":false,"foodWater":false,"respiratory":false,"animalExposure":false,"freshwater":false,"sexualTransmission":false,"notifiable":true,"postExposure":false}
  }
] as const;
