import { Router, type IRouter } from "express";
import healthRouter from "./health";
import aorSourcePolicyRouter from "./aor-source-policy";
import stateMapGeometryRouter from "./state-map-geometry";
import fmcsaRouter from "./fmcsa";
import coreLiveSearchRouter from "./core-live-search";
import coreIntelligenceRouter from "./core-intelligence";
import locationDiscoveryCacheRouter from "./locationDiscoveryCache";
import entityDiscoveryRouter from "./entityDiscovery";
import locationsCerebrasV2Router from "./locations-cerebras-v2";
import locationsAiRouter from "./locations-ai";
import bulkManualLocationsRouter from "./bulkManualLocations";
import intelligenceRouter from "./intelligence";
import publicApiRepairsRouter from "./public-api-repairs";
import employerIntelligenceRouter from "./employer-intelligence";
import companyLiveIntelligenceRouter from "./company-live-intelligence";
import courtlistenerRichRouter from "./courtlistener-rich";
import crisiswatchRouter from "./crisiswatch";
import aorRiskIntelligenceRouter from "./aor-risk-intelligence";
import workersCompCoverageRouter from "./workers-comp-coverage";
import dbaIntelligenceRouter from "./dba-intelligence";
import dbaHubRouter from "./dba-hub";
import sourceGovernanceRouter from "./source-governance";
import dataVisualizationRouter from "./dataVisualization";
import portalLinksRouter from "./portalLinks";
import secFilingsRouter from "./sec-filings";
import hiringIntelligenceRouter from "./hiring-intelligence";
import leadershipMapManualSnapshotsRouter from "./leadership-map-manual-snapshots";
import leadershipMapQualityRouter from "./leadership-map-quality";
import leadershipMapCerebrasV2Router from "./leadership-map-cerebras-v2";
import leadershipMapLangSearchRouter from "./leadership-map-langsearch";
import leadershipMapOrchestrationRouter from "./leadership-map-orchestration";
import corporateStructureRouter from "./corporate-structure";
import companyLibraryRouter from "./company-library";
import companyFileRouter from "./company-file";

const router: IRouter = Router();

router.use(healthRouter);
router.use(aorSourcePolicyRouter);
router.use(stateMapGeometryRouter);
router.use(fmcsaRouter);
router.use(coreLiveSearchRouter);
router.use(coreIntelligenceRouter);
router.use(companyLibraryRouter);
router.use(companyFileRouter);
router.use(locationDiscoveryCacheRouter);
router.use(entityDiscoveryRouter);
router.use(locationsCerebrasV2Router);
router.use(locationsAiRouter);
router.use(bulkManualLocationsRouter);
router.use(intelligenceRouter);
router.use(publicApiRepairsRouter);
router.use(employerIntelligenceRouter);
router.use(companyLiveIntelligenceRouter);
router.use(courtlistenerRichRouter);
router.use(crisiswatchRouter);
router.use(aorRiskIntelligenceRouter);
router.use(workersCompCoverageRouter);
router.use(dbaIntelligenceRouter);
router.use(dbaHubRouter);
router.use(sourceGovernanceRouter);
router.use(dataVisualizationRouter);
router.use(portalLinksRouter);
router.use(secFilingsRouter);
router.use(hiringIntelligenceRouter);
router.use(leadershipMapManualSnapshotsRouter);
router.use(leadershipMapQualityRouter);
router.use(leadershipMapCerebrasV2Router);
router.use(leadershipMapLangSearchRouter);
router.use(leadershipMapOrchestrationRouter);
router.use(corporateStructureRouter);

export default router;
