import { Router, type IRouter } from "express";
import healthRouter from "./health";
import locationDiscoveryCacheRouter from "./locationDiscoveryCache";
import entityDiscoveryRouter from "./entityDiscovery";
import locationsAiRouter from "./locations-ai";
import bulkManualLocationsRouter from "./bulkManualLocations";
import intelligenceRouter from "./intelligence";
import onetRouter from "./onet";
import employerIntelligenceRouter from "./employer-intelligence";
import companyLiveIntelligenceRouter from "./company-live-intelligence";
import workersCompCoverageRouter from "./workers-comp-coverage";
import dbaIntelligenceRouter from "./dba-intelligence";
import sourceGovernanceRouter from "./source-governance";
import dataVisualizationRouter from "./dataVisualization";
import portalLinksRouter from "./portalLinks";
import secFilingsRouter from "./sec-filings";
import hiringIntelligenceRouter from "./hiring-intelligence";
import leadershipMapQualityRouter from "./leadership-map-quality";
import leadershipMapOrchestrationRouter from "./leadership-map-orchestration";
import leadershipMapRouter from "./leadership-map";
import corporateStructureRouter from "./corporate-structure";
import companyLibraryRouter from "./company-library";

const router: IRouter = Router();

router.use(healthRouter);
router.use(companyLibraryRouter);
router.use(locationDiscoveryCacheRouter);
router.use(entityDiscoveryRouter);
router.use(locationsAiRouter);
router.use(bulkManualLocationsRouter);
router.use(intelligenceRouter);
router.use(onetRouter);
router.use(employerIntelligenceRouter);
router.use(companyLiveIntelligenceRouter);
router.use(workersCompCoverageRouter);
router.use(dbaIntelligenceRouter);
router.use(sourceGovernanceRouter);
router.use(dataVisualizationRouter);
router.use(portalLinksRouter);
router.use(secFilingsRouter);
router.use(hiringIntelligenceRouter);
router.use(leadershipMapQualityRouter);
router.use(leadershipMapOrchestrationRouter);
router.use(leadershipMapRouter);
router.use(corporateStructureRouter);

export default router;
