// AOR Factors vaccine-entry source registry: 390 official links from "Insight_Hub_2_AOR_Vaccine_Entry_Source_Registry.docx"
// (research snapshot 2026-10-08). Generated from the document tables; do not hand-edit rows, re-import the registry instead.
//
// Row = [scope, section, authority, what to check, url]
//   scope   ISO3 of the country, or "GLOBAL" for section A
//   section A global authorities | B direct country MOH / port health / immigration | C national discovery pages | D WHO country profile
//
// This is a pool of places to look. A row is NOT a statement that the page contains a current legal requirement.
export type RegistrySection = "A" | "B" | "C" | "D";
export type RegistryRow = readonly [scope: string, section: RegistrySection, authority: string, check: string, url: string];

export const REGISTRY_SNAPSHOT_DATE = "2026-10-08";

export const REGISTRY_ROWS: readonly RegistryRow[] = [
  ["GLOBAL", "A", "WHO", "WHO Countries directory — Country profiles and regional links", "https://www.who.int/countries"],
  ["GLOBAL", "A", "WHO", "Vaccines and travel — Travel-vaccine guidance; routine vs selective-use vaccines", "https://www.who.int/travel-advice/vaccines"],
  ["GLOBAL", "A", "WHO", "International Travel and Health - vaccine-preventable diseases (2025) — Traveler risk, geography, precautions, vaccines", "https://www.who.int/publications/i/item/9789240113350"],
  ["GLOBAL", "A", "WHO", "Disease Outbreak News — Authoritative acute public-health event reports", "https://www.who.int/emergencies/disease-outbreak-news"],
  ["GLOBAL", "A", "WHO", "Polio IHR Emergency Committee - 45th meeting (Aug 2026) — Current temporary recommendations affecting international travel", "https://www.who.int/news/item/25-08-2026-statement-of-the-forty-fifth-meeting-of-the-polio-ihr-emergency-committee"],
  ["GLOBAL", "A", "WHO", "Global respiratory-virus surveillance — Influenza/RSV/SARS-CoV-2 surveillance context", "https://www.who.int/teams/global-influenza-programme/surveillance-and-monitoring/respiratory-viruses"],
  ["GLOBAL", "A", "WHO", "FluNet — Country influenza virological surveillance", "https://www.who.int/tools/flunet"],
  ["GLOBAL", "A", "WHO", "Global Health Observatory — Structural country health-system indicators", "https://www.who.int/data/gho"],
  ["GLOBAL", "A", "CDC", "Travelers’ Health — Destination health intelligence", "https://wwwnc.cdc.gov/travel"],
  ["GLOBAL", "A", "CDC", "Travelers’ Health destination list — All destination pages", "https://wwwnc.cdc.gov/travel/destinations/list/"],
  ["GLOBAL", "A", "CDC", "Yellow Book 2026 — Core travel-medicine reference", "https://www.cdc.gov/yellow-book/hcp/contents/index.html"],
  ["GLOBAL", "A", "CDC", "Yellow Fever Vaccine & Malaria Prevention by Country — Country-specific YF entry/recommendation + malaria guidance", "https://www.cdc.gov/yellow-book/hcp/preparing-international-travelers/yellow-fever-vaccine-and-malaria-prevention-information-by-country.html"],
  ["GLOBAL", "A", "CDC", "Travel Health Notices — Current destination health notices", "https://wwwnc.cdc.gov/travel/notices"],
  ["GLOBAL", "A", "CDC", "Polio - International Travelers — Polio vaccination and IHR-related travel context", "https://www.cdc.gov/polio/vaccines/international-travelers.html"],
  ["GLOBAL", "A", "CDC/NCBI", "Yellow Book Table 4.21.4 — Countries requiring proof of YF vaccination from all arriving travelers", "https://www.ncbi.nlm.nih.gov/books/NBK620866/table/yellowfever.tab6/"],
  ["GLOBAL", "A", "U.S. State Department", "Travel Advisories — Current security/travel advisory layer", "https://travel.state.gov/content/travel/en/traveladvisories.html"],
  ["GLOBAL", "A", "UK FCDO", "Foreign Travel Advice — Independent government country travel/health/entry advice", "https://www.gov.uk/foreign-travel-advice"],
  ["GLOBAL", "A", "GDACS", "Global Disaster Alert and Coordination System — Near-real-time global disaster events", "https://www.gdacs.org/Alerts/default.aspx"],
  ["GLOBAL", "A", "GDACS", "Feed reference — Machine-readable disaster feeds", "https://www.gdacs.org/feed_reference.aspx"],
  ["GLOBAL", "A", "USGS", "Earthquake feeds — GeoJSON seismic event feeds", "https://earthquake.usgs.gov/earthquakes/feed/"],
  ["GLOBAL", "A", "ReliefWeb/OCHA", "ReliefWeb API v2 — Humanitarian reports and disaster context", "https://apidoc.reliefweb.int/"],
  ["GLOBAL", "A", "ReliefWeb/OCHA", "API parameters — Current API appname/filter requirements", "https://apidoc.reliefweb.int/parameters"],
  ["GLOBAL", "A", "NASA", "POWER API — Climate/environmental context", "https://power.larc.nasa.gov/docs/services/api/"],
  ["GLOBAL", "A", "OpenAQ", "OpenAQ v3 API — Air-quality station and measurement data", "https://docs.openaq.org/"],
  ["GLOBAL", "A", "DoD", "Combatant Commands — Official geographic command context", "https://www.defense.gov/Resources/Military-Departments/Our-Story/Combatant-Commands/"],
  ["GLOBAL", "A", "U.S. Africa Command", "AFRICOM — Official command source", "https://www.africom.mil/"],
  ["GLOBAL", "A", "U.S. Central Command", "CENTCOM AOR — Official command/AOR source", "https://www.centcom.mil/AREA-OF-RESPONSIBILITY/"],
  ["GLOBAL", "A", "U.S. European Command", "EUCOM — Official command source", "https://www.eucom.mil/"],
  ["GLOBAL", "A", "U.S. Indo-Pacific Command", "INDOPACOM — Official command source", "https://www.pacom.mil/"],
  ["GLOBAL", "A", "U.S. Northern Command", "NORTHCOM — Official command source", "https://www.northcom.mil/"],
  ["GLOBAL", "A", "U.S. Southern Command", "SOUTHCOM — Official command source", "https://www.southcom.mil/"],
  ["AGO", "B", "Permanent Mission of Angola to UN", "General information / health-entry reference", "https://www.un.int/angola/angola/general-information"],
  ["BEN", "B", "Ministry of Health", "2026 health formalities at points of entry", "https://www.sante.gouv.bj/article/actualites/information-sur-les-formalites-sanitaires-aux-points-dentree-du-benin"],
  ["BEN", "B", "Ministry of Health", "Official MOH portal", "https://sante.gouv.bj/"],
  ["BWA", "B", "Government / Ministry of Health", "Yellow Fever vaccination", "https://www.gov.bw/disease-prevention-control/yellow-fever-vaccination?page=1"],
  ["BWA", "B", "Government / Port Health", "Health guidelines for ports of entry", "https://www.gov.bw/learning-and-teaching/health-guidelines-ports-entry?page=1"],
  ["BWA", "B", "Ministry of Health", "Official ministry directory", "https://www.gov.bw/ministries/ministry-health"],
  ["BDI", "B", "Ministry of Public Health", "Official MOH portal", "https://minisante.gov.bi/"],
  ["CMR", "B", "Ministry of Public Health", "Official MOH portal", "https://www.minsante.cm/"],
  ["CMR", "B", "Embassy of Cameroon in Washington", "Official travel guidance", "https://www.cameroonembassyusa.org/traveling.php"],
  ["CMR", "B", "Embassy of Cameroon in Washington", "Visa requirements PDF", "https://www.cameroonembassyusa.org/main23/Images/documents_folder/VisaApplicationRequirementstandForm.pdf"],
  ["COG", "B", "Ministry of Health", "Official MOH portal", "https://sante.gouv.cg/w/"],
  ["COD", "B", "Ministry of Health", "Official MOH portal", "https://sante.gouv.cd/"],
  ["DJI", "B", "Ministry of Health", "Official MOH portal", "https://sante.gouv.dj/"],
  ["EGY", "B", "Ministry of Health and Population", "Official MOH portal", "https://www.mohp.gov.eg/"],
  ["EGY", "B", "Ministry of Health and Population", "Quarantine / international-health services", "https://www.mohp.gov.eg/SectorServices.aspx?Deptcode=12&SectorCode=6"],
  ["GNQ", "B", "Ministry of Health and Social Welfare", "Official health portal", "https://guineasalud.org/?lang=en"],
  ["ETH", "B", "Ministry of Health", "Official MOH portal", "https://www.moh.gov.et/"],
  ["GAB", "B", "Ministry of Health", "Official MOH portal", "https://sante.gouv.ga/"],
  ["GMB", "B", "Ministry of Health", "Official MOH portal", "https://moh.gov.gm/"],
  ["GMB", "B", "Ministry of Health", "Expanded Programme on Immunization", "https://moh.gov.gm/expanded-program-on-immunization/"],
  ["GHA", "B", "Ghana Immigration Service", "Official eVisa / entry portal", "https://evisa.immigration.gov.gh/"],
  ["GHA", "B", "Ghana Immigration Service", "ETA applicant guide - Yellow Fever/public health", "https://evisa.immigration.gov.gh/eta-applicant-guide.html"],
  ["GHA", "B", "Ghana Immigration Service", "Visa information", "https://evisa.immigration.gov.gh/visa-information"],
  ["KEN", "B", "Ministry of Health", "Incoming travellers / Yellow Fever requirements", "https://www.health.go.ke/index.php/incoming-travellers"],
  ["KEN", "B", "Ministry of Health", "Traveller information hub", "https://health.go.ke/travelers-information"],
  ["KEN", "B", "Port Health Services", "Official port-health portal", "https://porthealth.health.go.ke/"],
  ["KEN", "B", "Port Health Services", "Port-health FAQ / entry documents", "https://porthealth.health.go.ke/faqs"],
  ["KEN", "B", "Ministry of Health", "Departing travellers / YF certification", "https://health.go.ke/departing-travellers"],
  ["LSO", "B", "Government of Lesotho", "Government ministries / Health", "https://www.gov.ls/government-ministries/"],
  ["LBR", "B", "Ministry of Health", "Official MOH portal", "https://moh.gov.lr/"],
  ["MWI", "B", "Ministry of Health", "Official MOH portal", "https://health.gov.mw/"],
  ["MLI", "B", "Ministry of Health", "Official MOH portal", "https://sante.gov.ml/"],
  ["MUS", "B", "Ministry of Health and Wellness", "Official MOH portal", "https://health.govmu.org/health/"],
  ["NAM", "B", "Ministry of Health and Social Services", "Official ministry portal", "https://mhss.gov.na/"],
  ["NGA", "B", "Federal Ministry of Health", "Official MOH portal", "https://health.gov.ng/"],
  ["NGA", "B", "Federal Ministry of Health", "FAQ / Port Health / YF entry-exit rule", "https://health.gov.ng/faqs/"],
  ["NGA", "B", "Federal Ministry of Health", "Port Health Services", "https://site.health.gov.ng/port-health/"],
  ["NGA", "B", "Federal Ministry of Health", "Electronic Yellow Card portal", "https://yellowcard.health.gov.ng/"],
  ["NGA", "B", "NCDC", "Health declaration / traveler portal", "https://healthapp.ncdc.gov.ng/"],
  ["RWA", "B", "Ministry of Health", "Legal frameworks", "https://www.moh.gov.rw/legal-frameworks"],
  ["RWA", "B", "Ministry of Health", "Presidential/ministerial orders incl. Yellow Fever instruction", "https://www.moh.gov.rw/legal-frameworks/presidential-ministerial-orders"],
  ["SEN", "B", "Ministry of Health", "Official MOH portal", "https://www.sante.gouv.sn/"],
  ["SYC", "B", "Ministry of Health", "Yellow Fever vaccine page", "https://www.health.gov.sc/yellow-fever-vaccine/"],
  ["SLE", "B", "Official Mission / Embassy", "Visa services / Yellow Fever evidence", "https://slmission.gov.sl/visa-services/"],
  ["ZAF", "B", "National Department of Health", "Port Health programme", "https://www.health.gov.za/eh-prog-port-health/"],
  ["ZAF", "B", "National Department of Health", "2026 YF importation guideline PDF", "https://www.health.gov.za/wp-content/uploads/2026/09/Guidelines-for-the-Prevention-of-Yellow-Fever-Importation-into-South-Africa.pdf"],
  ["ZAF", "B", "Government of South Africa", "Yellow Fever requirements policy page", "https://www.gov.za/news/media-statements/health-reviews-yellow-fever-requirements-03-feb-2015"],
  ["ZAF", "B", "DIRCO / High Commission", "Official Yellow Fever page", "https://dirco.gov.za/canberra/yellow-fever/"],
  ["TZA", "B", "Ministry of Health", "Yellow Fever entry-requirements PDF", "https://www.moh.go.tz/storage/app/uploads/public/65a/f76/a77/65af76a777832906196271.pdf"],
  ["TZA", "B", "Ministry of Health", "Publications / Yellow Fever entry requirements", "https://www.moh.go.tz/en/publications/22"],
  ["UGA", "B", "Directorate of Citizenship and Immigration Control", "2026 Yellow Fever certificate entry notice", "https://www.immigration.go.ug/index.php/node/254"],
  ["UGA", "B", "Immigration", "Official immigration portal", "https://immigration.go.ug/"],
  ["ZMB", "B", "Ministry of Health", "Official MOH portal", "https://www.moh.gov.zm/"],
  ["ZWE", "B", "Ministry of Health and Child Care", "Official MOH portal", "https://www.mohcc.gov.zw/"],
  ["BRA", "B", "ANVISA", "Traveller / international vaccination certificate", "https://www.gov.br/anvisa/en/travellers"],
  ["BRA", "B", "Ministry of Health", "Traveler health", "https://www.gov.br/saude/pt-br/assuntos/saude-de-a-a-z/s/saude-do-viajante"],
  ["BRA", "B", "Ministry of Health", "Vaccination for travelers", "https://www.gov.br/saude/pt-br/vacinacao/viajantes"],
  ["BRA", "B", "ANVISA", "International vaccination certificate", "https://www.gov.br/anvisa/pt-br/assuntos/paf/certificado-internacional-de-vacinacao"],
  ["COL", "B", "Ministry of Health", "Traveler vaccination portal", "https://vacunacion.minsalud.gov.co/EV/Paginas/viajeros.aspx"],
  ["COL", "B", "Ministry of Health", "Health recommendations for travelers", "https://www2.minsalud.gov.co/English/Paginas/health-recomendations-for-travelers.aspx"],
  ["COL", "B", "Ministry of Health", "Yellow Fever", "https://www2.minsalud.gov.co/salud/publica/PET/Paginas/fiebre-amarilla.aspx"],
  ["CRI", "B", "Ministry of Health", "2026 Yellow Fever requirement update", "https://www.ministeriodesalud.go.cr/index.php/prensa/67-noticias-2026/2364-ministerio-de-salud-actualiza-disposiciones-sobre-fiebre-amarilla-y-mantiene-vacunacion-obligatoria-para-viajeros-a-zonas-de-riesgo"],
  ["CRI", "B", "Ministry of Health", "Sep 2026 implementation reminder", "https://ministeriodesalud.go.cr/index.php/muestratitulocomunicado/2635-salud-recuerda-cumplir-requisito-de-vacunacion-contra-la-fiebre-amarilla-a-partir-del-1-de-octubre"],
  ["CRI", "B", "Ministry of Health", "Aug 2026 deadline extension", "https://ministeriodesalud.go.cr/index.php/muestratitulocomunicado/2618-plazo-para-el-requisito-de-vacunacion-contra-la-fiebre-amarilla-se-amplia-hasta-el-1-de-octubre"],
  ["SLV", "B", "Ministry of Health", "Yellow Fever / entry status", "https://www.salud.gob.sv/fiebre-amarilla/"],
  ["GUY", "B", "Department of Public Information / Government", "Yellow Fever entry requirements", "https://dpi.gov.gy/yellow-fever-immunization-requirements-for-entry-into-guyana/"],
  ["JAM", "B", "Ministry of Health & Wellness", "Yellow Fever travel reminder", "https://www.moh.gov.jm/jamaican-travellers-reminded-to-get-yellow-fever-vaccine/"],
  ["JAM", "B", "Ministry of Health & Wellness", "Yellow Fever FAQ", "https://www.moh.gov.jm/edu-resources/yellow-fever-faqs/"],
  ["JAM", "B", "Ministry of Health & Wellness", "Yellow Fever travel advisory", "https://www.moh.gov.jm/jamaican-travellers-advised-to-get-yellow-fever-vaccine/"],
  ["PAN", "B", "Ministry of Health", "Yellow Fever traveler requirements", "https://minsa.gob.pa/noticia/requisitos-viajeros-por-la-vacuna-contra-la-fiebre-amarilla"],
  ["PRY", "B", "Ministry of Public Health", "Requirements to enter Paraguay", "https://dgvs.mspbs.gov.py/salud-del-viajero/requisitos-para-ingresar-a-paraguay/"],
  ["PRY", "B", "Ministry of Public Health", "Entry-health requirements detail", "https://www.mspbs.gov.py/dgps/33333/requisitos-sanitarios-para-ingreso-a-paraguay.html"],
  ["PRY", "B", "Immigration", "Health requirements for entry and exit", "https://migraciones.gov.py/requisitos-sanitarios-de-entrada-y-salida-del-paraguay/"],
  ["PRY", "B", "Ministry of Public Health", "Requirements for travel abroad", "https://dgvs.mspbs.gov.py/salud-del-viajero/requisitos-para-viajar-al-exterior/"],
  ["PER", "B", "Ministry of Health", "2026 Yellow Fever travel recommendations", "https://www.gob.pe/institucion/minsa/noticias/1331071-minsa-brinda-recomendaciones-para-prevenir-la-fiebre-amarilla"],
  ["PER", "B", "Government / Ministry of Health", "Yellow Fever vaccine / ICVP service", "https://www.gob.pe/25427"],
  ["PER", "B", "Government / Ministry of Health", "Traveler health overview", "https://www.gob.pe/25424"],
  ["TTO", "B", "Ministry of Health", "Yellow Fever", "https://health.gov.tt/yellow-fever"],
  ["TTO", "B", "Ministry of Health", "Vaccines and immunization schedule", "https://health.gov.tt/services/vaccines-and-immunization/immunization-schedule-for-trinidad-and-tobago"],
  ["SAU", "B", "Ministry of Health", "Hajj and Umrah health requirements hub", "https://www.moh.gov.sa/en/healthawareness/pilgrims-health/pages/default.aspx"],
  ["SAU", "B", "Ministry of Health", "2026 Umrah health regulations PDF", "https://www.moh.gov.sa/en/HealthAwareness/Pilgrims-Health/Documents/Health-Regulations-Umrah-EN.pdf"],
  ["SAU", "B", "Ministry of Health", "2026 Hajj health requirements PDF", "https://www.moh.gov.sa/HealthAwareness/Pilgrims-Health/Documents/Hajj-Health-Requirements-English-language.pdf"],
  ["BHR", "B", "Ministry of Health", "Immunizations / travel vaccines", "https://www.moh.gov.bh/HealthInfo/Immunizations?lang=en"],
  ["BHR", "B", "Ministry of Health", "Publications", "https://www.moh.gov.bh/HealthInfo/Publications"],
  ["KWT", "B", "Government / Ministry of Health", "Passenger health", "https://e.gov.kw/sites/kgoenglish/Pages/Services/MOH/PassengersHealth.aspx"],
  ["OMN", "B", "Ministry of Health", "Travel medical service / community awareness", "https://www.moh.gov.om/en/puffs/community-awareness-and-of-travel-medical-service/"],
  ["PAK", "B", "Polio Eradication Programme", "International polio vaccination certificate", "https://www.poliofreepakistan.gov.pk/certificate/vaccination-certificate"],
  ["PAK", "B", "Ministry of National Health Services", "Official ministry portal", "https://www.nhsrc.gov.pk/"],
  ["IND", "B", "Directorate General of Health Services", "Public Health / International Health", "https://dghs.mohfw.gov.in/phih.php"],
  ["IND", "B", "International Health / Points of Entry", "Yellow Fever vaccination / IHR", "https://ihpoe.mohfw.gov.in/test2025/vaccination.php"],
  ["SGP", "B", "Immigration & Checkpoints Authority", "Yellow Fever vaccination certificate / transit rule", "https://www.ica.gov.sg/enter-transit-depart/entering-singapore/yellow-fever-vaccination-certificate"],
  ["SGP", "B", "Immigration & Checkpoints Authority", "Entering Singapore - public health requirements", "https://www.ica.gov.sg/enter-transit-depart/entering-singapore"],
  ["SGP", "B", "Communicable Diseases Agency", "Yellow Fever", "https://www.cda.gov.sg/public/diseases/yellow-fever/"],
  ["MYS", "B", "Ministry of Health", "Yellow Fever", "https://www.moh.gov.my/en/core/health-information/yellow-fever"],
  ["MYS", "B", "Immigration Department", "Visa requirements by country / Yellow Fever certificate", "https://www.imi.gov.my/index.php/en/main-services/visa/visa-requirement-by-country/"],
  ["LKA", "B", "Department of Immigration & Emigration", "Yellow Fever certificate", "https://immigration.gov.lk/pages_e.php?id=22"],
  ["HKG", "B", "Travel Health Service", "Yellow Fever", "https://www.travelhealth.gov.hk/english/travel_related_diseases/yellow_fever.html"],
  ["HKG", "B", "Travel Health Service", "About / official service", "https://www.travelhealth.gov.hk/english/about_us/about_us.html"],
  ["TWN", "B", "Taiwan CDC", "International vaccination certificate", "https://www.cdc.gov.tw/En/Category/ListContent/YipvR33b32K-dsMI2eIrIg?uaid=RsH5qo4kmbfJfU5ProCOTQ"],
  ["ISR", "B", "Ministry of Health", "Diseases / vaccines for international travelers", "https://www.gov.il/en/departments/topics/diseases"],
  ["IDN", "B", "Ministry of Health", "International vaccination certificate / WHO standard", "https://www.kemkes.go.id/id/kemenkes-terbitkan-sertifikat-vaksin-internasional-sesuai-standar-who"],
  ["IDN", "B", "Ministry of Health / Port Health", "International quarantine / ICVP system", "https://sinkarkes.kemkes.go.id/"],
  ["THA", "B", "Department of Disease Control", "International/YF legal notifications", "https://ddc.moph.go.th/law_gcd_eng.php"],
  ["THA", "B", "Department of Disease Control", "Yellow Fever vaccination centers", "https://ddc.moph.go.th/dcd/pagecontent.php?dept=dcd&page=621"],
  ["JPN", "B", "Ministry of Health, Labour and Welfare", "Vaccination information for international visitors", "https://www.mhlw.go.jp/stf/english/posters-about-vaccination.html"],
  ["AUS", "B", "Department of Health", "2026 Yellow Fever fact sheet PDF", "https://www.health.gov.au/sites/default/files/2026-04/yellow-fever-fact-sheet.pdf"],
  ["AUS", "B", "Australian Immunisation Handbook", "Yellow Fever", "https://immunisationhandbook.health.gov.au/contents/vaccine-preventable-diseases/yellow-fever"],
  ["NZL", "B", "Health New Zealand", "Yellow Fever", "https://www.healthnz.govt.nz/health-topics/conditions-treatments/infectious-diseases/yellow-fever"],
  ["NZL", "B", "Health New Zealand", "Yellow Fever vaccine / authorized providers", "https://www.healthnz.govt.nz/health-topics/immunisations/vaccines-aotearoa/yellow-fever-vaccine"],
  ["NZL", "B", "Health New Zealand", "Border health measures and controls", "https://www.healthnz.govt.nz/health-professionals/guidance-standards/topic/border-health/border-health-surveillance-and-resources/border-health-measures-and-controls"],
  ["NZL", "B", "SafeTravel", "Infectious diseases / Yellow Fever", "https://www.safetravel.govt.nz/before-you-go/health/diseases"],
  ["FRA", "B", "Service-Public", "Travel vaccinations", "https://www.service-public.gouv.fr/particuliers/vosdroits/F720?lang=en"],
  ["FRA", "B", "Ministry of Health", "Health recommendations for travelers", "https://sante.gouv.fr/prevention-en-sante/sante-des-populations/article/recommandations-sanitaires-pour-les-voyageurs"],
  ["FRA", "B", "Ministry for Europe and Foreign Affairs", "Health while traveling", "https://www.diplomatie.gouv.fr/fr/informations-pratiques/preparer-son-depart/la-sante-en-voyage"],
  ["SWE", "B", "Public Health Agency", "Travel vaccinations", "https://www.folkhalsomyndigheten.se/the-public-health-agency-of-sweden/communicable-disease-control/vaccinations/travel-vaccinations/"],
  ["FIN", "B", "Suomi.fi", "Vaccinations for travelers", "https://www.suomi.fi/citizen/health-and-medical-care/staying-healthy/guide/vaccinations/vaccinations-for-travellers"],
  ["NOR", "B", "Norwegian Institute of Public Health", "Travel advice and vaccines", "https://www.fhi.no/en/in/travel/traveladvice-vaccines/"],
  ["CHE", "B", "Federal Office of Public Health", "Vaccinations and malaria prevention for international travel", "https://www.bag.admin.ch/en/vaccinations-and-malaria-prevention-for-international-travel"],
  ["IRL", "B", "Official tourism / government-supported", "Health information / vaccination requirement context", "https://www.ireland.com/en-us/help-and-advice/practical-information/health-information/"],
  ["GBR", "B", "NHS", "Travel vaccinations", "https://www.nhs.uk/vaccinations/travel-vaccinations/"],
  ["DZA", "C", "Ministry of Health", "Official ministry portal", "https://sante.gov.dz/"],
  ["BFA", "C", "Ministry of Health", "Official ministry portal", "https://www.sante.gov.bf/"],
  ["CPV", "C", "Ministry of Health", "Official ministry portal", "https://www.minsaude.gov.cv/"],
  ["CIV", "C", "Ministry of Health", "Official ministry portal", "https://www.sante.gouv.ci/"],
  ["SWZ", "C", "Ministry of Health", "Official ministry portal", "https://www.gov.sz/index.php/ministries-departments/ministry-of-health"],
  ["GIN", "C", "Ministry of Health", "Official ministry portal", "https://sante.gov.gn/"],
  ["MDG", "C", "Ministry of Public Health", "Official ministry portal", "https://www.sante.gov.mg/"],
  ["MAR", "C", "Ministry of Health and Social Protection", "Official ministry portal", "https://www.sante.gov.ma/"],
  ["MOZ", "C", "Ministry of Health", "Official ministry portal", "https://www.misau.gov.mz/"],
  ["NER", "C", "Ministry of Public Health", "Official ministry portal", "https://sante.gouv.ne/"],
  ["TGO", "C", "Ministry of Health", "Official ministry portal", "https://sante.gouv.tg/"],
  ["ARG", "C", "Ministry of Health", "Official ministry portal", "https://www.argentina.gob.ar/salud"],
  ["BOL", "C", "Ministry of Health and Sports", "Official ministry portal", "https://www.minsalud.gob.bo/"],
  ["CAN", "C", "Government of Canada", "Travel health and safety", "https://travel.gc.ca/travelling/health-safety"],
  ["CHL", "C", "Ministry of Health", "Official ministry portal", "https://www.minsal.cl/"],
  ["ECU", "C", "Ministry of Public Health", "Official ministry portal", "https://www.salud.gob.ec/"],
  ["GTM", "C", "Ministry of Public Health", "Official ministry portal", "https://www.mspas.gob.gt/"],
  ["HND", "C", "Secretariat of Health", "Official health portal", "https://www.salud.gob.hn/"],
  ["MEX", "C", "Secretariat of Health", "Official ministry portal", "https://www.gob.mx/salud"],
  ["URY", "C", "Ministry of Public Health", "Official ministry portal", "https://www.gub.uy/ministerio-salud-publica/"],
  ["BGD", "C", "Ministry of Health and Family Welfare", "Official ministry portal", "https://mohfw.gov.bd/"],
  ["BTN", "C", "Ministry of Health", "Official ministry portal", "https://www.moh.gov.bt/"],
  ["BRN", "C", "Ministry of Health", "Official ministry portal", "https://www.moh.gov.bn/"],
  ["KHM", "C", "Ministry of Health", "Official ministry portal", "https://moh.gov.kh/"],
  ["JOR", "C", "Ministry of Health", "Official ministry portal", "https://moh.gov.jo/"],
  ["LBN", "C", "Ministry of Public Health", "Official ministry portal", "https://www.moph.gov.lb/"],
  ["MDV", "C", "Ministry of Health", "Official ministry portal", "https://health.gov.mv/"],
  ["NPL", "C", "Ministry of Health and Population", "Official ministry portal", "https://mohp.gov.np/"],
  ["PHL", "C", "Department of Health", "Official health portal", "https://doh.gov.ph/"],
  ["QAT", "C", "Ministry of Public Health", "Official ministry portal", "https://www.moph.gov.qa/"],
  ["ARE", "C", "Ministry of Health and Prevention", "Official ministry portal", "https://mohap.gov.ae/"],
  ["VNM", "C", "Ministry of Health", "Official ministry portal", "https://moh.gov.vn/"],
  ["AUT", "C", "Federal Ministry / Health portal", "Official public-health portal", "https://www.sozialministerium.at/"],
  ["BEL", "C", "FPS Public Health", "Official health portal", "https://www.health.belgium.be/"],
  ["DNK", "C", "Danish Health Authority", "Official health authority", "https://www.sst.dk/en"],
  ["DEU", "C", "Federal Ministry of Health", "Official ministry portal", "https://www.bundesgesundheitsministerium.de/"],
  ["ITA", "C", "Ministry of Health", "Official ministry portal", "https://www.salute.gov.it/"],
  ["NLD", "C", "Government of Netherlands", "Health ministry / public health", "https://www.government.nl/ministries/ministry-of-health-welfare-and-sport"],
  ["POL", "C", "Ministry of Health", "Official ministry portal", "https://www.gov.pl/web/zdrowie"],
  ["PRT", "C", "Directorate-General of Health", "Official health authority", "https://www.dgs.pt/"],
  ["ESP", "C", "Ministry of Health", "Official ministry portal", "https://www.sanidad.gob.es/"],
  ["TUR", "C", "Ministry of Health", "Official ministry portal", "https://www.saglik.gov.tr/"],
  ["FJI", "C", "Ministry of Health and Medical Services", "Official ministry portal", "https://www.health.gov.fj/"],
  ["PNG", "C", "National Department of Health", "Official health portal", "https://www.health.gov.pg/"],
  ["WSM", "C", "Ministry of Health", "Official ministry portal", "https://www.health.gov.ws/"],
  ["AFG", "D", "WHO", "WHO country profile", "https://www.who.int/countries/afg"],
  ["ALB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/alb"],
  ["DZA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/dza"],
  ["AND", "D", "WHO", "WHO country profile", "https://www.who.int/countries/and"],
  ["AGO", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ago"],
  ["ATG", "D", "WHO", "WHO country profile", "https://www.who.int/countries/atg"],
  ["ARG", "D", "WHO", "WHO country profile", "https://www.who.int/countries/arg"],
  ["ARM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/arm"],
  ["AUS", "D", "WHO", "WHO country profile", "https://www.who.int/countries/aus"],
  ["AUT", "D", "WHO", "WHO country profile", "https://www.who.int/countries/aut"],
  ["AZE", "D", "WHO", "WHO country profile", "https://www.who.int/countries/aze"],
  ["BHS", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bhs"],
  ["BHR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bhr"],
  ["BGD", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bgd"],
  ["BRB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/brb"],
  ["BLR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/blr"],
  ["BEL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bel"],
  ["BLZ", "D", "WHO", "WHO country profile", "https://www.who.int/countries/blz"],
  ["BEN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ben"],
  ["BTN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/btn"],
  ["BOL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bol"],
  ["BIH", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bih"],
  ["BWA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bwa"],
  ["BRA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bra"],
  ["BRN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/brn"],
  ["BGR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bgr"],
  ["BFA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bfa"],
  ["BDI", "D", "WHO", "WHO country profile", "https://www.who.int/countries/bdi"],
  ["CPV", "D", "WHO", "WHO country profile", "https://www.who.int/countries/cpv"],
  ["KHM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/khm"],
  ["CMR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/cmr"],
  ["CAN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/can"],
  ["CAF", "D", "WHO", "WHO country profile", "https://www.who.int/countries/caf"],
  ["TCD", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tcd"],
  ["CHL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/chl"],
  ["CHN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/chn"],
  ["COL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/col"],
  ["COM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/com"],
  ["COG", "D", "WHO", "WHO country profile", "https://www.who.int/countries/cog"],
  ["COK", "D", "WHO", "WHO country profile", "https://www.who.int/countries/cok"],
  ["CRI", "D", "WHO", "WHO country profile", "https://www.who.int/countries/cri"],
  ["CIV", "D", "WHO", "WHO country profile", "https://www.who.int/countries/civ"],
  ["HRV", "D", "WHO", "WHO country profile", "https://www.who.int/countries/hrv"],
  ["CUB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/cub"],
  ["CYP", "D", "WHO", "WHO country profile", "https://www.who.int/countries/cyp"],
  ["CZE", "D", "WHO", "WHO country profile", "https://www.who.int/countries/cze"],
  ["PRK", "D", "WHO", "WHO country profile", "https://www.who.int/countries/prk"],
  ["COD", "D", "WHO", "WHO country profile", "https://www.who.int/countries/cod"],
  ["DNK", "D", "WHO", "WHO country profile", "https://www.who.int/countries/dnk"],
  ["DJI", "D", "WHO", "WHO country profile", "https://www.who.int/countries/dji"],
  ["DMA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/dma"],
  ["DOM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/dom"],
  ["ECU", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ecu"],
  ["EGY", "D", "WHO", "WHO country profile", "https://www.who.int/countries/egy"],
  ["SLV", "D", "WHO", "WHO country profile", "https://www.who.int/countries/slv"],
  ["GNQ", "D", "WHO", "WHO country profile", "https://www.who.int/countries/gnq"],
  ["ERI", "D", "WHO", "WHO country profile", "https://www.who.int/countries/eri"],
  ["EST", "D", "WHO", "WHO country profile", "https://www.who.int/countries/est"],
  ["SWZ", "D", "WHO", "WHO country profile", "https://www.who.int/countries/swz"],
  ["ETH", "D", "WHO", "WHO country profile", "https://www.who.int/countries/eth"],
  ["FJI", "D", "WHO", "WHO country profile", "https://www.who.int/countries/fji"],
  ["FIN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/fin"],
  ["FRA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/fra"],
  ["GAB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/gab"],
  ["GMB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/gmb"],
  ["GEO", "D", "WHO", "WHO country profile", "https://www.who.int/countries/geo"],
  ["DEU", "D", "WHO", "WHO country profile", "https://www.who.int/countries/deu"],
  ["GHA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/gha"],
  ["GRC", "D", "WHO", "WHO country profile", "https://www.who.int/countries/grc"],
  ["GRD", "D", "WHO", "WHO country profile", "https://www.who.int/countries/grd"],
  ["GTM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/gtm"],
  ["GIN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/gin"],
  ["GNB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/gnb"],
  ["GUY", "D", "WHO", "WHO country profile", "https://www.who.int/countries/guy"],
  ["HTI", "D", "WHO", "WHO country profile", "https://www.who.int/countries/hti"],
  ["HND", "D", "WHO", "WHO country profile", "https://www.who.int/countries/hnd"],
  ["HUN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/hun"],
  ["ISL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/isl"],
  ["IND", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ind"],
  ["IDN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/idn"],
  ["IRN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/irn"],
  ["IRQ", "D", "WHO", "WHO country profile", "https://www.who.int/countries/irq"],
  ["IRL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/irl"],
  ["ISR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/isr"],
  ["ITA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ita"],
  ["JAM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/jam"],
  ["JPN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/jpn"],
  ["JOR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/jor"],
  ["KAZ", "D", "WHO", "WHO country profile", "https://www.who.int/countries/kaz"],
  ["KEN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ken"],
  ["KIR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/kir"],
  ["KWT", "D", "WHO", "WHO country profile", "https://www.who.int/countries/kwt"],
  ["KGZ", "D", "WHO", "WHO country profile", "https://www.who.int/countries/kgz"],
  ["LAO", "D", "WHO", "WHO country profile", "https://www.who.int/countries/lao"],
  ["LVA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/lva"],
  ["LBN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/lbn"],
  ["LSO", "D", "WHO", "WHO country profile", "https://www.who.int/countries/lso"],
  ["LBR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/lbr"],
  ["LBY", "D", "WHO", "WHO country profile", "https://www.who.int/countries/lby"],
  ["LTU", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ltu"],
  ["LUX", "D", "WHO", "WHO country profile", "https://www.who.int/countries/lux"],
  ["MDG", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mdg"],
  ["MWI", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mwi"],
  ["MYS", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mys"],
  ["MDV", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mdv"],
  ["MLI", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mli"],
  ["MLT", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mlt"],
  ["MHL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mhl"],
  ["MRT", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mrt"],
  ["MUS", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mus"],
  ["MEX", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mex"],
  ["FSM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/fsm"],
  ["MCO", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mco"],
  ["MNG", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mng"],
  ["MNE", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mne"],
  ["MAR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mar"],
  ["MOZ", "D", "WHO", "WHO country profile", "https://www.who.int/countries/moz"],
  ["MMR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mmr"],
  ["NAM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/nam"],
  ["NRU", "D", "WHO", "WHO country profile", "https://www.who.int/countries/nru"],
  ["NPL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/npl"],
  ["NLD", "D", "WHO", "WHO country profile", "https://www.who.int/countries/nld"],
  ["NZL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/nzl"],
  ["NIC", "D", "WHO", "WHO country profile", "https://www.who.int/countries/nic"],
  ["NER", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ner"],
  ["NGA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/nga"],
  ["NIU", "D", "WHO", "WHO country profile", "https://www.who.int/countries/niu"],
  ["MKD", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mkd"],
  ["NOR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/nor"],
  ["OMN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/omn"],
  ["PAK", "D", "WHO", "WHO country profile", "https://www.who.int/countries/pak"],
  ["PLW", "D", "WHO", "WHO country profile", "https://www.who.int/countries/plw"],
  ["PAN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/pan"],
  ["PNG", "D", "WHO", "WHO country profile", "https://www.who.int/countries/png"],
  ["PRY", "D", "WHO", "WHO country profile", "https://www.who.int/countries/pry"],
  ["PER", "D", "WHO", "WHO country profile", "https://www.who.int/countries/per"],
  ["PHL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/phl"],
  ["POL", "D", "WHO", "WHO country profile", "https://www.who.int/countries/pol"],
  ["PRT", "D", "WHO", "WHO country profile", "https://www.who.int/countries/prt"],
  ["QAT", "D", "WHO", "WHO country profile", "https://www.who.int/countries/qat"],
  ["KOR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/kor"],
  ["MDA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/mda"],
  ["ROU", "D", "WHO", "WHO country profile", "https://www.who.int/countries/rou"],
  ["RUS", "D", "WHO", "WHO country profile", "https://www.who.int/countries/rus"],
  ["RWA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/rwa"],
  ["KNA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/kna"],
  ["LCA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/lca"],
  ["VCT", "D", "WHO", "WHO country profile", "https://www.who.int/countries/vct"],
  ["WSM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/wsm"],
  ["SMR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/smr"],
  ["STP", "D", "WHO", "WHO country profile", "https://www.who.int/countries/stp"],
  ["SAU", "D", "WHO", "WHO country profile", "https://www.who.int/countries/sau"],
  ["SEN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/sen"],
  ["SRB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/srb"],
  ["SYC", "D", "WHO", "WHO country profile", "https://www.who.int/countries/syc"],
  ["SLE", "D", "WHO", "WHO country profile", "https://www.who.int/countries/sle"],
  ["SGP", "D", "WHO", "WHO country profile", "https://www.who.int/countries/sgp"],
  ["SVK", "D", "WHO", "WHO country profile", "https://www.who.int/countries/svk"],
  ["SVN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/svn"],
  ["SLB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/slb"],
  ["SOM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/som"],
  ["ZAF", "D", "WHO", "WHO country profile", "https://www.who.int/countries/zaf"],
  ["SSD", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ssd"],
  ["ESP", "D", "WHO", "WHO country profile", "https://www.who.int/countries/esp"],
  ["LKA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/lka"],
  ["SDN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/sdn"],
  ["SUR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/sur"],
  ["SWE", "D", "WHO", "WHO country profile", "https://www.who.int/countries/swe"],
  ["CHE", "D", "WHO", "WHO country profile", "https://www.who.int/countries/che"],
  ["SYR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/syr"],
  ["TJK", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tjk"],
  ["THA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tha"],
  ["TLS", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tls"],
  ["TGO", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tgo"],
  ["TON", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ton"],
  ["TTO", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tto"],
  ["TUN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tun"],
  ["TUR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tur"],
  ["TKM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tkm"],
  ["TUV", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tuv"],
  ["UGA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/uga"],
  ["UKR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ukr"],
  ["ARE", "D", "WHO", "WHO country profile", "https://www.who.int/countries/are"],
  ["GBR", "D", "WHO", "WHO country profile", "https://www.who.int/countries/gbr"],
  ["TZA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/tza"],
  ["USA", "D", "WHO", "WHO country profile", "https://www.who.int/countries/usa"],
  ["URY", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ury"],
  ["UZB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/uzb"],
  ["VUT", "D", "WHO", "WHO country profile", "https://www.who.int/countries/vut"],
  ["VEN", "D", "WHO", "WHO country profile", "https://www.who.int/countries/ven"],
  ["VNM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/vnm"],
  ["YEM", "D", "WHO", "WHO country profile", "https://www.who.int/countries/yem"],
  ["ZMB", "D", "WHO", "WHO country profile", "https://www.who.int/countries/zmb"],
  ["ZWE", "D", "WHO", "WHO country profile", "https://www.who.int/countries/zwe"],
];
