import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ReferenceLine, XAxis, YAxis } from "recharts";
import { HeaderBar } from "@/components/insight/HeaderBar";
import { MetricCard } from "@/components/insight/MetricCard";
import { ChartBlock } from "@/components/insight/ChartBlock";
import { SectionPanel } from "@/components/insight/SectionPanel";
import { Sidebar } from "@/components/insight/Sidebar";
import { GlassCard } from "@/components/insight/GlassCard";
import { useInsightData, useSelectedCompany } from "@/data/useInsightData";

const idsContractRiskData = [{ name: "Iraq / Camp Taji", value: 27.9 }, { name: "Djibouti", value: 8 }, { name: "Jordan", value: 6 }, { name: "DECO", value: 4 }];
const idsInjuryCostData = [{ name: "DECO Guards", direct: 320, additional: 240 }, { name: "Tactical Trainers", direct: 320, additional: 320 }, { name: "Exped. Support", direct: 160, additional: 120 }, { name: "Cyber / Office", direct: 30, additional: 30 }];
const idsTrirData = [{ name: "DECO Guards", trir: 1.1 }, { name: "Tactical Trainers", trir: 2.5 }, { name: "Exped. Support", trir: 2.0 }, { name: "Cyber / Office", trir: 0.5 }];
const kbrEucomRiskData = [{ name: "Poland", value: 8 }, { name: "Romania", value: 7 }, { name: "Latvia", value: 8 }, { name: "Lithuania", value: 8 }, { name: "Bulgaria", value: 5 }, { name: "Kosovo", value: 6 }, { name: "Germany", value: 3 }, { name: "Italy", value: 2 }, { name: "Türkiye", value: 5 }];
const kbrRevenueData = [{ name: "Pre-Employment", value: 1375 }, { name: "DBA Pre-Deploy", value: 1350 }, { name: "Hearing", value: 325 }, { name: "Respirator", value: 150 }, { name: "DOT CDL", value: 132 }, { name: "Behavioral", value: 325 }];
const kbrTrirSegmentData = [{ name: "STS Chem/Const", trir: 3.5 }, { name: "LOGCAP OCONUS", trir: 2.5 }, { name: "Govt Tech/SCI", trir: 0.7 }, { name: "Intel/Cyber", trir: 0.5 }, { name: "HQ/Corporate", trir: 0.4 }];
const kbrTrirTrendData = [{ year: "2023", kbr: 0.04 }, { year: "2024", kbr: 0.05 }, { year: "2025", kbr: 0.04 }];
const kbrPenaltiesData = [{ name: "FCPA", value: 579 }, { name: "False Claims", value: 108.75 }, { name: "FCA", value: 13.67 }, { name: "Wage & Hour", value: 8.51 }, { name: "OSHA", value: 0.09 }];
const paeAcquisitionData = [{ name: "Revenue ($B)", amentum: 6, added: 3 }, { name: "Employees (K)", amentum: 35, added: 18 }];
const paeRevenueData = [{ name: "USCIS/CBP", value: 140 }, { name: "Army CFT", value: 95 }, { name: "OCONUS DBA", value: 170 }, { name: "Fresno CFT", value: 50 }];
const paeOconusData = [{ name: "State/Embassy", value: 3000 }, { name: "Afghanistan", value: 4500 }, { name: "Africa", value: 1500 }, { name: "Iraq/CENTCOM", value: 2500 }, { name: "Europe BOS", value: 2000 }];
const paeTrirData = [{ name: "USCIS/CBP", trir: 0.8 }, { name: "Army CFT", trir: 3.4 }, { name: "OCONUS BOS", trir: 2.5 }, { name: "DOS Overseas", trir: 2.0 }, { name: "Training/Tech", trir: 0.6 }];
const paeBiometricRiskData = [{ name: "Disease", severity: 4, frequency: 5 }, { name: "Ergonomic", severity: 3, frequency: 5 }, { name: "Stress", severity: 4, frequency: 4 }, { name: "Needle-stick", severity: 2, frequency: 3 }, { name: "Skin contact", severity: 2, frequency: 3 }];
const s3AircraftNoiseData = [{ name: "AH-64E", noise: 115 }, { name: "UH-60M", noise: 112 }, { name: "AH-6I", noise: 108 }, { name: "MD-530F", noise: 105 }, { name: "CH-47F", noise: 118 }];
const s3HazardGapData = [{ name: "Extreme Heat", severity: 5, gap: 4 }, { name: "JP-8/Skydrol", severity: 4, gap: 4 }, { name: "Helicopter Noise", severity: 4, gap: 3 }, { name: "Lead Exposure", severity: 3, gap: 4 }, { name: "Aviation Fatality", severity: 5, gap: 3 }, { name: "DBA Liability", severity: 5, gap: 5 }];
const s3LocationData = [{ name: "Saudi Arabia", workers: 300 }, { name: "Africa/MENA", workers: 80 }, { name: "S/SE Asia", workers: 60 }, { name: "Europe/NATO", workers: 40 }, { name: "CONUS", workers: 200 }];
const s3RevenueData = [{ name: "DBA Pre-Deploy", value: 220 }, { name: "Heat Illness", value: 40 }, { name: "Hearing", value: 32 }, { name: "JP-8", value: 48 }, { name: "Lead", value: 28 }, { name: "Pilot Physicals", value: 26 }, { name: "Pre-Employment", value: 20 }];
const traceCcmdRiskData = [{ name: "CENTCOM", risk: 9 }, { name: "EUCOM", risk: 7 }, { name: "AFRICOM", risk: 6 }, { name: "INDOPACOM", risk: 5 }, { name: "NORTHCOM", risk: 2 }];
const traceContractData = [{ name: "Pre-2024", value: 40 }, { name: "FY2024", value: 60 }, { name: "VSAT IV", value: 352 }, { name: "Global FSR", value: 564 }, { name: "2025 Total", value: 937 }];
const traceGrowthData = [{ name: "Current", total: 350, oconus: 180 }, { name: "VSAT IV", total: 550, oconus: 310 }, { name: "Global FSR", total: 900, oconus: 600 }, { name: "AFCENT", total: 1150, oconus: 750 }];
const traceHazardData = [{ name: "RF/EMF", severity: 4, frequency: 5 }, { name: "Falls", severity: 3, frequency: 3 }, { name: "Heat Stress", severity: 4, frequency: 4 }, { name: "Blast/Noise", severity: 3, frequency: 2 }, { name: "DBA Hostile", severity: 4, frequency: 5 }, { name: "Ergonomic", severity: 3, frequency: 5 }];
const traceRevenueData = [{ name: "DBA Pre-Deploy", current: 76, projected: 262 }, { name: "Pre-Employment", current: 20, projected: 89 }, { name: "RF/EMF", current: 65, projected: 170 }, { name: "CRC Medicals", current: 0, projected: 118 }, { name: "Hearing", current: 16, projected: 32 }];

function formatYAxis(value: number) { return Number.isInteger(value) ? `${value}` : value.toFixed(1); }

export default function DataProfiles() {
  const { dataset } = useInsightData();
  const { companyId, setCompanyId, company } = useSelectedCompany(dataset.companies);
  const profile = dataset.profiles.find((item) => item.companyId === companyId) || dataset.profiles[0];
  const isIds = companyId === "ids";
  const isKbr = companyId === "kbr";
  const isPae = companyId === "pae-amentum";
  const isS3 = companyId === "s3-international";
  const isTrace = companyId === "trace-systems";
  const companyMetrics = dataset.metrics.filter((metric) => metric.companyId === companyId || (companyId !== "v2x" && metric.companyId === "v2x")).slice(0, 6);
  const chartData = companyMetrics.map((metric) => ({ name: metric.label.replace("Estimated annual ", "").slice(0, 16), value: metric.unit === "usd" ? metric.value / 1000000 : metric.value }));
  const sources = dataset.sources.filter((source) => source.companyId === companyId || source.companyId === "v2x");
  const companyLocations = dataset.locations.filter((location) => location.companyId === companyId);
  const idsSignals = [{ label: "Contract value at risk", value: "$45.9M", note: "One preventable event may trigger stop-work exposure across four contract/location groups." }, { label: "Worker population", value: "~1,300", note: "Modeled across guards, trainers, expeditionary support, and cyber/office." }, { label: "Annual injury cost", value: "$1.1M-$1.5M", note: "Estimated annual injury cost exposure from uploaded visual." }, { label: "Highest TRIR", value: "2.5", note: "Tactical trainers carry the highest benchmarked risk." }];
  const kbrSignals = [{ label: "Revenue potential", value: "$3.657M", note: "Modeled annual Occu-Med revenue opportunity." }, { label: "Peak EUCOM risk", value: "8/10", note: "Poland, Latvia, and Lithuania are highest-risk nodes." }, { label: "Worker population", value: "~38K", note: "Modeled across five workforce categories." }, { label: "Compliance exposure", value: "$710M", note: "Penalty model dominated by FCPA and False Claims Act categories." }];
  const paeSignals = [{ label: "Combined scale", value: "$9B / 53K", note: "Amentum plus PAE modeled combined scale." }, { label: "PAE added", value: "$3B / 18K", note: "PAE added revenue and workers to Amentum baseline." }, { label: "Legacy revenue", value: "$455K/yr", note: "Modeled revenue across legacy program lanes." }, { label: "Worker-risk peak", value: "TRIR 3.4", note: "Army CFT aviation mechanics are highest-risk category." }];
  const s3Signals = [{ label: "Peak aircraft noise", value: "118 dB", note: "All platforms exceed OSHA action lines." }, { label: "Saudi risk node", value: "300 / 9-10", note: "Largest and highest-risk international workforce node." }, { label: "Revenue potential", value: "$414K/yr", note: "DBA pre-deploy is the largest modeled lane." }, { label: "Hazard gap", value: "5/5", note: "DBA unlimited medical liability has maximum gap score." }];
  const traceSignals = [{ label: "Award surge", value: "$937M", note: "2025 total awards modeled across VSAT IV and Global FSR." }, { label: "Projected workforce", value: "1,150", note: "Projected total workforce by 2026-2027." }, { label: "OCONUS DBA", value: "750", note: "Projected DBA-covered OCONUS headcount." }, { label: "Revenue upside", value: "$671K/yr", note: "Projected 2027 Occu-Med revenue potential." }];
  const defaultSignals = [{ label: "Global workforce exposure", value: `${(company?.employees || 0).toLocaleString()} employees`, note: "Large distributed workforce creates broad service aperture." }, { label: "WC reserve signal", value: "$9.5M", note: "Public reserve/accrual disclosure elevates claims-control relevance." }, { label: "Footprint intensity", value: `${companyLocations.length || dataset.locations.length} mapped sites`, note: "Workbook geography indicates multi-region complexity." }, { label: "Operating environment", value: "High complexity", note: "Defense and overseas support increase readiness needs." }];
  const executiveSignals = isIds ? idsSignals : isKbr ? kbrSignals : isPae ? paeSignals : isS3 ? s3Signals : isTrace ? traceSignals : defaultSignals;
  const curveTitle = isIds ? "IDS financial exposure curve" : isKbr ? "KBR opportunity and risk curve" : isPae ? "PAE acquisition and legacy opportunity curve" : isS3 ? "S3 aviation hazard and revenue curve" : isTrace ? "Trace growth and readiness curve" : `${company?.shortName || "Company"} exposure curve`;
  const curveSubtitle = isTrace ? "Award surge, workforce growth, OCONUS DBA exposure, and revenue upside normalized for executive scanning." : isS3 ? "Aviation noise, Saudi risk, worker deployment, and revenue potential normalized for executive scanning." : isPae ? "Acquisition scale, legacy revenue, OCONUS headcount, and worker-risk values normalized for executive scanning." : isIds ? "Contract value, worker population, injury cost, and safety benchmark values normalized for executive scanning." : isKbr ? "Revenue potential, country risk, worker risk, TRIR, and penalty exposure normalized for executive scanning." : "Workbook values normalized for executive scanability.";
  return (
    <main className="aurora-bg min-h-screen text-white"><Sidebar /><section className="relative z-10 px-5 py-8 lg:ml-[210px] lg:px-12">
      <HeaderBar eyebrow="Portal 01" title="Data Profiles" subtitle="Reusable company intelligence dossiers with expandable source-backed sections, executive metrics, and structured records for future company uploads." actions={<select value={companyId} onChange={(event) => setCompanyId(event.target.value)} className="rounded-full border border-cyan-100/15 bg-[#07111d] px-4 py-2 text-sm text-cyan-50 outline-none">{dataset.companies.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>} />
      <GlassCard className="executive-strip mb-5 p-5"><div className="mb-4 flex items-center justify-between gap-5"><div><p className="text-xs uppercase tracking-[0.28em] text-emerald-200/70">Key intelligence signals</p><h2 className="mt-2 text-2xl font-black text-white">{company?.shortName} executive readout</h2></div><span className="rounded-full border border-cyan-100/18 bg-cyan-200/10 px-4 py-2 text-xs text-cyan-50/75">Live dossier view</span></div><div className="grid gap-3 md:grid-cols-4">{executiveSignals.map((signal) => <div key={signal.label} className="rounded-2xl border border-cyan-100/12 bg-black/18 p-4 shadow-[inset_0_0_24px_rgba(45,212,191,.06)]"><p className="text-[10px] uppercase tracking-[0.22em] text-cyan-100/42">{signal.label}</p><p className="mt-2 text-lg font-black text-cyan-50">{signal.value}</p><p className="mt-2 text-xs leading-5 text-cyan-100/58">{signal.note}</p></div>)}</div></GlassCard>
      <div className="grid gap-4 md:grid-cols-3">{companyMetrics.map((metric) => <MetricCard key={metric.id} metric={metric} />)}</div>
      <div className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><ChartBlock title={curveTitle} subtitle={curveSubtitle}><AreaChart data={chartData}><defs><linearGradient id="profileGlow" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#5eead4" stopOpacity={0.45} /><stop offset="95%" stopColor="#5eead4" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.08)" /><XAxis dataKey="name" stroke="rgba(207,250,254,.45)" tick={{ fontSize: 11 }} /><YAxis stroke="rgba(207,250,254,.45)" tick={{ fontSize: 11 }} /><Area type="monotone" dataKey="value" stroke="#67e8f9" fill="url(#profileGlow)" strokeWidth={2} /></AreaChart></ChartBlock><GlassCard className="p-6"><p className="text-xs uppercase tracking-[0.25em] text-emerald-200/60">Company dossier</p><h2 className="mt-2 text-2xl font-black text-white">{company?.name}</h2><p className="mt-3 text-sm leading-6 text-cyan-100/60">{company?.summary}</p><div className="mt-5 flex flex-wrap gap-2">{company?.tags.map((tag) => <span key={tag} className="rounded-full border border-cyan-100/15 bg-cyan-100/5 px-3 py-1 text-xs text-cyan-50/70">{tag}</span>)}</div></GlassCard></div>
      {isIds ? <div className="mt-5 grid gap-5 xl:grid-cols-3"><BarPanel title="IDS contract value at risk" subtitle="Source: uploaded IDS visual; value at risk shown in $M." data={idsContractRiskData} dataKey="value" formatter="$M" color="#f97316" /><StackedPanel title="IDS estimated annual injury cost" subtitle="Source: uploaded IDS visual; values shown in $K." data={idsInjuryCostData} a="direct" b="additional" aLabel="Direct low" bLabel="High additional" /><BarPanel title="IDS worker risk: TRIR benchmark" subtitle="Source: uploaded IDS visual; TRIR benchmark." data={idsTrirData} dataKey="trir" color="#dc2626" /></div> : null}
      {isKbr ? <div className="mt-5 grid gap-5 xl:grid-cols-2"><BarPanel title="KBR LOGCAP EUCOM hostile-environment risk" subtitle="Source: uploaded KBR visual; country risk 1-10." data={kbrEucomRiskData} dataKey="value" color="#ef4444" domain={[0,10]} /><BarPanel title="KBR Occu-Med annual revenue potential" subtitle="Source: uploaded KBR visual; annual revenue shown in $K." data={kbrRevenueData} dataKey="value" formatter="$K" color="#22d3ee" /><BarPanel title="KBR worker risk by TRIR segment" subtitle="Source: uploaded KBR visual; segment benchmark." data={kbrTrirSegmentData} dataKey="trir" color="#f97316" /><ChartBlock title="KBR TRIR trend vs portfolio peers" subtitle="Source: uploaded KBR visual; benchmark reference lines."><LineChart data={kbrTrirTrendData}><CartesianGrid stroke="rgba(255,255,255,.08)" /><XAxis dataKey="year" stroke="rgba(207,250,254,.45)" tick={{ fontSize: 11 }} /><YAxis stroke="rgba(207,250,254,.45)" tick={{ fontSize: 11 }} domain={[0,1.5]} /><ReferenceLine y={1.4} stroke="#94a3b8" strokeDasharray="4 4" /><ReferenceLine y={0.69} stroke="#ef4444" strokeDasharray="4 4" /><ReferenceLine y={0.33} stroke="#38bdf8" strokeDasharray="4 4" /><ReferenceLine y={0.31} stroke="#f97316" strokeDasharray="4 4" /><Line type="monotone" dataKey="kbr" stroke="#22c55e" strokeWidth={3} dot={{ r: 4 }} /></LineChart></ChartBlock><div className="xl:col-span-2"><BarPanel title="KBR cumulative violation penalties" subtitle="Source: uploaded KBR visual; penalties shown in $M." data={kbrPenaltiesData} dataKey="value" formatter="$M" color="#dc2626" /></div></div> : null}
      {isPae ? <div className="mt-5 grid gap-5 xl:grid-cols-2"><StackedPanel title="PAE acquisition impact" subtitle="Source: uploaded PAE visual; Amentum baseline plus PAE added." data={paeAcquisitionData} a="amentum" b="added" aLabel="Amentum" bLabel="PAE added" /><BarPanel title="PAE legacy revenue potential" subtitle="Source: uploaded PAE visual; $K/yr." data={paeRevenueData} dataKey="value" formatter="$K" color="#22d3ee" /><BarPanel title="PAE historical peak OCONUS headcount" subtitle="Source: uploaded PAE visual; peak deployed workers." data={paeOconusData} dataKey="value" color="#dc2626" /><BarPanel title="PAE legacy worker TRIR by type" subtitle="Source: uploaded PAE visual; BLS TRIR benchmark." data={paeTrirData} dataKey="trir" color="#f97316" /><div className="xl:col-span-2"><StackedPanel title="USCIS/CBP biometric worker risk" subtitle="Source: uploaded PAE visual; severity vs frequency." data={paeBiometricRiskData} a="severity" b="frequency" aLabel="Severity" bLabel="Frequency" grouped /></div></div> : null}
      {isS3 ? <div className="mt-5 grid gap-5 xl:grid-cols-2"><ChartBlock title="S3 aircraft fleet noise vs OSHA thresholds" subtitle="Source: uploaded S3 visual; maintenance/run-up noise in dB."><BarChart data={s3AircraftNoiseData}><CartesianGrid stroke="rgba(255,255,255,.08)" /><XAxis dataKey="name" stroke="rgba(207,250,254,.45)" tick={{ fontSize: 10 }} /><YAxis stroke="rgba(207,250,254,.45)" tick={{ fontSize: 11 }} domain={[0,125]} /><ReferenceLine y={85} stroke="#f59e0b" strokeDasharray="4 4" /><ReferenceLine y={90} stroke="#ef4444" strokeDasharray="4 4" /><Bar dataKey="noise" fill="#22d3ee" radius={[10,10,0,0]} /></BarChart></ChartBlock><StackedPanel title="S3 Saudi hazard severity vs Occu-Med gap" subtitle="Source: uploaded S3 visual; scores 1-5." data={s3HazardGapData} a="severity" b="gap" aLabel="Severity" bLabel="Gap" grouped /><BarPanel title="S3 workforce deployment by location" subtitle="Source: uploaded S3 visual; worker count by location." data={s3LocationData} dataKey="workers" color="#dc2626" /><BarPanel title="S3 Occu-Med revenue potential" subtitle="Source: uploaded S3 visual; annual revenue in $K." data={s3RevenueData} dataKey="value" formatter="$K" color="#22d3ee" /></div> : null}
      {isTrace ? <div className="mt-5 grid gap-5 xl:grid-cols-2"><BarPanel title="Trace FSR OCONUS risk by combatant command" subtitle="Source: uploaded Trace visual; hostile environment risk 1-10." data={traceCcmdRiskData} dataKey="risk" color="#f97316" domain={[0,10]} /><BarPanel title="Trace Systems contract award surge" subtitle="Source: uploaded Trace visual; contract value shown in $M." data={traceContractData} dataKey="value" formatter="$M" color="#dc2626" /><StackedPanel title="Trace workforce growth projection" subtitle="Source: uploaded Trace visual; total workforce and OCONUS DBA-covered headcount." data={traceGrowthData} a="oconus" b="total" aLabel="OCONUS DBA-covered" bLabel="Total workforce" /><StackedPanel title="Trace FSR occupational hazards" subtitle="Source: uploaded Trace visual; severity vs frequency scored 1-5." data={traceHazardData} a="severity" b="frequency" aLabel="Severity" bLabel="Frequency" grouped /><div className="xl:col-span-2"><StackedPanel title="Trace Systems Occu-Med revenue now vs 2027" subtitle="Source: uploaded Trace visual; current vs projected annual revenue shown in $K." data={traceRevenueData} a="current" b="projected" aLabel="Current 2025" bLabel="Projected 2027" grouped /></div></div> : null}
      <div className="mt-5 space-y-4">{profile.sections.map((section, index) => (<SectionPanel key={section.id} title={section.title} narrative={section.narrative} defaultOpen={index < 2}><div className="grid gap-4 md:grid-cols-[1fr_.8fr]"><ul className="space-y-2 text-sm text-cyan-50/72">{section.bullets.map((bullet) => <li key={bullet} className="rounded-2xl border border-cyan-100/10 bg-white/[0.03] px-4 py-3">{bullet}</li>)}</ul><div className="grid gap-3">{section.metrics.map((id) => dataset.metrics.find((metric) => metric.id === id)).filter(Boolean).map((metric) => metric ? <MetricCard key={metric.id} metric={metric} /> : null)}</div></div></SectionPanel>))}</div>
      <GlassCard className="mt-5 p-6"><h3 className="text-lg font-bold text-white">Source Library</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{sources.slice(0, 8).map((source) => <div key={source.id} className="rounded-2xl border border-cyan-100/10 bg-white/[0.03] p-4"><p className="text-sm font-semibold text-cyan-50">{source.label}</p><p className="mt-1 text-xs text-cyan-100/52">{source.type}</p><p className="mt-3 text-sm leading-6 text-cyan-100/58">{source.note}</p>{source.url ? <a className="mt-3 inline-block text-xs font-semibold text-emerald-200" href={source.url} target="_blank" rel="noreferrer">Open source</a> : null}</div>)}</div></GlassCard>
    </section></main>
  );
}

function BarPanel({ title, subtitle, data, dataKey, color, formatter, domain }: { title: string; subtitle: string; data: any[]; dataKey: string; color: string; formatter?: "$K" | "$M"; domain?: [number, number] }) {
  return <ChartBlock title={title} subtitle={subtitle}><BarChart data={data}><CartesianGrid stroke="rgba(255,255,255,.08)" /><XAxis dataKey="name" stroke="rgba(207,250,254,.45)" tick={{ fontSize: 10 }} /><YAxis stroke="rgba(207,250,254,.45)" tick={{ fontSize: 11 }} domain={domain} tickFormatter={(value) => formatter ? `${formatter[0]}${value}${formatter.slice(1)}` : formatYAxis(value as number)} /><Bar dataKey={dataKey} fill={color} radius={[10,10,0,0]} /></BarChart></ChartBlock>;
}

function StackedPanel({ title, subtitle, data, a, b, aLabel, bLabel, grouped = false }: { title: string; subtitle: string; data: any[]; a: string; b: string; aLabel: string; bLabel: string; grouped?: boolean }) {
  return <ChartBlock title={title} subtitle={subtitle}><BarChart data={data}><CartesianGrid stroke="rgba(255,255,255,.08)" /><XAxis dataKey="name" stroke="rgba(207,250,254,.45)" tick={{ fontSize: 10 }} /><YAxis stroke="rgba(207,250,254,.45)" tick={{ fontSize: 11 }} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey={a} name={aLabel} stackId={grouped ? undefined : "stack"} fill="#22d3ee" radius={grouped ? [10,10,0,0] : [0,0,0,0]} /><Bar dataKey={b} name={bLabel} stackId={grouped ? undefined : "stack"} fill="#ef4444" radius={[10,10,0,0]} /></BarChart></ChartBlock>;
}
