import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Building2, CalendarClock, CircleDollarSign, ExternalLink, HeartPulse, Landmark, Loader2, Radar, Search, ShieldCheck } from "lucide-react";
import { HeaderBar } from "@/components/insight/HeaderBar";
import { Sidebar } from "@/components/insight/Sidebar";

const AGENCIES = ["Department of Defense","Department of Homeland Security","Department of Veterans Affairs","Department of Health and Human Services","Department of State","Department of Transportation","Department of Labor","Department of Energy","Department of Justice","Department of Agriculture","Department of the Interior"];
const BUCKETS = ["forecast","recompete-watch","incumbent-tracker","deployment-medical"];
const OCCU_MED = /occupational\s+(health|medicine)|employee\s+health|medical\s+(exam|evaluation|surveillance)|physical\s+exam|pre[- ]?(employment|placement)|fitness[- ]?for[- ]?duty|drug\s+(test|screen)|alcohol\s+(test|screen)|respirator|audiometr|hearing\s+conservation|vaccin|immuniz|specimen\s+collection|workers.?\s*comp|return[- ]?to[- ]?work|deployment\s+medical|travel\s+medicine/i;
type Opportunity = { noticeId:string; title:string; organization:string; solicitationNumber:string; postedDate:string; responseDeadline:string; type:string; naicsCode:string; classificationCode:string; setAside:string; active:boolean; award:any; placeOfPerformance:{city:string;state:string;country:string}; sourceUrl:string; descriptionUrl:string; occuMedScore:number; occuMedTags:string[]; occuMedRelevant:boolean };
type Pipeline = { ok:boolean; configured:boolean; agency:string; opportunities:Opportunity[]; relevant:Opportunity[]; returned:number; relevantCount:number; retrievedAt?:string; source?:string; sourceUrl?:string; error?:string; limitation?:string; diagnostics?:any };
type Persisted = { id:string; bucket:string; sourceType:string|null; agency:string|null; component:string|null; office:string|null; regionCountry:string|null; title:string; summary:string|null; datePosted:string|null; status:string|null; contractorIncumbent:string|null; budgetSignal:string|null; medicalTravelRelevance:string|null; occuMedScore:number|null; sourceUrl:string|null; fetchedAt:string|null };

async function read<T>(url:string):Promise<T> { const response=await fetch(url,{cache:"no-store"}); const payload=await response.json().catch(()=>({})); if(!response.ok) throw new Error(payload?.error||`HTTP ${response.status}`); return payload as T; }
function agencyMatch(value:string|null, selected:string) { if(!value) return false; const left=value.toLowerCase(),right=selected.toLowerCase(); if(right.includes("defense")) return /defense|dept of defense|dod/.test(left); if(right.includes("homeland")) return /homeland security/.test(left); return left.includes(right.replace("department of ","")) || right.includes(left); }
function moneyValue(value?:string|null) { const n=Number(String(value||"").replace(/[^0-9.-]/g,"")); return Number.isFinite(n)?n:0; }
function compactMoney(value:number) { if(value>=1e9)return `$${(value/1e9).toFixed(1)}B`; if(value>=1e6)return `$${(value/1e6).toFixed(1)}M`; if(value>=1e3)return `$${(value/1e3).toFixed(1)}K`; return `$${Math.round(value).toLocaleString()}`; }
function formatDate(value?:string|null) { if(!value)return "—"; const d=new Date(value); return Number.isNaN(d.getTime())?value:d.toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}); }
function persistedRelevant(item:Persisted) { return OCCU_MED.test(`${item.title} ${item.summary||""} ${item.medicalTravelRelevance||""}`); }

export default function FederalAgenciesPage() {
  const [agency,setAgency]=useState(AGENCIES[0]);
  const [query,setQuery]=useState("");
  const [pipeline,setPipeline]=useState<Pipeline|null>(null);
  const [persisted,setPersisted]=useState<Persisted[]>([]);
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState("");

  useEffect(()=>{ let active=true; setLoading(true); setError(""); setPipeline(null); const encoded=encodeURIComponent(agency); Promise.all([read<Pipeline>(`/api/core-intelligence/federal-occupational-pipeline?agency=${encoded}&days=365`),...BUCKETS.map((bucket)=>read<{items:Persisted[]}>(`/api/federal-intel/${bucket}?limit=200`).catch(()=>({items:[]})))])
    .then(([live,...buckets])=>{ if(!active)return; setPipeline(live as Pipeline); setPersisted(buckets.flatMap((payload:any)=>payload.items||[]).filter((item:Persisted)=>agencyMatch(item.agency,agency))); })
    .catch((reason)=>active&&setError(reason instanceof Error?reason.message:"Federal intelligence failed."))
    .finally(()=>active&&setLoading(false)); return()=>{active=false}; },[agency]);

  const liveRelevant=useMemo(()=>pipeline?.relevant||[],[pipeline]);
  const persistedMedical=useMemo(()=>persisted.filter(persistedRelevant),[persisted]);
  const incumbents=useMemo(()=>persisted.filter((item)=>item.bucket==="incumbent-tracker"),[persisted]);
  const recompetes=useMemo(()=>persisted.filter((item)=>item.bucket==="recompete-watch"&&persistedRelevant(item)),[persisted]);
  const forecasts=useMemo(()=>persisted.filter((item)=>item.bucket==="forecast"&&persistedRelevant(item)),[persisted]);
  const spend=incumbents.reduce((sum,item)=>sum+moneyValue(item.budgetSignal),0);
  const tags=useMemo(()=>{ const map=new Map<string,number>(); liveRelevant.forEach((item)=>item.occuMedTags.forEach((tag)=>map.set(tag,(map.get(tag)||0)+1))); return [...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8); },[liveRelevant]);
  const maxTag=Math.max(1,...tags.map(([,count])=>count));
  const filtered=useMemo(()=>{ const needle=query.trim().toLowerCase(); const rows=[...liveRelevant.map((item)=>({kind:"Live SAM",title:item.title,summary:item.occuMedTags.join(" · "),date:item.postedDate,value:item.award?.amount?compactMoney(item.award.amount):"",office:item.organization,url:item.sourceUrl,deadline:item.responseDeadline})),...persistedMedical.map((item)=>({kind:item.bucket.replace(/-/g," "),title:item.title,summary:item.summary||item.medicalTravelRelevance||"",date:item.datePosted||item.fetchedAt,value:item.budgetSignal||"",office:item.office||item.component||"",url:item.sourceUrl||"",deadline:""}))]; return needle?rows.filter((row)=>`${row.title} ${row.summary} ${row.office}`.toLowerCase().includes(needle)):rows; },[liveRelevant,persistedMedical,query]);

  return <main className="min-h-screen overflow-x-hidden bg-[#020817] text-white"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_14%_16%,rgba(16,185,129,.16),transparent_30%),radial-gradient(circle_at_56%_28%,rgba(14,165,233,.17),transparent_34%),radial-gradient(circle_at_88%_18%,rgba(99,102,241,.18),transparent_29%),linear-gradient(145deg,#020817,#052638_50%,#0a0b2c)]"/><Sidebar/><section className="relative z-10 px-5 py-8 pt-24 lg:ml-[224px] lg:px-12 lg:pt-8"><HeaderBar eyebrow="Federal intelligence · occupational-health pipeline" title="Federal Agencies" subtitle="Live SAM opportunities, medical-service signals, incumbent context, and forward-pipeline evidence are separated by source and relevance. API failures are shown as failures—not converted into fake zeros." />

    <section className="mt-8 grid gap-8 xl:grid-cols-[260px_1fr]"><aside className="self-start xl:sticky xl:top-8"><p className="text-[9px] font-black uppercase tracking-[.17em] text-cyan-100/38">Agency directory</p><div className="mt-4 border-y border-white/8 divide-y divide-white/7">{AGENCIES.map((item)=><button key={item} onClick={()=>setAgency(item)} className={`w-full py-3 text-left text-[11px] font-black transition ${agency===item?"text-white":"text-cyan-50/42 hover:text-white"}`}><span className="flex items-center justify-between gap-3">{item}{agency===item?<span className="h-2 w-2 rounded-full bg-cyan-300"/>:null}</span></button>)}</div></aside>
      <div><section className="overflow-hidden rounded-[34px] border border-white/12 bg-[linear-gradient(145deg,rgba(4,37,51,.87),rgba(27,39,89,.76))] shadow-[0_36px_100px_rgba(0,0,0,.36)]"><div className="p-7 md:p-10"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[9px] font-black uppercase tracking-[.19em] text-cyan-100/38">Selected agency</p><h2 className="mt-2 text-4xl font-black tracking-[-.055em]">{agency}</h2><p className="mt-3 text-xs text-cyan-50/42">SAM public Opportunities API + persisted federal intelligence</p></div><Landmark className="text-cyan-100/45"/></div><div className="mt-10 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/9 bg-white/9 md:grid-cols-5">{[["Live relevant",liveRelevant.length],["Medical persisted",persistedMedical.length],["Incumbents",incumbents.length],["Recompetes",recompetes.length],["Tracked value",compactMoney(spend)]].map(([label,value])=><div key={String(label)} className="bg-[#061521]/92 p-5"><p className="text-[8px] font-black uppercase tracking-[.13em] text-cyan-100/30">{label}</p><strong className="mt-2 block text-2xl font-black">{value}</strong></div>)}</div></div></section>

      {loading?<div className="mt-8 flex items-center justify-center gap-3 py-16 text-sm text-cyan-50/45"><Loader2 size={18} className="animate-spin"/>Loading federal source pipeline…</div>:null}
      {error?<div className="mt-6 rounded-2xl border border-rose-200/20 bg-rose-300/[.05] p-5 text-sm text-rose-100"><AlertTriangle size={16} className="mr-2 inline"/>{error}<p className="mt-2 text-xs text-rose-100/60">This is a source failure, not a zero-opportunity result.</p></div>:null}
      {!loading&&pipeline&&!pipeline.ok?<div className="mt-6 rounded-2xl border border-rose-200/20 bg-rose-300/[.05] p-5 text-sm text-rose-100"><AlertTriangle size={16} className="mr-2 inline"/>{pipeline.error||"SAM.gov request failed."}</div>:null}

      {!loading&&pipeline?.ok?<><section className="mt-12 grid gap-10 xl:grid-cols-[.68fr_1.32fr]"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-100/38">Opportunity signal mix</p><h3 className="mt-3 text-3xl font-black tracking-[-.045em]">What kind of Occu-Med demand is visible.</h3><p className="mt-4 text-sm leading-7 text-cyan-50/46">Relevance is conservative: the SAM public feed exposes a description URL, not inline description text, so this view does not pretend a URL is a synopsis.</p><div className="mt-7 space-y-4">{tags.map(([tag,count])=><div key={tag}><div className="flex justify-between text-xs"><span className="text-cyan-50/60">{tag}</span><b>{count}</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/[.05]"><div className="h-full rounded-full bg-gradient-to-r from-emerald-300/65 via-cyan-300/70 to-violet-300/70" style={{width:`${Math.max(8,(count/maxTag)*100)}%`}}/></div></div>)}{!tags.length?<p className="text-sm text-cyan-50/38">No occupational-health title/classification signals were returned for this agency in the selected window.</p>:null}</div></div>
      <div className="rounded-[30px] border border-white/10 bg-white/[.025] p-6 md:p-8"><div className="flex items-center justify-between gap-4"><div><p className="text-[9px] font-black uppercase tracking-[.17em] text-cyan-100/38">SAM retrieval diagnostics</p><h3 className="mt-2 text-xl font-black">The source pipeline is inspectable.</h3></div><Radar className="text-cyan-100/45"/></div><div className="mt-7 space-y-3">{(pipeline.diagnostics?.searches||[]).map((search:any)=><div key={search.mode} className="grid grid-cols-[1fr_auto_auto] gap-4 border-b border-white/7 pb-3 text-xs"><span className="capitalize text-cyan-50/58">{String(search.mode).replace(/-/g," ")}</span><span className="text-cyan-50/38">HTTP {search.httpStatus}</span><b>{search.returned}/{search.totalRecords}</b></div>)}</div><div className="mt-6 grid grid-cols-2 gap-5 text-xs"><div><p className="text-[8px] uppercase tracking-[.13em] text-cyan-100/30">Window</p><p className="mt-1 font-black">{pipeline.diagnostics?.postedFrom} → {pipeline.diagnostics?.postedTo}</p></div><div><p className="text-[8px] uppercase tracking-[.13em] text-cyan-100/30">Page size</p><p className="mt-1 font-black">{pipeline.diagnostics?.pageLimit||1000}</p></div></div></div></section>

      <section className="mt-14"><div className="flex flex-wrap items-end justify-between gap-5 border-b border-white/10 pb-5"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-cyan-100/38">Evidence stream</p><h3 className="mt-2 text-3xl font-black tracking-[-.045em]">Occu-Med-relevant federal records</h3></div><div className="flex min-w-[280px] items-center gap-2 border-b border-white/12 py-2"><Search size={14} className="text-cyan-100/35"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Filter loaded evidence…" className="w-full bg-transparent text-xs outline-none placeholder:text-cyan-100/22"/></div></div><div className="divide-y divide-white/8">{filtered.slice(0,40).map((row,index)=><article key={`${row.kind}-${row.title}-${index}`} className="grid gap-4 py-6 lg:grid-cols-[110px_1fr_130px_auto]"><div><span className="text-[8px] font-black uppercase tracking-[.13em] text-cyan-100/36">{row.kind}</span><p className="mt-2 text-[10px] text-cyan-50/38">{formatDate(row.date)}</p></div><div><h4 className="text-base font-black leading-6">{row.title}</h4><p className="mt-2 text-xs leading-6 text-cyan-50/48">{row.summary||"Source record loaded without a narrative summary."}</p><p className="mt-2 text-[9px] text-cyan-100/34">{row.office}</p></div><div><p className="text-[8px] uppercase tracking-[.12em] text-cyan-100/30">Value / deadline</p><p className="mt-2 text-xs font-black">{row.value||row.deadline||"—"}</p></div>{row.url?<a href={row.url} target="_blank" rel="noreferrer" className="mt-1 text-cyan-100/45 hover:text-white"><ExternalLink size={15}/></a>:null}</article>)}{!filtered.length?<div className="py-16 text-sm text-cyan-50/40">No verified Occu-Med-relevant records match this agency/filter. The page intentionally does not fill the gap with unrelated hardware procurement.</div>:null}</div></section>

      <section className="mt-14 grid gap-6 border-t border-white/10 pt-10 md:grid-cols-3"><div><HeartPulse className="text-emerald-100/45"/><h4 className="mt-3 text-sm font-black">Medical relevance</h4><p className="mt-2 text-xs leading-6 text-cyan-50/42">Occupational health, exams, surveillance, drug testing, respirators, hearing, vaccination, lab collection, RTW, and deployment medicine drive the relevance layer.</p></div><div><CircleDollarSign className="text-cyan-100/45"/><h4 className="mt-3 text-sm font-black">Contract context</h4><p className="mt-2 text-xs leading-6 text-cyan-50/42">Incumbent and value data remain separate from opportunity relevance so spend does not masquerade as medical demand.</p></div><div><ShieldCheck className="text-violet-100/45"/><h4 className="mt-3 text-sm font-black">No hardware pollution</h4><p className="mt-2 text-xs leading-6 text-cyan-50/42">Valves, clamps, drums, roofing, painting, cranes, and generic construction do not enter the Occu-Med stream without medical evidence.</p></div></section></>:null}
      </div></section>
    </section></main>;
}
