import { useEffect, useState, type ReactNode } from "react";
import { AlertTriangle, BriefcaseBusiness, CheckCircle2, Database, Loader2, Radar, Search, Stethoscope } from "lucide-react";
import { HeaderBar } from "@/components/insight/HeaderBar";
import { Sidebar } from "@/components/insight/Sidebar";
import { ReviewerInjuryHologram } from "./reviewer-injury-hologram";
import "./reviewer-tool-hierarchy.css";

async function loadJson(url:string):Promise<any>{const response=await fetch(url,{headers:{Accept:"application/json"}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||`Request failed (${response.status}).`);return payload;}
function Loading({text="Loading source data…"}:{text?:string}){return <div className="flex min-h-28 items-center justify-center gap-3 text-sm text-cyan-100/55"><Loader2 size={18} className="animate-spin"/>{text}</div>}
function ErrorState({error}:{error:string}){return <div className="rounded-2xl border border-rose-200/16 bg-rose-300/[.05] p-4 text-sm text-rose-50/75"><AlertTriangle size={16} className="mr-2 inline"/>{error}</div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rh-metric"><span>{label}</span><strong>{value}</strong></div>}
function BulletList({items}:{items:string[]}){return <div className="space-y-3">{items.map((item)=><div key={item} className="flex gap-2 text-xs leading-6 text-cyan-100/58"><CheckCircle2 size={14} className="mt-1 shrink-0 text-cyan-100/52"/>{item}</div>)}</div>}

const CONDITIONS=[
{id:"diabetes",label:"Diabetes",domains:["glycemic stability","hypoglycemia","medication access","renal / cardiovascular context"],prompts:["What is the current A1C and treatment route?","Any severe hypoglycemia or impaired awareness?","Can medication, monitoring supplies, food, and storage be maintained in the work setting?"],docs:["Recent A1C","Medication list","Glucose-monitoring history","Complication / specialist documentation when applicable"]},
{id:"osa",label:"Obstructive Sleep Apnea",domains:["alertness","PAP adherence","fatigue","power / equipment access"],prompts:["What was the diagnostic AHI/RDI?","Is there objective PAP compliance data?","Any residual daytime sleepiness or safety-sensitive symptoms?"],docs:["Sleep study","30–90 day PAP download","Epworth / symptom history","Device / battery plan when relevant"]},
{id:"hypertension",label:"Hypertension",domains:["blood pressure control","medication tolerance","cardiovascular risk","exertion"],prompts:["Are repeated resting blood pressures available?","Any dizziness, syncope, or medication side effects?","Is additional cardiac risk assessment required by the controlling program?"],docs:["Serial blood pressures","Medication history","Cardiology records when indicated"]},
{id:"asthma",label:"Asthma / Reactive Airway Disease",domains:["respiratory reserve","trigger exposure","rescue medication","PPE / respirator tolerance"],prompts:["Current severity and symptom frequency?","Recent ER visits, hospitalization, or systemic steroids?","Pulmonary function / FEV1 available?","Can required respiratory protection be used?"],docs:["Spirometry/PFT","ACT or symptom history","Recent urgent-care records","Medication plan"]},
{id:"seizure",label:"Seizure Disorder",domains:["loss of consciousness","medication stability","driving / heights","emergency access"],prompts:["Date and circumstances of last seizure?","Current anticonvulsant indication and stability?","Any duty involving driving, weapons, heights, or hazardous machinery?"],docs:["Neurology note","Seizure history","Medication list / levels when applicable"]},
{id:"cardiac",label:"Cardiovascular Disease",domains:["functional capacity","ischemia","arrhythmia","anticoagulation"],prompts:["Symptoms with exertion?","Most recent functional testing / METs?","Any rhythm disorder or anticoagulant therapy?"],docs:["Cardiology note","ECG","Stress test / echo when applicable","Medication list"]},
{id:"behavioral",label:"Behavioral Health",domains:["stability","sleep","judgment","medication effects"],prompts:["Current diagnosis and treatment stability?","Any recent hospitalization, self-harm, or major functional change?","Any medication side effects relevant to safety-sensitive work?"],docs:["Treating clinician summary","Medication history","Functional / stability documentation"]},
{id:"musculoskeletal",label:"Musculoskeletal Condition",domains:["lifting / carrying","mobility","pain","PPE / emergency egress"],prompts:["What movements or loads reproduce symptoms?","Any restrictions, assistive devices, or recent surgery?","Can the person meet the actual job task and emergency egress demands?"],docs:["Orthopedic / PT note","Functional restrictions","Imaging when clinically relevant","Job-demand description"]},
] as const;

export default function ReviewerInjuriesMedicalPage(){
 const [tab,setTab]=useState<"injury"|"conditions">("injury");
 const [osha,setOsha]=useState<any>(null);const [oshaError,setOshaError]=useState("");
 const [occupation,setOccupation]=useState("");const [onet,setOnet]=useState<any>(null);const [onetLoading,setOnetLoading]=useState(false);
 const [conditionId,setConditionId]=useState<(typeof CONDITIONS)[number]["id"]>("diabetes");
 useEffect(()=>{void loadJson("/api/occupational-discovery/osha-overview").then(setOsha).catch((error)=>setOshaError(error.message));},[]);
 async function runOccupation(){if(!occupation.trim())return;setOnetLoading(true);try{setOnet(await loadJson(`/api/occupational-discovery/onet/profile?keyword=${encodeURIComponent(occupation.trim())}`));}catch(error){setOnet({error:error instanceof Error?error.message:"O*NET request failed."});}finally{setOnetLoading(false)}}
 const profile=onet?.profile??null;const condition=CONDITIONS.find((item)=>item.id===conditionId)??CONDITIONS[0];

 return <main className="aurora-bg reviewer-native-page min-h-screen pb-24 text-white"><Sidebar/><section className="relative z-10 px-5 py-8 pt-24 lg:ml-[210px] lg:px-12 lg:pt-8"><HeaderBar eyebrow="Clinical / Occupational Health Intelligence" title="Injuries & Medical Conditions" subtitle="Occupation-linked injury intelligence, the restored holographic anatomy projection, and condition-specific reviewer context in one coherent hierarchy."/>
  <div className="rh-stack">
   <div className="rh-tabs" role="tablist"><button role="tab" aria-selected={tab==="injury"} onClick={()=>setTab("injury")} className={`rh-tab ${tab==="injury"?"active":""}`}>Injury Intelligence</button><button role="tab" aria-selected={tab==="conditions"} onClick={()=>setTab("conditions")} className={`rh-tab ${tab==="conditions"?"active":""}`}>Medical Conditions</button></div>

   {tab==="injury"?<>
    <section className="rh-primary-action"><div className="rh-kicker">01 · Occupation context</div><h2 className="rh-section-title">Connect the injury picture to the actual job.</h2><p className="rh-section-copy">Load an O*NET occupation profile to energize the hologram and keep job-demand evidence separate from OSHA establishment surveillance.</p><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_auto]"><div className="flex items-center gap-3 rounded-2xl border border-white/16 bg-black/20 px-4"><Search size={17} className="text-cyan-100/55"/><input value={occupation} onChange={(event)=>setOccupation(event.target.value)} onKeyDown={(event)=>event.key==="Enter"&&void runOccupation()} placeholder="Firefighter, electrician, truck driver…" className="rh-input !border-0 !bg-transparent !px-0"/></div><button type="button" onClick={()=>void runOccupation()} disabled={onetLoading||!occupation.trim()} className="rh-action">{onetLoading?<Loader2 size={16} className="mr-2 inline animate-spin"/>:<Radar size={16} className="mr-2 inline"/>}Build occupation profile</button></div></section>

    <ReviewerInjuryHologram profile={profile}/>

    <section className="rh-support-grid">
     <div className="rh-card"><div className="flex items-center justify-between"><div><div className="rh-label">03 · OSHA surveillance</div><h3 className="mt-2">Reported injury burden</h3></div><Database className="text-cyan-100/50"/></div>{oshaError?<div className="mt-4"><ErrorState error={oshaError}/></div>:!osha?<Loading/>:!osha.imported?<p className="mt-4">{osha.warning||"No OSHA ITA rows are imported yet."}</p>:<div className="rh-metric-grid mt-5"><Metric label="Latest year" value={String(osha.latestYear||"—")}/><Metric label="Top employer cases" value={String(osha.topEmployers?.[0]?.total_cases??"—")}/><Metric label="Top state cases" value={String(osha.topStates?.[0]?.total_cases??"—")}/><Metric label="High-rate establishments" value={String(osha.highRateEstablishments?.length??0)}/></div>}<p className="mt-5 text-[10px] leading-5 text-cyan-100/35">OSHA ITA reporting is not representative of every employer and does not establish fault, negligence, compensability, or causation.</p></div>
     <div className="rh-card is-wide"><div className="flex items-center justify-between"><div><div className="rh-label">04 · O*NET demand evidence</div><h3 className="mt-2">Occupation demand profile</h3></div><BriefcaseBusiness className="text-violet-100/50"/></div>{onetLoading?<Loading text="Loading O*NET evidence…"/>:onet?.error?<div className="mt-4"><ErrorState error={onet.error}/></div>:profile?<div className="mt-5"><h4 className="text-xl font-black">{profile.occupation?.title}</h4><p className="mt-2 text-sm leading-6 text-cyan-100/50">{profile.occupation?.description}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{(profile.serviceMatches||[]).slice(0,8).map((item:any)=><div key={item.id} className="rounded-2xl border border-white/10 bg-white/[.022] p-4"><div className="flex items-start justify-between gap-3"><strong className="text-sm">{item.label}</strong><span className="rounded-full border border-cyan-100/14 px-2 py-1 text-[9px] font-black text-cyan-100/58">{item.count} hits</span></div><p className="mt-2 text-xs leading-5 text-cyan-100/43">{item.description}</p></div>)}</div></div>:<p className="mt-4">Search an occupation to connect O*NET demand evidence to the hologram.</p>}</div>
     <div className="rh-card is-full is-quiet"><div className="rh-label">Interpretation boundary</div><p className="mt-2">The hologram visualizes occupation-linked evidence and reviewer attention regions; it is not a diagnosis, injury prediction, causation opinion, or medical clearance determination.</p></div>
    </section>
   </>:<>
    <section className="rh-primary-action"><div className="rh-kicker">01 · Condition library</div><h2 className="rh-section-title">Choose the condition, then resolve the reviewer questions.</h2><p className="rh-section-copy">The condition determines the review prompts below. Supporting documentation and functional domains stay secondary to the actual questions that need answers.</p><div className="mt-5 flex flex-wrap gap-2">{CONDITIONS.map((item)=><button key={item.id} onClick={()=>setConditionId(item.id)} className={`rh-secondary ${conditionId===item.id?"!border-cyan-100/28 !bg-cyan-300/[.08] !text-white":""}`}>{item.label}</button>)}</div></section>

    <section className="rh-hero"><div className="rh-hero-grid"><div className="rh-hero-main"><div className="flex items-start justify-between"><div><div className="rh-kicker">02 · Active condition</div><h2 className="rh-section-title">{condition.label}</h2><p className="rh-section-copy">Reviewer context only. Start with functional stability and the actual occupational setting rather than assuming restriction from the diagnosis name.</p></div><Stethoscope className="text-violet-100/50"/></div><div className="mt-7"><div className="rh-label">Questions to resolve</div><div className="mt-4"><BulletList items={[...condition.prompts]}/></div></div></div><aside className="rh-hero-side"><div className="rh-kicker">03 · Functional domains</div><div className="mt-5 space-y-3">{condition.domains.map((domain,index)=><div key={domain} className="rounded-2xl border border-white/10 bg-white/[.022] p-4"><span className="text-[9px] font-black text-cyan-100/35">{String(index+1).padStart(2,"0")}</span><strong className="mt-1 block text-sm capitalize">{domain}</strong></div>)}</div></aside></div></section>

    <section className="rh-support-grid"><div className="rh-card is-wide"><div className="rh-label">04 · Useful documentation</div><h3 className="mt-2">Evidence to collect</h3><div className="mt-4"><BulletList items={[...condition.docs]}/></div></div><div className="rh-card"><div className="rh-label">Review focus</div><h3 className="mt-2">Function before label</h3><p className="mt-3">Resolve current stability, symptoms, treatment effects, job demands, PPE/egress needs, and controlling program requirements.</p></div><div className="rh-card is-full is-quiet"><div className="rh-label">Interpretation boundary</div><p className="mt-2">Condition context supports reviewer questioning; it does not independently determine fitness, disability, causation, deployability, or clearance.</p></div></section>
   </>}
  </div>
 </section></main>;
}
