import { useMemo, useState } from "react";
import { Calculator, RefreshCw } from "lucide-react";
import { HeaderBar } from "@/components/insight/HeaderBar";
import { Sidebar } from "@/components/insight/Sidebar";
import "./reviewer-tool-hierarchy.css";

type CalcField = { key: string; label: string; unit?: string; type?: "number" | "select"; options?: Array<{ label: string; value: string }>; min?: number; max?: number; step?: number };
type CalcOutput = { value: string; interpretation: string; reference: string };
type CalcDef = { id: string; label: string; description: string; group: "Body & Renal" | "Cardiovascular" | "Environment"; fields: CalcField[]; calculate: (v: Record<string,string>) => CalcOutput | null };
const n=(v:Record<string,string>,key:string)=>Number.parseFloat(v[key]||"");
const sexOptions=[{label:"Male",value:"male"},{label:"Female",value:"female"}];
const result=(value:string,interpretation:string,reference:string):CalcOutput=>({value,interpretation,reference});

const CALCS:CalcDef[]=[
{id:"bmi",label:"BMI",group:"Body & Renal",description:"Adult body-mass-index screening value",fields:[{key:"weight",label:"Weight",unit:"kg",min:20,max:300},{key:"height",label:"Height",unit:"cm",min:100,max:250}],calculate:(v)=>{const bmi=n(v,"weight")/((n(v,"height")/100)**2);if(!Number.isFinite(bmi))return null;const band=bmi<18.5?"Underweight":bmi<25?"Healthy-weight":bmi<30?"Overweight":bmi<35?"Obesity class 1":bmi<40?"Obesity class 2":"Obesity class 3";return result(bmi.toFixed(1),`${band} range. BMI is a screening measure, not a fitness determination.`,`CDC adult BMI categories`)}},
{id:"egfr",label:"eGFR",group:"Body & Renal",description:"2021 CKD-EPI creatinine estimate",fields:[{key:"creatinine",label:"Serum creatinine",unit:"mg/dL",min:.3,max:15,step:.01},{key:"age",label:"Age",unit:"years",min:18,max:120},{key:"sex",label:"Sex used by equation",type:"select",options:sexOptions}],calculate:(v)=>{const cr=n(v,"creatinine"),age=n(v,"age"),female=v.sex==="female",k=female?.7:.9,a=female?-.241:-.302,ratio=cr/k;const value=142*Math.pow(Math.min(ratio,1),a)*Math.pow(Math.max(ratio,1),-1.2)*Math.pow(.9938,age)*(female?1.012:1);return Number.isFinite(value)?result(`${value.toFixed(0)} mL/min/1.73m²`,value>=90?"G1 eGFR range — eGFR alone does not establish CKD":value>=60?"G2 eGFR range — eGFR alone does not establish CKD":value>=45?"G3a eGFR range":value>=30?"G3b eGFR range":value>=15?"G4 eGFR range":"G5 eGFR range","CKD-EPI 2021 race-free creatinine equation"):null}},
{id:"bsa",label:"Body Surface Area",group:"Body & Renal",description:"Mosteller body surface area",fields:[{key:"height",label:"Height",unit:"cm",min:50,max:275},{key:"weight",label:"Weight",unit:"kg",min:2,max:500}],calculate:(v)=>result(`${Math.sqrt(n(v,"height")*n(v,"weight")/3600).toFixed(2)} m²`,`Body-size estimate; use only where the applicable protocol calls for BSA.`,`Mosteller: √((height cm × weight kg) ÷ 3600)`)},
{id:"ibw",label:"Ideal Body Weight",group:"Body & Renal",description:"Devine equation reference",fields:[{key:"height",label:"Height",unit:"cm",min:100,max:250},{key:"sex",label:"Sex used by equation",type:"select",options:sexOptions}],calculate:(v)=>{const inches=n(v,"height")/2.54,base=v.sex==="female"?45.5:50,value=base+2.3*Math.max(0,inches-60);return result(`${value.toFixed(1)} kg`,`Equation-derived dosing reference, not a target weight or fitness determination.`,`Devine equation`)}},
{id:"adjbw",label:"Adjusted Body Weight",group:"Body & Renal",description:"IBW-based dosing reference",fields:[{key:"actual",label:"Actual weight",unit:"kg",min:2,max:500},{key:"ibw",label:"Ideal body weight",unit:"kg",min:20,max:250}],calculate:(v)=>result(`${(n(v,"ibw")+.4*(n(v,"actual")-n(v,"ibw"))).toFixed(1)} kg`,`Use only when a medication or protocol specifies adjusted body weight.`,`AdjBW = IBW + 0.4 × (actual − IBW)`)},
{id:"crcl",label:"Creatinine Clearance",group:"Body & Renal",description:"Adult Cockcroft–Gault estimate",fields:[{key:"age",label:"Age",unit:"years",min:18,max:120},{key:"weight",label:"Weight selected for equation",unit:"kg",min:20,max:500},{key:"creatinine",label:"Serum creatinine",unit:"mg/dL",min:.2,max:20,step:.01},{key:"sex",label:"Sex adjustment",type:"select",options:sexOptions}],calculate:(v)=>{let value=((140-n(v,"age"))*n(v,"weight"))/(72*n(v,"creatinine"));if(v.sex==="female")value*=.85;return result(`${value.toFixed(0)} mL/min`,`Adult estimate; clinically appropriate weight and dosing decision remain protocol-specific.`,`Cockcroft–Gault equation`)}},
{id:"map",label:"Mean Arterial Pressure",group:"Cardiovascular",description:"Quick SBP / DBP arithmetic estimate",fields:[{key:"sbp",label:"Systolic BP",unit:"mmHg",min:50,max:300},{key:"dbp",label:"Diastolic BP",unit:"mmHg",min:20,max:200}],calculate:(v)=>n(v,"sbp")>n(v,"dbp")?result(`${((n(v,"sbp")+2*n(v,"dbp"))/3).toFixed(0)} mmHg`,`Arithmetic estimate. Apply program-specific BP criteria separately.`,`MAP ≈ (SBP + 2×DBP) / 3`):null},
{id:"mets",label:"Walking METs",group:"Cardiovascular",description:"ACSM treadmill walking-equation estimate",fields:[{key:"speed",label:"Speed",unit:"mph",min:.1,max:8,step:.1},{key:"grade",label:"Grade",unit:"%",min:0,max:30,step:.5}],calculate:(v)=>{const sp=n(v,"speed"),m=sp*26.8224,g=n(v,"grade")/100,mets=(.1*m+1.8*m*g+3.5)/3.5;return result(mets.toFixed(1),`${sp>=1.9&&sp<=3.7?"Within":"Outside"} the usual walking-equation speed range. Estimate only.`,`ACSM walking metabolic equation`)}},
{id:"mphr",label:"Maximum Predicted HR",group:"Cardiovascular",description:"Age-predicted maximum",fields:[{key:"age",label:"Age",unit:"years",min:1,max:120}],calculate:(v)=>result(`${(220-n(v,"age")).toFixed(0)} bpm`,`Population estimate only; not an exercise clearance or fitness decision.`,`220 − age`)},
{id:"target",label:"Target Heart Rate",group:"Cardiovascular",description:"User-selected intensity zone",fields:[{key:"age",label:"Age",unit:"years",min:1,max:120},{key:"low",label:"Low intensity",unit:"%",min:1,max:100},{key:"high",label:"High intensity",unit:"%",min:1,max:100}],calculate:(v)=>{const max=220-n(v,"age");return result(`${(max*n(v,"low")/100).toFixed(0)}–${(max*n(v,"high")/100).toFixed(0)} bpm`,`Age-predicted zone; individual response may differ.`,`(220 − age) × selected intensity`)}},
{id:"bazett",label:"QTc — Bazett",group:"Cardiovascular",description:"Heart-rate corrected QT",fields:[{key:"qt",label:"QT interval",unit:"ms",min:100,max:1000},{key:"rr",label:"RR interval",unit:"seconds",min:.3,max:2,step:.01}],calculate:(v)=>result(`${(n(v,"qt")/Math.sqrt(n(v,"rr"))).toFixed(0)} ms`,`Rate-corrected estimate; interpret in ECG and clinical context.`,`QTc = QT ÷ √RR`)},
{id:"fridericia",label:"QTc — Fridericia",group:"Cardiovascular",description:"Cube-root corrected QT",fields:[{key:"qt",label:"QT interval",unit:"ms",min:100,max:1000},{key:"rr",label:"RR interval",unit:"seconds",min:.3,max:2,step:.01}],calculate:(v)=>result(`${(n(v,"qt")/Math.cbrt(n(v,"rr"))).toFixed(0)} ms`,`Rate-corrected estimate; interpret in ECG and clinical context.`,`QTc = QT ÷ ∛RR`)},
{id:"pack",label:"Pack-Years",group:"Environment",description:"Smoking exposure history",fields:[{key:"cigs",label:"Cigarettes per day",min:0,max:200},{key:"years",label:"Years smoked",min:0,max:100,step:.5}],calculate:(v)=>result(`${((n(v,"cigs")/20)*n(v,"years")).toFixed(1)} pack-years`,`Exposure summary only. Screening criteria come from the applicable standard.`,`(cigarettes/day ÷ 20) × years`)},
{id:"heat",label:"Heat Index",group:"Environment",description:"NOAA apparent heat estimate",fields:[{key:"temp",label:"Air temperature",unit:"°F",min:80,max:130,step:.1},{key:"rh",label:"Relative humidity",unit:"%",min:40,max:100}],calculate:(v)=>{const T=n(v,"temp"),R=n(v,"rh"),hi=-42.379+2.04901523*T+10.14333127*R-.22475541*T*R-.00683783*T*T-.05481717*R*R+.00122874*T*T*R+.00085282*T*R*R-.00000199*T*T*R*R;return result(`${hi.toFixed(0)} °F`,`Apparent temperature estimate for shaded, light-wind conditions.`,`NOAA/NWS Rothfusz regression`)}},
{id:"wind",label:"Wind Chill",group:"Environment",description:"NWS apparent cold estimate",fields:[{key:"temp",label:"Air temperature",unit:"°F",min:-100,max:50,step:.1},{key:"wind",label:"Wind speed",unit:"mph",min:3,max:150,step:.1}],calculate:(v)=>{const T=n(v,"temp"),W=n(v,"wind"),wc=35.74+.6215*T-35.75*Math.pow(W,.16)+.4275*T*Math.pow(W,.16);return result(`${wc.toFixed(0)} °F`,`Apparent cold estimate for exposed skin; clothing and wetness materially affect risk.`,`NWS wind-chill formula`)}}
];

const GROUPS:[CalcDef["group"],string][]=[["Body & Renal","Body size · renal"],["Cardiovascular","Cardiovascular · exercise"],["Environment","Environment · exposure"]];

export default function ReviewerClinicalCalculatorsPage(){
  const [group,setGroup]=useState<CalcDef["group"]>("Body & Renal");
  const [activeId,setActiveId]=useState("bmi");
  const [values,setValues]=useState<Record<string,Record<string,string>>>({});
  const [output,setOutput]=useState<CalcOutput|null>(null);
  const [error,setError]=useState("");
  const groupCalcs=useMemo(()=>CALCS.filter((calc)=>calc.group===group),[group]);
  const active=CALCS.find((calc)=>calc.id===activeId) ?? groupCalcs[0];
  const current=values[active.id]||{};

  function chooseGroup(next:CalcDef["group"]){setGroup(next);const first=CALCS.find((calc)=>calc.group===next);if(first)setActiveId(first.id);setOutput(null);setError("");}
  function chooseCalc(id:string){setActiveId(id);setOutput(null);setError("");}
  function setValue(key:string,value:string){setValues((all)=>({...all,[active.id]:{...(all[active.id]||{}),[key]:value}}));setOutput(null);setError("");}
  function calculate(){const missing=active.fields.find((field)=>!current[field.key]);if(missing){setError(`${missing.label} is required.`);return;}const invalid=active.fields.find((field)=>field.type!=="select"&&(!Number.isFinite(n(current,field.key))||(field.min!==undefined&&n(current,field.key)<field.min)||(field.max!==undefined&&n(current,field.key)>field.max)));if(invalid){setError(`${invalid.label} must be within ${invalid.min}–${invalid.max}${invalid.unit?` ${invalid.unit}`:""}.`);return;}try{const value=active.calculate(current);if(!value)throw new Error("Inputs are not valid for this equation.");setOutput(value);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Calculation failed.");}}
  function clear(){setValues((all)=>({...all,[active.id]:{}}));setOutput(null);setError("");}

  return <main className="aurora-bg reviewer-native-page min-h-screen pb-24 text-white"><Sidebar/><section className="relative z-10 px-5 py-8 pt-24 lg:ml-[210px] lg:px-12 lg:pt-8"><HeaderBar eyebrow="Clinical / Calculators" title="Clinical Calculators" subtitle="One calculator at a time: grouped inputs, one dominant result, interpretation, and source."/>
    <div className="rh-stack">
      <section className="rh-primary-action"><div className="rh-kicker">01 · Calculator family</div><div className="mt-4 rh-tabs">{GROUPS.map(([id,label])=><button key={id} className={`rh-tab ${group===id?"active":""}`} onClick={()=>chooseGroup(id)}>{label}</button>)}</div><div className="mt-4 flex flex-wrap gap-2">{groupCalcs.map((calc)=><button key={calc.id} onClick={()=>chooseCalc(calc.id)} className={`rh-secondary ${active.id===calc.id?"!border-cyan-100/28 !bg-cyan-300/[.08] !text-white":""}`}>{calc.label}</button>)}</div></section>

      <section className="rh-hero"><div className="rh-hero-grid"><div className="rh-hero-main"><div className="rh-kicker">02 · Inputs</div><h2 className="rh-section-title">{active.label}</h2><p className="rh-section-copy">{active.description}</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{active.fields.map((field)=><label key={field.key}><span className="rh-label">{field.label}{field.unit?` · ${field.unit}`:""}</span>{field.type==="select"?<select aria-label={field.unit?`${field.label} · ${field.unit}`:field.label} value={current[field.key]||""} onChange={(event)=>setValue(field.key,event.target.value)} className="rh-input mt-2 bg-[#061123]"><option value="">Select…</option>{field.options?.map((option)=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:<input aria-label={field.unit?`${field.label} · ${field.unit}`:field.label} type="number" min={field.min} max={field.max} step={field.step||.1} value={current[field.key]||""} onChange={(event)=>setValue(field.key,event.target.value)} className="rh-input mt-2"/>}</label>)}</div><div className="mt-6 flex flex-wrap gap-2"><button onClick={calculate} className="rh-action"><Calculator size={15} className="mr-2 inline"/>Calculate</button><button onClick={clear} className="rh-secondary"><RefreshCw size={14} className="mr-2 inline"/>Clear</button></div>{error?<div className="mt-5 rounded-2xl border border-rose-200/18 bg-rose-300/[.05] p-4 text-sm text-rose-50/75">{error}</div>:null}</div>
        <aside className="rh-hero-side"><div className="rh-kicker">03 · Primary result</div>{output?<div className="rh-result mt-4"><div className="rh-label">Result</div><div className="rh-result-value">{output.value}</div><p className="rh-result-copy">{output.interpretation}</p><div className="rh-result-source">{output.reference}</div></div>:<div className="mt-6 rounded-[26px] border border-white/10 bg-white/[.018] p-6"><div className="text-5xl font-black text-white/12">—</div><p className="mt-4 text-sm leading-6 text-cyan-100/46">Enter the required values and calculate. The result is intentionally the dominant output on this screen.</p></div>}</aside></div></section>

      <section className="rh-support-grid"><div className="rh-card is-wide"><div className="rh-label">Interpretation</div><h3 className="mt-2">What this calculator is—and is not</h3><p className="mt-3">The equation produces a transparent numerical estimate. It does not convert the result into clearance, deployability, disability, causation, or a fabricated risk score.</p></div><div className="rh-card"><div className="rh-label">Current equation</div><h3 className="mt-2">{active.label}</h3><p className="mt-3">{output?.reference || active.description}</p></div><div className="rh-card is-full is-quiet"><div className="rh-label">Decision boundary</div><p className="mt-2">Apply the current controlling medical, occupational, deployment, aviation, driver, or organizational standard separately. The calculator remains arithmetic decision support.</p></div></section>
    </div>
  </section></main>;
}
