import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, Loader2, Plus, Search, Trash2 } from "lucide-react";
import { HeaderBar } from "@/components/insight/HeaderBar";
import { Sidebar } from "@/components/insight/Sidebar";
import "./reviewer-tool-hierarchy.css";

type SavedDuty={id:string;duty:string;source:string;types:string[]};
const DUTY_KEY="insight_hub_reviewer_job_duties";

async function loadJson(url:string):Promise<any>{const response=await fetch(url,{headers:{Accept:"application/json"}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error||`Request failed (${response.status}).`);return payload;}
function dutyTypes(value:string){const text=value.toLowerCase();const values:string[]=[];if(/lift|carry|climb|stand|walk|push|pull|bend|kneel|reach|strength|endurance/.test(text))values.push("Physical");if(/decision|memory|attention|read|write|communicat|judg|assess|reason/.test(text))values.push("Cognitive");if(/chemical|heat|cold|noise|dust|fume|outdoor|weather|toxic|hazard|exposure/.test(text))values.push("Environmental");if(/drive|operat|pilot|firearm|weapon|emergency|critical|public safety|hazardous equipment/.test(text))values.push("Safety-sensitive");return values.length?values:["General"];}
function EvidenceList({title,rows=[],onAdd}:{title:string;rows?:any[];onAdd:(row:any)=>void}){return <div><div className="rh-label">Source evidence</div><h3 className="mt-2 text-base font-black">{title}</h3><div className="mt-3 max-h-[520px] space-y-2 overflow-y-auto pr-1">{rows.slice(0,40).map((row,index)=><div key={`${row.id||row.name}-${index}`} className="rounded-2xl border border-white/10 bg-white/[.022] p-3"><div className="flex gap-3"><div className="min-w-0 flex-1"><p className="text-xs font-bold leading-5">{row.name}</p>{row.description?<p className="mt-1 text-[11px] leading-5 text-cyan-100/42">{row.description}</p>:null}</div><button onClick={()=>onAdd(row)} aria-label={`Add ${row.name}`} className="h-8 w-8 shrink-0 rounded-xl border border-cyan-100/16 text-cyan-100/60 hover:text-white"><Plus size={13} className="mx-auto"/></button></div></div>)}</div></div>}

export default function ReviewerJobIntelligencePage(){
  const [query,setQuery]=useState("");
  const [profile,setProfile]=useState<any>(null);
  const [loading,setLoading]=useState(false);
  const [paste,setPaste]=useState("");
  const [duties,setDuties]=useState<SavedDuty[]>(()=>{try{return JSON.parse(localStorage.getItem(DUTY_KEY)||"[]")}catch{return[]}});
  useEffect(()=>{localStorage.setItem(DUTY_KEY,JSON.stringify(duties));},[duties]);
  const occupation=profile?.profile;
  const dutyCounts=useMemo(()=>duties.reduce<Record<string,number>>((acc,item)=>{item.types.forEach((type)=>{acc[type]=(acc[type]||0)+1});return acc;},{}),[duties]);

  async function searchJob(){if(!query.trim())return;setLoading(true);try{setProfile(await loadJson(`/api/occupational-discovery/onet/profile?keyword=${encodeURIComponent(query.trim())}`));}catch(error){setProfile({error:error instanceof Error?error.message:"O*NET unavailable."});}finally{setLoading(false);}}
  function addDuty(duty:string,source:string){const clean=duty.trim();if(!clean||duties.some((item)=>item.duty.toLowerCase()===clean.toLowerCase()))return;setDuties((current)=>[...current,{id:crypto.randomUUID(),duty:clean,source,types:dutyTypes(clean)}]);}
  function importPaste(){paste.split(/\n|•|;/).map((item)=>item.replace(/^[-*\d.)\s]+/,"").trim()).filter(Boolean).forEach((item)=>addDuty(item,"Reviewer pasted"));setPaste("");}

  return <main className="aurora-bg reviewer-native-page min-h-screen pb-24 text-white"><Sidebar/><section className="relative z-10 px-5 py-8 pt-24 lg:ml-[210px] lg:px-12 lg:pt-8"><HeaderBar eyebrow="Occupational / Job Intelligence" title="Job Intelligence" subtitle="One occupation drives O*NET evidence, task selection, and the reviewer duty workspace below."/>
    <div className="rh-stack">
      <section className="rh-primary-action"><div className="rh-kicker">01 · Occupation lookup</div><h2 className="rh-section-title">Start with the job.</h2><p className="rh-section-copy">Resolve the occupation through O*NET, then promote only the tasks and context that matter into the reviewer duty workspace.</p><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_auto]"><div className="flex items-center gap-3 rounded-2xl border border-white/16 bg-black/20 px-4"><Search size={17} className="text-cyan-100/55"/><input value={query} onChange={(event)=>setQuery(event.target.value)} onKeyDown={(event)=>event.key==="Enter"&&void searchJob()} placeholder="Aircraft mechanic, firefighter, HVAC mechanic…" className="rh-input !border-0 !bg-transparent !px-0"/></div><button onClick={()=>void searchJob()} disabled={loading||!query.trim()} className="rh-action">{loading?<Loader2 size={16} className="mr-2 inline animate-spin"/>:<Search size={16} className="mr-2 inline"/>}Search O*NET</button></div></section>

      {profile?.error?<div className="rounded-2xl border border-rose-200/18 bg-rose-300/[.05] p-4 text-sm text-rose-50/75">{profile.error}</div>:null}
      {loading?<div className="rh-primary-action text-center text-sm text-cyan-100/55"><Loader2 size={18} className="mr-2 inline animate-spin"/>Loading O*NET evidence…</div>:null}

      {occupation?<section className="rh-hero"><div className="rh-hero-grid"><div className="rh-hero-main"><div className="flex items-start justify-between gap-4"><div><div className="rh-kicker">02 · Occupation identity</div><h2 className="rh-section-title">{occupation.occupation?.title}</h2><p className="rh-section-copy">{occupation.occupation?.description}</p></div><BriefcaseBusiness className="text-cyan-100/55"/></div><div className="mt-7 grid gap-6 xl:grid-cols-2"><EvidenceList title="Tasks" rows={occupation.tasks} onAdd={(row)=>addDuty(row.name,`O*NET ${occupation.occupation?.code} · task`)}/><EvidenceList title="Work context & abilities" rows={[...(occupation.workContext||[]),...(occupation.abilities||[])]} onAdd={(row)=>addDuty(row.name,`O*NET ${occupation.occupation?.code} · evidence`)}/></div></div><aside className="rh-hero-side"><div className="rh-kicker">03 · Reviewer extraction</div><h3 className="mt-2 text-xl font-black">Promote what matters</h3><p className="mt-3 text-sm leading-6 text-cyan-100/50">Use the + controls to move individual O*NET tasks and demand evidence into the saved duty workspace. The source stays attached to each selected item.</p><div className="rh-metric-grid mt-6"><div className="rh-metric"><span>Saved duties</span><strong>{duties.length}</strong></div><div className="rh-metric"><span>O*NET code</span><strong>{occupation.occupation?.code||"—"}</strong></div></div></aside></div></section>:null}

      <section className="rh-support-grid">
        <div className="rh-card is-wide"><div className="flex items-center justify-between gap-3"><div><div className="rh-label">04 · Duty workspace</div><h3 className="mt-2">Saved job duties</h3></div><span className="rounded-full border border-cyan-100/14 px-2.5 py-1 text-[9px] font-black text-cyan-100/60">{duties.length} saved</span></div>{duties.length?<div className="mt-4 space-y-3">{duties.map((item)=><div key={item.id} className="rounded-2xl border border-white/10 bg-white/[.022] p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="text-sm font-bold">{item.duty}</p><p className="mt-1 text-[10px] text-cyan-100/38">{item.source}</p><div className="mt-2 flex flex-wrap gap-1.5">{item.types.map((type)=><span key={type} className="rounded-full border border-violet-200/14 bg-violet-300/[.05] px-2 py-1 text-[9px] font-black text-violet-50/70">{type}</span>)}</div></div><button aria-label={`Remove ${item.duty}`} onClick={()=>setDuties((current)=>current.filter((d)=>d.id!==item.id))} className="rounded-xl border border-white/10 p-2 text-cyan-100/45 hover:text-white"><Trash2 size={14}/></button></div></div>)}</div>:<p className="mt-4">Add duties from O*NET or paste a job description.</p>}</div>
        <div className="rh-card"><div className="rh-label">Duty composition</div><h3 className="mt-2">Demand signals</h3><div className="mt-4 space-y-3">{Object.keys(dutyCounts).length?Object.entries(dutyCounts).map(([type,count])=><div key={type} className="flex items-center justify-between border-b border-white/7 pb-2 text-xs"><span className="text-cyan-100/55">{type}</span><strong>{count}</strong></div>):<p>No saved-duty signals yet.</p>}</div></div>
        <div className="rh-card is-full"><div className="rh-label">05 · Paste unstructured duties</div><h3 className="mt-2">Bring in the job description</h3><textarea value={paste} onChange={(event)=>setPaste(event.target.value)} rows={7} placeholder="Paste bullets, duties, or job-description text…" className="mt-4 w-full rounded-2xl border border-white/14 bg-black/20 p-4 text-sm leading-6 outline-none placeholder:text-cyan-100/28 focus:border-cyan-100/30"/><button onClick={importPaste} disabled={!paste.trim()} className="rh-action mt-3"><Plus size={15} className="mr-2 inline"/>Add to duty workspace</button></div>
        <div className="rh-card is-full is-quiet"><div className="rh-label">Interpretation boundary</div><p className="mt-2">O*NET evidence describes occupational tasks and demands. It does not independently establish medical restrictions, causation, fitness, or disability.</p></div>
      </section>
    </div>
  </section></main>;
}
