// Normalized evidence model for the AOR Factors (Cesium) workspace.
// Every record is built from an authoritative source adapter; nothing here is
// generated by a language model. Observations are derived by deterministic rules
// and always cite evidence ids.

export type Freshness =
  | "NEAR_REAL_TIME"
  | "CURRENT_NOTICE"
  | "WEEKLY_SURVEILLANCE"
  | "CURRENT_GUIDANCE"
  | "HISTORICAL_CLIMATOLOGICAL"
  | "STRUCTURAL_DATA"
  | "STALE_CACHE";

export type GeographyLevel = "point" | "admin_region" | "multi_region" | "country" | "text_only" | "unresolved";

export type Dimension = "health_vaccines" | "malaria" | "outbreaks" | "environment" | "disasters" | "security" | "medical_access";

export type RecommendationType = "routine" | "recommended" | "selected_travelers" | "consider" | "not_routinely_recommended" | "review";
export type RequirementType = "entry_required" | "entry_required_after_transit" | "entry_required_conditional" | "not_required" | "not_evaluated";

export type SourceStatus =
  | "ok" // source answered and produced findings
  | "no_current_matching_finding" // source answered; nothing matched this country
  | "source_returned_no_data" // source answered with empty/unusable content
  | "source_unavailable" // request failed / blocked / timed out
  | "not_configured" // required credential or env var missing
  | "not_applicable"
  | "not_evaluated" // adapter not built / rule not run
  | "stale_cache"; // live failed, cached copy served

export type GeoGeometry =
  | { type: "Point"; coordinates: [number, number] }
  | { type: "Country"; iso2: string }
  | { type: "None" };

export interface EvidenceRecord {
  id: string;
  dimension: Dimension;
  category: string;
  subtype: string;
  title: string;
  summary: string;
  evidence: string; // verbatim/near-verbatim source text supporting the summary
  severity: string | null; // source-defined level label only; never a computed score
  severityLevel: number | null; // source-defined ordinal (e.g. State level 1-4), never cross-source
  recommendationType: RecommendationType | null;
  requirementType: RequirementType | null;
  sourceName: string;
  sourceUrl: string;
  publishedAt: string | null;
  updatedAt: string | null;
  retrievedAt: string;
  country: string;
  iso2: string;
  iso3: string;
  region: string | null;
  geometry: GeoGeometry;
  geographyLevel: GeographyLevel;
  geographyNote: string | null;
  freshness: Freshness;
  extra?: Record<string, unknown>;
}

export interface AdapterResult {
  sourceId: string;
  sourceName: string;
  sourceUrl: string;
  dimension: Dimension | "multi";
  status: SourceStatus;
  freshness: Freshness | null;
  retrievedAt: string;
  note: string | null;
  records: EvidenceRecord[];
}

export interface Observation {
  id: string;
  dimension: Dimension;
  headline: string;
  detail: string;
  kind: "finding" | "caveat" | "gap";
  evidenceIds: string[];
  freshness: Freshness | null;
}

export interface CountryRef {
  iso2: string;
  iso3: string;
  name: string;
  center: [number, number] | null; // [lon, lat]
  capital: string | null;
  aorRegion: string | null;
  bboxes: Array<[number, number, number, number]>;
}

export interface AdapterContext {
  country: CountryRef;
  now: () => Date;
  /** Fetch JSON from this app's own AOR routes (server-side loopback) or a fixture in tests. */
  internalJson: (path: string) => Promise<unknown>;
  /** Fetch JSON from an external URL (injected for tests). */
  externalJson: (url: string, init?: { headers?: Record<string, string>; timeoutMs?: number; method?: "GET" | "POST"; body?: unknown }) => Promise<unknown>;
  env: (key: string) => string | undefined;
}

export interface CountryIntelResponse {
  ok: true;
  country: CountryRef;
  generatedAt: string;
  whatMattersNow: {
    method: "deterministic-rules";
    /** "available" means an LLM provider key is configured and /api/aor/country-intel/synthesis can be requested. */
    llmSynthesis: "not_configured" | "available";
    summary: string;
    observations: Observation[];
  };
  sources: Array<Omit<AdapterResult, "records"> & { recordCount: number }>;
  evidence: EvidenceRecord[];
  limitations: string[];
}

export interface SynthesisStatement {
  text: string;
  /** Evidence record ids this statement rests on. Statements without valid ids are discarded. */
  evidenceIds: string[];
}

export interface SynthesisResponse {
  ok: true;
  iso2: string;
  status: "applied" | "not_configured" | "failed" | "rejected";
  model: string | null;
  generatedAt: string;
  statements: SynthesisStatement[];
  /** Statements the model proposed that the validator discarded (no valid evidence, ungrounded numbers, or label mixing). */
  discarded: number;
  note: string;
}
